#!/bin/bash

echo "Copying test...";
cp $REPOROOT/test/shire/shire_top_netlist/compare_log*.txt $testRunDir
cp $REPOROOT/test/shire/shire_top_netlist/vsrc/*.json $testRunDir

touch $testRunDir/mem_desc.txt

# and create logs dir
mkdir -p $testRunDir/logs || exit
