/* Copyright (c) 2026 Ainekko          */
/* SPDX-License-Identifier: Apache-2.0 */

// CHECKSUM %CHECKSUM%
// This file has been autogenerated. Do not edit!

#include "${module}.h"

#include <istream>
#include <ostream>

#include <spdlog/fmt/fmt.h>

#include "dispatcher.h"

% for event in events:
void trigger_${event.name}(${', '.join(  field.type.cpp + ' ' + field.name + (f"[{field.width}]" if field.width > 1 else '') for field in event.fields)} )
{
    // Compared to vcs version with unpacked structs, this much slower do the copies for each DPI
    // but verilator does not allow to pass unpacked array pointers thought DPI.
    ${module}::${event.name}_t packet_evt;
% for field in event.fields:
% if field.width > 1:    
    % for i in range(field.width):
    packet_evt.${field.name}[${i}] = ${field.name}[${i}];              
    % endfor
% else:
    packet_evt.${field.name} = ${field.name};              
% endif            
% endfor
    dispatcher::instance()->dispatch(&packet_evt);
}
% endfor

namespace ${module} {

const char* event_name(event_id id)
{
    switch (id) {
% for event in events:
    case event_id::${event.name}:
        return "${event.name}";
% endfor
    default:
        return "none";
    }
}

% for event in events:
std::string ${event.name}_t::describe() const
{
    return fmt::format(
            "${event.name}("\
% for field in event.fields[:-1]:
            ${fmt_field(field)} ", "\
% endfor
            ${fmt_field(event.fields[-1])} ")",\
% for field in event.fields[:-1]:
            ${arg_field(field)},\
% endfor
            ${arg_field(event.fields[-1])}
    );
}
% endfor

std::string event_union::describe() const
{
    switch (id) {
% for event in events:
    case event_id::${event.name}:
        return data.${event.name}.describe();
% endfor
    default:
        return "none";
    }
}

% for event in events:
template <>
const ${event.name}_t* event_union::get() const
{
    assert(id == event_id::${event.name});
    return &(data.${event.name});
}
% endfor

void handler::on(const event_union* evt)
{
    switch (evt->id) {
% for event in events:
    case event_id::${event.name}:
        this->on(evt->get<${event.name}_t>());
        break;
% endfor
    default:
        assert(0 && "invalid event");
    }
}

} // namespace ${module}

<%def name="fmt_field(field)">
% if field.width > 1:
            "${field.name}={{0:{}"
% for i in range(field.width-1):
            " ${i+1}:{}"
% endfor
            "}}"\
% else:
            "${field.name}={}"\
% endif
</%def>

<%def name="arg_field(field)">
% if field.width > 1:
% for i in range(field.width-1): 
            ${field.name}[${i}],
% endfor
            ${field.name}[${field.width-1}]\
% else:
            ${field.name}\
% endif
</%def>
