/* Copyright (c) 2026 Ainekko          */
/* SPDX-License-Identifier: Apache-2.0 */

// CHECKSUM %CHECKSUM%
// This file has been autogenerated. Do not edit!

#ifndef _${module.upper()}_
#define _${module.upper()}_

#include <stdint.h>
#include <assert.h>

#include <array>
#include <string>

#include <cereal/cereal.hpp>

namespace ${module} {

enum class event_id {
    none = 0,
% for event in events:
    ${event.name} = ${event.id},
% endfor
};

#define ${module.upper()}_FOREACH(_) \
% for event in events:
    _(${event.name}) \
% endfor


constexpr std::array<event_id, ${len(events)}> all_events = {
% for event in events:
    event_id::${event.name},
% endfor
};

const char* event_name(event_id id);

% for event in events:
struct ${event.name}_t {
    static constexpr inline ${module}::event_id event_id()
    {
        return ${module}::event_id::${event.name};
    }
    static constexpr const char* tag()
    {
% if event.tag:
        return "${event.tag}";
% else:
        return "NONE";
% endif
    }
    static constexpr const char* name()
    {
        return "${event.name}";
    }
    std::string describe() const;
    template <class Archive> void save(Archive& archive) const
    {
        archive( CEREAL_NVP(${event.fields[0].name})
% for field in event.fields[1:]:
               , CEREAL_NVP(${field.name})
% endfor
               );
    }
    template <class Archive> void load(Archive& archive)
    {
        archive( ${event.fields[0].name}
% for field in event.fields[1:]:
               , ${field.name}
% endfor
               );
    }
% for field in event.fields:
% if field.width > 1:
    ${field.type.cpp} ${field.name}[${field.width}];
% else:
    ${field.type.cpp} ${field.name};
% endif
% endfor
};
% endfor

struct event_union {
    std::string describe() const;

    template <typename EventT>
    const EventT* get() const;

    template <class Archive> void save(Archive& archive) const
    {
        archive(cereal::make_nvp("event_id", id));
        switch (id) {
% for event in events:
        case event_id::${event.name}:
            archive(cereal::make_nvp("${event.name}", data.${event.name}));
            break;
% endfor
        default:
            assert(0 && "Invalid event");
        }
    }

    template <class Archive> void load(Archive& archive)
    {
        archive(id);
        switch (id) {
% for event in events:
        case event_id::${event.name}:
            archive(data.${event.name});
            break;
% endfor
        default:
            assert(0 && "Invalid event");
        }
    }

    event_id id;
    union {
% for event in events:
        ${event.name}_t ${event.name};
% endfor
    } data;
};

struct handler {
    virtual ~handler() {}
    void on(const event_union* evt);
% for event in events:
    virtual void on(const ${event.name}_t* evt) { (void)evt; }
% endfor
};

struct hash_id {
    std::size_t operator()(const event_id& id) const
    {
        return static_cast<std::size_t>(id);
    }
};

}

extern "C" {
% for event in events:
void trigger_${event.name}(${', '.join(  field.type.cpp + ' ' + field.name + (f"[{field.width}]" if field.width > 1 else '') for field in event.fields)} );
% endfor
}

#endif // _${module.upper()}_
