#!/bin/bash

# call global post simulation script
$testPath/scripts/postTest

# check that the last write to s11 - x27 ( error count) is zero
cd $testRunDir
min=0
status=0
for thread in `seq 0 1`; do
    err=`grep "^C \+$min\.$thread.*pc=.*W\[r27"  logs/shire.commit  | tail -1 |sed s/".*W\[r27=\([0-9a-fA-F]\+\).*"/"\1"/`
    if  [ ! -z "$err" ] ; then
        err=$[0x$err]
        if [ $err != 0 ]; then
            status=1
            echo  "ERROR: found errors for thread $thread"
        else
            echo "thread $thread => OK"
        fi
    else
        echo "thread $thread not used"
    fi
done

exit $status
