// Copyright (c) 2026 Ainekko
// SPDX-License-Identifier: Apache-2.0

/* verilator lint_off IMPORTSTAR */
import dft_pkg::*;
import etlink_pkg::*;
import minion_pkg::*;
import minion_dcache_pkg::*;
import vpu_pkg::*;
import vpu_defs_pkg::*;
/* verilator lint_on IMPORTSTAR */

module cosim_txfma_f3_tb
(
  input logic ctrl_f2_clk,
  input logic ctrl_f3_clk,
  input logic [TXFMA_A3:TXFMA_B27] fa_f3a_h,
  input logic [TXFMA_A3:TXFMA_B27] fc_f3a_h,
  input logic [TXFMA_A3:0] prodsum_f3a_h,
  input logic [6:0] exp_res_f2a_h,
  input logic [5:0] ediff_abs_diff_hi_f2a_h,
  input logic [4:0] align2_rshamt_c3_f2a_h,
  input logic [1:0] op3p3spc_sel_f2a_h,
  input logic [2:0] op3p2c_sel_f2a_h,
  input logic [1:0] imxc_sel_f3a_h,
  input logic [1:0] ugfxrplc_sel_f2a_h,
  input logic [1:0] sgfxrplc_sel_f2a_h,
  input logic [1:0] icgfxc_sel_f2a_h,
  input logic [1:0] al1znp2c_sel_f2a_h,
  input logic [1:0] al2c_sel_f2a_h,
  input logic [1:0] al1p2c_sel_f2a_h,
  input logic al1p1c_sel_f2a_h,
  input logic op3p1c_sel_r_f2a_h,
  input logic op3p1c_sel_p_f2a_h,
  input logic op3g_sel_f2a_h,
  input logic op2_sxtto_g_f2a_h,
  input logic rm_rne_f2a_h,
  input logic rm_rmm_f2a_h,
  input logic frnd_rupnsc_f2a_h,
  input logic frnd_rdnsc_f2a_h,
  input logic frnd_t1_f2a_h,
  input logic frnd_t2_f2a_h,
  input logic al1c_zap_f2a_h,
  input logic op1c_log_mul_clr_f2a_h,
  input logic negop1c_int_logmul_clr_f2a_h,
  input logic psc_op1_clr_f2a_h,
  input logic align2_zap_f2a_h,
  input logic align2c_neg_f2a_h,
  input logic al2c3_neg_cin_ps_f3a_h,
  output logic orig_fround_rbit_f3a_h,
  output logic new_fround_rbit_f3a_h,
  output logic orig_prodsum_a2_f3a_h,
  output logic new_prodsum_a2_f3a_h,
  output logic orig_op2_sxtto_g_f3a_h,
  output logic new_op2_sxtto_g_f3a_h,
  output logic [TXFMA_A3:TXFMA_B47] orig_comb_s_f4a_h,
  output logic [TXFMA_A3:TXFMA_B47] new_comb_s_f4a_h,
  output logic [TXFMA_A3:TXFMA_B47] orig_comb_c_f4a_h,
  output logic [TXFMA_A3:TXFMA_B47] new_comb_c_f4a_h,
  output logic [TXFMA_A3:TXFMA_B27] orig_int_minmax_res_f4a_h,
  output logic [TXFMA_A3:TXFMA_B27] new_int_minmax_res_f4a_h
);

  txfma_f3_orig u_orig (
    .ctrl_f2_clk (ctrl_f2_clk),
    .ctrl_f3_clk (ctrl_f3_clk),
    .fa_f3a_h (fa_f3a_h),
    .fc_f3a_h (fc_f3a_h),
    .prodsum_f3a_h (prodsum_f3a_h),
    .exp_res_f2a_h (exp_res_f2a_h),
    .ediff_abs_diff_hi_f2a_h (ediff_abs_diff_hi_f2a_h),
    .align2_rshamt_c3_f2a_h (align2_rshamt_c3_f2a_h),
    .op3p3spc_sel_f2a_h (op3p3spc_sel_f2a_h),
    .op3p2c_sel_f2a_h (op3p2c_sel_f2a_h),
    .imxc_sel_f3a_h (imxc_sel_f3a_h),
    .ugfxrplc_sel_f2a_h (ugfxrplc_sel_f2a_h),
    .sgfxrplc_sel_f2a_h (sgfxrplc_sel_f2a_h),
    .icgfxc_sel_f2a_h (icgfxc_sel_f2a_h),
    .al1znp2c_sel_f2a_h (al1znp2c_sel_f2a_h),
    .al2c_sel_f2a_h (al2c_sel_f2a_h),
    .al1p2c_sel_f2a_h (al1p2c_sel_f2a_h),
    .al1p1c_sel_f2a_h (al1p1c_sel_f2a_h),
    .op3p1c_sel_r_f2a_h (op3p1c_sel_r_f2a_h),
    .op3p1c_sel_p_f2a_h (op3p1c_sel_p_f2a_h),
    .op3g_sel_f2a_h (op3g_sel_f2a_h),
    .op2_sxtto_g_f2a_h (op2_sxtto_g_f2a_h),
    .rm_rne_f2a_h (rm_rne_f2a_h),
    .rm_rmm_f2a_h (rm_rmm_f2a_h),
    .frnd_rupnsc_f2a_h (frnd_rupnsc_f2a_h),
    .frnd_rdnsc_f2a_h (frnd_rdnsc_f2a_h),
    .frnd_t1_f2a_h (frnd_t1_f2a_h),
    .frnd_t2_f2a_h (frnd_t2_f2a_h),
    .al1c_zap_f2a_h (al1c_zap_f2a_h),
    .op1c_log_mul_clr_f2a_h (op1c_log_mul_clr_f2a_h),
    .negop1c_int_logmul_clr_f2a_h (negop1c_int_logmul_clr_f2a_h),
    .psc_op1_clr_f2a_h (psc_op1_clr_f2a_h),
    .align2_zap_f2a_h (align2_zap_f2a_h),
    .align2c_neg_f2a_h (align2c_neg_f2a_h),
    .al2c3_neg_cin_ps_f3a_h (al2c3_neg_cin_ps_f3a_h),
    .fround_rbit_f3a_h (orig_fround_rbit_f3a_h),
    .prodsum_a2_f3a_h (orig_prodsum_a2_f3a_h),
    .op2_sxtto_g_f3a_h (orig_op2_sxtto_g_f3a_h),
    .comb_s_f4a_h (orig_comb_s_f4a_h),
    .comb_c_f4a_h (orig_comb_c_f4a_h),
    .int_minmax_res_f4a_h (orig_int_minmax_res_f4a_h)
  );

  txfma_f3 u_new (
    .ctrl_f2_clk (ctrl_f2_clk),
    .ctrl_f3_clk (ctrl_f3_clk),
    .fa_f3a_h (fa_f3a_h),
    .fc_f3a_h (fc_f3a_h),
    .prodsum_f3a_h (prodsum_f3a_h),
    .exp_res_f2a_h (exp_res_f2a_h),
    .ediff_abs_diff_hi_f2a_h (ediff_abs_diff_hi_f2a_h),
    .align2_rshamt_c3_f2a_h (align2_rshamt_c3_f2a_h),
    .op3p3spc_sel_f2a_h (op3p3spc_sel_f2a_h),
    .op3p2c_sel_f2a_h (op3p2c_sel_f2a_h),
    .imxc_sel_f3a_h (imxc_sel_f3a_h),
    .ugfxrplc_sel_f2a_h (ugfxrplc_sel_f2a_h),
    .sgfxrplc_sel_f2a_h (sgfxrplc_sel_f2a_h),
    .icgfxc_sel_f2a_h (icgfxc_sel_f2a_h),
    .al1znp2c_sel_f2a_h (al1znp2c_sel_f2a_h),
    .al2c_sel_f2a_h (al2c_sel_f2a_h),
    .al1p2c_sel_f2a_h (al1p2c_sel_f2a_h),
    .al1p1c_sel_f2a_h (al1p1c_sel_f2a_h),
    .op3p1c_sel_r_f2a_h (op3p1c_sel_r_f2a_h),
    .op3p1c_sel_p_f2a_h (op3p1c_sel_p_f2a_h),
    .op3g_sel_f2a_h (op3g_sel_f2a_h),
    .op2_sxtto_g_f2a_h (op2_sxtto_g_f2a_h),
    .rm_rne_f2a_h (rm_rne_f2a_h),
    .rm_rmm_f2a_h (rm_rmm_f2a_h),
    .frnd_rupnsc_f2a_h (frnd_rupnsc_f2a_h),
    .frnd_rdnsc_f2a_h (frnd_rdnsc_f2a_h),
    .frnd_t1_f2a_h (frnd_t1_f2a_h),
    .frnd_t2_f2a_h (frnd_t2_f2a_h),
    .al1c_zap_f2a_h (al1c_zap_f2a_h),
    .op1c_log_mul_clr_f2a_h (op1c_log_mul_clr_f2a_h),
    .negop1c_int_logmul_clr_f2a_h (negop1c_int_logmul_clr_f2a_h),
    .psc_op1_clr_f2a_h (psc_op1_clr_f2a_h),
    .align2_zap_f2a_h (align2_zap_f2a_h),
    .align2c_neg_f2a_h (align2c_neg_f2a_h),
    .al2c3_neg_cin_ps_f3a_h (al2c3_neg_cin_ps_f3a_h),
    .fround_rbit_f3a_h (new_fround_rbit_f3a_h),
    .prodsum_a2_f3a_h (new_prodsum_a2_f3a_h),
    .op2_sxtto_g_f3a_h (new_op2_sxtto_g_f3a_h),
    .comb_s_f4a_h (new_comb_s_f4a_h),
    .comb_c_f4a_h (new_comb_c_f4a_h),
    .int_minmax_res_f4a_h (new_int_minmax_res_f4a_h)
  );

endmodule : cosim_txfma_f3_tb
