/* Copyright (c) 2026 Ainekko          */
/* SPDX-License-Identifier: Apache-2.0 */

// CHECKSUM 1bd7531bb85db283dfe043a792cae329
// This file has been autogenerated. Do not edit!

#ifndef _COSIM_EVT_
#define _COSIM_EVT_

#include <assert.h>
#include <stdint.h>

#include <array>
#include <string>

#include <cereal/cereal.hpp>

namespace cosim_evt {

enum class event_id {
    none = 0,
    inst_retire = 1,
    inst_exception = 2,
    inst_interrupt = 3,
    delayed_write_int = 4,
    flb_update = 5,
    load_miss_bus_err = 6,
    delayed_store = 7,
    update_fcsr_flags = 8,
    delayed_write_fp = 9,
    vpu_rf_update = 10,
    delayed_write_rm = 11,
    ipi_received = 12,
    tensorfma_write = 13,
    tensorfma_write8 = 14,
    tensorquant_write = 15,
    reduce_write = 16,
    tensorstore_write = 17,
    tensorfma_done = 18,
    tensorquant_done = 19,
    reduce_done = 20,
    tensorstore_done = 21,
    tl_mon_op_start = 22,
    tl_mon_process_busy = 23,
    tl_mon_process_req = 24,
    tl_mon_process_resp = 25,
    tl_mon_process_trans_data_xfer = 26,
    tl_mon_process_tenb_flush = 27,
    esr_write = 28,
    icache_prefetch_done = 29,
    warm_reset = 30,
    clear_interrupt = 31,
};

#define COSIM_EVT_FOREACH(_)                                                                                           \
    _(inst_retire)                                                                                                     \
    _(inst_exception) _(inst_interrupt) _(delayed_write_int) _(flb_update) _(load_miss_bus_err) _(delayed_store)       \
        _(update_fcsr_flags) _(delayed_write_fp) _(vpu_rf_update) _(delayed_write_rm) _(ipi_received)                  \
            _(tensorfma_write) _(tensorfma_write8) _(tensorquant_write) _(reduce_write) _(tensorstore_write)           \
                _(tensorfma_done) _(tensorquant_done) _(reduce_done) _(tensorstore_done) _(tl_mon_op_start)            \
                    _(tl_mon_process_busy) _(tl_mon_process_req) _(tl_mon_process_resp)                                \
                        _(tl_mon_process_trans_data_xfer) _(tl_mon_process_tenb_flush) _(esr_write)                    \
                            _(icache_prefetch_done) _(warm_reset) _(clear_interrupt)

constexpr std::array<event_id, 31> all_events = {
    event_id::inst_retire,
    event_id::inst_exception,
    event_id::inst_interrupt,
    event_id::delayed_write_int,
    event_id::flb_update,
    event_id::load_miss_bus_err,
    event_id::delayed_store,
    event_id::update_fcsr_flags,
    event_id::delayed_write_fp,
    event_id::vpu_rf_update,
    event_id::delayed_write_rm,
    event_id::ipi_received,
    event_id::tensorfma_write,
    event_id::tensorfma_write8,
    event_id::tensorquant_write,
    event_id::reduce_write,
    event_id::tensorstore_write,
    event_id::tensorfma_done,
    event_id::tensorquant_done,
    event_id::reduce_done,
    event_id::tensorstore_done,
    event_id::tl_mon_op_start,
    event_id::tl_mon_process_busy,
    event_id::tl_mon_process_req,
    event_id::tl_mon_process_resp,
    event_id::tl_mon_process_trans_data_xfer,
    event_id::tl_mon_process_tenb_flush,
    event_id::esr_write,
    event_id::icache_prefetch_done,
    event_id::warm_reset,
    event_id::clear_interrupt,
};

const char* event_name(event_id id);

struct inst_retire_t {
    static constexpr inline cosim_evt::event_id event_id() { return cosim_evt::event_id::inst_retire; }
    static constexpr const char* tag() { return "RET"; }
    static constexpr const char* name() { return "inst_retire"; }
    std::string describe() const;
    template <class Archive>
    void save(Archive& archive) const
    {
        archive(CEREAL_NVP(cycle), CEREAL_NVP(minion_id), CEREAL_NVP(thread_id), CEREAL_NVP(pc), CEREAL_NVP(inst_bits),
                CEREAL_NVP(delayed_write), CEREAL_NVP(load_miss), CEREAL_NVP(wbx), CEREAL_NVP(wbx_rd),
                CEREAL_NVP(wbx_data), CEREAL_NVP(wbf), CEREAL_NVP(wbf_rd), CEREAL_NVP(wbm), CEREAL_NVP(wbmall),
                CEREAL_NVP(wbm_rd), CEREAL_NVP(wbm_data), CEREAL_NVP(store), CEREAL_NVP(store_size),
                CEREAL_NVP(store_addr), CEREAL_NVP(store_data), CEREAL_NVP(store_mask), CEREAL_NVP(delayed_store),
                CEREAL_NVP(store_age_id), CEREAL_NVP(scatter), CEREAL_NVP(scatter_addr), CEREAL_NVP(scatter_data),
                CEREAL_NVP(tex_send), CEREAL_NVP(tex_rcv), CEREAL_NVP(tensor_load), CEREAL_NVP(tenb),
                CEREAL_NVP(tensor_load_num_lines), CEREAL_NVP(tensor_fma), CEREAL_NVP(tensor_quant), CEREAL_NVP(reduce),
                CEREAL_NVP(tensor_store), CEREAL_NVP(flb_valid), CEREAL_NVP(flb_idx), CEREAL_NVP(flb_range),
                CEREAL_NVP(wflags), CEREAL_NVP(trans_id), CEREAL_NVP(prv));
    }
    template <class Archive>
    void load(Archive& archive)
    {
        archive(cycle, minion_id, thread_id, pc, inst_bits, delayed_write, load_miss, wbx, wbx_rd, wbx_data, wbf,
                wbf_rd, wbm, wbmall, wbm_rd, wbm_data, store, store_size, store_addr, store_data, store_mask,
                delayed_store, store_age_id, scatter, scatter_addr, scatter_data, tex_send, tex_rcv, tensor_load, tenb,
                tensor_load_num_lines, tensor_fma, tensor_quant, reduce, tensor_store, flb_valid, flb_idx, flb_range,
                wflags, trans_id, prv);
    }
    uint64_t cycle;
    uint32_t minion_id;
    uint8_t thread_id;
    uint64_t pc;
    uint32_t inst_bits;
    bool delayed_write;
    bool load_miss;
    bool wbx;
    uint32_t wbx_rd;
    uint64_t wbx_data;
    bool wbf;
    uint32_t wbf_rd;
    bool wbm;
    bool wbmall;
    uint32_t wbm_rd;
    uint64_t wbm_data;
    bool store;
    uint32_t store_size;
    uint64_t store_addr;
    uint64_t store_data[4];
    uint32_t store_mask;
    bool delayed_store;
    uint32_t store_age_id;
    bool scatter;
    uint64_t scatter_addr[8];
    uint32_t scatter_data[8];
    bool tex_send;
    bool tex_rcv;
    bool tensor_load;
    bool tenb;
    uint32_t tensor_load_num_lines;
    bool tensor_fma;
    bool tensor_quant;
    bool reduce;
    bool tensor_store;
    bool flb_valid;
    uint32_t flb_idx;
    uint32_t flb_range;
    bool wflags;
    uint32_t trans_id;
    uint32_t prv;
};
struct inst_exception_t {
    static constexpr inline cosim_evt::event_id event_id() { return cosim_evt::event_id::inst_exception; }
    static constexpr const char* tag() { return "XCPT"; }
    static constexpr const char* name() { return "inst_exception"; }
    std::string describe() const;
    template <class Archive>
    void save(Archive& archive) const
    {
        archive(CEREAL_NVP(cycle), CEREAL_NVP(minion_id), CEREAL_NVP(thread_id), CEREAL_NVP(pc), CEREAL_NVP(inst_bits),
                CEREAL_NVP(wbf_rd), CEREAL_NVP(is_store), CEREAL_NVP(is_atomic), CEREAL_NVP(is_gsc),
                CEREAL_NVP(scatter_addr), CEREAL_NVP(scatter_data), CEREAL_NVP(store_mask), CEREAL_NVP(gsc_size),
                CEREAL_NVP(gsc_progress), CEREAL_NVP(mstatus), CEREAL_NVP(cause), CEREAL_NVP(tval), CEREAL_NVP(epc),
                CEREAL_NVP(mip), CEREAL_NVP(prv));
    }
    template <class Archive>
    void load(Archive& archive)
    {
        archive(cycle, minion_id, thread_id, pc, inst_bits, wbf_rd, is_store, is_atomic, is_gsc, scatter_addr,
                scatter_data, store_mask, gsc_size, gsc_progress, mstatus, cause, tval, epc, mip, prv);
    }
    uint64_t cycle;
    uint32_t minion_id;
    uint8_t thread_id;
    uint64_t pc;
    uint32_t inst_bits;
    uint32_t wbf_rd;
    bool is_store;
    bool is_atomic;
    bool is_gsc;
    uint64_t scatter_addr[8];
    uint32_t scatter_data[8];
    uint32_t store_mask;
    uint32_t gsc_size;
    uint32_t gsc_progress;
    uint64_t mstatus;
    uint64_t cause;
    uint64_t tval;
    uint64_t epc;
    uint64_t mip;
    uint32_t prv;
};
struct inst_interrupt_t {
    static constexpr inline cosim_evt::event_id event_id() { return cosim_evt::event_id::inst_interrupt; }
    static constexpr const char* tag() { return "INT"; }
    static constexpr const char* name() { return "inst_interrupt"; }
    std::string describe() const;
    template <class Archive>
    void save(Archive& archive) const
    {
        archive(CEREAL_NVP(cycle), CEREAL_NVP(minion_id), CEREAL_NVP(thread_id), CEREAL_NVP(pc), CEREAL_NVP(inst_bits),
                CEREAL_NVP(is_gsc), CEREAL_NVP(gsc_progress), CEREAL_NVP(mstatus), CEREAL_NVP(cause), CEREAL_NVP(tval),
                CEREAL_NVP(epc), CEREAL_NVP(mip), CEREAL_NVP(bus_error_addr), CEREAL_NVP(bus_error_pc),
                CEREAL_NVP(prv));
    }
    template <class Archive>
    void load(Archive& archive)
    {
        archive(cycle, minion_id, thread_id, pc, inst_bits, is_gsc, gsc_progress, mstatus, cause, tval, epc, mip,
                bus_error_addr, bus_error_pc, prv);
    }
    uint64_t cycle;
    uint32_t minion_id;
    uint8_t thread_id;
    uint64_t pc;
    uint32_t inst_bits;
    bool is_gsc;
    uint32_t gsc_progress;
    uint64_t mstatus;
    uint64_t cause;
    uint64_t tval;
    uint64_t epc;
    uint64_t mip;
    uint64_t bus_error_addr;
    uint64_t bus_error_pc;
    uint32_t prv;
};
struct delayed_write_int_t {
    static constexpr inline cosim_evt::event_id event_id() { return cosim_evt::event_id::delayed_write_int; }
    static constexpr const char* tag() { return "XREG"; }
    static constexpr const char* name() { return "delayed_write_int"; }
    std::string describe() const;
    template <class Archive>
    void save(Archive& archive) const
    {
        archive(CEREAL_NVP(cycle), CEREAL_NVP(minion_id), CEREAL_NVP(thread_id), CEREAL_NVP(wbx_rd),
                CEREAL_NVP(wbx_data));
    }
    template <class Archive>
    void load(Archive& archive)
    {
        archive(cycle, minion_id, thread_id, wbx_rd, wbx_data);
    }
    uint64_t cycle;
    uint32_t minion_id;
    uint8_t thread_id;
    uint32_t wbx_rd;
    uint64_t wbx_data;
};
struct flb_update_t {
    static constexpr inline cosim_evt::event_id event_id() { return cosim_evt::event_id::flb_update; }
    static constexpr const char* tag() { return "FLB"; }
    static constexpr const char* name() { return "flb_update"; }
    std::string describe() const;
    template <class Archive>
    void save(Archive& archive) const
    {
        archive(CEREAL_NVP(cycle), CEREAL_NVP(minion_id), CEREAL_NVP(thread_id), CEREAL_NVP(wbx_rd),
                CEREAL_NVP(wbx_data));
    }
    template <class Archive>
    void load(Archive& archive)
    {
        archive(cycle, minion_id, thread_id, wbx_rd, wbx_data);
    }
    uint64_t cycle;
    uint32_t minion_id;
    uint8_t thread_id;
    uint32_t wbx_rd;
    uint64_t wbx_data;
};
struct load_miss_bus_err_t {
    static constexpr inline cosim_evt::event_id event_id() { return cosim_evt::event_id::load_miss_bus_err; }
    static constexpr const char* tag() { return "BUS"; }
    static constexpr const char* name() { return "load_miss_bus_err"; }
    std::string describe() const;
    template <class Archive>
    void save(Archive& archive) const
    {
        archive(CEREAL_NVP(cycle), CEREAL_NVP(minion_id), CEREAL_NVP(pc), CEREAL_NVP(thread_id),
                CEREAL_NVP(bus_error_addr));
    }
    template <class Archive>
    void load(Archive& archive)
    {
        archive(cycle, minion_id, pc, thread_id, bus_error_addr);
    }
    uint64_t cycle;
    uint32_t minion_id;
    uint64_t pc;
    uint8_t thread_id;
    uint64_t bus_error_addr;
};
struct delayed_store_t {
    static constexpr inline cosim_evt::event_id event_id() { return cosim_evt::event_id::delayed_store; }
    static constexpr const char* tag() { return "ST"; }
    static constexpr const char* name() { return "delayed_store"; }
    std::string describe() const;
    template <class Archive>
    void save(Archive& archive) const
    {
        archive(CEREAL_NVP(cycle), CEREAL_NVP(minion_id), CEREAL_NVP(thread_id), CEREAL_NVP(scatter),
                CEREAL_NVP(scatter_cnt), CEREAL_NVP(store_size), CEREAL_NVP(store_data), CEREAL_NVP(store_age_id));
    }
    template <class Archive>
    void load(Archive& archive)
    {
        archive(cycle, minion_id, thread_id, scatter, scatter_cnt, store_size, store_data, store_age_id);
    }
    uint64_t cycle;
    uint32_t minion_id;
    uint8_t thread_id;
    bool scatter;
    uint32_t scatter_cnt;
    uint32_t store_size;
    uint64_t store_data[4];
    uint32_t store_age_id;
};
struct update_fcsr_flags_t {
    static constexpr inline cosim_evt::event_id event_id() { return cosim_evt::event_id::update_fcsr_flags; }
    static constexpr const char* tag() { return "FCSR"; }
    static constexpr const char* name() { return "update_fcsr_flags"; }
    std::string describe() const;
    template <class Archive>
    void save(Archive& archive) const
    {
        archive(CEREAL_NVP(cycle), CEREAL_NVP(minion_id), CEREAL_NVP(thread_id), CEREAL_NVP(flags),
                CEREAL_NVP(trans_id));
    }
    template <class Archive>
    void load(Archive& archive)
    {
        archive(cycle, minion_id, thread_id, flags, trans_id);
    }
    uint64_t cycle;
    uint32_t minion_id;
    uint8_t thread_id;
    uint32_t flags;
    uint32_t trans_id;
};
struct delayed_write_fp_t {
    static constexpr inline cosim_evt::event_id event_id() { return cosim_evt::event_id::delayed_write_fp; }
    static constexpr const char* tag() { return "FP"; }
    static constexpr const char* name() { return "delayed_write_fp"; }
    std::string describe() const;
    template <class Archive>
    void save(Archive& archive) const
    {
        archive(CEREAL_NVP(cycle), CEREAL_NVP(minion_id), CEREAL_NVP(thread_id), CEREAL_NVP(wbf_rd),
                CEREAL_NVP(entry_point_id));
    }
    template <class Archive>
    void load(Archive& archive)
    {
        archive(cycle, minion_id, thread_id, wbf_rd, entry_point_id);
    }
    uint64_t cycle;
    uint32_t minion_id;
    uint8_t thread_id;
    uint32_t wbf_rd;
    uint32_t entry_point_id;
};
struct vpu_rf_update_t {
    static constexpr inline cosim_evt::event_id event_id() { return cosim_evt::event_id::vpu_rf_update; }
    static constexpr const char* tag() { return "VPU"; }
    static constexpr const char* name() { return "vpu_rf_update"; }
    std::string describe() const;
    template <class Archive>
    void save(Archive& archive) const
    {
        archive(CEREAL_NVP(cycle), CEREAL_NVP(minion_id), CEREAL_NVP(wr_mask), CEREAL_NVP(thread_ids), CEREAL_NVP(addr),
                CEREAL_NVP(data));
    }
    template <class Archive>
    void load(Archive& archive)
    {
        archive(cycle, minion_id, wr_mask, thread_ids, addr, data);
    }
    uint64_t cycle;
    uint32_t minion_id;
    uint32_t wr_mask;
    uint32_t thread_ids;
    uint8_t addr[8];
    uint32_t data[8];
};
struct delayed_write_rm_t {
    static constexpr inline cosim_evt::event_id event_id() { return cosim_evt::event_id::delayed_write_rm; }
    static constexpr const char* tag() { return "MASK"; }
    static constexpr const char* name() { return "delayed_write_rm"; }
    std::string describe() const;
    template <class Archive>
    void save(Archive& archive) const
    {
        archive(CEREAL_NVP(cycle), CEREAL_NVP(minion_id), CEREAL_NVP(thread_id), CEREAL_NVP(wbmall), CEREAL_NVP(wbm_rd),
                CEREAL_NVP(wbm_data));
    }
    template <class Archive>
    void load(Archive& archive)
    {
        archive(cycle, minion_id, thread_id, wbmall, wbm_rd, wbm_data);
    }
    uint64_t cycle;
    uint32_t minion_id;
    uint8_t thread_id;
    bool wbmall;
    uint32_t wbm_rd;
    uint64_t wbm_data;
};
struct ipi_received_t {
    static constexpr inline cosim_evt::event_id event_id() { return cosim_evt::event_id::ipi_received; }
    static constexpr const char* tag() { return "IPI"; }
    static constexpr const char* name() { return "ipi_received"; }
    std::string describe() const;
    template <class Archive>
    void save(Archive& archive) const
    {
        archive(CEREAL_NVP(cycle), CEREAL_NVP(minion_id), CEREAL_NVP(thread_id), CEREAL_NVP(pc));
    }
    template <class Archive>
    void load(Archive& archive)
    {
        archive(cycle, minion_id, thread_id, pc);
    }
    uint64_t cycle;
    uint32_t minion_id;
    uint8_t thread_id;
    uint64_t pc;
};
struct tensorfma_write_t {
    static constexpr inline cosim_evt::event_id event_id() { return cosim_evt::event_id::tensorfma_write; }
    static constexpr const char* tag() { return "TFMA"; }
    static constexpr const char* name() { return "tensorfma_write"; }
    std::string describe() const;
    template <class Archive>
    void save(Archive& archive) const
    {
        archive(CEREAL_NVP(cycle), CEREAL_NVP(minion_id), CEREAL_NVP(entry), CEREAL_NVP(wmask));
    }
    template <class Archive>
    void load(Archive& archive)
    {
        archive(cycle, minion_id, entry, wmask);
    }
    uint64_t cycle;
    uint32_t minion_id;
    int32_t entry;
    uint32_t wmask;
};
struct tensorfma_write8_t {
    static constexpr inline cosim_evt::event_id event_id() { return cosim_evt::event_id::tensorfma_write8; }
    static constexpr const char* tag() { return "TFMA"; }
    static constexpr const char* name() { return "tensorfma_write8"; }
    std::string describe() const;
    template <class Archive>
    void save(Archive& archive) const
    {
        archive(CEREAL_NVP(cycle), CEREAL_NVP(minion_id), CEREAL_NVP(entry), CEREAL_NVP(data), CEREAL_NVP(wmask));
    }
    template <class Archive>
    void load(Archive& archive)
    {
        archive(cycle, minion_id, entry, data, wmask);
    }
    uint64_t cycle;
    uint32_t minion_id;
    int32_t entry;
    uint32_t data[8];
    uint32_t wmask;
};
struct tensorquant_write_t {
    static constexpr inline cosim_evt::event_id event_id() { return cosim_evt::event_id::tensorquant_write; }
    static constexpr const char* tag() { return "TQ"; }
    static constexpr const char* name() { return "tensorquant_write"; }
    std::string describe() const;
    template <class Archive>
    void save(Archive& archive) const
    {
        archive(CEREAL_NVP(cycle), CEREAL_NVP(minion_id), CEREAL_NVP(entry), CEREAL_NVP(wmask));
    }
    template <class Archive>
    void load(Archive& archive)
    {
        archive(cycle, minion_id, entry, wmask);
    }
    uint64_t cycle;
    uint32_t minion_id;
    int32_t entry;
    uint32_t wmask;
};
struct reduce_write_t {
    static constexpr inline cosim_evt::event_id event_id() { return cosim_evt::event_id::reduce_write; }
    static constexpr const char* tag() { return "RED"; }
    static constexpr const char* name() { return "reduce_write"; }
    std::string describe() const;
    template <class Archive>
    void save(Archive& archive) const
    {
        archive(CEREAL_NVP(cycle), CEREAL_NVP(minion_id), CEREAL_NVP(entry));
    }
    template <class Archive>
    void load(Archive& archive)
    {
        archive(cycle, minion_id, entry);
    }
    uint64_t cycle;
    uint32_t minion_id;
    int32_t entry;
};
struct tensorstore_write_t {
    static constexpr inline cosim_evt::event_id event_id() { return cosim_evt::event_id::tensorstore_write; }
    static constexpr const char* tag() { return "TS"; }
    static constexpr const char* name() { return "tensorstore_write"; }
    std::string describe() const;
    template <class Archive>
    void save(Archive& archive) const
    {
        archive(CEREAL_NVP(cycle), CEREAL_NVP(minion_id), CEREAL_NVP(is_256_bit), CEREAL_NVP(addr), CEREAL_NVP(data),
                CEREAL_NVP(size), CEREAL_NVP(qwen), CEREAL_NVP(subcode), CEREAL_NVP(coop));
    }
    template <class Archive>
    void load(Archive& archive)
    {
        archive(cycle, minion_id, is_256_bit, addr, data, size, qwen, subcode, coop);
    }
    uint64_t cycle;
    uint32_t minion_id;
    bool is_256_bit;
    uint64_t addr;
    uint32_t data[16];
    uint8_t size;
    uint8_t qwen;
    uint8_t subcode;
    uint8_t coop;
};
struct tensorfma_done_t {
    static constexpr inline cosim_evt::event_id event_id() { return cosim_evt::event_id::tensorfma_done; }
    static constexpr const char* tag() { return "TFMA"; }
    static constexpr const char* name() { return "tensorfma_done"; }
    std::string describe() const;
    template <class Archive>
    void save(Archive& archive) const
    {
        archive(CEREAL_NVP(cycle), CEREAL_NVP(minion_id));
    }
    template <class Archive>
    void load(Archive& archive)
    {
        archive(cycle, minion_id);
    }
    uint64_t cycle;
    uint32_t minion_id;
};
struct tensorquant_done_t {
    static constexpr inline cosim_evt::event_id event_id() { return cosim_evt::event_id::tensorquant_done; }
    static constexpr const char* tag() { return "TQ"; }
    static constexpr const char* name() { return "tensorquant_done"; }
    std::string describe() const;
    template <class Archive>
    void save(Archive& archive) const
    {
        archive(CEREAL_NVP(cycle), CEREAL_NVP(minion_id));
    }
    template <class Archive>
    void load(Archive& archive)
    {
        archive(cycle, minion_id);
    }
    uint64_t cycle;
    uint32_t minion_id;
};
struct reduce_done_t {
    static constexpr inline cosim_evt::event_id event_id() { return cosim_evt::event_id::reduce_done; }
    static constexpr const char* tag() { return "RED"; }
    static constexpr const char* name() { return "reduce_done"; }
    std::string describe() const;
    template <class Archive>
    void save(Archive& archive) const
    {
        archive(CEREAL_NVP(cycle), CEREAL_NVP(minion_id), CEREAL_NVP(action), CEREAL_NVP(partner_minion_id),
                CEREAL_NVP(operation), CEREAL_NVP(zero_reg_reduce), CEREAL_NVP(auto_pair), CEREAL_NVP(level));
    }
    template <class Archive>
    void load(Archive& archive)
    {
        archive(cycle, minion_id, action, partner_minion_id, operation, zero_reg_reduce, auto_pair, level);
    }
    uint64_t cycle;
    uint32_t minion_id;
    uint8_t action;
    uint32_t partner_minion_id;
    uint8_t operation;
    bool zero_reg_reduce;
    bool auto_pair;
    uint8_t level;
};
struct tensorstore_done_t {
    static constexpr inline cosim_evt::event_id event_id() { return cosim_evt::event_id::tensorstore_done; }
    static constexpr const char* tag() { return "TS"; }
    static constexpr const char* name() { return "tensorstore_done"; }
    std::string describe() const;
    template <class Archive>
    void save(Archive& archive) const
    {
        archive(CEREAL_NVP(cycle), CEREAL_NVP(minion_id), CEREAL_NVP(coop));
    }
    template <class Archive>
    void load(Archive& archive)
    {
        archive(cycle, minion_id, coop);
    }
    uint64_t cycle;
    uint32_t minion_id;
    uint8_t coop;
};
struct tl_mon_op_start_t {
    static constexpr inline cosim_evt::event_id event_id() { return cosim_evt::event_id::tl_mon_op_start; }
    static constexpr const char* tag() { return "TL"; }
    static constexpr const char* name() { return "tl_mon_op_start"; }
    std::string describe() const;
    template <class Archive>
    void save(Archive& archive) const
    {
        archive(CEREAL_NVP(cycle), CEREAL_NVP(minion_id), CEREAL_NVP(tl_module), CEREAL_NVP(transform),
                CEREAL_NVP(num_lines));
    }
    template <class Archive>
    void load(Archive& archive)
    {
        archive(cycle, minion_id, tl_module, transform, num_lines);
    }
    uint64_t cycle;
    uint32_t minion_id;
    uint32_t tl_module;
    uint32_t transform;
    uint32_t num_lines;
};
struct tl_mon_process_busy_t {
    static constexpr inline cosim_evt::event_id event_id() { return cosim_evt::event_id::tl_mon_process_busy; }
    static constexpr const char* tag() { return "TL"; }
    static constexpr const char* name() { return "tl_mon_process_busy"; }
    std::string describe() const;
    template <class Archive>
    void save(Archive& archive) const
    {
        archive(CEREAL_NVP(cycle), CEREAL_NVP(minion_id), CEREAL_NVP(tl_module), CEREAL_NVP(state));
    }
    template <class Archive>
    void load(Archive& archive)
    {
        archive(cycle, minion_id, tl_module, state);
    }
    uint64_t cycle;
    uint32_t minion_id;
    int32_t tl_module;
    int32_t state;
};
struct tl_mon_process_req_t {
    static constexpr inline cosim_evt::event_id event_id() { return cosim_evt::event_id::tl_mon_process_req; }
    static constexpr const char* tag() { return "TL"; }
    static constexpr const char* name() { return "tl_mon_process_req"; }
    std::string describe() const;
    template <class Archive>
    void save(Archive& archive) const
    {
        archive(CEREAL_NVP(cycle), CEREAL_NVP(minion_id), CEREAL_NVP(tl_module), CEREAL_NVP(req_id_idx));
    }
    template <class Archive>
    void load(Archive& archive)
    {
        archive(cycle, minion_id, tl_module, req_id_idx);
    }
    uint64_t cycle;
    uint32_t minion_id;
    int32_t tl_module;
    int32_t req_id_idx;
};
struct tl_mon_process_resp_t {
    static constexpr inline cosim_evt::event_id event_id() { return cosim_evt::event_id::tl_mon_process_resp; }
    static constexpr const char* tag() { return "TL"; }
    static constexpr const char* name() { return "tl_mon_process_resp"; }
    std::string describe() const;
    template <class Archive>
    void save(Archive& archive) const
    {
        archive(CEREAL_NVP(cycle), CEREAL_NVP(minion_id), CEREAL_NVP(tl_module), CEREAL_NVP(resp_id_idx),
                CEREAL_NVP(entry), CEREAL_NVP(data));
    }
    template <class Archive>
    void load(Archive& archive)
    {
        archive(cycle, minion_id, tl_module, resp_id_idx, entry, data);
    }
    uint64_t cycle;
    uint32_t minion_id;
    int32_t tl_module;
    int32_t resp_id_idx;
    int32_t entry;
    uint64_t data[4];
};
struct tl_mon_process_trans_data_xfer_t {
    static constexpr inline cosim_evt::event_id event_id()
    {
        return cosim_evt::event_id::tl_mon_process_trans_data_xfer;
    }
    static constexpr const char* tag() { return "TL"; }
    static constexpr const char* name() { return "tl_mon_process_trans_data_xfer"; }
    std::string describe() const;
    template <class Archive>
    void save(Archive& archive) const
    {
        archive(CEREAL_NVP(cycle), CEREAL_NVP(minion_id), CEREAL_NVP(entry), CEREAL_NVP(banks), CEREAL_NVP(data));
    }
    template <class Archive>
    void load(Archive& archive)
    {
        archive(cycle, minion_id, entry, banks, data);
    }
    uint64_t cycle;
    uint32_t minion_id;
    int32_t entry;
    int32_t banks;
    uint64_t data[4];
};
struct tl_mon_process_tenb_flush_t {
    static constexpr inline cosim_evt::event_id event_id() { return cosim_evt::event_id::tl_mon_process_tenb_flush; }
    static constexpr const char* tag() { return "TL"; }
    static constexpr const char* name() { return "tl_mon_process_tenb_flush"; }
    std::string describe() const;
    template <class Archive>
    void save(Archive& archive) const
    {
        archive(CEREAL_NVP(cycle), CEREAL_NVP(minion_id));
    }
    template <class Archive>
    void load(Archive& archive)
    {
        archive(cycle, minion_id);
    }
    uint64_t cycle;
    uint32_t minion_id;
};
struct esr_write_t {
    static constexpr inline cosim_evt::event_id event_id() { return cosim_evt::event_id::esr_write; }
    static constexpr const char* tag() { return "ESR"; }
    static constexpr const char* name() { return "esr_write"; }
    std::string describe() const;
    template <class Archive>
    void save(Archive& archive) const
    {
        archive(CEREAL_NVP(addr), CEREAL_NVP(data));
    }
    template <class Archive>
    void load(Archive& archive)
    {
        archive(addr, data);
    }
    uint64_t addr;
    uint64_t data;
};
struct icache_prefetch_done_t {
    static constexpr inline cosim_evt::event_id event_id() { return cosim_evt::event_id::icache_prefetch_done; }
    static constexpr const char* tag() { return "PREF"; }
    static constexpr const char* name() { return "icache_prefetch_done"; }
    std::string describe() const;
    template <class Archive>
    void save(Archive& archive) const
    {
        archive(CEREAL_NVP(shire_id));
    }
    template <class Archive>
    void load(Archive& archive)
    {
        archive(shire_id);
    }
    uint32_t shire_id;
};
struct warm_reset_t {
    static constexpr inline cosim_evt::event_id event_id() { return cosim_evt::event_id::warm_reset; }
    static constexpr const char* tag() { return "RST"; }
    static constexpr const char* name() { return "warm_reset"; }
    std::string describe() const;
    template <class Archive>
    void save(Archive& archive) const
    {
        archive(CEREAL_NVP(cycle), CEREAL_NVP(minion_id));
    }
    template <class Archive>
    void load(Archive& archive)
    {
        archive(cycle, minion_id);
    }
    uint64_t cycle;
    uint32_t minion_id;
};
struct clear_interrupt_t {
    static constexpr inline cosim_evt::event_id event_id() { return cosim_evt::event_id::clear_interrupt; }
    static constexpr const char* tag() { return "CLR"; }
    static constexpr const char* name() { return "clear_interrupt"; }
    std::string describe() const;
    template <class Archive>
    void save(Archive& archive) const
    {
        archive(CEREAL_NVP(cycle), CEREAL_NVP(minion_id), CEREAL_NVP(thread_id), CEREAL_NVP(mip));
    }
    template <class Archive>
    void load(Archive& archive)
    {
        archive(cycle, minion_id, thread_id, mip);
    }
    uint64_t cycle;
    uint32_t minion_id;
    uint8_t thread_id;
    uint32_t mip;
};

struct event_union {
    std::string describe() const;

    template <typename EventT>
    const EventT* get() const;

    template <class Archive>
    void save(Archive& archive) const
    {
        archive(cereal::make_nvp("event_id", id));
        switch (id) {
        case event_id::inst_retire:
            archive(cereal::make_nvp("inst_retire", data.inst_retire));
            break;
        case event_id::inst_exception:
            archive(cereal::make_nvp("inst_exception", data.inst_exception));
            break;
        case event_id::inst_interrupt:
            archive(cereal::make_nvp("inst_interrupt", data.inst_interrupt));
            break;
        case event_id::delayed_write_int:
            archive(cereal::make_nvp("delayed_write_int", data.delayed_write_int));
            break;
        case event_id::flb_update:
            archive(cereal::make_nvp("flb_update", data.flb_update));
            break;
        case event_id::load_miss_bus_err:
            archive(cereal::make_nvp("load_miss_bus_err", data.load_miss_bus_err));
            break;
        case event_id::delayed_store:
            archive(cereal::make_nvp("delayed_store", data.delayed_store));
            break;
        case event_id::update_fcsr_flags:
            archive(cereal::make_nvp("update_fcsr_flags", data.update_fcsr_flags));
            break;
        case event_id::delayed_write_fp:
            archive(cereal::make_nvp("delayed_write_fp", data.delayed_write_fp));
            break;
        case event_id::vpu_rf_update:
            archive(cereal::make_nvp("vpu_rf_update", data.vpu_rf_update));
            break;
        case event_id::delayed_write_rm:
            archive(cereal::make_nvp("delayed_write_rm", data.delayed_write_rm));
            break;
        case event_id::ipi_received:
            archive(cereal::make_nvp("ipi_received", data.ipi_received));
            break;
        case event_id::tensorfma_write:
            archive(cereal::make_nvp("tensorfma_write", data.tensorfma_write));
            break;
        case event_id::tensorfma_write8:
            archive(cereal::make_nvp("tensorfma_write8", data.tensorfma_write8));
            break;
        case event_id::tensorquant_write:
            archive(cereal::make_nvp("tensorquant_write", data.tensorquant_write));
            break;
        case event_id::reduce_write:
            archive(cereal::make_nvp("reduce_write", data.reduce_write));
            break;
        case event_id::tensorstore_write:
            archive(cereal::make_nvp("tensorstore_write", data.tensorstore_write));
            break;
        case event_id::tensorfma_done:
            archive(cereal::make_nvp("tensorfma_done", data.tensorfma_done));
            break;
        case event_id::tensorquant_done:
            archive(cereal::make_nvp("tensorquant_done", data.tensorquant_done));
            break;
        case event_id::reduce_done:
            archive(cereal::make_nvp("reduce_done", data.reduce_done));
            break;
        case event_id::tensorstore_done:
            archive(cereal::make_nvp("tensorstore_done", data.tensorstore_done));
            break;
        case event_id::tl_mon_op_start:
            archive(cereal::make_nvp("tl_mon_op_start", data.tl_mon_op_start));
            break;
        case event_id::tl_mon_process_busy:
            archive(cereal::make_nvp("tl_mon_process_busy", data.tl_mon_process_busy));
            break;
        case event_id::tl_mon_process_req:
            archive(cereal::make_nvp("tl_mon_process_req", data.tl_mon_process_req));
            break;
        case event_id::tl_mon_process_resp:
            archive(cereal::make_nvp("tl_mon_process_resp", data.tl_mon_process_resp));
            break;
        case event_id::tl_mon_process_trans_data_xfer:
            archive(cereal::make_nvp("tl_mon_process_trans_data_xfer", data.tl_mon_process_trans_data_xfer));
            break;
        case event_id::tl_mon_process_tenb_flush:
            archive(cereal::make_nvp("tl_mon_process_tenb_flush", data.tl_mon_process_tenb_flush));
            break;
        case event_id::esr_write:
            archive(cereal::make_nvp("esr_write", data.esr_write));
            break;
        case event_id::icache_prefetch_done:
            archive(cereal::make_nvp("icache_prefetch_done", data.icache_prefetch_done));
            break;
        case event_id::warm_reset:
            archive(cereal::make_nvp("warm_reset", data.warm_reset));
            break;
        case event_id::clear_interrupt:
            archive(cereal::make_nvp("clear_interrupt", data.clear_interrupt));
            break;
        default:
            assert(0 && "Invalid event");
        }
    }

    template <class Archive>
    void load(Archive& archive)
    {
        archive(id);
        switch (id) {
        case event_id::inst_retire:
            archive(data.inst_retire);
            break;
        case event_id::inst_exception:
            archive(data.inst_exception);
            break;
        case event_id::inst_interrupt:
            archive(data.inst_interrupt);
            break;
        case event_id::delayed_write_int:
            archive(data.delayed_write_int);
            break;
        case event_id::flb_update:
            archive(data.flb_update);
            break;
        case event_id::load_miss_bus_err:
            archive(data.load_miss_bus_err);
            break;
        case event_id::delayed_store:
            archive(data.delayed_store);
            break;
        case event_id::update_fcsr_flags:
            archive(data.update_fcsr_flags);
            break;
        case event_id::delayed_write_fp:
            archive(data.delayed_write_fp);
            break;
        case event_id::vpu_rf_update:
            archive(data.vpu_rf_update);
            break;
        case event_id::delayed_write_rm:
            archive(data.delayed_write_rm);
            break;
        case event_id::ipi_received:
            archive(data.ipi_received);
            break;
        case event_id::tensorfma_write:
            archive(data.tensorfma_write);
            break;
        case event_id::tensorfma_write8:
            archive(data.tensorfma_write8);
            break;
        case event_id::tensorquant_write:
            archive(data.tensorquant_write);
            break;
        case event_id::reduce_write:
            archive(data.reduce_write);
            break;
        case event_id::tensorstore_write:
            archive(data.tensorstore_write);
            break;
        case event_id::tensorfma_done:
            archive(data.tensorfma_done);
            break;
        case event_id::tensorquant_done:
            archive(data.tensorquant_done);
            break;
        case event_id::reduce_done:
            archive(data.reduce_done);
            break;
        case event_id::tensorstore_done:
            archive(data.tensorstore_done);
            break;
        case event_id::tl_mon_op_start:
            archive(data.tl_mon_op_start);
            break;
        case event_id::tl_mon_process_busy:
            archive(data.tl_mon_process_busy);
            break;
        case event_id::tl_mon_process_req:
            archive(data.tl_mon_process_req);
            break;
        case event_id::tl_mon_process_resp:
            archive(data.tl_mon_process_resp);
            break;
        case event_id::tl_mon_process_trans_data_xfer:
            archive(data.tl_mon_process_trans_data_xfer);
            break;
        case event_id::tl_mon_process_tenb_flush:
            archive(data.tl_mon_process_tenb_flush);
            break;
        case event_id::esr_write:
            archive(data.esr_write);
            break;
        case event_id::icache_prefetch_done:
            archive(data.icache_prefetch_done);
            break;
        case event_id::warm_reset:
            archive(data.warm_reset);
            break;
        case event_id::clear_interrupt:
            archive(data.clear_interrupt);
            break;
        default:
            assert(0 && "Invalid event");
        }
    }

    event_id id;
    union {
        inst_retire_t inst_retire;
        inst_exception_t inst_exception;
        inst_interrupt_t inst_interrupt;
        delayed_write_int_t delayed_write_int;
        flb_update_t flb_update;
        load_miss_bus_err_t load_miss_bus_err;
        delayed_store_t delayed_store;
        update_fcsr_flags_t update_fcsr_flags;
        delayed_write_fp_t delayed_write_fp;
        vpu_rf_update_t vpu_rf_update;
        delayed_write_rm_t delayed_write_rm;
        ipi_received_t ipi_received;
        tensorfma_write_t tensorfma_write;
        tensorfma_write8_t tensorfma_write8;
        tensorquant_write_t tensorquant_write;
        reduce_write_t reduce_write;
        tensorstore_write_t tensorstore_write;
        tensorfma_done_t tensorfma_done;
        tensorquant_done_t tensorquant_done;
        reduce_done_t reduce_done;
        tensorstore_done_t tensorstore_done;
        tl_mon_op_start_t tl_mon_op_start;
        tl_mon_process_busy_t tl_mon_process_busy;
        tl_mon_process_req_t tl_mon_process_req;
        tl_mon_process_resp_t tl_mon_process_resp;
        tl_mon_process_trans_data_xfer_t tl_mon_process_trans_data_xfer;
        tl_mon_process_tenb_flush_t tl_mon_process_tenb_flush;
        esr_write_t esr_write;
        icache_prefetch_done_t icache_prefetch_done;
        warm_reset_t warm_reset;
        clear_interrupt_t clear_interrupt;
    } data;
};

struct handler {
    virtual ~handler() {}
    void on(const event_union* evt);
    virtual void on(const inst_retire_t* evt) { (void)evt; }
    virtual void on(const inst_exception_t* evt) { (void)evt; }
    virtual void on(const inst_interrupt_t* evt) { (void)evt; }
    virtual void on(const delayed_write_int_t* evt) { (void)evt; }
    virtual void on(const flb_update_t* evt) { (void)evt; }
    virtual void on(const load_miss_bus_err_t* evt) { (void)evt; }
    virtual void on(const delayed_store_t* evt) { (void)evt; }
    virtual void on(const update_fcsr_flags_t* evt) { (void)evt; }
    virtual void on(const delayed_write_fp_t* evt) { (void)evt; }
    virtual void on(const vpu_rf_update_t* evt) { (void)evt; }
    virtual void on(const delayed_write_rm_t* evt) { (void)evt; }
    virtual void on(const ipi_received_t* evt) { (void)evt; }
    virtual void on(const tensorfma_write_t* evt) { (void)evt; }
    virtual void on(const tensorfma_write8_t* evt) { (void)evt; }
    virtual void on(const tensorquant_write_t* evt) { (void)evt; }
    virtual void on(const reduce_write_t* evt) { (void)evt; }
    virtual void on(const tensorstore_write_t* evt) { (void)evt; }
    virtual void on(const tensorfma_done_t* evt) { (void)evt; }
    virtual void on(const tensorquant_done_t* evt) { (void)evt; }
    virtual void on(const reduce_done_t* evt) { (void)evt; }
    virtual void on(const tensorstore_done_t* evt) { (void)evt; }
    virtual void on(const tl_mon_op_start_t* evt) { (void)evt; }
    virtual void on(const tl_mon_process_busy_t* evt) { (void)evt; }
    virtual void on(const tl_mon_process_req_t* evt) { (void)evt; }
    virtual void on(const tl_mon_process_resp_t* evt) { (void)evt; }
    virtual void on(const tl_mon_process_trans_data_xfer_t* evt) { (void)evt; }
    virtual void on(const tl_mon_process_tenb_flush_t* evt) { (void)evt; }
    virtual void on(const esr_write_t* evt) { (void)evt; }
    virtual void on(const icache_prefetch_done_t* evt) { (void)evt; }
    virtual void on(const warm_reset_t* evt) { (void)evt; }
    virtual void on(const clear_interrupt_t* evt) { (void)evt; }
};

struct hash_id {
    std::size_t operator()(const event_id& id) const { return static_cast<std::size_t>(id); }
};

} // namespace cosim_evt

extern "C" {
void trigger_inst_retire(uint64_t cycle, uint32_t minion_id, uint8_t thread_id, uint64_t pc, uint32_t inst_bits,
                         bool delayed_write, bool load_miss, bool wbx, uint32_t wbx_rd, uint64_t wbx_data, bool wbf,
                         uint32_t wbf_rd, bool wbm, bool wbmall, uint32_t wbm_rd, uint64_t wbm_data, bool store,
                         uint32_t store_size, uint64_t store_addr, uint64_t store_data[4], uint32_t store_mask,
                         bool delayed_store, uint32_t store_age_id, bool scatter, uint64_t scatter_addr[8],
                         uint32_t scatter_data[8], bool tex_send, bool tex_rcv, bool tensor_load, bool tenb,
                         uint32_t tensor_load_num_lines, bool tensor_fma, bool tensor_quant, bool reduce,
                         bool tensor_store, bool flb_valid, uint32_t flb_idx, uint32_t flb_range, bool wflags,
                         uint32_t trans_id, uint32_t prv);
void trigger_inst_exception(uint64_t cycle, uint32_t minion_id, uint8_t thread_id, uint64_t pc, uint32_t inst_bits,
                            uint32_t wbf_rd, bool is_store, bool is_atomic, bool is_gsc, uint64_t scatter_addr[8],
                            uint32_t scatter_data[8], uint32_t store_mask, uint32_t gsc_size, uint32_t gsc_progress,
                            uint64_t mstatus, uint64_t cause, uint64_t tval, uint64_t epc, uint64_t mip, uint32_t prv);
void trigger_inst_interrupt(uint64_t cycle, uint32_t minion_id, uint8_t thread_id, uint64_t pc, uint32_t inst_bits,
                            bool is_gsc, uint32_t gsc_progress, uint64_t mstatus, uint64_t cause, uint64_t tval,
                            uint64_t epc, uint64_t mip, uint64_t bus_error_addr, uint64_t bus_error_pc, uint32_t prv);
void trigger_delayed_write_int(uint64_t cycle, uint32_t minion_id, uint8_t thread_id, uint32_t wbx_rd,
                               uint64_t wbx_data);
void trigger_flb_update(uint64_t cycle, uint32_t minion_id, uint8_t thread_id, uint32_t wbx_rd, uint64_t wbx_data);
void trigger_load_miss_bus_err(uint64_t cycle, uint32_t minion_id, uint64_t pc, uint8_t thread_id,
                               uint64_t bus_error_addr);
void trigger_delayed_store(uint64_t cycle, uint32_t minion_id, uint8_t thread_id, bool scatter, uint32_t scatter_cnt,
                           uint32_t store_size, uint64_t store_data[4], uint32_t store_age_id);
void trigger_update_fcsr_flags(uint64_t cycle, uint32_t minion_id, uint8_t thread_id, uint32_t flags,
                               uint32_t trans_id);
void trigger_delayed_write_fp(uint64_t cycle, uint32_t minion_id, uint8_t thread_id, uint32_t wbf_rd,
                              uint32_t entry_point_id);
void trigger_vpu_rf_update(uint64_t cycle, uint32_t minion_id, uint32_t wr_mask, uint32_t thread_ids, uint8_t addr[8],
                           uint32_t data[8]);
void trigger_delayed_write_rm(uint64_t cycle, uint32_t minion_id, uint8_t thread_id, bool wbmall, uint32_t wbm_rd,
                              uint64_t wbm_data);
void trigger_ipi_received(uint64_t cycle, uint32_t minion_id, uint8_t thread_id, uint64_t pc);
void trigger_tensorfma_write(uint64_t cycle, uint32_t minion_id, int32_t entry, uint32_t wmask);
void trigger_tensorfma_write8(uint64_t cycle, uint32_t minion_id, int32_t entry, uint32_t data[8], uint32_t wmask);
void trigger_tensorquant_write(uint64_t cycle, uint32_t minion_id, int32_t entry, uint32_t wmask);
void trigger_reduce_write(uint64_t cycle, uint32_t minion_id, int32_t entry);
void trigger_tensorstore_write(uint64_t cycle, uint32_t minion_id, bool is_256_bit, uint64_t addr, uint32_t data[16],
                               uint8_t size, uint8_t qwen, uint8_t subcode, uint8_t coop);
void trigger_tensorfma_done(uint64_t cycle, uint32_t minion_id);
void trigger_tensorquant_done(uint64_t cycle, uint32_t minion_id);
void trigger_reduce_done(uint64_t cycle, uint32_t minion_id, uint8_t action, uint32_t partner_minion_id,
                         uint8_t operation, bool zero_reg_reduce, bool auto_pair, uint8_t level);
void trigger_tensorstore_done(uint64_t cycle, uint32_t minion_id, uint8_t coop);
void trigger_tl_mon_op_start(uint64_t cycle, uint32_t minion_id, uint32_t tl_module, uint32_t transform,
                             uint32_t num_lines);
void trigger_tl_mon_process_busy(uint64_t cycle, uint32_t minion_id, int32_t tl_module, int32_t state);
void trigger_tl_mon_process_req(uint64_t cycle, uint32_t minion_id, int32_t tl_module, int32_t req_id_idx);
void trigger_tl_mon_process_resp(uint64_t cycle, uint32_t minion_id, int32_t tl_module, int32_t resp_id_idx,
                                 int32_t entry, uint64_t data[4]);
void trigger_tl_mon_process_trans_data_xfer(uint64_t cycle, uint32_t minion_id, int32_t entry, int32_t banks,
                                            uint64_t data[4]);
void trigger_tl_mon_process_tenb_flush(uint64_t cycle, uint32_t minion_id);
void trigger_esr_write(uint64_t addr, uint64_t data);
void trigger_icache_prefetch_done(uint32_t shire_id);
void trigger_warm_reset(uint64_t cycle, uint32_t minion_id);
void trigger_clear_interrupt(uint64_t cycle, uint32_t minion_id, uint8_t thread_id, uint32_t mip);
}

#endif // _COSIM_EVT_
