// CHECKSUM a0a04d0a3bd0cd6069840b6f3cf8f4ff
// This file has been autogenerated. Do not edit!

`ifndef _COSIM_EVT_
`define _COSIM_EVT_

typedef struct {
    longint unsigned cycle;
    int unsigned minion_id;
    byte unsigned thread_id;
    longint unsigned pc;
    int unsigned inst_bits;
    bit delayed_write;
    bit load_miss;
    bit wbx;
    int unsigned wbx_rd;
    longint unsigned wbx_data;
    bit wbf;
    int unsigned wbf_rd;
    bit wbm;
    bit wbmall;
    int unsigned wbm_rd;
    longint unsigned wbm_data;
    bit store;
    int unsigned store_size;
    longint unsigned store_addr;
    longint unsigned store_data[4];
    int unsigned store_mask;
    bit delayed_store;
    int unsigned store_age_id;
    bit scatter;
    longint unsigned scatter_addr[8];
    int unsigned scatter_data[8];
    bit tex_send;
    bit tex_rcv;
    bit tensor_load;
    bit tenb;
    int unsigned tensor_load_num_lines;
    bit tensor_fma;
    bit tensor_quant;
    bit reduce;
    bit tensor_store;
    bit flb_valid;
    int unsigned flb_idx;
    int unsigned flb_range;
    bit wflags;
    int unsigned trans_id;
    int unsigned prv;
} inst_retire_t;

   
 function automatic void trigger_inst_retire_unpack(input inst_retire_t evt);
    trigger_inst_retire ( evt.cycle, evt.minion_id, evt.thread_id, evt.pc, evt.inst_bits, evt.delayed_write, evt.load_miss, evt.wbx, evt.wbx_rd, evt.wbx_data, evt.wbf, evt.wbf_rd, evt.wbm, evt.wbmall, evt.wbm_rd, evt.wbm_data, evt.store, evt.store_size, evt.store_addr, evt.store_data, evt.store_mask, evt.delayed_store, evt.store_age_id, evt.scatter, evt.scatter_addr, evt.scatter_data, evt.tex_send, evt.tex_rcv, evt.tensor_load, evt.tenb, evt.tensor_load_num_lines, evt.tensor_fma, evt.tensor_quant, evt.reduce, evt.tensor_store, evt.flb_valid, evt.flb_idx, evt.flb_range, evt.wflags, evt.trans_id, evt.prv );
 endfunction

import "DPI-C" context function void trigger_inst_retire (input longint unsigned cycle, input int unsigned minion_id, input byte unsigned thread_id, input longint unsigned pc, input int unsigned inst_bits, input bit delayed_write, input bit load_miss, input bit wbx, input int unsigned wbx_rd, input longint unsigned wbx_data, input bit wbf, input int unsigned wbf_rd, input bit wbm, input bit wbmall, input int unsigned wbm_rd, input longint unsigned wbm_data, input bit store, input int unsigned store_size, input longint unsigned store_addr, input longint unsigned store_data[4], input int unsigned store_mask, input bit delayed_store, input int unsigned store_age_id, input bit scatter, input longint unsigned scatter_addr[8], input int unsigned scatter_data[8], input bit tex_send, input bit tex_rcv, input bit tensor_load, input bit tenb, input int unsigned tensor_load_num_lines, input bit tensor_fma, input bit tensor_quant, input bit reduce, input bit tensor_store, input bit flb_valid, input int unsigned flb_idx, input int unsigned flb_range, input bit wflags, input int unsigned trans_id, input int unsigned prv );

typedef struct {
    longint unsigned cycle;
    int unsigned minion_id;
    byte unsigned thread_id;
    longint unsigned pc;
    int unsigned inst_bits;
    int unsigned wbf_rd;
    bit is_store;
    bit is_atomic;
    bit is_gsc;
    longint unsigned scatter_addr[8];
    int unsigned scatter_data[8];
    int unsigned store_mask;
    int unsigned gsc_size;
    int unsigned gsc_progress;
    longint unsigned mstatus;
    longint unsigned cause;
    longint unsigned tval;
    longint unsigned epc;
    longint unsigned mip;
    int unsigned prv;
} inst_exception_t;

   
 function automatic void trigger_inst_exception_unpack(input inst_exception_t evt);
    trigger_inst_exception ( evt.cycle, evt.minion_id, evt.thread_id, evt.pc, evt.inst_bits, evt.wbf_rd, evt.is_store, evt.is_atomic, evt.is_gsc, evt.scatter_addr, evt.scatter_data, evt.store_mask, evt.gsc_size, evt.gsc_progress, evt.mstatus, evt.cause, evt.tval, evt.epc, evt.mip, evt.prv );
 endfunction

import "DPI-C" context function void trigger_inst_exception (input longint unsigned cycle, input int unsigned minion_id, input byte unsigned thread_id, input longint unsigned pc, input int unsigned inst_bits, input int unsigned wbf_rd, input bit is_store, input bit is_atomic, input bit is_gsc, input longint unsigned scatter_addr[8], input int unsigned scatter_data[8], input int unsigned store_mask, input int unsigned gsc_size, input int unsigned gsc_progress, input longint unsigned mstatus, input longint unsigned cause, input longint unsigned tval, input longint unsigned epc, input longint unsigned mip, input int unsigned prv );

typedef struct {
    longint unsigned cycle;
    int unsigned minion_id;
    byte unsigned thread_id;
    longint unsigned pc;
    int unsigned inst_bits;
    bit is_gsc;
    int unsigned gsc_progress;
    longint unsigned mstatus;
    longint unsigned cause;
    longint unsigned tval;
    longint unsigned epc;
    longint unsigned mip;
    longint unsigned bus_error_addr;
    longint unsigned bus_error_pc;
    int unsigned prv;
} inst_interrupt_t;

   
 function automatic void trigger_inst_interrupt_unpack(input inst_interrupt_t evt);
    trigger_inst_interrupt ( evt.cycle, evt.minion_id, evt.thread_id, evt.pc, evt.inst_bits, evt.is_gsc, evt.gsc_progress, evt.mstatus, evt.cause, evt.tval, evt.epc, evt.mip, evt.bus_error_addr, evt.bus_error_pc, evt.prv );
 endfunction

import "DPI-C" context function void trigger_inst_interrupt (input longint unsigned cycle, input int unsigned minion_id, input byte unsigned thread_id, input longint unsigned pc, input int unsigned inst_bits, input bit is_gsc, input int unsigned gsc_progress, input longint unsigned mstatus, input longint unsigned cause, input longint unsigned tval, input longint unsigned epc, input longint unsigned mip, input longint unsigned bus_error_addr, input longint unsigned bus_error_pc, input int unsigned prv );

typedef struct {
    longint unsigned cycle;
    int unsigned minion_id;
    byte unsigned thread_id;
    int unsigned wbx_rd;
    longint unsigned wbx_data;
} delayed_write_int_t;

   
 function automatic void trigger_delayed_write_int_unpack(input delayed_write_int_t evt);
    trigger_delayed_write_int ( evt.cycle, evt.minion_id, evt.thread_id, evt.wbx_rd, evt.wbx_data );
 endfunction

import "DPI-C" context function void trigger_delayed_write_int (input longint unsigned cycle, input int unsigned minion_id, input byte unsigned thread_id, input int unsigned wbx_rd, input longint unsigned wbx_data );

typedef struct {
    longint unsigned cycle;
    int unsigned minion_id;
    byte unsigned thread_id;
    int unsigned wbx_rd;
    longint unsigned wbx_data;
} flb_update_t;

   
 function automatic void trigger_flb_update_unpack(input flb_update_t evt);
    trigger_flb_update ( evt.cycle, evt.minion_id, evt.thread_id, evt.wbx_rd, evt.wbx_data );
 endfunction

import "DPI-C" context function void trigger_flb_update (input longint unsigned cycle, input int unsigned minion_id, input byte unsigned thread_id, input int unsigned wbx_rd, input longint unsigned wbx_data );

typedef struct {
    longint unsigned cycle;
    int unsigned minion_id;
    longint unsigned pc;
    byte unsigned thread_id;
    longint unsigned bus_error_addr;
} load_miss_bus_err_t;

   
 function automatic void trigger_load_miss_bus_err_unpack(input load_miss_bus_err_t evt);
    trigger_load_miss_bus_err ( evt.cycle, evt.minion_id, evt.pc, evt.thread_id, evt.bus_error_addr );
 endfunction

import "DPI-C" context function void trigger_load_miss_bus_err (input longint unsigned cycle, input int unsigned minion_id, input longint unsigned pc, input byte unsigned thread_id, input longint unsigned bus_error_addr );

typedef struct {
    longint unsigned cycle;
    int unsigned minion_id;
    byte unsigned thread_id;
    bit scatter;
    int unsigned scatter_cnt;
    int unsigned store_size;
    longint unsigned store_data[4];
    int unsigned store_age_id;
} delayed_store_t;

   
 function automatic void trigger_delayed_store_unpack(input delayed_store_t evt);
    trigger_delayed_store ( evt.cycle, evt.minion_id, evt.thread_id, evt.scatter, evt.scatter_cnt, evt.store_size, evt.store_data, evt.store_age_id );
 endfunction

import "DPI-C" context function void trigger_delayed_store (input longint unsigned cycle, input int unsigned minion_id, input byte unsigned thread_id, input bit scatter, input int unsigned scatter_cnt, input int unsigned store_size, input longint unsigned store_data[4], input int unsigned store_age_id );

typedef struct {
    longint unsigned cycle;
    int unsigned minion_id;
    byte unsigned thread_id;
    int unsigned flags;
    int unsigned trans_id;
} update_fcsr_flags_t;

   
 function automatic void trigger_update_fcsr_flags_unpack(input update_fcsr_flags_t evt);
    trigger_update_fcsr_flags ( evt.cycle, evt.minion_id, evt.thread_id, evt.flags, evt.trans_id );
 endfunction

import "DPI-C" context function void trigger_update_fcsr_flags (input longint unsigned cycle, input int unsigned minion_id, input byte unsigned thread_id, input int unsigned flags, input int unsigned trans_id );

typedef struct {
    longint unsigned cycle;
    int unsigned minion_id;
    byte unsigned thread_id;
    int unsigned wbf_rd;
    int unsigned entry_point_id;
} delayed_write_fp_t;

   
 function automatic void trigger_delayed_write_fp_unpack(input delayed_write_fp_t evt);
    trigger_delayed_write_fp ( evt.cycle, evt.minion_id, evt.thread_id, evt.wbf_rd, evt.entry_point_id );
 endfunction

import "DPI-C" context function void trigger_delayed_write_fp (input longint unsigned cycle, input int unsigned minion_id, input byte unsigned thread_id, input int unsigned wbf_rd, input int unsigned entry_point_id );

typedef struct {
    longint unsigned cycle;
    int unsigned minion_id;
    int unsigned wr_mask;
    int unsigned thread_ids;
    byte unsigned addr[8];
    int unsigned data[8];
} vpu_rf_update_t;

   
 function automatic void trigger_vpu_rf_update_unpack(input vpu_rf_update_t evt);
    trigger_vpu_rf_update ( evt.cycle, evt.minion_id, evt.wr_mask, evt.thread_ids, evt.addr, evt.data );
 endfunction

import "DPI-C" context function void trigger_vpu_rf_update (input longint unsigned cycle, input int unsigned minion_id, input int unsigned wr_mask, input int unsigned thread_ids, input byte unsigned addr[8], input int unsigned data[8] );

typedef struct {
    longint unsigned cycle;
    int unsigned minion_id;
    byte unsigned thread_id;
    bit wbmall;
    int unsigned wbm_rd;
    longint unsigned wbm_data;
} delayed_write_rm_t;

   
 function automatic void trigger_delayed_write_rm_unpack(input delayed_write_rm_t evt);
    trigger_delayed_write_rm ( evt.cycle, evt.minion_id, evt.thread_id, evt.wbmall, evt.wbm_rd, evt.wbm_data );
 endfunction

import "DPI-C" context function void trigger_delayed_write_rm (input longint unsigned cycle, input int unsigned minion_id, input byte unsigned thread_id, input bit wbmall, input int unsigned wbm_rd, input longint unsigned wbm_data );

typedef struct {
    longint unsigned cycle;
    int unsigned minion_id;
    byte unsigned thread_id;
    longint unsigned pc;
} ipi_received_t;

   
 function automatic void trigger_ipi_received_unpack(input ipi_received_t evt);
    trigger_ipi_received ( evt.cycle, evt.minion_id, evt.thread_id, evt.pc );
 endfunction

import "DPI-C" context function void trigger_ipi_received (input longint unsigned cycle, input int unsigned minion_id, input byte unsigned thread_id, input longint unsigned pc );

typedef struct {
    longint unsigned cycle;
    int unsigned minion_id;
    int entry;
    int unsigned wmask;
} tensorfma_write_t;

   
 function automatic void trigger_tensorfma_write_unpack(input tensorfma_write_t evt);
    trigger_tensorfma_write ( evt.cycle, evt.minion_id, evt.entry, evt.wmask );
 endfunction

import "DPI-C" context function void trigger_tensorfma_write (input longint unsigned cycle, input int unsigned minion_id, input int entry, input int unsigned wmask );

typedef struct {
    longint unsigned cycle;
    int unsigned minion_id;
    int entry;
    int unsigned data[8];
    int unsigned wmask;
} tensorfma_write8_t;

   
 function automatic void trigger_tensorfma_write8_unpack(input tensorfma_write8_t evt);
    trigger_tensorfma_write8 ( evt.cycle, evt.minion_id, evt.entry, evt.data, evt.wmask );
 endfunction

import "DPI-C" context function void trigger_tensorfma_write8 (input longint unsigned cycle, input int unsigned minion_id, input int entry, input int unsigned data[8], input int unsigned wmask );

typedef struct {
    longint unsigned cycle;
    int unsigned minion_id;
    int entry;
    int unsigned wmask;
} tensorquant_write_t;

   
 function automatic void trigger_tensorquant_write_unpack(input tensorquant_write_t evt);
    trigger_tensorquant_write ( evt.cycle, evt.minion_id, evt.entry, evt.wmask );
 endfunction

import "DPI-C" context function void trigger_tensorquant_write (input longint unsigned cycle, input int unsigned minion_id, input int entry, input int unsigned wmask );

typedef struct {
    longint unsigned cycle;
    int unsigned minion_id;
    int entry;
} reduce_write_t;

   
 function automatic void trigger_reduce_write_unpack(input reduce_write_t evt);
    trigger_reduce_write ( evt.cycle, evt.minion_id, evt.entry );
 endfunction

import "DPI-C" context function void trigger_reduce_write (input longint unsigned cycle, input int unsigned minion_id, input int entry );

typedef struct {
    longint unsigned cycle;
    int unsigned minion_id;
    bit is_256_bit;
    longint unsigned addr;
    int unsigned data[16];
    byte unsigned size;
    byte unsigned qwen;
    byte unsigned subcode;
    byte unsigned coop;
} tensorstore_write_t;

   
 function automatic void trigger_tensorstore_write_unpack(input tensorstore_write_t evt);
    trigger_tensorstore_write ( evt.cycle, evt.minion_id, evt.is_256_bit, evt.addr, evt.data, evt.size, evt.qwen, evt.subcode, evt.coop );
 endfunction

import "DPI-C" context function void trigger_tensorstore_write (input longint unsigned cycle, input int unsigned minion_id, input bit is_256_bit, input longint unsigned addr, input int unsigned data[16], input byte unsigned size, input byte unsigned qwen, input byte unsigned subcode, input byte unsigned coop );

typedef struct {
    longint unsigned cycle;
    int unsigned minion_id;
} tensorfma_done_t;

   
 function automatic void trigger_tensorfma_done_unpack(input tensorfma_done_t evt);
    trigger_tensorfma_done ( evt.cycle, evt.minion_id );
 endfunction

import "DPI-C" context function void trigger_tensorfma_done (input longint unsigned cycle, input int unsigned minion_id );

typedef struct {
    longint unsigned cycle;
    int unsigned minion_id;
} tensorquant_done_t;

   
 function automatic void trigger_tensorquant_done_unpack(input tensorquant_done_t evt);
    trigger_tensorquant_done ( evt.cycle, evt.minion_id );
 endfunction

import "DPI-C" context function void trigger_tensorquant_done (input longint unsigned cycle, input int unsigned minion_id );

typedef struct {
    longint unsigned cycle;
    int unsigned minion_id;
    byte unsigned action;
    int unsigned partner_minion_id;
    byte unsigned operation;
    bit zero_reg_reduce;
    bit auto_pair;
    byte unsigned level;
} reduce_done_t;

   
 function automatic void trigger_reduce_done_unpack(input reduce_done_t evt);
    trigger_reduce_done ( evt.cycle, evt.minion_id, evt.action, evt.partner_minion_id, evt.operation, evt.zero_reg_reduce, evt.auto_pair, evt.level );
 endfunction

import "DPI-C" context function void trigger_reduce_done (input longint unsigned cycle, input int unsigned minion_id, input byte unsigned action, input int unsigned partner_minion_id, input byte unsigned operation, input bit zero_reg_reduce, input bit auto_pair, input byte unsigned level );

typedef struct {
    longint unsigned cycle;
    int unsigned minion_id;
    byte unsigned coop;
} tensorstore_done_t;

   
 function automatic void trigger_tensorstore_done_unpack(input tensorstore_done_t evt);
    trigger_tensorstore_done ( evt.cycle, evt.minion_id, evt.coop );
 endfunction

import "DPI-C" context function void trigger_tensorstore_done (input longint unsigned cycle, input int unsigned minion_id, input byte unsigned coop );

typedef struct {
    longint unsigned cycle;
    int unsigned minion_id;
    int unsigned tl_module;
    int unsigned transform;
    int unsigned num_lines;
} tl_mon_op_start_t;

   
 function automatic void trigger_tl_mon_op_start_unpack(input tl_mon_op_start_t evt);
    trigger_tl_mon_op_start ( evt.cycle, evt.minion_id, evt.tl_module, evt.transform, evt.num_lines );
 endfunction

import "DPI-C" context function void trigger_tl_mon_op_start (input longint unsigned cycle, input int unsigned minion_id, input int unsigned tl_module, input int unsigned transform, input int unsigned num_lines );

typedef struct {
    longint unsigned cycle;
    int unsigned minion_id;
    int tl_module;
    int state;
} tl_mon_process_busy_t;

   
 function automatic void trigger_tl_mon_process_busy_unpack(input tl_mon_process_busy_t evt);
    trigger_tl_mon_process_busy ( evt.cycle, evt.minion_id, evt.tl_module, evt.state );
 endfunction

import "DPI-C" context function void trigger_tl_mon_process_busy (input longint unsigned cycle, input int unsigned minion_id, input int tl_module, input int state );

typedef struct {
    longint unsigned cycle;
    int unsigned minion_id;
    int tl_module;
    int req_id_idx;
} tl_mon_process_req_t;

   
 function automatic void trigger_tl_mon_process_req_unpack(input tl_mon_process_req_t evt);
    trigger_tl_mon_process_req ( evt.cycle, evt.minion_id, evt.tl_module, evt.req_id_idx );
 endfunction

import "DPI-C" context function void trigger_tl_mon_process_req (input longint unsigned cycle, input int unsigned minion_id, input int tl_module, input int req_id_idx );

typedef struct {
    longint unsigned cycle;
    int unsigned minion_id;
    int tl_module;
    int resp_id_idx;
    int entry;
    longint unsigned data[4];
} tl_mon_process_resp_t;

   
 function automatic void trigger_tl_mon_process_resp_unpack(input tl_mon_process_resp_t evt);
    trigger_tl_mon_process_resp ( evt.cycle, evt.minion_id, evt.tl_module, evt.resp_id_idx, evt.entry, evt.data );
 endfunction

import "DPI-C" context function void trigger_tl_mon_process_resp (input longint unsigned cycle, input int unsigned minion_id, input int tl_module, input int resp_id_idx, input int entry, input longint unsigned data[4] );

typedef struct {
    longint unsigned cycle;
    int unsigned minion_id;
    int entry;
    int banks;
    longint unsigned data[4];
} tl_mon_process_trans_data_xfer_t;

   
 function automatic void trigger_tl_mon_process_trans_data_xfer_unpack(input tl_mon_process_trans_data_xfer_t evt);
    trigger_tl_mon_process_trans_data_xfer ( evt.cycle, evt.minion_id, evt.entry, evt.banks, evt.data );
 endfunction

import "DPI-C" context function void trigger_tl_mon_process_trans_data_xfer (input longint unsigned cycle, input int unsigned minion_id, input int entry, input int banks, input longint unsigned data[4] );

typedef struct {
    longint unsigned cycle;
    int unsigned minion_id;
} tl_mon_process_tenb_flush_t;

   
 function automatic void trigger_tl_mon_process_tenb_flush_unpack(input tl_mon_process_tenb_flush_t evt);
    trigger_tl_mon_process_tenb_flush ( evt.cycle, evt.minion_id );
 endfunction

import "DPI-C" context function void trigger_tl_mon_process_tenb_flush (input longint unsigned cycle, input int unsigned minion_id );

typedef struct {
    longint unsigned addr;
    longint unsigned data;
} esr_write_t;

   
 function automatic void trigger_esr_write_unpack(input esr_write_t evt);
    trigger_esr_write ( evt.addr, evt.data );
 endfunction

import "DPI-C" context function void trigger_esr_write (input longint unsigned addr, input longint unsigned data );

typedef struct {
    int unsigned shire_id;
} icache_prefetch_done_t;

   
 function automatic void trigger_icache_prefetch_done_unpack(input icache_prefetch_done_t evt);
    trigger_icache_prefetch_done ( evt.shire_id );
 endfunction

import "DPI-C" context function void trigger_icache_prefetch_done (input int unsigned shire_id );

typedef struct {
    longint unsigned cycle;
    int unsigned minion_id;
} warm_reset_t;

   
 function automatic void trigger_warm_reset_unpack(input warm_reset_t evt);
    trigger_warm_reset ( evt.cycle, evt.minion_id );
 endfunction

import "DPI-C" context function void trigger_warm_reset (input longint unsigned cycle, input int unsigned minion_id );

typedef struct {
    longint unsigned cycle;
    int unsigned minion_id;
    byte unsigned thread_id;
    int unsigned mip;
} clear_interrupt_t;

   
 function automatic void trigger_clear_interrupt_unpack(input clear_interrupt_t evt);
    trigger_clear_interrupt ( evt.cycle, evt.minion_id, evt.thread_id, evt.mip );
 endfunction

import "DPI-C" context function void trigger_clear_interrupt (input longint unsigned cycle, input int unsigned minion_id, input byte unsigned thread_id, input int unsigned mip );


`endif // _COSIM_EVT_

