// Copyright (c) 2026 Ainekko
// SPDX-License-Identifier: Apache-2.0

module cosim_txfma_booth_ppg_32r4_tb
  import minion_pkg::*;
(
  input  logic [VpuDataSSz-1:0] mpcnd_i,
  input  logic [VpuDataSSz-1:0] mplr_i,
  input  logic                  mode_i,
  input  logic                  sign_i,
  output logic [VpuDataSSz-1:0] orig_sxt_o,
  output logic [VpuDataSSz-1:0] orig_cin_o,
  output logic [VpuDataSSz:0]   orig_pp1_o,
  output logic [VpuDataSSz:0]   orig_pp2_o,
  output logic [VpuDataSSz:0]   orig_pp3_o,
  output logic [VpuDataSSz:0]   orig_pp4_o,
  output logic [VpuDataSSz:0]   orig_pp5_o,
  output logic [VpuDataSSz:0]   orig_pp6_o,
  output logic [VpuDataSSz:0]   orig_pp7_o,
  output logic [VpuDataSSz:0]   orig_pp8_o,
  output logic [VpuDataSSz:0]   orig_pp9_o,
  output logic [VpuDataSSz:0]   orig_pp10_o,
  output logic [VpuDataSSz:0]   orig_pp11_o,
  output logic [VpuDataSSz:0]   orig_pp12_o,
  output logic [VpuDataSSz:0]   orig_pp13_o,
  output logic [VpuDataSSz:0]   orig_pp14_o,
  output logic [VpuDataSSz:0]   orig_pp15_o,
  output logic [VpuDataSSz:0]   orig_pp16_o,
  output logic [VpuDataSSz:0]   orig_pp17_o,
  output logic [VpuDataSSz-1:0] new_sxt_o,
  output logic [VpuDataSSz-1:0] new_cin_o,
  output logic [VpuDataSSz:0]   new_pp1_o,
  output logic [VpuDataSSz:0]   new_pp2_o,
  output logic [VpuDataSSz:0]   new_pp3_o,
  output logic [VpuDataSSz:0]   new_pp4_o,
  output logic [VpuDataSSz:0]   new_pp5_o,
  output logic [VpuDataSSz:0]   new_pp6_o,
  output logic [VpuDataSSz:0]   new_pp7_o,
  output logic [VpuDataSSz:0]   new_pp8_o,
  output logic [VpuDataSSz:0]   new_pp9_o,
  output logic [VpuDataSSz:0]   new_pp10_o,
  output logic [VpuDataSSz:0]   new_pp11_o,
  output logic [VpuDataSSz:0]   new_pp12_o,
  output logic [VpuDataSSz:0]   new_pp13_o,
  output logic [VpuDataSSz:0]   new_pp14_o,
  output logic [VpuDataSSz:0]   new_pp15_o,
  output logic [VpuDataSSz:0]   new_pp16_o,
  output logic [VpuDataSSz:0]   new_pp17_o
);

  txfma_booth_ppg_32r4_orig u_orig (
    .mpcnd (mpcnd_i),
    .mplr  (mplr_i),
    .mode  (mode_i),
    .sign  (sign_i),
    .Sxt   (orig_sxt_o),
    .Cin   (orig_cin_o),
    .pp1   (orig_pp1_o),
    .pp2   (orig_pp2_o),
    .pp3   (orig_pp3_o),
    .pp4   (orig_pp4_o),
    .pp5   (orig_pp5_o),
    .pp6   (orig_pp6_o),
    .pp7   (orig_pp7_o),
    .pp8   (orig_pp8_o),
    .pp9   (orig_pp9_o),
    .pp10  (orig_pp10_o),
    .pp11  (orig_pp11_o),
    .pp12  (orig_pp12_o),
    .pp13  (orig_pp13_o),
    .pp14  (orig_pp14_o),
    .pp15  (orig_pp15_o),
    .pp16  (orig_pp16_o),
    .pp17  (orig_pp17_o)
  );

  txfma_booth_ppg_32r4 u_new (
    .mpcnd_i,
    .mplr_i,
    .mode_i,
    .sign_i,
    .sxt_o  (new_sxt_o),
    .cin_o  (new_cin_o),
    .pp1_o  (new_pp1_o),
    .pp2_o  (new_pp2_o),
    .pp3_o  (new_pp3_o),
    .pp4_o  (new_pp4_o),
    .pp5_o  (new_pp5_o),
    .pp6_o  (new_pp6_o),
    .pp7_o  (new_pp7_o),
    .pp8_o  (new_pp8_o),
    .pp9_o  (new_pp9_o),
    .pp10_o (new_pp10_o),
    .pp11_o (new_pp11_o),
    .pp12_o (new_pp12_o),
    .pp13_o (new_pp13_o),
    .pp14_o (new_pp14_o),
    .pp15_o (new_pp15_o),
    .pp16_o (new_pp16_o),
    .pp17_o (new_pp17_o)
  );

endmodule : cosim_txfma_booth_ppg_32r4_tb
