// Copyright (c) 2026 Ainekko
// SPDX-License-Identifier: Apache-2.0

module cosim_txfma_c1_tb import vpu_defs_pkg::*;
(
  input logic ctrl_valid_f1a_h,
  input logic [TXFMA_SIGS_SZ-1:0] sigs_f1a_h,
  input logic [VPU_FCMD_SZ-1:0] cmd_in_f1a_h,
  input logic [VPU_DTYPE_SZ-1:0] op_dtype_f1a_h,
  input logic [TXFMA_EXP_PS_SZ-1:0] ea_hi_f1a_h,
  input logic fa_hi_zero_f1a_h,
  input logic sa_hi_f1a_h,
  input logic sb_hi_f1a_h,
  input logic sc_f1a_h,
  input logic sa_lo_f1a_h,
  input logic sb_lo_f1a_h,
  input logic ea_hi_zero_f1a_h,
  input logic eb_hi_zero_f1a_h,
  input logic ea_lo_zero_f1a_h,
  input logic eb_lo_zero_f1a_h,
  input logic flog_mul_prod_zero_f1a_h,
  output logic orig_minmax_op_f1a_h,
  output logic new_minmax_op_f1a_h,
  output logic orig_prod_sign_hi_f1a_h,
  output logic new_prod_sign_hi_f1a_h,
  output logic orig_prod_sign_lo_f1a_h,
  output logic new_prod_sign_lo_f1a_h,
  output logic orig_eprod_hi_zero_f1a_h,
  output logic new_eprod_hi_zero_f1a_h,
  output logic orig_eprod_lo_zero_f1a_h,
  output logic new_eprod_lo_zero_f1a_h,
  output logic orig_norm_f32_ovf_f1a_h,
  output logic new_norm_f32_ovf_f1a_h,
  output logic orig_norm_one_out_f1a_h,
  output logic new_norm_one_out_f1a_h,
  output logic orig_paddin1_sels_f1a_h,
  output logic new_paddin1_sels_f1a_h,
  output logic orig_paddin2_selc_f1a_h,
  output logic new_paddin2_selc_f1a_h,
  output logic orig_paddin2_selfcneg_f1a_h,
  output logic new_paddin2_selfcneg_f1a_h,
  output logic orig_padd_cin_f1a_h,
  output logic new_padd_cin_f1a_h,
  output logic orig_sel_famask_f1a_h,
  output logic new_sel_famask_f1a_h,
  output logic orig_sel_fcmask_f1a_h,
  output logic new_sel_fcmask_f1a_h,
  output logic orig_fa_en_f1a_h,
  output logic new_fa_en_f1a_h,
  output logic [VPU_FCMD_SZ-1:0] orig_cmd_f1a_h,
  output logic [VPU_FCMD_SZ-1:0] new_cmd_f1a_h,
  output logic orig_use_mul_f1a_h,
  output logic new_use_mul_f1a_h
);

  txfma_c1_orig u_orig (
    .ctrl_valid_f1a_h (ctrl_valid_f1a_h),
    .sigs_f1a_h (sigs_f1a_h),
    .cmd_in_f1a_h (cmd_in_f1a_h),
    .op_dtype_f1a_h (op_dtype_f1a_h),
    .ea_hi_f1a_h (ea_hi_f1a_h),
    .fa_hi_zero_f1a_h (fa_hi_zero_f1a_h),
    .sa_hi_f1a_h (sa_hi_f1a_h),
    .sb_hi_f1a_h (sb_hi_f1a_h),
    .sc_f1a_h (sc_f1a_h),
    .sa_lo_f1a_h (sa_lo_f1a_h),
    .sb_lo_f1a_h (sb_lo_f1a_h),
    .ea_hi_zero_f1a_h (ea_hi_zero_f1a_h),
    .eb_hi_zero_f1a_h (eb_hi_zero_f1a_h),
    .ea_lo_zero_f1a_h (ea_lo_zero_f1a_h),
    .eb_lo_zero_f1a_h (eb_lo_zero_f1a_h),
    .flog_mul_prod_zero_f1a_h (flog_mul_prod_zero_f1a_h),
    .minmax_op_f1a_h (orig_minmax_op_f1a_h),
    .prod_sign_hi_f1a_h (orig_prod_sign_hi_f1a_h),
    .prod_sign_lo_f1a_h (orig_prod_sign_lo_f1a_h),
    .eprod_hi_zero_f1a_h (orig_eprod_hi_zero_f1a_h),
    .eprod_lo_zero_f1a_h (orig_eprod_lo_zero_f1a_h),
    .norm_f32_ovf_f1a_h (orig_norm_f32_ovf_f1a_h),
    .norm_one_out_f1a_h (orig_norm_one_out_f1a_h),
    .paddin1_sels_f1a_h (orig_paddin1_sels_f1a_h),
    .paddin2_selc_f1a_h (orig_paddin2_selc_f1a_h),
    .paddin2_selfcneg_f1a_h (orig_paddin2_selfcneg_f1a_h),
    .padd_cin_f1a_h (orig_padd_cin_f1a_h),
    .sel_famask_f1a_h (orig_sel_famask_f1a_h),
    .sel_fcmask_f1a_h (orig_sel_fcmask_f1a_h),
    .fa_en_f1a_h (orig_fa_en_f1a_h),
    .cmd_f1a_h (orig_cmd_f1a_h),
    .use_mul_f1a_h (orig_use_mul_f1a_h)
  );

  txfma_c1 u_new (
    .ctrl_valid_f1a_h (ctrl_valid_f1a_h),
    .sigs_f1a_h (sigs_f1a_h),
    .cmd_in_f1a_h (cmd_in_f1a_h),
    .op_dtype_f1a_h (op_dtype_f1a_h),
    .ea_hi_f1a_h (ea_hi_f1a_h),
    .fa_hi_zero_f1a_h (fa_hi_zero_f1a_h),
    .sa_hi_f1a_h (sa_hi_f1a_h),
    .sb_hi_f1a_h (sb_hi_f1a_h),
    .sc_f1a_h (sc_f1a_h),
    .sa_lo_f1a_h (sa_lo_f1a_h),
    .sb_lo_f1a_h (sb_lo_f1a_h),
    .ea_hi_zero_f1a_h (ea_hi_zero_f1a_h),
    .eb_hi_zero_f1a_h (eb_hi_zero_f1a_h),
    .ea_lo_zero_f1a_h (ea_lo_zero_f1a_h),
    .eb_lo_zero_f1a_h (eb_lo_zero_f1a_h),
    .flog_mul_prod_zero_f1a_h (flog_mul_prod_zero_f1a_h),
    .minmax_op_f1a_h (new_minmax_op_f1a_h),
    .prod_sign_hi_f1a_h (new_prod_sign_hi_f1a_h),
    .prod_sign_lo_f1a_h (new_prod_sign_lo_f1a_h),
    .eprod_hi_zero_f1a_h (new_eprod_hi_zero_f1a_h),
    .eprod_lo_zero_f1a_h (new_eprod_lo_zero_f1a_h),
    .norm_f32_ovf_f1a_h (new_norm_f32_ovf_f1a_h),
    .norm_one_out_f1a_h (new_norm_one_out_f1a_h),
    .paddin1_sels_f1a_h (new_paddin1_sels_f1a_h),
    .paddin2_selc_f1a_h (new_paddin2_selc_f1a_h),
    .paddin2_selfcneg_f1a_h (new_paddin2_selfcneg_f1a_h),
    .padd_cin_f1a_h (new_padd_cin_f1a_h),
    .sel_famask_f1a_h (new_sel_famask_f1a_h),
    .sel_fcmask_f1a_h (new_sel_fcmask_f1a_h),
    .fa_en_f1a_h (new_fa_en_f1a_h),
    .cmd_f1a_h (new_cmd_f1a_h),
    .use_mul_f1a_h (new_use_mul_f1a_h)
  );

endmodule : cosim_txfma_c1_tb
