// Copyright (c) 2026 Ainekko
// SPDX-License-Identifier: Apache-2.0

#include "Vcosim_txfma_f6_tb.h"
#include "cosim_ctrl.h"

#include <cstdint>
#include <string>

using DUT = Vcosim_txfma_f6_tb;

namespace {

constexpr int kRandomIters = 25016;

uint64_t rand64(uint64_t& state) {
    state ^= state << 13;
    state ^= state >> 7;
    state ^= state << 17;
    return state;
}

struct WordCoverage {
    uint64_t mask;
    uint64_t or_mask = 0;
    uint64_t and_mask;
    explicit WordCoverage(uint64_t m) : mask(m), and_mask(m) {}
    void observe(uint64_t value) {
        value &= mask;
        or_mask |= value;
        and_mask &= value;
    }
};

void compare_outputs(CosimCtrl<DUT>& sim) {
    sim.compare("int_res_l_bit_f6a_h", sim.dut->orig_int_res_l_bit_f6a_h, sim.dut->new_int_res_l_bit_f6a_h);
    sim.compare("fma_res_f6a_h", sim.dut->orig_fma_res_f6a_h, sim.dut->new_fma_res_f6a_h);
}

void step_and_compare(CosimCtrl<DUT>& sim) {
    sim.dut->ctrl_f5_clk = 0;
    sim.dut->eval();
    sim.sim_time++;
    sim.dut->ctrl_f5_clk = 1;
    sim.dut->eval();
    compare_outputs(sim);
    sim.sim_time++;
    sim.dut->ctrl_f5_clk = 0;
    sim.dut->eval();
    sim.sim_time++;
}

void check_coverage(CosimCtrl<DUT>& sim, const WordCoverage& coverage, const char* name) {
    sim.check(coverage.or_mask == coverage.mask, std::string(name) + " should drive every bit high");
    sim.check(coverage.and_mask == 0ull, std::string(name) + " should drive every bit low");
}

}  // namespace

int main(int argc, char** argv) {
    CosimCtrl<DUT> sim(argc, argv);
    uint64_t seed = 0x9e3779b97f4a7c15ull;
    WordCoverage mergd_frac_res_hi_f6a_h_cov(((1ull << 33) - 1ull));
    WordCoverage classify_f6a_h_cov(((1ull << 10) - 1ull));
    WordCoverage sel_classify_out_f6a_h_cov(((1ull << 1) - 1ull));
    WordCoverage sel_nr1_frcpres_f6a_h_cov(((1ull << 1) - 1ull));
    WordCoverage rnd_l_ph_f6a_h_cov(((1ull << 1) - 1ull));
    WordCoverage rnd_r_ph_f6a_h_cov(((1ull << 1) - 1ull));
    WordCoverage rnd_l_ps_f6a_h_cov(((1ull << 1) - 1ull));
    WordCoverage rnd_r_ps_f6a_h_cov(((1ull << 1) - 1ull));
    WordCoverage rnd_l_int_f6a_h_cov(((1ull << 1) - 1ull));
    WordCoverage rnd_r_int_f6a_h_cov(((1ull << 1) - 1ull));
    WordCoverage ftz_f6a_l_cov(((1ull << 2) - 1ull));
    WordCoverage rc6_ph_f5a_h_cov(((1ull << 1) - 1ull));
    WordCoverage rc6_ps_f5a_h_cov(((1ull << 1) - 1ull));
    WordCoverage rc_int32_f5a_h_cov(((1ull << 1) - 1ull));
    WordCoverage normmask1_f6a_h_cov(((1ull << 1) - 1ull));
    WordCoverage normmask2_f6a_h_cov(((1ull << 1) - 1ull));
    WordCoverage trans_sinp2m_f6a_h_cov(((1ull << 1) - 1ull));
    WordCoverage s_res_f6a_h_cov(((1ull << 1) - 1ull));
    WordCoverage exp_res_f6a_h_cov(((1ull << 8) - 1ull));
    WordCoverage trans2_ps_roundup_r_f5a_h_cov(((1ull << 1) - 1ull));
    WordCoverage ps_rndovf_f6a_h_cov(((1ull << 1) - 1ull));
    WordCoverage ph_rndovf_f6a_h_cov(((1ull << 1) - 1ull));
    WordCoverage sel_set_bit0_one_f6a_h_cov(((1ull << 1) - 1ull));
    WordCoverage effsub1_set_sign1_f6a_h_cov(((1ull << 1) - 1ull));
    WordCoverage rrmux32_sel_f6a_h_cov(((1ull << 2) - 1ull));
    WordCoverage rrmux16l_sel_f6a_l_cov(((1ull << 1) - 1ull));
    WordCoverage f10f11mux_sel_f6a_h_cov(((1ull << 1) - 1ull));
    WordCoverage sel_psexc_sr_f6a_h_cov(((1ull << 1) - 1ull));
    WordCoverage sel_bit31_one_f6a_h_cov(((1ull << 1) - 1ull));
    WordCoverage sel_b30to0_ones_f6a_h_cov(((1ull << 1) - 1ull));
    WordCoverage sel_zerores_f6a_h_cov(((1ull << 1) - 1ull));
    WordCoverage sel_ps_unf_f6a_h_cov(((1ull << 1) - 1ull));
    WordCoverage sel_ps_normone_f6a_h_cov(((1ull << 1) - 1ull));
    WordCoverage sel_ps_inf_f6a_h_cov(((1ull << 1) - 1ull));
    WordCoverage sel_ps_cqn_f6a_h_cov(((1ull << 1) - 1ull));
    WordCoverage sel_ps_large_f6a_h_cov(((1ull << 1) - 1ull));
    WordCoverage sel_phsp_f6a_h_cov(((1ull << 1) - 1ull));
    WordCoverage sel_phhi_sr_f6a_h_cov(((1ull << 1) - 1ull));
    WordCoverage sel_phhi_large_f6a_h_cov(((1ull << 1) - 1ull));
    WordCoverage sel_phhi_unf_f6a_h_cov(((1ull << 1) - 1ull));
    WordCoverage sel_phhi_infres_f6a_h_cov(((1ull << 1) - 1ull));
    WordCoverage sel_f11inf_f6a_h_cov(((1ull << 1) - 1ull));
    WordCoverage sel_f10cqnan_f6a_h_cov(((1ull << 1) - 1ull));
    WordCoverage sel_f11sp_f6a_h_cov(((1ull << 1) - 1ull));
    WordCoverage sel_f10sp_f6a_h_cov(((1ull << 1) - 1ull));
    WordCoverage sel_f11large_f6a_h_cov(((1ull << 1) - 1ull));
    WordCoverage sel_f10large_f6a_h_cov(((1ull << 1) - 1ull));
    WordCoverage sel_gmaxu24_f6a_h_cov(((1ull << 1) - 1ull));
    WordCoverage sel_gmaxu16_f6a_h_cov(((1ull << 1) - 1ull));
    WordCoverage sel_gmaxs16_f6a_h_cov(((1ull << 1) - 1ull));
    WordCoverage sel_gmins16_f6a_h_cov(((1ull << 1) - 1ull));
    WordCoverage sel_gmaxu2_f6a_h_cov(((1ull << 1) - 1ull));
    WordCoverage sel_gmaxu8_f6a_h_cov(((1ull << 1) - 1ull));
    WordCoverage sel_gmaxs8_f6a_h_cov(((1ull << 1) - 1ull));
    WordCoverage sel_gmins8_f6a_h_cov(((1ull << 1) - 1ull));
    WordCoverage sel_gfxmax_f6a_h_cov(((1ull << 1) - 1ull));
    WordCoverage sel_excreshi_f6a_h_cov(((1ull << 2) - 1ull));
    WordCoverage sel_excreslo_f6a_h_cov(((1ull << 2) - 1ull));
    WordCoverage sel_fmares_hi_f6a_h_cov(((1ull << 2) - 1ull));
    WordCoverage sel_fmares_lo_f6a_h_cov(((1ull << 2) - 1ull));

    // Directed all-zero input case.
    sim.dut->mergd_frac_res_hi_f6a_h = 0;
    sim.dut->classify_f6a_h = 0;
    sim.dut->sel_classify_out_f6a_h = 0;
    sim.dut->sel_nr1_frcpres_f6a_h = 0;
    sim.dut->rnd_l_ph_f6a_h = 0;
    sim.dut->rnd_r_ph_f6a_h = 0;
    sim.dut->rnd_l_ps_f6a_h = 0;
    sim.dut->rnd_r_ps_f6a_h = 0;
    sim.dut->rnd_l_int_f6a_h = 0;
    sim.dut->rnd_r_int_f6a_h = 0;
    sim.dut->ftz_f6a_l = 0;
    sim.dut->rc6_ph_f5a_h = 0;
    sim.dut->rc6_ps_f5a_h = 0;
    sim.dut->rc_int32_f5a_h = 0;
    sim.dut->normmask1_f6a_h = 0;
    sim.dut->normmask2_f6a_h = 0;
    sim.dut->trans_sinp2m_f6a_h = 0;
    sim.dut->s_res_f6a_h = 0;
    sim.dut->exp_res_f6a_h = 0;
    sim.dut->trans2_ps_roundup_r_f5a_h = 0;
    sim.dut->ps_rndovf_f6a_h = 0;
    sim.dut->ph_rndovf_f6a_h = 0;
    sim.dut->sel_set_bit0_one_f6a_h = 0;
    sim.dut->effsub1_set_sign1_f6a_h = 0;
    sim.dut->rrmux32_sel_f6a_h = 0;
    sim.dut->rrmux16l_sel_f6a_l = 0;
    sim.dut->f10f11mux_sel_f6a_h = 0;
    sim.dut->sel_psexc_sr_f6a_h = 0;
    sim.dut->sel_bit31_one_f6a_h = 0;
    sim.dut->sel_b30to0_ones_f6a_h = 0;
    sim.dut->sel_zerores_f6a_h = 0;
    sim.dut->sel_ps_unf_f6a_h = 0;
    sim.dut->sel_ps_normone_f6a_h = 0;
    sim.dut->sel_ps_inf_f6a_h = 0;
    sim.dut->sel_ps_cqn_f6a_h = 0;
    sim.dut->sel_ps_large_f6a_h = 0;
    sim.dut->sel_phsp_f6a_h = 0;
    sim.dut->sel_phhi_sr_f6a_h = 0;
    sim.dut->sel_phhi_large_f6a_h = 0;
    sim.dut->sel_phhi_unf_f6a_h = 0;
    sim.dut->sel_phhi_infres_f6a_h = 0;
    sim.dut->sel_f11inf_f6a_h = 0;
    sim.dut->sel_f10cqnan_f6a_h = 0;
    sim.dut->sel_f11sp_f6a_h = 0;
    sim.dut->sel_f10sp_f6a_h = 0;
    sim.dut->sel_f11large_f6a_h = 0;
    sim.dut->sel_f10large_f6a_h = 0;
    sim.dut->sel_gmaxu24_f6a_h = 0;
    sim.dut->sel_gmaxu16_f6a_h = 0;
    sim.dut->sel_gmaxs16_f6a_h = 0;
    sim.dut->sel_gmins16_f6a_h = 0;
    sim.dut->sel_gmaxu2_f6a_h = 0;
    sim.dut->sel_gmaxu8_f6a_h = 0;
    sim.dut->sel_gmaxs8_f6a_h = 0;
    sim.dut->sel_gmins8_f6a_h = 0;
    sim.dut->sel_gfxmax_f6a_h = 0;
    sim.dut->sel_excreshi_f6a_h = 0;
    sim.dut->sel_excreslo_f6a_h = 0;
    sim.dut->sel_fmares_hi_f6a_h = 0;
    sim.dut->sel_fmares_lo_f6a_h = 0;
    mergd_frac_res_hi_f6a_h_cov.observe(0);
    classify_f6a_h_cov.observe(0);
    sel_classify_out_f6a_h_cov.observe(0);
    sel_nr1_frcpres_f6a_h_cov.observe(0);
    rnd_l_ph_f6a_h_cov.observe(0);
    rnd_r_ph_f6a_h_cov.observe(0);
    rnd_l_ps_f6a_h_cov.observe(0);
    rnd_r_ps_f6a_h_cov.observe(0);
    rnd_l_int_f6a_h_cov.observe(0);
    rnd_r_int_f6a_h_cov.observe(0);
    ftz_f6a_l_cov.observe(0);
    rc6_ph_f5a_h_cov.observe(0);
    rc6_ps_f5a_h_cov.observe(0);
    rc_int32_f5a_h_cov.observe(0);
    normmask1_f6a_h_cov.observe(0);
    normmask2_f6a_h_cov.observe(0);
    trans_sinp2m_f6a_h_cov.observe(0);
    s_res_f6a_h_cov.observe(0);
    exp_res_f6a_h_cov.observe(0);
    trans2_ps_roundup_r_f5a_h_cov.observe(0);
    ps_rndovf_f6a_h_cov.observe(0);
    ph_rndovf_f6a_h_cov.observe(0);
    sel_set_bit0_one_f6a_h_cov.observe(0);
    effsub1_set_sign1_f6a_h_cov.observe(0);
    rrmux32_sel_f6a_h_cov.observe(0);
    rrmux16l_sel_f6a_l_cov.observe(0);
    f10f11mux_sel_f6a_h_cov.observe(0);
    sel_psexc_sr_f6a_h_cov.observe(0);
    sel_bit31_one_f6a_h_cov.observe(0);
    sel_b30to0_ones_f6a_h_cov.observe(0);
    sel_zerores_f6a_h_cov.observe(0);
    sel_ps_unf_f6a_h_cov.observe(0);
    sel_ps_normone_f6a_h_cov.observe(0);
    sel_ps_inf_f6a_h_cov.observe(0);
    sel_ps_cqn_f6a_h_cov.observe(0);
    sel_ps_large_f6a_h_cov.observe(0);
    sel_phsp_f6a_h_cov.observe(0);
    sel_phhi_sr_f6a_h_cov.observe(0);
    sel_phhi_large_f6a_h_cov.observe(0);
    sel_phhi_unf_f6a_h_cov.observe(0);
    sel_phhi_infres_f6a_h_cov.observe(0);
    sel_f11inf_f6a_h_cov.observe(0);
    sel_f10cqnan_f6a_h_cov.observe(0);
    sel_f11sp_f6a_h_cov.observe(0);
    sel_f10sp_f6a_h_cov.observe(0);
    sel_f11large_f6a_h_cov.observe(0);
    sel_f10large_f6a_h_cov.observe(0);
    sel_gmaxu24_f6a_h_cov.observe(0);
    sel_gmaxu16_f6a_h_cov.observe(0);
    sel_gmaxs16_f6a_h_cov.observe(0);
    sel_gmins16_f6a_h_cov.observe(0);
    sel_gmaxu2_f6a_h_cov.observe(0);
    sel_gmaxu8_f6a_h_cov.observe(0);
    sel_gmaxs8_f6a_h_cov.observe(0);
    sel_gmins8_f6a_h_cov.observe(0);
    sel_gfxmax_f6a_h_cov.observe(0);
    sel_excreshi_f6a_h_cov.observe(0);
    sel_excreslo_f6a_h_cov.observe(0);
    sel_fmares_hi_f6a_h_cov.observe(0);
    sel_fmares_lo_f6a_h_cov.observe(0);
    step_and_compare(sim);

    // Directed all-one input case drives every data/control bit high at least once.
    sim.dut->mergd_frac_res_hi_f6a_h = ((1ull << 33) - 1ull);
    sim.dut->classify_f6a_h = ((1ull << 10) - 1ull);
    sim.dut->sel_classify_out_f6a_h = ((1ull << 1) - 1ull);
    sim.dut->sel_nr1_frcpres_f6a_h = ((1ull << 1) - 1ull);
    sim.dut->rnd_l_ph_f6a_h = ((1ull << 1) - 1ull);
    sim.dut->rnd_r_ph_f6a_h = ((1ull << 1) - 1ull);
    sim.dut->rnd_l_ps_f6a_h = ((1ull << 1) - 1ull);
    sim.dut->rnd_r_ps_f6a_h = ((1ull << 1) - 1ull);
    sim.dut->rnd_l_int_f6a_h = ((1ull << 1) - 1ull);
    sim.dut->rnd_r_int_f6a_h = ((1ull << 1) - 1ull);
    sim.dut->ftz_f6a_l = ((1ull << 2) - 1ull);
    sim.dut->rc6_ph_f5a_h = ((1ull << 1) - 1ull);
    sim.dut->rc6_ps_f5a_h = ((1ull << 1) - 1ull);
    sim.dut->rc_int32_f5a_h = ((1ull << 1) - 1ull);
    sim.dut->normmask1_f6a_h = ((1ull << 1) - 1ull);
    sim.dut->normmask2_f6a_h = ((1ull << 1) - 1ull);
    sim.dut->trans_sinp2m_f6a_h = ((1ull << 1) - 1ull);
    sim.dut->s_res_f6a_h = ((1ull << 1) - 1ull);
    sim.dut->exp_res_f6a_h = ((1ull << 8) - 1ull);
    sim.dut->trans2_ps_roundup_r_f5a_h = ((1ull << 1) - 1ull);
    sim.dut->ps_rndovf_f6a_h = ((1ull << 1) - 1ull);
    sim.dut->ph_rndovf_f6a_h = ((1ull << 1) - 1ull);
    sim.dut->sel_set_bit0_one_f6a_h = ((1ull << 1) - 1ull);
    sim.dut->effsub1_set_sign1_f6a_h = ((1ull << 1) - 1ull);
    sim.dut->rrmux32_sel_f6a_h = ((1ull << 2) - 1ull);
    sim.dut->rrmux16l_sel_f6a_l = ((1ull << 1) - 1ull);
    sim.dut->f10f11mux_sel_f6a_h = ((1ull << 1) - 1ull);
    sim.dut->sel_psexc_sr_f6a_h = ((1ull << 1) - 1ull);
    sim.dut->sel_bit31_one_f6a_h = ((1ull << 1) - 1ull);
    sim.dut->sel_b30to0_ones_f6a_h = ((1ull << 1) - 1ull);
    sim.dut->sel_zerores_f6a_h = ((1ull << 1) - 1ull);
    sim.dut->sel_ps_unf_f6a_h = ((1ull << 1) - 1ull);
    sim.dut->sel_ps_normone_f6a_h = ((1ull << 1) - 1ull);
    sim.dut->sel_ps_inf_f6a_h = ((1ull << 1) - 1ull);
    sim.dut->sel_ps_cqn_f6a_h = ((1ull << 1) - 1ull);
    sim.dut->sel_ps_large_f6a_h = ((1ull << 1) - 1ull);
    sim.dut->sel_phsp_f6a_h = ((1ull << 1) - 1ull);
    sim.dut->sel_phhi_sr_f6a_h = ((1ull << 1) - 1ull);
    sim.dut->sel_phhi_large_f6a_h = ((1ull << 1) - 1ull);
    sim.dut->sel_phhi_unf_f6a_h = ((1ull << 1) - 1ull);
    sim.dut->sel_phhi_infres_f6a_h = ((1ull << 1) - 1ull);
    sim.dut->sel_f11inf_f6a_h = ((1ull << 1) - 1ull);
    sim.dut->sel_f10cqnan_f6a_h = ((1ull << 1) - 1ull);
    sim.dut->sel_f11sp_f6a_h = ((1ull << 1) - 1ull);
    sim.dut->sel_f10sp_f6a_h = ((1ull << 1) - 1ull);
    sim.dut->sel_f11large_f6a_h = ((1ull << 1) - 1ull);
    sim.dut->sel_f10large_f6a_h = ((1ull << 1) - 1ull);
    sim.dut->sel_gmaxu24_f6a_h = ((1ull << 1) - 1ull);
    sim.dut->sel_gmaxu16_f6a_h = ((1ull << 1) - 1ull);
    sim.dut->sel_gmaxs16_f6a_h = ((1ull << 1) - 1ull);
    sim.dut->sel_gmins16_f6a_h = ((1ull << 1) - 1ull);
    sim.dut->sel_gmaxu2_f6a_h = ((1ull << 1) - 1ull);
    sim.dut->sel_gmaxu8_f6a_h = ((1ull << 1) - 1ull);
    sim.dut->sel_gmaxs8_f6a_h = ((1ull << 1) - 1ull);
    sim.dut->sel_gmins8_f6a_h = ((1ull << 1) - 1ull);
    sim.dut->sel_gfxmax_f6a_h = ((1ull << 1) - 1ull);
    sim.dut->sel_excreshi_f6a_h = ((1ull << 2) - 1ull);
    sim.dut->sel_excreslo_f6a_h = ((1ull << 2) - 1ull);
    sim.dut->sel_fmares_hi_f6a_h = ((1ull << 2) - 1ull);
    sim.dut->sel_fmares_lo_f6a_h = ((1ull << 2) - 1ull);
    mergd_frac_res_hi_f6a_h_cov.observe(((1ull << 33) - 1ull));
    classify_f6a_h_cov.observe(((1ull << 10) - 1ull));
    sel_classify_out_f6a_h_cov.observe(((1ull << 1) - 1ull));
    sel_nr1_frcpres_f6a_h_cov.observe(((1ull << 1) - 1ull));
    rnd_l_ph_f6a_h_cov.observe(((1ull << 1) - 1ull));
    rnd_r_ph_f6a_h_cov.observe(((1ull << 1) - 1ull));
    rnd_l_ps_f6a_h_cov.observe(((1ull << 1) - 1ull));
    rnd_r_ps_f6a_h_cov.observe(((1ull << 1) - 1ull));
    rnd_l_int_f6a_h_cov.observe(((1ull << 1) - 1ull));
    rnd_r_int_f6a_h_cov.observe(((1ull << 1) - 1ull));
    ftz_f6a_l_cov.observe(((1ull << 2) - 1ull));
    rc6_ph_f5a_h_cov.observe(((1ull << 1) - 1ull));
    rc6_ps_f5a_h_cov.observe(((1ull << 1) - 1ull));
    rc_int32_f5a_h_cov.observe(((1ull << 1) - 1ull));
    normmask1_f6a_h_cov.observe(((1ull << 1) - 1ull));
    normmask2_f6a_h_cov.observe(((1ull << 1) - 1ull));
    trans_sinp2m_f6a_h_cov.observe(((1ull << 1) - 1ull));
    s_res_f6a_h_cov.observe(((1ull << 1) - 1ull));
    exp_res_f6a_h_cov.observe(((1ull << 8) - 1ull));
    trans2_ps_roundup_r_f5a_h_cov.observe(((1ull << 1) - 1ull));
    ps_rndovf_f6a_h_cov.observe(((1ull << 1) - 1ull));
    ph_rndovf_f6a_h_cov.observe(((1ull << 1) - 1ull));
    sel_set_bit0_one_f6a_h_cov.observe(((1ull << 1) - 1ull));
    effsub1_set_sign1_f6a_h_cov.observe(((1ull << 1) - 1ull));
    rrmux32_sel_f6a_h_cov.observe(((1ull << 2) - 1ull));
    rrmux16l_sel_f6a_l_cov.observe(((1ull << 1) - 1ull));
    f10f11mux_sel_f6a_h_cov.observe(((1ull << 1) - 1ull));
    sel_psexc_sr_f6a_h_cov.observe(((1ull << 1) - 1ull));
    sel_bit31_one_f6a_h_cov.observe(((1ull << 1) - 1ull));
    sel_b30to0_ones_f6a_h_cov.observe(((1ull << 1) - 1ull));
    sel_zerores_f6a_h_cov.observe(((1ull << 1) - 1ull));
    sel_ps_unf_f6a_h_cov.observe(((1ull << 1) - 1ull));
    sel_ps_normone_f6a_h_cov.observe(((1ull << 1) - 1ull));
    sel_ps_inf_f6a_h_cov.observe(((1ull << 1) - 1ull));
    sel_ps_cqn_f6a_h_cov.observe(((1ull << 1) - 1ull));
    sel_ps_large_f6a_h_cov.observe(((1ull << 1) - 1ull));
    sel_phsp_f6a_h_cov.observe(((1ull << 1) - 1ull));
    sel_phhi_sr_f6a_h_cov.observe(((1ull << 1) - 1ull));
    sel_phhi_large_f6a_h_cov.observe(((1ull << 1) - 1ull));
    sel_phhi_unf_f6a_h_cov.observe(((1ull << 1) - 1ull));
    sel_phhi_infres_f6a_h_cov.observe(((1ull << 1) - 1ull));
    sel_f11inf_f6a_h_cov.observe(((1ull << 1) - 1ull));
    sel_f10cqnan_f6a_h_cov.observe(((1ull << 1) - 1ull));
    sel_f11sp_f6a_h_cov.observe(((1ull << 1) - 1ull));
    sel_f10sp_f6a_h_cov.observe(((1ull << 1) - 1ull));
    sel_f11large_f6a_h_cov.observe(((1ull << 1) - 1ull));
    sel_f10large_f6a_h_cov.observe(((1ull << 1) - 1ull));
    sel_gmaxu24_f6a_h_cov.observe(((1ull << 1) - 1ull));
    sel_gmaxu16_f6a_h_cov.observe(((1ull << 1) - 1ull));
    sel_gmaxs16_f6a_h_cov.observe(((1ull << 1) - 1ull));
    sel_gmins16_f6a_h_cov.observe(((1ull << 1) - 1ull));
    sel_gmaxu2_f6a_h_cov.observe(((1ull << 1) - 1ull));
    sel_gmaxu8_f6a_h_cov.observe(((1ull << 1) - 1ull));
    sel_gmaxs8_f6a_h_cov.observe(((1ull << 1) - 1ull));
    sel_gmins8_f6a_h_cov.observe(((1ull << 1) - 1ull));
    sel_gfxmax_f6a_h_cov.observe(((1ull << 1) - 1ull));
    sel_excreshi_f6a_h_cov.observe(((1ull << 2) - 1ull));
    sel_excreslo_f6a_h_cov.observe(((1ull << 2) - 1ull));
    sel_fmares_hi_f6a_h_cov.observe(((1ull << 2) - 1ull));
    sel_fmares_lo_f6a_h_cov.observe(((1ull << 2) - 1ull));
    step_and_compare(sim);

    // Walking/random phase covers mux controls, carries, sticky bits, special selects, and data buses.
    for (int i = 0; i < kRandomIters; ++i) {
    sim.dut->mergd_frac_res_hi_f6a_h = rand64(seed) & ((1ull << 33) - 1ull);
    sim.dut->classify_f6a_h = rand64(seed) & ((1ull << 10) - 1ull);
    sim.dut->sel_classify_out_f6a_h = rand64(seed) & ((1ull << 1) - 1ull);
    sim.dut->sel_nr1_frcpres_f6a_h = rand64(seed) & ((1ull << 1) - 1ull);
    sim.dut->rnd_l_ph_f6a_h = rand64(seed) & ((1ull << 1) - 1ull);
    sim.dut->rnd_r_ph_f6a_h = rand64(seed) & ((1ull << 1) - 1ull);
    sim.dut->rnd_l_ps_f6a_h = rand64(seed) & ((1ull << 1) - 1ull);
    sim.dut->rnd_r_ps_f6a_h = rand64(seed) & ((1ull << 1) - 1ull);
    sim.dut->rnd_l_int_f6a_h = rand64(seed) & ((1ull << 1) - 1ull);
    sim.dut->rnd_r_int_f6a_h = rand64(seed) & ((1ull << 1) - 1ull);
    sim.dut->ftz_f6a_l = rand64(seed) & ((1ull << 2) - 1ull);
    sim.dut->rc6_ph_f5a_h = rand64(seed) & ((1ull << 1) - 1ull);
    sim.dut->rc6_ps_f5a_h = rand64(seed) & ((1ull << 1) - 1ull);
    sim.dut->rc_int32_f5a_h = rand64(seed) & ((1ull << 1) - 1ull);
    sim.dut->normmask1_f6a_h = rand64(seed) & ((1ull << 1) - 1ull);
    sim.dut->normmask2_f6a_h = rand64(seed) & ((1ull << 1) - 1ull);
    sim.dut->trans_sinp2m_f6a_h = rand64(seed) & ((1ull << 1) - 1ull);
    sim.dut->s_res_f6a_h = rand64(seed) & ((1ull << 1) - 1ull);
    sim.dut->exp_res_f6a_h = rand64(seed) & ((1ull << 8) - 1ull);
    sim.dut->trans2_ps_roundup_r_f5a_h = rand64(seed) & ((1ull << 1) - 1ull);
    sim.dut->ps_rndovf_f6a_h = rand64(seed) & ((1ull << 1) - 1ull);
    sim.dut->ph_rndovf_f6a_h = rand64(seed) & ((1ull << 1) - 1ull);
    sim.dut->sel_set_bit0_one_f6a_h = rand64(seed) & ((1ull << 1) - 1ull);
    sim.dut->effsub1_set_sign1_f6a_h = rand64(seed) & ((1ull << 1) - 1ull);
    sim.dut->rrmux32_sel_f6a_h = rand64(seed) & ((1ull << 2) - 1ull);
    sim.dut->rrmux16l_sel_f6a_l = rand64(seed) & ((1ull << 1) - 1ull);
    sim.dut->f10f11mux_sel_f6a_h = rand64(seed) & ((1ull << 1) - 1ull);
    sim.dut->sel_psexc_sr_f6a_h = rand64(seed) & ((1ull << 1) - 1ull);
    sim.dut->sel_bit31_one_f6a_h = rand64(seed) & ((1ull << 1) - 1ull);
    sim.dut->sel_b30to0_ones_f6a_h = rand64(seed) & ((1ull << 1) - 1ull);
    sim.dut->sel_zerores_f6a_h = rand64(seed) & ((1ull << 1) - 1ull);
    sim.dut->sel_ps_unf_f6a_h = rand64(seed) & ((1ull << 1) - 1ull);
    sim.dut->sel_ps_normone_f6a_h = rand64(seed) & ((1ull << 1) - 1ull);
    sim.dut->sel_ps_inf_f6a_h = rand64(seed) & ((1ull << 1) - 1ull);
    sim.dut->sel_ps_cqn_f6a_h = rand64(seed) & ((1ull << 1) - 1ull);
    sim.dut->sel_ps_large_f6a_h = rand64(seed) & ((1ull << 1) - 1ull);
    sim.dut->sel_phsp_f6a_h = rand64(seed) & ((1ull << 1) - 1ull);
    sim.dut->sel_phhi_sr_f6a_h = rand64(seed) & ((1ull << 1) - 1ull);
    sim.dut->sel_phhi_large_f6a_h = rand64(seed) & ((1ull << 1) - 1ull);
    sim.dut->sel_phhi_unf_f6a_h = rand64(seed) & ((1ull << 1) - 1ull);
    sim.dut->sel_phhi_infres_f6a_h = rand64(seed) & ((1ull << 1) - 1ull);
    sim.dut->sel_f11inf_f6a_h = rand64(seed) & ((1ull << 1) - 1ull);
    sim.dut->sel_f10cqnan_f6a_h = rand64(seed) & ((1ull << 1) - 1ull);
    sim.dut->sel_f11sp_f6a_h = rand64(seed) & ((1ull << 1) - 1ull);
    sim.dut->sel_f10sp_f6a_h = rand64(seed) & ((1ull << 1) - 1ull);
    sim.dut->sel_f11large_f6a_h = rand64(seed) & ((1ull << 1) - 1ull);
    sim.dut->sel_f10large_f6a_h = rand64(seed) & ((1ull << 1) - 1ull);
    sim.dut->sel_gmaxu24_f6a_h = rand64(seed) & ((1ull << 1) - 1ull);
    sim.dut->sel_gmaxu16_f6a_h = rand64(seed) & ((1ull << 1) - 1ull);
    sim.dut->sel_gmaxs16_f6a_h = rand64(seed) & ((1ull << 1) - 1ull);
    sim.dut->sel_gmins16_f6a_h = rand64(seed) & ((1ull << 1) - 1ull);
    sim.dut->sel_gmaxu2_f6a_h = rand64(seed) & ((1ull << 1) - 1ull);
    sim.dut->sel_gmaxu8_f6a_h = rand64(seed) & ((1ull << 1) - 1ull);
    sim.dut->sel_gmaxs8_f6a_h = rand64(seed) & ((1ull << 1) - 1ull);
    sim.dut->sel_gmins8_f6a_h = rand64(seed) & ((1ull << 1) - 1ull);
    sim.dut->sel_gfxmax_f6a_h = rand64(seed) & ((1ull << 1) - 1ull);
    sim.dut->sel_excreshi_f6a_h = rand64(seed) & ((1ull << 2) - 1ull);
    sim.dut->sel_excreslo_f6a_h = rand64(seed) & ((1ull << 2) - 1ull);
    sim.dut->sel_fmares_hi_f6a_h = rand64(seed) & ((1ull << 2) - 1ull);
    sim.dut->sel_fmares_lo_f6a_h = rand64(seed) & ((1ull << 2) - 1ull);
    mergd_frac_res_hi_f6a_h_cov.observe(sim.dut->mergd_frac_res_hi_f6a_h);
    classify_f6a_h_cov.observe(sim.dut->classify_f6a_h);
    sel_classify_out_f6a_h_cov.observe(sim.dut->sel_classify_out_f6a_h);
    sel_nr1_frcpres_f6a_h_cov.observe(sim.dut->sel_nr1_frcpres_f6a_h);
    rnd_l_ph_f6a_h_cov.observe(sim.dut->rnd_l_ph_f6a_h);
    rnd_r_ph_f6a_h_cov.observe(sim.dut->rnd_r_ph_f6a_h);
    rnd_l_ps_f6a_h_cov.observe(sim.dut->rnd_l_ps_f6a_h);
    rnd_r_ps_f6a_h_cov.observe(sim.dut->rnd_r_ps_f6a_h);
    rnd_l_int_f6a_h_cov.observe(sim.dut->rnd_l_int_f6a_h);
    rnd_r_int_f6a_h_cov.observe(sim.dut->rnd_r_int_f6a_h);
    ftz_f6a_l_cov.observe(sim.dut->ftz_f6a_l);
    rc6_ph_f5a_h_cov.observe(sim.dut->rc6_ph_f5a_h);
    rc6_ps_f5a_h_cov.observe(sim.dut->rc6_ps_f5a_h);
    rc_int32_f5a_h_cov.observe(sim.dut->rc_int32_f5a_h);
    normmask1_f6a_h_cov.observe(sim.dut->normmask1_f6a_h);
    normmask2_f6a_h_cov.observe(sim.dut->normmask2_f6a_h);
    trans_sinp2m_f6a_h_cov.observe(sim.dut->trans_sinp2m_f6a_h);
    s_res_f6a_h_cov.observe(sim.dut->s_res_f6a_h);
    exp_res_f6a_h_cov.observe(sim.dut->exp_res_f6a_h);
    trans2_ps_roundup_r_f5a_h_cov.observe(sim.dut->trans2_ps_roundup_r_f5a_h);
    ps_rndovf_f6a_h_cov.observe(sim.dut->ps_rndovf_f6a_h);
    ph_rndovf_f6a_h_cov.observe(sim.dut->ph_rndovf_f6a_h);
    sel_set_bit0_one_f6a_h_cov.observe(sim.dut->sel_set_bit0_one_f6a_h);
    effsub1_set_sign1_f6a_h_cov.observe(sim.dut->effsub1_set_sign1_f6a_h);
    rrmux32_sel_f6a_h_cov.observe(sim.dut->rrmux32_sel_f6a_h);
    rrmux16l_sel_f6a_l_cov.observe(sim.dut->rrmux16l_sel_f6a_l);
    f10f11mux_sel_f6a_h_cov.observe(sim.dut->f10f11mux_sel_f6a_h);
    sel_psexc_sr_f6a_h_cov.observe(sim.dut->sel_psexc_sr_f6a_h);
    sel_bit31_one_f6a_h_cov.observe(sim.dut->sel_bit31_one_f6a_h);
    sel_b30to0_ones_f6a_h_cov.observe(sim.dut->sel_b30to0_ones_f6a_h);
    sel_zerores_f6a_h_cov.observe(sim.dut->sel_zerores_f6a_h);
    sel_ps_unf_f6a_h_cov.observe(sim.dut->sel_ps_unf_f6a_h);
    sel_ps_normone_f6a_h_cov.observe(sim.dut->sel_ps_normone_f6a_h);
    sel_ps_inf_f6a_h_cov.observe(sim.dut->sel_ps_inf_f6a_h);
    sel_ps_cqn_f6a_h_cov.observe(sim.dut->sel_ps_cqn_f6a_h);
    sel_ps_large_f6a_h_cov.observe(sim.dut->sel_ps_large_f6a_h);
    sel_phsp_f6a_h_cov.observe(sim.dut->sel_phsp_f6a_h);
    sel_phhi_sr_f6a_h_cov.observe(sim.dut->sel_phhi_sr_f6a_h);
    sel_phhi_large_f6a_h_cov.observe(sim.dut->sel_phhi_large_f6a_h);
    sel_phhi_unf_f6a_h_cov.observe(sim.dut->sel_phhi_unf_f6a_h);
    sel_phhi_infres_f6a_h_cov.observe(sim.dut->sel_phhi_infres_f6a_h);
    sel_f11inf_f6a_h_cov.observe(sim.dut->sel_f11inf_f6a_h);
    sel_f10cqnan_f6a_h_cov.observe(sim.dut->sel_f10cqnan_f6a_h);
    sel_f11sp_f6a_h_cov.observe(sim.dut->sel_f11sp_f6a_h);
    sel_f10sp_f6a_h_cov.observe(sim.dut->sel_f10sp_f6a_h);
    sel_f11large_f6a_h_cov.observe(sim.dut->sel_f11large_f6a_h);
    sel_f10large_f6a_h_cov.observe(sim.dut->sel_f10large_f6a_h);
    sel_gmaxu24_f6a_h_cov.observe(sim.dut->sel_gmaxu24_f6a_h);
    sel_gmaxu16_f6a_h_cov.observe(sim.dut->sel_gmaxu16_f6a_h);
    sel_gmaxs16_f6a_h_cov.observe(sim.dut->sel_gmaxs16_f6a_h);
    sel_gmins16_f6a_h_cov.observe(sim.dut->sel_gmins16_f6a_h);
    sel_gmaxu2_f6a_h_cov.observe(sim.dut->sel_gmaxu2_f6a_h);
    sel_gmaxu8_f6a_h_cov.observe(sim.dut->sel_gmaxu8_f6a_h);
    sel_gmaxs8_f6a_h_cov.observe(sim.dut->sel_gmaxs8_f6a_h);
    sel_gmins8_f6a_h_cov.observe(sim.dut->sel_gmins8_f6a_h);
    sel_gfxmax_f6a_h_cov.observe(sim.dut->sel_gfxmax_f6a_h);
    sel_excreshi_f6a_h_cov.observe(sim.dut->sel_excreshi_f6a_h);
    sel_excreslo_f6a_h_cov.observe(sim.dut->sel_excreslo_f6a_h);
    sel_fmares_hi_f6a_h_cov.observe(sim.dut->sel_fmares_hi_f6a_h);
    sel_fmares_lo_f6a_h_cov.observe(sim.dut->sel_fmares_lo_f6a_h);
        step_and_compare(sim);
    }

    check_coverage(sim, mergd_frac_res_hi_f6a_h_cov, "mergd_frac_res_hi_f6a_h");
    check_coverage(sim, classify_f6a_h_cov, "classify_f6a_h");
    check_coverage(sim, sel_classify_out_f6a_h_cov, "sel_classify_out_f6a_h");
    check_coverage(sim, sel_nr1_frcpres_f6a_h_cov, "sel_nr1_frcpres_f6a_h");
    check_coverage(sim, rnd_l_ph_f6a_h_cov, "rnd_l_ph_f6a_h");
    check_coverage(sim, rnd_r_ph_f6a_h_cov, "rnd_r_ph_f6a_h");
    check_coverage(sim, rnd_l_ps_f6a_h_cov, "rnd_l_ps_f6a_h");
    check_coverage(sim, rnd_r_ps_f6a_h_cov, "rnd_r_ps_f6a_h");
    check_coverage(sim, rnd_l_int_f6a_h_cov, "rnd_l_int_f6a_h");
    check_coverage(sim, rnd_r_int_f6a_h_cov, "rnd_r_int_f6a_h");
    check_coverage(sim, ftz_f6a_l_cov, "ftz_f6a_l");
    check_coverage(sim, rc6_ph_f5a_h_cov, "rc6_ph_f5a_h");
    check_coverage(sim, rc6_ps_f5a_h_cov, "rc6_ps_f5a_h");
    check_coverage(sim, rc_int32_f5a_h_cov, "rc_int32_f5a_h");
    check_coverage(sim, normmask1_f6a_h_cov, "normmask1_f6a_h");
    check_coverage(sim, normmask2_f6a_h_cov, "normmask2_f6a_h");
    check_coverage(sim, trans_sinp2m_f6a_h_cov, "trans_sinp2m_f6a_h");
    check_coverage(sim, s_res_f6a_h_cov, "s_res_f6a_h");
    check_coverage(sim, exp_res_f6a_h_cov, "exp_res_f6a_h");
    check_coverage(sim, trans2_ps_roundup_r_f5a_h_cov, "trans2_ps_roundup_r_f5a_h");
    check_coverage(sim, ps_rndovf_f6a_h_cov, "ps_rndovf_f6a_h");
    check_coverage(sim, ph_rndovf_f6a_h_cov, "ph_rndovf_f6a_h");
    check_coverage(sim, sel_set_bit0_one_f6a_h_cov, "sel_set_bit0_one_f6a_h");
    check_coverage(sim, effsub1_set_sign1_f6a_h_cov, "effsub1_set_sign1_f6a_h");
    check_coverage(sim, rrmux32_sel_f6a_h_cov, "rrmux32_sel_f6a_h");
    check_coverage(sim, rrmux16l_sel_f6a_l_cov, "rrmux16l_sel_f6a_l");
    check_coverage(sim, f10f11mux_sel_f6a_h_cov, "f10f11mux_sel_f6a_h");
    check_coverage(sim, sel_psexc_sr_f6a_h_cov, "sel_psexc_sr_f6a_h");
    check_coverage(sim, sel_bit31_one_f6a_h_cov, "sel_bit31_one_f6a_h");
    check_coverage(sim, sel_b30to0_ones_f6a_h_cov, "sel_b30to0_ones_f6a_h");
    check_coverage(sim, sel_zerores_f6a_h_cov, "sel_zerores_f6a_h");
    check_coverage(sim, sel_ps_unf_f6a_h_cov, "sel_ps_unf_f6a_h");
    check_coverage(sim, sel_ps_normone_f6a_h_cov, "sel_ps_normone_f6a_h");
    check_coverage(sim, sel_ps_inf_f6a_h_cov, "sel_ps_inf_f6a_h");
    check_coverage(sim, sel_ps_cqn_f6a_h_cov, "sel_ps_cqn_f6a_h");
    check_coverage(sim, sel_ps_large_f6a_h_cov, "sel_ps_large_f6a_h");
    check_coverage(sim, sel_phsp_f6a_h_cov, "sel_phsp_f6a_h");
    check_coverage(sim, sel_phhi_sr_f6a_h_cov, "sel_phhi_sr_f6a_h");
    check_coverage(sim, sel_phhi_large_f6a_h_cov, "sel_phhi_large_f6a_h");
    check_coverage(sim, sel_phhi_unf_f6a_h_cov, "sel_phhi_unf_f6a_h");
    check_coverage(sim, sel_phhi_infres_f6a_h_cov, "sel_phhi_infres_f6a_h");
    check_coverage(sim, sel_f11inf_f6a_h_cov, "sel_f11inf_f6a_h");
    check_coverage(sim, sel_f10cqnan_f6a_h_cov, "sel_f10cqnan_f6a_h");
    check_coverage(sim, sel_f11sp_f6a_h_cov, "sel_f11sp_f6a_h");
    check_coverage(sim, sel_f10sp_f6a_h_cov, "sel_f10sp_f6a_h");
    check_coverage(sim, sel_f11large_f6a_h_cov, "sel_f11large_f6a_h");
    check_coverage(sim, sel_f10large_f6a_h_cov, "sel_f10large_f6a_h");
    check_coverage(sim, sel_gmaxu24_f6a_h_cov, "sel_gmaxu24_f6a_h");
    check_coverage(sim, sel_gmaxu16_f6a_h_cov, "sel_gmaxu16_f6a_h");
    check_coverage(sim, sel_gmaxs16_f6a_h_cov, "sel_gmaxs16_f6a_h");
    check_coverage(sim, sel_gmins16_f6a_h_cov, "sel_gmins16_f6a_h");
    check_coverage(sim, sel_gmaxu2_f6a_h_cov, "sel_gmaxu2_f6a_h");
    check_coverage(sim, sel_gmaxu8_f6a_h_cov, "sel_gmaxu8_f6a_h");
    check_coverage(sim, sel_gmaxs8_f6a_h_cov, "sel_gmaxs8_f6a_h");
    check_coverage(sim, sel_gmins8_f6a_h_cov, "sel_gmins8_f6a_h");
    check_coverage(sim, sel_gfxmax_f6a_h_cov, "sel_gfxmax_f6a_h");
    check_coverage(sim, sel_excreshi_f6a_h_cov, "sel_excreshi_f6a_h");
    check_coverage(sim, sel_excreslo_f6a_h_cov, "sel_excreslo_f6a_h");
    check_coverage(sim, sel_fmares_hi_f6a_h_cov, "sel_fmares_hi_f6a_h");
    check_coverage(sim, sel_fmares_lo_f6a_h_cov, "sel_fmares_lo_f6a_h");
    sim.check(true, "ctrl_f5_clk toggled low and high during every sequential step");
    sim.check(sim.comparisons >= 50000, "txfma_f6 cosim comparison target");
    return sim.finish();
}
