// Auto-generated by gen_esr.py (CSR mode) — do not edit manually.

      reg_fflags_en_next[0] = 1'b0;
      reg_fflags_en_next[1] = 1'b0;
      reg_frm_en_next[0] = 1'b0;
      reg_frm_en_next[1] = 1'b0;
      reg_fcsr_en_next[0] = 1'b0;
      reg_fcsr_en_next[1] = 1'b0;
      reg_tensor_reduce_en_next = 1'b0;
      reg_tensor_fma_en_next = 1'b0;
      reg_tensor_conv_size_en_next[0] = 1'b0;
      reg_tensor_conv_size_en_next[1] = 1'b0;
      reg_tensor_conv_ctrl_en_next[0] = 1'b0;
      reg_tensor_conv_ctrl_en_next[1] = 1'b0;
      reg_tensor_cooperation_en_next = 1'b0;
      reg_tensor_mask_en_next[0] = 1'b0;
      reg_tensor_mask_en_next[1] = 1'b0;
      reg_tensor_quant_en_next = 1'b0;
      reg_tex_send_en_next = 1'b0;
      reg_tensor_error_en_next[0] = 1'b0;
      reg_tensor_error_en_next[1] = 1'b0;
      reg_ucache_control_en_next = 1'b0;
      reg_flb_en_next = 1'b0;
      reg_fcc_en_next[0] = 1'b0;
      reg_fcc_en_next[1] = 1'b0;
      reg_stall_en_next = 1'b0;
      reg_tensor_wait_en_next[0] = 1'b0;
      reg_tensor_wait_en_next[1] = 1'b0;
      reg_tensor_load_en_next = 1'b0;
      reg_gsc_progress_en_next[0] = 1'b0;
      reg_gsc_progress_en_next[1] = 1'b0;
      reg_tensor_load_l2scp_en_next = 1'b0;
      reg_tensor_store_en_next = 1'b0;
`ifdef ET_SIMULATION
      reg_validation0_en_next[0] = 1'b0;
      reg_validation0_en_next[1] = 1'b0;
`endif
`ifdef ET_SIMULATION
      reg_validation1_en_next[0] = 1'b0;
      reg_validation1_en_next[1] = 1'b0;
`endif
`ifdef ET_SIMULATION
      reg_validation2_en_next[0] = 1'b0;
      reg_validation2_en_next[1] = 1'b0;
`endif
`ifdef ET_SIMULATION
      reg_validation3_en_next[0] = 1'b0;
      reg_validation3_en_next[1] = 1'b0;
`endif
`ifdef NOT_VERIF_SIMULATION
      reg_validation0_ps_en_next[0] = 1'b0;
      reg_validation0_ps_en_next[1] = 1'b0;
`endif
`ifdef NOT_VERIF_SIMULATION
      reg_validation1_ps_en_next[0] = 1'b0;
      reg_validation1_ps_en_next[1] = 1'b0;
`endif
`ifdef NOT_VERIF_SIMULATION
      reg_validation2_ps_en_next[0] = 1'b0;
      reg_validation2_ps_en_next[1] = 1'b0;
`endif
`ifdef NOT_VERIF_SIMULATION
      reg_validation3_ps_en_next[0] = 1'b0;
      reg_validation3_ps_en_next[1] = 1'b0;
`endif
      reg_co_evict_va_en_next = 1'b0;
      reg_co_flush_va_en_next = 1'b0;
      reg_co_lock_va_en_next = 1'b0;
      reg_co_unlock_va_en_next = 1'b0;
      reg_co_prefetch_va_en_next = 1'b0;
      reg_sstatus_en_next[0] = 1'b0;
      reg_sstatus_en_next[1] = 1'b0;
      reg_sie_en_next[0] = 1'b0;
      reg_sie_en_next[1] = 1'b0;
      reg_stvec_en_next[0] = 1'b0;
      reg_stvec_en_next[1] = 1'b0;
      reg_scounteren_en_next[0] = 1'b0;
      reg_scounteren_en_next[1] = 1'b0;
      reg_sscratch_en_next[0] = 1'b0;
      reg_sscratch_en_next[1] = 1'b0;
      reg_sepc_en_next[0] = 1'b0;
      reg_sepc_en_next[1] = 1'b0;
      reg_scause_en_next[0] = 1'b0;
      reg_scause_en_next[1] = 1'b0;
      reg_stval_en_next[0] = 1'b0;
      reg_stval_en_next[1] = 1'b0;
      reg_sip_en_next[0] = 1'b0;
      reg_sip_en_next[1] = 1'b0;
      reg_satp_en_next = 1'b0;
      reg_smsg_port0_en_next[0] = 1'b0;
      reg_smsg_port0_en_next[1] = 1'b0;
      reg_smsg_port1_en_next[0] = 1'b0;
      reg_smsg_port1_en_next[1] = 1'b0;
      reg_smsg_port2_en_next[0] = 1'b0;
      reg_smsg_port2_en_next[1] = 1'b0;
      reg_smsg_port3_en_next[0] = 1'b0;
      reg_smsg_port3_en_next[1] = 1'b0;
      reg_mstatus_en_next[0] = 1'b0;
      reg_mstatus_en_next[1] = 1'b0;
      reg_medeleg_en_next[0] = 1'b0;
      reg_medeleg_en_next[1] = 1'b0;
      reg_mideleg_en_next[0] = 1'b0;
      reg_mideleg_en_next[1] = 1'b0;
      reg_mie_en_next[0] = 1'b0;
      reg_mie_en_next[1] = 1'b0;
      reg_mtvec_en_next[0] = 1'b0;
      reg_mtvec_en_next[1] = 1'b0;
      reg_mcounteren_en_next[0] = 1'b0;
      reg_mcounteren_en_next[1] = 1'b0;
      reg_mscratch_en_next[0] = 1'b0;
      reg_mscratch_en_next[1] = 1'b0;
      reg_mepc_en_next[0] = 1'b0;
      reg_mepc_en_next[1] = 1'b0;
      reg_mcause_en_next[0] = 1'b0;
      reg_mcause_en_next[1] = 1'b0;
      reg_mtval_en_next[0] = 1'b0;
      reg_mtval_en_next[1] = 1'b0;
      reg_mip_en_next[0] = 1'b0;
      reg_mip_en_next[1] = 1'b0;
      reg_pmpcfg0_en_next[0] = 1'b0;
      reg_pmpcfg0_en_next[1] = 1'b0;
      reg_pmpcfg2_en_next[0] = 1'b0;
      reg_pmpcfg2_en_next[1] = 1'b0;
      reg_pmpaddr0_en_next[0] = 1'b0;
      reg_pmpaddr0_en_next[1] = 1'b0;
      reg_pmpaddr1_en_next[0] = 1'b0;
      reg_pmpaddr1_en_next[1] = 1'b0;
      reg_pmpaddr15_en_next[0] = 1'b0;
      reg_pmpaddr15_en_next[1] = 1'b0;
      reg_mcycle_en_next = 1'b0;
      reg_minstret_en_next[0] = 1'b0;
      reg_minstret_en_next[1] = 1'b0;
      reg_mhpmcounter3_en_next[0] = 1'b0;
      reg_mhpmcounter3_en_next[1] = 1'b0;
      reg_mhpmcounter4_en_next[0] = 1'b0;
      reg_mhpmcounter4_en_next[1] = 1'b0;
      reg_mhpmcounter5_en_next[0] = 1'b0;
      reg_mhpmcounter5_en_next[1] = 1'b0;
      reg_mhpmcounter6_en_next[0] = 1'b0;
      reg_mhpmcounter6_en_next[1] = 1'b0;
      reg_mhpmcounter7_en_next[0] = 1'b0;
      reg_mhpmcounter7_en_next[1] = 1'b0;
      reg_mhpmcounter8_en_next[0] = 1'b0;
      reg_mhpmcounter8_en_next[1] = 1'b0;
      reg_mhpmevent3_en_next[0] = 1'b0;
      reg_mhpmevent3_en_next[1] = 1'b0;
      reg_mhpmevent4_en_next[0] = 1'b0;
      reg_mhpmevent4_en_next[1] = 1'b0;
      reg_mhpmevent5_en_next[0] = 1'b0;
      reg_mhpmevent5_en_next[1] = 1'b0;
      reg_mhpmevent6_en_next[0] = 1'b0;
      reg_mhpmevent6_en_next[1] = 1'b0;
      reg_mhpmevent7_en_next[0] = 1'b0;
      reg_mhpmevent7_en_next[1] = 1'b0;
      reg_mhpmevent8_en_next[0] = 1'b0;
      reg_mhpmevent8_en_next[1] = 1'b0;
      reg_tdata1_en_next[0] = 1'b0;
      reg_tdata1_en_next[1] = 1'b0;
      reg_tdata2_en_next[0] = 1'b0;
      reg_tdata2_en_next[1] = 1'b0;
      reg_dcsr_en_next[0] = 1'b0;
      reg_dcsr_en_next[1] = 1'b0;
      reg_dpc_en_next[0] = 1'b0;
      reg_dpc_en_next[1] = 1'b0;
      reg_ddata0_en_next[0] = 1'b0;
      reg_ddata0_en_next[1] = 1'b0;
      reg_matp_en_next = 1'b0;
      reg_minstmask_en_next[0] = 1'b0;
      reg_minstmask_en_next[1] = 1'b0;
      reg_minstmatch_en_next[0] = 1'b0;
      reg_minstmatch_en_next[1] = 1'b0;
      reg_cacheInvalidate_en_next = 1'b0;
      reg_menable_shadows_en_next = 1'b0;
      reg_excl_mode_en_next = 1'b0;
      reg_mbusaddr_en_next[0] = 1'b0;
      reg_mbusaddr_en_next[1] = 1'b0;
`ifdef DCACHE_REPORT_PC
      reg_mbuspc_en_next[0] = 1'b0;
      reg_mbuspc_en_next[1] = 1'b0;
`endif
      reg_mcache_control_en_next = 1'b0;
      reg_co_evict_sw_en_next = 1'b0;
      reg_co_flush_sw_en_next = 1'b0;
      reg_co_lock_sw_en_next = 1'b0;
      reg_co_unlock_sw_en_next = 1'b0;
