// Auto-generated by gen_esr.py (CSR mode) — do not edit manually.

      if (reg_fflags_en[0]) reg_fcsr_next[0] = write_fcsr_as_fflags(reg_fcsr_next[0], write_fflags(wb_wdata[$bits(csr_fflags_t)-1:0]));
      if (reg_fflags_en[1]) reg_fcsr_next[1] = write_fcsr_as_fflags(reg_fcsr_next[1], write_fflags(wb_wdata[$bits(csr_fflags_t)-1:0]));
      if (reg_frm_en[0]) reg_fcsr_next[0] = write_fcsr_as_frm(reg_fcsr_next[0], wb_wdata[$bits(csr_frm_t)-1:0]);
      if (reg_frm_en[1]) reg_fcsr_next[1] = write_fcsr_as_frm(reg_fcsr_next[1], wb_wdata[$bits(csr_frm_t)-1:0]);
      if (reg_sstatus_en[0]) reg_mstatus_next[0] = write_mstatus_as_sstatus(reg_mstatus_next[0], write_sstatus(wb_wdata[$bits(csr_sstatus_t)-1:0]));
      if (reg_sstatus_en[1]) reg_mstatus_next[1] = write_mstatus_as_sstatus(reg_mstatus_next[1], write_sstatus(wb_wdata[$bits(csr_sstatus_t)-1:0]));
      if (reg_sie_en[0]) reg_mie_next[0] = write_mie_as_sie(reg_mie_next[0], sie_wdata[wb_thread_id]);
      if (reg_sie_en[1]) reg_mie_next[1] = write_mie_as_sie(reg_mie_next[1], sie_wdata[wb_thread_id]);
      if (reg_sip_en[0]) reg_mip_next[0] = write_mip_as_sip(reg_mip_next[0], sip_wdata[wb_thread_id]);
      if (reg_sip_en[1]) reg_mip_next[1] = write_mip_as_sip(reg_mip_next[1], sip_wdata[wb_thread_id]);
      if (reg_fcsr_en[0]) reg_fcsr_next[0] = write_fcsr(wb_wdata[$bits(csr_fcsr_t)-1:0]);
      if (reg_fcsr_en[1]) reg_fcsr_next[1] = write_fcsr(wb_wdata[$bits(csr_fcsr_t)-1:0]);
      reg_tensor_fma_next = tensorfma_control'(wb_wdata_1p[$bits(tensorfma_control)-1:0]);
      reg_tensor_fma_latch_clk_en |= reg_tensor_fma_en;
      reg_tensor_conv_size_next[0] = tensorconv_size'(wb_wdata_1p[$bits(tensorconv_size)-1:0]);
      reg_tensor_conv_size_next[1] = tensorconv_size'(wb_wdata_1p[$bits(tensorconv_size)-1:0]);
      reg_tensor_conv_size_latch_clk_en |= reg_tensor_conv_size_en;
      reg_tensor_conv_ctrl_next[0] = tensorconv_control'(wb_wdata_1p[$bits(tensorconv_control)-1:0]);
      reg_tensor_conv_ctrl_next[1] = tensorconv_control'(wb_wdata_1p[$bits(tensorconv_control)-1:0]);
      reg_tensor_conv_ctrl_latch_clk_en |= reg_tensor_conv_ctrl_en;
      reg_tensor_cooperation_next = tensorcoop_control'(wb_wdata_1p[$bits(tensorcoop_control)-1:0]);
      reg_tensor_cooperation_latch_clk_en |= reg_tensor_cooperation_en;
      if (reg_tensor_mask_en[0]) reg_tensor_mask_next[0] = wb_wdata[16-1:0];
      if (reg_tensor_mask_en[1]) reg_tensor_mask_next[1] = wb_wdata[16-1:0];
      reg_tensor_quant_next = tensorquant_control'(wb_wdata_1p[$bits(tensorquant_control)-1:0]);
      reg_tensor_quant_latch_clk_en |= reg_tensor_quant_en;
      if (reg_gsc_progress_en[0]) reg_gsc_progress_next[0] = wb_wdata[3-1:0];
      if (reg_gsc_progress_en[1]) reg_gsc_progress_next[1] = wb_wdata[3-1:0];
`ifdef ET_SIMULATION
      reg_validation0_next[0] = wb_wdata_1p;
      reg_validation0_next[1] = wb_wdata_1p;
      reg_validation0_latch_clk_en |= reg_validation0_en;
`endif
`ifdef ET_SIMULATION
      reg_validation1_next[0] = wb_wdata_1p;
      reg_validation1_next[1] = wb_wdata_1p;
      reg_validation1_latch_clk_en |= reg_validation1_en;
`endif
`ifdef ET_SIMULATION
      reg_validation2_next[0] = wb_wdata_1p;
      reg_validation2_next[1] = wb_wdata_1p;
      reg_validation2_latch_clk_en |= reg_validation2_en;
`endif
`ifdef ET_SIMULATION
      reg_validation3_next[0] = wb_wdata_1p;
      reg_validation3_next[1] = wb_wdata_1p;
      reg_validation3_latch_clk_en |= reg_validation3_en;
`endif
`ifdef NOT_VERIF_SIMULATION
      if (reg_validation0_ps_en[0]) reg_validation0_ps_next[0] = wb_wdata[1-1:0];
      if (reg_validation0_ps_en[1]) reg_validation0_ps_next[1] = wb_wdata[1-1:0];
`endif
`ifdef NOT_VERIF_SIMULATION
      if (reg_validation1_ps_en[0]) reg_validation1_ps_next[0] = wb_wdata[1-1:0];
      if (reg_validation1_ps_en[1]) reg_validation1_ps_next[1] = wb_wdata[1-1:0];
`endif
`ifdef NOT_VERIF_SIMULATION
      if (reg_validation2_ps_en[0]) reg_validation2_ps_next[0] = wb_wdata[1-1:0];
      if (reg_validation2_ps_en[1]) reg_validation2_ps_next[1] = wb_wdata[1-1:0];
`endif
`ifdef NOT_VERIF_SIMULATION
      if (reg_validation3_ps_en[0]) reg_validation3_ps_next[0] = wb_wdata[1-1:0];
      if (reg_validation3_ps_en[1]) reg_validation3_ps_next[1] = wb_wdata[1-1:0];
`endif
      if (reg_stvec_en[0]) reg_stvec_next[0] = extend_VA(wb_wdata);
      if (reg_stvec_en[1]) reg_stvec_next[1] = extend_VA(wb_wdata);
      reg_scounteren_next[0] = wb_wdata_1p[CsrNrCounters-1:0];
      reg_scounteren_next[1] = wb_wdata_1p[CsrNrCounters-1:0];
      reg_scounteren_latch_clk_en |= reg_scounteren_en;
      reg_sscratch_next[0] = wb_wdata_1p;
      reg_sscratch_next[1] = wb_wdata_1p;
      reg_sscratch_latch_clk_en |= reg_sscratch_en;
      if (reg_sepc_en[0]) reg_sepc_next[0] = extend_VA(wb_wdata);
      if (reg_sepc_en[1]) reg_sepc_next[1] = extend_VA(wb_wdata);
      if (reg_scause_en[0]) reg_scause_next[0] = write_cause(wb_wdata[$bits(csr_cause_t)-1:0]);
      if (reg_scause_en[1]) reg_scause_next[1] = write_cause(wb_wdata[$bits(csr_cause_t)-1:0]);
      if (reg_stval_en[0]) reg_stval_next[0] = extend_VA(wb_wdata);
      if (reg_stval_en[1]) reg_stval_next[1] = extend_VA(wb_wdata);
      reg_satp_next = write_satp(wb_wdata_1p[$bits(csr_satp_t)-1:0]);
      reg_satp_latch_clk_en |= reg_satp_en;
      if (reg_mstatus_en[0]) reg_mstatus_next[0] = write_mstatus(wb_wdata[$bits(csr_mstatus_t)-1:0]);
      if (reg_mstatus_en[1]) reg_mstatus_next[1] = write_mstatus(wb_wdata[$bits(csr_mstatus_t)-1:0]);
      reg_medeleg_next[0] = write_medeleg(wb_wdata_1p[$bits(csr_medeleg_t)-1:0]);
      reg_medeleg_next[1] = write_medeleg(wb_wdata_1p[$bits(csr_medeleg_t)-1:0]);
      reg_medeleg_latch_clk_en |= reg_medeleg_en;
      reg_mideleg_next[0] = write_mideleg(wb_wdata_1p[$bits(csr_mideleg_t)-1:0]);
      reg_mideleg_next[1] = write_mideleg(wb_wdata_1p[$bits(csr_mideleg_t)-1:0]);
      reg_mideleg_latch_clk_en |= reg_mideleg_en;
      if (reg_mie_en[0]) reg_mie_next[0] = write_mie(wb_wdata[$bits(csr_mie_t)-1:0]);
      if (reg_mie_en[1]) reg_mie_next[1] = write_mie(wb_wdata[$bits(csr_mie_t)-1:0]);
      if (reg_mtvec_en[0]) reg_mtvec_next[0] = extend_VA(wb_wdata);
      if (reg_mtvec_en[1]) reg_mtvec_next[1] = extend_VA(wb_wdata);
      reg_mcounteren_next[0] = wb_wdata_1p[CsrNrCounters-1:0];
      reg_mcounteren_next[1] = wb_wdata_1p[CsrNrCounters-1:0];
      reg_mcounteren_latch_clk_en |= reg_mcounteren_en;
      reg_mscratch_next[0] = wb_wdata_1p;
      reg_mscratch_next[1] = wb_wdata_1p;
      reg_mscratch_latch_clk_en |= reg_mscratch_en;
      if (reg_mepc_en[0]) reg_mepc_next[0] = extend_VA(wb_wdata);
      if (reg_mepc_en[1]) reg_mepc_next[1] = extend_VA(wb_wdata);
      if (reg_mcause_en[0]) reg_mcause_next[0] = write_cause(wb_wdata[$bits(csr_cause_t)-1:0]);
      if (reg_mcause_en[1]) reg_mcause_next[1] = write_cause(wb_wdata[$bits(csr_cause_t)-1:0]);
      if (reg_mtval_en[0]) reg_mtval_next[0] = extend_VA(wb_wdata);
      if (reg_mtval_en[1]) reg_mtval_next[1] = extend_VA(wb_wdata);
      if (reg_mip_en[0]) reg_mip_next[0] = write_mip(wb_wdata[$bits(csr_mip_t)-1:0]);
      if (reg_mip_en[1]) reg_mip_next[1] = write_mip(wb_wdata[$bits(csr_mip_t)-1:0]);
      if (reg_pmpcfg0_en[0]) reg_pmpcfg0_next[0] = wb_wdata;
      if (reg_pmpcfg0_en[1]) reg_pmpcfg0_next[1] = wb_wdata;
      if (reg_pmpcfg2_en[0]) reg_pmpcfg2_next[0] = wb_wdata;
      if (reg_pmpcfg2_en[1]) reg_pmpcfg2_next[1] = wb_wdata;
      if (reg_pmpaddr0_en[0]) reg_pmpaddr0_next[0] = wb_wdata;
      if (reg_pmpaddr0_en[1]) reg_pmpaddr0_next[1] = wb_wdata;
      if (reg_pmpaddr1_en[0]) reg_pmpaddr1_next[0] = wb_wdata;
      if (reg_pmpaddr1_en[1]) reg_pmpaddr1_next[1] = wb_wdata;
      if (reg_pmpaddr15_en[0]) reg_pmpaddr15_next[0] = wb_wdata;
      if (reg_pmpaddr15_en[1]) reg_pmpaddr15_next[1] = wb_wdata;
      reg_mhpmevent3_next[0] = wb_wdata_1p[CsrNrEventsL-1:0];
      reg_mhpmevent3_next[1] = wb_wdata_1p[CsrNrEventsL-1:0];
      reg_mhpmevent3_latch_clk_en |= reg_mhpmevent3_en;
      reg_mhpmevent4_next[0] = wb_wdata_1p[CsrNrEventsL-1:0];
      reg_mhpmevent4_next[1] = wb_wdata_1p[CsrNrEventsL-1:0];
      reg_mhpmevent4_latch_clk_en |= reg_mhpmevent4_en;
      reg_mhpmevent5_next[0] = wb_wdata_1p[CsrNrEventsL-1:0];
      reg_mhpmevent5_next[1] = wb_wdata_1p[CsrNrEventsL-1:0];
      reg_mhpmevent5_latch_clk_en |= reg_mhpmevent5_en;
      reg_mhpmevent6_next[0] = wb_wdata_1p[CsrNrEventsL-1:0];
      reg_mhpmevent6_next[1] = wb_wdata_1p[CsrNrEventsL-1:0];
      reg_mhpmevent6_latch_clk_en |= reg_mhpmevent6_en;
      if (reg_mhpmevent7_en[0]) reg_mhpmevent7_next[0] = wb_wdata[CsrNrEventsL-1:0];
      if (reg_mhpmevent7_en[1]) reg_mhpmevent7_next[1] = wb_wdata[CsrNrEventsL-1:0];
      if (reg_mhpmevent8_en[0]) reg_mhpmevent8_next[0] = wb_wdata[CsrNrEventsL-1:0];
      if (reg_mhpmevent8_en[1]) reg_mhpmevent8_next[1] = wb_wdata[CsrNrEventsL-1:0];
      if (reg_tdata1_en[0]) reg_tdata1_next[0] = write_tdata1(wb_wdata[$bits(csr_tdata1_t)-1:0]);
      if (reg_tdata1_en[1]) reg_tdata1_next[1] = write_tdata1(wb_wdata[$bits(csr_tdata1_t)-1:0]);
      reg_tdata2_next[0] = wb_wdata_1p[VaSize-1:0];
      reg_tdata2_next[1] = wb_wdata_1p[VaSize-1:0];
      reg_tdata2_latch_clk_en |= reg_tdata2_en;
      if (reg_dcsr_en[0]) reg_dcsr_next[0] = write_dcsr(wb_wdata[$bits(csr_dcsr_t)-1:0]);
      if (reg_dcsr_en[1]) reg_dcsr_next[1] = write_dcsr(wb_wdata[$bits(csr_dcsr_t)-1:0]);
      if (reg_dpc_en[0]) reg_dpc_next[0] = extend_VA(wb_wdata);
      if (reg_dpc_en[1]) reg_dpc_next[1] = extend_VA(wb_wdata);
      reg_matp_next = write_matp(wb_wdata_1p[$bits(csr_matp_t)-1:0]);
      reg_matp_latch_clk_en |= reg_matp_en;
      reg_minstmask_next[0] = minst_mask_t'(wb_wdata_1p[$bits(minst_mask_t)-1:0]);
      reg_minstmask_next[1] = minst_mask_t'(wb_wdata_1p[$bits(minst_mask_t)-1:0]);
      reg_minstmask_latch_clk_en |= reg_minstmask_en;
      reg_minstmatch_next[0] = wb_wdata_1p[32-1:0];
      reg_minstmatch_next[1] = wb_wdata_1p[32-1:0];
      reg_minstmatch_latch_clk_en |= reg_minstmatch_en;
      reg_menable_shadows_next = menable_shadows_t'(wb_wdata_1p[$bits(menable_shadows_t)-1:0]);
      reg_menable_shadows_latch_clk_en |= reg_menable_shadows_en;
      reg_excl_mode_next = wb_wdata_1p[1-1:0];
      reg_excl_mode_latch_clk_en |= reg_excl_mode_en;
      if (reg_mbusaddr_en[0]) reg_mbusaddr_next[0] = wb_wdata[PaSize-1:0];
      if (reg_mbusaddr_en[1]) reg_mbusaddr_next[1] = wb_wdata[PaSize-1:0];
`ifdef DCACHE_REPORT_PC
      if (reg_mbuspc_en[0]) reg_mbuspc_next[0] = wb_wdata[PcSizeExt-1:0];
      if (reg_mbuspc_en[1]) reg_mbuspc_next[1] = wb_wdata[PcSizeExt-1:0];
`endif
