// Auto-generated by gen_esr.py (CSR mode) — do not edit manually.

      reg_fcsr_next = reg_fcsr;
      reg_tensor_fma_latch_clk_en = '0;
      reg_tensor_conv_size_latch_clk_en = '0;
      reg_tensor_conv_ctrl_latch_clk_en = '0;
      reg_tensor_cooperation_latch_clk_en = '0;
      reg_tensor_mask_next = reg_tensor_mask;
      reg_tensor_quant_latch_clk_en = '0;
      reg_gsc_progress_next = reg_gsc_progress;
`ifdef ET_SIMULATION
      reg_validation0_latch_clk_en = '0;
`endif
`ifdef ET_SIMULATION
      reg_validation1_latch_clk_en = '0;
`endif
`ifdef ET_SIMULATION
      reg_validation2_latch_clk_en = '0;
`endif
`ifdef ET_SIMULATION
      reg_validation3_latch_clk_en = '0;
`endif
`ifdef NOT_VERIF_SIMULATION
      reg_validation0_ps_next = reg_validation0_ps;
`endif
`ifdef NOT_VERIF_SIMULATION
      reg_validation1_ps_next = reg_validation1_ps;
`endif
`ifdef NOT_VERIF_SIMULATION
      reg_validation2_ps_next = reg_validation2_ps;
`endif
`ifdef NOT_VERIF_SIMULATION
      reg_validation3_ps_next = reg_validation3_ps;
`endif
      reg_stvec_next = reg_stvec;
      reg_scounteren_latch_clk_en = '0;
      reg_sscratch_latch_clk_en = '0;
      reg_sepc_next = reg_sepc;
      reg_scause_next = reg_scause;
      reg_stval_next = reg_stval;
      reg_satp_latch_clk_en = '0;
      reg_mstatus_next = reg_mstatus;
      reg_medeleg_latch_clk_en = '0;
      reg_mideleg_latch_clk_en = '0;
      reg_mie_next = reg_mie;
      reg_mtvec_next = reg_mtvec;
      reg_mcounteren_latch_clk_en = '0;
      reg_mscratch_latch_clk_en = '0;
      reg_mepc_next = reg_mepc;
      reg_mcause_next = reg_mcause;
      reg_mtval_next = reg_mtval;
      reg_mip_next = reg_mip;
      reg_pmpcfg0_next = reg_pmpcfg0;
      reg_pmpcfg2_next = reg_pmpcfg2;
      reg_pmpaddr0_next = reg_pmpaddr0;
      reg_pmpaddr1_next = reg_pmpaddr1;
      reg_pmpaddr15_next = reg_pmpaddr15;
      reg_mhpmevent3_latch_clk_en = '0;
      reg_mhpmevent4_latch_clk_en = '0;
      reg_mhpmevent5_latch_clk_en = '0;
      reg_mhpmevent6_latch_clk_en = '0;
      reg_mhpmevent7_next = reg_mhpmevent7;
      reg_mhpmevent8_next = reg_mhpmevent8;
      reg_tdata1_next = reg_tdata1;
      reg_tdata2_latch_clk_en = '0;
      reg_dcsr_next = reg_dcsr;
      reg_dpc_next = reg_dpc;
      reg_matp_latch_clk_en = '0;
      reg_minstmask_latch_clk_en = '0;
      reg_minstmatch_latch_clk_en = '0;
      reg_menable_shadows_latch_clk_en = '0;
      reg_excl_mode_latch_clk_en = '0;
      reg_mbusaddr_next = reg_mbusaddr;
`ifdef DCACHE_REPORT_PC
      reg_mbuspc_next = reg_mbuspc;
`endif
