// Copyright (c) 2026 Ainekko
// SPDX-License-Identifier: Apache-2.0
//
// CSR type definitions and address enum.
// Auto-generated by gen_esr.py — do not edit manually.

package intpipe_csr_pkg;

  typedef struct packed {
    logic af_rl;
    logic fa_aq;
    logic fa_rl;
    logic af_aq;
  } csr_amofence_t;

  typedef struct packed {
    logic interrupt_x;
    logic [57:0] reserved1;
    logic [4:0] cause;
  } csr_cause_t;

  typedef struct packed {
    logic [3:0] xdebugver;
    logic [11:0] reserved1;
    logic ebreakm;
    logic reserved3;
    logic ebreaks;
    logic ebreaku;
    logic reserved6;
    logic reserved7;
    logic reserved8;
    logic [2:0] cause;
    logic reserved10;
    logic mprven;
    logic nmip;
    logic step;
    logic [1:0] prv;
  } csr_dcsr_t;

  typedef struct packed {
    logic eflags;
    logic [22:0] reserved1;
    logic [2:0] rm;
    logic [4:0] flags;
  } csr_fcsr_t;

  typedef struct packed {
    logic eflags;
    logic [25:0] reserved1;
    logic [4:0] flags;
  } csr_fflags_t;

  typedef struct packed {
    logic [2:0] rm;
  } csr_frm_t;

  typedef struct packed {
    logic [3:0] mode;
    logic lock;
    logic [14:0] reserved2;
    logic [15:0] reserved3;
    logic [27:0] ppn;
  } csr_matp_t;

  typedef struct packed {
    logic [15:0] reserved0;
    logic store_page_fault;
    logic reserved2;
    logic load_page_fault;
    logic fetch_page_fault;
    logic reserved5;
    logic reserved6;
    logic reserved7;
    logic user_ecall;
    logic reserved9;
    logic reserved10;
    logic reserved11;
    logic reserved12;
    logic breakpoint;
    logic reserved14;
    logic reserved15;
    logic reserved16;
  } csr_medeleg_t;

  typedef struct packed {
    logic [43:0] reserved0;
    logic reserved1;
    logic [1:0] reserved2;
    logic reserved3;
    logic [3:0] reserved4;
    logic reserved5;
    logic reserved6;
    logic seip;
    logic reserved8;
    logic reserved9;
    logic reserved10;
    logic stip;
    logic reserved12;
    logic reserved13;
    logic reserved14;
    logic ssip;
    logic reserved16;
  } csr_mideleg_t;

  typedef struct packed {
    logic [39:0] reserved0;
    logic bus_err;
    logic [2:0] reserved2;
    logic mieco;
    logic [1:0] reserved4;
    logic mbad_red;
    logic [3:0] reserved6;
    logic meie;
    logic reserved8;
    logic seie;
    logic reserved10;
    logic mtie;
    logic reserved12;
    logic stie;
    logic reserved14;
    logic msie;
    logic reserved16;
    logic ssie;
    logic reserved18;
  } csr_mie_t;

  typedef struct packed {
    logic [39:0] reserved0;
    logic bus_err;
    logic [2:0] reserved2;
    logic mieco;
    logic [1:0] reserved4;
    logic mbad_red;
    logic [3:0] reserved6;
    logic meip;
    logic reserved8;
    logic seip;
    logic ueip___zero;
    logic mtip;
    logic reserved12;
    logic stip;
    logic utip___zero;
    logic msip;
    logic reserved16;
    logic ssip;
    logic usip___zero;
  } csr_mip_t;

  typedef struct packed {
    logic sd;
    logic [26:0] reserved1;
    logic [1:0] sxl;
    logic [1:0] uxl;
    logic [8:0] reserved4;
    logic tsr;
    logic tw;
    logic tvm;
    logic mxr;
    logic sum;
    logic mprv;
    logic [1:0] xs;
    logic [1:0] fs;
    logic [1:0] mpp;
    logic [1:0] reserved14;
    logic spp;
    logic mpie;
    logic reserved17;
    logic spie;
    logic reserved19;
    logic mie;
    logic reserved21;
    logic sie;
    logic reserved23;
  } csr_mstatus_t;

  typedef struct packed {
    logic sign_ext;
    logic [46:0] base;
    logic reserved2;
  } csr_pc_t;

  typedef struct packed {
    logic [3:0] mode;
    logic [15:0] reserved1;
    logic [15:0] reserved2;
    logic [27:0] ppn;
  } csr_satp_t;

  typedef struct packed {
    logic [53:0] reserved0;
    logic seip;
    logic reserved2;
    logic [1:0] reserved3;
    logic stip;
    logic reserved5;
    logic [1:0] reserved6;
    logic ssip;
    logic reserved8;
  } csr_sideleg_t;

  typedef struct packed {
    logic [53:0] reserved0;
    logic seie;
    logic reserved2;
    logic [1:0] reserved3;
    logic stie;
    logic reserved5;
    logic [1:0] reserved6;
    logic ssie;
    logic reserved8;
  } csr_sie_t;

  typedef struct packed {
    logic [53:0] reserved0;
    logic seip;
    logic reserved2;
    logic [1:0] reserved3;
    logic stip;
    logic reserved5;
    logic [1:0] reserved6;
    logic ssip;
    logic reserved8;
  } csr_sip_t;

  typedef struct packed {
    logic sd;
    logic [28:0] reserved1;
    logic [1:0] uxl;
    logic [11:0] reserved3;
    logic mxr;
    logic sum;
    logic reserved6;
    logic [1:0] xs;
    logic [1:0] fs;
    logic [3:0] reserved9;
    logic spp;
    logic [1:0] reserved11;
    logic spie;
    logic reserved13;
    logic [1:0] reserved14;
    logic sie;
    logic reserved16;
  } csr_sstatus_t;

  typedef struct packed {
    logic [3:0] ttype;
    logic dmode;
    logic [5:0] maskmax;
    logic [31:0] reserved3;
    logic reserved4;
    logic reserved5;
    logic timing;
    logic [4:0] action_msb_zero;
    logic action;
    logic reserved9;
    logic [2:0] reserved10;
    logic match;
    logic m;
    logic reserved13;
    logic s;
    logic u;
    logic execute;
    logic store;
    logic load;
  } csr_tdata1_t;

  typedef struct packed {
    logic ext;
    logic [35:0] base;
    logic [10:0] reserved2;
    logic mode;
  } csr_tvec_t;

  typedef struct packed {
    logic [54:0] reserved0;
    logic ueie;
    logic [2:0] reserved2;
    logic utie;
    logic [2:0] reserved4;
    logic usie;
  } csr_uie_t;

  typedef struct packed {
    logic [53:0] reserved0;
    logic reserved1;
    logic ueip;
    logic [1:0] reserved3;
    logic reserved4;
    logic utip;
    logic [1:0] reserved6;
    logic reserved7;
    logic usip;
  } csr_uip_t;

  typedef struct packed {
    logic [58:0] reserved0;
    logic upie;
    logic [2:0] reserved2;
    logic uie;
  } csr_ustatus_t;

  typedef struct packed {
    logic hartid;
  } menable_shadows_t;

  typedef struct packed {
    logic enable;
    logic [31:0] mask;
  } minst_mask_t;

  typedef struct packed {
    logic tensorfma_fp16_fp32;
    logic tensor_quant;
    logic tensor_reduce_fp32;
    logic trans;
    logic other;
  } txfma_sleep_traps_t;

  typedef enum logic [11:0] {
    csr_ad_FFLAGS = 12'h001,
    csr_ad_FRM = 12'h002,
    csr_ad_FCSR = 12'h003,
    csr_ad_CYCLE = 12'hc00,
    csr_ad_INSTRET = 12'hc02,
    csr_ad_HPMCOUNTER3 = 12'hc03,
    csr_ad_HPMCOUNTER4 = 12'hc04,
    csr_ad_HPMCOUNTER5 = 12'hc05,
    csr_ad_HPMCOUNTER6 = 12'hc06,
    csr_ad_HPMCOUNTER7 = 12'hc07,
    csr_ad_HPMCOUNTER8 = 12'hc08,
    csr_ad_TENSOR_REDUCE = 12'h800,
    csr_ad_TENSOR_FMA = 12'h801,
    csr_ad_TENSOR_CONV_SIZE = 12'h802,
    csr_ad_TENSOR_CONV_CTRL = 12'h803,
    csr_ad_TENSOR_COOPERATION = 12'h804,
    csr_ad_TENSOR_MASK = 12'h805,
    csr_ad_TENSOR_QUANT = 12'h806,
    csr_ad_TEX_SEND = 12'h807,
    csr_ad_TENSOR_ERROR = 12'h808,
    csr_ad_UCACHE_CONTROL = 12'h810,
    csr_ad_FLB = 12'h820,
    csr_ad_FCC = 12'h821,
    csr_ad_STALL = 12'h822,
    csr_ad_TENSOR_WAIT = 12'h830,
    csr_ad_TENSOR_LOAD = 12'h83f,
    csr_ad_GSC_PROGRESS = 12'h840,
    csr_ad_TENSOR_LOAD_L2SCP = 12'h85f,
    csr_ad_TENSOR_STORE = 12'h87f,
`ifdef ET_SIMULATION
    csr_ad_VALIDATION0 = 12'h8d0,
`endif
`ifdef ET_SIMULATION
    csr_ad_VALIDATION1 = 12'h8d1,
`endif
`ifdef ET_SIMULATION
    csr_ad_VALIDATION2 = 12'h8d2,
`endif
`ifdef ET_SIMULATION
    csr_ad_VALIDATION3 = 12'h8d3,
`endif
`ifdef NOT_VERIF_SIMULATION
    csr_ad_VALIDATION0_PS = 12'h8d0,
`endif
`ifdef NOT_VERIF_SIMULATION
    csr_ad_VALIDATION1_PS = 12'h8d1,
`endif
`ifdef NOT_VERIF_SIMULATION
    csr_ad_VALIDATION2_PS = 12'h8d2,
`endif
`ifdef NOT_VERIF_SIMULATION
    csr_ad_VALIDATION3_PS = 12'h8d3,
`endif
    csr_ad_HARTID = 12'hcd0,
    csr_ad_NB_FCC = 12'hcc0,
    csr_ad_PORTHEAD0 = 12'hcc8,
    csr_ad_PORTHEAD1 = 12'hcc9,
    csr_ad_PORTHEAD2 = 12'hcca,
    csr_ad_PORTHEAD3 = 12'hccb,
    csr_ad_PORTHEADNB0 = 12'hccc,
    csr_ad_PORTHEADNB1 = 12'hccd,
    csr_ad_PORTHEADNB2 = 12'hcce,
    csr_ad_PORTHEADNB3 = 12'hccf,
    csr_ad_CO_EVICT_VA = 12'h89f,
    csr_ad_CO_FLUSH_VA = 12'h8bf,
    csr_ad_CO_LOCK_VA = 12'h8df,
    csr_ad_CO_UNLOCK_VA = 12'h8ff,
    csr_ad_CO_PREFETCH_VA = 12'h81f,
    csr_ad_SSTATUS = 12'h100,
    csr_ad_SIE = 12'h104,
    csr_ad_STVEC = 12'h105,
    csr_ad_SCOUNTEREN = 12'h106,
    csr_ad_SSCRATCH = 12'h140,
    csr_ad_SEPC = 12'h141,
    csr_ad_SCAUSE = 12'h142,
    csr_ad_STVAL = 12'h143,
    csr_ad_SIP = 12'h144,
    csr_ad_SATP = 12'h180,
    csr_ad_SMSG_PORT0 = 12'h9cc,
    csr_ad_SMSG_PORT1 = 12'h9cd,
    csr_ad_SMSG_PORT2 = 12'h9ce,
    csr_ad_SMSG_PORT3 = 12'h9cf,
    csr_ad_MVENDORID = 12'hf11,
    csr_ad_MARCHID = 12'hf12,
    csr_ad_MIMPID = 12'hf13,
    csr_ad_MHARTID = 12'hf14,
    csr_ad_MSTATUS = 12'h300,
    csr_ad_MISA = 12'h301,
    csr_ad_MEDELEG = 12'h302,
    csr_ad_MIDELEG = 12'h303,
    csr_ad_MIE = 12'h304,
    csr_ad_MTVEC = 12'h305,
    csr_ad_MCOUNTEREN = 12'h306,
    csr_ad_MSCRATCH = 12'h340,
    csr_ad_MEPC = 12'h341,
    csr_ad_MCAUSE = 12'h342,
    csr_ad_MTVAL = 12'h343,
    csr_ad_MIP = 12'h344,
    csr_ad_PMPCFG0 = 12'h3a0,
    csr_ad_PMPCFG2 = 12'h3a2,
    csr_ad_PMPADDR0 = 12'h3b0,
    csr_ad_PMPADDR1 = 12'h3b1,
    csr_ad_PMPADDR15 = 12'h3bf,
    csr_ad_MCYCLE = 12'hb00,
    csr_ad_MINSTRET = 12'hb02,
    csr_ad_MHPMCOUNTER3 = 12'hb03,
    csr_ad_MHPMCOUNTER4 = 12'hb04,
    csr_ad_MHPMCOUNTER5 = 12'hb05,
    csr_ad_MHPMCOUNTER6 = 12'hb06,
    csr_ad_MHPMCOUNTER7 = 12'hb07,
    csr_ad_MHPMCOUNTER8 = 12'hb08,
    csr_ad_MHPMEVENT3 = 12'h323,
    csr_ad_MHPMEVENT4 = 12'h324,
    csr_ad_MHPMEVENT5 = 12'h325,
    csr_ad_MHPMEVENT6 = 12'h326,
    csr_ad_MHPMEVENT7 = 12'h327,
    csr_ad_MHPMEVENT8 = 12'h328,
    csr_ad_TSELECT = 12'h7a0,
    csr_ad_TDATA1 = 12'h7a1,
    csr_ad_TDATA2 = 12'h7a2,
    csr_ad_DCSR = 12'h7b0,
    csr_ad_DPC = 12'h7b1,
    csr_ad_DDATA0 = 12'h7b8,
    csr_ad_MATP = 12'h7c0,
    csr_ad_MINSTMASK = 12'h7cd,
    csr_ad_MINSTMATCH = 12'h7ce,
    csr_ad_CACHEINVALIDATE = 12'h7d0,
    csr_ad_MENABLE_SHADOWS = 12'h7d2,
    csr_ad_EXCL_MODE = 12'h7d3,
    csr_ad_MBUSADDR = 12'h7d5,
`ifdef DCACHE_REPORT_PC
    csr_ad_MBUSPC = 12'h7d6,
`endif
    csr_ad_MCACHE_CONTROL = 12'h7e0,
    csr_ad_CO_EVICT_SW = 12'h7f9,
    csr_ad_CO_FLUSH_SW = 12'h7fb,
    csr_ad_CO_LOCK_SW = 12'h7fd,
    csr_ad_CO_UNLOCK_SW = 12'h7ff,
    csr_ad_DCACHE_DEBUG = 12'hfc0,
    csr_ad_MHPMCOUNTER9 = 12'hb09,
    csr_ad_MHPMCOUNTER10 = 12'hb0a,
    csr_ad_MHPMCOUNTER11 = 12'hb0b,
    csr_ad_MHPMCOUNTER12 = 12'hb0c,
    csr_ad_MHPMCOUNTER13 = 12'hb0d,
    csr_ad_MHPMCOUNTER14 = 12'hb0e,
    csr_ad_MHPMCOUNTER15 = 12'hb0f,
    csr_ad_MHPMCOUNTER16 = 12'hb10,
    csr_ad_MHPMCOUNTER17 = 12'hb11,
    csr_ad_MHPMCOUNTER18 = 12'hb12,
    csr_ad_MHPMCOUNTER19 = 12'hb13,
    csr_ad_MHPMCOUNTER20 = 12'hb14,
    csr_ad_MHPMCOUNTER21 = 12'hb15,
    csr_ad_MHPMCOUNTER22 = 12'hb16,
    csr_ad_MHPMCOUNTER23 = 12'hb17,
    csr_ad_MHPMCOUNTER24 = 12'hb18,
    csr_ad_MHPMCOUNTER25 = 12'hb19,
    csr_ad_MHPMCOUNTER26 = 12'hb1a,
    csr_ad_MHPMCOUNTER27 = 12'hb1b,
    csr_ad_MHPMCOUNTER28 = 12'hb1c,
    csr_ad_MHPMCOUNTER29 = 12'hb1d,
    csr_ad_MHPMCOUNTER30 = 12'hb1e,
    csr_ad_MHPMCOUNTER31 = 12'hb1f,
    csr_ad_MHPMEVENT9 = 12'h329,
    csr_ad_MHPMEVENT10 = 12'h32a,
    csr_ad_MHPMEVENT11 = 12'h32b,
    csr_ad_MHPMEVENT12 = 12'h32c,
    csr_ad_MHPMEVENT13 = 12'h32d,
    csr_ad_MHPMEVENT14 = 12'h32e,
    csr_ad_MHPMEVENT15 = 12'h32f,
    csr_ad_MHPMEVENT16 = 12'h330,
    csr_ad_MHPMEVENT17 = 12'h331,
    csr_ad_MHPMEVENT18 = 12'h332,
    csr_ad_MHPMEVENT19 = 12'h333,
    csr_ad_MHPMEVENT20 = 12'h334,
    csr_ad_MHPMEVENT21 = 12'h335,
    csr_ad_MHPMEVENT22 = 12'h336,
    csr_ad_MHPMEVENT23 = 12'h337,
    csr_ad_MHPMEVENT24 = 12'h338,
    csr_ad_MHPMEVENT25 = 12'h339,
    csr_ad_MHPMEVENT26 = 12'h33a,
    csr_ad_MHPMEVENT27 = 12'h33b,
    csr_ad_MHPMEVENT28 = 12'h33c,
    csr_ad_MHPMEVENT29 = 12'h33d,
    csr_ad_MHPMEVENT30 = 12'h33e,
    csr_ad_MHPMEVENT31 = 12'h33f
  } csr_ad_t;

endpackage
