// Auto-generated by gen_esr.py (CSR mode) — do not edit manually.

  function automatic csr_cause_t write_cause;
    input [$bits(csr_cause_t)-1:0] d;
    csr_cause_t dd, ret;
  begin
    dd = csr_cause_t'(d);
    ret.interrupt_x = dd.interrupt_x;
    ret.reserved1 = '0;
    ret.cause = dd.cause;
    return ret;
  end
  endfunction

  function automatic csr_cause_t write_cause_non_reserved;
    input csr_cause_t d;
    csr_cause_t ret;
  begin
    ret.interrupt_x = d.interrupt_x;
    ret.reserved1 = '0;
    ret.cause = d.cause;
    return ret;
  end
  endfunction

  function automatic csr_dcsr_t write_dcsr;
    input [$bits(csr_dcsr_t)-1:0] d;
    csr_dcsr_t dd, ret;
  begin
    dd = csr_dcsr_t'(d);
    ret.xdebugver = 4'h4;
    ret.reserved1 = '0;
    ret.ebreakm = dd.ebreakm;
    ret.reserved3 = '0;
    ret.ebreaks = dd.ebreaks;
    ret.ebreaku = dd.ebreaku;
    ret.reserved6 = '0;
    ret.reserved7 = '0;
    ret.reserved8 = '0;
    ret.cause = 'x;
    ret.reserved10 = '0;
    ret.mprven = dd.mprven;
    ret.nmip = 'x;
    ret.step = dd.step;
    ret.prv = dd.prv;
    return ret;
  end
  endfunction

  function automatic csr_dcsr_t write_dcsr_non_reserved;
    input csr_dcsr_t d;
    csr_dcsr_t ret;
  begin
    ret.xdebugver = d.xdebugver;
    ret.reserved1 = '0;
    ret.ebreakm = d.ebreakm;
    ret.reserved3 = '0;
    ret.ebreaks = d.ebreaks;
    ret.ebreaku = d.ebreaku;
    ret.reserved6 = '0;
    ret.reserved7 = '0;
    ret.reserved8 = '0;
    ret.cause = d.cause;
    ret.reserved10 = '0;
    ret.mprven = d.mprven;
    ret.nmip = d.nmip;
    ret.step = d.step;
    ret.prv = d.prv;
    return ret;
  end
  endfunction

  function automatic csr_fcsr_t write_fcsr;
    input [$bits(csr_fcsr_t)-1:0] d;
    csr_fcsr_t dd, ret;
  begin
    dd = csr_fcsr_t'(d);
    ret.eflags = dd.eflags;
    ret.reserved1 = '0;
    ret.rm = dd.rm;
    ret.flags = dd.flags;
    return ret;
  end
  endfunction

  function automatic csr_fcsr_t write_fcsr_non_reserved;
    input csr_fcsr_t d;
    csr_fcsr_t ret;
  begin
    ret.eflags = d.eflags;
    ret.reserved1 = '0;
    ret.rm = d.rm;
    ret.flags = d.flags;
    return ret;
  end
  endfunction

  function automatic csr_fflags_t write_fflags;
    input [$bits(csr_fflags_t)-1:0] d;
    csr_fflags_t dd, ret;
  begin
    dd = csr_fflags_t'(d);
    ret.eflags = dd.eflags;
    ret.reserved1 = '0;
    ret.flags = dd.flags;
    return ret;
  end
  endfunction

  function automatic csr_fflags_t write_fflags_non_reserved;
    input csr_fflags_t d;
    csr_fflags_t ret;
  begin
    ret.eflags = d.eflags;
    ret.reserved1 = '0;
    ret.flags = d.flags;
    return ret;
  end
  endfunction

  function automatic csr_frm_t write_frm;
    input [$bits(csr_frm_t)-1:0] d;
    csr_frm_t dd, ret;
  begin
    dd = csr_frm_t'(d);
    ret.rm = dd.rm;
    return ret;
  end
  endfunction

  function automatic csr_frm_t write_frm_non_reserved;
    input csr_frm_t d;
    csr_frm_t ret;
  begin
    ret.rm = d.rm;
    return ret;
  end
  endfunction

  function automatic csr_matp_t write_matp;
    input [$bits(csr_matp_t)-1:0] d;
    csr_matp_t dd, ret;
  begin
    dd = csr_matp_t'(d);
    ret.mode = dd.mode;
    ret.lock = dd.lock;
    ret.reserved2 = '0;
    ret.reserved3 = '0;
    ret.ppn = dd.ppn;
    return ret;
  end
  endfunction

  function automatic csr_matp_t write_matp_non_reserved;
    input csr_matp_t d;
    csr_matp_t ret;
  begin
    ret.mode = d.mode;
    ret.lock = d.lock;
    ret.reserved2 = '0;
    ret.reserved3 = '0;
    ret.ppn = d.ppn;
    return ret;
  end
  endfunction

  function automatic csr_medeleg_t write_medeleg;
    input [$bits(csr_medeleg_t)-1:0] d;
    csr_medeleg_t dd, ret;
  begin
    dd = csr_medeleg_t'(d);
    ret.reserved0 = '0;
    ret.store_page_fault = dd.store_page_fault;
    ret.reserved2 = '0;
    ret.load_page_fault = dd.load_page_fault;
    ret.fetch_page_fault = dd.fetch_page_fault;
    ret.reserved5 = '0;
    ret.reserved6 = '0;
    ret.reserved7 = '0;
    ret.user_ecall = dd.user_ecall;
    ret.reserved9 = '0;
    ret.reserved10 = '0;
    ret.reserved11 = '0;
    ret.reserved12 = '0;
    ret.breakpoint = dd.breakpoint;
    ret.reserved14 = '0;
    ret.reserved15 = '0;
    ret.reserved16 = '0;
    return ret;
  end
  endfunction

  function automatic csr_medeleg_t write_medeleg_non_reserved;
    input csr_medeleg_t d;
    csr_medeleg_t ret;
  begin
    ret.reserved0 = '0;
    ret.store_page_fault = d.store_page_fault;
    ret.reserved2 = '0;
    ret.load_page_fault = d.load_page_fault;
    ret.fetch_page_fault = d.fetch_page_fault;
    ret.reserved5 = '0;
    ret.reserved6 = '0;
    ret.reserved7 = '0;
    ret.user_ecall = d.user_ecall;
    ret.reserved9 = '0;
    ret.reserved10 = '0;
    ret.reserved11 = '0;
    ret.reserved12 = '0;
    ret.breakpoint = d.breakpoint;
    ret.reserved14 = '0;
    ret.reserved15 = '0;
    ret.reserved16 = '0;
    return ret;
  end
  endfunction

  function automatic csr_mideleg_t write_mideleg;
    input [$bits(csr_mideleg_t)-1:0] d;
    csr_mideleg_t dd, ret;
  begin
    dd = csr_mideleg_t'(d);
    ret.reserved0 = '0;
    ret.reserved1 = '0;
    ret.reserved2 = '0;
    ret.reserved3 = '0;
    ret.reserved4 = '0;
    ret.reserved5 = '0;
    ret.reserved6 = '0;
    ret.seip = dd.seip;
    ret.reserved8 = '0;
    ret.reserved9 = '0;
    ret.reserved10 = '0;
    ret.stip = dd.stip;
    ret.reserved12 = '0;
    ret.reserved13 = '0;
    ret.reserved14 = '0;
    ret.ssip = dd.ssip;
    ret.reserved16 = '0;
    return ret;
  end
  endfunction

  function automatic csr_mideleg_t write_mideleg_non_reserved;
    input csr_mideleg_t d;
    csr_mideleg_t ret;
  begin
    ret.reserved0 = '0;
    ret.reserved1 = '0;
    ret.reserved2 = '0;
    ret.reserved3 = '0;
    ret.reserved4 = '0;
    ret.reserved5 = '0;
    ret.reserved6 = '0;
    ret.seip = d.seip;
    ret.reserved8 = '0;
    ret.reserved9 = '0;
    ret.reserved10 = '0;
    ret.stip = d.stip;
    ret.reserved12 = '0;
    ret.reserved13 = '0;
    ret.reserved14 = '0;
    ret.ssip = d.ssip;
    ret.reserved16 = '0;
    return ret;
  end
  endfunction

  function automatic csr_mie_t write_mie;
    input [$bits(csr_mie_t)-1:0] d;
    csr_mie_t dd, ret;
  begin
    dd = csr_mie_t'(d);
    ret.reserved0 = '0;
    ret.bus_err = dd.bus_err;
    ret.reserved2 = '0;
    ret.mieco = dd.mieco;
    ret.reserved4 = '0;
    ret.mbad_red = dd.mbad_red;
    ret.reserved6 = '0;
    ret.meie = dd.meie;
    ret.reserved8 = '0;
    ret.seie = dd.seie;
    ret.reserved10 = '0;
    ret.mtie = dd.mtie;
    ret.reserved12 = '0;
    ret.stie = dd.stie;
    ret.reserved14 = '0;
    ret.msie = dd.msie;
    ret.reserved16 = '0;
    ret.ssie = dd.ssie;
    ret.reserved18 = '0;
    return ret;
  end
  endfunction

  function automatic csr_mie_t write_mie_non_reserved;
    input csr_mie_t d;
    csr_mie_t ret;
  begin
    ret.reserved0 = '0;
    ret.bus_err = d.bus_err;
    ret.reserved2 = '0;
    ret.mieco = d.mieco;
    ret.reserved4 = '0;
    ret.mbad_red = d.mbad_red;
    ret.reserved6 = '0;
    ret.meie = d.meie;
    ret.reserved8 = '0;
    ret.seie = d.seie;
    ret.reserved10 = '0;
    ret.mtie = d.mtie;
    ret.reserved12 = '0;
    ret.stie = d.stie;
    ret.reserved14 = '0;
    ret.msie = d.msie;
    ret.reserved16 = '0;
    ret.ssie = d.ssie;
    ret.reserved18 = '0;
    return ret;
  end
  endfunction

  function automatic csr_mip_t write_mip;
    input [$bits(csr_mip_t)-1:0] d;
    csr_mip_t dd, ret;
  begin
    dd = csr_mip_t'(d);
    ret.reserved0 = '0;
    ret.bus_err = dd.bus_err;
    ret.reserved2 = '0;
    ret.mieco = 'x;
    ret.reserved4 = '0;
    ret.mbad_red = dd.mbad_red;
    ret.reserved6 = '0;
    ret.meip = 'x;
    ret.reserved8 = '0;
    ret.seip = dd.seip;
    ret.ueip___zero = dd.ueip___zero;
    ret.mtip = 'x;
    ret.reserved12 = '0;
    ret.stip = dd.stip;
    ret.utip___zero = dd.utip___zero;
    ret.msip = 'x;
    ret.reserved16 = '0;
    ret.ssip = dd.ssip;
    ret.usip___zero = dd.usip___zero;
    return ret;
  end
  endfunction

  function automatic csr_mip_t write_mip_non_reserved;
    input csr_mip_t d;
    csr_mip_t ret;
  begin
    ret.reserved0 = '0;
    ret.bus_err = d.bus_err;
    ret.reserved2 = '0;
    ret.mieco = d.mieco;
    ret.reserved4 = '0;
    ret.mbad_red = d.mbad_red;
    ret.reserved6 = '0;
    ret.meip = d.meip;
    ret.reserved8 = '0;
    ret.seip = d.seip;
    ret.ueip___zero = d.ueip___zero;
    ret.mtip = d.mtip;
    ret.reserved12 = '0;
    ret.stip = d.stip;
    ret.utip___zero = d.utip___zero;
    ret.msip = d.msip;
    ret.reserved16 = '0;
    ret.ssip = d.ssip;
    ret.usip___zero = d.usip___zero;
    return ret;
  end
  endfunction

  function automatic csr_mstatus_t write_mstatus;
    input [$bits(csr_mstatus_t)-1:0] d;
    csr_mstatus_t dd, ret;
  begin
    dd = csr_mstatus_t'(d);
    ret.sd = 'x;
    ret.reserved1 = '0;
    ret.sxl = 2'b10;
    ret.uxl = 2'b10;
    ret.reserved4 = '0;
    ret.tsr = dd.tsr;
    ret.tw = dd.tw;
    ret.tvm = dd.tvm;
    ret.mxr = dd.mxr;
    ret.sum = dd.sum;
    ret.mprv = dd.mprv;
    ret.xs = 'x;
    ret.fs = dd.fs;
    ret.mpp = dd.mpp;
    ret.reserved14 = '0;
    ret.spp = dd.spp;
    ret.mpie = dd.mpie;
    ret.reserved17 = '0;
    ret.spie = dd.spie;
    ret.reserved19 = '0;
    ret.mie = dd.mie;
    ret.reserved21 = '0;
    ret.sie = dd.sie;
    ret.reserved23 = '0;
    return ret;
  end
  endfunction

  function automatic csr_mstatus_t write_mstatus_non_reserved;
    input csr_mstatus_t d;
    csr_mstatus_t ret;
  begin
    ret.sd = d.sd;
    ret.reserved1 = '0;
    ret.sxl = d.sxl;
    ret.uxl = d.uxl;
    ret.reserved4 = '0;
    ret.tsr = d.tsr;
    ret.tw = d.tw;
    ret.tvm = d.tvm;
    ret.mxr = d.mxr;
    ret.sum = d.sum;
    ret.mprv = d.mprv;
    ret.xs = d.xs;
    ret.fs = d.fs;
    ret.mpp = d.mpp;
    ret.reserved14 = '0;
    ret.spp = d.spp;
    ret.mpie = d.mpie;
    ret.reserved17 = '0;
    ret.spie = d.spie;
    ret.reserved19 = '0;
    ret.mie = d.mie;
    ret.reserved21 = '0;
    ret.sie = d.sie;
    ret.reserved23 = '0;
    return ret;
  end
  endfunction

  function automatic csr_pc_t write_pc;
    input [$bits(csr_pc_t)-1:0] d;
    csr_pc_t dd, ret;
  begin
    dd = csr_pc_t'(d);
    ret.sign_ext = dd.sign_ext;
    ret.base = dd.base;
    ret.reserved2 = '0;
    return ret;
  end
  endfunction

  function automatic csr_pc_t write_pc_non_reserved;
    input csr_pc_t d;
    csr_pc_t ret;
  begin
    ret.sign_ext = d.sign_ext;
    ret.base = d.base;
    ret.reserved2 = '0;
    return ret;
  end
  endfunction

  function automatic csr_satp_t write_satp;
    input [$bits(csr_satp_t)-1:0] d;
    csr_satp_t dd, ret;
  begin
    dd = csr_satp_t'(d);
    ret.mode = dd.mode;
    ret.reserved1 = '0;
    ret.reserved2 = '0;
    ret.ppn = dd.ppn;
    return ret;
  end
  endfunction

  function automatic csr_satp_t write_satp_non_reserved;
    input csr_satp_t d;
    csr_satp_t ret;
  begin
    ret.mode = d.mode;
    ret.reserved1 = '0;
    ret.reserved2 = '0;
    ret.ppn = d.ppn;
    return ret;
  end
  endfunction

  function automatic csr_sie_t write_sie;
    input [$bits(csr_sie_t)-1:0] d;
    csr_sie_t dd, ret;
  begin
    dd = csr_sie_t'(d);
    ret.reserved0 = '0;
    ret.seie = dd.seie;
    ret.reserved2 = '0;
    ret.reserved3 = '0;
    ret.stie = dd.stie;
    ret.reserved5 = '0;
    ret.reserved6 = '0;
    ret.ssie = dd.ssie;
    ret.reserved8 = '0;
    return ret;
  end
  endfunction

  function automatic csr_sie_t write_sie_non_reserved;
    input csr_sie_t d;
    csr_sie_t ret;
  begin
    ret.reserved0 = '0;
    ret.seie = d.seie;
    ret.reserved2 = '0;
    ret.reserved3 = '0;
    ret.stie = d.stie;
    ret.reserved5 = '0;
    ret.reserved6 = '0;
    ret.ssie = d.ssie;
    ret.reserved8 = '0;
    return ret;
  end
  endfunction

  function automatic csr_sip_t write_sip;
    input [$bits(csr_sip_t)-1:0] d;
    csr_sip_t dd, ret;
  begin
    dd = csr_sip_t'(d);
    ret.reserved0 = '0;
    ret.seip = dd.seip;
    ret.reserved2 = '0;
    ret.reserved3 = '0;
    ret.stip = dd.stip;
    ret.reserved5 = '0;
    ret.reserved6 = '0;
    ret.ssip = dd.ssip;
    ret.reserved8 = '0;
    return ret;
  end
  endfunction

  function automatic csr_sip_t write_sip_non_reserved;
    input csr_sip_t d;
    csr_sip_t ret;
  begin
    ret.reserved0 = '0;
    ret.seip = d.seip;
    ret.reserved2 = '0;
    ret.reserved3 = '0;
    ret.stip = d.stip;
    ret.reserved5 = '0;
    ret.reserved6 = '0;
    ret.ssip = d.ssip;
    ret.reserved8 = '0;
    return ret;
  end
  endfunction

  function automatic csr_sstatus_t write_sstatus;
    input [$bits(csr_sstatus_t)-1:0] d;
    csr_sstatus_t dd, ret;
  begin
    dd = csr_sstatus_t'(d);
    ret.sd = dd.sd;
    ret.reserved1 = '0;
    ret.uxl = dd.uxl;
    ret.reserved3 = '0;
    ret.mxr = dd.mxr;
    ret.sum = dd.sum;
    ret.reserved6 = '0;
    ret.xs = dd.xs;
    ret.fs = dd.fs;
    ret.reserved9 = '0;
    ret.spp = dd.spp;
    ret.reserved11 = '0;
    ret.spie = dd.spie;
    ret.reserved13 = '0;
    ret.reserved14 = '0;
    ret.sie = dd.sie;
    ret.reserved16 = '0;
    return ret;
  end
  endfunction

  function automatic csr_sstatus_t write_sstatus_non_reserved;
    input csr_sstatus_t d;
    csr_sstatus_t ret;
  begin
    ret.sd = d.sd;
    ret.reserved1 = '0;
    ret.uxl = d.uxl;
    ret.reserved3 = '0;
    ret.mxr = d.mxr;
    ret.sum = d.sum;
    ret.reserved6 = '0;
    ret.xs = d.xs;
    ret.fs = d.fs;
    ret.reserved9 = '0;
    ret.spp = d.spp;
    ret.reserved11 = '0;
    ret.spie = d.spie;
    ret.reserved13 = '0;
    ret.reserved14 = '0;
    ret.sie = d.sie;
    ret.reserved16 = '0;
    return ret;
  end
  endfunction

  function automatic csr_tdata1_t write_tdata1;
    input [$bits(csr_tdata1_t)-1:0] d;
    csr_tdata1_t dd, ret;
  begin
    dd = csr_tdata1_t'(d);
    ret.ttype = 4'h2;
    ret.dmode = dd.dmode;
    ret.maskmax = 6'h6;
    ret.reserved3 = '0;
    ret.reserved4 = '0;
    ret.reserved5 = '0;
    ret.timing = 'x;
    ret.action_msb_zero = dd.action_msb_zero;
    ret.action = dd.action;
    ret.reserved9 = '0;
    ret.reserved10 = '0;
    ret.match = dd.match;
    ret.m = dd.m;
    ret.reserved13 = '0;
    ret.s = dd.s;
    ret.u = dd.u;
    ret.execute = dd.execute;
    ret.store = dd.store;
    ret.load = dd.load;
    return ret;
  end
  endfunction

  function automatic csr_tdata1_t write_tdata1_non_reserved;
    input csr_tdata1_t d;
    csr_tdata1_t ret;
  begin
    ret.ttype = d.ttype;
    ret.dmode = d.dmode;
    ret.maskmax = d.maskmax;
    ret.reserved3 = '0;
    ret.reserved4 = '0;
    ret.reserved5 = '0;
    ret.timing = d.timing;
    ret.action_msb_zero = d.action_msb_zero;
    ret.action = d.action;
    ret.reserved9 = '0;
    ret.reserved10 = '0;
    ret.match = d.match;
    ret.m = d.m;
    ret.reserved13 = '0;
    ret.s = d.s;
    ret.u = d.u;
    ret.execute = d.execute;
    ret.store = d.store;
    ret.load = d.load;
    return ret;
  end
  endfunction

  function automatic csr_tvec_t write_tvec;
    input [$bits(csr_tvec_t)-1:0] d;
    csr_tvec_t dd, ret;
  begin
    dd = csr_tvec_t'(d);
    ret.ext = dd.ext;
    ret.base = dd.base;
    ret.reserved2 = '0;
    ret.mode = dd.mode;
    return ret;
  end
  endfunction

  function automatic csr_tvec_t write_tvec_non_reserved;
    input csr_tvec_t d;
    csr_tvec_t ret;
  begin
    ret.ext = d.ext;
    ret.base = d.base;
    ret.reserved2 = '0;
    ret.mode = d.mode;
    return ret;
  end
  endfunction

  function automatic menable_shadows_t write_menable_shadows;
    input [$bits(menable_shadows_t)-1:0] d;
    menable_shadows_t dd, ret;
  begin
    dd = menable_shadows_t'(d);
    ret.hartid = dd.hartid;
    return ret;
  end
  endfunction

  function automatic menable_shadows_t write_menable_shadows_non_reserved;
    input menable_shadows_t d;
    menable_shadows_t ret;
  begin
    ret.hartid = d.hartid;
    return ret;
  end
  endfunction

  function automatic minst_mask_t write_minst_mask;
    input [$bits(minst_mask_t)-1:0] d;
    minst_mask_t dd, ret;
  begin
    dd = minst_mask_t'(d);
    ret.enable = dd.enable;
    ret.mask = dd.mask;
    return ret;
  end
  endfunction

  function automatic minst_mask_t write_minst_mask_non_reserved;
    input minst_mask_t d;
    minst_mask_t ret;
  begin
    ret.enable = d.enable;
    ret.mask = d.mask;
    return ret;
  end
  endfunction

  function automatic csr_fflags_t read_fcsr_as_fflags;
    input csr_fcsr_t orig;
    csr_fflags_t ret;
  begin
    ret = '0;
    ret.eflags = orig.eflags;
    ret.flags = orig.flags;
    return ret;
  end
  endfunction

  function automatic csr_fcsr_t write_fcsr_as_fflags;
    input csr_fcsr_t orig;
    input csr_fflags_t d;
    csr_fcsr_t ret;
  begin
    ret = orig;
    ret.eflags = d.eflags;
    ret.flags = d.flags;
    return ret;
  end
  endfunction

  function automatic csr_frm_t read_fcsr_as_frm;
    input csr_fcsr_t orig;
    csr_frm_t ret;
  begin
    ret = '0;
    ret.rm = orig.rm;
    return ret;
  end
  endfunction

  function automatic csr_fcsr_t write_fcsr_as_frm;
    input csr_fcsr_t orig;
    input csr_frm_t d;
    csr_fcsr_t ret;
  begin
    ret = orig;
    ret.rm = d.rm;
    return ret;
  end
  endfunction

  function automatic csr_sstatus_t read_mstatus_as_sstatus;
    input csr_mstatus_t orig;
    csr_sstatus_t ret;
  begin
    ret = '0;
    ret.sd = orig.sd;
    ret.uxl = orig.uxl;
    ret.mxr = orig.mxr;
    ret.sum = orig.sum;
    ret.xs = orig.xs;
    ret.fs = orig.fs;
    ret.spp = orig.spp;
    ret.spie = orig.spie;
    ret.sie = orig.sie;
    return ret;
  end
  endfunction

  function automatic csr_mstatus_t write_mstatus_as_sstatus;
    input csr_mstatus_t orig;
    input csr_sstatus_t d;
    csr_mstatus_t ret;
  begin
    ret = orig;
    // ret.sd = RO;
    // ret.uxl = RO;
    ret.mxr = d.mxr;
    ret.sum = d.sum;
    // ret.xs = RO;
    ret.fs = d.fs;
    ret.spp = d.spp;
    ret.spie = d.spie;
    ret.sie = d.sie;
    return ret;
  end
  endfunction

  function automatic csr_sie_t read_mie_as_sie;
    input csr_mie_t orig;
    csr_sie_t ret;
  begin
    ret = '0;
    ret.seie = orig.seie;
    ret.stie = orig.stie;
    ret.ssie = orig.ssie;
    return ret;
  end
  endfunction

  function automatic csr_mie_t write_mie_as_sie;
    input csr_mie_t orig;
    input csr_sie_t d;
    csr_mie_t ret;
  begin
    ret = orig;
    ret.seie = d.seie;
    ret.stie = d.stie;
    ret.ssie = d.ssie;
    return ret;
  end
  endfunction

  function automatic csr_sip_t read_mip_as_sip;
    input csr_mip_t orig;
    csr_sip_t ret;
  begin
    ret = '0;
    ret.seip = orig.seip;
    ret.stip = orig.stip;
    ret.ssip = orig.ssip;
    return ret;
  end
  endfunction

  function automatic csr_mip_t write_mip_as_sip;
    input csr_mip_t orig;
    input csr_sip_t d;
    csr_mip_t ret;
  begin
    ret = orig;
    ret.seip = d.seip;
    ret.stip = d.stip;
    ret.ssip = d.ssip;
    return ret;
  end
  endfunction

