// Auto-generated by gen_esr.py (CSR mode) — do not edit manually.

  logic [2-1:0] reg_fflags_en, reg_fflags_en_next;
  logic [2-1:0] reg_frm_en, reg_frm_en_next;
  csr_fcsr_t [2-1:0] reg_fcsr, reg_fcsr_pre, reg_fcsr_next;
  logic [2-1:0] reg_fcsr_en, reg_fcsr_en_next;
  logic reg_tensor_reduce_en, reg_tensor_reduce_en_next;
  tensorfma_control reg_tensor_fma, reg_tensor_fma_pre, reg_tensor_fma_next;
  logic reg_tensor_fma_en, reg_tensor_fma_en_next;
  logic reg_tensor_fma_latch_clk_en;
  tensorconv_size [2-1:0] reg_tensor_conv_size, reg_tensor_conv_size_pre, reg_tensor_conv_size_next;
  logic [2-1:0] reg_tensor_conv_size_en, reg_tensor_conv_size_en_next;
  logic [2-1:0] reg_tensor_conv_size_latch_clk_en;
  tensorconv_control [2-1:0] reg_tensor_conv_ctrl, reg_tensor_conv_ctrl_pre, reg_tensor_conv_ctrl_next;
  logic [2-1:0] reg_tensor_conv_ctrl_en, reg_tensor_conv_ctrl_en_next;
  logic [2-1:0] reg_tensor_conv_ctrl_latch_clk_en;
  tensorcoop_control reg_tensor_cooperation, reg_tensor_cooperation_pre, reg_tensor_cooperation_next;
  logic reg_tensor_cooperation_en, reg_tensor_cooperation_en_next;
  logic reg_tensor_cooperation_latch_clk_en;
  logic [2-1:0][16-1:0] reg_tensor_mask, reg_tensor_mask_next;
  logic [2-1:0] reg_tensor_mask_en, reg_tensor_mask_en_next;
  tensorquant_control reg_tensor_quant, reg_tensor_quant_pre, reg_tensor_quant_next;
  logic reg_tensor_quant_en, reg_tensor_quant_en_next;
  logic reg_tensor_quant_latch_clk_en;
  logic reg_tex_send_en, reg_tex_send_en_next;
  logic [2-1:0] reg_tensor_error_en, reg_tensor_error_en_next;
  logic reg_ucache_control_en, reg_ucache_control_en_next;
  logic reg_flb_en, reg_flb_en_next;
  logic [2-1:0] reg_fcc_en, reg_fcc_en_next;
  logic reg_stall_en, reg_stall_en_next;
  logic [2-1:0] reg_tensor_wait_en, reg_tensor_wait_en_next;
  logic reg_tensor_load_en, reg_tensor_load_en_next;
  logic [2-1:0][3-1:0] reg_gsc_progress, reg_gsc_progress_next;
  logic [2-1:0] reg_gsc_progress_en, reg_gsc_progress_en_next;
  logic reg_tensor_load_l2scp_en, reg_tensor_load_l2scp_en_next;
  logic reg_tensor_store_en, reg_tensor_store_en_next;
`ifdef ET_SIMULATION
  logic [2-1:0][64-1:0] reg_validation0, reg_validation0_next;
  logic [2-1:0] reg_validation0_en, reg_validation0_en_next;
  logic [2-1:0] reg_validation0_latch_clk_en;
`endif
`ifdef ET_SIMULATION
  logic [2-1:0][64-1:0] reg_validation1, reg_validation1_next;
  logic [2-1:0] reg_validation1_en, reg_validation1_en_next;
  logic [2-1:0] reg_validation1_latch_clk_en;
`endif
`ifdef ET_SIMULATION
  logic [2-1:0][64-1:0] reg_validation2, reg_validation2_next;
  logic [2-1:0] reg_validation2_en, reg_validation2_en_next;
  logic [2-1:0] reg_validation2_latch_clk_en;
`endif
`ifdef ET_SIMULATION
  logic [2-1:0][64-1:0] reg_validation3, reg_validation3_next;
  logic [2-1:0] reg_validation3_en, reg_validation3_en_next;
  logic [2-1:0] reg_validation3_latch_clk_en;
`endif
`ifdef NOT_VERIF_SIMULATION
  logic [2-1:0][1-1:0] reg_validation0_ps, reg_validation0_ps_next;
  logic [2-1:0] reg_validation0_ps_en, reg_validation0_ps_en_next;
`endif
`ifdef NOT_VERIF_SIMULATION
  logic [2-1:0][1-1:0] reg_validation1_ps, reg_validation1_ps_next;
  logic [2-1:0] reg_validation1_ps_en, reg_validation1_ps_en_next;
`endif
`ifdef NOT_VERIF_SIMULATION
  logic [2-1:0][1-1:0] reg_validation2_ps, reg_validation2_ps_next;
  logic [2-1:0] reg_validation2_ps_en, reg_validation2_ps_en_next;
`endif
`ifdef NOT_VERIF_SIMULATION
  logic [2-1:0][1-1:0] reg_validation3_ps, reg_validation3_ps_next;
  logic [2-1:0] reg_validation3_ps_en, reg_validation3_ps_en_next;
`endif
  logic reg_co_evict_va_en, reg_co_evict_va_en_next;
  logic reg_co_flush_va_en, reg_co_flush_va_en_next;
  logic reg_co_lock_va_en, reg_co_lock_va_en_next;
  logic reg_co_unlock_va_en, reg_co_unlock_va_en_next;
  logic reg_co_prefetch_va_en, reg_co_prefetch_va_en_next;
  logic [2-1:0] reg_sstatus_en, reg_sstatus_en_next;
  logic [2-1:0] reg_sie_en, reg_sie_en_next;
  csr_tvec_t [2-1:0] reg_stvec, reg_stvec_pre, reg_stvec_next;
  logic [2-1:0] reg_stvec_en, reg_stvec_en_next;
  logic [2-1:0][CsrNrCounters-1:0] reg_scounteren, reg_scounteren_next;
  logic [2-1:0] reg_scounteren_en, reg_scounteren_en_next;
  logic [2-1:0] reg_scounteren_latch_clk_en;
  logic [2-1:0][64-1:0] reg_sscratch, reg_sscratch_next;
  logic [2-1:0] reg_sscratch_en, reg_sscratch_en_next;
  logic [2-1:0] reg_sscratch_latch_clk_en;
  csr_pc_t [2-1:0] reg_sepc, reg_sepc_pre, reg_sepc_next;
  logic [2-1:0] reg_sepc_en, reg_sepc_en_next;
  csr_cause_t [2-1:0] reg_scause, reg_scause_pre, reg_scause_next;
  logic [2-1:0] reg_scause_en, reg_scause_en_next;
  logic [2-1:0][VaSizeExt-1:0] reg_stval, reg_stval_next;
  logic [2-1:0] reg_stval_en, reg_stval_en_next;
  logic [2-1:0] reg_sip_en, reg_sip_en_next;
  csr_satp_t reg_satp, reg_satp_pre, reg_satp_next;
  logic reg_satp_en, reg_satp_en_next;
  logic reg_satp_latch_clk_en;
  logic [2-1:0] reg_smsg_port0_en, reg_smsg_port0_en_next;
  logic [2-1:0] reg_smsg_port1_en, reg_smsg_port1_en_next;
  logic [2-1:0] reg_smsg_port2_en, reg_smsg_port2_en_next;
  logic [2-1:0] reg_smsg_port3_en, reg_smsg_port3_en_next;
  csr_mstatus_t [2-1:0] reg_mstatus, reg_mstatus_pre, reg_mstatus_next;
  logic [2-1:0] reg_mstatus_en, reg_mstatus_en_next;
  csr_medeleg_t [2-1:0] reg_medeleg, reg_medeleg_pre, reg_medeleg_next;
  logic [2-1:0] reg_medeleg_en, reg_medeleg_en_next;
  logic [2-1:0] reg_medeleg_latch_clk_en;
  csr_mideleg_t [2-1:0] reg_mideleg, reg_mideleg_pre, reg_mideleg_next;
  logic [2-1:0] reg_mideleg_en, reg_mideleg_en_next;
  logic [2-1:0] reg_mideleg_latch_clk_en;
  csr_mie_t [2-1:0] reg_mie, reg_mie_pre, reg_mie_next;
  logic [2-1:0] reg_mie_en, reg_mie_en_next;
  csr_tvec_t [2-1:0] reg_mtvec, reg_mtvec_pre, reg_mtvec_next;
  logic [2-1:0] reg_mtvec_en, reg_mtvec_en_next;
  logic [2-1:0][CsrNrCounters-1:0] reg_mcounteren, reg_mcounteren_next;
  logic [2-1:0] reg_mcounteren_en, reg_mcounteren_en_next;
  logic [2-1:0] reg_mcounteren_latch_clk_en;
  logic [2-1:0][64-1:0] reg_mscratch, reg_mscratch_next;
  logic [2-1:0] reg_mscratch_en, reg_mscratch_en_next;
  logic [2-1:0] reg_mscratch_latch_clk_en;
  csr_pc_t [2-1:0] reg_mepc, reg_mepc_pre, reg_mepc_next;
  logic [2-1:0] reg_mepc_en, reg_mepc_en_next;
  csr_cause_t [2-1:0] reg_mcause, reg_mcause_pre, reg_mcause_next;
  logic [2-1:0] reg_mcause_en, reg_mcause_en_next;
  logic [2-1:0][VaSizeExt-1:0] reg_mtval, reg_mtval_next;
  logic [2-1:0] reg_mtval_en, reg_mtval_en_next;
  csr_mip_t [2-1:0] reg_mip, reg_mip_pre, reg_mip_next;
  logic [2-1:0] reg_mip_en, reg_mip_en_next;
  logic [2-1:0][64-1:0] reg_pmpcfg0, reg_pmpcfg0_next;
  logic [2-1:0] reg_pmpcfg0_en, reg_pmpcfg0_en_next;
  logic [2-1:0][64-1:0] reg_pmpcfg2, reg_pmpcfg2_next;
  logic [2-1:0] reg_pmpcfg2_en, reg_pmpcfg2_en_next;
  logic [2-1:0][64-1:0] reg_pmpaddr0, reg_pmpaddr0_next;
  logic [2-1:0] reg_pmpaddr0_en, reg_pmpaddr0_en_next;
  logic [2-1:0][64-1:0] reg_pmpaddr1, reg_pmpaddr1_next;
  logic [2-1:0] reg_pmpaddr1_en, reg_pmpaddr1_en_next;
  logic [2-1:0][64-1:0] reg_pmpaddr15, reg_pmpaddr15_next;
  logic [2-1:0] reg_pmpaddr15_en, reg_pmpaddr15_en_next;
  logic reg_mcycle_en, reg_mcycle_en_next;
  logic [2-1:0] reg_minstret_en, reg_minstret_en_next;
  logic [2-1:0] reg_mhpmcounter3_en, reg_mhpmcounter3_en_next;
  logic [2-1:0] reg_mhpmcounter4_en, reg_mhpmcounter4_en_next;
  logic [2-1:0] reg_mhpmcounter5_en, reg_mhpmcounter5_en_next;
  logic [2-1:0] reg_mhpmcounter6_en, reg_mhpmcounter6_en_next;
  logic [2-1:0] reg_mhpmcounter7_en, reg_mhpmcounter7_en_next;
  logic [2-1:0] reg_mhpmcounter8_en, reg_mhpmcounter8_en_next;
  logic [2-1:0][CsrNrEventsL-1:0] reg_mhpmevent3, reg_mhpmevent3_next;
  logic [2-1:0] reg_mhpmevent3_en, reg_mhpmevent3_en_next;
  logic [2-1:0] reg_mhpmevent3_latch_clk_en;
  logic [2-1:0][CsrNrEventsL-1:0] reg_mhpmevent4, reg_mhpmevent4_next;
  logic [2-1:0] reg_mhpmevent4_en, reg_mhpmevent4_en_next;
  logic [2-1:0] reg_mhpmevent4_latch_clk_en;
  logic [2-1:0][CsrNrEventsL-1:0] reg_mhpmevent5, reg_mhpmevent5_next;
  logic [2-1:0] reg_mhpmevent5_en, reg_mhpmevent5_en_next;
  logic [2-1:0] reg_mhpmevent5_latch_clk_en;
  logic [2-1:0][CsrNrEventsL-1:0] reg_mhpmevent6, reg_mhpmevent6_next;
  logic [2-1:0] reg_mhpmevent6_en, reg_mhpmevent6_en_next;
  logic [2-1:0] reg_mhpmevent6_latch_clk_en;
  logic [2-1:0][CsrNrEventsL-1:0] reg_mhpmevent7, reg_mhpmevent7_next;
  logic [2-1:0] reg_mhpmevent7_en, reg_mhpmevent7_en_next;
  logic [2-1:0][CsrNrEventsL-1:0] reg_mhpmevent8, reg_mhpmevent8_next;
  logic [2-1:0] reg_mhpmevent8_en, reg_mhpmevent8_en_next;
  csr_tdata1_t [2-1:0] reg_tdata1, reg_tdata1_pre, reg_tdata1_next;
  logic [2-1:0] reg_tdata1_en, reg_tdata1_en_next;
  logic [2-1:0][VaSize-1:0] reg_tdata2, reg_tdata2_next;
  logic [2-1:0] reg_tdata2_en, reg_tdata2_en_next;
  logic [2-1:0] reg_tdata2_latch_clk_en;
  csr_dcsr_t [2-1:0] reg_dcsr, reg_dcsr_pre, reg_dcsr_next;
  logic [2-1:0] reg_dcsr_en, reg_dcsr_en_next;
  csr_pc_t [2-1:0] reg_dpc, reg_dpc_pre, reg_dpc_next;
  logic [2-1:0] reg_dpc_en, reg_dpc_en_next;
  logic [2-1:0] reg_ddata0_en, reg_ddata0_en_next;
  csr_matp_t reg_matp, reg_matp_pre, reg_matp_next;
  logic reg_matp_en, reg_matp_en_next;
  logic reg_matp_latch_clk_en;
  minst_mask_t [2-1:0] reg_minstmask, reg_minstmask_pre, reg_minstmask_next;
  logic [2-1:0] reg_minstmask_en, reg_minstmask_en_next;
  logic [2-1:0] reg_minstmask_latch_clk_en;
  logic [2-1:0][32-1:0] reg_minstmatch, reg_minstmatch_next;
  logic [2-1:0] reg_minstmatch_en, reg_minstmatch_en_next;
  logic [2-1:0] reg_minstmatch_latch_clk_en;
  logic reg_cacheInvalidate_en, reg_cacheInvalidate_en_next;
  menable_shadows_t reg_menable_shadows, reg_menable_shadows_pre, reg_menable_shadows_next;
  logic reg_menable_shadows_en, reg_menable_shadows_en_next;
  logic reg_menable_shadows_latch_clk_en;
  logic [1-1:0] reg_excl_mode, reg_excl_mode_next;
  logic reg_excl_mode_en, reg_excl_mode_en_next;
  logic reg_excl_mode_latch_clk_en;
  logic [2-1:0][PaSize-1:0] reg_mbusaddr, reg_mbusaddr_next;
  logic [2-1:0] reg_mbusaddr_en, reg_mbusaddr_en_next;
`ifdef DCACHE_REPORT_PC
  logic [2-1:0][PcSizeExt-1:0] reg_mbuspc, reg_mbuspc_next;
  logic [2-1:0] reg_mbuspc_en, reg_mbuspc_en_next;
`endif
  logic reg_mcache_control_en, reg_mcache_control_en_next;
  logic reg_co_evict_sw_en, reg_co_evict_sw_en_next;
  logic reg_co_flush_sw_en, reg_co_flush_sw_en_next;
  logic reg_co_lock_sw_en, reg_co_lock_sw_en_next;
  logic reg_co_unlock_sw_en, reg_co_unlock_sw_en_next;
