// Auto-generated by gen_esr.py (CSR mode) — do not edit manually.

        csr_ad_FFLAGS: begin
          mem_addr_valid = 1'b1;
          reg_fflags_en_next = {mem_wen && mem_thread_id, mem_wen && !mem_thread_id};
          io_rw_wb_rdata_next = 64'(read_fflags[mem_thread_id]);
        end
        csr_ad_FRM: begin
          mem_addr_valid = 1'b1;
          reg_frm_en_next = {mem_wen && mem_thread_id, mem_wen && !mem_thread_id};
          io_rw_wb_rdata_next = 64'(read_fcsr_as_frm(reg_fcsr[mem_thread_id]));
        end
        csr_ad_FCSR: begin
          mem_addr_valid = 1'b1;
          reg_fcsr_en_next = {mem_wen && mem_thread_id, mem_wen && !mem_thread_id};
          io_rw_wb_rdata_next = 64'(read_fcsr[mem_thread_id]);
        end
        csr_ad_CYCLE: begin
          mem_addr_valid = 1'b1;
          io_rw_wb_rdata_next = 64'(reg_mcycle);
        end
        csr_ad_INSTRET: begin
          mem_addr_valid = 1'b1;
          io_rw_wb_rdata_next = 64'(reg_minstret[mem_thread_id]);
        end
        csr_ad_HPMCOUNTER3: begin
          mem_addr_valid = 1'b1;
          io_rw_wb_rdata_next = 64'(reg_mhpmcounter3[mem_thread_id]);
        end
        csr_ad_HPMCOUNTER4: begin
          mem_addr_valid = 1'b1;
          io_rw_wb_rdata_next = 64'(reg_mhpmcounter4[mem_thread_id]);
        end
        csr_ad_HPMCOUNTER5: begin
          mem_addr_valid = 1'b1;
          io_rw_wb_rdata_next = 64'(reg_mhpmcounter5[mem_thread_id]);
        end
        csr_ad_HPMCOUNTER6: begin
          mem_addr_valid = 1'b1;
          io_rw_wb_rdata_next = 64'(reg_mhpmcounter6[mem_thread_id]);
        end
        csr_ad_HPMCOUNTER7: begin
          mem_addr_valid = 1'b1;
          io_rw_wb_rdata_next = 64'(reg_mhpmcounter7[mem_thread_id]);
        end
        csr_ad_HPMCOUNTER8: begin
          mem_addr_valid = 1'b1;
          io_rw_wb_rdata_next = 64'(reg_mhpmcounter8[mem_thread_id]);
        end
        csr_ad_TENSOR_REDUCE: begin
          mem_addr_valid = !trap_on_ml_or_thread1;
          reg_tensor_reduce_en_next = mem_wen && !trap_on_ml_or_thread1;
          mem_feature_xcpt = trap_on_ml_or_thread1;
          io_rw_wb_rdata_next = 64'(64'h0);
        end
        csr_ad_TENSOR_FMA: begin
          mem_addr_valid = !trap_on_ml_or_thread1;
          reg_tensor_fma_en_next = mem_wen && !trap_on_ml_or_thread1;
          mem_feature_xcpt = trap_on_ml_or_thread1;
          io_rw_wb_rdata_next = 64'(64'h0);
        end
        csr_ad_TENSOR_CONV_SIZE: begin
          mem_addr_valid = !esr_features.trap_on_ml;
          reg_tensor_conv_size_en_next = {mem_wen && mem_thread_id, mem_wen && !mem_thread_id} & {2{!esr_features.trap_on_ml}};
          mem_feature_xcpt = esr_features.trap_on_ml;
          io_rw_wb_rdata_next = 64'(64'h0);
        end
        csr_ad_TENSOR_CONV_CTRL: begin
          mem_addr_valid = !esr_features.trap_on_ml;
          reg_tensor_conv_ctrl_en_next = {mem_wen && mem_thread_id, mem_wen && !mem_thread_id} & {2{!esr_features.trap_on_ml}};
          mem_feature_xcpt = esr_features.trap_on_ml;
          io_rw_wb_rdata_next = 64'(64'h0);
        end
        csr_ad_TENSOR_COOPERATION: begin
          mem_addr_valid = !trap_on_ml_or_thread1;
          reg_tensor_cooperation_en_next = mem_wen && !trap_on_ml_or_thread1;
          mem_feature_xcpt = trap_on_ml_or_thread1;
          io_rw_wb_rdata_next = 64'(64'h0);
        end
        csr_ad_TENSOR_MASK: begin
          mem_addr_valid = !esr_features.trap_on_ml;
          reg_tensor_mask_en_next = {mem_wen && mem_thread_id, mem_wen && !mem_thread_id} & {2{!esr_features.trap_on_ml}};
          mem_feature_xcpt = esr_features.trap_on_ml;
          io_rw_wb_rdata_next = 64'(reg_tensor_mask[mem_thread_id]);
        end
        csr_ad_TENSOR_QUANT: begin
          mem_addr_valid = !trap_on_ml_or_thread1;
          reg_tensor_quant_en_next = mem_wen && !trap_on_ml_or_thread1;
          mem_feature_xcpt = trap_on_ml_or_thread1;
          io_rw_wb_rdata_next = 64'(64'h0);
        end
        csr_ad_TEX_SEND: begin
          mem_addr_valid = !esr_features.trap_on_gfx;
          reg_tex_send_en_next = mem_wen && !esr_features.trap_on_gfx;
          mem_feature_xcpt = esr_features.trap_on_gfx;
          io_rw_wb_rdata_next = 64'(64'h0);
        end
        csr_ad_TENSOR_ERROR: begin
          mem_addr_valid = 1'b1;
          reg_tensor_error_en_next = {mem_wen && mem_thread_id, mem_wen && !mem_thread_id};
          io_rw_wb_rdata_next = 64'(reg_tensor_error[mem_thread_id]);
        end
        csr_ad_UCACHE_CONTROL: begin
          mem_addr_valid = !esr_features.trap_on_u_scp;
          reg_ucache_control_en_next = mem_wen && !esr_features.trap_on_u_scp;
          mem_feature_xcpt = esr_features.trap_on_u_scp;
          io_rw_wb_rdata_next = 64'(reg_ucache_control);
        end
        csr_ad_FLB: begin
          mem_addr_valid = !esr_features.trap_on_ml;
          reg_flb_en_next = mem_wen && !esr_features.trap_on_ml;
          mem_feature_xcpt = esr_features.trap_on_ml;
          io_rw_wb_rdata_next = 64'(64'h0);
        end
        csr_ad_FCC: begin
          mem_addr_valid = !esr_features.trap_on_ml;
          reg_fcc_en_next = {mem_wen && mem_thread_id, mem_wen && !mem_thread_id} & {2{!esr_features.trap_on_ml}};
          mem_feature_xcpt = esr_features.trap_on_ml;
          io_rw_wb_rdata_next = 64'(64'h0);
        end
        csr_ad_STALL: begin
          mem_addr_valid = !esr_features.trap_on_ml;
          reg_stall_en_next = mem_wen && !esr_features.trap_on_ml;
          mem_feature_xcpt = esr_features.trap_on_ml;
          io_rw_wb_rdata_next = 64'(64'h0);
        end
        csr_ad_TENSOR_WAIT: begin
          mem_addr_valid = 1'b1;
          reg_tensor_wait_en_next = {mem_wen && mem_thread_id, mem_wen && !mem_thread_id};
          io_rw_wb_rdata_next = 64'(64'h0);
        end
        csr_ad_TENSOR_LOAD: begin
          mem_addr_valid = !trap_on_ml_or_thread1;
          reg_tensor_load_en_next = mem_wen && !trap_on_ml_or_thread1;
          mem_feature_xcpt = trap_on_ml_or_thread1;
          io_rw_wb_rdata_next = 64'(64'h0);
        end
        csr_ad_GSC_PROGRESS: begin
          mem_addr_valid = 1'b1;
          reg_gsc_progress_en_next = {mem_wen && mem_thread_id, mem_wen && !mem_thread_id};
          io_rw_wb_rdata_next = 64'(reg_gsc_progress[mem_thread_id]);
        end
        csr_ad_TENSOR_LOAD_L2SCP: begin
          mem_addr_valid = !esr_features.trap_on_ml;
          reg_tensor_load_l2scp_en_next = mem_wen && !esr_features.trap_on_ml;
          mem_feature_xcpt = esr_features.trap_on_ml;
          io_rw_wb_rdata_next = 64'(64'h0);
        end
        csr_ad_TENSOR_STORE: begin
          mem_addr_valid = !trap_on_ml_or_thread1;
          reg_tensor_store_en_next = mem_wen && !trap_on_ml_or_thread1;
          mem_feature_xcpt = trap_on_ml_or_thread1;
          io_rw_wb_rdata_next = 64'(64'h0);
        end
`ifdef ET_SIMULATION
        csr_ad_VALIDATION0: begin
          mem_addr_valid = 1'b1;
          reg_validation0_en_next = {mem_wen && mem_thread_id, mem_wen && !mem_thread_id};
          io_rw_wb_rdata_next = 64'(reg_validation0[mem_thread_id]);
        end
`endif
`ifdef ET_SIMULATION
        csr_ad_VALIDATION1: begin
          mem_addr_valid = 1'b1;
          reg_validation1_en_next = {mem_wen && mem_thread_id, mem_wen && !mem_thread_id};
          io_rw_wb_rdata_next = 64'(reg_validation1[mem_thread_id]);
        end
`endif
`ifdef ET_SIMULATION
        csr_ad_VALIDATION2: begin
          mem_addr_valid = 1'b1;
          reg_validation2_en_next = {mem_wen && mem_thread_id, mem_wen && !mem_thread_id};
          io_rw_wb_rdata_next = 64'(reg_validation2[mem_thread_id]);
        end
`endif
`ifdef ET_SIMULATION
        csr_ad_VALIDATION3: begin
          mem_addr_valid = 1'b1;
          reg_validation3_en_next = {mem_wen && mem_thread_id, mem_wen && !mem_thread_id};
          io_rw_wb_rdata_next = 64'(reg_validation3[mem_thread_id]);
        end
`endif
`ifdef NOT_VERIF_SIMULATION
        csr_ad_VALIDATION0_PS: begin
          mem_addr_valid = 1'b1;
          reg_validation0_ps_en_next = {mem_wen && mem_thread_id, mem_wen && !mem_thread_id};
          io_rw_wb_rdata_next = 64'(64'h0);
        end
`endif
`ifdef NOT_VERIF_SIMULATION
        csr_ad_VALIDATION1_PS: begin
          mem_addr_valid = 1'b1;
          reg_validation1_ps_en_next = {mem_wen && mem_thread_id, mem_wen && !mem_thread_id};
          io_rw_wb_rdata_next = 64'(64'h0);
        end
`endif
`ifdef NOT_VERIF_SIMULATION
        csr_ad_VALIDATION2_PS: begin
          mem_addr_valid = 1'b1;
          reg_validation2_ps_en_next = {mem_wen && mem_thread_id, mem_wen && !mem_thread_id};
          io_rw_wb_rdata_next = 64'(64'h0);
        end
`endif
`ifdef NOT_VERIF_SIMULATION
        csr_ad_VALIDATION3_PS: begin
          mem_addr_valid = 1'b1;
          reg_validation3_ps_en_next = {mem_wen && mem_thread_id, mem_wen && !mem_thread_id};
          io_rw_wb_rdata_next = 64'(64'h0);
        end
`endif
        csr_ad_HARTID: begin
          mem_addr_valid = 1'b1;
          io_rw_wb_rdata_next = 64'(read_hartid);
        end
        csr_ad_NB_FCC: begin
          mem_addr_valid = !esr_features.trap_on_ml;
          mem_feature_xcpt = esr_features.trap_on_ml;
          io_rw_wb_rdata_next = 64'(read_nb_fcc[mem_thread_id]);
        end
        csr_ad_PORTHEAD0: begin
          mem_addr_valid = 1'b1;
          io_rw_wb_rdata_next = 64'(msg_port_rdata[mem_thread_id]);
        end
        csr_ad_PORTHEAD1: begin
          mem_addr_valid = 1'b1;
          io_rw_wb_rdata_next = 64'(msg_port_rdata[mem_thread_id]);
        end
        csr_ad_PORTHEAD2: begin
          mem_addr_valid = 1'b1;
          io_rw_wb_rdata_next = 64'(msg_port_rdata[mem_thread_id]);
        end
        csr_ad_PORTHEAD3: begin
          mem_addr_valid = 1'b1;
          io_rw_wb_rdata_next = 64'(msg_port_rdata[mem_thread_id]);
        end
        csr_ad_PORTHEADNB0: begin
          mem_addr_valid = 1'b1;
          io_rw_wb_rdata_next = 64'(msg_port_rdata[mem_thread_id]);
        end
        csr_ad_PORTHEADNB1: begin
          mem_addr_valid = 1'b1;
          io_rw_wb_rdata_next = 64'(msg_port_rdata[mem_thread_id]);
        end
        csr_ad_PORTHEADNB2: begin
          mem_addr_valid = 1'b1;
          io_rw_wb_rdata_next = 64'(msg_port_rdata[mem_thread_id]);
        end
        csr_ad_PORTHEADNB3: begin
          mem_addr_valid = 1'b1;
          io_rw_wb_rdata_next = 64'(msg_port_rdata[mem_thread_id]);
        end
        csr_ad_CO_EVICT_VA: begin
          mem_addr_valid = !esr_features.trap_on_u_cacheops;
          reg_co_evict_va_en_next = mem_wen && !esr_features.trap_on_u_cacheops;
          mem_feature_xcpt = esr_features.trap_on_u_cacheops;
          io_rw_wb_rdata_next = 64'(64'h0);
        end
        csr_ad_CO_FLUSH_VA: begin
          mem_addr_valid = !esr_features.trap_on_u_cacheops;
          reg_co_flush_va_en_next = mem_wen && !esr_features.trap_on_u_cacheops;
          mem_feature_xcpt = esr_features.trap_on_u_cacheops;
          io_rw_wb_rdata_next = 64'(64'h0);
        end
        csr_ad_CO_LOCK_VA: begin
          mem_addr_valid = !esr_features.trap_on_u_cacheops;
          reg_co_lock_va_en_next = mem_wen && !esr_features.trap_on_u_cacheops;
          mem_feature_xcpt = esr_features.trap_on_u_cacheops;
          io_rw_wb_rdata_next = 64'(64'h0);
        end
        csr_ad_CO_UNLOCK_VA: begin
          mem_addr_valid = !esr_features.trap_on_u_cacheops;
          reg_co_unlock_va_en_next = mem_wen && !esr_features.trap_on_u_cacheops;
          mem_feature_xcpt = esr_features.trap_on_u_cacheops;
          io_rw_wb_rdata_next = 64'(64'h0);
        end
        csr_ad_CO_PREFETCH_VA: begin
          mem_addr_valid = !esr_features.trap_on_u_cacheops;
          reg_co_prefetch_va_en_next = mem_wen && !esr_features.trap_on_u_cacheops;
          mem_feature_xcpt = esr_features.trap_on_u_cacheops;
          io_rw_wb_rdata_next = 64'(64'h0);
        end
        csr_ad_SSTATUS: begin
          mem_addr_valid = 1'b1;
          reg_sstatus_en_next = {mem_wen && mem_thread_id, mem_wen && !mem_thread_id};
          io_rw_wb_rdata_next = 64'(read_sstatus[mem_thread_id]);
        end
        csr_ad_SIE: begin
          mem_addr_valid = 1'b1;
          reg_sie_en_next = {mem_wen && mem_thread_id, mem_wen && !mem_thread_id};
          io_rw_wb_rdata_next = 64'(read_sie[mem_thread_id]);
        end
        csr_ad_STVEC: begin
          mem_addr_valid = 1'b1;
          reg_stvec_en_next = {mem_wen && mem_thread_id, mem_wen && !mem_thread_id};
          io_rw_wb_rdata_next = 64'($signed(reg_stvec[mem_thread_id]));
        end
        csr_ad_SCOUNTEREN: begin
          mem_addr_valid = 1'b1;
          reg_scounteren_en_next = {mem_wen && mem_thread_id, mem_wen && !mem_thread_id};
          io_rw_wb_rdata_next = 64'(reg_scounteren[mem_thread_id]);
        end
        csr_ad_SSCRATCH: begin
          mem_addr_valid = 1'b1;
          reg_sscratch_en_next = {mem_wen && mem_thread_id, mem_wen && !mem_thread_id};
          io_rw_wb_rdata_next = 64'(reg_sscratch[mem_thread_id]);
        end
        csr_ad_SEPC: begin
          mem_addr_valid = 1'b1;
          reg_sepc_en_next = {mem_wen && mem_thread_id, mem_wen && !mem_thread_id};
          io_rw_wb_rdata_next = 64'($signed(reg_sepc[mem_thread_id]));
        end
        csr_ad_SCAUSE: begin
          mem_addr_valid = 1'b1;
          reg_scause_en_next = {mem_wen && mem_thread_id, mem_wen && !mem_thread_id};
          io_rw_wb_rdata_next = 64'(reg_scause[mem_thread_id]);
        end
        csr_ad_STVAL: begin
          mem_addr_valid = 1'b1;
          reg_stval_en_next = {mem_wen && mem_thread_id, mem_wen && !mem_thread_id};
          io_rw_wb_rdata_next = 64'($signed(reg_stval[mem_thread_id]));
        end
        csr_ad_SIP: begin
          mem_addr_valid = 1'b1;
          reg_sip_en_next = {mem_wen && mem_thread_id, mem_wen && !mem_thread_id};
          io_rw_wb_rdata_next = 64'(read_sip[mem_thread_id]);
        end
        csr_ad_SATP: begin
          mem_addr_valid = !mem_trap_virtual_memory;
          reg_satp_en_next = mem_wen && !mem_trap_virtual_memory;
          mem_feature_xcpt = mem_trap_virtual_memory;
          io_rw_wb_rdata_next = 64'(reg_satp);
        end
        csr_ad_SMSG_PORT0: begin
          mem_addr_valid = 1'b1;
          reg_smsg_port0_en_next = {mem_wen && mem_thread_id, mem_wen && !mem_thread_id};
          io_rw_wb_rdata_next = 64'(portctl_rdata[mem_thread_id]);
        end
        csr_ad_SMSG_PORT1: begin
          mem_addr_valid = 1'b1;
          reg_smsg_port1_en_next = {mem_wen && mem_thread_id, mem_wen && !mem_thread_id};
          io_rw_wb_rdata_next = 64'(portctl_rdata[mem_thread_id]);
        end
        csr_ad_SMSG_PORT2: begin
          mem_addr_valid = 1'b1;
          reg_smsg_port2_en_next = {mem_wen && mem_thread_id, mem_wen && !mem_thread_id};
          io_rw_wb_rdata_next = 64'(portctl_rdata[mem_thread_id]);
        end
        csr_ad_SMSG_PORT3: begin
          mem_addr_valid = 1'b1;
          reg_smsg_port3_en_next = {mem_wen && mem_thread_id, mem_wen && !mem_thread_id};
          io_rw_wb_rdata_next = 64'(portctl_rdata[mem_thread_id]);
        end
        csr_ad_MVENDORID: begin
          mem_addr_valid = 1'b1;
          io_rw_wb_rdata_next = CsrVendorId;
        end
        csr_ad_MARCHID: begin
          mem_addr_valid = 1'b1;
          io_rw_wb_rdata_next = CsrArchId;
        end
        csr_ad_MIMPID: begin
          mem_addr_valid = 1'b1;
          io_rw_wb_rdata_next = CsrImpId;
        end
        csr_ad_MHARTID: begin
          mem_addr_valid = 1'b1;
          io_rw_wb_rdata_next = read_hartid;
        end
        csr_ad_MSTATUS: begin
          mem_addr_valid = 1'b1;
          reg_mstatus_en_next = {mem_wen && mem_thread_id, mem_wen && !mem_thread_id};
          io_rw_wb_rdata_next = 64'(read_mstatus[mem_thread_id]);
        end
        csr_ad_MISA: begin
          mem_addr_valid = 1'b1;
          io_rw_wb_rdata_next = CsrIsaMax;
        end
        csr_ad_MEDELEG: begin
          mem_addr_valid = 1'b1;
          reg_medeleg_en_next = {mem_wen && mem_thread_id, mem_wen && !mem_thread_id};
          io_rw_wb_rdata_next = 64'(reg_medeleg[mem_thread_id]);
        end
        csr_ad_MIDELEG: begin
          mem_addr_valid = 1'b1;
          reg_mideleg_en_next = {mem_wen && mem_thread_id, mem_wen && !mem_thread_id};
          io_rw_wb_rdata_next = 64'(reg_mideleg[mem_thread_id]);
        end
        csr_ad_MIE: begin
          mem_addr_valid = 1'b1;
          reg_mie_en_next = {mem_wen && mem_thread_id, mem_wen && !mem_thread_id};
          io_rw_wb_rdata_next = 64'(reg_mie[mem_thread_id]);
        end
        csr_ad_MTVEC: begin
          mem_addr_valid = 1'b1;
          reg_mtvec_en_next = {mem_wen && mem_thread_id, mem_wen && !mem_thread_id};
          io_rw_wb_rdata_next = 64'($signed(reg_mtvec[mem_thread_id]));
        end
        csr_ad_MCOUNTEREN: begin
          mem_addr_valid = 1'b1;
          reg_mcounteren_en_next = {mem_wen && mem_thread_id, mem_wen && !mem_thread_id};
          io_rw_wb_rdata_next = 64'(reg_mcounteren[mem_thread_id]);
        end
        csr_ad_MSCRATCH: begin
          mem_addr_valid = 1'b1;
          reg_mscratch_en_next = {mem_wen && mem_thread_id, mem_wen && !mem_thread_id};
          io_rw_wb_rdata_next = 64'(reg_mscratch[mem_thread_id]);
        end
        csr_ad_MEPC: begin
          mem_addr_valid = 1'b1;
          reg_mepc_en_next = {mem_wen && mem_thread_id, mem_wen && !mem_thread_id};
          io_rw_wb_rdata_next = 64'($signed(reg_mepc[mem_thread_id]));
        end
        csr_ad_MCAUSE: begin
          mem_addr_valid = 1'b1;
          reg_mcause_en_next = {mem_wen && mem_thread_id, mem_wen && !mem_thread_id};
          io_rw_wb_rdata_next = 64'(reg_mcause[mem_thread_id]);
        end
        csr_ad_MTVAL: begin
          mem_addr_valid = 1'b1;
          reg_mtval_en_next = {mem_wen && mem_thread_id, mem_wen && !mem_thread_id};
          io_rw_wb_rdata_next = 64'($signed(reg_mtval[mem_thread_id]));
        end
        csr_ad_MIP: begin
          mem_addr_valid = 1'b1;
          reg_mip_en_next = {mem_wen && mem_thread_id, mem_wen && !mem_thread_id};
          io_rw_wb_rdata_next = 64'(read_mip[mem_thread_id]);
        end
        csr_ad_PMPCFG0: begin
          mem_addr_valid = 1'b1;
          reg_pmpcfg0_en_next = {mem_wen && mem_thread_id, mem_wen && !mem_thread_id};
          io_rw_wb_rdata_next = 64'(reg_pmpcfg0[mem_thread_id]);
        end
        csr_ad_PMPCFG2: begin
          mem_addr_valid = 1'b1;
          reg_pmpcfg2_en_next = {mem_wen && mem_thread_id, mem_wen && !mem_thread_id};
          io_rw_wb_rdata_next = 64'(reg_pmpcfg2[mem_thread_id]);
        end
        csr_ad_PMPADDR0: begin
          mem_addr_valid = 1'b1;
          reg_pmpaddr0_en_next = {mem_wen && mem_thread_id, mem_wen && !mem_thread_id};
          io_rw_wb_rdata_next = 64'(reg_pmpaddr0[mem_thread_id]);
        end
        csr_ad_PMPADDR1: begin
          mem_addr_valid = 1'b1;
          reg_pmpaddr1_en_next = {mem_wen && mem_thread_id, mem_wen && !mem_thread_id};
          io_rw_wb_rdata_next = 64'(reg_pmpaddr1[mem_thread_id]);
        end
        csr_ad_PMPADDR15: begin
          mem_addr_valid = 1'b1;
          reg_pmpaddr15_en_next = {mem_wen && mem_thread_id, mem_wen && !mem_thread_id};
          io_rw_wb_rdata_next = 64'(reg_pmpaddr15[mem_thread_id]);
        end
        csr_ad_MCYCLE: begin
          mem_addr_valid = 1'b1;
          reg_mcycle_en_next = mem_wen;
          io_rw_wb_rdata_next = 64'(reg_mcycle);
        end
        csr_ad_MINSTRET: begin
          mem_addr_valid = 1'b1;
          reg_minstret_en_next = {mem_wen && mem_thread_id, mem_wen && !mem_thread_id};
          io_rw_wb_rdata_next = 64'(reg_minstret[mem_thread_id]);
        end
        csr_ad_MHPMCOUNTER3: begin
          mem_addr_valid = 1'b1;
          reg_mhpmcounter3_en_next = {mem_wen && mem_thread_id, mem_wen && !mem_thread_id};
          io_rw_wb_rdata_next = 64'(reg_mhpmcounter3[mem_thread_id]);
        end
        csr_ad_MHPMCOUNTER4: begin
          mem_addr_valid = 1'b1;
          reg_mhpmcounter4_en_next = {mem_wen && mem_thread_id, mem_wen && !mem_thread_id};
          io_rw_wb_rdata_next = 64'(reg_mhpmcounter4[mem_thread_id]);
        end
        csr_ad_MHPMCOUNTER5: begin
          mem_addr_valid = 1'b1;
          reg_mhpmcounter5_en_next = {mem_wen && mem_thread_id, mem_wen && !mem_thread_id};
          io_rw_wb_rdata_next = 64'(reg_mhpmcounter5[mem_thread_id]);
        end
        csr_ad_MHPMCOUNTER6: begin
          mem_addr_valid = 1'b1;
          reg_mhpmcounter6_en_next = {mem_wen && mem_thread_id, mem_wen && !mem_thread_id};
          io_rw_wb_rdata_next = 64'(reg_mhpmcounter6[mem_thread_id]);
        end
        csr_ad_MHPMCOUNTER7: begin
          mem_addr_valid = 1'b1;
          reg_mhpmcounter7_en_next = {mem_wen && mem_thread_id, mem_wen && !mem_thread_id};
          io_rw_wb_rdata_next = 64'(reg_mhpmcounter7[mem_thread_id]);
        end
        csr_ad_MHPMCOUNTER8: begin
          mem_addr_valid = 1'b1;
          reg_mhpmcounter8_en_next = {mem_wen && mem_thread_id, mem_wen && !mem_thread_id};
          io_rw_wb_rdata_next = 64'(reg_mhpmcounter8[mem_thread_id]);
        end
        csr_ad_MHPMEVENT3: begin
          mem_addr_valid = 1'b1;
          reg_mhpmevent3_en_next = {mem_wen && mem_thread_id, mem_wen && !mem_thread_id};
          io_rw_wb_rdata_next = 64'(reg_mhpmevent3[mem_thread_id]);
        end
        csr_ad_MHPMEVENT4: begin
          mem_addr_valid = 1'b1;
          reg_mhpmevent4_en_next = {mem_wen && mem_thread_id, mem_wen && !mem_thread_id};
          io_rw_wb_rdata_next = 64'(reg_mhpmevent4[mem_thread_id]);
        end
        csr_ad_MHPMEVENT5: begin
          mem_addr_valid = 1'b1;
          reg_mhpmevent5_en_next = {mem_wen && mem_thread_id, mem_wen && !mem_thread_id};
          io_rw_wb_rdata_next = 64'(reg_mhpmevent5[mem_thread_id]);
        end
        csr_ad_MHPMEVENT6: begin
          mem_addr_valid = 1'b1;
          reg_mhpmevent6_en_next = {mem_wen && mem_thread_id, mem_wen && !mem_thread_id};
          io_rw_wb_rdata_next = 64'(reg_mhpmevent6[mem_thread_id]);
        end
        csr_ad_MHPMEVENT7: begin
          mem_addr_valid = 1'b1;
          reg_mhpmevent7_en_next = {mem_wen && mem_thread_id, mem_wen && !mem_thread_id};
          io_rw_wb_rdata_next = 64'(reg_mhpmevent7[mem_thread_id]);
        end
        csr_ad_MHPMEVENT8: begin
          mem_addr_valid = 1'b1;
          reg_mhpmevent8_en_next = {mem_wen && mem_thread_id, mem_wen && !mem_thread_id};
          io_rw_wb_rdata_next = 64'(reg_mhpmevent8[mem_thread_id]);
        end
        csr_ad_TSELECT: begin
          mem_addr_valid = 1'b1;
          io_rw_wb_rdata_next = 64'h0;
        end
        csr_ad_TDATA1: begin
          mem_addr_valid = 1'b1;
          reg_tdata1_en_next = {mem_wen && mem_thread_id, mem_wen && !mem_thread_id};
          io_rw_wb_rdata_next = 64'(read_tdata1[mem_thread_id]);
        end
        csr_ad_TDATA2: begin
          mem_addr_valid = 1'b1;
          reg_tdata2_en_next = {mem_wen && mem_thread_id, mem_wen && !mem_thread_id};
          io_rw_wb_rdata_next = 64'(reg_tdata2[mem_thread_id]);
        end
        csr_ad_DCSR: begin
          mem_addr_valid = 1'b1;
          reg_dcsr_en_next = {mem_wen && mem_thread_id, mem_wen && !mem_thread_id};
          io_rw_wb_rdata_next = 64'(reg_dcsr[mem_thread_id]);
        end
        csr_ad_DPC: begin
          mem_addr_valid = 1'b1;
          reg_dpc_en_next = {mem_wen && mem_thread_id, mem_wen && !mem_thread_id};
          io_rw_wb_rdata_next = 64'($signed(reg_dpc[mem_thread_id]));
        end
        csr_ad_DDATA0: begin
          mem_addr_valid = 1'b1;
          reg_ddata0_en_next = {mem_wen && mem_thread_id, mem_wen && !mem_thread_id};
          io_rw_wb_rdata_next = 64'(read_ddata0[mem_thread_id]);
        end
        csr_ad_MATP: begin
          mem_addr_valid = 1'b1;
          reg_matp_en_next = mem_wen;
          io_rw_wb_rdata_next = 64'(reg_matp);
        end
        csr_ad_MINSTMASK: begin
          mem_addr_valid = 1'b1;
          reg_minstmask_en_next = {mem_wen && mem_thread_id, mem_wen && !mem_thread_id};
          io_rw_wb_rdata_next = 64'(reg_minstmask[mem_thread_id]);
        end
        csr_ad_MINSTMATCH: begin
          mem_addr_valid = 1'b1;
          reg_minstmatch_en_next = {mem_wen && mem_thread_id, mem_wen && !mem_thread_id};
          io_rw_wb_rdata_next = 64'(reg_minstmatch[mem_thread_id]);
        end
        csr_ad_CACHEINVALIDATE: begin
          mem_addr_valid = 1'b1;
          reg_cacheInvalidate_en_next = mem_wen;
          io_rw_wb_rdata_next = 64'(64'h0);
        end
        csr_ad_MENABLE_SHADOWS: begin
          mem_addr_valid = 1'b1;
          reg_menable_shadows_en_next = mem_wen;
          io_rw_wb_rdata_next = 64'(reg_menable_shadows);
        end
        csr_ad_EXCL_MODE: begin
          mem_addr_valid = 1'b1;
          reg_excl_mode_en_next = mem_wen;
          io_rw_wb_rdata_next = 64'(reg_excl_mode);
        end
        csr_ad_MBUSADDR: begin
          mem_addr_valid = 1'b1;
          reg_mbusaddr_en_next = {mem_wen && mem_thread_id, mem_wen && !mem_thread_id};
          io_rw_wb_rdata_next = 64'(reg_mbusaddr[mem_thread_id]);
        end
`ifdef DCACHE_REPORT_PC
        csr_ad_MBUSPC: begin
          mem_addr_valid = 1'b1;
          reg_mbuspc_en_next = {mem_wen && mem_thread_id, mem_wen && !mem_thread_id};
          io_rw_wb_rdata_next = 64'(reg_mbuspc[mem_thread_id]);
        end
`endif
        csr_ad_MCACHE_CONTROL: begin
          mem_addr_valid = 1'b1;
          reg_mcache_control_en_next = mem_wen;
          io_rw_wb_rdata_next = 64'(reg_mcache_control);
        end
        csr_ad_CO_EVICT_SW: begin
          mem_addr_valid = 1'b1;
          reg_co_evict_sw_en_next = mem_wen;
          io_rw_wb_rdata_next = 64'(64'h0);
        end
        csr_ad_CO_FLUSH_SW: begin
          mem_addr_valid = 1'b1;
          reg_co_flush_sw_en_next = mem_wen;
          io_rw_wb_rdata_next = 64'(64'h0);
        end
        csr_ad_CO_LOCK_SW: begin
          mem_addr_valid = 1'b1;
          reg_co_lock_sw_en_next = mem_wen;
          io_rw_wb_rdata_next = 64'(64'h0);
        end
        csr_ad_CO_UNLOCK_SW: begin
          mem_addr_valid = 1'b1;
          reg_co_unlock_sw_en_next = mem_wen;
          io_rw_wb_rdata_next = 64'(64'h0);
        end
        csr_ad_DCACHE_DEBUG: begin
          mem_addr_valid = 1'b1;
          io_rw_wb_rdata_next = 64'(dcache_debug_signals);
        end
        csr_ad_MHPMCOUNTER9: begin
          mem_addr_valid = 1'b1;
          io_rw_wb_rdata_next = 64'h0;
        end
        csr_ad_MHPMCOUNTER10: begin
          mem_addr_valid = 1'b1;
          io_rw_wb_rdata_next = 64'h0;
        end
        csr_ad_MHPMCOUNTER11: begin
          mem_addr_valid = 1'b1;
          io_rw_wb_rdata_next = 64'h0;
        end
        csr_ad_MHPMCOUNTER12: begin
          mem_addr_valid = 1'b1;
          io_rw_wb_rdata_next = 64'h0;
        end
        csr_ad_MHPMCOUNTER13: begin
          mem_addr_valid = 1'b1;
          io_rw_wb_rdata_next = 64'h0;
        end
        csr_ad_MHPMCOUNTER14: begin
          mem_addr_valid = 1'b1;
          io_rw_wb_rdata_next = 64'h0;
        end
        csr_ad_MHPMCOUNTER15: begin
          mem_addr_valid = 1'b1;
          io_rw_wb_rdata_next = 64'h0;
        end
        csr_ad_MHPMCOUNTER16: begin
          mem_addr_valid = 1'b1;
          io_rw_wb_rdata_next = 64'h0;
        end
        csr_ad_MHPMCOUNTER17: begin
          mem_addr_valid = 1'b1;
          io_rw_wb_rdata_next = 64'h0;
        end
        csr_ad_MHPMCOUNTER18: begin
          mem_addr_valid = 1'b1;
          io_rw_wb_rdata_next = 64'h0;
        end
        csr_ad_MHPMCOUNTER19: begin
          mem_addr_valid = 1'b1;
          io_rw_wb_rdata_next = 64'h0;
        end
        csr_ad_MHPMCOUNTER20: begin
          mem_addr_valid = 1'b1;
          io_rw_wb_rdata_next = 64'h0;
        end
        csr_ad_MHPMCOUNTER21: begin
          mem_addr_valid = 1'b1;
          io_rw_wb_rdata_next = 64'h0;
        end
        csr_ad_MHPMCOUNTER22: begin
          mem_addr_valid = 1'b1;
          io_rw_wb_rdata_next = 64'h0;
        end
        csr_ad_MHPMCOUNTER23: begin
          mem_addr_valid = 1'b1;
          io_rw_wb_rdata_next = 64'h0;
        end
        csr_ad_MHPMCOUNTER24: begin
          mem_addr_valid = 1'b1;
          io_rw_wb_rdata_next = 64'h0;
        end
        csr_ad_MHPMCOUNTER25: begin
          mem_addr_valid = 1'b1;
          io_rw_wb_rdata_next = 64'h0;
        end
        csr_ad_MHPMCOUNTER26: begin
          mem_addr_valid = 1'b1;
          io_rw_wb_rdata_next = 64'h0;
        end
        csr_ad_MHPMCOUNTER27: begin
          mem_addr_valid = 1'b1;
          io_rw_wb_rdata_next = 64'h0;
        end
        csr_ad_MHPMCOUNTER28: begin
          mem_addr_valid = 1'b1;
          io_rw_wb_rdata_next = 64'h0;
        end
        csr_ad_MHPMCOUNTER29: begin
          mem_addr_valid = 1'b1;
          io_rw_wb_rdata_next = 64'h0;
        end
        csr_ad_MHPMCOUNTER30: begin
          mem_addr_valid = 1'b1;
          io_rw_wb_rdata_next = 64'h0;
        end
        csr_ad_MHPMCOUNTER31: begin
          mem_addr_valid = 1'b1;
          io_rw_wb_rdata_next = 64'h0;
        end
        csr_ad_MHPMEVENT9: begin
          mem_addr_valid = 1'b1;
          io_rw_wb_rdata_next = 64'h0;
        end
        csr_ad_MHPMEVENT10: begin
          mem_addr_valid = 1'b1;
          io_rw_wb_rdata_next = 64'h0;
        end
        csr_ad_MHPMEVENT11: begin
          mem_addr_valid = 1'b1;
          io_rw_wb_rdata_next = 64'h0;
        end
        csr_ad_MHPMEVENT12: begin
          mem_addr_valid = 1'b1;
          io_rw_wb_rdata_next = 64'h0;
        end
        csr_ad_MHPMEVENT13: begin
          mem_addr_valid = 1'b1;
          io_rw_wb_rdata_next = 64'h0;
        end
        csr_ad_MHPMEVENT14: begin
          mem_addr_valid = 1'b1;
          io_rw_wb_rdata_next = 64'h0;
        end
        csr_ad_MHPMEVENT15: begin
          mem_addr_valid = 1'b1;
          io_rw_wb_rdata_next = 64'h0;
        end
        csr_ad_MHPMEVENT16: begin
          mem_addr_valid = 1'b1;
          io_rw_wb_rdata_next = 64'h0;
        end
        csr_ad_MHPMEVENT17: begin
          mem_addr_valid = 1'b1;
          io_rw_wb_rdata_next = 64'h0;
        end
        csr_ad_MHPMEVENT18: begin
          mem_addr_valid = 1'b1;
          io_rw_wb_rdata_next = 64'h0;
        end
        csr_ad_MHPMEVENT19: begin
          mem_addr_valid = 1'b1;
          io_rw_wb_rdata_next = 64'h0;
        end
        csr_ad_MHPMEVENT20: begin
          mem_addr_valid = 1'b1;
          io_rw_wb_rdata_next = 64'h0;
        end
        csr_ad_MHPMEVENT21: begin
          mem_addr_valid = 1'b1;
          io_rw_wb_rdata_next = 64'h0;
        end
        csr_ad_MHPMEVENT22: begin
          mem_addr_valid = 1'b1;
          io_rw_wb_rdata_next = 64'h0;
        end
        csr_ad_MHPMEVENT23: begin
          mem_addr_valid = 1'b1;
          io_rw_wb_rdata_next = 64'h0;
        end
        csr_ad_MHPMEVENT24: begin
          mem_addr_valid = 1'b1;
          io_rw_wb_rdata_next = 64'h0;
        end
        csr_ad_MHPMEVENT25: begin
          mem_addr_valid = 1'b1;
          io_rw_wb_rdata_next = 64'h0;
        end
        csr_ad_MHPMEVENT26: begin
          mem_addr_valid = 1'b1;
          io_rw_wb_rdata_next = 64'h0;
        end
        csr_ad_MHPMEVENT27: begin
          mem_addr_valid = 1'b1;
          io_rw_wb_rdata_next = 64'h0;
        end
        csr_ad_MHPMEVENT28: begin
          mem_addr_valid = 1'b1;
          io_rw_wb_rdata_next = 64'h0;
        end
        csr_ad_MHPMEVENT29: begin
          mem_addr_valid = 1'b1;
          io_rw_wb_rdata_next = 64'h0;
        end
        csr_ad_MHPMEVENT30: begin
          mem_addr_valid = 1'b1;
          io_rw_wb_rdata_next = 64'h0;
        end
        csr_ad_MHPMEVENT31: begin
          mem_addr_valid = 1'b1;
          io_rw_wb_rdata_next = 64'h0;
        end
