// Copyright (c) 2026 Ainekko
// SPDX-License-Identifier: Apache-2.0

module cosim_txfma_e2_tb
  import vpu_defs_pkg::*;
(
  input  logic [VPU_FCMD_SZ-1:0]                  cmd_i,
  input  logic [VPU_DTYPE_SZ-1:0]                 op_dtype_i,
  input  logic [TXFMA_SIGS_SZ-1:0]                sigs_i,
  input  logic [TXFMA_EXP_SEXT_PS_SZ-1:0]         ediff_ec_eph_i,
  input  logic [TXFMA_EXP_SEXT_PS_SZ-1:0]         ediff_ec_epl_i,
  input  logic [TXFMA_EXP_SEXT_PS_SZ-1:0]         ediff_eph_epl_i,
  input  logic [TXFMA_EXP_SEXT_PS_SZ-1:0]         eprod_hi_i,
  input  logic [TXFMA_EXP_SEXT_PS_SZ-1:0]         eprod_lo_i,
  input  logic [TXFMA_EXP_PS_SZ-1:0]              ec_i,
  input  logic [TXFMA_EXP_PS_SZ-1:0]              eb_hi_i,
  input  logic [4:0]                               etrz_fa_lo_ps_i,
  input  logic [4:0]                               etrz_fc_i,
  input  logic [TXFMA_ETRZ_PROD_PH_SZ-1:0]        etrz_prod_hi_ph_i,
  input  logic [TXFMA_ETRZ_PROD_PS_SZ-1:0]        etrz_prod_lo_ps_i,
  input  logic                                     sin_ediff2_i,
  input  logic                                     eprod_hi_zero_i,
  input  logic                                     eprod_lo_zero_i,
  input  logic                                     ec_zero_i,
  input  logic                                     exp_fma2_exc_i,
  output logic                                     orig_e_sticky1_o,
  output logic                                     orig_e_sticky2_o,
  output logic                                     orig_ediff1_zap_o,
  output logic [5:0]                               orig_ediff_abs_diff_hi_o,
  output logic [4:0]                               orig_align2_rshamt_c3_o,
  output logic [6:0]                               orig_exp_res_2f3_o,
  output logic [TXFMA_EDIFF_OPD_SEL_SZ-1:0]        orig_align1_mux_sel_o,
  output logic [TXFMA_EDIFF_OPD_SEL_SZ-1:0]        orig_align2_mux_sel_o,
  output logic [TXFMA_EDIFF_OPD_SEL_SZ-1:0]        orig_opd3_mux_sel_o,
  output logic [TXFMA_EXP_SEXT_PS_SZ-1:0]          orig_ediff1_o,
  output logic [TXFMA_EXP_SEXT_PS_SZ-1:0]          orig_ediff2_o,
  output logic [TXFMA_EDIFF_OPD_SEL_SZ-1:0]        orig_ediff1_sel_o,
  output logic [TXFMA_EDIFF_OPD_SEL_SZ-1:0]        orig_ediff2_sel_o,
  output logic [TXFMA_EXP_SEXT_PS_SZ-1:0]          orig_ediff1_abs_o,
  output logic [TXFMA_EXP_SEXT_PS_SZ-1:0]          orig_ediff2_abs_o,
  output logic [TXFMA_EXP_SEXT_PS_SZ-1:0]          orig_exp_res_o,
  output logic                                     new_e_sticky1_o,
  output logic                                     new_e_sticky2_o,
  output logic                                     new_ediff1_zap_o,
  output logic [5:0]                               new_ediff_abs_diff_hi_o,
  output logic [4:0]                               new_align2_rshamt_c3_o,
  output logic [6:0]                               new_exp_res_2f3_o,
  output logic [TXFMA_EDIFF_OPD_SEL_SZ-1:0]        new_align1_mux_sel_o,
  output logic [TXFMA_EDIFF_OPD_SEL_SZ-1:0]        new_align2_mux_sel_o,
  output logic [TXFMA_EDIFF_OPD_SEL_SZ-1:0]        new_opd3_mux_sel_o,
  output logic [TXFMA_EXP_SEXT_PS_SZ-1:0]          new_ediff1_o,
  output logic [TXFMA_EXP_SEXT_PS_SZ-1:0]          new_ediff2_o,
  output logic [TXFMA_EDIFF_OPD_SEL_SZ-1:0]        new_ediff1_sel_o,
  output logic [TXFMA_EDIFF_OPD_SEL_SZ-1:0]        new_ediff2_sel_o,
  output logic [TXFMA_EXP_SEXT_PS_SZ-1:0]          new_ediff1_abs_o,
  output logic [TXFMA_EXP_SEXT_PS_SZ-1:0]          new_ediff2_abs_o,
  output logic [TXFMA_EXP_SEXT_PS_SZ-1:0]          new_exp_res_o
);

  txfma_e2_orig u_orig (
    .cmd_f2a_h                (cmd_i),
    .op_dtype_f2a_h           (op_dtype_i),
    .sigs_f2a_h               (sigs_i),
    .ediff_ec_eph_f2a_h       (ediff_ec_eph_i),
    .ediff_ec_epl_f2a_h       (ediff_ec_epl_i),
    .ediff_eph_epl_f2a_h      (ediff_eph_epl_i),
    .eprod_hi_f2a_h           (eprod_hi_i),
    .eprod_lo_f2a_h           (eprod_lo_i),
    .ec_f2a_h                 (ec_i),
    .eb_hi_f2a_h              (eb_hi_i),
    .etrz_fa_lo_ps_f2a_h      (etrz_fa_lo_ps_i),
    .etrz_fc_f2a_h            (etrz_fc_i),
    .etrz_prod_hi_ph_f2a_h    (etrz_prod_hi_ph_i),
    .etrz_prod_lo_ps_f2a_h    (etrz_prod_lo_ps_i),
    .sin_ediff2_f2a_h         (sin_ediff2_i),
    .eprod_hi_zero_f2a_h      (eprod_hi_zero_i),
    .eprod_lo_zero_f2a_h      (eprod_lo_zero_i),
    .ec_zero_f2a_h            (ec_zero_i),
    .exp_fma2_exc_f2a_h       (exp_fma2_exc_i),
    .e_sticky1_f2a_h          (orig_e_sticky1_o),
    .e_sticky2_f2a_h          (orig_e_sticky2_o),
    .ediff1_zap_f2a_h         (orig_ediff1_zap_o),
    .ediff_abs_diff_hi_f2a_h  (orig_ediff_abs_diff_hi_o),
    .align2_rshamt_c3_f2a_h   (orig_align2_rshamt_c3_o),
    .exp_res_2f3_f2a_h        (orig_exp_res_2f3_o),
    .align1_mux_sel_f2a_h     (orig_align1_mux_sel_o),
    .align2_mux_sel_f2a_h     (orig_align2_mux_sel_o),
    .opd3_mux_sel_f2a_h       (orig_opd3_mux_sel_o),
    .ediff1_f2a_h             (orig_ediff1_o),
    .ediff2_f2a_h             (orig_ediff2_o),
    .ediff1_sel_f2a_h         (orig_ediff1_sel_o),
    .ediff2_sel_f2a_h         (orig_ediff2_sel_o),
    .ediff1_abs_f2a_h         (orig_ediff1_abs_o),
    .ediff2_abs_f2a_h         (orig_ediff2_abs_o),
    .exp_res_f2a_h            (orig_exp_res_o)
  );

  txfma_e2 u_new (
    .cmd_f2a_h                (cmd_i),
    .op_dtype_f2a_h           (op_dtype_i),
    .sigs_f2a_h               (sigs_i),
    .ediff_ec_eph_f2a_h       (ediff_ec_eph_i),
    .ediff_ec_epl_f2a_h       (ediff_ec_epl_i),
    .ediff_eph_epl_f2a_h      (ediff_eph_epl_i),
    .eprod_hi_f2a_h           (eprod_hi_i),
    .eprod_lo_f2a_h           (eprod_lo_i),
    .ec_f2a_h                 (ec_i),
    .eb_hi_f2a_h              (eb_hi_i),
    .etrz_fa_lo_ps_f2a_h      (etrz_fa_lo_ps_i),
    .etrz_fc_f2a_h            (etrz_fc_i),
    .etrz_prod_hi_ph_f2a_h    (etrz_prod_hi_ph_i),
    .etrz_prod_lo_ps_f2a_h    (etrz_prod_lo_ps_i),
    .sin_ediff2_f2a_h         (sin_ediff2_i),
    .eprod_hi_zero_f2a_h      (eprod_hi_zero_i),
    .eprod_lo_zero_f2a_h      (eprod_lo_zero_i),
    .ec_zero_f2a_h            (ec_zero_i),
    .exp_fma2_exc_f2a_h       (exp_fma2_exc_i),
    .e_sticky1_f2a_h          (new_e_sticky1_o),
    .e_sticky2_f2a_h          (new_e_sticky2_o),
    .ediff1_zap_f2a_h         (new_ediff1_zap_o),
    .ediff_abs_diff_hi_f2a_h  (new_ediff_abs_diff_hi_o),
    .align2_rshamt_c3_f2a_h   (new_align2_rshamt_c3_o),
    .exp_res_2f3_f2a_h        (new_exp_res_2f3_o),
    .align1_mux_sel_f2a_h     (new_align1_mux_sel_o),
    .align2_mux_sel_f2a_h     (new_align2_mux_sel_o),
    .opd3_mux_sel_f2a_h       (new_opd3_mux_sel_o),
    .ediff1_f2a_h             (new_ediff1_o),
    .ediff2_f2a_h             (new_ediff2_o),
    .ediff1_sel_f2a_h         (new_ediff1_sel_o),
    .ediff2_sel_f2a_h         (new_ediff2_sel_o),
    .ediff1_abs_f2a_h         (new_ediff1_abs_o),
    .ediff2_abs_f2a_h         (new_ediff2_abs_o),
    .exp_res_f2a_h            (new_exp_res_o)
  );

endmodule : cosim_txfma_e2_tb
