#!/bin/bash
source $REPOROOT/dv/common/scripts/bash_utils.sh

info "Building ATPG test $testdir in `pwd`"

# Cleanup
#rm -rf simv.daidir
#rm -f  simv

echo "fsdbDumpvars +all +parameter;run" > ucli.tcl
echo "cmd=\`readlink -f \$0\`;debug_dir=\`dirname \$cmd\`;verdi -simflow -ssf \${debug_dir}/novas.fsdb " > debug_me
chmod +x debug_me
echo "./simv -ucli -i ucli.tcl " >> runme
chmod +x runme


echo "--Mapping default work directory" >  synopsys_sim.setup
echo "WORK > DEFAULT"                   >> synopsys_sim.setup
echo "DEFAULT : ./work"                 >> synopsys_sim.setup
echo "--Library Mapping"                >> synopsys_sim.setup
echo "--Library Mapping"                >> synopsys_sim.setup
echo "TB_PKG  : ./tb_pkg"               >> synopsys_sim.setup


VLOG_CMD="vlogan -sverilog -full64 -timescale=1ns/1fs +libext+.v+.vh+.sv+.svh -kdb -debug +vcs+lic+wait "
VCS_ARGS="-reportstats -j8 -ucli +vcs+lic+wait"

${VLOG_CMD} -work SOC_PKG \
+define+ET_USE_ASIC_MEMS +define+USE_REAL_DDRC \
-f $RTLROOT/ip/synopsys/ddrc/ddrc_rtl.f \
-f $RTLROOT/soctop/soctop_vcs.f \
$RTLROOT/soctop/soc_top.v \
$DDR_SS_DIR/src/top/ddr_ss_cc_constants.sv \
 | tee soc_compile.log 2>&1

${VLOG_CMD} -work TB_PKG $REPOROOT/physical/bist/ate/testbench/soc_top_tb_reset_pattern.v +incdir+$REPOROOT/physical/bist/ate/testbench/ | tee tb_compile.log 2>&1

vcs ${VCS_ARGS} SOC_PKG.soc_top TB_PKG.soc_top_tb_reset_pattern | tee elab.log 2>&1

info "run ./runme to execute:"
info "run ./debug_me for Verdi debug"
