#!/eng/dvtools/release/ruby/2.4.2/bin/ruby
# Hack the GEM_PATH To Karls Libary
ENV['GEM_PATH']="/eng/dvtools/release/ruby/mygems"
Gem.clear_paths

require 'optparse'
require 'fileutils'
require 'logger'
require 'awesome_print'
require 'tempfile'
require 'csv'
require 'tempfile'
require 'fileutils'
require_relative 'rblib/et_log'

#@@usage="usage: $0 {-h} {-v <verbose level>} {-s <grid number>}"

include ET_LOG

def file_edit(filename, regexp, replacement)
  Tempfile.open(".#{File.basename(filename)}", File.dirname(filename)) do |tempfile|
    File.open(filename).each do |line|
      tempfile.puts line.gsub(regexp, replacement)
    end
    tempfile.fdatasync
    tempfile.close
    stat = File.stat(filename)
    FileUtils.chown stat.uid, stat.gid, tempfile.path
    FileUtils.chmod stat.mode, tempfile.path
    FileUtils.mv tempfile.path, filename
  end
end

def setup_repo options

   # Is $REPOROOT defined and is it a valid writable path?
   if ENV.has_key? "REPOROOT"
     unless File.writable? ENV['REPOROOT']
       error "$REPOROOT points to non existant path #{ENV['REPO_ROOT']} or is not writable".colorize("red")
     end
   else
       error "Env var reporoot is not defined.  source env.sh in root of repo".colorize("red")
   end

   logpath="."
   options[:logpath] = logpath

   # Now that we are done cleaning etc, we can setup the proper log
   #'
   options[:prog_name]="make_pll_csv"
   level=:info
   @log = EtLog.new("#{logpath}/#{options[:prog_name]}.log",:info,false,options[:prog_name])
   if options[:verbose]
    level=:debug
   end
   @log.level = level
   @log.info "#{options[:prog_name]} is running"
   @log.info "logpath is #{logpath}/#{options[:prog_name]}.log"
   options[:logfile] = "#{logpath}/#{options[:prog_name]}.log"

   @log.info "command line=#{options[:cmd_line]}"

   options[:git_hash],rc = @log.et_backtick "cd ${REPOROOT};git rev-parse HEAD"
   options[:git_hash].chomp!
   @log.info "git revision=#{options[:git_hash]}"

   options[:git_short_hash],rc = @log.et_backtick "cd ${REPOROOT};git rev-parse --short HEAD"
   options[:git_short_hash].chomp!
   @log.info "git short hash=#{options[:git_short_hash]}"

   @log.info "Querying git repo for local modifications..."
   diff,rc =@log.et_backtick "cd ${REPOROOT};git diff"
   if diff != ""
     diff_path="#{logpath}/local_modifications.patch"
     f = File.new(diff_path, File::CREAT|File::TRUNC|File::RDWR, 0644)
     f.write diff
     f.close
     @log.warn "There were local modifications so creating patch file #{diff_path}"
   else
     @log.info "Repo is clean there are no modifications"
   end
end

def find_csv path
  return Dir["#{path}/*.csv"]
end

def parse_modes_spreadsheet options 

  #csv_hash=Hash.new

   my_csv = CSV.read options[:ss_csv_path]

   num_modes = ((my_csv.length) -1)
   for i in 1..num_modes
     row=my_csv[i]   
     unless row[0]==nil
       if row[5]=="DVFS"
         outfile="mode_#{row[0]}_i#{row[1]}_o#{row[2]}_dvfs"
       else
         outfile="mode_#{row[0]}_i#{row[1]}_o#{row[2]}"
       end
       @log.info "Generating #{outfile}"
       if options[:pll_type]=='LVDPLL'
         @log.et_sys "gen_pll_mode -p #{options[:pll_type]} -d #{options[:digital_voltage]} -i #{row[1]} -t #{row[2]} -o #{outfile}"
       else
         @log.et_sys "gen_pll_mode -p #{options[:pll_type]} -i #{row[1]} -t #{row[2]} -o #{outfile}"
       end

       # HACK: updating 1066MHz mode to use 2132MHz DCO freq instead of 1066MHz DCO freq
       if options[:pll_type]=='HPDPLL' && row[1]=='100' && row[2]=='1066'
          @log.info "HACK: updating 1066MHz HPDPLL mode to use 2132MHz DCO freq instead of 1066MHz DCO freq"
          path = "reg/HPDPLL_mode_#{row[0]}_i#{row[1]}_o#{row[2]}.csv"
          temp_file = Tempfile.new('foo')
          begin
            File.open(path, 'r') do |file|
              file.each_line do |line|
                if line.strip.eql? '0x2,0xa'
                  temp_file.puts '0x2,0x15'
                elsif line.strip.eql? '0x3,0xa8f6'
                  temp_file.puts '0x3,0x51ec'
                elsif line.strip.eql? '0xb,0xbf'
                  temp_file.puts '0xb,0x17e'
                elsif line.strip.eql? '0xe,0x1'
                  temp_file.puts '0xe,0x2'
                else
                  temp_file.puts line
                end
              end
            end
            temp_file.close
            FileUtils.mv(temp_file.path, path)
          ensure
            temp_file.close
            temp_file.unlink
          end
       end
     end
   end
end

begin
   cmd_line="make_pll_csv"
   ARGV.each { |arg| cmd_line += " #{arg}" }

   options = {}
   OptionParser.new do |opts|
     opts.banner = "Usage: make_pll_csv [options]"
     opts.on("-f spreadsheet.csv","--file spreadsheet.csv","Specify path spreadsheet CSV of all the modes") do |arg|
       options[:ss_csv_path] = File.expand_path arg
     end
     opts.on("-p [HPDPLL or LVDPLL]","--pll [HPDPLL or LVDPLL]","Specify PLL type [HPDPLL or LVDPLL]") do |arg|
       options[:pll_type] = arg
     end
     opts.on("-o filename", "--output filename", "Output name for hal file to generate") do |arg|
       options[:hal_name] = arg
     end
     opts.on("-q", "--quiet", "Quiesce most output") do |arg|
       options[:quiet] = arg
     end
     opts.on("-v", "--verbose", "Verbose output") do |arg|
       options[:verbose] = arg
     end
     opts.on("-d voltage", "--digital_voltage voltage", "LVDPLL digital voltage") do |arg|
       options[:digital_voltage] = arg
     end
   end.parse!
   options[:cmd_line]=cmd_line

   unless options[:quiet]
     options[:quiet]=:info
   end

   #
   # Setup the workspace, cleanup, and get the log setup
   #
   setup_repo options
   @log.info "cmd_line=#{cmd_line}"

   require 'socket'
   hostname = Socket.gethostname
   @log.info "running on hostname=#{hostname}"

   ap options      if options[:verbose]
   @log.ap options if options[:verbose]

   unless options[:pll_type]
     options[:pll_type]="HPDPLL"
     @log.info "-p or --name was not specified so using default_name=#{options[:pll_type]}".colorize("yellow")
   end

   unless File.exist? options[:ss_csv_path]
      @log.error "input csv does not exist. file=#{options[:ss_csv_path]}"
   end

   @log.info "Using input filename=#{options[:ss_csv_path]}".colorize("green")
    
   parse_modes_spreadsheet options

   @log.et_sys "cd $RTLROOT/ip/movellus/#{options[:pll_type].upcase}/modes/reg;make_pll_hal -v -d . -n #{options[:pll_type]} -o movellus_#{options[:pll_type].downcase}_modes_config.h"


rescue Interrupt => e
  @log.info "Interrupt detected (Ctrl-c): #{e}\nStack Trace Follows\n#{e.backtrace.join("\n")}"
  exit 1
#rescue Exception => e
#  @log.info "Exception detected : #{e}\nStack Trace Follows\n#{e.backtrace.join("\n")}"
# exit 1
rescue SystemExit => e
  exit e.status
ensure
  @log.close unless @log.nil?
end
