#!/eng/dvtools/release/ruby/2.4.2/bin/ruby

# Hack the GEM_PATH To Karls Libary
ENV['GEM_PATH']="/eng/dvtools/release/ruby/mygems"
Gem.clear_paths

require 'json'
require "awesome_print"
require 'optparse'

#
# Methods
#

def friendly_filename(filename)
    filename.gsub(/[^\w\s_-]+/, '')
            .gsub(/(^|\b\s)\s+($|\s?\b)/, '\\1\\2')
            .gsub(/\s+/, '_')
            .gsub(/\-/,'_')
end

def convert_acc_type(access_type)

  acc_string=""
  case access_type
    when "RW"
      acc_string="property read_access=true;\n      property write_access=true;"
    when "R"
      acc_string="property read_access=true;\n      property write_access=false;"
    when "W"
      acc_string="property read_access=true;\n      property write_access=false;"
    else
      puts "ERROR: no matching access type for #{access_type}"
      exit 1;
  end
  return acc_string
end

#
# Main
#

options = {}
OptionParser.new do |opts|
   opts.banner = "Usage: max_json_2_csr [options]"
   opts.on("-f filename", "--file filename", "name of file to convert") do |arg|
     options[:filename] = arg
   end
   opts.on("-r size_in_bits", "--reg_size size_in_bytes", "byte width of registers/alignment") do |arg|
     options[:reg_size] = arg
   end
   opts.on("-s size_in_bytes", "--property_size size_in_bytes", "size of this addressmap") do |arg|
     options[:property_size] = arg
   end
   opts.on("-o filename", "--output filename", "name of file to convert") do |arg|
     options[:out_filename] = arg
   end
end.parse!

unless options[:filename]
  puts "ERROR: -f filename is a required flag"
  exit
end

unless options[:out_filename]
  options[:out_filename]="#{ENV['RTLROOT']}/ip/hal/csr/#{File.basename(options[:filename],".*")}.csr"
end

unless options[:reg_size]
  options[:reg_size]=4
end

unless options[:property_size]
  options[:property_size]=4096
end

data = JSON.parse(File.read options[:filename])

reg_name=""
reg_fields=[]
reg_offset=0x0

FILE_HEADER  = <<-EOS
// Generated by max_json_2_csr.rb
//

addressmap {
  property word_size = #{options[:reg_size]} bytes;
  property alignment_mode = "compact";
  property addressmap_bus_protocol = "basic";
  property size = #{options[:property_size]};
EOS

f = File.new(options[:out_filename], File::CREAT|File::TRUNC|File::RDWR, 0644)
f.write FILE_HEADER


device = data['peripheral']
addr_map_name = device['displayName']
addr_map_base_addr=device['baseAddress']

puts "ip name=#{addr_map_name} found at baseAddress=#{addr_map_base_addr}"

addr_map = Hash.new

device['regfields'].each do |regfield|
  regfield.each do |stuff|
    reg_hash=stuff[1];
    offset=reg_hash['byteOffset'].to_i(16)
    if addr_map.has_key? offset
      addr_map[offset] << stuff[1]
    else
      addr_map[offset] = Array.new
      addr_map[offset] << stuff[1]
    end
  end
end

addr_map=Hash[addr_map.sort]

reg_names=Array.new
fields = Array.new

addr_map.each do |addr, register|
  fields_string=""
  reg_name=""
  reg_desc=""
  register.each do |field|
    field_lsb=field['bitOffset'].to_i
    field_msb=(field_lsb +field['bitWidth'].to_i)-1
    field_access=field['accessType']
    field_name = friendly_filename(field['name'])

    field.each do |key, val|
      unless fields.include? key
        fields << key
      end
    end



    volatile=nil
    if field.has_key? 'resetValue'
      volatile="property hardware_volatile;"
    end

    if field.has_key? 'group'
      reg_name=field['group']
      if field.has_key? 'groupDesc'
        reg_desc=field['groupDesc']
      end
    else
      if field_name =~ /(.*)(_\d+)/
        reg_name=$1 if reg_name==""
      else
        reg_name=field_name if reg_name==""
      end
    end

    field_access_type = convert_acc_type(field['accessType'])

    if (field_lsb > field_msb) # Swap the order if lsb > msb
      temp=field_lsb
      field_lsb=field_msb
      field_msb=temp
    end
    field_width=field_msb-field_lsb+1

    reset_value=nil
    if field.has_key? 'resetValue'
      reset_val=field['resetValue'].to_i
      if reset_val < 0  # FUTURE: hack for 2's complement. dont know if this is right
        reset_value="property reset_value=#{field_width}'b#{(field_width-1).downto(0).map { |n| reset_val[n] }.join};"
      else
        reset_value="property reset_value=#{field_width}'h#{reset_val.to_s(16)};"
      end
    end

    field_template = <<-EOS
    field {
      property title = "#{field_name}";
      property description = "#{field['description']}";
      property width = #{field_width};
      property output_port = true;
      #{field_access_type}
      #{reset_value}
      #{volatile}
    } [#{field_msb}:#{field_lsb}] #{field_name};
EOS
     if field_name != "reserved"
       fields_string += field_template
     end
  end

  # Check for dupe reg names since we are inferring regnames
  #
  if (reg_names.include? reg_name)
    i=0;
    done=false
    while !done do
      test_reg_name="#{reg_name}_#{i}"
      #puts "testing reg_name=#{test_reg_name} i=#{i}"
      unless  (reg_names.include? test_reg_name)
        reg_names << test_reg_name
        reg_name = test_reg_name
        done=true
      end
      i+=1
    end
  else
    reg_names << reg_name
  end

  csr_reg_template = <<-EOS
  register {
    property title = "#{reg_name}";
    property description = "#{reg_desc}";
#{fields_string}
  } [0x#{addr.to_s(16)}] #{friendly_filename(reg_name)};
EOS
     f.write csr_reg_template
end

f.write "} #{addr_map_name};"
f.close

puts "All Keys used:"
ap fields


