#!/bin/sh  -e
export MAX_PARALLEL_JOBS=4
export B4C_MAX_TIMEOUT=10800
export B4C_SLOTS=8
rm -rf $REPOROOT/test_run_dir/ioshire/builds
mkdir -p $REPOROOT/test_run_dir/ioshire/builds
srun -c 5 -p dv-gpd "cd $TESTRUN;b4c -na -i -m -ms -o -fc $*"
