#!/bin/sh  -e
export MAX_PARALLEL_JOBS=8
export B4C_MAX_TIMEOUT=10800
export B4C_SLOTS=10
rm -rf $REPOROOT/test_run_dir/ioshire/builds   # This is for ioshire
mkdir -p  $REPOROOT/test_run_dir/ioshire/builds
srun -c 8 -p dv-gpd "cd $TESTRUN;b4c -na -f -i -m -ms -o -fc -g -t -c -p -ps -uc -sc $*"
