#!/eng/dvtools/release/ruby/2.4.2/bin/ruby
# Hack the GEM_PATH To Karls Libary
ENV['GEM_PATH']="/eng/dvtools/release/ruby/mygems"
Gem.clear_paths

require 'optparse'
require 'fileutils'
require 'logger'
require 'awesome_print'
require 'tempfile'
require 'csv'
require_relative 'rblib/et_log'

#@@usage="usage: $0 {-h} {-v <verbose level>} {-s <grid number>}"

include ET_LOG

def setup_repo options

   # Is $REPOROOT defined and is it a valid writable path?
   if ENV.has_key? "REPOROOT"
     unless File.writable? ENV['REPOROOT']
       error "$REPOROOT points to non existant path #{ENV['REPO_ROOT']} or is not writable".colorize("red")
     end
   else
       error "Env var reporoot is not defined.  source env.sh in root of repo".colorize("red")
   end

   logpath="."
   options[:logpath] = logpath

   # Now that we are done cleaning etc, we can setup the proper log
   #'
   options[:prog_name]="update_sp_roms_4_burn"
   level=:info
   @log = EtLog.new("#{logpath}/#{options[:prog_name]}.log",:info,false,options[:prog_name])
   if options[:verbose]
    level=:debug
   end
   @log.level = level
   @log.info "#{options[:prog_name]} is running"
   @log.info "logpath is #{logpath}/#{options[:prog_name]}.log"
   options[:logfile] = "#{logpath}/#{options[:prog_name]}.log"

   @log.info "command line=#{options[:cmd_line]}"

   options[:git_hash],rc = @log.et_backtick "cd ${REPOROOT};git rev-parse HEAD"
   options[:git_hash].chomp!
   @log.info "git revision=#{options[:git_hash]}"

   options[:git_short_hash],rc = @log.et_backtick "cd ${REPOROOT};git rev-parse --short HEAD"
   options[:git_short_hash].chomp!
   @log.info "git short hash=#{options[:git_short_hash]}"

   @log.info "Querying git repo for local modifications..."
   diff,rc =@log.et_backtick "cd ${REPOROOT};git diff"
   if diff != ""
     diff_path="#{logpath}/local_modifications.patch"
     f = File.new(diff_path, File::CREAT|File::TRUNC|File::RDWR, 0644)
     f.write diff
     f.close
     @log.warn "There were local modifications so creating patch file #{diff_path}"
   else
     @log.info "Repo is clean there are no modifications"
   end
end

begin
   cmd_line="update_sp_roms_4_burn"
   ARGV.each { |arg| cmd_line += " #{arg}" }

   options = {}
   OptionParser.new do |opts|
     opts.banner = "Usage: update_sp_roms_4_burn [options]"
     opts.on("-q", "--quiet", "Quiesce most output") do |arg|
       options[:quiet] = arg
     end
     opts.on("-v", "--verbose", "Verbose output") do |arg|
       options[:verbose] = arg
     end
   end.parse!
   options[:cmd_line]=cmd_line

   unless options[:quiet]
     options[:quiet]=:info
   end

   #
   # Setup the workspace, cleanup, and get the log setup
   #
   setup_repo options
   @log.info "cmd_line=#{cmd_line}"

   require 'socket'
   hostname = Socket.gethostname
   @log.info "running on hostname=#{hostname}"

   file_list =  Dir["*.zhex"]
   file_list.each do |hex_file|
     @log.info "Processing file #{hex_file}"
     count=0
   Tempfile.open(".#{File.basename(hex_file)}", File.dirname(hex_file)) do |tempfile|
     File.open(hex_file).each do |line|

       tempfile.puts line.gsub(/@[0-9a-fA-F]+ /,'').upcase
       count+=1
     end
     while count < 4096 do
       tempfile.puts "000000"
       count+=1
     end
    tempfile.fdatasync
    tempfile.close
    stat = File.stat(hex_file)
    FileUtils.chown stat.uid, stat.gid, tempfile.path
    FileUtils.chmod stat.mode, tempfile.path
    FileUtils.mv tempfile.path, hex_file
  end
end

rescue Interrupt => e
  @log.info "Interrupt detected (Ctrl-c): #{e}\nStack Trace Follows\n#{e.backtrace.join("\n")}"
  exit 1
#rescue Exception => e
#  @log.info "Exception detected : #{e}\nStack Trace Follows\n#{e.backtrace.join("\n")}"
# exit 1
rescue SystemExit => e
  exit e.status
ensure
  @log.close unless @log.nil?
end
