// Copyright (c) 2026 Ainekko
// SPDX-License-Identifier: Apache-2.0


//////////////////////////////////////////////////////////////////////
// BEGIN autogenerated DECLARATIONS - do not edit manually   
// User Floating-Point CSRs
`CSR_DECLARATION_NON_SHARED_DEC_ONLY(fflags)
`CSR_DECLARATION_NON_SHARED_DEC_ONLY(frm)
`CSR_DECLARATION_NON_SHARED_WITH_TYPE(fcsr, csr_fcsr_t)
// misc esperanto
`CSR_DECLARATION_SHARED_DEC_ONLY(tensor_reduce)
`CSR_DECLARATION_SHARED_LATCH_WITH_TYPE(tensor_fma, tensorfma_control)
`CSR_DECLARATION_NON_SHARED_LATCH_WITH_TYPE(tensor_conv_size, tensorconv_size)
`CSR_DECLARATION_NON_SHARED_LATCH_WITH_TYPE(tensor_conv_ctrl, tensorconv_control)
`CSR_DECLARATION_SHARED_LATCH_WITH_TYPE(tensor_cooperation, tensorcoop_control)
`CSR_DECLARATION_NON_SHARED(tensor_mask, 16)
`CSR_DECLARATION_SHARED_LATCH_WITH_TYPE(tensor_quant, tensorquant_control)
`CSR_DECLARATION_NON_SHARED_DEC_ONLY(tensor_error)
`CSR_DECLARATION_SHARED_DEC_ONLY(ucache_control)
`CSR_DECLARATION_SHARED_DEC_ONLY(flb)
`CSR_DECLARATION_NON_SHARED_DEC_ONLY(fcc)
`CSR_DECLARATION_SHARED_DEC_ONLY(stall)
`CSR_DECLARATION_NON_SHARED_DEC_ONLY(tensor_wait)
`CSR_DECLARATION_SHARED_DEC_ONLY(tensor_load)
`CSR_DECLARATION_NON_SHARED(gsc_progress, 3)
`CSR_DECLARATION_SHARED_DEC_ONLY(tensor_store)
`ifdef ET_SIMULATION
`CSR_DECLARATION_NON_SHARED_LATCH(validation0, 64)
`endif
`ifdef ET_SIMULATION
`CSR_DECLARATION_NON_SHARED_LATCH(validation1, 64)
`endif
`ifdef ET_SIMULATION
`CSR_DECLARATION_NON_SHARED_LATCH(validation2, 64)
`endif
`ifdef ET_SIMULATION
`CSR_DECLARATION_NON_SHARED_LATCH(validation3, 64)
`endif
`ifdef NOT_VERIF_SIMULATION
`CSR_DECLARATION_NON_SHARED(validation0_ps, 1)
`endif
`ifdef NOT_VERIF_SIMULATION
`CSR_DECLARATION_NON_SHARED(validation1_ps, 1)
`endif
`ifdef NOT_VERIF_SIMULATION
`CSR_DECLARATION_NON_SHARED(validation2_ps, 1)
`endif
`ifdef NOT_VERIF_SIMULATION
`CSR_DECLARATION_NON_SHARED(validation3_ps, 1)
`endif
// Cache Ops
`CSR_DECLARATION_SHARED_DEC_ONLY(co_evict_va)
`CSR_DECLARATION_SHARED_DEC_ONLY(co_flush_va)
`CSR_DECLARATION_SHARED_DEC_ONLY(co_lock_va)
`CSR_DECLARATION_SHARED_DEC_ONLY(co_unlock_va)
`CSR_DECLARATION_SHARED_DEC_ONLY(co_prefetch_va)
// Supervisor Trap Setup
`CSR_DECLARATION_NON_SHARED_DEC_ONLY(sstatus)
`CSR_DECLARATION_NON_SHARED_DEC_ONLY(sie)
`CSR_DECLARATION_NON_SHARED_WITH_TYPE(stvec, csr_tvec_t)
`CSR_DECLARATION_NON_SHARED_LATCH(scounteren, `CSR_NR_COUNTERS)
// Supervisor Trap Handling
`CSR_DECLARATION_NON_SHARED_LATCH(sscratch, 64)
`CSR_DECLARATION_NON_SHARED_WITH_TYPE(sepc, csr_pc_t)
`CSR_DECLARATION_NON_SHARED_WITH_TYPE(scause, csr_cause_t)
`CSR_DECLARATION_NON_SHARED(stval, `VA_SIZE_EXT)
`CSR_DECLARATION_NON_SHARED_DEC_ONLY(sip)
// Supervisor Protection and Translation
`CSR_DECLARATION_SHARED_LATCH_WITH_TYPE(satp, csr_satp_t)
// Machine Trap Setup
`CSR_DECLARATION_NON_SHARED_WITH_TYPE(mstatus, csr_mstatus_t)
`CSR_DECLARATION_NON_SHARED_LATCH_WITH_TYPE(medeleg, csr_medeleg_t)
`CSR_DECLARATION_NON_SHARED_LATCH_WITH_TYPE(mideleg, csr_mideleg_t)
`CSR_DECLARATION_NON_SHARED_WITH_TYPE(mie, csr_mie_t)
`CSR_DECLARATION_NON_SHARED_WITH_TYPE(mtvec, csr_tvec_t)
`CSR_DECLARATION_NON_SHARED_LATCH(mcounteren, `CSR_NR_COUNTERS)
// Machine Trap Handling
`CSR_DECLARATION_NON_SHARED_LATCH(mscratch, 64)
`CSR_DECLARATION_NON_SHARED_WITH_TYPE(mepc, csr_pc_t)
`CSR_DECLARATION_NON_SHARED_WITH_TYPE(mcause, csr_cause_t)
`CSR_DECLARATION_NON_SHARED(mtval, `VA_SIZE_EXT)
`CSR_DECLARATION_NON_SHARED_WITH_TYPE(mip, csr_mip_t)
// Machine Counter/Timers
`CSR_DECLARATION_SHARED_DEC_ONLY(mcycle)
`CSR_DECLARATION_NON_SHARED_DEC_ONLY(minstret)
`CSR_DECLARATION_NON_SHARED_DEC_ONLY(mhpmcounter3)
`CSR_DECLARATION_NON_SHARED_DEC_ONLY(mhpmcounter4)
`CSR_DECLARATION_NON_SHARED_DEC_ONLY(mhpmcounter5)
`CSR_DECLARATION_NON_SHARED_DEC_ONLY(mhpmcounter6)
`CSR_DECLARATION_NON_SHARED_DEC_ONLY(mhpmcounter7)
`CSR_DECLARATION_NON_SHARED_DEC_ONLY(mhpmcounter8)
// Machine counter setup
`CSR_DECLARATION_NON_SHARED_LATCH(mhpmevent3, `CSR_NR_EVENTS_L)
`CSR_DECLARATION_NON_SHARED_LATCH(mhpmevent4, `CSR_NR_EVENTS_L)
`CSR_DECLARATION_NON_SHARED_LATCH(mhpmevent5, `CSR_NR_EVENTS_L)
`CSR_DECLARATION_NON_SHARED_LATCH(mhpmevent6, `CSR_NR_EVENTS_L)
`CSR_DECLARATION_NON_SHARED(mhpmevent7, `CSR_NR_EVENTS_L)
`CSR_DECLARATION_NON_SHARED(mhpmevent8, `CSR_NR_EVENTS_L)
// Debug/Trace Registers (shared with Debug Mode)
`CSR_DECLARATION_NON_SHARED_WITH_TYPE(tdata1, csr_tdata1_t)
`CSR_DECLARATION_NON_SHARED_LATCH(tdata2, `VA_SIZE)
// Debug Mode Registers
`CSR_DECLARATION_NON_SHARED_WITH_TYPE(dcsr, csr_dcsr_t)
`CSR_DECLARATION_NON_SHARED_WITH_TYPE(dpc, csr_pc_t)
`CSR_DECLARATION_NON_SHARED_DEC_ONLY(ddata0)
// custom esperanto machine csrs
`CSR_DECLARATION_SHARED_LATCH_WITH_TYPE(matp, csr_matp_t)
`CSR_DECLARATION_NON_SHARED_LATCH_WITH_TYPE(minstmask, minst_mask_t)
`CSR_DECLARATION_NON_SHARED_LATCH(minstmatch, 32)
`CSR_DECLARATION_SHARED_DEC_ONLY(cacheInvalidate)
`CSR_DECLARATION_SHARED_LATCH_WITH_TYPE(menable_shadows, menable_shadows_t)
`CSR_DECLARATION_SHARED_LATCH(excl_mode, 1)
`CSR_DECLARATION_NON_SHARED(mbusaddr, `PA_SIZE)
`ifdef DCACHE_REPORT_PC
`CSR_DECLARATION_NON_SHARED(mbuspc, `PC_SIZE_EXT)
`endif
// Custom Esperanto Cache Ops m-mode csr
`CSR_DECLARATION_SHARED_DEC_ONLY(mcache_control)
`CSR_DECLARATION_SHARED_DEC_ONLY(co_evict_sw)
`CSR_DECLARATION_SHARED_DEC_ONLY(co_flush_sw)
`CSR_DECLARATION_SHARED_DEC_ONLY(co_lock_sw)
`CSR_DECLARATION_SHARED_DEC_ONLY(co_unlock_sw)
`CSR_LATCH_RESET_DECLARATION(reset_w)

// END autogenerated DECLARATIONS
//////////////////////////////////////////////////////////////////////


function automatic void csr_read_and_decode_comb_default;
   begin
      //////////////////////////////////////////////////////////////////////
      // BEGIN autogenerated READ_AND_DECODE_COMB_DEFAULT - do not edit
      // User Floating-Point CSRs
      `CSR_DECODE_DEFAULT_NON_SHARED(fflags)
      `CSR_DECODE_DEFAULT_NON_SHARED(frm)
      `CSR_DECODE_DEFAULT_NON_SHARED(fcsr)
      // misc esperanto
      `CSR_DECODE_DEFAULT_SHARED(tensor_reduce)
      `CSR_DECODE_DEFAULT_SHARED(tensor_fma)
      `CSR_DECODE_DEFAULT_NON_SHARED(tensor_conv_size)
      `CSR_DECODE_DEFAULT_NON_SHARED(tensor_conv_ctrl)
      `CSR_DECODE_DEFAULT_SHARED(tensor_cooperation)
      `CSR_DECODE_DEFAULT_NON_SHARED(tensor_mask)
      `CSR_DECODE_DEFAULT_SHARED(tensor_quant)
      `CSR_DECODE_DEFAULT_NON_SHARED(tensor_error)
      `CSR_DECODE_DEFAULT_SHARED(ucache_control)
      `CSR_DECODE_DEFAULT_SHARED(flb)
      `CSR_DECODE_DEFAULT_NON_SHARED(fcc)
      `CSR_DECODE_DEFAULT_SHARED(stall)
      `CSR_DECODE_DEFAULT_NON_SHARED(tensor_wait)
      `CSR_DECODE_DEFAULT_SHARED(tensor_load)
      `CSR_DECODE_DEFAULT_NON_SHARED(gsc_progress)
      `CSR_DECODE_DEFAULT_SHARED(tensor_store)
      `ifdef ET_SIMULATION
      `CSR_DECODE_DEFAULT_NON_SHARED(validation0)
      `endif
      `ifdef ET_SIMULATION
      `CSR_DECODE_DEFAULT_NON_SHARED(validation1)
      `endif
      `ifdef ET_SIMULATION
      `CSR_DECODE_DEFAULT_NON_SHARED(validation2)
      `endif
      `ifdef ET_SIMULATION
      `CSR_DECODE_DEFAULT_NON_SHARED(validation3)
      `endif
      `ifdef NOT_VERIF_SIMULATION
      `CSR_DECODE_DEFAULT_NON_SHARED(validation0_ps)
      `endif
      `ifdef NOT_VERIF_SIMULATION
      `CSR_DECODE_DEFAULT_NON_SHARED(validation1_ps)
      `endif
      `ifdef NOT_VERIF_SIMULATION
      `CSR_DECODE_DEFAULT_NON_SHARED(validation2_ps)
      `endif
      `ifdef NOT_VERIF_SIMULATION
      `CSR_DECODE_DEFAULT_NON_SHARED(validation3_ps)
      `endif
      // Cache Ops
      `CSR_DECODE_DEFAULT_SHARED(co_evict_va)
      `CSR_DECODE_DEFAULT_SHARED(co_flush_va)
      `CSR_DECODE_DEFAULT_SHARED(co_lock_va)
      `CSR_DECODE_DEFAULT_SHARED(co_unlock_va)
      `CSR_DECODE_DEFAULT_SHARED(co_prefetch_va)
      // Supervisor Trap Setup
      `CSR_DECODE_DEFAULT_NON_SHARED(sstatus)
      `CSR_DECODE_DEFAULT_NON_SHARED(sie)
      `CSR_DECODE_DEFAULT_NON_SHARED(stvec)
      `CSR_DECODE_DEFAULT_NON_SHARED(scounteren)
      // Supervisor Trap Handling
      `CSR_DECODE_DEFAULT_NON_SHARED(sscratch)
      `CSR_DECODE_DEFAULT_NON_SHARED(sepc)
      `CSR_DECODE_DEFAULT_NON_SHARED(scause)
      `CSR_DECODE_DEFAULT_NON_SHARED(stval)
      `CSR_DECODE_DEFAULT_NON_SHARED(sip)
      // Supervisor Protection and Translation
      `CSR_DECODE_DEFAULT_SHARED(satp)
      // Machine Trap Setup
      `CSR_DECODE_DEFAULT_NON_SHARED(mstatus)
      `CSR_DECODE_DEFAULT_NON_SHARED(medeleg)
      `CSR_DECODE_DEFAULT_NON_SHARED(mideleg)
      `CSR_DECODE_DEFAULT_NON_SHARED(mie)
      `CSR_DECODE_DEFAULT_NON_SHARED(mtvec)
      `CSR_DECODE_DEFAULT_NON_SHARED(mcounteren)
      // Machine Trap Handling
      `CSR_DECODE_DEFAULT_NON_SHARED(mscratch)
      `CSR_DECODE_DEFAULT_NON_SHARED(mepc)
      `CSR_DECODE_DEFAULT_NON_SHARED(mcause)
      `CSR_DECODE_DEFAULT_NON_SHARED(mtval)
      `CSR_DECODE_DEFAULT_NON_SHARED(mip)
      // Machine Counter/Timers
      `CSR_DECODE_DEFAULT_SHARED(mcycle)
      `CSR_DECODE_DEFAULT_NON_SHARED(minstret)
      `CSR_DECODE_DEFAULT_NON_SHARED(mhpmcounter3)
      `CSR_DECODE_DEFAULT_NON_SHARED(mhpmcounter4)
      `CSR_DECODE_DEFAULT_NON_SHARED(mhpmcounter5)
      `CSR_DECODE_DEFAULT_NON_SHARED(mhpmcounter6)
      `CSR_DECODE_DEFAULT_NON_SHARED(mhpmcounter7)
      `CSR_DECODE_DEFAULT_NON_SHARED(mhpmcounter8)
      // Machine counter setup
      `CSR_DECODE_DEFAULT_NON_SHARED(mhpmevent3)
      `CSR_DECODE_DEFAULT_NON_SHARED(mhpmevent4)
      `CSR_DECODE_DEFAULT_NON_SHARED(mhpmevent5)
      `CSR_DECODE_DEFAULT_NON_SHARED(mhpmevent6)
      `CSR_DECODE_DEFAULT_NON_SHARED(mhpmevent7)
      `CSR_DECODE_DEFAULT_NON_SHARED(mhpmevent8)
      // Debug/Trace Registers (shared with Debug Mode)
      `CSR_DECODE_DEFAULT_NON_SHARED(tdata1)
      `CSR_DECODE_DEFAULT_NON_SHARED(tdata2)
      // Debug Mode Registers
      `CSR_DECODE_DEFAULT_NON_SHARED(dcsr)
      `CSR_DECODE_DEFAULT_NON_SHARED(dpc)
      `CSR_DECODE_DEFAULT_NON_SHARED(ddata0)
      // custom esperanto machine csrs
      `CSR_DECODE_DEFAULT_SHARED(matp)
      `CSR_DECODE_DEFAULT_NON_SHARED(minstmask)
      `CSR_DECODE_DEFAULT_NON_SHARED(minstmatch)
      `CSR_DECODE_DEFAULT_SHARED(cacheInvalidate)
      `CSR_DECODE_DEFAULT_SHARED(menable_shadows)
      `CSR_DECODE_DEFAULT_SHARED(excl_mode)
      `CSR_DECODE_DEFAULT_NON_SHARED(mbusaddr)
      `ifdef DCACHE_REPORT_PC
      `CSR_DECODE_DEFAULT_NON_SHARED(mbuspc)
      `endif
      // Custom Esperanto Cache Ops m-mode csr
      `CSR_DECODE_DEFAULT_SHARED(mcache_control)
      `CSR_DECODE_DEFAULT_SHARED(co_evict_sw)
      `CSR_DECODE_DEFAULT_SHARED(co_flush_sw)
      `CSR_DECODE_DEFAULT_SHARED(co_lock_sw)
      `CSR_DECODE_DEFAULT_SHARED(co_unlock_sw)
      // END autogenerated READ_AND_DECODE_COMB_DEFAULT - do not edit
      //////////////////////////////////////////////////////////////////////
   end
endfunction


//function automatic void csr_read_and_decode_comb_cases //( input mem_wen, input mem_thread_id, input io_rw_mem_valid_qual, input [`CSR_REG_NR_SZ-1:0] io_rw_mem_addr);
//   begin
`define csr_read_and_decode_comb_cases  \
      if(io_rw_mem_valid_qual) begin \
         case (csr_ad_t'(io_rw_mem_addr)) \
           ////////////////////////////////////////////////////////////////////// \
           // BEGIN autogenerated READ_AND_DECODE_COMB_CASES - do not edit \
            // User Floating-Point CSRs \
            `CSR_DECODE_CASE_NON_SHARED(csr_ad_FFLAGS, fflags, read_fflags) \
            `CSR_DECODE_CASE_NON_SHARED_SHADOW(csr_ad_FRM, frm, read_fcsr, read_fcsr_as_frm) \
            `CSR_DECODE_CASE_NON_SHARED(csr_ad_FCSR, fcsr, read_fcsr) \
            // User Counter/Timers \
            `CSR_DECODE_CASE_RO_SHARED(csr_ad_CYCLE, reg_mcycle) \
            `CSR_DECODE_CASE_RO_NON_SHARED(csr_ad_INSTRET, reg_minstret) \
            `CSR_DECODE_CASE_RO_NON_SHARED(csr_ad_HPMCOUNTER3, reg_mhpmcounter3) \
            `CSR_DECODE_CASE_RO_NON_SHARED(csr_ad_HPMCOUNTER4, reg_mhpmcounter4) \
            `CSR_DECODE_CASE_RO_NON_SHARED(csr_ad_HPMCOUNTER5, reg_mhpmcounter5) \
            `CSR_DECODE_CASE_RO_NON_SHARED(csr_ad_HPMCOUNTER6, reg_mhpmcounter6) \
            `CSR_DECODE_CASE_RO_NON_SHARED(csr_ad_HPMCOUNTER7, reg_mhpmcounter7) \
            `CSR_DECODE_CASE_RO_NON_SHARED(csr_ad_HPMCOUNTER8, reg_mhpmcounter8) \
            // misc esperanto \
            `CSR_DECODE_CASE_SHARED_RD_CONSTANT_WITH_TRAP(csr_ad_TENSOR_REDUCE, tensor_reduce, 64'h0, trap_on_ml_or_thread1) \
            `CSR_DECODE_CASE_SHARED_RD_CONSTANT_WITH_TRAP(csr_ad_TENSOR_FMA, tensor_fma, 64'h0, trap_on_ml_or_thread1) \
            `CSR_DECODE_CASE_NON_SHARED_RD_CONSTANT_WITH_TRAP(csr_ad_TENSOR_CONV_SIZE, tensor_conv_size, 64'h0, esr_features.trap_on_ml) \
            `CSR_DECODE_CASE_NON_SHARED_RD_CONSTANT_WITH_TRAP(csr_ad_TENSOR_CONV_CTRL, tensor_conv_ctrl, 64'h0, esr_features.trap_on_ml) \
            `CSR_DECODE_CASE_SHARED_RD_CONSTANT_WITH_TRAP(csr_ad_TENSOR_COOPERATION, tensor_cooperation, 64'h0, trap_on_ml_or_thread1) \
            `CSR_DECODE_CASE_NON_SHARED_WITH_TRAP(csr_ad_TENSOR_MASK, tensor_mask, reg_tensor_mask, esr_features.trap_on_ml) \
            `CSR_DECODE_CASE_SHARED_RD_CONSTANT_WITH_TRAP(csr_ad_TENSOR_QUANT, tensor_quant, 64'h0, trap_on_ml_or_thread1) \
            `CSR_DECODE_CASE_NON_SHARED(csr_ad_TENSOR_ERROR, tensor_error, reg_tensor_error) \
            `CSR_DECODE_CASE_SHARED_WITH_TRAP(csr_ad_UCACHE_CONTROL, ucache_control, reg_ucache_control, esr_features.trap_on_u_scp) \
            `CSR_DECODE_CASE_SHARED_RD_CONSTANT_WITH_TRAP(csr_ad_FLB, flb, 64'h0, esr_features.trap_on_ml) \
            `CSR_DECODE_CASE_NON_SHARED_RD_CONSTANT_WITH_TRAP(csr_ad_FCC, fcc, 64'h0, esr_features.trap_on_ml) \
            `CSR_DECODE_CASE_SHARED_RD_CONSTANT_WITH_TRAP(csr_ad_STALL, stall, 64'h0, esr_features.trap_on_ml) \
            `CSR_DECODE_CASE_NON_SHARED_RD_CONSTANT(csr_ad_TENSOR_WAIT, tensor_wait, 64'h0) \
            `CSR_DECODE_CASE_SHARED_RD_CONSTANT_WITH_TRAP(csr_ad_TENSOR_LOAD, tensor_load, 64'h0, trap_on_ml_or_thread1) \
            `CSR_DECODE_CASE_NON_SHARED(csr_ad_GSC_PROGRESS, gsc_progress, reg_gsc_progress) \
            `CSR_DECODE_CASE_SHARED_RD_CONSTANT_WITH_TRAP(csr_ad_TENSOR_STORE, tensor_store, 64'h0, trap_on_ml_or_thread1) \
            `ifdef ET_SIMULATION \
            `CSR_DECODE_CASE_NON_SHARED(csr_ad_VALIDATION0, validation0, reg_validation0) \
            `endif \
            `ifdef ET_SIMULATION \
            `CSR_DECODE_CASE_NON_SHARED(csr_ad_VALIDATION1, validation1, reg_validation1) \
            `endif \
            `ifdef ET_SIMULATION \
            `CSR_DECODE_CASE_NON_SHARED(csr_ad_VALIDATION2, validation2, reg_validation2) \
            `endif \
            `ifdef ET_SIMULATION \
            `CSR_DECODE_CASE_NON_SHARED(csr_ad_VALIDATION3, validation3, reg_validation3) \
            `endif \
            `ifdef NOT_VERIF_SIMULATION \
            `CSR_DECODE_CASE_NON_SHARED_RD_CONSTANT(csr_ad_VALIDATION0_PS, validation0_ps, 64'h0) \
            `endif \
            `ifdef NOT_VERIF_SIMULATION \
            `CSR_DECODE_CASE_NON_SHARED_RD_CONSTANT(csr_ad_VALIDATION1_PS, validation1_ps, 64'h0) \
            `endif \
            `ifdef NOT_VERIF_SIMULATION \
            `CSR_DECODE_CASE_NON_SHARED_RD_CONSTANT(csr_ad_VALIDATION2_PS, validation2_ps, 64'h0) \
            `endif \
            `ifdef NOT_VERIF_SIMULATION \
            `CSR_DECODE_CASE_NON_SHARED_RD_CONSTANT(csr_ad_VALIDATION3_PS, validation3_ps, 64'h0) \
            `endif \
            `CSR_DECODE_CASE_RO_SHARED(csr_ad_HARTID, read_hartid) \
            `CSR_DECODE_CASE_RO_NON_SHARED_WITH_TRAP(csr_ad_NB_FCC, read_nb_fcc, esr_features.trap_on_ml) \
            // Cache Ops \
            `CSR_DECODE_CASE_SHARED_RD_CONSTANT_WITH_TRAP(csr_ad_CO_EVICT_VA, co_evict_va, 64'h0, esr_features.trap_on_u_cacheops) \
            `CSR_DECODE_CASE_SHARED_RD_CONSTANT_WITH_TRAP(csr_ad_CO_FLUSH_VA, co_flush_va, 64'h0, esr_features.trap_on_u_cacheops) \
            `CSR_DECODE_CASE_SHARED_RD_CONSTANT_WITH_TRAP(csr_ad_CO_LOCK_VA, co_lock_va, 64'h0, esr_features.trap_on_u_cacheops) \
            `CSR_DECODE_CASE_SHARED_RD_CONSTANT_WITH_TRAP(csr_ad_CO_UNLOCK_VA, co_unlock_va, 64'h0, esr_features.trap_on_u_cacheops) \
            `CSR_DECODE_CASE_SHARED_RD_CONSTANT_WITH_TRAP(csr_ad_CO_PREFETCH_VA, co_prefetch_va, 64'h0, esr_features.trap_on_u_cacheops) \
            // Supervisor Trap Setup \
            `CSR_DECODE_CASE_NON_SHARED(csr_ad_SSTATUS, sstatus, read_sstatus) \
            `CSR_DECODE_CASE_NON_SHARED(csr_ad_SIE, sie, read_sie) \
            `CSR_DECODE_CASE_NON_SHARED_SX(csr_ad_STVEC, stvec, reg_stvec) \
            `CSR_DECODE_CASE_NON_SHARED(csr_ad_SCOUNTEREN, scounteren, reg_scounteren) \
            // Supervisor Trap Handling \
            `CSR_DECODE_CASE_NON_SHARED(csr_ad_SSCRATCH, sscratch, reg_sscratch) \
            `CSR_DECODE_CASE_NON_SHARED_SX(csr_ad_SEPC, sepc, reg_sepc) \
            `CSR_DECODE_CASE_NON_SHARED(csr_ad_SCAUSE, scause, reg_scause) \
            `CSR_DECODE_CASE_NON_SHARED_SX(csr_ad_STVAL, stval, reg_stval) \
            `CSR_DECODE_CASE_NON_SHARED(csr_ad_SIP, sip, read_sip) \
            // Supervisor Protection and Translation \
            `CSR_DECODE_CASE_SHARED_WITH_TRAP(csr_ad_SATP, satp, reg_satp, mem_trap_virtual_memory) \
            // Machine Information Registers \
            `CSR_DECODE_CASE_RO_SHARED(csr_ad_MVENDORID, `CSR_VENDOR_ID) \
            `CSR_DECODE_CASE_RO_SHARED(csr_ad_MARCHID, `CSR_ARCH_ID) \
            `CSR_DECODE_CASE_RO_SHARED(csr_ad_MIMPID, `CSR_IMP_ID) \
            `CSR_DECODE_CASE_RO_SHARED(csr_ad_MHARTID, read_hartid) \
            // Machine Trap Setup \
            `CSR_DECODE_CASE_NON_SHARED(csr_ad_MSTATUS, mstatus, read_mstatus) \
            `CSR_DECODE_CASE_RO_SHARED(csr_ad_MISA, `CSR_ISA_MAX) \
            `CSR_DECODE_CASE_NON_SHARED(csr_ad_MEDELEG, medeleg, reg_medeleg) \
            `CSR_DECODE_CASE_NON_SHARED(csr_ad_MIDELEG, mideleg, reg_mideleg) \
            `CSR_DECODE_CASE_NON_SHARED(csr_ad_MIE, mie, reg_mie) \
            `CSR_DECODE_CASE_NON_SHARED_SX(csr_ad_MTVEC, mtvec, reg_mtvec) \
            `CSR_DECODE_CASE_NON_SHARED(csr_ad_MCOUNTEREN, mcounteren, reg_mcounteren) \
            // Machine Trap Handling \
            `CSR_DECODE_CASE_NON_SHARED(csr_ad_MSCRATCH, mscratch, reg_mscratch) \
            `CSR_DECODE_CASE_NON_SHARED_SX(csr_ad_MEPC, mepc, reg_mepc) \
            `CSR_DECODE_CASE_NON_SHARED(csr_ad_MCAUSE, mcause, reg_mcause) \
            `CSR_DECODE_CASE_NON_SHARED_SX(csr_ad_MTVAL, mtval, reg_mtval) \
            `CSR_DECODE_CASE_NON_SHARED(csr_ad_MIP, mip, read_mip) \
            // Machine Counter/Timers \
            `CSR_DECODE_CASE_SHARED(csr_ad_MCYCLE, mcycle, reg_mcycle) \
            `CSR_DECODE_CASE_NON_SHARED(csr_ad_MINSTRET, minstret, reg_minstret) \
            `CSR_DECODE_CASE_NON_SHARED(csr_ad_MHPMCOUNTER3, mhpmcounter3, reg_mhpmcounter3) \
            `CSR_DECODE_CASE_NON_SHARED(csr_ad_MHPMCOUNTER4, mhpmcounter4, reg_mhpmcounter4) \
            `CSR_DECODE_CASE_NON_SHARED(csr_ad_MHPMCOUNTER5, mhpmcounter5, reg_mhpmcounter5) \
            `CSR_DECODE_CASE_NON_SHARED(csr_ad_MHPMCOUNTER6, mhpmcounter6, reg_mhpmcounter6) \
            `CSR_DECODE_CASE_NON_SHARED(csr_ad_MHPMCOUNTER7, mhpmcounter7, reg_mhpmcounter7) \
            `CSR_DECODE_CASE_NON_SHARED(csr_ad_MHPMCOUNTER8, mhpmcounter8, reg_mhpmcounter8) \
            // Machine counter setup \
            `CSR_DECODE_CASE_NON_SHARED(csr_ad_MHPMEVENT3, mhpmevent3, reg_mhpmevent3) \
            `CSR_DECODE_CASE_NON_SHARED(csr_ad_MHPMEVENT4, mhpmevent4, reg_mhpmevent4) \
            `CSR_DECODE_CASE_NON_SHARED(csr_ad_MHPMEVENT5, mhpmevent5, reg_mhpmevent5) \
            `CSR_DECODE_CASE_NON_SHARED(csr_ad_MHPMEVENT6, mhpmevent6, reg_mhpmevent6) \
            `CSR_DECODE_CASE_NON_SHARED(csr_ad_MHPMEVENT7, mhpmevent7, reg_mhpmevent7) \
            `CSR_DECODE_CASE_NON_SHARED(csr_ad_MHPMEVENT8, mhpmevent8, reg_mhpmevent8) \
            // Debug/Trace Registers (shared with Debug Mode) \
            `CSR_DECODE_CASE_RO_SHARED(csr_ad_TSELECT, 64'h0) \
            `CSR_DECODE_CASE_NON_SHARED(csr_ad_TDATA1, tdata1, read_tdata1) \
            `CSR_DECODE_CASE_NON_SHARED(csr_ad_TDATA2, tdata2, reg_tdata2) \
            `CSR_DECODE_CASE_RO_SHARED(csr_ad_TDATA3, 64'h0) \
            // Debug Mode Registers \
            `CSR_DECODE_CASE_NON_SHARED(csr_ad_DCSR, dcsr, reg_dcsr) \
            `CSR_DECODE_CASE_NON_SHARED_SX(csr_ad_DPC, dpc, reg_dpc) \
            `CSR_DECODE_CASE_NON_SHARED(csr_ad_DDATA0, ddata0, read_ddata0) \
            // custom esperanto machine csrs \
            `CSR_DECODE_CASE_SHARED(csr_ad_MATP, matp, reg_matp) \
            `CSR_DECODE_CASE_NON_SHARED(csr_ad_MINSTMASK, minstmask, reg_minstmask) \
            `CSR_DECODE_CASE_NON_SHARED(csr_ad_MINSTMATCH, minstmatch, reg_minstmatch) \
            `CSR_DECODE_CASE_SHARED_RD_CONSTANT(csr_ad_CACHEINVALIDATE, cacheInvalidate, 64'h0) \
            `CSR_DECODE_CASE_SHARED(csr_ad_MENABLE_SHADOWS, menable_shadows, reg_menable_shadows) \
            `CSR_DECODE_CASE_SHARED(csr_ad_EXCL_MODE, excl_mode, reg_excl_mode) \
            `CSR_DECODE_CASE_NON_SHARED(csr_ad_MBUSADDR, mbusaddr, reg_mbusaddr) \
            `ifdef DCACHE_REPORT_PC \
            `CSR_DECODE_CASE_NON_SHARED(csr_ad_MBUSPC, mbuspc, reg_mbuspc) \
            `endif \
            // Custom Esperanto Cache Ops m-mode csr \
            `CSR_DECODE_CASE_SHARED(csr_ad_MCACHE_CONTROL, mcache_control, reg_mcache_control) \
            `CSR_DECODE_CASE_SHARED_RD_CONSTANT(csr_ad_CO_EVICT_SW, co_evict_sw, 64'h0) \
            `CSR_DECODE_CASE_SHARED_RD_CONSTANT(csr_ad_CO_FLUSH_SW, co_flush_sw, 64'h0) \
            `CSR_DECODE_CASE_SHARED_RD_CONSTANT(csr_ad_CO_LOCK_SW, co_lock_sw, 64'h0) \
            `CSR_DECODE_CASE_SHARED_RD_CONSTANT(csr_ad_CO_UNLOCK_SW, co_unlock_sw, 64'h0) \
            // Custom Esperanto Debug m-mode csr \
            `CSR_DECODE_CASE_RO_SHARED(csr_ad_DCACHE_DEBUG, dcache_debug_signals) \
            // machine not implemented/hardwired \
            `CSR_DECODE_CASE_RO_SHARED(csr_ad_MHPMCOUNTER9, 64'h0) \
            `CSR_DECODE_CASE_RO_SHARED(csr_ad_MHPMCOUNTER10, 64'h0) \
            `CSR_DECODE_CASE_RO_SHARED(csr_ad_MHPMCOUNTER11, 64'h0) \
            `CSR_DECODE_CASE_RO_SHARED(csr_ad_MHPMCOUNTER12, 64'h0) \
            `CSR_DECODE_CASE_RO_SHARED(csr_ad_MHPMCOUNTER13, 64'h0) \
            `CSR_DECODE_CASE_RO_SHARED(csr_ad_MHPMCOUNTER14, 64'h0) \
            `CSR_DECODE_CASE_RO_SHARED(csr_ad_MHPMCOUNTER15, 64'h0) \
            `CSR_DECODE_CASE_RO_SHARED(csr_ad_MHPMCOUNTER16, 64'h0) \
            `CSR_DECODE_CASE_RO_SHARED(csr_ad_MHPMCOUNTER17, 64'h0) \
            `CSR_DECODE_CASE_RO_SHARED(csr_ad_MHPMCOUNTER18, 64'h0) \
            `CSR_DECODE_CASE_RO_SHARED(csr_ad_MHPMCOUNTER19, 64'h0) \
            `CSR_DECODE_CASE_RO_SHARED(csr_ad_MHPMCOUNTER20, 64'h0) \
            `CSR_DECODE_CASE_RO_SHARED(csr_ad_MHPMCOUNTER21, 64'h0) \
            `CSR_DECODE_CASE_RO_SHARED(csr_ad_MHPMCOUNTER22, 64'h0) \
            `CSR_DECODE_CASE_RO_SHARED(csr_ad_MHPMCOUNTER23, 64'h0) \
            `CSR_DECODE_CASE_RO_SHARED(csr_ad_MHPMCOUNTER24, 64'h0) \
            `CSR_DECODE_CASE_RO_SHARED(csr_ad_MHPMCOUNTER25, 64'h0) \
            `CSR_DECODE_CASE_RO_SHARED(csr_ad_MHPMCOUNTER26, 64'h0) \
            `CSR_DECODE_CASE_RO_SHARED(csr_ad_MHPMCOUNTER27, 64'h0) \
            `CSR_DECODE_CASE_RO_SHARED(csr_ad_MHPMCOUNTER28, 64'h0) \
            `CSR_DECODE_CASE_RO_SHARED(csr_ad_MHPMCOUNTER29, 64'h0) \
            `CSR_DECODE_CASE_RO_SHARED(csr_ad_MHPMCOUNTER30, 64'h0) \
            `CSR_DECODE_CASE_RO_SHARED(csr_ad_MHPMCOUNTER31, 64'h0) \
            `CSR_DECODE_CASE_RO_SHARED(csr_ad_MHPMEVENT9, 64'h0) \
            `CSR_DECODE_CASE_RO_SHARED(csr_ad_MHPMEVENT10, 64'h0) \
            `CSR_DECODE_CASE_RO_SHARED(csr_ad_MHPMEVENT11, 64'h0) \
            `CSR_DECODE_CASE_RO_SHARED(csr_ad_MHPMEVENT12, 64'h0) \
            `CSR_DECODE_CASE_RO_SHARED(csr_ad_MHPMEVENT13, 64'h0) \
            `CSR_DECODE_CASE_RO_SHARED(csr_ad_MHPMEVENT14, 64'h0) \
            `CSR_DECODE_CASE_RO_SHARED(csr_ad_MHPMEVENT15, 64'h0) \
            `CSR_DECODE_CASE_RO_SHARED(csr_ad_MHPMEVENT16, 64'h0) \
            `CSR_DECODE_CASE_RO_SHARED(csr_ad_MHPMEVENT17, 64'h0) \
            `CSR_DECODE_CASE_RO_SHARED(csr_ad_MHPMEVENT18, 64'h0) \
            `CSR_DECODE_CASE_RO_SHARED(csr_ad_MHPMEVENT19, 64'h0) \
            `CSR_DECODE_CASE_RO_SHARED(csr_ad_MHPMEVENT20, 64'h0) \
            `CSR_DECODE_CASE_RO_SHARED(csr_ad_MHPMEVENT21, 64'h0) \
            `CSR_DECODE_CASE_RO_SHARED(csr_ad_MHPMEVENT22, 64'h0) \
            `CSR_DECODE_CASE_RO_SHARED(csr_ad_MHPMEVENT23, 64'h0) \
            `CSR_DECODE_CASE_RO_SHARED(csr_ad_MHPMEVENT24, 64'h0) \
            `CSR_DECODE_CASE_RO_SHARED(csr_ad_MHPMEVENT25, 64'h0) \
            `CSR_DECODE_CASE_RO_SHARED(csr_ad_MHPMEVENT26, 64'h0) \
            `CSR_DECODE_CASE_RO_SHARED(csr_ad_MHPMEVENT27, 64'h0) \
            `CSR_DECODE_CASE_RO_SHARED(csr_ad_MHPMEVENT28, 64'h0) \
            `CSR_DECODE_CASE_RO_SHARED(csr_ad_MHPMEVENT29, 64'h0) \
            `CSR_DECODE_CASE_RO_SHARED(csr_ad_MHPMEVENT30, 64'h0) \
            `CSR_DECODE_CASE_RO_SHARED(csr_ad_MHPMEVENT31, 64'h0) \
           // END autogenerated READ_AND_DECODE_COMB_CASES - do not edit \
           ////////////////////////////////////////////////////////////////////// \
           default: \
             mem_addr_valid = 1'b0; \
            \
         endcase // case (io_rw_mem_addr) \
      end // if (io_rw_mem_valid_qual) \
//   end \
//endfunction

   
//////////////////////////////////////////////////////////////////////
// BEGIN autogenerated READ_AND_DECODE_SEQ - do not edit
// User Floating-Point CSRs
`CSR_DECODE_SEQ_NON_SHARED(fflags)
`CSR_DECODE_SEQ_NON_SHARED(frm)
`CSR_DECODE_SEQ_NON_SHARED(fcsr)
// misc esperanto
`CSR_DECODE_SEQ_SHARED(tensor_reduce)
`CSR_DECODE_SEQ_SHARED(tensor_fma)
`CSR_DECODE_SEQ_NON_SHARED(tensor_conv_size)
`CSR_DECODE_SEQ_NON_SHARED(tensor_conv_ctrl)
`CSR_DECODE_SEQ_SHARED(tensor_cooperation)
`CSR_DECODE_SEQ_NON_SHARED(tensor_mask)
`CSR_DECODE_SEQ_SHARED(tensor_quant)
`CSR_DECODE_SEQ_NON_SHARED(tensor_error)
`CSR_DECODE_SEQ_SHARED(ucache_control)
`CSR_DECODE_SEQ_SHARED(flb)
`CSR_DECODE_SEQ_NON_SHARED(fcc)
`CSR_DECODE_SEQ_SHARED(stall)
`CSR_DECODE_SEQ_NON_SHARED(tensor_wait)
`CSR_DECODE_SEQ_SHARED(tensor_load)
`CSR_DECODE_SEQ_NON_SHARED(gsc_progress)
`CSR_DECODE_SEQ_SHARED(tensor_store)
`ifdef ET_SIMULATION
`CSR_DECODE_SEQ_NON_SHARED(validation0)
`endif
`ifdef ET_SIMULATION
`CSR_DECODE_SEQ_NON_SHARED(validation1)
`endif
`ifdef ET_SIMULATION
`CSR_DECODE_SEQ_NON_SHARED(validation2)
`endif
`ifdef ET_SIMULATION
`CSR_DECODE_SEQ_NON_SHARED(validation3)
`endif
`ifdef NOT_VERIF_SIMULATION
`CSR_DECODE_SEQ_NON_SHARED(validation0_ps)
`endif
`ifdef NOT_VERIF_SIMULATION
`CSR_DECODE_SEQ_NON_SHARED(validation1_ps)
`endif
`ifdef NOT_VERIF_SIMULATION
`CSR_DECODE_SEQ_NON_SHARED(validation2_ps)
`endif
`ifdef NOT_VERIF_SIMULATION
`CSR_DECODE_SEQ_NON_SHARED(validation3_ps)
`endif
// Cache Ops
`CSR_DECODE_SEQ_SHARED(co_evict_va)
`CSR_DECODE_SEQ_SHARED(co_flush_va)
`CSR_DECODE_SEQ_SHARED(co_lock_va)
`CSR_DECODE_SEQ_SHARED(co_unlock_va)
`CSR_DECODE_SEQ_SHARED(co_prefetch_va)
// Supervisor Trap Setup
`CSR_DECODE_SEQ_NON_SHARED(sstatus)
`CSR_DECODE_SEQ_NON_SHARED(sie)
`CSR_DECODE_SEQ_NON_SHARED(stvec)
`CSR_DECODE_SEQ_NON_SHARED(scounteren)
// Supervisor Trap Handling
`CSR_DECODE_SEQ_NON_SHARED(sscratch)
`CSR_DECODE_SEQ_NON_SHARED(sepc)
`CSR_DECODE_SEQ_NON_SHARED(scause)
`CSR_DECODE_SEQ_NON_SHARED(stval)
`CSR_DECODE_SEQ_NON_SHARED(sip)
// Supervisor Protection and Translation
`CSR_DECODE_SEQ_SHARED(satp)
// Machine Trap Setup
`CSR_DECODE_SEQ_NON_SHARED(mstatus)
`CSR_DECODE_SEQ_NON_SHARED(medeleg)
`CSR_DECODE_SEQ_NON_SHARED(mideleg)
`CSR_DECODE_SEQ_NON_SHARED(mie)
`CSR_DECODE_SEQ_NON_SHARED(mtvec)
`CSR_DECODE_SEQ_NON_SHARED(mcounteren)
// Machine Trap Handling
`CSR_DECODE_SEQ_NON_SHARED(mscratch)
`CSR_DECODE_SEQ_NON_SHARED(mepc)
`CSR_DECODE_SEQ_NON_SHARED(mcause)
`CSR_DECODE_SEQ_NON_SHARED(mtval)
`CSR_DECODE_SEQ_NON_SHARED(mip)
// Machine Counter/Timers
`CSR_DECODE_SEQ_SHARED(mcycle)
`CSR_DECODE_SEQ_NON_SHARED(minstret)
`CSR_DECODE_SEQ_NON_SHARED(mhpmcounter3)
`CSR_DECODE_SEQ_NON_SHARED(mhpmcounter4)
`CSR_DECODE_SEQ_NON_SHARED(mhpmcounter5)
`CSR_DECODE_SEQ_NON_SHARED(mhpmcounter6)
`CSR_DECODE_SEQ_NON_SHARED(mhpmcounter7)
`CSR_DECODE_SEQ_NON_SHARED(mhpmcounter8)
// Machine counter setup
`CSR_DECODE_SEQ_NON_SHARED(mhpmevent3)
`CSR_DECODE_SEQ_NON_SHARED(mhpmevent4)
`CSR_DECODE_SEQ_NON_SHARED(mhpmevent5)
`CSR_DECODE_SEQ_NON_SHARED(mhpmevent6)
`CSR_DECODE_SEQ_NON_SHARED(mhpmevent7)
`CSR_DECODE_SEQ_NON_SHARED(mhpmevent8)
// Debug/Trace Registers (shared with Debug Mode)
`CSR_DECODE_SEQ_NON_SHARED(tdata1)
`CSR_DECODE_SEQ_NON_SHARED(tdata2)
// Debug Mode Registers
`CSR_DECODE_SEQ_NON_SHARED(dcsr)
`CSR_DECODE_SEQ_NON_SHARED(dpc)
`CSR_DECODE_SEQ_NON_SHARED(ddata0)
// custom esperanto machine csrs
`CSR_DECODE_SEQ_SHARED(matp)
`CSR_DECODE_SEQ_NON_SHARED(minstmask)
`CSR_DECODE_SEQ_NON_SHARED(minstmatch)
`CSR_DECODE_SEQ_SHARED(cacheInvalidate)
`CSR_DECODE_SEQ_SHARED(menable_shadows)
`CSR_DECODE_SEQ_SHARED(excl_mode)
`CSR_DECODE_SEQ_NON_SHARED(mbusaddr)
`ifdef DCACHE_REPORT_PC
`CSR_DECODE_SEQ_NON_SHARED(mbuspc)
`endif
// Custom Esperanto Cache Ops m-mode csr
`CSR_DECODE_SEQ_SHARED(mcache_control)
`CSR_DECODE_SEQ_SHARED(co_evict_sw)
`CSR_DECODE_SEQ_SHARED(co_flush_sw)
`CSR_DECODE_SEQ_SHARED(co_lock_sw)
`CSR_DECODE_SEQ_SHARED(co_unlock_sw)
// END autogenerated READ_AND_DECODE_SEQ
//////////////////////////////////////////////////////////////////////




//function  automatic void csr_write_comb_default;
//   begin
`define csr_write_comb_default \
      //////////////////////////////////////////////////////// \
      // BEGIN autogenerated WRITE_COMB_DEFAULT - do not edit \
      // User Floating-Point CSRs \
      `CSR_WRITE_COMB_DEFAULT(fcsr) \
      // misc esperanto \
      `CSR_WRITE_LATCH_CLK_EN_ZERO(tensor_fma) \
      `CSR_WRITE_LATCH_CLK_EN_ZERO(tensor_conv_size) \
      `CSR_WRITE_LATCH_CLK_EN_ZERO(tensor_conv_ctrl) \
      `CSR_WRITE_LATCH_CLK_EN_ZERO(tensor_cooperation) \
      `CSR_WRITE_COMB_DEFAULT(tensor_mask) \
      `CSR_WRITE_LATCH_CLK_EN_ZERO(tensor_quant) \
      `CSR_WRITE_COMB_DEFAULT(gsc_progress) \
      `ifdef ET_SIMULATION \
      `CSR_WRITE_LATCH_CLK_EN_ZERO(validation0) \
      `endif \
      `ifdef ET_SIMULATION \
      `CSR_WRITE_LATCH_CLK_EN_ZERO(validation1) \
      `endif \
      `ifdef ET_SIMULATION \
      `CSR_WRITE_LATCH_CLK_EN_ZERO(validation2) \
      `endif \
      `ifdef ET_SIMULATION \
      `CSR_WRITE_LATCH_CLK_EN_ZERO(validation3) \
      `endif \
      `ifdef NOT_VERIF_SIMULATION \
      `CSR_WRITE_COMB_DEFAULT(validation0_ps) \
      `endif \
      `ifdef NOT_VERIF_SIMULATION \
      `CSR_WRITE_COMB_DEFAULT(validation1_ps) \
      `endif \
      `ifdef NOT_VERIF_SIMULATION \
      `CSR_WRITE_COMB_DEFAULT(validation2_ps) \
      `endif \
      `ifdef NOT_VERIF_SIMULATION \
      `CSR_WRITE_COMB_DEFAULT(validation3_ps) \
      `endif \
      // Supervisor Trap Setup \
      `CSR_WRITE_COMB_DEFAULT(stvec) \
      `CSR_WRITE_LATCH_CLK_EN_ZERO(scounteren) \
      // Supervisor Trap Handling \
      `CSR_WRITE_LATCH_CLK_EN_ZERO(sscratch) \
      `CSR_WRITE_COMB_DEFAULT(sepc) \
      `CSR_WRITE_COMB_DEFAULT(scause) \
      `CSR_WRITE_COMB_DEFAULT(stval) \
      // Supervisor Protection and Translation \
      `CSR_WRITE_LATCH_CLK_EN_ZERO(satp) \
      // Machine Trap Setup \
      `CSR_WRITE_COMB_DEFAULT(mstatus) \
      `CSR_WRITE_LATCH_CLK_EN_ZERO(medeleg) \
      `CSR_WRITE_LATCH_CLK_EN_ZERO(mideleg) \
      `CSR_WRITE_COMB_DEFAULT(mie) \
      `CSR_WRITE_COMB_DEFAULT(mtvec) \
      `CSR_WRITE_LATCH_CLK_EN_ZERO(mcounteren) \
      // Machine Trap Handling \
      `CSR_WRITE_LATCH_CLK_EN_ZERO(mscratch) \
      `CSR_WRITE_COMB_DEFAULT(mepc) \
      `CSR_WRITE_COMB_DEFAULT(mcause) \
      `CSR_WRITE_COMB_DEFAULT(mtval) \
      `CSR_WRITE_COMB_DEFAULT(mip) \
      // Machine counter setup \
      `CSR_WRITE_LATCH_CLK_EN_ZERO(mhpmevent3) \
      `CSR_WRITE_LATCH_CLK_EN_ZERO(mhpmevent4) \
      `CSR_WRITE_LATCH_CLK_EN_ZERO(mhpmevent5) \
      `CSR_WRITE_LATCH_CLK_EN_ZERO(mhpmevent6) \
      `CSR_WRITE_COMB_DEFAULT(mhpmevent7) \
      `CSR_WRITE_COMB_DEFAULT(mhpmevent8) \
      // Debug/Trace Registers (shared with Debug Mode) \
      `CSR_WRITE_COMB_DEFAULT(tdata1) \
      `CSR_WRITE_LATCH_CLK_EN_ZERO(tdata2) \
      // Debug Mode Registers \
      `CSR_WRITE_COMB_DEFAULT(dcsr) \
      `CSR_WRITE_COMB_DEFAULT(dpc) \
      // custom esperanto machine csrs \
      `CSR_WRITE_LATCH_CLK_EN_ZERO(matp) \
      `CSR_WRITE_LATCH_CLK_EN_ZERO(minstmask) \
      `CSR_WRITE_LATCH_CLK_EN_ZERO(minstmatch) \
      `CSR_WRITE_LATCH_CLK_EN_ZERO(menable_shadows) \
      `CSR_WRITE_LATCH_CLK_EN_ZERO(excl_mode) \
      `CSR_WRITE_COMB_DEFAULT(mbusaddr) \
      `ifdef DCACHE_REPORT_PC \
      `CSR_WRITE_COMB_DEFAULT(mbuspc) \
      `endif \
      // END autogenerated WRITE_COMB_DEFAULT \
      //////////////////////////////////////////////////////////////////////
//   end
//endfunction

//function automatic void csr_write_comb;
//   begin
`define csr_write_comb \
      ////////////////////////////////////////////////////////////////////// \
      // BEGIN autogenerated WRITE_CORE_COMB - do not edit \
 \
      // WRITE_COMB for regs that shadow some other reg \
      // User Floating-Point CSRs \
      `CSR_WRITE_COMB_NON_SHARED_SHADOW(fflags, write_fflags(wb_wdata[$bits(csr_fflags_t)-1:0]), fcsr, write_fcsr_as_fflags) \
      `CSR_WRITE_COMB_NON_SHARED_SHADOW(frm, wb_wdata[$bits(csr_frm_t)-1:0], fcsr, write_fcsr_as_frm) \
      // Supervisor Trap Setup \
      `CSR_WRITE_COMB_NON_SHARED_SHADOW(sstatus, write_sstatus(wb_wdata[$bits(csr_sstatus_t)-1:0]), mstatus, write_mstatus_as_sstatus) \
      `CSR_WRITE_COMB_NON_SHARED_SHADOW(sie, sie_wdata[wb_thread_id], mie, write_mie_as_sie) \
      // Supervisor Trap Handling \
      `CSR_WRITE_COMB_NON_SHARED_SHADOW(sip, sip_wdata[wb_thread_id], mip, write_mip_as_sip) \
 \
      // WRITE_COMB for the other regs \
      // User Floating-Point CSRs \
      `CSR_WRITE_COMB_NON_SHARED(fcsr, write_fcsr(wb_wdata[$bits(csr_fcsr_t)-1:0])) \
      // misc esperanto \
      `CSR_WRITE_COMB_LATCH_SHARED(tensor_fma, tensorfma_control'(wb_wdata_1p[$bits(tensorfma_control)-1:0])) \
      `CSR_WRITE_COMB_LATCH_NON_SHARED(tensor_conv_size, tensorconv_size'(wb_wdata_1p[$bits(tensorconv_size)-1:0])) \
      `CSR_WRITE_COMB_LATCH_NON_SHARED(tensor_conv_ctrl, tensorconv_control'(wb_wdata_1p[$bits(tensorconv_control)-1:0])) \
      `CSR_WRITE_COMB_LATCH_SHARED(tensor_cooperation, tensorcoop_control'(wb_wdata_1p[$bits(tensorcoop_control)-1:0])) \
      `CSR_WRITE_COMB_NON_SHARED(tensor_mask, wb_wdata[15:0]) \
      `CSR_WRITE_COMB_LATCH_SHARED(tensor_quant, tensorquant_control'(wb_wdata_1p[$bits(tensorquant_control)-1:0])) \
      `CSR_WRITE_COMB_NON_SHARED(gsc_progress, wb_wdata[2:0]) \
      `ifdef ET_SIMULATION \
      `CSR_WRITE_COMB_LATCH_NON_SHARED(validation0, wb_wdata_1p) \
      `endif \
      `ifdef ET_SIMULATION \
      `CSR_WRITE_COMB_LATCH_NON_SHARED(validation1, wb_wdata_1p) \
      `endif \
      `ifdef ET_SIMULATION \
      `CSR_WRITE_COMB_LATCH_NON_SHARED(validation2, wb_wdata_1p) \
      `endif \
      `ifdef ET_SIMULATION \
      `CSR_WRITE_COMB_LATCH_NON_SHARED(validation3, wb_wdata_1p) \
      `endif \
      `ifdef NOT_VERIF_SIMULATION \
      `CSR_WRITE_COMB_NON_SHARED(validation0_ps, wb_wdata[0:0]) \
      `endif \
      `ifdef NOT_VERIF_SIMULATION \
      `CSR_WRITE_COMB_NON_SHARED(validation1_ps, wb_wdata[0:0]) \
      `endif \
      `ifdef NOT_VERIF_SIMULATION \
      `CSR_WRITE_COMB_NON_SHARED(validation2_ps, wb_wdata[0:0]) \
      `endif \
      `ifdef NOT_VERIF_SIMULATION \
      `CSR_WRITE_COMB_NON_SHARED(validation3_ps, wb_wdata[0:0]) \
      `endif \
      // Supervisor Trap Setup \
      `CSR_WRITE_COMB_NON_SHARED(stvec, extend_VA(wb_wdata)) \
      `CSR_WRITE_COMB_LATCH_NON_SHARED(scounteren, wb_wdata_1p[`CSR_NR_COUNTERS-1:0]) \
      // Supervisor Trap Handling \
      `CSR_WRITE_COMB_LATCH_NON_SHARED(sscratch, wb_wdata_1p) \
      `CSR_WRITE_COMB_NON_SHARED(sepc, extend_VA(wb_wdata)) \
      `CSR_WRITE_COMB_NON_SHARED(scause, write_cause(wb_wdata[$bits(csr_cause_t)-1:0])) \
      `CSR_WRITE_COMB_NON_SHARED(stval, extend_VA(wb_wdata)) \
      // Supervisor Protection and Translation \
      `CSR_WRITE_COMB_LATCH_SHARED(satp, write_satp(wb_wdata_1p[$bits(csr_satp_t)-1:0])) \
      // Machine Trap Setup \
      `CSR_WRITE_COMB_NON_SHARED(mstatus, write_mstatus(wb_wdata[$bits(csr_mstatus_t)-1:0])) \
      `CSR_WRITE_COMB_LATCH_NON_SHARED(medeleg, write_medeleg(wb_wdata_1p[$bits(csr_medeleg_t)-1:0])) \
      `CSR_WRITE_COMB_LATCH_NON_SHARED(mideleg, write_mideleg(wb_wdata_1p[$bits(csr_mideleg_t)-1:0])) \
      `CSR_WRITE_COMB_NON_SHARED(mie, write_mie(wb_wdata[$bits(csr_mie_t)-1:0])) \
      `CSR_WRITE_COMB_NON_SHARED(mtvec, extend_VA(wb_wdata)) \
      `CSR_WRITE_COMB_LATCH_NON_SHARED(mcounteren, wb_wdata_1p[`CSR_NR_COUNTERS-1:0]) \
      // Machine Trap Handling \
      `CSR_WRITE_COMB_LATCH_NON_SHARED(mscratch, wb_wdata_1p) \
      `CSR_WRITE_COMB_NON_SHARED(mepc, extend_VA(wb_wdata)) \
      `CSR_WRITE_COMB_NON_SHARED(mcause, write_cause(wb_wdata[$bits(csr_cause_t)-1:0])) \
      `CSR_WRITE_COMB_NON_SHARED(mtval, extend_VA(wb_wdata)) \
      `CSR_WRITE_COMB_NON_SHARED(mip, write_mip(wb_wdata[$bits(csr_mip_t)-1:0])) \
      // Machine counter setup \
      `CSR_WRITE_COMB_LATCH_NON_SHARED(mhpmevent3, wb_wdata_1p[`CSR_NR_EVENTS_L-1:0]) \
      `CSR_WRITE_COMB_LATCH_NON_SHARED(mhpmevent4, wb_wdata_1p[`CSR_NR_EVENTS_L-1:0]) \
      `CSR_WRITE_COMB_LATCH_NON_SHARED(mhpmevent5, wb_wdata_1p[`CSR_NR_EVENTS_L-1:0]) \
      `CSR_WRITE_COMB_LATCH_NON_SHARED(mhpmevent6, wb_wdata_1p[`CSR_NR_EVENTS_L-1:0]) \
      `CSR_WRITE_COMB_NON_SHARED(mhpmevent7, wb_wdata[`CSR_NR_EVENTS_L-1:0]) \
      `CSR_WRITE_COMB_NON_SHARED(mhpmevent8, wb_wdata[`CSR_NR_EVENTS_L-1:0]) \
      // Debug/Trace Registers (shared with Debug Mode) \
      `CSR_WRITE_COMB_NON_SHARED(tdata1, write_tdata1(wb_wdata[$bits(csr_tdata1_t)-1:0])) \
      `CSR_WRITE_COMB_LATCH_NON_SHARED(tdata2, wb_wdata_1p[`VA_SIZE-1:0]) \
      // Debug Mode Registers \
      `CSR_WRITE_COMB_NON_SHARED(dcsr, write_dcsr(wb_wdata[$bits(csr_dcsr_t)-1:0])) \
      `CSR_WRITE_COMB_NON_SHARED(dpc, extend_VA(wb_wdata)) \
      // custom esperanto machine csrs \
      `CSR_WRITE_COMB_LATCH_SHARED(matp, write_matp(wb_wdata_1p[$bits(csr_matp_t)-1:0])) \
      `CSR_WRITE_COMB_LATCH_NON_SHARED(minstmask, wb_wdata_1p[$bits(minst_mask_t)-1:0]) \
      `CSR_WRITE_COMB_LATCH_NON_SHARED(minstmatch, wb_wdata_1p[31:0]) \
      `CSR_WRITE_COMB_LATCH_SHARED(menable_shadows, wb_wdata_1p[$bits(menable_shadows_t)-1:0]) \
      `CSR_WRITE_COMB_LATCH_SHARED(excl_mode, wb_wdata_1p[0:0]) \
      `CSR_WRITE_COMB_NON_SHARED(mbusaddr, wb_wdata[`PA_SIZE-1:0]) \
      `ifdef DCACHE_REPORT_PC \
      `CSR_WRITE_COMB_NON_SHARED(mbuspc, wb_wdata[`PC_SIZE_EXT-1:0]) \
      `endif \
      // END autogenerated WRITE_CORE_COMB \
      //////////////////////////////////////////////////////////////////////
//   end
//endfunction




//////////////////////////////////////////////////////////////////////
// BEGIN autogenerated WRITE_SEQ - do not edit
   // User Floating-Point CSRs
`CSR_WRITE_SEQ_NON_SHARED(clock, fcsr_pre, fcsr_next)
`CSR_WRITE_TYPE_WITH_RESERVED_NON_SHARED(fcsr, write_fcsr_non_reserved)
   // misc esperanto
`CSR_WRITE_LATCH_SHARED(clock_wb, tensor_fma, tensor_fma_pre, tensor_fma_next)
`CSR_WRITE_TYPE_WITH_RESERVED_SHARED(tensor_fma, tensorfma_control')
`CSR_WRITE_LATCH_NON_SHARED(clock_wb, tensor_conv_size, tensor_conv_size_pre, tensor_conv_size_next)
`CSR_WRITE_TYPE_WITH_RESERVED_NON_SHARED(tensor_conv_size, tensorconv_size')
`CSR_WRITE_LATCH_NON_SHARED(clock_wb, tensor_conv_ctrl, tensor_conv_ctrl_pre, tensor_conv_ctrl_next)
`CSR_WRITE_TYPE_WITH_RESERVED_NON_SHARED(tensor_conv_ctrl, tensorconv_control')
`CSR_WRITE_LATCH_SHARED(clock_wb, tensor_cooperation, tensor_cooperation_pre, tensor_cooperation_next)
`CSR_WRITE_TYPE_WITH_RESERVED_SHARED(tensor_cooperation, tensorcoop_control')
`CSR_WRITE_SEQ_NON_SHARED(clock, tensor_mask, tensor_mask_next)
`CSR_WRITE_LATCH_SHARED(clock_wb, tensor_quant, tensor_quant_pre, tensor_quant_next)
`CSR_WRITE_TYPE_WITH_RESERVED_SHARED(tensor_quant, tensorquant_control')
`CSR_WRITE_SEQ_NON_SHARED_RST_ND(clock, gsc_progress, gsc_progress_next, 0)
`ifdef ET_SIMULATION
`CSR_WRITE_LATCH_NON_SHARED(clock_wb, validation0, validation0, validation0_next)
`endif
`ifdef ET_SIMULATION
`CSR_WRITE_LATCH_NON_SHARED(clock_wb, validation1, validation1, validation1_next)
`endif
`ifdef ET_SIMULATION
`CSR_WRITE_LATCH_NON_SHARED(clock_wb, validation2, validation2, validation2_next)
`endif
`ifdef ET_SIMULATION
`CSR_WRITE_LATCH_NON_SHARED(clock_wb, validation3, validation3, validation3_next)
`endif
`ifdef NOT_VERIF_SIMULATION
`CSR_WRITE_SEQ_NON_SHARED(clock_wb, validation0_ps, validation0_ps_next)
`endif
`ifdef NOT_VERIF_SIMULATION
`CSR_WRITE_SEQ_NON_SHARED(clock_wb, validation1_ps, validation1_ps_next)
`endif
`ifdef NOT_VERIF_SIMULATION
`CSR_WRITE_SEQ_NON_SHARED(clock_wb, validation2_ps, validation2_ps_next)
`endif
`ifdef NOT_VERIF_SIMULATION
`CSR_WRITE_SEQ_NON_SHARED(clock_wb, validation3_ps, validation3_ps_next)
`endif
   // Supervisor Trap Setup
`CSR_WRITE_SEQ_NON_SHARED(clock_wb, stvec_pre, stvec_next)
`CSR_WRITE_TYPE_WITH_RESERVED_NON_SHARED(stvec, write_tvec_non_reserved)
`CSR_WRITE_LATCH_NON_SHARED_RST_ND(clock_wb, scounteren, scounteren, scounteren_next, '0)
   // Supervisor Trap Handling
`CSR_WRITE_LATCH_NON_SHARED(clock_wb, sscratch, sscratch, sscratch_next)
`CSR_WRITE_SEQ_NON_SHARED(clock, sepc_pre, sepc_next)
`CSR_WRITE_TYPE_WITH_RESERVED_NON_SHARED(sepc, write_pc_non_reserved)
`CSR_WRITE_SEQ_NON_SHARED(clock, scause_pre, scause_next)
`CSR_WRITE_TYPE_WITH_RESERVED_NON_SHARED(scause, write_cause_non_reserved)
`CSR_WRITE_SEQ_NON_SHARED(clock, stval, stval_next)
   // Supervisor Protection and Translation
`CSR_WRITE_LATCH_SHARED(clock_wb, satp, satp_pre, satp_next)
`CSR_WRITE_TYPE_WITH_RESERVED_SHARED(satp, write_satp_non_reserved)
   // Machine Trap Setup
`CSR_WRITE_SEQ_NON_SHARED_RST_ND(clock, mstatus_pre, mstatus_next, `MSTATUS_RESET_VAL)
`CSR_WRITE_TYPE_WITH_RESERVED_NON_SHARED(mstatus, write_mstatus_non_reserved)
`CSR_WRITE_LATCH_NON_SHARED_RST_ND(clock_wb, medeleg, medeleg_pre, medeleg_next, '0)
`CSR_WRITE_TYPE_WITH_RESERVED_NON_SHARED(medeleg, write_medeleg_non_reserved)
`CSR_WRITE_LATCH_NON_SHARED_RST_ND(clock_wb, mideleg, mideleg_pre, mideleg_next, '0)
`CSR_WRITE_TYPE_WITH_RESERVED_NON_SHARED(mideleg, write_mideleg_non_reserved)
`CSR_WRITE_SEQ_NON_SHARED_RST_ND(clock_wb, mie_pre, mie_next, '0)
`CSR_WRITE_TYPE_WITH_RESERVED_NON_SHARED(mie, write_mie_non_reserved)
`CSR_WRITE_SEQ_NON_SHARED(clock_wb, mtvec_pre, mtvec_next)
`CSR_WRITE_TYPE_WITH_RESERVED_NON_SHARED(mtvec, write_tvec_non_reserved)
`CSR_WRITE_LATCH_NON_SHARED_RST_ND(clock_wb, mcounteren, mcounteren, mcounteren_next, '0)
   // Machine Trap Handling
`CSR_WRITE_LATCH_NON_SHARED(clock_wb, mscratch, mscratch, mscratch_next)
`CSR_WRITE_SEQ_NON_SHARED(clock, mepc_pre, mepc_next)
`CSR_WRITE_TYPE_WITH_RESERVED_NON_SHARED(mepc, write_pc_non_reserved)
`CSR_WRITE_SEQ_NON_SHARED_RST_ND(clock, mcause_pre, mcause_next, '0)
`CSR_WRITE_TYPE_WITH_RESERVED_NON_SHARED(mcause, write_cause_non_reserved)
`CSR_WRITE_SEQ_NON_SHARED(clock, mtval, mtval_next)
`CSR_WRITE_SEQ_NON_SHARED_RST_ND(clock, mip_pre, mip_next, '0)
`CSR_WRITE_TYPE_WITH_RESERVED_NON_SHARED(mip, write_mip_non_reserved)
   // Machine counter setup
`CSR_WRITE_LATCH_NON_SHARED_RST_ND(clock_wb, mhpmevent3, mhpmevent3, mhpmevent3_next, 0)
`CSR_WRITE_LATCH_NON_SHARED_RST_ND(clock_wb, mhpmevent4, mhpmevent4, mhpmevent4_next, 0)
`CSR_WRITE_LATCH_NON_SHARED_RST_ND(clock_wb, mhpmevent5, mhpmevent5, mhpmevent5_next, 0)
`CSR_WRITE_LATCH_NON_SHARED_RST_ND(clock_wb, mhpmevent6, mhpmevent6, mhpmevent6_next, 0)
`CSR_WRITE_SEQ_NON_SHARED_RST_ND(clock_wb, mhpmevent7, mhpmevent7_next, 0)
`CSR_WRITE_SEQ_NON_SHARED_RST_ND(clock_wb, mhpmevent8, mhpmevent8_next, 0)
   // Debug/Trace Registers (shared with Debug Mode)
`CSR_WRITE_SEQ_NON_SHARED_RST_ND(clock_wb, tdata1_pre, tdata1_next, `TDATA1_RESET_VAL)
`CSR_WRITE_TYPE_WITH_RESERVED_NON_SHARED(tdata1, write_tdata1_non_reserved)
`CSR_WRITE_LATCH_NON_SHARED(clock_wb, tdata2, tdata2, tdata2_next)
   // Debug Mode Registers
`CSR_WRITE_SEQ_NON_SHARED_RST_ND(clock, dcsr_pre, dcsr_next, `DCSR_RESET_VAL)
`CSR_WRITE_TYPE_WITH_RESERVED_NON_SHARED(dcsr, write_dcsr_non_reserved)
`CSR_WRITE_SEQ_NON_SHARED(clock, dpc_pre, dpc_next)
`CSR_WRITE_TYPE_WITH_RESERVED_NON_SHARED(dpc, write_pc_non_reserved)
   // custom esperanto machine csrs
`CSR_WRITE_LATCH_SHARED_RST_ND(clock_wb, matp, matp_pre, matp_next, '0)
`CSR_WRITE_TYPE_WITH_RESERVED_SHARED(matp, write_matp_non_reserved)
`CSR_WRITE_LATCH_NON_SHARED_RST_ND(clock_wb, minstmask, minstmask_pre, minstmask_next, 0)
`CSR_WRITE_TYPE_WITH_RESERVED_NON_SHARED(minstmask, minst_mask_t')
`CSR_WRITE_LATCH_NON_SHARED_RST_ND(clock_wb, minstmatch, minstmatch, minstmatch_next, '0)
`CSR_WRITE_LATCH_SHARED_RST_ND(clock_wb, menable_shadows, menable_shadows_pre, menable_shadows_next, '0)
`CSR_WRITE_TYPE_WITH_RESERVED_SHARED(menable_shadows, menable_shadows_t')
`CSR_WRITE_LATCH_SHARED_RST_ND(clock_wb, excl_mode, excl_mode, excl_mode_next, '0)
`CSR_WRITE_SEQ_NON_SHARED(clock, mbusaddr, mbusaddr_next)
`ifdef DCACHE_REPORT_PC
`CSR_WRITE_SEQ_NON_SHARED(clock, mbuspc, mbuspc_next)
`endif
// END autogenerated WRITE_SEQ
//////////////////////////////////////////////////////////////////////


//////////////////////////////////////////////////////////////////////
// BEGIN autogenerated TYPE_CONVERSIONS - do not edit
   //conversion functions for csr_cause_t
   function automatic csr_cause_t write_cause;
   input [$bits(csr_cause_t)-1:0] d;
   csr_cause_t dd;
   csr_cause_t ret;
   begin
      dd = csr_cause_t'(d);
      ret.cause = dd.cause;
      ret.reserved0 = '0; 
      ret.interrupt_x = dd.interrupt_x;
      return ret;
   end
   endfunction

   function automatic csr_cause_t write_cause_non_reserved;
   input csr_cause_t d;
   csr_cause_t ret;
   begin
      ret.cause = d.cause;
      ret.reserved0 = '0; 
      ret.interrupt_x = d.interrupt_x;
      return ret;
   end
   endfunction

   //conversion functions for csr_dcsr_t
   function automatic csr_dcsr_t write_dcsr;
   input [$bits(csr_dcsr_t)-1:0] d;
   csr_dcsr_t dd;
   csr_dcsr_t ret;
   begin
      dd = csr_dcsr_t'(d);
      ret.prv = dd.prv;
      ret.step = dd.step;
      ret.nmip = 'x; // RO field... needs to be set manually if used
      ret.mprven = dd.mprven;
      ret.reserved0 = '0; 
      ret.cause = 'x; // RO field... needs to be set manually if used
      ret.stoptime_reserved = '0; 
      ret.stopcount_reserved = '0; 
      ret.stepie_reserved = '0; 
      ret.ebreaku = dd.ebreaku;
      ret.ebreaks = dd.ebreaks;
      ret.reserved1 = '0; 
      ret.ebreakm = dd.ebreakm;
      ret.reserved2 = '0; 
      ret.xdebugver = 4'h4; // RO field
      return ret;
   end
   endfunction

   function automatic csr_dcsr_t write_dcsr_non_reserved;
   input csr_dcsr_t d;
   csr_dcsr_t ret;
   begin
      ret.prv = d.prv;
      ret.step = d.step;
      ret.nmip = d.nmip;
      ret.mprven = d.mprven;
      ret.reserved0 = '0; 
      ret.cause = d.cause;
      ret.stoptime_reserved = '0; 
      ret.stopcount_reserved = '0; 
      ret.stepie_reserved = '0; 
      ret.ebreaku = d.ebreaku;
      ret.ebreaks = d.ebreaks;
      ret.reserved1 = '0; 
      ret.ebreakm = d.ebreakm;
      ret.reserved2 = '0; 
      ret.xdebugver = d.xdebugver;
      return ret;
   end
   endfunction

   //conversion functions for csr_fcsr_t
   function automatic csr_fcsr_t write_fcsr;
   input [$bits(csr_fcsr_t)-1:0] d;
   csr_fcsr_t dd;
   csr_fcsr_t ret;
   begin
      dd = csr_fcsr_t'(d);
      ret.flags = dd.flags;
      ret.rm = dd.rm;
      ret.reserved0 = '0; 
      ret.eflags = dd.eflags;
      return ret;
   end
   endfunction

   function automatic csr_fcsr_t write_fcsr_non_reserved;
   input csr_fcsr_t d;
   csr_fcsr_t ret;
   begin
      ret.flags = d.flags;
      ret.rm = d.rm;
      ret.reserved0 = '0; 
      ret.eflags = d.eflags;
      return ret;
   end
   endfunction


   function automatic csr_fcsr_t write_fcsr_as_fflags;
   input csr_fcsr_t orig;
   input csr_fflags_t d;
   csr_fcsr_t ret;
   begin
      ret = orig;
      ret.flags = d.flags;
      ret.eflags = d.eflags;
      return ret;
   end
   endfunction

   function automatic csr_fcsr_t write_fcsr_as_frm;
   input csr_fcsr_t orig;
   input csr_frm_t d;
   csr_fcsr_t ret;
   begin
      ret = orig;
      ret.rm = d.rm;
      return ret;
   end
   endfunction

   function automatic csr_fflags_t read_fcsr_as_fflags;
   input csr_fcsr_t orig;
   csr_fflags_t ret;
   begin
      ret = '0;
      ret.flags = orig.flags;
      ret.eflags = orig.eflags;
      return ret;
   end
   endfunction


   function automatic csr_frm_t read_fcsr_as_frm;
   input csr_fcsr_t orig;
   csr_frm_t ret;
   begin
      ret.rm = orig.rm;
      return ret;
   end
   endfunction

   //conversion functions for csr_fflags_t
   function automatic csr_fflags_t write_fflags;
   input [$bits(csr_fflags_t)-1:0] d;
   csr_fflags_t dd;
   csr_fflags_t ret;
   begin
      dd = csr_fflags_t'(d);
      ret.flags = dd.flags;
      ret.reserved0 = '0; 
      ret.eflags = dd.eflags;
      return ret;
   end
   endfunction

   //conversion functions for csr_matp_t
   function automatic csr_matp_t write_matp;
   input [$bits(csr_matp_t)-1:0] d;
   csr_matp_t dd;
   csr_matp_t ret;
   begin
      dd = csr_matp_t'(d);
      ret.ppn = 28'b0; // RO field
      ret.reserved0 = '0; 
      ret.reserved1 = '0; 
      ret.lock = 1'b0; // RO field
      ret.mode = 4'b0; // RO field
      return ret;
   end
   endfunction

   function automatic csr_matp_t write_matp_non_reserved;
   input csr_matp_t d;
   csr_matp_t ret;
   begin
      ret.ppn = d.ppn;
      ret.reserved0 = '0; 
      ret.reserved1 = '0; 
      ret.lock = d.lock;
      ret.mode = d.mode;
      return ret;
   end
   endfunction

   //conversion functions for csr_medeleg_t
   function automatic csr_medeleg_t write_medeleg;
   input [$bits(csr_medeleg_t)-1:0] d;
   csr_medeleg_t dd;
   csr_medeleg_t ret;
   begin
      dd = csr_medeleg_t'(d);
      ret.misaligned_fetch_reserved = '0; 
      ret.fetch_access_reserved = '0; 
      ret.illegal_instruction_reserved = '0; 
      ret.breakpoint = dd.breakpoint;
      ret.misaligned_load_reserved = '0; 
      ret.load_access_reserved = '0; 
      ret.misaligned_store_reserved = '0; 
      ret.store_access_reserved = '0; 
      ret.user_ecall = dd.user_ecall;
      ret.supervisor_ecall_reserved = '0; 
      ret.reserved0 = '0; 
      ret.machine_ecall_reserved = '0; 
      ret.fetch_page_fault = dd.fetch_page_fault;
      ret.load_page_fault = dd.load_page_fault;
      ret.debug_around_fault_reserved = '0; 
      ret.store_page_fault = dd.store_page_fault;
      ret.reserved1 = '0; 
      return ret;
   end
   endfunction

   function automatic csr_medeleg_t write_medeleg_non_reserved;
   input csr_medeleg_t d;
   csr_medeleg_t ret;
   begin
      ret.misaligned_fetch_reserved = '0; 
      ret.fetch_access_reserved = '0; 
      ret.illegal_instruction_reserved = '0; 
      ret.breakpoint = d.breakpoint;
      ret.misaligned_load_reserved = '0; 
      ret.load_access_reserved = '0; 
      ret.misaligned_store_reserved = '0; 
      ret.store_access_reserved = '0; 
      ret.user_ecall = d.user_ecall;
      ret.supervisor_ecall_reserved = '0; 
      ret.reserved0 = '0; 
      ret.machine_ecall_reserved = '0; 
      ret.fetch_page_fault = d.fetch_page_fault;
      ret.load_page_fault = d.load_page_fault;
      ret.debug_around_fault_reserved = '0; 
      ret.store_page_fault = d.store_page_fault;
      ret.reserved1 = '0; 
      return ret;
   end
   endfunction

   //conversion functions for csr_mideleg_t
   function automatic csr_mideleg_t write_mideleg;
   input [$bits(csr_mideleg_t)-1:0] d;
   csr_mideleg_t dd;
   csr_mideleg_t ret;
   begin
      dd = csr_mideleg_t'(d);
      ret.usip_reserved = '0; 
      ret.ssip = dd.ssip;
      ret.reserved0 = '0; 
      ret.msip_reserved = '0; 
      ret.utip_reserved = '0; 
      ret.stip = dd.stip;
      ret.reserved1 = '0; 
      ret.mtip_reserved = '0; 
      ret.ueip_reserved = '0; 
      ret.seip = dd.seip;
      ret.reserved2 = '0; 
      ret.meip_reserved = '0; 
      ret.reserved3 = '0; 
      ret.mbad_rep_reserved = '0; 
      ret.reserved4 = '0; 
      ret.mieco_reserved = '0; 
      ret.reserved5 = '0; 
      return ret;
   end
   endfunction

   function automatic csr_mideleg_t write_mideleg_non_reserved;
   input csr_mideleg_t d;
   csr_mideleg_t ret;
   begin
      ret.usip_reserved = '0; 
      ret.ssip = d.ssip;
      ret.reserved0 = '0; 
      ret.msip_reserved = '0; 
      ret.utip_reserved = '0; 
      ret.stip = d.stip;
      ret.reserved1 = '0; 
      ret.mtip_reserved = '0; 
      ret.ueip_reserved = '0; 
      ret.seip = d.seip;
      ret.reserved2 = '0; 
      ret.meip_reserved = '0; 
      ret.reserved3 = '0; 
      ret.mbad_rep_reserved = '0; 
      ret.reserved4 = '0; 
      ret.mieco_reserved = '0; 
      ret.reserved5 = '0; 
      return ret;
   end
   endfunction

   //conversion functions for csr_mie_t
   function automatic csr_mie_t write_mie;
   input [$bits(csr_mie_t)-1:0] d;
   csr_mie_t dd;
   csr_mie_t ret;
   begin
      dd = csr_mie_t'(d);
      ret.usie_reserved = '0; 
      ret.ssie = dd.ssie;
      ret.reserved0 = '0; 
      ret.msie = dd.msie;
      ret.utie_reserved = '0; 
      ret.stie = dd.stie;
      ret.reserved1 = '0; 
      ret.mtie = dd.mtie;
      ret.ueie_reserved = '0; 
      ret.seie = dd.seie;
      ret.reserved2 = '0; 
      ret.meie = dd.meie;
      ret.reserved3 = '0; 
      ret.mbad_red = dd.mbad_red;
      ret.reserved4 = '0; 
      ret.mieco = dd.mieco;
      ret.reserved5 = '0; 
      ret.bus_err = dd.bus_err;
      ret.reserved6 = '0; 
      return ret;
   end
   endfunction

   function automatic csr_mie_t write_mie_non_reserved;
   input csr_mie_t d;
   csr_mie_t ret;
   begin
      ret.usie_reserved = '0; 
      ret.ssie = d.ssie;
      ret.reserved0 = '0; 
      ret.msie = d.msie;
      ret.utie_reserved = '0; 
      ret.stie = d.stie;
      ret.reserved1 = '0; 
      ret.mtie = d.mtie;
      ret.ueie_reserved = '0; 
      ret.seie = d.seie;
      ret.reserved2 = '0; 
      ret.meie = d.meie;
      ret.reserved3 = '0; 
      ret.mbad_red = d.mbad_red;
      ret.reserved4 = '0; 
      ret.mieco = d.mieco;
      ret.reserved5 = '0; 
      ret.bus_err = d.bus_err;
      ret.reserved6 = '0; 
      return ret;
   end
   endfunction


   function automatic csr_mie_t write_mie_as_sie;
   input csr_mie_t orig;
   input csr_sie_t d;
   csr_mie_t ret;
   begin
      ret = orig;
      ret.ssie = d.ssie;
      ret.stie = d.stie;
      ret.seie = d.seie;
      return ret;
   end
   endfunction

   function automatic csr_sie_t read_mie_as_sie;
   input csr_mie_t orig;
   csr_sie_t ret;
   begin
      ret = '0;
      ret.ssie = orig.ssie;
      ret.stie = orig.stie;
      ret.seie = orig.seie;
      return ret;
   end
   endfunction

   //conversion functions for csr_mip_t
   function automatic csr_mip_t write_mip;
   input [$bits(csr_mip_t)-1:0] d;
   csr_mip_t dd;
   csr_mip_t ret;
   begin
      dd = csr_mip_t'(d);
      ret.usip_reserved = '0; 
      ret.ssip = dd.ssip;
      ret.reserved0 = '0; 
      ret.msip = 'x; // RO field... needs to be set manually if used
      ret.utip_reserved = '0; 
      ret.stip = dd.stip;
      ret.reserved1 = '0; 
      ret.mtip = 'x; // RO field... needs to be set manually if used
      ret.ueip_reserved = '0; 
      ret.seip = dd.seip;
      ret.reserved2 = '0; 
      ret.meip = 'x; // RO field... needs to be set manually if used
      ret.reserved3 = '0; 
      ret.mbad_red = dd.mbad_red;
      ret.reserved4 = '0; 
      ret.mieco = 'x; // RO field... needs to be set manually if used
      ret.reserved5 = '0; 
      ret.bus_err = dd.bus_err;
      ret.reserved6 = '0; 
      return ret;
   end
   endfunction

   function automatic csr_mip_t write_mip_non_reserved;
   input csr_mip_t d;
   csr_mip_t ret;
   begin
      ret.usip_reserved = '0; 
      ret.ssip = d.ssip;
      ret.reserved0 = '0; 
      ret.msip = d.msip;
      ret.utip_reserved = '0; 
      ret.stip = d.stip;
      ret.reserved1 = '0; 
      ret.mtip = d.mtip;
      ret.ueip_reserved = '0; 
      ret.seip = d.seip;
      ret.reserved2 = '0; 
      ret.meip = d.meip;
      ret.reserved3 = '0; 
      ret.mbad_red = d.mbad_red;
      ret.reserved4 = '0; 
      ret.mieco = d.mieco;
      ret.reserved5 = '0; 
      ret.bus_err = d.bus_err;
      ret.reserved6 = '0; 
      return ret;
   end
   endfunction


   function automatic csr_mip_t write_mip_as_sip;
   input csr_mip_t orig;
   input csr_sip_t d;
   csr_mip_t ret;
   begin
      ret = orig;
      ret.ssip = d.ssip;
      ret.stip = d.stip;
      ret.seip = d.seip;
      return ret;
   end
   endfunction

   function automatic csr_sip_t read_mip_as_sip;
   input csr_mip_t orig;
   csr_sip_t ret;
   begin
      ret = '0;
      ret.ssip = orig.ssip;
      ret.stip = orig.stip;
      ret.seip = orig.seip;
      return ret;
   end
   endfunction

   //conversion functions for csr_mstatus_t
   function automatic csr_mstatus_t write_mstatus;
   input [$bits(csr_mstatus_t)-1:0] d;
   csr_mstatus_t dd;
   csr_mstatus_t ret;
   begin
      dd = csr_mstatus_t'(d);
      ret.uie_reserved = '0; 
      ret.sie = dd.sie;
      ret.reserved0 = '0; 
      ret.mie = dd.mie;
      ret.upie_reserved = '0; 
      ret.spie = dd.spie;
      ret.reserved1 = '0; 
      ret.mpie = dd.mpie;
      ret.spp = dd.spp;
      ret.reserved2 = '0; 
      ret.mpp = dd.mpp;
      ret.fs = dd.fs;
      ret.xs = 'x; // RO field... needs to be set manually if used
      ret.mprv = dd.mprv;
      ret.sum = 1'b0; // RO field
      ret.mxr = dd.mxr;
      ret.tvm = dd.tvm;
      ret.tw = dd.tw;
      ret.tsr = dd.tsr;
      ret.reserved3 = '0; 
      ret.uxl = 2'b10; // RO field
      ret.sxl = 2'b10; // RO field
      ret.reserved4 = '0; 
      ret.sd = 'x; // RO field... needs to be set manually if used
      return ret;
   end
   endfunction

   function automatic csr_mstatus_t write_mstatus_non_reserved;
   input csr_mstatus_t d;
   csr_mstatus_t ret;
   begin
      ret.uie_reserved = '0; 
      ret.sie = d.sie;
      ret.reserved0 = '0; 
      ret.mie = d.mie;
      ret.upie_reserved = '0; 
      ret.spie = d.spie;
      ret.reserved1 = '0; 
      ret.mpie = d.mpie;
      ret.spp = d.spp;
      ret.reserved2 = '0; 
      ret.mpp = d.mpp;
      ret.fs = d.fs;
      ret.xs = d.xs;
      ret.mprv = d.mprv;
      ret.sum = d.sum;
      ret.mxr = d.mxr;
      ret.tvm = d.tvm;
      ret.tw = d.tw;
      ret.tsr = d.tsr;
      ret.reserved3 = '0; 
      ret.uxl = d.uxl;
      ret.sxl = d.sxl;
      ret.reserved4 = '0; 
      ret.sd = d.sd;
      return ret;
   end
   endfunction


   function automatic csr_mstatus_t write_mstatus_as_sstatus;
   input csr_mstatus_t orig;
   input csr_sstatus_t d;
   csr_mstatus_t ret;
   begin
      ret = orig;
      ret.sie = d.sie;
      ret.spie = d.spie;
      ret.spp = d.spp;
      ret.fs = d.fs;
       // ret.xs = RO;
       // ret.sum = RO;
      ret.mxr = d.mxr;
       // ret.uxl = RO;
       // ret.sd = RO;
      return ret;
   end
   endfunction

   function automatic csr_sstatus_t read_mstatus_as_sstatus;
   input csr_mstatus_t orig;
   csr_sstatus_t ret;
   begin
      ret = '0;
      ret.sie = orig.sie;
      ret.spie = orig.spie;
      ret.spp = orig.spp;
      ret.fs = orig.fs;
      ret.xs = orig.xs;
      ret.sum = orig.sum;
      ret.mxr = orig.mxr;
      ret.uxl = orig.uxl;
      ret.sd = orig.sd;
      return ret;
   end
   endfunction

   //conversion functions for csr_pc_t
   function automatic csr_pc_t write_pc;
   input [$bits(csr_pc_t)-1:0] d;
   csr_pc_t dd;
   csr_pc_t ret;
   begin
      dd = csr_pc_t'(d);
      ret.reserved0 = '0; 
      ret.base = dd.base;
      ret.sign_ext = dd.sign_ext;
      return ret;
   end
   endfunction

   function automatic csr_pc_t write_pc_non_reserved;
   input csr_pc_t d;
   csr_pc_t ret;
   begin
      ret.reserved0 = '0; 
      ret.base = d.base;
      ret.sign_ext = d.sign_ext;
      return ret;
   end
   endfunction

   //conversion functions for csr_satp_t
   function automatic csr_satp_t write_satp;
   input [$bits(csr_satp_t)-1:0] d;
   csr_satp_t dd;
   csr_satp_t ret;
   begin
      dd = csr_satp_t'(d);
      ret.ppn = 28'b0; // RO field
      ret.reserved0 = '0; 
      ret.reserved1 = '0; 
      ret.mode = 4'b0; // RO field
      return ret;
   end
   endfunction

   function automatic csr_satp_t write_satp_non_reserved;
   input csr_satp_t d;
   csr_satp_t ret;
   begin
      ret.ppn = d.ppn;
      ret.reserved0 = '0; 
      ret.reserved1 = '0; 
      ret.mode = d.mode;
      return ret;
   end
   endfunction

   //conversion functions for csr_sie_t
   function automatic csr_sie_t write_sie;
   input [$bits(csr_sie_t)-1:0] d;
   csr_sie_t dd;
   csr_sie_t ret;
   begin
      dd = csr_sie_t'(d);
      ret.usie_reserved = '0; 
      ret.ssie = dd.ssie;
      ret.reserved0 = '0; 
      ret.utie_reserved = '0; 
      ret.stie = dd.stie;
      ret.reserved1 = '0; 
      ret.ueie_reserved = '0; 
      ret.seie = dd.seie;
      ret.reserved2 = '0; 
      return ret;
   end
   endfunction

   //conversion functions for csr_sip_t
   function automatic csr_sip_t write_sip;
   input [$bits(csr_sip_t)-1:0] d;
   csr_sip_t dd;
   csr_sip_t ret;
   begin
      dd = csr_sip_t'(d);
      ret.usip_reserved = '0; 
      ret.ssip = dd.ssip;
      ret.reserved0 = '0; 
      ret.utip_reserved = '0; 
      ret.stip = dd.stip;
      ret.reserved1 = '0; 
      ret.ueip_reserved = '0; 
      ret.seip = dd.seip;
      ret.reserved2 = '0; 
      return ret;
   end
   endfunction

   //conversion functions for csr_sstatus_t
   function automatic csr_sstatus_t write_sstatus;
   input [$bits(csr_sstatus_t)-1:0] d;
   csr_sstatus_t dd;
   csr_sstatus_t ret;
   begin
      dd = csr_sstatus_t'(d);
      ret.uie_reserved = '0; 
      ret.sie = dd.sie;
      ret.reserved0 = '0; 
      ret.upie_reserved = '0; 
      ret.spie = dd.spie;
      ret.reserved1 = '0; 
      ret.spp = dd.spp;
      ret.reserved2 = '0; 
      ret.fs = dd.fs;
      ret.xs = dd.xs;
      ret.reserved3 = '0; 
      ret.sum = 1'b0; // RO field
      ret.mxr = dd.mxr;
      ret.reserved4 = '0; 
      ret.uxl = dd.uxl;
      ret.reserved5 = '0; 
      ret.sd = dd.sd;
      return ret;
   end
   endfunction

   //conversion functions for csr_tdata1_t
   function automatic csr_tdata1_t write_tdata1;
   input [$bits(csr_tdata1_t)-1:0] d;
   csr_tdata1_t dd;
   csr_tdata1_t ret;
   begin
      dd = csr_tdata1_t'(d);
      ret.load = dd.load;
      ret.store = dd.store;
      ret.execute = dd.execute;
      ret.u = dd.u;
      ret.s = dd.s;
      ret.reserved0 = '0; 
      ret.m = dd.m;
      ret.match = dd.match;
      ret.match_msb_reserved = '0; 
      ret.chain_reserved = '0; 
      ret.action = dd.action;
      ret.action_msb_reserved = '0; 
      ret.timing = 'x; // RO field... needs to be set manually if used
      ret.select_reserved = '0; 
      ret.hit_reserved = '0; 
      ret.reserved1 = '0; 
      ret.maskmax = 6'h6; // RO field
      ret.dmode = dd.dmode;
      ret.ttype = 4'h2; // RO field
      return ret;
   end
   endfunction

   function automatic csr_tdata1_t write_tdata1_non_reserved;
   input csr_tdata1_t d;
   csr_tdata1_t ret;
   begin
      ret.load = d.load;
      ret.store = d.store;
      ret.execute = d.execute;
      ret.u = d.u;
      ret.s = d.s;
      ret.reserved0 = '0; 
      ret.m = d.m;
      ret.match = d.match;
      ret.match_msb_reserved = '0; 
      ret.chain_reserved = '0; 
      ret.action = d.action;
      ret.action_msb_reserved = '0; 
      ret.timing = d.timing;
      ret.select_reserved = '0; 
      ret.hit_reserved = '0; 
      ret.reserved1 = '0; 
      ret.maskmax = d.maskmax;
      ret.dmode = d.dmode;
      ret.ttype = d.ttype;
      return ret;
   end
   endfunction

   //conversion functions for csr_tvec_t
   function automatic csr_tvec_t write_tvec;
   input [$bits(csr_tvec_t)-1:0] d;
   csr_tvec_t dd;
   csr_tvec_t ret;
   begin
      dd = csr_tvec_t'(d);
      ret.mode = dd.mode;
      ret.reserved0 = '0; 
      ret.base = dd.base;
      return ret;
   end
   endfunction

   function automatic csr_tvec_t write_tvec_non_reserved;
   input csr_tvec_t d;
   csr_tvec_t ret;
   begin
      ret.mode = d.mode;
      ret.reserved0 = '0; 
      ret.base = d.base;
      return ret;
   end
   endfunction
// END autogenerated TYPE_CONVERSIONS
//////////////////////////////////////////////////////////////////////
