#!/usr/bin/env python3
# Copyright (c) 2026 Ainekko
# SPDX-License-Identifier: Apache-2.0

import sys
import os
from shutil import copyfile

if "RTLROOT" not in os.environ:
    raise Exception( "RTLROOT not set" )
rtlroot= os.environ['RTLROOT']
sys.path.append(rtlroot + '/shire/scripts')
from CsrFile import CsrFile
from XsrType import XsrType
from XsrFileIO import printToFile, replaceInFile, mkdir_p

# make copy of old files
dstDirRTL=rtlroot + '/shire/minion/intpipe/csr/'
dstDirDEF =rtlroot + '/inc/'
fileRTL = dstDirRTL + 'intpipe_csr_file_auto.v'
fileDEF = dstDirDEF + 'csr_defines_auto.vh'
fileTYPES = dstDirDEF + 'csr_types_auto.vh'

for f in [fileRTL, fileDEF, fileTYPES]:
    copyfile( f, f + '.old')

# generate code

if "FROM_GDOCS" in os.environ:
    fromGdocs = os.environ['FROM_GDOCS'] != "0"
else:
    fromGdocs = False

c = CsrFile(fromGdocs);

# for intpipe_csr_file_auto.v
labelsRTL = ['DECLARATIONS', 'READ_AND_DECODE_COMB_DEFAULT',  'READ_AND_DECODE_COMB_CASES', 
          'READ_AND_DECODE_SEQ', 'WRITE_COMB_DEFAULT', 'WRITE_CORE_COMB', 
          'WRITE_SEQ',  'TYPE_CONVERSIONS']
code = []

code.append(c.declarations())
code.extend(c.readAndDecodeProc([False,True,False]))
code.append(c.writeCombDefault(True))
code.append(c.writeCoreComb(True))
code.append(c.writeSeq())
code.append(XsrType.allConversions())

for contents, lab in zip(code, labelsRTL):
    replaceInFile( fileRTL, contents, 'BEGIN autogenerated ' + lab, 'END autogenerated ' + lab, False)


# code for csr_types_auto.vh
labelsDEF = ['TYPE_DEFINITIONS', 'CSR_AD_DEFINITIONS']
code = []

code.append(XsrType.allDefinitions())
code.append(c.addressDefinitions())

for contents, lab in zip(code, labelsDEF):
    replaceInFile( fileTYPES, contents, 'BEGIN autogenerated ' + lab, 'END autogenerated ' + lab)
