# Copyright (c) 2026 Ainekko
# SPDX-License-Identifier: Apache-2.0

import sys
import os
import re
import datetime
from shutil import copyfile

if "REPOROOT" not in os.environ:
	raise Exception ( "REPOROOT not set" )
sysroot = os.environ['REPOROOT']
sys.path.append(sysroot + '/rtl/shire/scripts')
sys.path.append(sysroot + '/rtl/shire/minion/intpipe/csr/scripts')

from CsrFile import CsrFile

OUT_SVH = os.environ['REPOROOT']+"/dv/minion_common/cov/minion_core_intpipe_csr_auto_cvg.svh"
my_path = os.path.realpath(__file__)
my_date = datetime.datetime.now()

if __name__ == "__main__":
	c = CsrFile()
	csr_dict = c.getCsrDv()

	deprio_csrs=[line.rstrip("\n") for line in open("deprioritized_csrs.data")]
    #backup old file
	copyfile(OUT_SVH, OUT_SVH + ".old")

	#start generating coverage
	cg_list=[]
	with open (OUT_SVH, "w") as f:
		f.write ("// !====================================!\n")
		f.write ("// !                                    !\n")
		f.write ("// !   THIS IS AN AUTO-GENERATED FILE   !\n")
		f.write ("// !                                    !\n")
		f.write ("// !       /!\ DO NOT EDIT /!\          !\n")
		f.write ("// !                                    !\n")
		f.write ("// !====================================!\n")
		f.write ("//\n")
		f.write ("// Generated by " + my_path + " on " + my_date.strftime('%Y/%m/%d %H:%M:%S') + "\n")
		f.write ("//\n")
		
		cg_name = "cg_csr"
		f.write ("\tcovergroup "+ cg_name + " with function sample (logic [11:0] io_rw_mem_addr, logic io_rw_mem_valid_qual, logic [2:0] io_rw_mem_cmd, logic [1:0] prv_0, logic [1:0] prv_1, logic mem_thread_id);"+"\n")
		f.write ("\t\toption.per_instance         = 0;"+"\n")
		f.write ("\t\ttype_option.merge_instances = 1;"+"\n\n")
		cg_list.append(cg_name)

		# CSR all addr coverpoint
		f.write("\t\tcp_csr_addr: coverpoint io_rw_mem_addr iff (io_rw_mem_valid_qual) {"+"\n")
		for csr_name, csr_data in sorted(csr_dict.items()):
			csr_len = len(csr_name)
			fllr = 30 - csr_len
			if (csr_name in deprio_csrs):
				 continue 
			else:
				f.write("\t\t\tbins addr_"+csr_name+ fllr*" " +" = {12'h"+'{:x}'.format(csr_data['address'])+"};"+"\n")
		#f.write("\t\t\tbins addr_illegal = default;\n")
		f.write("\t\t}"+"\n")

		#CSR R/O addr coverpoint
		f.write("\t\tcp_csr_addr_ro: coverpoint io_rw_mem_addr iff (io_rw_mem_valid_qual) {"+"\n")
		for csr_name, csr_data in sorted(csr_dict.items()):
			if (csr_name in deprio_csrs):
				continue	
			else:
				if (csr_data['access']=="RO" or csr_data['access']=="RO-HWIRED"):
					csr_len = len(csr_name)
					fllr = 30 - csr_len
					f.write("\t\t\tbins addr_"+csr_name+ fllr*" " +" = {12'h"+'{:x}'.format(csr_data['address'])+"};"+"\n")
		f.write("\t\t}"+"\n")

		#CSR R/W addr coverpoint
		f.write("\t\tcp_csr_addr_rw: coverpoint io_rw_mem_addr iff (io_rw_mem_valid_qual) {"+"\n")
		for csr_name, csr_data in sorted(csr_dict.items()):
			if (csr_name in deprio_csrs):
				continue
			else:
				if (csr_data['access']=="RW" or csr_data['access']=="RW-HWIRED"):
					csr_len = len(csr_name)
					fllr = 30 - csr_len
					f.write("\t\t\tbins addr_"+csr_name+ fllr*" " +" = {12'h"+'{:x}'.format(csr_data['address'])+"};"+"\n")
		f.write("\t\t}"+"\n")
			

		# CSR read/write coverpoint
		f.write("\t\tcp_csr_read_write: coverpoint io_rw_mem_cmd iff (io_rw_mem_valid_qual) {"+"\n")
		f.write("\t\t\tbins read  = {3'h5};\n")	
		f.write("\t\t\tbins write = {3'h1};\n")
		f.write("\t\t}\n")

		# CSR priviledge mode coverpoint th0
		f.write("\t\tcp_csr_prv_th0: coverpoint prv_0 iff (io_rw_mem_valid_qual && mem_thread_id == 0) {\n")
		f.write("\t\t\tbins machine    = {2'b11};\n")
		f.write("\t\t\tbins supervisor = {2'b01};\n")
		f.write("\t\t\tbins user       = {2'b00};\n")
		f.write("\t\t}\n")

		# CSR priviledge mode coverpoint th1
		f.write("\t\tcp_csr_prv_th1: coverpoint prv_1 iff (io_rw_mem_valid_qual && mem_thread_id == 1) {\n")
		f.write("\t\t\tbins machine    = {2'b11};\n")
		f.write("\t\t\tbins supervisor = {2'b01};\n")
		f.write("\t\t\tbins user       = {2'b00};\n")
		f.write("\t\t}\n\n")

		# CSR thread Id
		#f.write("\t\tcp_csr_thread_id: coverpoint mem_thread_id iff (io_rw_mem_valid_qual) {\n")
		#f.write("\t\t\tbins thread_0  = {1'b0};\n")
		#f.write("\t\t\tbins thread_1  = {1'b1};\n")
		#f.write("\t\t}\n")

		f.write("\t\tcross_csr_addr_prv_th0: cross cp_csr_addr,cp_csr_prv_th0;\n")
		f.write("\t\tcross_csr_addr_prv_th1: cross cp_csr_addr,cp_csr_prv_th1;\n")
		f.write("\t\tcross_csr_addr_rw_read_write: cross cp_csr_addr_rw, cp_csr_read_write;\n")
		f.write("\n")

		f.write("\tendgroup : "+ cg_name +"\n\n")
		
