// Copyright (c) 2026 Ainekko
// SPDX-License-Identifier: Apache-2.0

module esr_spio #(
  parameter int unsigned AdWidth = esr_pkg::EsrSpioApbPpAddrWidth,
  /* verilator lint_off UNUSEDPARAM */  // Preserved original module parameters; SPIO ESR logic itself does not consume cache geometry.
  parameter int unsigned SetsPerSubBank = shirecache_pkg::SetsPerSubBank,
  parameter int unsigned NumReqqEntries = shirecache_pkg::ReqqDepth
  /* verilator lint_on UNUSEDPARAM */
) (
  input  logic                        clk_i,
  input  logic                        rst_c_ni,
  /* verilator lint_off UNUSEDSIGNAL */  // Original shell exposes all three reset domains even though SPIO only stores state in the debug-reset domain.
  input  logic                        rst_w_ni,
  /* verilator lint_on UNUSEDSIGNAL */
  input  logic                        rst_d_ni,
  /* verilator lint_off UNUSEDSIGNAL */  // Test-enable port is preserved for standalone_minion parity; this translated block has no latch/gated-clock ESR sites.
  input  logic                        test_en_i,
  /* verilator lint_on UNUSEDSIGNAL */

  output esr_pkg::esr_spdmctrl_t      esr_spdmctrl_o,
  input  minion_pkg::minion_debug_out_t svcproc_dbg_status_i,
  output esr_pkg::esr_sphastatus_t    esr_sphastatus_o,
  input  logic                        spio_rc_resumeack_i,

  input  logic [AdWidth-1:0]          apb_paddr_i,
  input  logic                        apb_pwrite_i,
  input  logic                        apb_psel_i,
  input  logic                        apb_penable_i,
  input  logic [63:0]                 apb_pwdata_i,
  output logic                        apb_pready_o,
  output logic [63:0]                 apb_prdata_o,
  output logic                        apb_pslverr_o
);
  import esr_pkg::*;

  logic            s0_en;
  logic            s0_addr_valid_d;
  logic [63:0]     s0_rdata_d;

  logic            s1_en;
  logic            s1_addr_valid_q;
  logic [63:0]     s1_rdata_q;
  logic [63:0]     s1_wdata_q;

  logic            reg_spdmctrl_en_q;
  logic            reg_spdmctrl_en_d;
  logic            reg_sphastatus_en_q;
  logic            reg_sphastatus_en_d;

  localparam logic [AdWidth-1:0] AddrSpdmctrl   = 4'hA;
  localparam logic [AdWidth-1:0] AddrSphastatus = 4'hB;

  esr_spdmctrl_t   reg_spdmctrl_q;
  esr_spdmctrl_t   reg_spdmctrl_d;
  esr_sphastatus_t reg_sphastatus_q;
  esr_sphastatus_t reg_sphastatus_d;

  esr_sphastatus_t read_sphastatus;
  esr_spdmctrl_t   read_spdmctrl;

  /* verilator lint_off UNUSEDSIGNAL */  // These helpers intentionally discard read-only and reserved APB bits, matching the original autogenerated write-conversion functions.
  function automatic esr_spdmctrl_t write_spdmctrl(input logic [63:0] d);
    esr_spdmctrl_t ret;
    begin
      ret = '0;
      ret.ndmreset         = d[1];
      ret.clrresethaltreq  = d[2];
      ret.setresethaltreq  = d[3];
      ret.ackhavereset     = d[28];
      ret.hartreset        = d[29];
      ret.resumereq        = d[30];
      ret.haltreq          = d[31];
      return ret;
    end
  endfunction

  function automatic esr_sphastatus_t write_sphastatus(input logic [63:0] d);
    esr_sphastatus_t ret;
    begin
      ret = '0;
      ret.reserved  = d[63:7];
      ret.error     = d[6];
      ret.exception = d[5];
      return ret;
    end
  endfunction
  /* verilator lint_on UNUSEDSIGNAL */

  always_comb begin
    read_sphastatus = reg_sphastatus_q;
    read_sphastatus.reserved  = '0;
    read_sphastatus.busy      = svcproc_dbg_status_i.busy[0];
    read_sphastatus.havereset = svcproc_dbg_status_i.have_reset[0];
    read_sphastatus.resumeack = spio_rc_resumeack_i;
    read_sphastatus.running   = svcproc_dbg_status_i.running[0];
    read_sphastatus.halted    = svcproc_dbg_status_i.halted[0];

    read_spdmctrl = reg_spdmctrl_q;
    read_spdmctrl.clrresethaltreq = '0;
    read_spdmctrl.setresethaltreq = '0;
    read_spdmctrl.reserved0       = '0;
    read_spdmctrl.reserved1       = '0;
    read_spdmctrl.reserved2       = '0;
    read_spdmctrl.ackhavereset    = '0;
    read_spdmctrl.resumereq       = '0;
    read_spdmctrl.haltreq         = '0;
  end

  always_comb begin
    s0_en = apb_psel_i && !apb_penable_i;
    s0_addr_valid_d = 1'b1;
    s0_rdata_d = '0;
    reg_spdmctrl_en_d = 1'b0;
    reg_sphastatus_en_d = 1'b0;

    if (s0_en) begin
      unique case (apb_paddr_i)
        AddrSpdmctrl: begin
          s0_addr_valid_d = 1'b1;
          reg_spdmctrl_en_d = apb_pwrite_i;
          s0_rdata_d = read_spdmctrl;
        end
        AddrSphastatus: begin
          s0_addr_valid_d = 1'b1;
          reg_sphastatus_en_d = apb_pwrite_i;
          s0_rdata_d = read_sphastatus;
        end
        default: begin
          s0_addr_valid_d = 1'b0;
        end
      endcase
    end
  end

  assign s1_en = apb_psel_i && apb_penable_i;

  always_comb begin
    reg_spdmctrl_d = reg_spdmctrl_q;
    reg_sphastatus_d = reg_sphastatus_q;

    if (reg_spdmctrl_en_q) begin
      reg_spdmctrl_d = write_spdmctrl(s1_wdata_q);
    end

    if (reg_sphastatus_en_q) begin
      reg_sphastatus_d = write_sphastatus(apb_pwdata_i);
    end

    reg_spdmctrl_d.reserved0 = '0;
    reg_spdmctrl_d.reserved1 = '0;
    reg_spdmctrl_d.reserved2 = '0;

    if (!reg_spdmctrl_en_q) begin
      reg_spdmctrl_d.clrresethaltreq = 1'b0;
      reg_spdmctrl_d.setresethaltreq = 1'b0;
      reg_spdmctrl_d.ackhavereset    = 1'b0;
      reg_spdmctrl_d.resumereq       = 1'b0;
    end

    if (svcproc_dbg_status_i.error[0]) begin
      reg_sphastatus_d.error = 1'b1;
    end else if (s1_en && !apb_pwdata_i[6] && (apb_paddr_i == AddrSphastatus)) begin
      reg_sphastatus_d.error = 1'b0;
    end

    if (svcproc_dbg_status_i.exception[0]) begin
      reg_sphastatus_d.exception = 1'b1;
    end else if (s1_en && !apb_pwdata_i[5] && (apb_paddr_i == AddrSphastatus)) begin
      reg_sphastatus_d.exception = 1'b0;
    end

    reg_sphastatus_d.havereset = svcproc_dbg_status_i.have_reset[0];
    reg_sphastatus_d.busy      = svcproc_dbg_status_i.busy[0];
    reg_sphastatus_d.resumeack = spio_rc_resumeack_i;
    reg_sphastatus_d.running   = svcproc_dbg_status_i.running[0];
    reg_sphastatus_d.halted    = svcproc_dbg_status_i.halted[0];
  end

  always_ff @(posedge clk_i) begin
    if (s0_en && apb_pwrite_i) begin
      s1_wdata_q <= apb_pwdata_i;
    end
    if (s0_en && !apb_pwrite_i) begin
      s1_rdata_q <= s0_rdata_d;
    end
  end

  always_ff @(posedge clk_i or negedge rst_c_ni) begin
    if (!rst_c_ni) begin
      s1_addr_valid_q  <= 1'b0;
      reg_spdmctrl_en_q <= 1'b0;
      reg_sphastatus_en_q <= 1'b0;
    end else begin
      if (s0_en) begin
        s1_addr_valid_q <= s0_addr_valid_d;
      end
      if (s0_en || s1_en) begin
        reg_spdmctrl_en_q  <= reg_spdmctrl_en_d;
        reg_sphastatus_en_q <= reg_sphastatus_en_d;
      end
    end
  end

  always_ff @(posedge clk_i or negedge rst_d_ni) begin
    if (!rst_d_ni) begin
      reg_spdmctrl_q  <= '0;
      reg_sphastatus_q <= '0;
    end else begin
      reg_spdmctrl_q  <= reg_spdmctrl_d;
      reg_sphastatus_q <= reg_sphastatus_d;
    end
  end

  assign apb_prdata_o  = s1_rdata_q;
  assign apb_pslverr_o = !s1_addr_valid_q;
  assign apb_pready_o  = 1'b1;

  assign esr_spdmctrl_o   = reg_spdmctrl_q;
  assign esr_sphastatus_o = read_sphastatus;
endmodule
