// Copyright (c) 2026 Ainekko
// SPDX-License-Identifier: Apache-2.0

// Native shire_top cosim wrapper.  The new side instantiates the project
// shire_top through the same observation wrapper used by unit smoke DV.  The
// original side instantiates a retained original-source top-wiring adapter
// documented in orig_shire_top_retained_slice.sv; the full original public top
// includes removed third-party/generated surfaces and is intentionally not
// recreated.

/* verilator lint_off UNUSEDSIGNAL */  // Cosim intentionally observes a directed retained native subset.
module cosim_shire_top_tb
  import axi_pkg::*;
  import shire_channel_leaves_pkg::*;
  import shire_esr_pkg::*;
  import shire_sbm_pkg::*;
  import shire_uncached_pkg::*;
  import neigh_ch_apb_mux_pkg::*;
  import ram_cfg_pkg::*;
  import dft_pkg::*;
(
  input  logic clk_i,
  input  logic rst_ni,

  input  logic rst_cold_ext_ni,
  input  logic rst_warm_ext_ni,
  input  logic rst_system_ext_ni,
  input  logic rst_system_debug_ext_ni,
  input  logic rst_noc_ext_ni,

  input  logic dft_scanmode_i,
  input  logic dft_scan_reset_ni,
  input  logic dft_sram_clk_i,
  input  logic dft_sram_clk_override_i,
  input  logic dft_ram_rei_i,
  input  logic dft_ram_wei_i,
  input  logic dft_mbist_en_i,

  input  logic [shire_esr_pkg::NumShireIdsBits-1:0] shire_id_reset_val_i,
  input  logic [shire_esr_pkg::NumShireIdsBits-1:0] shire_phy_id_i,
  input  logic plic_mtip_i,
  input  logic plic_meip_i,
  input  logic plic_seip_i,
  input  logic [shire_channel_leaves_pkg::NocIntNum-1:0] noc_err_int_srcs_i,
  input  logic [shirecache_pkg::BankIdSize-1:0] status_monitor_bank_sel_stim_i,
  input  logic [$bits(shire_channel_leaves_pkg::esr_and_or_tree_l2_t)-1:0]
      debug_and_or_tree_l2_stim_i,

  input  logic sys_axi_ar_valid_stim_i,
  input  logic sys_axi_aw_valid_stim_i,
  input  logic sys_axi_w_valid_stim_i,
  input  logic sys_axi_b_ready_stim_i,
  input  logic sys_axi_r_ready_stim_i,
  input  logic [1:0] sys_axi_aw_vcvalid_stim_i,
  input  logic [1:0] sys_axi_w_vcvalid_stim_i,
  input  logic [axi_pkg::ScSlaveIdSize-1:0] sys_id_stim_i,
  input  logic [axi_pkg::ScMasterAddrSize-1:0] sys_addr_stim_i,
  input  logic [axi_pkg::SysSlaveDataSize-1:0] sys_wdata_stim_i,
  input  logic [7:0] sys_len_stim_i,
  input  logic [2:0] sys_size_stim_i,

  output logic [shire_esr_pkg::NumNeigh-1:0] orig_rst_c_shire_no_o,
  output logic [shire_esr_pkg::NumNeigh-1:0] new_rst_c_shire_no_o,
  output logic [shire_esr_pkg::NumNeigh-1:0] orig_rst_w_shire_no_o,
  output logic [shire_esr_pkg::NumNeigh-1:0] new_rst_w_shire_no_o,
  output logic [shire_esr_pkg::NumNeigh-1:0] orig_rst_d_shire_no_o,
  output logic [shire_esr_pkg::NumNeigh-1:0] new_rst_d_shire_no_o,
  output logic [shire_esr_pkg::NumNeigh-1:0] orig_rst_warm_to_neigh_no_o,
  output logic [shire_esr_pkg::NumNeigh-1:0] new_rst_warm_to_neigh_no_o,
  output logic [shire_esr_pkg::NumNeigh-1:0] orig_rst_w_icache_no_o,
  output logic [shire_esr_pkg::NumNeigh-1:0] new_rst_w_icache_no_o,
  output logic orig_rst_system_lv_no_o,
  output logic new_rst_system_lv_no_o,
  output logic orig_rst_system_debug_lv_no_o,
  output logic new_rst_system_debug_lv_no_o,
  output logic orig_rst_noc_lv_no_o,
  output logic new_rst_noc_lv_no_o,
  output logic [shire_esr_pkg::NumNeigh-1:0] orig_clk_neigh_obs_o,
  output logic [shire_esr_pkg::NumNeigh-1:0] new_clk_neigh_obs_o,
  output logic orig_clk_shire_obs_o,
  output logic new_clk_shire_obs_o,
  output logic [shire_esr_pkg::NumNeigh-1:0][shire_esr_pkg::NumShireIdsBits-1:0]
      orig_shire_id_o,
  output logic [shire_esr_pkg::NumNeigh-1:0][shire_esr_pkg::NumShireIdsBits-1:0]
      new_shire_id_o,
  output logic [shire_esr_pkg::TboxPerShire-1:0][1:0] orig_tbox_id_o,
  output logic [shire_esr_pkg::TboxPerShire-1:0][1:0] new_tbox_id_o,
  output logic [shire_esr_pkg::TboxPerShire-1:0] orig_tbox_en_o,
  output logic [shire_esr_pkg::TboxPerShire-1:0] new_tbox_en_o,
  output logic [shire_esr_pkg::NumNeigh-1:0] orig_plic_meip_to_neigh_o,
  output logic [shire_esr_pkg::NumNeigh-1:0] new_plic_meip_to_neigh_o,
  output logic [shire_esr_pkg::NumNeigh-1:0] orig_plic_seip_to_neigh_o,
  output logic [shire_esr_pkg::NumNeigh-1:0] new_plic_seip_to_neigh_o,
  output logic [shire_esr_pkg::ThreadsPerShire-1:0] orig_int_mtip_flat_o,
  output logic [shire_esr_pkg::ThreadsPerShire-1:0] new_int_mtip_flat_o,
  output logic [shire_esr_pkg::NumNeigh-1:0] orig_apb_neigh_psel_o,
  output logic [shire_esr_pkg::NumNeigh-1:0] new_apb_neigh_psel_o,
  output logic [shire_esr_pkg::NumNeigh-1:0] orig_apb_neigh_pwrite_o,
  output logic [shire_esr_pkg::NumNeigh-1:0] new_apb_neigh_pwrite_o,
  output logic [neigh_ch_apb_mux_pkg::NeighDmApbAddrWidth-1:0] orig_apb_neigh0_paddr_o,
  output logic [neigh_ch_apb_mux_pkg::NeighDmApbAddrWidth-1:0] new_apb_neigh0_paddr_o,
  output logic [shire_sbm_pkg::ApbDataWidth-1:0] orig_apb_neigh0_pwdata_o,
  output logic [shire_sbm_pkg::ApbDataWidth-1:0] new_apb_neigh0_pwdata_o,
  output logic [shirecache_pkg::Banks+shirecache_pkg::RboxPerShire+2-1:0] orig_apb_channel_psel_o,
  output logic [shirecache_pkg::Banks+shirecache_pkg::RboxPerShire+2-1:0] new_apb_channel_psel_o,
  output logic [shirecache_pkg::Banks+shirecache_pkg::RboxPerShire+2-1:0]
      orig_apb_channel_pwrite_o,
  output logic [shirecache_pkg::Banks+shirecache_pkg::RboxPerShire+2-1:0]
      new_apb_channel_pwrite_o,
  output logic [shire_esr_pkg::NumNeigh-1:0][shirecache_pkg::Banks:0] orig_neigh_sc_req_ready_o,
  output logic [shire_esr_pkg::NumNeigh-1:0][shirecache_pkg::Banks:0] new_neigh_sc_req_ready_o,
  output logic [shire_esr_pkg::NumNeigh-1:0] orig_neigh_sc_rsp_valid_o,
  output logic [shire_esr_pkg::NumNeigh-1:0] new_neigh_sc_rsp_valid_o,
  output logic [shire_esr_pkg::NumNeigh-1:0] orig_icache_req_ready_o,
  output logic [shire_esr_pkg::NumNeigh-1:0] new_icache_req_ready_o,
  output logic [shire_esr_pkg::NumNeigh-1:0] orig_icache_resp_valid_o,
  output logic [shire_esr_pkg::NumNeigh-1:0] new_icache_resp_valid_o,
  output logic [shire_esr_pkg::NumNeigh-1:0] orig_flb_l2_neigh_resp_valid_o,
  output logic [shire_esr_pkg::NumNeigh-1:0] new_flb_l2_neigh_resp_valid_o,
  output logic [shire_esr_pkg::NumNeigh-1:0] orig_flb_l2_neigh_resp_data_o,
  output logic [shire_esr_pkg::NumNeigh-1:0] new_flb_l2_neigh_resp_data_o,
  output logic [shire_esr_pkg::NumNeigh-1:0][shire_uncached_pkg::MinPerNeigh-1:0]
      orig_uc_to_neigh_fcc_o,
  output logic [shire_esr_pkg::NumNeigh-1:0][shire_uncached_pkg::MinPerNeigh-1:0]
      new_uc_to_neigh_fcc_o,
  output logic [shire_esr_pkg::NumNeigh-1:0][shire_uncached_pkg::UcFccTargetSize-1:0]
      orig_uc_to_neigh_fcc_target_o,
  output logic [shire_esr_pkg::NumNeigh-1:0][shire_uncached_pkg::UcFccTargetSize-1:0]
      new_uc_to_neigh_fcc_target_o,
  output logic [shire_esr_pkg::NumNeigh-1:0] orig_pwr_ctrl_glb_nsleepin_o,
  output logic [shire_esr_pkg::NumNeigh-1:0] new_pwr_ctrl_glb_nsleepin_o,
  output logic [shire_esr_pkg::NumNeigh-1:0] orig_pwr_ctrl_glb_iso_o,
  output logic [shire_esr_pkg::NumNeigh-1:0] new_pwr_ctrl_glb_iso_o,
  output logic [shire_esr_pkg::NumNeigh*shire_esr_pkg::MinPerNeigh-1:0]
      orig_pwr_ctrl_neigh_nsleepin_o,
  output logic [shire_esr_pkg::NumNeigh*shire_esr_pkg::MinPerNeigh-1:0]
      new_pwr_ctrl_neigh_nsleepin_o,
  output logic [shire_esr_pkg::NumNeigh*shire_esr_pkg::MinPerNeigh-1:0]
      orig_pwr_ctrl_neigh_iso_o,
  output logic [shire_esr_pkg::NumNeigh*shire_esr_pkg::MinPerNeigh-1:0]
      new_pwr_ctrl_neigh_iso_o,
  output logic [$bits(ram_cfg_pkg::ram_cfg_t)-1:0] orig_ram_cfg_flat_o,
  output logic [$bits(ram_cfg_pkg::ram_cfg_t)-1:0] new_ram_cfg_flat_o,
  output logic [$bits(dft_pkg::dft_t)-1:0] orig_dft_hv_flat_o,
  output logic [$bits(dft_pkg::dft_t)-1:0] new_dft_hv_flat_o,
  output logic [$bits(shire_channel_leaves_pkg::esr_and_or_tree_l2_t)-1:0]
      orig_debug_and_or_tree_l2_flat_o,
  output logic [$bits(shire_channel_leaves_pkg::esr_and_or_tree_l2_t)-1:0]
      new_debug_and_or_tree_l2_flat_o,
  output logic orig_ioshire_combined_err_int_o,
  output logic new_ioshire_combined_err_int_o,
  output logic orig_ioshire_noc_err_int_o,
  output logic new_ioshire_noc_err_int_o,
  output logic [shire_channel_leaves_pkg::NocIntNum-1:0] orig_noc_all_err_int_srcs_o,
  output logic [shire_channel_leaves_pkg::NocIntNum-1:0] new_noc_all_err_int_srcs_o,
  output logic [shire_esr_pkg::NumNeigh-1:0][shire_esr_pkg::NumNeigh-2:0] orig_coop_slv_valid_o,
  output logic [shire_esr_pkg::NumNeigh-1:0][shire_esr_pkg::NumNeigh-2:0] new_coop_slv_valid_o,
  output logic [shire_esr_pkg::NumNeigh-1:0][shire_esr_pkg::NumNeigh-2:0] orig_coop_done_valid_o,
  output logic [shire_esr_pkg::NumNeigh-1:0][shire_esr_pkg::NumNeigh-2:0] new_coop_done_valid_o,
  output logic orig_sys_axi_ar_ready_obs_o,
  output logic new_sys_axi_ar_ready_obs_o,
  output logic orig_sys_axi_aw_ready_obs_o,
  output logic new_sys_axi_aw_ready_obs_o,
  output logic orig_sys_axi_w_ready_obs_o,
  output logic new_sys_axi_w_ready_obs_o,
  output logic orig_sys_axi_b_valid_obs_o,
  output logic new_sys_axi_b_valid_obs_o,
  output logic [axi_pkg::ScSlaveIdSize-1:0] orig_sys_axi_b_id_obs_o,
  output logic [axi_pkg::ScSlaveIdSize-1:0] new_sys_axi_b_id_obs_o,
  output logic [1:0] orig_sys_axi_b_resp_obs_o,
  output logic [1:0] new_sys_axi_b_resp_obs_o,
  output logic orig_sys_axi_r_valid_obs_o,
  output logic new_sys_axi_r_valid_obs_o,
  output logic [63:0] orig_sys_axi_r_data_lo_obs_o,
  output logic [63:0] new_sys_axi_r_data_lo_obs_o,
  output logic [1:0] orig_sys_axi_aw_credit_obs_o,
  output logic [1:0] new_sys_axi_aw_credit_obs_o
);

  shire_top_tb u_new (
    .clk_i,
    .rst_ni,
    .rst_cold_ext_ni,
    .rst_warm_ext_ni,
    .rst_system_ext_ni,
    .rst_system_debug_ext_ni,
    .rst_noc_ext_ni,
    .dft_scanmode_i,
    .dft_scan_reset_ni,
    .dft_sram_clk_i,
    .dft_sram_clk_override_i,
    .dft_ram_rei_i,
    .dft_ram_wei_i,
    .dft_mbist_en_i,
    .shire_id_reset_val_i,
    .shire_phy_id_i,
    .plic_mtip_i,
    .plic_meip_i,
    .plic_seip_i,
    .noc_err_int_srcs_i,
    .status_monitor_bank_sel_stim_i,
    .debug_and_or_tree_l2_stim_i,
    .sys_axi_ar_valid_stim_i,
    .sys_axi_aw_valid_stim_i,
    .sys_axi_w_valid_stim_i,
    .sys_axi_b_ready_stim_i,
    .sys_axi_r_ready_stim_i,
    .sys_axi_aw_vcvalid_stim_i,
    .sys_axi_w_vcvalid_stim_i,
    .sys_id_stim_i,
    .sys_addr_stim_i,
    .sys_wdata_stim_i,
    .sys_len_stim_i,
    .sys_size_stim_i,
    .rst_c_shire_no_o            (new_rst_c_shire_no_o),
    .rst_w_shire_no_o            (new_rst_w_shire_no_o),
    .rst_d_shire_no_o            (new_rst_d_shire_no_o),
    .rst_warm_to_neigh_no_o      (new_rst_warm_to_neigh_no_o),
    .rst_w_icache_no_o           (new_rst_w_icache_no_o),
    .rst_system_lv_no_o          (new_rst_system_lv_no_o),
    .rst_system_debug_lv_no_o    (new_rst_system_debug_lv_no_o),
    .rst_noc_lv_no_o             (new_rst_noc_lv_no_o),
    .clk_neigh_obs_o             (new_clk_neigh_obs_o),
    .clk_shire_obs_o             (new_clk_shire_obs_o),
    .shire_id_o                  (new_shire_id_o),
    .tbox_id_o                   (new_tbox_id_o),
    .tbox_en_o                   (new_tbox_en_o),
    .plic_meip_to_neigh_o        (new_plic_meip_to_neigh_o),
    .plic_seip_to_neigh_o        (new_plic_seip_to_neigh_o),
    .int_mtip_flat_o             (new_int_mtip_flat_o),
    .apb_neigh_psel_o            (new_apb_neigh_psel_o),
    .apb_neigh_pwrite_o          (new_apb_neigh_pwrite_o),
    .apb_neigh0_paddr_o          (new_apb_neigh0_paddr_o),
    .apb_neigh0_pwdata_o         (new_apb_neigh0_pwdata_o),
    .apb_channel_psel_o          (new_apb_channel_psel_o),
    .apb_channel_pwrite_o        (new_apb_channel_pwrite_o),
    .neigh_sc_req_ready_o        (new_neigh_sc_req_ready_o),
    .neigh_sc_rsp_valid_o        (new_neigh_sc_rsp_valid_o),
    .icache_req_ready_o          (new_icache_req_ready_o),
    .icache_resp_valid_o         (new_icache_resp_valid_o),
    .flb_l2_neigh_resp_valid_o   (new_flb_l2_neigh_resp_valid_o),
    .flb_l2_neigh_resp_data_o    (new_flb_l2_neigh_resp_data_o),
    .uc_to_neigh_fcc_o           (new_uc_to_neigh_fcc_o),
    .uc_to_neigh_fcc_target_o    (new_uc_to_neigh_fcc_target_o),
    .pwr_ctrl_glb_nsleepin_o     (new_pwr_ctrl_glb_nsleepin_o),
    .pwr_ctrl_glb_iso_o          (new_pwr_ctrl_glb_iso_o),
    .pwr_ctrl_neigh_nsleepin_o   (new_pwr_ctrl_neigh_nsleepin_o),
    .pwr_ctrl_neigh_iso_o        (new_pwr_ctrl_neigh_iso_o),
    .ram_cfg_flat_o              (new_ram_cfg_flat_o),
    .dft_hv_flat_o               (new_dft_hv_flat_o),
    .debug_and_or_tree_l2_flat_o (new_debug_and_or_tree_l2_flat_o),
    .ioshire_combined_err_int_o  (new_ioshire_combined_err_int_o),
    .ioshire_noc_err_int_o       (new_ioshire_noc_err_int_o),
    .noc_all_err_int_srcs_o      (new_noc_all_err_int_srcs_o),
    .coop_slv_valid_o            (new_coop_slv_valid_o),
    .coop_done_valid_o           (new_coop_done_valid_o),
    .sys_axi_ar_ready_obs_o      (new_sys_axi_ar_ready_obs_o),
    .sys_axi_aw_ready_obs_o      (new_sys_axi_aw_ready_obs_o),
    .sys_axi_w_ready_obs_o       (new_sys_axi_w_ready_obs_o),
    .sys_axi_b_valid_obs_o       (new_sys_axi_b_valid_obs_o),
    .sys_axi_b_id_obs_o          (new_sys_axi_b_id_obs_o),
    .sys_axi_b_resp_obs_o        (new_sys_axi_b_resp_obs_o),
    .sys_axi_r_valid_obs_o       (new_sys_axi_r_valid_obs_o),
    .sys_axi_r_data_lo_obs_o     (new_sys_axi_r_data_lo_obs_o),
    .sys_axi_aw_credit_obs_o     (new_sys_axi_aw_credit_obs_o)
  );

  orig_shire_top_retained_slice u_orig (
    .clk_i,
    .rst_ni,
    .rst_cold_ext_ni,
    .rst_warm_ext_ni,
    .rst_system_ext_ni,
    .rst_system_debug_ext_ni,
    .rst_noc_ext_ni,
    .dft_scanmode_i,
    .dft_scan_reset_ni,
    .dft_sram_clk_i,
    .dft_sram_clk_override_i,
    .dft_ram_rei_i,
    .dft_ram_wei_i,
    .dft_mbist_en_i,
    .shire_id_reset_val_i,
    .shire_phy_id_i,
    .plic_mtip_i,
    .plic_meip_i,
    .plic_seip_i,
    .noc_err_int_srcs_i,
    .status_monitor_bank_sel_stim_i,
    .debug_and_or_tree_l2_stim_i,
    .sys_axi_ar_valid_stim_i,
    .sys_axi_aw_valid_stim_i,
    .sys_axi_w_valid_stim_i,
    .sys_axi_b_ready_stim_i,
    .sys_axi_r_ready_stim_i,
    .sys_axi_aw_vcvalid_stim_i,
    .sys_axi_w_vcvalid_stim_i,
    .sys_id_stim_i,
    .sys_addr_stim_i,
    .sys_wdata_stim_i,
    .sys_len_stim_i,
    .sys_size_stim_i,
    .rst_c_shire_no_o            (orig_rst_c_shire_no_o),
    .rst_w_shire_no_o            (orig_rst_w_shire_no_o),
    .rst_d_shire_no_o            (orig_rst_d_shire_no_o),
    .rst_warm_to_neigh_no_o      (orig_rst_warm_to_neigh_no_o),
    .rst_w_icache_no_o           (orig_rst_w_icache_no_o),
    .rst_system_lv_no_o          (orig_rst_system_lv_no_o),
    .rst_system_debug_lv_no_o    (orig_rst_system_debug_lv_no_o),
    .rst_noc_lv_no_o             (orig_rst_noc_lv_no_o),
    .clk_neigh_obs_o             (orig_clk_neigh_obs_o),
    .clk_shire_obs_o             (orig_clk_shire_obs_o),
    .shire_id_o                  (orig_shire_id_o),
    .tbox_id_o                   (orig_tbox_id_o),
    .tbox_en_o                   (orig_tbox_en_o),
    .plic_meip_to_neigh_o        (orig_plic_meip_to_neigh_o),
    .plic_seip_to_neigh_o        (orig_plic_seip_to_neigh_o),
    .int_mtip_flat_o             (orig_int_mtip_flat_o),
    .apb_neigh_psel_o            (orig_apb_neigh_psel_o),
    .apb_neigh_pwrite_o          (orig_apb_neigh_pwrite_o),
    .apb_neigh0_paddr_o          (orig_apb_neigh0_paddr_o),
    .apb_neigh0_pwdata_o         (orig_apb_neigh0_pwdata_o),
    .apb_channel_psel_o          (orig_apb_channel_psel_o),
    .apb_channel_pwrite_o        (orig_apb_channel_pwrite_o),
    .neigh_sc_req_ready_o        (orig_neigh_sc_req_ready_o),
    .neigh_sc_rsp_valid_o        (orig_neigh_sc_rsp_valid_o),
    .icache_req_ready_o          (orig_icache_req_ready_o),
    .icache_resp_valid_o         (orig_icache_resp_valid_o),
    .flb_l2_neigh_resp_valid_o   (orig_flb_l2_neigh_resp_valid_o),
    .flb_l2_neigh_resp_data_o    (orig_flb_l2_neigh_resp_data_o),
    .uc_to_neigh_fcc_o           (orig_uc_to_neigh_fcc_o),
    .uc_to_neigh_fcc_target_o    (orig_uc_to_neigh_fcc_target_o),
    .pwr_ctrl_glb_nsleepin_o     (orig_pwr_ctrl_glb_nsleepin_o),
    .pwr_ctrl_glb_iso_o          (orig_pwr_ctrl_glb_iso_o),
    .pwr_ctrl_neigh_nsleepin_o   (orig_pwr_ctrl_neigh_nsleepin_o),
    .pwr_ctrl_neigh_iso_o        (orig_pwr_ctrl_neigh_iso_o),
    .ram_cfg_flat_o              (orig_ram_cfg_flat_o),
    .dft_hv_flat_o               (orig_dft_hv_flat_o),
    .debug_and_or_tree_l2_flat_o (orig_debug_and_or_tree_l2_flat_o),
    .ioshire_combined_err_int_o  (orig_ioshire_combined_err_int_o),
    .ioshire_noc_err_int_o       (orig_ioshire_noc_err_int_o),
    .noc_all_err_int_srcs_o      (orig_noc_all_err_int_srcs_o),
    .coop_slv_valid_o            (orig_coop_slv_valid_o),
    .coop_done_valid_o           (orig_coop_done_valid_o),
    .sys_axi_ar_ready_obs_o      (orig_sys_axi_ar_ready_obs_o),
    .sys_axi_aw_ready_obs_o      (orig_sys_axi_aw_ready_obs_o),
    .sys_axi_w_ready_obs_o       (orig_sys_axi_w_ready_obs_o),
    .sys_axi_b_valid_obs_o       (orig_sys_axi_b_valid_obs_o),
    .sys_axi_b_id_obs_o          (orig_sys_axi_b_id_obs_o),
    .sys_axi_b_resp_obs_o        (orig_sys_axi_b_resp_obs_o),
    .sys_axi_r_valid_obs_o       (orig_sys_axi_r_valid_obs_o),
    .sys_axi_r_data_lo_obs_o     (orig_sys_axi_r_data_lo_obs_o),
    .sys_axi_aw_credit_obs_o     (orig_sys_axi_aw_credit_obs_o)
  );

endmodule : cosim_shire_top_tb
/* verilator lint_on UNUSEDSIGNAL */
