`ifdef ET_USE_SHIRE_MONITOR_PIPE
   et_shire_monitor_pipeline #(.SHIRE_ID(254)) shire_monitor_pipe (.clock(top.clock_tb));
`endif // ifndef ET_USE_SHIRE_MONITOR_PIPE

`ifdef EVL_SIMULATION

wire        spio_noc_spio_apb0_psel;
wire [31:0] spio_noc_spio_apb0_prdata;
wire        spio_noc_spio_apb0_pready;
wire        spio_noc_spio_apb0_pslverr;
wire        spio_noc_spio_apb1_psel;
wire [31:0] spio_noc_spio_apb1_prdata;
wire        spio_noc_spio_apb1_pready;
wire        spio_noc_spio_apb1_pslverr;

`ifndef DV_IOSHIRE_NOC_ONLY
 `ifdef SPIO_GATESIM
   assign spio_noc_spio_apb0_psel = 'h0;
   assign spio_noc_spio_apb0_prdata = 'h0;
   assign spio_noc_spio_apb0_pready = 'h0;
   assign spio_noc_spio_apb0_pslverr = 'h0;
   assign spio_noc_spio_apb1_psel = 'h0;
   assign spio_noc_spio_apb1_prdata = 'h0;
   assign spio_noc_spio_apb1_pready = 'h0;
   assign spio_noc_spio_apb1_pslverr = 'h0;
 `else
      assign spio_noc_spio_apb0_psel = spio_noc_spio_pvtc0_apb_psel
                                     | spio_noc_spio_pvtc1_apb_psel
                                     | spio_noc_spio_pvtc2_apb_psel
                                     | spio_noc_spio_pvtc3_apb_psel
                                       | spio_noc_spio_pvtc4_apb_psel 
                                      | spio.spio_noc_spio_i2c1_slave_apb_psel
                                      | spio.spio_noc_spio_spi1_slave_apb_psel
                                      | spio.spio_noc_spio_uart1_slave_apb_psel
                                      | spio.spio_noc_spio_pll0_slave_apb_psel
                                      | spio.spio_noc_spio_pll1_slave_apb_psel
                                      | spio.spio_noc_spio_pll2_slave_apb_psel
                                      | spio.spio_noc_spio_pll3_slave_apb_psel
                                       | spio.spio_noc_spio_pll4_slave_apb_psel;
				       

      assign spio_noc_spio_apb0_prdata = spio_noc_spio_pvtc0_apb_psel ? spio_noc_spio_pvtc0_apb_prdata :
                                         spio_noc_spio_pvtc1_apb_psel ? spio_noc_spio_pvtc1_apb_prdata :
                                         spio_noc_spio_pvtc2_apb_psel ? spio_noc_spio_pvtc2_apb_prdata :
                                         spio_noc_spio_pvtc3_apb_psel ? spio_noc_spio_pvtc3_apb_prdata :
                                         spio_noc_spio_pvtc4_apb_psel ? spio_noc_spio_pvtc4_apb_prdata :
                                          spio.spio_noc_spio_i2c1_slave_apb_psel  ? spio.spio_noc_spio_i2c1_slave_apb_prdata  :
                                         spio.spio_noc_spio_spi1_slave_apb_psel  ? spio.spio_noc_spio_spi1_slave_apb_prdata  :
                                         spio.spio_noc_spio_uart1_slave_apb_psel ? spio.spio_noc_spio_uart1_slave_apb_prdata :
                                         spio.spio_noc_spio_pll0_slave_apb_psel  ? spio.spio_noc_spio_pll0_slave_apb_prdata  :
                                         spio.spio_noc_spio_pll1_slave_apb_psel  ? spio.spio_noc_spio_pll1_slave_apb_prdata  :
                                         spio.spio_noc_spio_pll2_slave_apb_psel  ? spio.spio_noc_spio_pll2_slave_apb_prdata  :
                                         spio.spio_noc_spio_pll3_slave_apb_psel  ? spio.spio_noc_spio_pll3_slave_apb_prdata  :
                                         spio.spio_noc_spio_pll4_slave_apb_psel  ? spio.spio_noc_spio_pll4_slave_apb_prdata  : 32'b0;

      assign spio_noc_spio_apb0_pready = spio_noc_spio_pvtc0_apb_psel ? spio_noc_spio_pvtc0_apb_pready :
                                         spio_noc_spio_pvtc1_apb_psel ? spio_noc_spio_pvtc1_apb_pready :
                                         spio_noc_spio_pvtc2_apb_psel ? spio_noc_spio_pvtc2_apb_pready :
                                         spio_noc_spio_pvtc3_apb_psel ? spio_noc_spio_pvtc3_apb_pready :
                                         spio_noc_spio_pvtc4_apb_psel ? spio_noc_spio_pvtc4_apb_pready : 
                                          spio.spio_noc_spio_i2c1_slave_apb_psel  ? spio.spio_noc_spio_i2c1_slave_apb_pready  :
                                          spio.spio_noc_spio_spi1_slave_apb_psel  ? spio.spio_noc_spio_spi1_slave_apb_pready  :
                                          spio.spio_noc_spio_uart1_slave_apb_psel ? spio.spio_noc_spio_uart1_slave_apb_pready :
                                          spio.spio_noc_spio_pll0_slave_apb_psel  ? spio.spio_noc_spio_pll0_slave_apb_pready  :
                                          spio.spio_noc_spio_pll1_slave_apb_psel  ? spio.spio_noc_spio_pll1_slave_apb_pready  :
                                          spio.spio_noc_spio_pll2_slave_apb_psel  ? spio.spio_noc_spio_pll2_slave_apb_pready  :
                                          spio.spio_noc_spio_pll3_slave_apb_psel  ? spio.spio_noc_spio_pll3_slave_apb_pready  :
                                          spio.spio_noc_spio_pll4_slave_apb_psel  ? spio.spio_noc_spio_pll4_slave_apb_pready  : 1'b1;

      assign spio_noc_spio_apb0_pslverr = spio_noc_spio_pvtc0_apb_psel ? spio_noc_spio_pvtc0_apb_pslverr :
                                          spio_noc_spio_pvtc1_apb_psel ? spio_noc_spio_pvtc1_apb_pslverr :
                                          spio_noc_spio_pvtc2_apb_psel ? spio_noc_spio_pvtc2_apb_pslverr :
                                          spio_noc_spio_pvtc3_apb_psel ? spio_noc_spio_pvtc3_apb_pslverr :
                                          spio_noc_spio_pvtc4_apb_psel ? spio_noc_spio_pvtc4_apb_pslverr : 
                                          spio.spio_noc_spio_i2c1_slave_apb_psel  ? spio.spio_noc_spio_i2c1_slave_apb_pslverr  :
                                          spio.spio_noc_spio_spi1_slave_apb_psel  ? spio.spio_noc_spio_spi1_slave_apb_psel     :
                                          spio.spio_noc_spio_uart1_slave_apb_psel ? spio.spio_noc_spio_uart1_slave_apb_psel    :
                                          spio.spio_noc_spio_pll0_slave_apb_psel  ? spio.spio_noc_spio_pll0_slave_apb_pslverr  :
                                          spio.spio_noc_spio_pll1_slave_apb_psel  ? spio.spio_noc_spio_pll1_slave_apb_pslverr  :
                                         spio.spio_noc_spio_pll2_slave_apb_psel  ? spio.spio_noc_spio_pll2_slave_apb_pslverr  :
                                          spio.spio_noc_spio_pll3_slave_apb_psel  ? spio.spio_noc_spio_pll3_slave_apb_pslverr  :
                                          spio.spio_noc_spio_pll4_slave_apb_psel  ? spio.spio_noc_spio_pll4_slave_apb_pslverr  : 1'b0;

      assign spio_noc_spio_apb1_psel = spio.spio_noc_spio_gpio_slave_apb_psel     | spio.spio_noc_spio_i2c0_slave_apb_psel   | spio.spio_noc_spio_spi0_slave_apb_psel | spio.spio_noc_spio_uart0_slave_apb_psel    |
                                       spio.spio_noc_spio_wdt_slave_apb_psel      | spio.spio_noc_spio_timers_slave_apb_psel | spio_noc_spio_fuse_apb_psel  | spio.spio_noc_spio_cru_slave_apb_psel      |
                                       spio.spio_noc_spio_misc_esr_slave_apb_psel | spio.spio_noc_spio_vault_slave_apb_psel  | spio.spio_noc_spio_plic_slave_apb_psel  | spio.spio_noc_spio_dma_reloc_slave_apb_psel;

      assign spio_noc_spio_apb1_prdata = spio.spio_noc_spio_gpio_slave_apb_psel      ? spio.spio_noc_spio_gpio_slave_apb_prdata      :
                                         spio.spio_noc_spio_i2c0_slave_apb_psel      ? spio.spio_noc_spio_i2c0_slave_apb_prdata      :
                                         spio.spio_noc_spio_spi0_slave_apb_psel      ? spio.spio_noc_spio_spi0_slave_apb_prdata      :
                                         spio.spio_noc_spio_uart0_slave_apb_psel     ? spio.spio_noc_spio_uart0_slave_apb_prdata     :
                                         spio.spio_noc_spio_wdt_slave_apb_psel       ? spio.spio_noc_spio_wdt_slave_apb_prdata       :
                                         spio.spio_noc_spio_timers_slave_apb_psel    ? spio.spio_noc_spio_timers_slave_apb_prdata    :
                                         spio_noc_spio_fuse_apb_psel      ? spio_noc_spio_fuse_apb_prdata      :
                                         spio.spio_noc_spio_cru_slave_apb_psel       ? spio.spio_noc_spio_cru_slave_apb_prdata       :
                                         spio.spio_noc_spio_misc_esr_slave_apb_psel  ? spio.spio_noc_spio_misc_esr_slave_apb_prdata  :
                                         spio.spio_noc_spio_vault_slave_apb_psel     ? spio.spio_noc_spio_vault_slave_apb_prdata     :
                                         spio.spio_noc_spio_plic_slave_apb_psel      ? spio.spio_noc_spio_plic_slave_apb_prdata      :
                                         spio.spio_noc_spio_dma_reloc_slave_apb_psel ? spio.spio_noc_spio_dma_reloc_slave_apb_prdata : 32'b0;

      assign spio_noc_spio_apb1_pready = spio.spio_noc_spio_gpio_slave_apb_psel      ? 1'b1                                :
                                         spio.spio_noc_spio_i2c0_slave_apb_psel      ? spio.spio_noc_spio_i2c0_slave_apb_pready       :
                                         spio.spio_noc_spio_spi0_slave_apb_psel      ? spio.spio_noc_spio_spi0_slave_apb_pready       :
                                         spio.spio_noc_spio_uart0_slave_apb_psel     ? spio.spio_noc_spio_uart0_slave_apb_pready      :
                                         spio.spio_noc_spio_wdt_slave_apb_psel       ? spio.spio_noc_spio_wdt_slave_apb_pready        :
                                         spio.spio_noc_spio_timers_slave_apb_psel    ? spio.spio_noc_spio_timers_slave_apb_pready     :
                                         spio_noc_spio_fuse_apb_psel      ? spio_noc_spio_fuse_apb_pready       :
                                         spio.spio_noc_spio_cru_slave_apb_psel       ? spio.spio_noc_spio_cru_slave_apb_pready        :
                                         spio.spio_noc_spio_misc_esr_slave_apb_psel  ? spio.spio_noc_spio_misc_esr_slave_apb_pready   :
                                         spio.spio_noc_spio_vault_slave_apb_psel     ? spio.spio_noc_spio_vault_slave_apb_pready      :
                                         spio.spio_noc_spio_plic_slave_apb_psel      ? spio.spio_noc_spio_plic_slave_apb_pready       :
                                         spio.spio_noc_spio_dma_reloc_slave_apb_psel ? spio.spio_noc_spio_dma_reloc_slave_apb_pready  : 1'b1;


      assign spio_noc_spio_apb1_pslverr = spio.spio_noc_spio_gpio_slave_apb_psel      ? 1'b0                                :
                                          spio.spio_noc_spio_i2c0_slave_apb_psel      ? spio.spio_noc_spio_i2c0_slave_apb_pslverr      :
                                          spio.spio_noc_spio_spi0_slave_apb_psel      ? spio.spio_noc_spio_spi0_slave_apb_pslverr      :
                                          spio.spio_noc_spio_uart0_slave_apb_psel     ? spio.spio_noc_spio_uart0_slave_apb_pslverr     :
                                          spio.spio_noc_spio_wdt_slave_apb_psel       ? spio.spio_noc_spio_wdt_slave_apb_pslverr       :
                                          spio.spio_noc_spio_timers_slave_apb_psel    ? spio.spio_noc_spio_timers_slave_apb_pslverr    :
                                          spio_noc_spio_fuse_apb_psel      ? spio_noc_spio_fuse_apb_pslverr      :
                                          spio.spio_noc_spio_cru_slave_apb_psel       ? spio.spio_noc_spio_cru_slave_apb_pslverr       :
                                          spio.spio_noc_spio_misc_esr_slave_apb_psel  ? spio.spio_noc_spio_misc_esr_slave_apb_pslverr  :
                                          spio.spio_noc_spio_vault_slave_apb_psel     ? spio.spio_noc_spio_vault_slave_apb_pslverr     :
                                          spio.spio_noc_spio_plic_slave_apb_psel      ? spio.spio_noc_spio_plic_slave_apb_pslverr      :
                                          spio.spio_noc_spio_dma_reloc_slave_apb_psel ? spio.spio_noc_spio_dma_reloc_slave_apb_pslverr : 1'b0;
  `endif // SPIO_GATESIM
`else
   assign spio_noc_spio_apb0_psel = 'h0;
   assign spio_noc_spio_apb0_prdata = 'h0;
   assign spio_noc_spio_apb0_pready = 'h0;
   assign spio_noc_spio_apb0_pslverr = 'h0;
   assign spio_noc_spio_apb1_psel = 'h0;
   assign spio_noc_spio_apb1_prdata = 'h0;
   assign spio_noc_spio_apb1_pready = 'h0;
   assign spio_noc_spio_apb1_pslverr = 'h0;
`endif  // ifndef


evl_ioshire_interface #(.IOSHIRE_ID(254),
                        `ifdef USE_SPIO_ES
                           .SP_IS_STUB(1),
                        `else
                           .SP_IS_STUB(0),
                        `endif
                        `ifdef NOC_DISABLE
                           .NOC_IS_STUB(1),
                        `else
                        .NOC_IS_STUB(0), // FIXME_DV: if we want to drive AXI requests into the spio block, this must be set to 1
                        `endif
                        `ifdef DV_IOSHIRE_NOC_ONLY
                           .IOSHIRE_NOC_ONLY(1'b1),
                        `else
                           .IOSHIRE_NOC_ONLY(1'b0),
                        `endif
                        `ifdef DV_IOSHIRE_NO_PU
                           .IOSHIRE_NO_PU(1'b1),
                        `else
                           .IOSHIRE_NO_PU(1'b0),
                        `endif
                        .ROM_FILE_NAME("spROMImage.hex"),
                        .RAM_FILE_NAME("spRAMImage.hex")) ioshire_ifc (

      .reset_ios_ckcore                (~resetn_ios),
      .clk__noc                        (clk__noc),
      .clk_ios                         (clk_ios),
      .clk_ios_ahb                     (clk_ios_ahb),
      .clk_maxshire_uncore             (clk_maxshire_uncore),
      .clk_maxshire_core               (clk_maxshire_core),
//    .clk_ios_apb                     (clk_ios_apb),

      .spio_p10_apb0_paddr             (spio_p10_apb0_s_paddr),
      .spio_p10_apb0_penable           (spio_p10_apb0_s_penable),
      .spio_p10_apb0_pwrite            (spio_p10_apb0_s_pwrite),
      .spio_p10_apb0_pwdata            (spio_p10_apb0_s_pwdata),

      .spio_p10_apb0_psel              (spio_noc_spio_apb0_psel),
      .spio_p10_apb0_pready            (spio_noc_spio_apb0_pready),
      .spio_p10_apb0_prdata            (spio_noc_spio_apb0_prdata),
      .spio_p10_apb0_pslverr           (spio_noc_spio_apb0_pslverr),

      .spio_p10_apb1_paddr             (spio_p10_apb1_s_paddr),
      .spio_p10_apb1_penable           (spio_p10_apb1_s_penable),
      .spio_p10_apb1_pwrite            (spio_p10_apb1_s_pwrite),
      .spio_p10_apb1_pwdata            (spio_p10_apb1_s_pwdata),

      .spio_p10_apb1_psel              (spio_noc_spio_apb1_psel),
      .spio_p10_apb1_pready            (spio_noc_spio_apb1_pready),
      .spio_p10_apb1_prdata            (spio_noc_spio_apb1_prdata),
      .spio_p10_apb1_pslverr           (spio_noc_spio_apb1_pslverr),

      .ioshire_slave_axi_AR                  (ioshire_slave_axi_AR                 ),
      .ioshire_slave_axi_ARVALID             (ioshire_slave_axi_ARVALID            ),
      .ioshire_slave_axi_ARREADY             (ioshire_slave_axi_ARREADY            ),
      .ioshire_slave_axi_AW                  (ioshire_slave_axi_AW                 ),
      .ioshire_slave_axi_AWVALID             (ioshire_slave_axi_AWVALID            ),
      .ioshire_slave_axi_AWREADY             (ioshire_slave_axi_AWREADY            ),
      .ioshire_slave_axi_W                   (ioshire_slave_axi_W                  ),
      .ioshire_slave_axi_WVALID              (ioshire_slave_axi_WVALID             ),
      .ioshire_slave_axi_WREADY              (ioshire_slave_axi_WREADY             ),
      .ioshire_slave_axi_B                   (ioshire_slave_axi_B                  ),
      .ioshire_slave_axi_BVALID              (ioshire_slave_axi_BVALID             ),
      .ioshire_slave_axi_BREADY              (ioshire_slave_axi_BREADY             ),
      .ioshire_slave_axi_R                   (ioshire_slave_axi_R                  ),
      .ioshire_slave_axi_RVALID              (ioshire_slave_axi_RVALID             ),
      .ioshire_slave_axi_RREADY              (ioshire_slave_axi_RREADY             ),

      .ioshire_esr_master_axi_AR             (ioshire_esr_master_axi_AR            ),
      .ioshire_esr_master_axi_ARVALID        (ioshire_esr_master_axi_ARVALID       ),
      .ioshire_esr_master_axi_ARREADY        (ioshire_esr_master_axi_ARREADY       ),
      .ioshire_esr_master_axi_AW             (ioshire_esr_master_axi_AW            ),
      .ioshire_esr_master_axi_AWVALID        (ioshire_esr_master_axi_AWVALID       ),
      .ioshire_esr_master_axi_AWREADY        (ioshire_esr_master_axi_AWREADY       ),
      .ioshire_esr_master_axi_W              (ioshire_esr_master_axi_W             ),
      .ioshire_esr_master_axi_WVALID         (ioshire_esr_master_axi_WVALID        ),
      .ioshire_esr_master_axi_WREADY         (ioshire_esr_master_axi_WREADY        ),
      .ioshire_esr_master_axi_B              (ioshire_esr_master_axi_B             ),
      .ioshire_esr_master_axi_BVALID         (ioshire_esr_master_axi_BVALID        ),
      .ioshire_esr_master_axi_BREADY         (ioshire_esr_master_axi_BREADY        ),
      .ioshire_esr_master_axi_R              (ioshire_esr_master_axi_R             ),
      .ioshire_esr_master_axi_RVALID         (ioshire_esr_master_axi_RVALID        ),
      .ioshire_esr_master_axi_RREADY         (ioshire_esr_master_axi_RREADY        ),

      .ioshire_tosys_master_axi_AR           (ioshire_tosys_master_axi_AR          ),
      .ioshire_tosys_master_axi_ARVALID      (ioshire_tosys_master_axi_ARVALID     ),
      .ioshire_tosys_master_axi_ARREADY      (ioshire_tosys_master_axi_ARREADY     ),
      .ioshire_tosys_master_axi_AW           (ioshire_tosys_master_axi_AW          ),
      .ioshire_tosys_master_axi_AWVALID      (ioshire_tosys_master_axi_AWVALID     ),
      .ioshire_tosys_master_axi_AWREADY      (ioshire_tosys_master_axi_AWREADY     ),
      .ioshire_tosys_master_axi_W            (ioshire_tosys_master_axi_W           ),
      .ioshire_tosys_master_axi_WVALID       (ioshire_tosys_master_axi_WVALID      ),
      .ioshire_tosys_master_axi_WREADY       (ioshire_tosys_master_axi_WREADY      ),
      .ioshire_tosys_master_axi_B            (ioshire_tosys_master_axi_B           ),
      .ioshire_tosys_master_axi_BVALID       (ioshire_tosys_master_axi_BVALID      ),
      .ioshire_tosys_master_axi_BREADY       (ioshire_tosys_master_axi_BREADY      ),
      .ioshire_tosys_master_axi_R            (ioshire_tosys_master_axi_R           ),
      .ioshire_tosys_master_axi_RVALID       (ioshire_tosys_master_axi_RVALID      ),
      .ioshire_tosys_master_axi_RREADY       (ioshire_tosys_master_axi_RREADY      ),

      .ioshire_tol3_master_axi_AR            (ioshire_tol3_master_axi_AR           ),
      .ioshire_tol3_master_axi_ARVALID       (ioshire_tol3_master_axi_ARVALID      ),
      .ioshire_tol3_master_axi_ARREADY       (ioshire_tol3_master_axi_ARREADY      ),
      .ioshire_tol3_master_axi_AW            (ioshire_tol3_master_axi_AW           ),
      .ioshire_tol3_master_axi_AWVALID       (ioshire_tol3_master_axi_AWVALID      ),
      .ioshire_tol3_master_axi_AWREADY       (ioshire_tol3_master_axi_AWREADY      ),
      .ioshire_tol3_master_axi_W             (ioshire_tol3_master_axi_W            ),
      .ioshire_tol3_master_axi_WVALID        (ioshire_tol3_master_axi_WVALID       ),
      .ioshire_tol3_master_axi_WREADY        (ioshire_tol3_master_axi_WREADY       ),
      .ioshire_tol3_master_axi_B             (ioshire_tol3_master_axi_B            ),
      .ioshire_tol3_master_axi_BVALID        (ioshire_tol3_master_axi_BVALID       ),
      .ioshire_tol3_master_axi_BREADY        (ioshire_tol3_master_axi_BREADY       ),
      .ioshire_tol3_master_axi_R             (ioshire_tol3_master_axi_R            ),
      .ioshire_tol3_master_axi_RVALID        (ioshire_tol3_master_axi_RVALID       ),
      .ioshire_tol3_master_axi_RREADY        (ioshire_tol3_master_axi_RREADY       ),

      .ioshire_tol3b_master_axi_AR           (ioshire_tol3b_master_axi_AR          ),
      .ioshire_tol3b_master_axi_ARVALID      (ioshire_tol3b_master_axi_ARVALID     ),
      .ioshire_tol3b_master_axi_ARREADY      (ioshire_tol3b_master_axi_ARREADY     ),
      .ioshire_tol3b_master_axi_AW           (ioshire_tol3b_master_axi_AW          ),
      .ioshire_tol3b_master_axi_AWVALID      (ioshire_tol3b_master_axi_AWVALID     ),
      .ioshire_tol3b_master_axi_AWREADY      (ioshire_tol3b_master_axi_AWREADY     ),
      .ioshire_tol3b_master_axi_W            (ioshire_tol3b_master_axi_W           ),
      .ioshire_tol3b_master_axi_WVALID       (ioshire_tol3b_master_axi_WVALID      ),
      .ioshire_tol3b_master_axi_WREADY       (ioshire_tol3b_master_axi_WREADY      ),
      .ioshire_tol3b_master_axi_B            (ioshire_tol3b_master_axi_B           ),
      .ioshire_tol3b_master_axi_BVALID       (ioshire_tol3b_master_axi_BVALID      ),
      .ioshire_tol3b_master_axi_BREADY       (ioshire_tol3b_master_axi_BREADY      ),
      .ioshire_tol3b_master_axi_R            (ioshire_tol3b_master_axi_R           ),
      .ioshire_tol3b_master_axi_RVALID       (ioshire_tol3b_master_axi_RVALID      ),
      .ioshire_tol3b_master_axi_RREADY       (ioshire_tol3b_master_axi_RREADY      ),

`ifdef IOSHIRE_WRAPPER_GATESIM
      .maxion_uc_to_l3_axi_AR                ({maxion_uc_to_l3_axi_AR, 1'b0}        ),
`else								       
      .maxion_uc_to_l3_axi_AR                (maxion_uc_to_l3_axi_AR               ),
`endif								       
      .maxion_uc_to_l3_axi_ARVALID           (maxion_uc_to_l3_axi_ARVALID          ),
      .maxion_uc_to_l3_axi_ARREADY           (maxion_uc_to_l3_axi_ARREADY          ),
      .maxion_uc_to_l3_axi_AW                (maxion_uc_to_l3_axi_AW               ),
      .maxion_uc_to_l3_axi_AWVALID           (maxion_uc_to_l3_axi_AWVALID          ),
      .maxion_uc_to_l3_axi_AWREADY           (maxion_uc_to_l3_axi_AWREADY          ),
      .maxion_uc_to_l3_axi_W                 (maxion_uc_to_l3_axi_W                ),
      .maxion_uc_to_l3_axi_WVALID            (maxion_uc_to_l3_axi_WVALID           ),
      .maxion_uc_to_l3_axi_WREADY            (maxion_uc_to_l3_axi_WREADY           ),
      .maxion_uc_to_l3_axi_B                 (maxion_uc_to_l3_axi_B                ),
      .maxion_uc_to_l3_axi_BVALID            (maxion_uc_to_l3_axi_BVALID           ),
      .maxion_uc_to_l3_axi_BREADY            (maxion_uc_to_l3_axi_BREADY           ),
      .maxion_uc_to_l3_axi_R                 (maxion_uc_to_l3_axi_R                ),
      .maxion_uc_to_l3_axi_RVALID            (maxion_uc_to_l3_axi_RVALID           ),
      .maxion_uc_to_l3_axi_RREADY            (maxion_uc_to_l3_axi_RREADY           ),

`ifdef IOSHIRE_WRAPPER_GATESIM
      .maxion_to_sys_axi_AR                  ({maxion_to_sys_axi_AR, 1'b0}         ),
`else								       
      .maxion_to_sys_axi_AR                  (maxion_to_sys_axi_AR                 ),
`endif								       
      .maxion_to_sys_axi_ARVALID             (maxion_to_sys_axi_ARVALID            ),
      .maxion_to_sys_axi_ARREADY             (maxion_to_sys_axi_ARREADY            ),
      .maxion_to_sys_axi_AW                  (maxion_to_sys_axi_AW                 ),
      .maxion_to_sys_axi_AWVALID             (maxion_to_sys_axi_AWVALID            ),
      .maxion_to_sys_axi_AWREADY             (maxion_to_sys_axi_AWREADY            ),
      .maxion_to_sys_axi_W                   (maxion_to_sys_axi_W                  ),
      .maxion_to_sys_axi_WVALID              (maxion_to_sys_axi_WVALID             ),
      .maxion_to_sys_axi_WREADY              (maxion_to_sys_axi_WREADY             ),
      .maxion_to_sys_axi_B                   (maxion_to_sys_axi_B                  ),
      .maxion_to_sys_axi_BVALID              (maxion_to_sys_axi_BVALID             ),
      .maxion_to_sys_axi_BREADY              (maxion_to_sys_axi_BREADY             ),
      .maxion_to_sys_axi_R                   (maxion_to_sys_axi_R                  ),
      .maxion_to_sys_axi_RVALID              (maxion_to_sys_axi_RVALID             ),
      .maxion_to_sys_axi_RREADY              (maxion_to_sys_axi_RREADY             ),

`ifdef IOSHIRE_WRAPPER_GATESIM
      .maxion_uc_to_sys_axi_AR               ({maxion_uc_to_sys_axi_AR, 1'b0}      ),
`else								       
      .maxion_uc_to_sys_axi_AR               (maxion_uc_to_sys_axi_AR              ),
`endif								       
      .maxion_uc_to_sys_axi_ARVALID          (maxion_uc_to_sys_axi_ARVALID         ),
      .maxion_uc_to_sys_axi_ARREADY          (maxion_uc_to_sys_axi_ARREADY         ),
      .maxion_uc_to_sys_axi_AW               (maxion_uc_to_sys_axi_AW              ),
      .maxion_uc_to_sys_axi_AWVALID          (maxion_uc_to_sys_axi_AWVALID         ),
      .maxion_uc_to_sys_axi_AWREADY          (maxion_uc_to_sys_axi_AWREADY         ),
      .maxion_uc_to_sys_axi_W                (maxion_uc_to_sys_axi_W               ),
      .maxion_uc_to_sys_axi_WVALID           (maxion_uc_to_sys_axi_WVALID          ),
      .maxion_uc_to_sys_axi_WREADY           (maxion_uc_to_sys_axi_WREADY          ),
      .maxion_uc_to_sys_axi_B                (maxion_uc_to_sys_axi_B               ),
      .maxion_uc_to_sys_axi_BVALID           (maxion_uc_to_sys_axi_BVALID          ),
      .maxion_uc_to_sys_axi_BREADY           (maxion_uc_to_sys_axi_BREADY          ),
      .maxion_uc_to_sys_axi_R                (maxion_uc_to_sys_axi_R               ),
      .maxion_uc_to_sys_axi_RVALID           (maxion_uc_to_sys_axi_RVALID          ),
      .maxion_uc_to_sys_axi_RREADY           (maxion_uc_to_sys_axi_RREADY          ),
`ifdef IOSHIRE_WRAPPER_GATESIM
      .maxion_l3_axi_AR                      ({85{1'b0}}                           ),
      .maxion_l3_axi_ARVALID                 (1'b0      ),
      .maxion_l3_axi_ARREADY                 (1'b0      ),
      .maxion_l3_axi_AW                      (maxion_l3_axi_AW                     ),
      .maxion_l3_axi_AWVALID                 (1'b0      ),
      .maxion_l3_axi_AWREADY                 (1'b0      ),
      .maxion_l3_axi_W                       (maxion_l3_axi_W                      ),
      .maxion_l3_axi_WVALID                  (1'b0      ),
      .maxion_l3_axi_WREADY                  (1'b0      ),
      .maxion_l3_axi_B                       (maxion_l3_axi_B                      ),
      .maxion_l3_axi_BVALID                  (maxion_l3_axi_BVALID                 ),
      .maxion_l3_axi_BREADY                  (maxion_l3_axi_BREADY                 ),
      .maxion_l3_axi_R                       (maxion_l3_axi_R                      ),
      .maxion_l3_axi_RVALID                  (maxion_l3_axi_RVALID                 ),
      .maxion_l3_axi_RREADY                  (maxion_l3_axi_RREADY                 ),
      .maxion_to_l3_axi_AR                   ({maxion_to_l3_axi_AR[149:76], 1'b0, 
					       maxion_to_l3_axi_AR[74:1], 1'b0}    ),
      .maxion_to_l3_axi_ARVALID              (maxion_to_l3_axi_ARVALID             ),
      .maxion_to_l3_axi_ARREADY              (maxion_to_l3_axi_ARREADY             ),
      .maxion_to_l3_axi_AW                   (maxion_to_l3_axi_AW                  ),
      .maxion_to_l3_axi_AWVALID              (maxion_to_l3_axi_AWVALID             ),
      .maxion_to_l3_axi_AWREADY              (maxion_to_l3_axi_AWREADY             ),
      .maxion_to_l3_axi_W                    (maxion_to_l3_axi_W                   ),
      .maxion_to_l3_axi_WVALID               (maxion_to_l3_axi_WVALID              ),
      .maxion_to_l3_axi_WREADY               (maxion_to_l3_axi_WREADY              ),
      .maxion_to_l3_axi_B                    (maxion_to_l3_axi_B                   ),
      .maxion_to_l3_axi_BVALID               (maxion_to_l3_axi_BVALID              ),
      .maxion_to_l3_axi_BREADY               (maxion_to_l3_axi_BREADY              ),
      .maxion_to_l3_axi_R                    (maxion_to_l3_axi_R                   ),
      .maxion_to_l3_axi_RVALID               (maxion_to_l3_axi_RVALID              ),
      .maxion_to_l3_axi_RREADY               (maxion_to_l3_axi_RREADY              ),
      .maxion_sys_axi_AR		     ({85{1'b0}}                           ),		      
      .maxion_sys_axi_ARVALID                (1'b0                                 ),
      .maxion_sys_axi_ARREADY                (maxion_sys_axi_ARREADY               ),	
`else			
      .maxion_l3_axi_AR                      (maxion_l3_axi_AR                     ),
      .maxion_l3_axi_ARVALID                 (maxion_l3_axi_ARVALID                ),
      .maxion_l3_axi_ARREADY                 (maxion_l3_axi_ARREADY                ),
      .maxion_l3_axi_AW                      (maxion_l3_axi_AW                     ),
      .maxion_l3_axi_AWVALID                 (maxion_l3_axi_AWVALID                ),
      .maxion_l3_axi_AWREADY                 (maxion_l3_axi_AWREADY                ),
      .maxion_l3_axi_W                       (maxion_l3_axi_W                      ),
      .maxion_l3_axi_WVALID                  (maxion_l3_axi_WVALID                 ),
      .maxion_l3_axi_WREADY                  (maxion_l3_axi_WREADY                 ),
      .maxion_l3_axi_B                       (maxion_l3_axi_B                      ),
      .maxion_l3_axi_BVALID                  (maxion_l3_axi_BVALID                 ),
      .maxion_l3_axi_BREADY                  (maxion_l3_axi_BREADY                 ),
      .maxion_l3_axi_R                       (maxion_l3_axi_R                      ),
      .maxion_l3_axi_RVALID                  (maxion_l3_axi_RVALID                 ),
      .maxion_l3_axi_RREADY                  (maxion_l3_axi_RREADY                 ),
      .maxion_to_l3_axi_AR                   (maxion_to_l3_axi_AR                  ),
      .maxion_to_l3_axi_ARVALID              (maxion_to_l3_axi_ARVALID             ),
      .maxion_to_l3_axi_ARREADY              (maxion_to_l3_axi_ARREADY             ),
      .maxion_to_l3_axi_AW                   (maxion_to_l3_axi_AW                  ),
      .maxion_to_l3_axi_AWVALID              (maxion_to_l3_axi_AWVALID             ),
      .maxion_to_l3_axi_AWREADY              (maxion_to_l3_axi_AWREADY             ),
      .maxion_to_l3_axi_W                    (maxion_to_l3_axi_W                   ),
      .maxion_to_l3_axi_WVALID               (maxion_to_l3_axi_WVALID              ),
      .maxion_to_l3_axi_WREADY               (maxion_to_l3_axi_WREADY              ),
      .maxion_to_l3_axi_B                    (maxion_to_l3_axi_B                   ),
      .maxion_to_l3_axi_BVALID               (maxion_to_l3_axi_BVALID              ),
      .maxion_to_l3_axi_BREADY               (maxion_to_l3_axi_BREADY              ),
      .maxion_to_l3_axi_R                    (maxion_to_l3_axi_R                   ),
      .maxion_to_l3_axi_RVALID               (maxion_to_l3_axi_RVALID              ),
      .maxion_to_l3_axi_RREADY               (maxion_to_l3_axi_RREADY              ),
      .maxion_sys_axi_AR                     (maxion_sys_axi_AR                    ),
      .maxion_sys_axi_ARVALID                (maxion_sys_axi_ARVALID               ),
      .maxion_sys_axi_ARREADY                (maxion_sys_axi_ARREADY               ),	      
`endif
      .maxion_sys_axi_AW                     (maxion_sys_axi_AW                    ),
      .maxion_sys_axi_AWVALID                (maxion_sys_axi_AWVALID               ),
      .maxion_sys_axi_AWvcvalid              (maxion_sys_axi_AWvcvalid             ),
      .maxion_sys_axi_AWcredit               (maxion_sys_axi_AWcredit              ),
      .maxion_sys_axi_AWREADY                (maxion_sys_axi_AWREADY               ),
      .maxion_sys_axi_W                      (maxion_sys_axi_W                     ),
      .maxion_sys_axi_WVALID                 (maxion_sys_axi_WVALID                ),
      .maxion_sys_axi_Wvcvalid               (maxion_sys_axi_Wvcvalid              ),
      .maxion_sys_axi_WREADY                 (maxion_sys_axi_WREADY                ),
      .maxion_sys_axi_B                      (maxion_sys_axi_B                     ),
      .maxion_sys_axi_BVALID                 (maxion_sys_axi_BVALID                ),
      .maxion_sys_axi_BREADY                 (maxion_sys_axi_BREADY                ),
      .maxion_sys_axi_R                      (maxion_sys_axi_R                     ),
      .maxion_sys_axi_RVALID                 (maxion_sys_axi_RVALID                ),
      .maxion_sys_axi_RREADY                 (maxion_sys_axi_RREADY                ),

      .pu_noc_pu_scram_axi_ARADDR            (pu_noc_pu_scram_axi_ARADDR           ),
      .pu_noc_pu_scram_axi_ARID              (pu_noc_pu_scram_axi_ARID             ),
      .pu_noc_pu_scram_axi_ARLEN             (pu_noc_pu_scram_axi_ARLEN            ),
      .pu_noc_pu_scram_axi_ARBURST           (pu_noc_pu_scram_axi_ARBURST          ),
      .pu_noc_pu_scram_axi_ARCACHE           (pu_noc_pu_scram_axi_ARCACHE          ),
      .pu_noc_pu_scram_axi_ARLOCK            (pu_noc_pu_scram_axi_ARLOCK           ),
      .pu_noc_pu_scram_axi_ARPROT            (pu_noc_pu_scram_axi_ARPROT           ),
      .pu_noc_pu_scram_axi_ARQOS             (pu_noc_pu_scram_axi_ARQOS            ),
      .pu_noc_pu_scram_axi_ARSIZE            (pu_noc_pu_scram_axi_ARSIZE           ),
      .pu_noc_pu_scram_axi_ARVALID           (pu_noc_pu_scram_axi_ARVALID          ),
      .pu_noc_pu_scram_axi_ARREADY           (pu_noc_pu_scram_axi_ARREADY          ),
      .pu_noc_pu_scram_axi_AWADDR            (pu_noc_pu_scram_axi_AWADDR           ),
      .pu_noc_pu_scram_axi_AWID              (pu_noc_pu_scram_axi_AWID             ),
      .pu_noc_pu_scram_axi_AWLEN             (pu_noc_pu_scram_axi_AWLEN            ),
      .pu_noc_pu_scram_axi_AWBURST           (pu_noc_pu_scram_axi_AWBURST          ),
      .pu_noc_pu_scram_axi_AWCACHE           (pu_noc_pu_scram_axi_AWCACHE          ),
      .pu_noc_pu_scram_axi_AWLOCK            (pu_noc_pu_scram_axi_AWLOCK           ),
      .pu_noc_pu_scram_axi_AWPROT            (pu_noc_pu_scram_axi_AWPROT           ),
      .pu_noc_pu_scram_axi_AWQOS             (pu_noc_pu_scram_axi_AWQOS            ),
      .pu_noc_pu_scram_axi_AWSIZE            (pu_noc_pu_scram_axi_AWSIZE           ),
      .pu_noc_pu_scram_axi_AWVALID           (pu_noc_pu_scram_axi_AWVALID          ),
      .pu_noc_pu_scram_axi_AWREADY           (pu_noc_pu_scram_axi_AWREADY          ),
      .pu_noc_pu_scram_axi_WDATA             (pu_noc_pu_scram_axi_WDATA            ),
      .pu_noc_pu_scram_axi_WSTRB             (pu_noc_pu_scram_axi_WSTRB            ),
      .pu_noc_pu_scram_axi_WLAST             (pu_noc_pu_scram_axi_WLAST            ),
      .pu_noc_pu_scram_axi_WVALID            (pu_noc_pu_scram_axi_WVALID           ),
      .pu_noc_pu_scram_axi_WREADY            (pu_noc_pu_scram_axi_WREADY           ),
      .pu_noc_pu_scram_axi_BID               (pu_noc_pu_scram_axi_BID              ),
      .pu_noc_pu_scram_axi_BRESP             (pu_noc_pu_scram_axi_BRESP            ),
      .pu_noc_pu_scram_axi_BVALID            (pu_noc_pu_scram_axi_BVALID           ),
      .pu_noc_pu_scram_axi_BREADY            (pu_noc_pu_scram_axi_BREADY           ),
      .pu_noc_pu_scram_axi_RDATA             (pu_noc_pu_scram_axi_RDATA            ),
      .pu_noc_pu_scram_axi_RID               (pu_noc_pu_scram_axi_RID              ),
      .pu_noc_pu_scram_axi_RLAST             (pu_noc_pu_scram_axi_RLAST            ),
      .pu_noc_pu_scram_axi_RRESP             (pu_noc_pu_scram_axi_RRESP            ),
      .pu_noc_pu_scram_axi_RVALID            (pu_noc_pu_scram_axi_RVALID           ),
      .pu_noc_pu_scram_axi_RREADY            (pu_noc_pu_scram_axi_RREADY           ),

      .pu_dma_pu_noc_axi_ARADDR              (pu_dma_pu_noc_axi_ARADDR             ),
      .pu_dma_pu_noc_axi_ARBURST             (pu_dma_pu_noc_axi_ARBURST            ),
      .pu_dma_pu_noc_axi_ARCACHE             (pu_dma_pu_noc_axi_ARCACHE            ),
      .pu_dma_pu_noc_axi_ARID                (pu_dma_pu_noc_axi_ARID               ),
      .pu_dma_pu_noc_axi_ARLEN               (pu_dma_pu_noc_axi_ARLEN              ),
      .pu_dma_pu_noc_axi_ARLOCK              (pu_dma_pu_noc_axi_ARLOCK             ),
      .pu_dma_pu_noc_axi_ARPROT              (pu_dma_pu_noc_axi_ARPROT             ),
      .pu_dma_pu_noc_axi_ARSIZE              (pu_dma_pu_noc_axi_ARSIZE             ),
      .pu_dma_pu_noc_axi_ARVALID             (pu_dma_pu_noc_axi_ARVALID            ),
      .pu_dma_pu_noc_axi_AWADDR              (pu_dma_pu_noc_axi_AWADDR             ),
      .pu_dma_pu_noc_axi_AWBURST             (pu_dma_pu_noc_axi_AWBURST            ),
      .pu_dma_pu_noc_axi_AWCACHE             (pu_dma_pu_noc_axi_AWCACHE            ),
      .pu_dma_pu_noc_axi_AWID                (pu_dma_pu_noc_axi_AWID               ),
      .pu_dma_pu_noc_axi_AWLEN               (pu_dma_pu_noc_axi_AWLEN              ),
      .pu_dma_pu_noc_axi_AWLOCK              (pu_dma_pu_noc_axi_AWLOCK             ),
      .pu_dma_pu_noc_axi_AWPROT              (pu_dma_pu_noc_axi_AWPROT             ),
      .pu_dma_pu_noc_axi_AWSIZE              (pu_dma_pu_noc_axi_AWSIZE             ),
      .pu_dma_pu_noc_axi_AWVALID             (pu_dma_pu_noc_axi_AWVALID            ),
      .pu_dma_pu_noc_axi_BREADY              (pu_dma_pu_noc_axi_BREADY             ),
      .pu_dma_pu_noc_axi_RREADY              (pu_dma_pu_noc_axi_RREADY             ),
      .pu_dma_pu_noc_axi_WDATA               (pu_dma_pu_noc_axi_WDATA              ),
      .pu_dma_pu_noc_axi_WID                 (pu_dma_pu_noc_axi_WID                ),
      .pu_dma_pu_noc_axi_WLAST               (pu_dma_pu_noc_axi_WLAST              ),
      .pu_dma_pu_noc_axi_WSTRB               (pu_dma_pu_noc_axi_WSTRB              ),
      .pu_dma_pu_noc_axi_WVALID              (pu_dma_pu_noc_axi_WVALID             ),
      .pu_dma_pu_noc_axi_ARREADY             (pu_dma_pu_noc_axi_ARREADY            ),
      .pu_dma_pu_noc_axi_AWREADY             (pu_dma_pu_noc_axi_AWREADY            ),
      .pu_dma_pu_noc_axi_BID                 (pu_dma_pu_noc_axi_BID                ),
      .pu_dma_pu_noc_axi_BRESP               (pu_dma_pu_noc_axi_BRESP              ),
      .pu_dma_pu_noc_axi_BVALID              (pu_dma_pu_noc_axi_BVALID             ),
      .pu_dma_pu_noc_axi_RDATA               (pu_dma_pu_noc_axi_RDATA              ),
      .pu_dma_pu_noc_axi_RID                 (pu_dma_pu_noc_axi_RID                ),
      .pu_dma_pu_noc_axi_RLAST               (pu_dma_pu_noc_axi_RLAST              ),
      .pu_dma_pu_noc_axi_RRESP               (pu_dma_pu_noc_axi_RRESP              ),
      .pu_dma_pu_noc_axi_RVALID              (pu_dma_pu_noc_axi_RVALID             ),
      .pu_dma_pu_noc_axi_WREADY              (pu_dma_pu_noc_axi_WREADY             ),

      .pu_dma_am_pu_noc_axi_ARADDR           (pu_dma_am_pu_noc_axi_ARADDR          ),
      .pu_dma_am_pu_noc_axi_ARBURST          (pu_dma_am_pu_noc_axi_ARBURST         ),
      .pu_dma_am_pu_noc_axi_ARCACHE          (pu_dma_am_pu_noc_axi_ARCACHE         ),
      .pu_dma_am_pu_noc_axi_ARID             (pu_dma_am_pu_noc_axi_ARID            ),
      .pu_dma_am_pu_noc_axi_ARLEN            (pu_dma_am_pu_noc_axi_ARLEN           ),
      .pu_dma_am_pu_noc_axi_ARLOCK           (pu_dma_am_pu_noc_axi_ARLOCK          ),
      .pu_dma_am_pu_noc_axi_ARPROT           (pu_dma_am_pu_noc_axi_ARPROT          ),
      .pu_dma_am_pu_noc_axi_ARQOS            (pu_dma_am_pu_noc_axi_ARQOS           ),
      .pu_dma_am_pu_noc_axi_ARSIZE           (pu_dma_am_pu_noc_axi_ARSIZE          ),
      .pu_dma_am_pu_noc_axi_ARVALID          (pu_dma_am_pu_noc_axi_ARVALID         ),
      .pu_dma_am_pu_noc_axi_AWADDR           (pu_dma_am_pu_noc_axi_AWADDR          ),
      .pu_dma_am_pu_noc_axi_AWBURST          (pu_dma_am_pu_noc_axi_AWBURST         ),
      .pu_dma_am_pu_noc_axi_AWCACHE          (pu_dma_am_pu_noc_axi_AWCACHE         ),
      .pu_dma_am_pu_noc_axi_AWID             (pu_dma_am_pu_noc_axi_AWID            ),
      .pu_dma_am_pu_noc_axi_AWLEN            (pu_dma_am_pu_noc_axi_AWLEN           ),
      .pu_dma_am_pu_noc_axi_AWLOCK           (pu_dma_am_pu_noc_axi_AWLOCK          ),
      .pu_dma_am_pu_noc_axi_AWPROT           (pu_dma_am_pu_noc_axi_AWPROT          ),
      .pu_dma_am_pu_noc_axi_AWQOS            (pu_dma_am_pu_noc_axi_AWQOS           ),
      .pu_dma_am_pu_noc_axi_AWSIZE           (pu_dma_am_pu_noc_axi_AWSIZE          ),
      .pu_dma_am_pu_noc_axi_AWVALID          (pu_dma_am_pu_noc_axi_AWVALID         ),
      .pu_dma_am_pu_noc_axi_BREADY           (pu_dma_am_pu_noc_axi_BREADY          ),
      .pu_dma_am_pu_noc_axi_RREADY           (pu_dma_am_pu_noc_axi_RREADY          ),
      .pu_dma_am_pu_noc_axi_WDATA            (pu_dma_am_pu_noc_axi_WDATA           ),
      .pu_dma_am_pu_noc_axi_WLAST            (pu_dma_am_pu_noc_axi_WLAST           ),
      .pu_dma_am_pu_noc_axi_WSTRB            (pu_dma_am_pu_noc_axi_WSTRB           ),
      .pu_dma_am_pu_noc_axi_WVALID           (pu_dma_am_pu_noc_axi_WVALID          ),
      .pu_dma_am_pu_noc_axi_ARREADY          (pu_dma_am_pu_noc_axi_ARREADY         ),
      .pu_dma_am_pu_noc_axi_AWREADY          (pu_dma_am_pu_noc_axi_AWREADY         ),
      .pu_dma_am_pu_noc_axi_BID              (pu_dma_am_pu_noc_axi_BID             ),
      .pu_dma_am_pu_noc_axi_BRESP            (pu_dma_am_pu_noc_axi_BRESP           ),
      .pu_dma_am_pu_noc_axi_BVALID           (pu_dma_am_pu_noc_axi_BVALID          ),
      .pu_dma_am_pu_noc_axi_RDATA            (pu_dma_am_pu_noc_axi_RDATA           ),
      .pu_dma_am_pu_noc_axi_RID              (pu_dma_am_pu_noc_axi_RID             ),
      .pu_dma_am_pu_noc_axi_RLAST            (pu_dma_am_pu_noc_axi_RLAST           ),
      .pu_dma_am_pu_noc_axi_RRESP            (pu_dma_am_pu_noc_axi_RRESP           ),
      .pu_dma_am_pu_noc_axi_RVALID           (pu_dma_am_pu_noc_axi_RVALID          ),
      .pu_dma_am_pu_noc_axi_WREADY           (pu_dma_am_pu_noc_axi_WREADY          ),

      .pu_emmc_pu_noc_axi_ARADDR             (pu_emmc_pu_noc_axi_ARADDR            ),
      .pu_emmc_pu_noc_axi_ARBURST            (pu_emmc_pu_noc_axi_ARBURST           ),
      .pu_emmc_pu_noc_axi_ARCACHE            (pu_emmc_pu_noc_axi_ARCACHE           ),
      .pu_emmc_pu_noc_axi_ARID               (pu_emmc_pu_noc_axi_ARID              ),
      .pu_emmc_pu_noc_axi_ARLEN              (pu_emmc_pu_noc_axi_ARLEN             ),
      .pu_emmc_pu_noc_axi_ARLOCK             (pu_emmc_pu_noc_axi_ARLOCK            ),
      .pu_emmc_pu_noc_axi_ARPROT             (pu_emmc_pu_noc_axi_ARPROT            ),
      .pu_emmc_pu_noc_axi_ARSIZE             (pu_emmc_pu_noc_axi_ARSIZE            ),
      .pu_emmc_pu_noc_axi_ARVALID            (pu_emmc_pu_noc_axi_ARVALID           ),
      .pu_emmc_pu_noc_axi_AWADDR             (pu_emmc_pu_noc_axi_AWADDR            ),
      .pu_emmc_pu_noc_axi_AWBURST            (pu_emmc_pu_noc_axi_AWBURST           ),
      .pu_emmc_pu_noc_axi_AWCACHE            (pu_emmc_pu_noc_axi_AWCACHE           ),
      .pu_emmc_pu_noc_axi_AWID               (pu_emmc_pu_noc_axi_AWID              ),
      .pu_emmc_pu_noc_axi_AWLEN              (pu_emmc_pu_noc_axi_AWLEN             ),
      .pu_emmc_pu_noc_axi_AWLOCK             (pu_emmc_pu_noc_axi_AWLOCK            ),
      .pu_emmc_pu_noc_axi_AWPROT             (pu_emmc_pu_noc_axi_AWPROT            ),
      .pu_emmc_pu_noc_axi_AWSIZE             (pu_emmc_pu_noc_axi_AWSIZE            ),
      .pu_emmc_pu_noc_axi_AWVALID            (pu_emmc_pu_noc_axi_AWVALID           ),
      .pu_emmc_pu_noc_axi_BREADY             (pu_emmc_pu_noc_axi_BREADY            ),
      .pu_emmc_pu_noc_axi_RREADY             (pu_emmc_pu_noc_axi_RREADY            ),
      .pu_emmc_pu_noc_axi_WDATA              (pu_emmc_pu_noc_axi_WDATA             ),
      .pu_emmc_pu_noc_axi_WID                (pu_emmc_pu_noc_axi_WID               ),
      .pu_emmc_pu_noc_axi_WLAST              (pu_emmc_pu_noc_axi_WLAST             ),
      .pu_emmc_pu_noc_axi_WSTRB              (pu_emmc_pu_noc_axi_WSTRB             ),
      .pu_emmc_pu_noc_axi_WVALID             (pu_emmc_pu_noc_axi_WVALID            ),
      .pu_emmc_pu_noc_axi_ARREADY            (pu_emmc_pu_noc_axi_ARREADY           ),
      .pu_emmc_pu_noc_axi_AWREADY            (pu_emmc_pu_noc_axi_AWREADY           ),
      .pu_emmc_pu_noc_axi_BID                (pu_emmc_pu_noc_axi_BID               ),
      .pu_emmc_pu_noc_axi_BRESP              (pu_emmc_pu_noc_axi_BRESP             ),
      .pu_emmc_pu_noc_axi_BVALID             (pu_emmc_pu_noc_axi_BVALID            ),
      .pu_emmc_pu_noc_axi_RDATA              (pu_emmc_pu_noc_axi_RDATA             ),
      .pu_emmc_pu_noc_axi_RID                (pu_emmc_pu_noc_axi_RID               ),
      .pu_emmc_pu_noc_axi_RLAST              (pu_emmc_pu_noc_axi_RLAST             ),
      .pu_emmc_pu_noc_axi_RRESP              (pu_emmc_pu_noc_axi_RRESP             ),
      .pu_emmc_pu_noc_axi_RVALID             (pu_emmc_pu_noc_axi_RVALID            ),
      .pu_emmc_pu_noc_axi_WREADY             (pu_emmc_pu_noc_axi_WREADY            ),

      .pu_usb0_pu_noc_axi_ARADDR             (pu_usb0_pu_noc_axi_ARADDR            ),
      .pu_usb0_pu_noc_axi_ARBURST            (pu_usb0_pu_noc_axi_ARBURST           ),
      .pu_usb0_pu_noc_axi_ARCACHE            (pu_usb0_pu_noc_axi_ARCACHE           ),
      .pu_usb0_pu_noc_axi_ARID               (pu_usb0_pu_noc_axi_ARID              ),
      .pu_usb0_pu_noc_axi_ARLEN              (pu_usb0_pu_noc_axi_ARLEN             ),
      .pu_usb0_pu_noc_axi_ARLOCK             (pu_usb0_pu_noc_axi_ARLOCK            ),
      .pu_usb0_pu_noc_axi_ARPROT             (pu_usb0_pu_noc_axi_ARPROT            ),
      .pu_usb0_pu_noc_axi_ARSIZE             (pu_usb0_pu_noc_axi_ARSIZE            ),
      .pu_usb0_pu_noc_axi_ARVALID            (pu_usb0_pu_noc_axi_ARVALID           ),
      .pu_usb0_pu_noc_axi_AWADDR             (pu_usb0_pu_noc_axi_AWADDR            ),
      .pu_usb0_pu_noc_axi_AWBURST            (pu_usb0_pu_noc_axi_AWBURST           ),
      .pu_usb0_pu_noc_axi_AWCACHE            (pu_usb0_pu_noc_axi_AWCACHE           ),
      .pu_usb0_pu_noc_axi_AWID               (pu_usb0_pu_noc_axi_AWID              ),
      .pu_usb0_pu_noc_axi_AWLEN              (pu_usb0_pu_noc_axi_AWLEN             ),
      .pu_usb0_pu_noc_axi_AWLOCK             (pu_usb0_pu_noc_axi_AWLOCK            ),
      .pu_usb0_pu_noc_axi_AWPROT             (pu_usb0_pu_noc_axi_AWPROT            ),
      .pu_usb0_pu_noc_axi_AWSIZE             (pu_usb0_pu_noc_axi_AWSIZE            ),
      .pu_usb0_pu_noc_axi_AWVALID            (pu_usb0_pu_noc_axi_AWVALID           ),
      .pu_usb0_pu_noc_axi_BREADY             (pu_usb0_pu_noc_axi_BREADY            ),
      .pu_usb0_pu_noc_axi_RREADY             (pu_usb0_pu_noc_axi_RREADY            ),
      .pu_usb0_pu_noc_axi_WDATA              (pu_usb0_pu_noc_axi_WDATA             ),
      .pu_usb0_pu_noc_axi_WID                (pu_usb0_pu_noc_axi_WID               ),
      .pu_usb0_pu_noc_axi_WLAST              (pu_usb0_pu_noc_axi_WLAST             ),
      .pu_usb0_pu_noc_axi_WSTRB              (pu_usb0_pu_noc_axi_WSTRB             ),
      .pu_usb0_pu_noc_axi_WVALID             (pu_usb0_pu_noc_axi_WVALID            ),
      .pu_usb0_pu_noc_axi_ARREADY            (pu_usb0_pu_noc_axi_ARREADY           ),
      .pu_usb0_pu_noc_axi_AWREADY            (pu_usb0_pu_noc_axi_AWREADY           ),
      .pu_usb0_pu_noc_axi_BID                (pu_usb0_pu_noc_axi_BID               ),
      .pu_usb0_pu_noc_axi_BRESP              (pu_usb0_pu_noc_axi_BRESP             ),
      .pu_usb0_pu_noc_axi_BVALID             (pu_usb0_pu_noc_axi_BVALID            ),
      .pu_usb0_pu_noc_axi_RDATA              (pu_usb0_pu_noc_axi_RDATA             ),
      .pu_usb0_pu_noc_axi_RID                (pu_usb0_pu_noc_axi_RID               ),
      .pu_usb0_pu_noc_axi_RLAST              (pu_usb0_pu_noc_axi_RLAST             ),
      .pu_usb0_pu_noc_axi_RRESP              (pu_usb0_pu_noc_axi_RRESP             ),
      .pu_usb0_pu_noc_axi_RVALID             (pu_usb0_pu_noc_axi_RVALID            ),
      .pu_usb0_pu_noc_axi_WREADY             (pu_usb0_pu_noc_axi_WREADY            ),

      .pu_usb1_pu_noc_axi_ARADDR             (pu_usb1_pu_noc_axi_ARADDR            ),
      .pu_usb1_pu_noc_axi_ARBURST            (pu_usb1_pu_noc_axi_ARBURST           ),
      .pu_usb1_pu_noc_axi_ARCACHE            (pu_usb1_pu_noc_axi_ARCACHE           ),
      .pu_usb1_pu_noc_axi_ARID               (pu_usb1_pu_noc_axi_ARID              ),
      .pu_usb1_pu_noc_axi_ARLEN              (pu_usb1_pu_noc_axi_ARLEN             ),
      .pu_usb1_pu_noc_axi_ARLOCK             (pu_usb1_pu_noc_axi_ARLOCK            ),
      .pu_usb1_pu_noc_axi_ARPROT             (pu_usb1_pu_noc_axi_ARPROT            ),
      .pu_usb1_pu_noc_axi_ARSIZE             (pu_usb1_pu_noc_axi_ARSIZE            ),
      .pu_usb1_pu_noc_axi_ARVALID            (pu_usb1_pu_noc_axi_ARVALID           ),
      .pu_usb1_pu_noc_axi_AWADDR             (pu_usb1_pu_noc_axi_AWADDR            ),
      .pu_usb1_pu_noc_axi_AWBURST            (pu_usb1_pu_noc_axi_AWBURST           ),
      .pu_usb1_pu_noc_axi_AWCACHE            (pu_usb1_pu_noc_axi_AWCACHE           ),
      .pu_usb1_pu_noc_axi_AWID               (pu_usb1_pu_noc_axi_AWID              ),
      .pu_usb1_pu_noc_axi_AWLEN              (pu_usb1_pu_noc_axi_AWLEN             ),
      .pu_usb1_pu_noc_axi_AWLOCK             (pu_usb1_pu_noc_axi_AWLOCK            ),
      .pu_usb1_pu_noc_axi_AWPROT             (pu_usb1_pu_noc_axi_AWPROT            ),
      .pu_usb1_pu_noc_axi_AWSIZE             (pu_usb1_pu_noc_axi_AWSIZE            ),
      .pu_usb1_pu_noc_axi_AWVALID            (pu_usb1_pu_noc_axi_AWVALID           ),
      .pu_usb1_pu_noc_axi_BREADY             (pu_usb1_pu_noc_axi_BREADY            ),
      .pu_usb1_pu_noc_axi_RREADY             (pu_usb1_pu_noc_axi_RREADY            ),
      .pu_usb1_pu_noc_axi_WDATA              (pu_usb1_pu_noc_axi_WDATA             ),
      .pu_usb1_pu_noc_axi_WID                (pu_usb1_pu_noc_axi_WID               ),
      .pu_usb1_pu_noc_axi_WLAST              (pu_usb1_pu_noc_axi_WLAST             ),
      .pu_usb1_pu_noc_axi_WSTRB              (pu_usb1_pu_noc_axi_WSTRB             ),
      .pu_usb1_pu_noc_axi_WVALID             (pu_usb1_pu_noc_axi_WVALID            ),
      .pu_usb1_pu_noc_axi_ARREADY            (pu_usb1_pu_noc_axi_ARREADY           ),
      .pu_usb1_pu_noc_axi_AWREADY            (pu_usb1_pu_noc_axi_AWREADY           ),
      .pu_usb1_pu_noc_axi_BID                (pu_usb1_pu_noc_axi_BID               ),
      .pu_usb1_pu_noc_axi_BRESP              (pu_usb1_pu_noc_axi_BRESP             ),
      .pu_usb1_pu_noc_axi_BVALID             (pu_usb1_pu_noc_axi_BVALID            ),
      .pu_usb1_pu_noc_axi_RDATA              (pu_usb1_pu_noc_axi_RDATA             ),
      .pu_usb1_pu_noc_axi_RID                (pu_usb1_pu_noc_axi_RID               ),
      .pu_usb1_pu_noc_axi_RLAST              (pu_usb1_pu_noc_axi_RLAST             ),
      .pu_usb1_pu_noc_axi_RRESP              (pu_usb1_pu_noc_axi_RRESP             ),
      .pu_usb1_pu_noc_axi_RVALID             (pu_usb1_pu_noc_axi_RVALID            ),
      .pu_usb1_pu_noc_axi_WREADY             (pu_usb1_pu_noc_axi_WREADY            ),

      .pu_static_pu_noc_axi_ARREADY          (pu_static_pu_noc_axi_ARREADY         ),
      .pu_static_pu_noc_axi_AWREADY          (pu_static_pu_noc_axi_AWREADY         ),
      .pu_static_pu_noc_axi_BID              (pu_static_pu_noc_axi_BID             ),
      .pu_static_pu_noc_axi_BRESP            (pu_static_pu_noc_axi_BRESP           ),
      .pu_static_pu_noc_axi_BVALID           (pu_static_pu_noc_axi_BVALID          ),
      .pu_static_pu_noc_axi_RDATA            (pu_static_pu_noc_axi_RDATA           ),
      .pu_static_pu_noc_axi_RID              (pu_static_pu_noc_axi_RID             ),
      .pu_static_pu_noc_axi_RLAST            (pu_static_pu_noc_axi_RLAST           ),
      .pu_static_pu_noc_axi_RRESP            (pu_static_pu_noc_axi_RRESP           ),
      .pu_static_pu_noc_axi_RVALID           (pu_static_pu_noc_axi_RVALID          ),
      .pu_static_pu_noc_axi_WREADY           (pu_static_pu_noc_axi_WREADY          ),
      .pu_static_pu_noc_axi_ARADDR           (pu_static_pu_noc_axi_ARADDR          ),
      .pu_static_pu_noc_axi_ARBURST          (pu_static_pu_noc_axi_ARBURST         ),
      .pu_static_pu_noc_axi_ARCACHE          (pu_static_pu_noc_axi_ARCACHE         ),
      .pu_static_pu_noc_axi_ARID             (pu_static_pu_noc_axi_ARID            ),
      .pu_static_pu_noc_axi_ARLEN            (pu_static_pu_noc_axi_ARLEN           ),
      .pu_static_pu_noc_axi_ARLOCK           (pu_static_pu_noc_axi_ARLOCK          ),
      .pu_static_pu_noc_axi_ARPROT           (pu_static_pu_noc_axi_ARPROT          ),
      .pu_static_pu_noc_axi_ARQOS            (pu_static_pu_noc_axi_ARQOS           ),
      .pu_static_pu_noc_axi_ARSIZE           (pu_static_pu_noc_axi_ARSIZE          ),
      .pu_static_pu_noc_axi_ARVALID          (pu_static_pu_noc_axi_ARVALID         ),
      .pu_static_pu_noc_axi_AWADDR           (pu_static_pu_noc_axi_AWADDR          ),
      .pu_static_pu_noc_axi_AWBURST          (pu_static_pu_noc_axi_AWBURST         ),
      .pu_static_pu_noc_axi_AWCACHE          (pu_static_pu_noc_axi_AWCACHE         ),
      .pu_static_pu_noc_axi_AWID             (pu_static_pu_noc_axi_AWID            ),
      .pu_static_pu_noc_axi_AWLEN            (pu_static_pu_noc_axi_AWLEN           ),
      .pu_static_pu_noc_axi_AWLOCK           (pu_static_pu_noc_axi_AWLOCK          ),
      .pu_static_pu_noc_axi_AWPROT           (pu_static_pu_noc_axi_AWPROT          ),
      .pu_static_pu_noc_axi_AWQOS            (pu_static_pu_noc_axi_AWQOS           ),
      .pu_static_pu_noc_axi_AWSIZE           (pu_static_pu_noc_axi_AWSIZE          ),
      .pu_static_pu_noc_axi_AWVALID          (pu_static_pu_noc_axi_AWVALID         ),
      .pu_static_pu_noc_axi_BREADY           (pu_static_pu_noc_axi_BREADY          ),
      .pu_static_pu_noc_axi_RREADY           (pu_static_pu_noc_axi_RREADY          ),
      .pu_static_pu_noc_axi_WDATA            (pu_static_pu_noc_axi_WDATA           ),
      .pu_static_pu_noc_axi_WLAST            (pu_static_pu_noc_axi_WLAST           ),
      .pu_static_pu_noc_axi_WSTRB            (pu_static_pu_noc_axi_WSTRB           ),
      .pu_static_pu_noc_axi_WVALID           (pu_static_pu_noc_axi_WVALID          ),

      .spio_noc_pu_noc_axi_ARADDR            (spio_noc_pu_noc_axi_ARADDR           ),
      .spio_noc_pu_noc_axi_ARID              (spio_noc_pu_noc_axi_ARID             ),
      .spio_noc_pu_noc_axi_ARLEN             (spio_noc_pu_noc_axi_ARLEN            ),
      .spio_noc_pu_noc_axi_ARBURST           (spio_noc_pu_noc_axi_ARBURST          ),
      .spio_noc_pu_noc_axi_ARCACHE           (spio_noc_pu_noc_axi_ARCACHE          ),
      .spio_noc_pu_noc_axi_ARLOCK            (spio_noc_pu_noc_axi_ARLOCK           ),
      .spio_noc_pu_noc_axi_ARPROT            (spio_noc_pu_noc_axi_ARPROT           ),
      .spio_noc_pu_noc_axi_ARQOS             (spio_noc_pu_noc_axi_ARQOS            ),
      .spio_noc_pu_noc_axi_ARSIZE            (spio_noc_pu_noc_axi_ARSIZE           ),
      .spio_noc_pu_noc_axi_ARVALID           (spio_noc_pu_noc_axi_ARVALID          ),
      .spio_noc_pu_noc_axi_ARREADY           (spio_noc_pu_noc_axi_ARREADY          ),
      .spio_noc_pu_noc_axi_AWADDR            (spio_noc_pu_noc_axi_AWADDR           ),
      .spio_noc_pu_noc_axi_AWID              (spio_noc_pu_noc_axi_AWID             ),
      .spio_noc_pu_noc_axi_AWLEN             (spio_noc_pu_noc_axi_AWLEN            ),
      .spio_noc_pu_noc_axi_AWBURST           (spio_noc_pu_noc_axi_AWBURST          ),
      .spio_noc_pu_noc_axi_AWCACHE           (spio_noc_pu_noc_axi_AWCACHE          ),
      .spio_noc_pu_noc_axi_AWLOCK            (spio_noc_pu_noc_axi_AWLOCK           ),
      .spio_noc_pu_noc_axi_AWPROT            (spio_noc_pu_noc_axi_AWPROT           ),
      .spio_noc_pu_noc_axi_AWQOS             (spio_noc_pu_noc_axi_AWQOS            ),
      .spio_noc_pu_noc_axi_AWSIZE            (spio_noc_pu_noc_axi_AWSIZE           ),
      .spio_noc_pu_noc_axi_AWVALID           (spio_noc_pu_noc_axi_AWVALID          ),
      .spio_noc_pu_noc_axi_AWREADY           (spio_noc_pu_noc_axi_AWREADY          ),
      .spio_noc_pu_noc_axi_AWUSER            (spio_noc_pu_noc_axi_AWUSER           ),
      .spio_noc_pu_noc_axi_WDATA             (spio_noc_pu_noc_axi_WDATA            ),
      .spio_noc_pu_noc_axi_WSTRB             (spio_noc_pu_noc_axi_WSTRB            ),
      .spio_noc_pu_noc_axi_WLAST             (spio_noc_pu_noc_axi_WLAST            ),
      .spio_noc_pu_noc_axi_WVALID            (spio_noc_pu_noc_axi_WVALID           ),
      .spio_noc_pu_noc_axi_WREADY            (spio_noc_pu_noc_axi_WREADY           ),
      .spio_noc_pu_noc_axi_BID               (spio_noc_pu_noc_axi_BID              ),
      .spio_noc_pu_noc_axi_BRESP             (spio_noc_pu_noc_axi_BRESP            ),
      .spio_noc_pu_noc_axi_BVALID            (spio_noc_pu_noc_axi_BVALID           ),
      .spio_noc_pu_noc_axi_BREADY            (spio_noc_pu_noc_axi_BREADY           ),
      .spio_noc_pu_noc_axi_RDATA             (spio_noc_pu_noc_axi_RDATA            ),
      .spio_noc_pu_noc_axi_RID               (spio_noc_pu_noc_axi_RID              ),
      .spio_noc_pu_noc_axi_RLAST             (spio_noc_pu_noc_axi_RLAST            ),
      .spio_noc_pu_noc_axi_RRESP             (spio_noc_pu_noc_axi_RRESP            ),
      .spio_noc_pu_noc_axi_RVALID            (spio_noc_pu_noc_axi_RVALID           ),
      .spio_noc_pu_noc_axi_RREADY            (spio_noc_pu_noc_axi_RREADY           ),

      .spio_noc_spio_rom_axi_ARADDR          (spio_noc_spio_rom_axi_ARADDR         ),
      .spio_noc_spio_rom_axi_ARID            (spio_noc_spio_rom_axi_ARID           ),
      .spio_noc_spio_rom_axi_ARQOS           (spio_noc_spio_rom_axi_ARQOS          ),
      .spio_noc_spio_rom_axi_ARLEN           (spio_noc_spio_rom_axi_ARLEN          ),
      .spio_noc_spio_rom_axi_ARBURST         (spio_noc_spio_rom_axi_ARBURST        ),
      .spio_noc_spio_rom_axi_ARCACHE         (spio_noc_spio_rom_axi_ARCACHE        ),
      .spio_noc_spio_rom_axi_ARLOCK          (spio_noc_spio_rom_axi_ARLOCK         ),
      .spio_noc_spio_rom_axi_ARPROT          (spio_noc_spio_rom_axi_ARPROT         ),
      .spio_noc_spio_rom_axi_ARSIZE          (spio_noc_spio_rom_axi_ARSIZE         ),
      .spio_noc_spio_rom_axi_ARVALID         (spio_noc_spio_rom_axi_ARVALID        ),
      .spio_noc_spio_rom_axi_ARREADY         (spio_noc_spio_rom_axi_ARREADY        ),
      .spio_noc_spio_rom_axi_AWADDR          (spio_noc_spio_rom_axi_AWADDR         ),
      .spio_noc_spio_rom_axi_AWID            (spio_noc_spio_rom_axi_AWID           ),
      .spio_noc_spio_rom_axi_AWQOS           (spio_noc_spio_rom_axi_AWQOS          ),
      .spio_noc_spio_rom_axi_AWLEN           (spio_noc_spio_rom_axi_AWLEN          ),
      .spio_noc_spio_rom_axi_AWBURST         (spio_noc_spio_rom_axi_AWBURST        ),
      .spio_noc_spio_rom_axi_AWCACHE         (spio_noc_spio_rom_axi_AWCACHE        ),
      .spio_noc_spio_rom_axi_AWLOCK          (spio_noc_spio_rom_axi_AWLOCK         ),
      .spio_noc_spio_rom_axi_AWPROT          (spio_noc_spio_rom_axi_AWPROT         ),
      .spio_noc_spio_rom_axi_AWSIZE          (spio_noc_spio_rom_axi_AWSIZE         ),
      .spio_noc_spio_rom_axi_AWVALID         (spio_noc_spio_rom_axi_AWVALID        ),
      .spio_noc_spio_rom_axi_AWREADY         (spio_noc_spio_rom_axi_AWREADY        ),
      .spio_noc_spio_rom_axi_WDATA           (spio_noc_spio_rom_axi_WDATA          ),
      .spio_noc_spio_rom_axi_WSTRB           (spio_noc_spio_rom_axi_WSTRB          ),
      .spio_noc_spio_rom_axi_WLAST           (spio_noc_spio_rom_axi_WLAST          ),
      .spio_noc_spio_rom_axi_WVALID          (spio_noc_spio_rom_axi_WVALID         ),
      .spio_noc_spio_rom_axi_WREADY          (spio_noc_spio_rom_axi_WREADY         ),
      .spio_noc_spio_rom_axi_BID             (spio_noc_spio_rom_axi_BID            ),
      .spio_noc_spio_rom_axi_BRESP           (spio_noc_spio_rom_axi_BRESP          ),
      .spio_noc_spio_rom_axi_BVALID          (spio_noc_spio_rom_axi_BVALID         ),
      .spio_noc_spio_rom_axi_BREADY          (spio_noc_spio_rom_axi_BREADY         ),
      .spio_noc_spio_rom_axi_RDATA           (spio_noc_spio_rom_axi_RDATA          ),
      .spio_noc_spio_rom_axi_RID             (spio_noc_spio_rom_axi_RID            ),
      .spio_noc_spio_rom_axi_RLAST           (spio_noc_spio_rom_axi_RLAST          ),
      .spio_noc_spio_rom_axi_RRESP           (spio_noc_spio_rom_axi_RRESP          ),
      .spio_noc_spio_rom_axi_RVALID          (spio_noc_spio_rom_axi_RVALID         ),
      .spio_noc_spio_rom_axi_RREADY          (spio_noc_spio_rom_axi_RREADY         ),

      .spio_noc_spio_scram_axi_ARADDR        (spio_noc_spio_scram_axi_ARADDR       ),
      .spio_noc_spio_scram_axi_ARID          (spio_noc_spio_scram_axi_ARID         ),
      .spio_noc_spio_scram_axi_ARQOS         (spio_noc_spio_scram_axi_ARQOS        ),
      .spio_noc_spio_scram_axi_ARLEN         (spio_noc_spio_scram_axi_ARLEN        ),
      .spio_noc_spio_scram_axi_ARBURST       (spio_noc_spio_scram_axi_ARBURST      ),
      .spio_noc_spio_scram_axi_ARCACHE       (spio_noc_spio_scram_axi_ARCACHE      ),
      .spio_noc_spio_scram_axi_ARLOCK        (spio_noc_spio_scram_axi_ARLOCK       ),
      .spio_noc_spio_scram_axi_ARPROT        (spio_noc_spio_scram_axi_ARPROT       ),
      .spio_noc_spio_scram_axi_ARSIZE        (spio_noc_spio_scram_axi_ARSIZE       ),
      .spio_noc_spio_scram_axi_ARVALID       (spio_noc_spio_scram_axi_ARVALID      ),
      .spio_noc_spio_scram_axi_ARREADY       (spio_noc_spio_scram_axi_ARREADY      ),
      .spio_noc_spio_scram_axi_AWADDR        (spio_noc_spio_scram_axi_AWADDR       ),
      .spio_noc_spio_scram_axi_AWID          (spio_noc_spio_scram_axi_AWID         ),
      .spio_noc_spio_scram_axi_AWQOS         (spio_noc_spio_scram_axi_AWQOS        ),
      .spio_noc_spio_scram_axi_AWLEN         (spio_noc_spio_scram_axi_AWLEN        ),
      .spio_noc_spio_scram_axi_AWBURST       (spio_noc_spio_scram_axi_AWBURST      ),
      .spio_noc_spio_scram_axi_AWCACHE       (spio_noc_spio_scram_axi_AWCACHE      ),
      .spio_noc_spio_scram_axi_AWLOCK        (spio_noc_spio_scram_axi_AWLOCK       ),
      .spio_noc_spio_scram_axi_AWPROT        (spio_noc_spio_scram_axi_AWPROT       ),
      .spio_noc_spio_scram_axi_AWSIZE        (spio_noc_spio_scram_axi_AWSIZE       ),
      .spio_noc_spio_scram_axi_AWVALID       (spio_noc_spio_scram_axi_AWVALID      ),
      .spio_noc_spio_scram_axi_AWREADY       (spio_noc_spio_scram_axi_AWREADY      ),
      .spio_noc_spio_scram_axi_WDATA         (spio_noc_spio_scram_axi_WDATA        ),
      .spio_noc_spio_scram_axi_WSTRB         (spio_noc_spio_scram_axi_WSTRB        ),
      .spio_noc_spio_scram_axi_WLAST         (spio_noc_spio_scram_axi_WLAST        ),
      .spio_noc_spio_scram_axi_WVALID        (spio_noc_spio_scram_axi_WVALID       ),
      .spio_noc_spio_scram_axi_WREADY        (spio_noc_spio_scram_axi_WREADY       ),
      .spio_noc_spio_scram_axi_BID           (spio_noc_spio_scram_axi_BID          ),
      .spio_noc_spio_scram_axi_BRESP         (spio_noc_spio_scram_axi_BRESP        ),
      .spio_noc_spio_scram_axi_BVALID        (spio_noc_spio_scram_axi_BVALID       ),
      .spio_noc_spio_scram_axi_BREADY        (spio_noc_spio_scram_axi_BREADY       ),
      .spio_noc_spio_scram_axi_RDATA         (spio_noc_spio_scram_axi_RDATA        ),
      .spio_noc_spio_scram_axi_RID           (spio_noc_spio_scram_axi_RID          ),
      .spio_noc_spio_scram_axi_RLAST         (spio_noc_spio_scram_axi_RLAST        ),
      .spio_noc_spio_scram_axi_RRESP         (spio_noc_spio_scram_axi_RRESP        ),
      .spio_noc_spio_scram_axi_RVALID        (spio_noc_spio_scram_axi_RVALID       ),
      .spio_noc_spio_scram_axi_RREADY        (spio_noc_spio_scram_axi_RREADY       ),

      .spio_sp_spio_noc_axi_ARQOS            (spio_sp_spio_noc_axi_ARQOS           ),
      .spio_sp_spio_noc_axi_AWQOS            (spio_sp_spio_noc_axi_AWQOS           ),
      .spio_sp_spio_noc_axi_AWUSER           (spio_sp_spio_noc_axi_AWUSER          ),
      .spio_sp_spio_noc_axi_ARADDR           (spio_sp_spio_noc_axi_ARADDR          ),
      .spio_sp_spio_noc_axi_ARID             (spio_sp_spio_noc_axi_ARID            ),
      .spio_sp_spio_noc_axi_ARLEN            (spio_sp_spio_noc_axi_ARLEN           ),
      .spio_sp_spio_noc_axi_ARBURST          (spio_sp_spio_noc_axi_ARBURST         ),
      .spio_sp_spio_noc_axi_ARCACHE          (spio_sp_spio_noc_axi_ARCACHE         ),
      .spio_sp_spio_noc_axi_ARLOCK           (spio_sp_spio_noc_axi_ARLOCK          ),
      .spio_sp_spio_noc_axi_ARPROT           (spio_sp_spio_noc_axi_ARPROT          ),
      .spio_sp_spio_noc_axi_ARSIZE           (spio_sp_spio_noc_axi_ARSIZE          ),
      .spio_sp_spio_noc_axi_ARVALID          (spio_sp_spio_noc_axi_ARVALID         ),
      .spio_sp_spio_noc_axi_ARREADY          (spio_sp_spio_noc_axi_ARREADY         ),
      .spio_sp_spio_noc_axi_AWADDR           (spio_sp_spio_noc_axi_AWADDR          ),
      .spio_sp_spio_noc_axi_AWID             (spio_sp_spio_noc_axi_AWID            ),
      .spio_sp_spio_noc_axi_AWLEN            (spio_sp_spio_noc_axi_AWLEN           ),
      .spio_sp_spio_noc_axi_AWBURST          (spio_sp_spio_noc_axi_AWBURST         ),
      .spio_sp_spio_noc_axi_AWCACHE          (spio_sp_spio_noc_axi_AWCACHE         ),
      .spio_sp_spio_noc_axi_AWLOCK           (spio_sp_spio_noc_axi_AWLOCK          ),
      .spio_sp_spio_noc_axi_AWPROT           (spio_sp_spio_noc_axi_AWPROT          ),
      .spio_sp_spio_noc_axi_AWSIZE           (spio_sp_spio_noc_axi_AWSIZE          ),
      .spio_sp_spio_noc_axi_AWVALID          (spio_sp_spio_noc_axi_AWVALID         ),
      .spio_sp_spio_noc_axi_AWREADY          (spio_sp_spio_noc_axi_AWREADY         ),
      .spio_sp_spio_noc_axi_WDATA            (spio_sp_spio_noc_axi_WDATA           ),
      .spio_sp_spio_noc_axi_WSTRB            (spio_sp_spio_noc_axi_WSTRB           ),
      .spio_sp_spio_noc_axi_WLAST            (spio_sp_spio_noc_axi_WLAST           ),
      .spio_sp_spio_noc_axi_WVALID           (spio_sp_spio_noc_axi_WVALID          ),
      .spio_sp_spio_noc_axi_WREADY           (spio_sp_spio_noc_axi_WREADY          ),
      .spio_sp_spio_noc_axi_BID              (spio_sp_spio_noc_axi_BID             ),
      .spio_sp_spio_noc_axi_BRESP            (spio_sp_spio_noc_axi_BRESP           ),
      .spio_sp_spio_noc_axi_BVALID           (spio_sp_spio_noc_axi_BVALID          ),
      .spio_sp_spio_noc_axi_BREADY           (spio_sp_spio_noc_axi_BREADY          ),
      .spio_sp_spio_noc_axi_RDATA            (spio_sp_spio_noc_axi_RDATA           ),
      .spio_sp_spio_noc_axi_RID              (spio_sp_spio_noc_axi_RID             ),
      .spio_sp_spio_noc_axi_RLAST            (spio_sp_spio_noc_axi_RLAST           ),
      .spio_sp_spio_noc_axi_RRESP            (spio_sp_spio_noc_axi_RRESP           ),
      .spio_sp_spio_noc_axi_RVALID           (spio_sp_spio_noc_axi_RVALID          ),
      .spio_sp_spio_noc_axi_RREADY           (spio_sp_spio_noc_axi_RREADY          ),

      .spio_noc_dbg_comm_axi_ARREADY         (spio_noc_dbg_comm_axi_ARREADY        ),
      .spio_noc_dbg_comm_axi_AWREADY         (spio_noc_dbg_comm_axi_AWREADY        ),
      .spio_noc_dbg_comm_axi_BID             (spio_noc_dbg_comm_axi_BID            ),
      .spio_noc_dbg_comm_axi_BRESP           (spio_noc_dbg_comm_axi_BRESP          ),
      .spio_noc_dbg_comm_axi_BVALID          (spio_noc_dbg_comm_axi_BVALID         ),
      .spio_noc_dbg_comm_axi_RDATA           (spio_noc_dbg_comm_axi_RDATA          ),
      .spio_noc_dbg_comm_axi_RID             (spio_noc_dbg_comm_axi_RID            ),
      .spio_noc_dbg_comm_axi_RLAST           (spio_noc_dbg_comm_axi_RLAST          ),
      .spio_noc_dbg_comm_axi_RRESP           (spio_noc_dbg_comm_axi_RRESP          ),
      .spio_noc_dbg_comm_axi_RVALID          (spio_noc_dbg_comm_axi_RVALID         ),
      .spio_noc_dbg_comm_axi_WREADY          (spio_noc_dbg_comm_axi_WREADY         ),
      .spio_noc_dbg_comm_axi_ARADDR          (spio_noc_dbg_comm_axi_ARADDR         ),
      .spio_noc_dbg_comm_axi_ARBURST         (spio_noc_dbg_comm_axi_ARBURST        ),
      .spio_noc_dbg_comm_axi_ARCACHE         (spio_noc_dbg_comm_axi_ARCACHE        ),
      .spio_noc_dbg_comm_axi_ARID            (spio_noc_dbg_comm_axi_ARID           ),
      .spio_noc_dbg_comm_axi_ARLEN           (spio_noc_dbg_comm_axi_ARLEN          ),
      .spio_noc_dbg_comm_axi_ARLOCK          (spio_noc_dbg_comm_axi_ARLOCK         ),
      .spio_noc_dbg_comm_axi_ARPROT          (spio_noc_dbg_comm_axi_ARPROT         ),
      .spio_noc_dbg_comm_axi_ARQOS           (spio_noc_dbg_comm_axi_ARQOS          ),
      .spio_noc_dbg_comm_axi_ARSIZE          (spio_noc_dbg_comm_axi_ARSIZE         ),
      .spio_noc_dbg_comm_axi_ARVALID         (spio_noc_dbg_comm_axi_ARVALID        ),
      .spio_noc_dbg_comm_axi_AWADDR          (spio_noc_dbg_comm_axi_AWADDR         ),
      .spio_noc_dbg_comm_axi_AWBURST         (spio_noc_dbg_comm_axi_AWBURST        ),
      .spio_noc_dbg_comm_axi_AWCACHE         (spio_noc_dbg_comm_axi_AWCACHE        ),
      .spio_noc_dbg_comm_axi_AWID            (spio_noc_dbg_comm_axi_AWID           ),
      .spio_noc_dbg_comm_axi_AWLEN           (spio_noc_dbg_comm_axi_AWLEN          ),
      .spio_noc_dbg_comm_axi_AWLOCK          (spio_noc_dbg_comm_axi_AWLOCK         ),
      .spio_noc_dbg_comm_axi_AWPROT          (spio_noc_dbg_comm_axi_AWPROT         ),
      .spio_noc_dbg_comm_axi_AWQOS           (spio_noc_dbg_comm_axi_AWQOS          ),
      .spio_noc_dbg_comm_axi_AWSIZE          (spio_noc_dbg_comm_axi_AWSIZE         ),
      .spio_noc_dbg_comm_axi_AWVALID         (spio_noc_dbg_comm_axi_AWVALID        ),
      .spio_noc_dbg_comm_axi_BREADY          (spio_noc_dbg_comm_axi_BREADY         ),
      .spio_noc_dbg_comm_axi_RREADY          (spio_noc_dbg_comm_axi_RREADY         ),
      .spio_noc_dbg_comm_axi_WDATA           (spio_noc_dbg_comm_axi_WDATA          ),
      .spio_noc_dbg_comm_axi_WLAST           (spio_noc_dbg_comm_axi_WLAST          ),
      .spio_noc_dbg_comm_axi_WSTRB           (spio_noc_dbg_comm_axi_WSTRB          ),
      .spio_noc_dbg_comm_axi_WVALID          (spio_noc_dbg_comm_axi_WVALID         ),

      .spio_am_spio_noc_axi_ARADDR           (spio_am_spio_noc_axi_ARADDR          ),
      .spio_am_spio_noc_axi_ARBURST          (spio_am_spio_noc_axi_ARBURST         ),
      .spio_am_spio_noc_axi_ARCACHE          (spio_am_spio_noc_axi_ARCACHE         ),
      .spio_am_spio_noc_axi_ARID             (spio_am_spio_noc_axi_ARID            ),
      .spio_am_spio_noc_axi_ARLEN            (spio_am_spio_noc_axi_ARLEN           ),
      .spio_am_spio_noc_axi_ARLOCK           (spio_am_spio_noc_axi_ARLOCK          ),
      .spio_am_spio_noc_axi_ARPROT           (spio_am_spio_noc_axi_ARPROT          ),
      .spio_am_spio_noc_axi_ARQOS            (spio_am_spio_noc_axi_ARQOS           ),
      .spio_am_spio_noc_axi_ARSIZE           (spio_am_spio_noc_axi_ARSIZE          ),
      .spio_am_spio_noc_axi_ARVALID          (spio_am_spio_noc_axi_ARVALID         ),
      .spio_am_spio_noc_axi_AWADDR           (spio_am_spio_noc_axi_AWADDR          ),
      .spio_am_spio_noc_axi_AWBURST          (spio_am_spio_noc_axi_AWBURST         ),
      .spio_am_spio_noc_axi_AWCACHE          (spio_am_spio_noc_axi_AWCACHE         ),
      .spio_am_spio_noc_axi_AWID             (spio_am_spio_noc_axi_AWID            ),
      .spio_am_spio_noc_axi_AWLEN            (spio_am_spio_noc_axi_AWLEN           ),
      .spio_am_spio_noc_axi_AWLOCK           (spio_am_spio_noc_axi_AWLOCK          ),
      .spio_am_spio_noc_axi_AWPROT           (spio_am_spio_noc_axi_AWPROT          ),
      .spio_am_spio_noc_axi_AWQOS            (spio_am_spio_noc_axi_AWQOS           ),
      .spio_am_spio_noc_axi_AWSIZE           (spio_am_spio_noc_axi_AWSIZE          ),
      .spio_am_spio_noc_axi_AWVALID          (spio_am_spio_noc_axi_AWVALID         ),
      .spio_am_spio_noc_axi_BREADY           (spio_am_spio_noc_axi_BREADY          ),
      .spio_am_spio_noc_axi_RREADY           (spio_am_spio_noc_axi_RREADY          ),
      .spio_am_spio_noc_axi_WDATA            (spio_am_spio_noc_axi_WDATA           ),
      .spio_am_spio_noc_axi_WLAST            (spio_am_spio_noc_axi_WLAST           ),
      .spio_am_spio_noc_axi_WSTRB            (spio_am_spio_noc_axi_WSTRB           ),
      .spio_am_spio_noc_axi_WVALID           (spio_am_spio_noc_axi_WVALID          ),
      .spio_am_spio_noc_axi_ARREADY          (spio_am_spio_noc_axi_ARREADY         ),
      .spio_am_spio_noc_axi_AWREADY          (spio_am_spio_noc_axi_AWREADY         ),
      .spio_am_spio_noc_axi_BID              (spio_am_spio_noc_axi_BID             ),
      .spio_am_spio_noc_axi_BRESP            (spio_am_spio_noc_axi_BRESP           ),
      .spio_am_spio_noc_axi_BVALID           (spio_am_spio_noc_axi_BVALID          ),
      .spio_am_spio_noc_axi_RDATA            (spio_am_spio_noc_axi_RDATA           ),
      .spio_am_spio_noc_axi_RID              (spio_am_spio_noc_axi_RID             ),
      .spio_am_spio_noc_axi_RLAST            (spio_am_spio_noc_axi_RLAST           ),
      .spio_am_spio_noc_axi_RRESP            (spio_am_spio_noc_axi_RRESP           ),
      .spio_am_spio_noc_axi_RVALID           (spio_am_spio_noc_axi_RVALID          ),
      .spio_am_spio_noc_axi_WREADY           (spio_am_spio_noc_axi_WREADY          ),

      .spio_dma_spio_noc_axi_ARADDR          (spio_dma_spio_noc_axi_ARADDR         ),
      .spio_dma_spio_noc_axi_ARBURST         (spio_dma_spio_noc_axi_ARBURST        ),
      .spio_dma_spio_noc_axi_ARCACHE         (spio_dma_spio_noc_axi_ARCACHE        ),
      .spio_dma_spio_noc_axi_ARID            (spio_dma_spio_noc_axi_ARID           ),
      .spio_dma_spio_noc_axi_ARLEN           (spio_dma_spio_noc_axi_ARLEN          ),
      .spio_dma_spio_noc_axi_ARLOCK          (spio_dma_spio_noc_axi_ARLOCK         ),
      .spio_dma_spio_noc_axi_ARPROT          (spio_dma_spio_noc_axi_ARPROT         ),
      .spio_dma_spio_noc_axi_ARSIZE          (spio_dma_spio_noc_axi_ARSIZE         ),
      .spio_dma_spio_noc_axi_ARVALID         (spio_dma_spio_noc_axi_ARVALID        ),
      .spio_dma_spio_noc_axi_AWADDR          (spio_dma_spio_noc_axi_AWADDR         ),
      .spio_dma_spio_noc_axi_AWBURST         (spio_dma_spio_noc_axi_AWBURST        ),
      .spio_dma_spio_noc_axi_AWCACHE         (spio_dma_spio_noc_axi_AWCACHE        ),
      .spio_dma_spio_noc_axi_AWID            (spio_dma_spio_noc_axi_AWID           ),
      .spio_dma_spio_noc_axi_AWLEN           (spio_dma_spio_noc_axi_AWLEN          ),
      .spio_dma_spio_noc_axi_AWLOCK          (spio_dma_spio_noc_axi_AWLOCK         ),
      .spio_dma_spio_noc_axi_AWPROT          (spio_dma_spio_noc_axi_AWPROT         ),
      .spio_dma_spio_noc_axi_AWSIZE          (spio_dma_spio_noc_axi_AWSIZE         ),
      .spio_dma_spio_noc_axi_AWVALID         (spio_dma_spio_noc_axi_AWVALID        ),
      .spio_dma_spio_noc_axi_BREADY          (spio_dma_spio_noc_axi_BREADY         ),
      .spio_dma_spio_noc_axi_RREADY          (spio_dma_spio_noc_axi_RREADY         ),
      .spio_dma_spio_noc_axi_WDATA           (spio_dma_spio_noc_axi_WDATA          ),
      .spio_dma_spio_noc_axi_WID             (spio_dma_spio_noc_axi_WID            ),
      .spio_dma_spio_noc_axi_WLAST           (spio_dma_spio_noc_axi_WLAST          ),
      .spio_dma_spio_noc_axi_WSTRB           (spio_dma_spio_noc_axi_WSTRB          ),
      .spio_dma_spio_noc_axi_WVALID          (spio_dma_spio_noc_axi_WVALID         ),
      .spio_dma_spio_noc_axi_ARREADY         (spio_dma_spio_noc_axi_ARREADY        ),
      .spio_dma_spio_noc_axi_AWREADY         (spio_dma_spio_noc_axi_AWREADY        ),
      .spio_dma_spio_noc_axi_BID             (spio_dma_spio_noc_axi_BID            ),
      .spio_dma_spio_noc_axi_BRESP           (spio_dma_spio_noc_axi_BRESP          ),
      .spio_dma_spio_noc_axi_BVALID          (spio_dma_spio_noc_axi_BVALID         ),
      .spio_dma_spio_noc_axi_RDATA           (spio_dma_spio_noc_axi_RDATA          ),
      .spio_dma_spio_noc_axi_RID             (spio_dma_spio_noc_axi_RID            ),
      .spio_dma_spio_noc_axi_RLAST           (spio_dma_spio_noc_axi_RLAST          ),
      .spio_dma_spio_noc_axi_RRESP           (spio_dma_spio_noc_axi_RRESP          ),
      .spio_dma_spio_noc_axi_RVALID          (spio_dma_spio_noc_axi_RVALID         ),
      .spio_dma_spio_noc_axi_WREADY          (spio_dma_spio_noc_axi_WREADY         ),

      .spio_vault_spio_noc_axi_ARADDR        (spio_vault_spio_noc_axi_ARADDR       ),
      .spio_vault_spio_noc_axi_ARBURST       (spio_vault_spio_noc_axi_ARBURST      ),
      .spio_vault_spio_noc_axi_ARCACHE       (spio_vault_spio_noc_axi_ARCACHE      ),
      .spio_vault_spio_noc_axi_ARID          (spio_vault_spio_noc_axi_ARID         ),
      .spio_vault_spio_noc_axi_ARLEN         (spio_vault_spio_noc_axi_ARLEN        ),
      .spio_vault_spio_noc_axi_ARLOCK        (spio_vault_spio_noc_axi_ARLOCK       ),
      .spio_vault_spio_noc_axi_ARPROT        (spio_vault_spio_noc_axi_ARPROT       ),
      .spio_vault_spio_noc_axi_ARQOS         (spio_vault_spio_noc_axi_ARQOS        ),
      .spio_vault_spio_noc_axi_ARSIZE        (spio_vault_spio_noc_axi_ARSIZE       ),
      .spio_vault_spio_noc_axi_ARVALID       (spio_vault_spio_noc_axi_ARVALID      ),
      .spio_vault_spio_noc_axi_AWADDR        (spio_vault_spio_noc_axi_AWADDR       ),
      .spio_vault_spio_noc_axi_AWBURST       (spio_vault_spio_noc_axi_AWBURST      ),
      .spio_vault_spio_noc_axi_AWCACHE       (spio_vault_spio_noc_axi_AWCACHE      ),
      .spio_vault_spio_noc_axi_AWID          (spio_vault_spio_noc_axi_AWID         ),
      .spio_vault_spio_noc_axi_AWLEN         (spio_vault_spio_noc_axi_AWLEN        ),
      .spio_vault_spio_noc_axi_AWLOCK        (spio_vault_spio_noc_axi_AWLOCK       ),
      .spio_vault_spio_noc_axi_AWPROT        (spio_vault_spio_noc_axi_AWPROT       ),
      .spio_vault_spio_noc_axi_AWQOS         (spio_vault_spio_noc_axi_AWQOS        ),
      .spio_vault_spio_noc_axi_AWSIZE        (spio_vault_spio_noc_axi_AWSIZE       ),
      .spio_vault_spio_noc_axi_AWVALID       (spio_vault_spio_noc_axi_AWVALID      ),
      .spio_vault_spio_noc_axi_BREADY        (spio_vault_spio_noc_axi_BREADY       ),
      .spio_vault_spio_noc_axi_RREADY        (spio_vault_spio_noc_axi_RREADY       ),
      .spio_vault_spio_noc_axi_WDATA         (spio_vault_spio_noc_axi_WDATA        ),
      .spio_vault_spio_noc_axi_WLAST         (spio_vault_spio_noc_axi_WLAST        ),
      .spio_vault_spio_noc_axi_WSTRB         (spio_vault_spio_noc_axi_WSTRB        ),
      .spio_vault_spio_noc_axi_WVALID        (spio_vault_spio_noc_axi_WVALID       ),
      .spio_vault_spio_noc_axi_ARREADY       (spio_vault_spio_noc_axi_ARREADY      ),
      .spio_vault_spio_noc_axi_AWREADY       (spio_vault_spio_noc_axi_AWREADY      ),
      .spio_vault_spio_noc_axi_BID           (spio_vault_spio_noc_axi_BID          ),
      .spio_vault_spio_noc_axi_BRESP         (spio_vault_spio_noc_axi_BRESP        ),
      .spio_vault_spio_noc_axi_BVALID        (spio_vault_spio_noc_axi_BVALID       ),
      .spio_vault_spio_noc_axi_RDATA         (spio_vault_spio_noc_axi_RDATA        ),
      .spio_vault_spio_noc_axi_RID           (spio_vault_spio_noc_axi_RID          ),
      .spio_vault_spio_noc_axi_RLAST         (spio_vault_spio_noc_axi_RLAST        ),
      .spio_vault_spio_noc_axi_RRESP         (spio_vault_spio_noc_axi_RRESP        ),
      .spio_vault_spio_noc_axi_RVALID        (spio_vault_spio_noc_axi_RVALID       ),
      .spio_vault_spio_noc_axi_WREADY        (spio_vault_spio_noc_axi_WREADY       ),

      .spio_p10_pcie_s_ARREADY               (spio_p10_pcie_s_ARREADY              ),
      .spio_p10_pcie_s_AWREADY               (spio_p10_pcie_s_AWREADY              ),
      .spio_p10_pcie_s_BID                   (spio_p10_pcie_s_BID                  ),
      .spio_p10_pcie_s_BRESP                 (spio_p10_pcie_s_BRESP                ),
      .spio_p10_pcie_s_BVALID                (spio_p10_pcie_s_BVALID               ),
      .spio_p10_pcie_s_RDATA                 (spio_p10_pcie_s_RDATA                ),
      .spio_p10_pcie_s_RID                   (spio_p10_pcie_s_RID                  ),
      .spio_p10_pcie_s_RLAST                 (spio_p10_pcie_s_RLAST                ),
      .spio_p10_pcie_s_RRESP                 (spio_p10_pcie_s_RRESP                ),
      .spio_p10_pcie_s_RVALID                (spio_p10_pcie_s_RVALID               ),
      .spio_p10_pcie_s_WREADY                (spio_p10_pcie_s_WREADY               ),
      .spio_p10_pcie_s_ARADDR                (spio_p10_pcie_s_ARADDR               ),
      .spio_p10_pcie_s_ARBURST               (spio_p10_pcie_s_ARBURST              ),
      .spio_p10_pcie_s_ARCACHE               (spio_p10_pcie_s_ARCACHE              ),
      .spio_p10_pcie_s_ARID                  (spio_p10_pcie_s_ARID                 ),
      .spio_p10_pcie_s_ARLEN                 (spio_p10_pcie_s_ARLEN                ),
      .spio_p10_pcie_s_ARLOCK                (spio_p10_pcie_s_ARLOCK               ),
      .spio_p10_pcie_s_ARPROT                (spio_p10_pcie_s_ARPROT               ),
      .spio_p10_pcie_s_ARQOS                 (spio_p10_pcie_s_ARQOS                ),
      .spio_p10_pcie_s_ARSIZE                (spio_p10_pcie_s_ARSIZE               ),
      .spio_p10_pcie_s_ARVALID               (spio_p10_pcie_s_ARVALID              ),
      .spio_p10_pcie_s_AWADDR                (spio_p10_pcie_s_AWADDR               ),
      .spio_p10_pcie_s_AWBURST               (spio_p10_pcie_s_AWBURST              ),
      .spio_p10_pcie_s_AWCACHE               (spio_p10_pcie_s_AWCACHE              ),
      .spio_p10_pcie_s_AWID                  (spio_p10_pcie_s_AWID                 ),
      .spio_p10_pcie_s_AWLEN                 (spio_p10_pcie_s_AWLEN                ),
      .spio_p10_pcie_s_AWLOCK                (spio_p10_pcie_s_AWLOCK               ),
      .spio_p10_pcie_s_AWPROT                (spio_p10_pcie_s_AWPROT               ),
      .spio_p10_pcie_s_AWQOS                 (spio_p10_pcie_s_AWQOS                ),
      .spio_p10_pcie_s_AWSIZE                (spio_p10_pcie_s_AWSIZE               ),
      .spio_p10_pcie_s_AWVALID               (spio_p10_pcie_s_AWVALID              ),
      .spio_p10_pcie_s_BREADY                (spio_p10_pcie_s_BREADY               ),
      .spio_p10_pcie_s_RREADY                (spio_p10_pcie_s_RREADY               ),
      .spio_p10_pcie_s_WDATA                 (spio_p10_pcie_s_WDATA                ),
      .spio_p10_pcie_s_WLAST                 (spio_p10_pcie_s_WLAST                ),
      .spio_p10_pcie_s_WSTRB                 (spio_p10_pcie_s_WSTRB                ),
      .spio_p10_pcie_s_WVALID                (spio_p10_pcie_s_WVALID               ),

      .spio_sp_main0_main_noc_rbm_s_AWVALID  (spio_sp_main0_main_noc_rbm_s_AWVALID ),
      .spio_sp_main0_main_noc_rbm_s_AWREADY  (spio_sp_main0_main_noc_rbm_s_AWREADY ),
      .spio_sp_main0_main_noc_rbm_s_AWADDR   (spio_sp_main0_main_noc_rbm_s_AWADDR  ),
      .spio_sp_main0_main_noc_rbm_s_AWPROT   (spio_sp_main0_main_noc_rbm_s_AWPROT  ),
      .spio_sp_main0_main_noc_rbm_s_WVALID   (spio_sp_main0_main_noc_rbm_s_WVALID  ),
      .spio_sp_main0_main_noc_rbm_s_WREADY   (spio_sp_main0_main_noc_rbm_s_WREADY  ),
      .spio_sp_main0_main_noc_rbm_s_WDATA    (spio_sp_main0_main_noc_rbm_s_WDATA   ),
      .spio_sp_main0_main_noc_rbm_s_WSTRB    (spio_sp_main0_main_noc_rbm_s_WSTRB   ),
      .spio_sp_main0_main_noc_rbm_s_BVALID   (spio_sp_main0_main_noc_rbm_s_BVALID  ),
      .spio_sp_main0_main_noc_rbm_s_BREADY   (spio_sp_main0_main_noc_rbm_s_BREADY  ),
      .spio_sp_main0_main_noc_rbm_s_BRESP    (spio_sp_main0_main_noc_rbm_s_BRESP   ),
      .spio_sp_main0_main_noc_rbm_s_ARVALID  (spio_sp_main0_main_noc_rbm_s_ARVALID ),
      .spio_sp_main0_main_noc_rbm_s_ARREADY  (spio_sp_main0_main_noc_rbm_s_ARREADY ),
      .spio_sp_main0_main_noc_rbm_s_ARADDR   (spio_sp_main0_main_noc_rbm_s_ARADDR  ),
      .spio_sp_main0_main_noc_rbm_s_ARPROT   (spio_sp_main0_main_noc_rbm_s_ARPROT  ),
      .spio_sp_main0_main_noc_rbm_s_RVALID   (spio_sp_main0_main_noc_rbm_s_RVALID  ),
      .spio_sp_main0_main_noc_rbm_s_RREADY   (spio_sp_main0_main_noc_rbm_s_RREADY  ),
      .spio_sp_main0_main_noc_rbm_s_RDATA    (spio_sp_main0_main_noc_rbm_s_RDATA   ),
      .spio_sp_main0_main_noc_rbm_s_RRESP    (spio_sp_main0_main_noc_rbm_s_RRESP   ),

      .spio_p10_pcie_rbm_s_ARREADY           (spio_p10_pcie_rbm_s_ARREADY          ),
      .spio_p10_pcie_rbm_s_AWREADY           (spio_p10_pcie_rbm_s_AWREADY          ),
      .spio_p10_pcie_rbm_s_BRESP             (spio_p10_pcie_rbm_s_BRESP            ),
      .spio_p10_pcie_rbm_s_BVALID            (spio_p10_pcie_rbm_s_BVALID           ),
      .spio_p10_pcie_rbm_s_RDATA             (spio_p10_pcie_rbm_s_RDATA            ),
      .spio_p10_pcie_rbm_s_RRESP             (spio_p10_pcie_rbm_s_RRESP            ),
      .spio_p10_pcie_rbm_s_RVALID            (spio_p10_pcie_rbm_s_RVALID           ),
      .spio_p10_pcie_rbm_s_WREADY            (spio_p10_pcie_rbm_s_WREADY           ),
      .spio_p10_pcie_rbm_s_ARADDR            (spio_p10_pcie_rbm_s_ARADDR           ),
      .spio_p10_pcie_rbm_s_ARPROT            (spio_p10_pcie_rbm_s_ARPROT           ),
      .spio_p10_pcie_rbm_s_ARVALID           (spio_p10_pcie_rbm_s_ARVALID          ),
      .spio_p10_pcie_rbm_s_AWADDR            (spio_p10_pcie_rbm_s_AWADDR           ),
      .spio_p10_pcie_rbm_s_AWPROT            (spio_p10_pcie_rbm_s_AWPROT           ),
      .spio_p10_pcie_rbm_s_AWVALID           (spio_p10_pcie_rbm_s_AWVALID          ),
      .spio_p10_pcie_rbm_s_BREADY            (spio_p10_pcie_rbm_s_BREADY           ),
      .spio_p10_pcie_rbm_s_RREADY            (spio_p10_pcie_rbm_s_RREADY           ),
      .spio_p10_pcie_rbm_s_WDATA             (spio_p10_pcie_rbm_s_WDATA            ),
      .spio_p10_pcie_rbm_s_WSTRB             (spio_p10_pcie_rbm_s_WSTRB            ),
      .spio_p10_pcie_rbm_s_WVALID            (spio_p10_pcie_rbm_s_WVALID           ),

      .spio_noc_pu_noc_regbus_axi_ARREADY    (spio_noc_pu_noc_regbus_axi_ARREADY   ),
      .spio_noc_pu_noc_regbus_axi_AWREADY    (spio_noc_pu_noc_regbus_axi_AWREADY   ),
      .spio_noc_pu_noc_regbus_axi_BRESP      (spio_noc_pu_noc_regbus_axi_BRESP     ),
      .spio_noc_pu_noc_regbus_axi_BVALID     (spio_noc_pu_noc_regbus_axi_BVALID    ),
      .spio_noc_pu_noc_regbus_axi_RDATA      (spio_noc_pu_noc_regbus_axi_RDATA     ),
      .spio_noc_pu_noc_regbus_axi_RRESP      (spio_noc_pu_noc_regbus_axi_RRESP     ),
      .spio_noc_pu_noc_regbus_axi_RVALID     (spio_noc_pu_noc_regbus_axi_RVALID    ),
      .spio_noc_pu_noc_regbus_axi_WREADY     (spio_noc_pu_noc_regbus_axi_WREADY    ),
`ifdef IOSHIRE_WRAPPER_GATESIM					      
      .spio_noc_pu_noc_regbus_axi_ARADDR     ({8'b0,spio_noc_pu_noc_regbus_axi_ARADDR}    ),
`else
      .spio_noc_pu_noc_regbus_axi_ARADDR     (spio_noc_pu_noc_regbus_axi_ARADDR    ),
`endif					     
      .spio_noc_pu_noc_regbus_axi_ARPROT     (spio_noc_pu_noc_regbus_axi_ARPROT    ),
      .spio_noc_pu_noc_regbus_axi_ARVALID    (spio_noc_pu_noc_regbus_axi_ARVALID   ),
`ifdef IOSHIRE_WRAPPER_GATESIM					      
      .spio_noc_pu_noc_regbus_axi_AWADDR     ({8'b0,spio_noc_pu_noc_regbus_axi_AWADDR}    ),
`else
      .spio_noc_pu_noc_regbus_axi_AWADDR     (spio_noc_pu_noc_regbus_axi_AWADDR    ),
`endif					      
      .spio_noc_pu_noc_regbus_axi_AWPROT     (spio_noc_pu_noc_regbus_axi_AWPROT    ),
      .spio_noc_pu_noc_regbus_axi_AWVALID    (spio_noc_pu_noc_regbus_axi_AWVALID   ),
      .spio_noc_pu_noc_regbus_axi_BREADY     (spio_noc_pu_noc_regbus_axi_BREADY    ),
      .spio_noc_pu_noc_regbus_axi_RREADY     (spio_noc_pu_noc_regbus_axi_RREADY    ),
      .spio_noc_pu_noc_regbus_axi_WDATA      (spio_noc_pu_noc_regbus_axi_WDATA     ),
      .spio_noc_pu_noc_regbus_axi_WSTRB      (spio_noc_pu_noc_regbus_axi_WSTRB     ),
      .spio_noc_pu_noc_regbus_axi_WVALID     (spio_noc_pu_noc_regbus_axi_WVALID    ),

      .host_beat_data_io0_lf_msg       (host_beat_data_io0_lf_msg  ),
      .host_beat_eop_io0_lf_msg        (host_beat_eop_io0_lf_msg   ),
      .host_beat_sop_io0_lf_msg        (host_beat_sop_io0_lf_msg   ),
      .host_beat_valid_io0_lf_msg      (host_beat_valid_io0_lf_msg ),
      .host_credit_inc_io0_lf_msg      (host_credit_inc_io0_lf_msg ),
      .host_dest_hp_io0_lf_msg         (host_dest_hp_io0_lf_msg    ),
      .host_dest_int_io0_lf_msg        (host_dest_int_io0_lf_msg   ),
      .host_xfer_qos_io0_lf_msg        (host_xfer_qos_io0_lf_msg   ),
      .noc_beat_data_io0_lf_msg        (noc_beat_data_io0_lf_msg   ),
      .noc_beat_eop_io0_lf_msg         (noc_beat_eop_io0_lf_msg    ),
      .noc_beat_sop_io0_lf_msg         (noc_beat_sop_io0_lf_msg    ),
      .noc_beat_valid_io0_lf_msg       (noc_beat_valid_io0_lf_msg  ),
      .noc_credit_inc_io0_lf_msg       (noc_credit_inc_io0_lf_msg  ),
                                                                  
      .host_beat_data_io0_lf_evt       (host_beat_data_io0_lf_evt  ),
      .host_beat_eop_io0_lf_evt        (host_beat_eop_io0_lf_evt   ),
      .host_beat_sop_io0_lf_evt        (host_beat_sop_io0_lf_evt   ),
      .host_beat_valid_io0_lf_evt      (host_beat_valid_io0_lf_evt ),
      .host_credit_inc_io0_lf_evt      (host_credit_inc_io0_lf_evt ),
      .host_dest_hp_io0_lf_evt         (host_dest_hp_io0_lf_evt    ),
      .host_dest_int_io0_lf_evt        (host_dest_int_io0_lf_evt   ),
      .host_xfer_qos_io0_lf_evt        (host_xfer_qos_io0_lf_evt   ),
      .noc_beat_data_io0_lf_evt        (noc_beat_data_io0_lf_evt   ),
      .noc_beat_eop_io0_lf_evt         (noc_beat_eop_io0_lf_evt    ),
      .noc_beat_sop_io0_lf_evt         (noc_beat_sop_io0_lf_evt    ),
      .noc_beat_valid_io0_lf_evt       (noc_beat_valid_io0_lf_evt  ),
      .noc_credit_inc_io0_lf_evt       (noc_credit_inc_io0_lf_evt  ),
                                                                  
      .host_beat_data_io0_rt_msg       (host_beat_data_io0_rt_msg  ),
      .host_beat_eop_io0_rt_msg        (host_beat_eop_io0_rt_msg   ),
      .host_beat_sop_io0_rt_msg        (host_beat_sop_io0_rt_msg   ),
      .host_beat_valid_io0_rt_msg      (host_beat_valid_io0_rt_msg ),
      .host_credit_inc_io0_rt_msg      (host_credit_inc_io0_rt_msg ),
      .host_dest_hp_io0_rt_msg         (host_dest_hp_io0_rt_msg    ),
      .host_dest_int_io0_rt_msg        (host_dest_int_io0_rt_msg   ),
      .host_xfer_qos_io0_rt_msg        (host_xfer_qos_io0_rt_msg   ),
      .noc_beat_data_io0_rt_msg        (noc_beat_data_io0_rt_msg   ),
      .noc_beat_eop_io0_rt_msg         (noc_beat_eop_io0_rt_msg    ),
      .noc_beat_sop_io0_rt_msg         (noc_beat_sop_io0_rt_msg    ),
      .noc_beat_valid_io0_rt_msg       (noc_beat_valid_io0_rt_msg  ),
      .noc_credit_inc_io0_rt_msg       (noc_credit_inc_io0_rt_msg  ),
                                                                  
      .host_beat_data_io0_rt_evt       (host_beat_data_io0_rt_evt  ),
      .host_beat_eop_io0_rt_evt        (host_beat_eop_io0_rt_evt   ),
      .host_beat_sop_io0_rt_evt        (host_beat_sop_io0_rt_evt   ),
      .host_beat_valid_io0_rt_evt      (host_beat_valid_io0_rt_evt ),
      .host_credit_inc_io0_rt_evt      (host_credit_inc_io0_rt_evt ),
      .host_dest_hp_io0_rt_evt         (host_dest_hp_io0_rt_evt    ),
      .host_dest_int_io0_rt_evt        (host_dest_int_io0_rt_evt   ),
      .host_xfer_qos_io0_rt_evt        (host_xfer_qos_io0_rt_evt   ),
      .noc_beat_data_io0_rt_evt        (noc_beat_data_io0_rt_evt   ),
      .noc_beat_eop_io0_rt_evt         (noc_beat_eop_io0_rt_evt    ),
      .noc_beat_sop_io0_rt_evt         (noc_beat_sop_io0_rt_evt    ),
      .noc_beat_valid_io0_rt_evt       (noc_beat_valid_io0_rt_evt  ),
      .noc_credit_inc_io0_rt_evt       (noc_credit_inc_io0_rt_evt  )

   );

`endif // ifdef EVL_SIMULATION
