// Copyright (c) 2026 Ainekko
// SPDX-License-Identifier: Apache-2.0

// Generated by PeakRDL-regblock - A free and open-source SystemVerilog generator
//  https://github.com/SystemRDL/PeakRDL-regblock

package Erbium_ESR_pkg;

    localparam ERBIUM_ESR_DATA_WIDTH = 32;
    localparam ERBIUM_ESR_MIN_ADDR_WIDTH = 24;
    localparam ERBIUM_ESR_SIZE = 'hf40318;

    typedef struct {
        logic rd_ack;
        logic [31:0] rd_data;
        logic wr_ack;
    } U_neigh__external__in_t;

    typedef struct {
        logic rd_ack;
        logic [31:0] rd_data;
        logic wr_ack;
    } U_cpu__external__in_t;

    typedef struct {
        logic rd_ack;
        logic [31:0] rd_data;
        logic wr_ack;
    } S_cpu__external__in_t;

    typedef struct {
        logic rd_ack;
        logic [31:0] rd_data;
        logic wr_ack;
    } D_hart_esr__external__in_t;

    typedef struct {
        logic rd_ack;
        logic [31:0] rd_data;
        logic wr_ack;
    } D_neigh__external__in_t;

    typedef struct {
        logic rd_ack;
        logic [31:0] rd_data;
        logic wr_ack;
    } D_cpu__external__in_t;

    typedef struct {
        logic rd_ack;
        logic [31:0] rd_data;
        logic wr_ack;
    } M_neigh__external__in_t;

    typedef struct {
        logic rd_ack;
        logic [31:0] rd_data;
        logic wr_ack;
    } M_cpu__external__in_t;

    typedef struct {
        U_neigh__external__in_t User_neigh;
        U_cpu__external__in_t User_cpu;
        S_cpu__external__in_t Supervisor_cpu;
        D_hart_esr__external__in_t D_hart_esr;
        D_neigh__external__in_t D_neigh;
        D_cpu__external__in_t D_cpu;
        M_neigh__external__in_t Machine_neigh;
        M_cpu__external__in_t Machine_cpu;
    } Erbium_ESR__in_t;

    typedef struct {
        logic req;
        logic [6:0] addr;
        logic req_is_wr;
        logic [31:0] wr_data;
        logic [31:0] wr_biten;
    } U_neigh__external__out_t;

    typedef struct {
        logic req;
        logic [9:0] addr;
        logic req_is_wr;
        logic [31:0] wr_data;
        logic [31:0] wr_biten;
    } U_cpu__external__out_t;

    typedef struct {
        logic req;
        logic [9:0] addr;
        logic req_is_wr;
        logic [31:0] wr_data;
        logic [31:0] wr_biten;
    } S_cpu__external__out_t;

    typedef struct {
        logic req;
        logic [15:0] addr;
        logic req_is_wr;
        logic [31:0] wr_data;
        logic [31:0] wr_biten;
    } D_hart_esr__external__out_t;

    typedef struct {
        logic req;
        logic [15:0] addr;
        logic req_is_wr;
        logic [31:0] wr_data;
        logic [31:0] wr_biten;
    } D_neigh__external__out_t;

    typedef struct {
        logic req;
        logic [11:0] addr;
        logic req_is_wr;
        logic [31:0] wr_data;
        logic [31:0] wr_biten;
    } D_cpu__external__out_t;

    typedef struct {
        logic req;
        logic [7:0] addr;
        logic req_is_wr;
        logic [31:0] wr_data;
        logic [31:0] wr_biten;
    } M_neigh__external__out_t;

    typedef struct {
        logic req;
        logic [9:0] addr;
        logic req_is_wr;
        logic [31:0] wr_data;
        logic [31:0] wr_biten;
    } M_cpu__external__out_t;

    typedef struct {
        U_neigh__external__out_t User_neigh;
        U_cpu__external__out_t User_cpu;
        S_cpu__external__out_t Supervisor_cpu;
        D_hart_esr__external__out_t D_hart_esr;
        D_neigh__external__out_t D_neigh;
        D_cpu__external__out_t D_cpu;
        M_neigh__external__out_t Machine_neigh;
        M_cpu__external__out_t Machine_cpu;
    } Erbium_ESR__out_t;
endpackage
