// Copyright (c) 2026 Ainekko
// SPDX-License-Identifier: Apache-2.0

// Generated by PeakRDL-regblock - A free and open-source SystemVerilog generator
//  https://github.com/SystemRDL/PeakRDL-regblock

module Erbium_ESR (
        input wire clk,
        input wire arst_n,

        input wire s_apb_psel,
        input wire s_apb_penable,
        input wire s_apb_pwrite,
        input wire [2:0] s_apb_pprot,
        input wire [23:0] s_apb_paddr,
        input wire [31:0] s_apb_pwdata,
        input wire [3:0] s_apb_pstrb,
        output logic s_apb_pready,
        output logic [31:0] s_apb_prdata,
        output logic s_apb_pslverr,

        input Erbium_ESR_pkg::Erbium_ESR__in_t hwif_in,
        output Erbium_ESR_pkg::Erbium_ESR__out_t hwif_out
    );

    //--------------------------------------------------------------------------
    // CPU Bus interface logic
    //--------------------------------------------------------------------------
    logic cpuif_req;
    logic cpuif_req_is_wr;
    logic [23:0] cpuif_addr;
    logic [31:0] cpuif_wr_data;
    logic [31:0] cpuif_wr_biten;
    logic cpuif_req_stall_wr;
    logic cpuif_req_stall_rd;

    logic cpuif_rd_ack;
    logic cpuif_rd_err;
    logic [31:0] cpuif_rd_data;

    logic cpuif_wr_ack;
    logic cpuif_wr_err;

    // Request
    logic is_active;
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            is_active <= '0;
            cpuif_req <= '0;
            cpuif_req_is_wr <= '0;
            cpuif_addr <= '0;
            cpuif_wr_data <= '0;
            cpuif_wr_biten <= '0;
        end else begin
            if(~is_active) begin
                if(s_apb_psel) begin
                    is_active <= '1;
                    cpuif_req <= '1;
                    cpuif_req_is_wr <= s_apb_pwrite;
                    cpuif_addr <= {s_apb_paddr[23:2], 2'b0};
                    cpuif_wr_data <= s_apb_pwdata;
                    for(int i=0; i<4; i++) begin
                        cpuif_wr_biten[i*8 +: 8] <= {8{s_apb_pstrb[i]}};
                    end
                end
            end else begin
                cpuif_req <= '0;
                if(cpuif_rd_ack || cpuif_wr_ack) begin
                    is_active <= '0;
                end
            end
        end
    end

    // Response
    assign s_apb_pready = cpuif_rd_ack | cpuif_wr_ack;
    assign s_apb_prdata = cpuif_rd_data;
    assign s_apb_pslverr = cpuif_rd_err | cpuif_wr_err;

    logic cpuif_req_masked;
    logic external_pending;

    // Read & write latencies are balanced. Stalls not required
    // except if external
    assign cpuif_req_stall_rd = external_pending;
    assign cpuif_req_stall_wr = external_pending;
    assign cpuif_req_masked = cpuif_req
                            & !(!cpuif_req_is_wr & cpuif_req_stall_rd)
                            & !(cpuif_req_is_wr & cpuif_req_stall_wr);

    //--------------------------------------------------------------------------
    // Address Decode
    //--------------------------------------------------------------------------
    typedef struct {
        logic User_neigh;
        logic User_cpu;
        logic Supervisor_cpu;
        logic D_hart_esr;
        logic D_neigh;
        logic D_cpu;
        logic Machine_neigh;
        logic Machine_cpu;
    } decoded_reg_strb_t;
    decoded_reg_strb_t decoded_reg_strb;
    logic decoded_err;
    logic decoded_req_is_external;

    logic [23:0] decoded_addr;
    logic decoded_req;
    logic decoded_req_is_wr;
    logic [31:0] decoded_wr_data;
    logic [31:0] decoded_wr_biten;

    always_comb begin
        automatic logic is_valid_addr;
        automatic logic is_valid_rw;
        automatic logic is_external;
        is_external = '0;
        is_valid_addr = '1; // No valid address check
        is_valid_rw = '1; // No valid RW check
        decoded_reg_strb.User_neigh = cpuif_req_masked & (cpuif_addr >= 24'h100000) & (cpuif_addr <= 24'h100000 + 24'h47);
        is_external |= cpuif_req_masked & (cpuif_addr >= 24'h100000) & (cpuif_addr <= 24'h100000 + 24'h47);
        is_valid_rw |= cpuif_req_masked & (cpuif_addr >= 24'h100000) & (cpuif_addr <= 24'h100000 + 24'h47);
        decoded_reg_strb.User_cpu = cpuif_req_masked & (cpuif_addr >= 24'h340000) & (cpuif_addr <= 24'h340000 + 24'h2ff);
        is_external |= cpuif_req_masked & (cpuif_addr >= 24'h340000) & (cpuif_addr <= 24'h340000 + 24'h2ff);
        is_valid_rw |= cpuif_req_masked & (cpuif_addr >= 24'h340000) & (cpuif_addr <= 24'h340000 + 24'h2ff);
        decoded_reg_strb.Supervisor_cpu = cpuif_req_masked & (cpuif_addr >= 24'h740000) & (cpuif_addr <= 24'h740000 + 24'h307);
        is_external |= cpuif_req_masked & (cpuif_addr >= 24'h740000) & (cpuif_addr <= 24'h740000 + 24'h307);
        is_valid_rw |= cpuif_req_masked & (cpuif_addr >= 24'h740000) & (cpuif_addr <= 24'h740000 + 24'h307);
        decoded_reg_strb.D_hart_esr = cpuif_req_masked & (cpuif_addr >= 24'h800000) & (cpuif_addr <= 24'h800000 + 24'hffff);
        is_external |= cpuif_req_masked & (cpuif_addr >= 24'h800000) & (cpuif_addr <= 24'h800000 + 24'hffff);
        is_valid_rw |= cpuif_req_masked & (cpuif_addr >= 24'h800000) & (cpuif_addr <= 24'h800000 + 24'hffff);
        decoded_reg_strb.D_neigh = cpuif_req_masked & (cpuif_addr >= 24'h900000) & (cpuif_addr <= 24'h900000 + 24'hff9f);
        is_external |= cpuif_req_masked & (cpuif_addr >= 24'h900000) & (cpuif_addr <= 24'h900000 + 24'hff9f);
        is_valid_rw |= cpuif_req_masked & (cpuif_addr >= 24'h900000) & (cpuif_addr <= 24'h900000 + 24'hff9f);
        decoded_reg_strb.D_cpu = cpuif_req_masked & (cpuif_addr >= 24'hb5f000) & (cpuif_addr <= 24'hb5f000 + 24'hfd7);
        is_external |= cpuif_req_masked & (cpuif_addr >= 24'hb5f000) & (cpuif_addr <= 24'hb5f000 + 24'hfd7);
        is_valid_rw |= cpuif_req_masked & (cpuif_addr >= 24'hb5f000) & (cpuif_addr <= 24'hb5f000 + 24'hfd7);
        decoded_reg_strb.Machine_neigh = cpuif_req_masked & (cpuif_addr >= 24'hd00000) & (cpuif_addr <= 24'hd00000 + 24'h97);
        is_external |= cpuif_req_masked & (cpuif_addr >= 24'hd00000) & (cpuif_addr <= 24'hd00000 + 24'h97);
        is_valid_rw |= cpuif_req_masked & (cpuif_addr >= 24'hd00000) & (cpuif_addr <= 24'hd00000 + 24'h97);
        decoded_reg_strb.Machine_cpu = cpuif_req_masked & (cpuif_addr >= 24'hf40000) & (cpuif_addr <= 24'hf40000 + 24'h317);
        is_external |= cpuif_req_masked & (cpuif_addr >= 24'hf40000) & (cpuif_addr <= 24'hf40000 + 24'h317);
        is_valid_rw |= cpuif_req_masked & (cpuif_addr >= 24'hf40000) & (cpuif_addr <= 24'hf40000 + 24'h317);
        decoded_err = '0;
        decoded_req_is_external = is_external;
    end
    logic external_wr_ack;
    logic external_rd_ack;
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            external_pending <= '0;
        end else begin
            if(decoded_req_is_external & ~external_wr_ack & ~external_rd_ack) external_pending <= '1;
            else if(external_wr_ack | external_rd_ack) external_pending <= '0;
            `ifndef SYNTHESIS
                assert_bad_ext_wr_ack: assert(!external_wr_ack || (external_pending | decoded_req_is_external))
                    else $error("An external wr_ack strobe was asserted when no external request was active");
                assert_bad_ext_rd_ack: assert(!external_rd_ack || (external_pending | decoded_req_is_external))
                    else $error("An external rd_ack strobe was asserted when no external request was active");
            `endif
        end
    end

    // Pass down signals to next stage
    assign decoded_addr = cpuif_addr;
    assign decoded_req = cpuif_req_masked;
    assign decoded_req_is_wr = cpuif_req_is_wr;
    assign decoded_wr_data = cpuif_wr_data;
    assign decoded_wr_biten = cpuif_wr_biten;

    //--------------------------------------------------------------------------
    // Field logic
    //--------------------------------------------------------------------------
    

    

    // External region: Erbium_ESR.User_neigh
    assign hwif_out.User_neigh.req = decoded_reg_strb.User_neigh;
    assign hwif_out.User_neigh.addr = decoded_addr[6:0];
    assign hwif_out.User_neigh.req_is_wr = decoded_req_is_wr;
    assign hwif_out.User_neigh.wr_data = decoded_wr_data;
    assign hwif_out.User_neigh.wr_biten = decoded_wr_biten;
    // External region: Erbium_ESR.User_cpu
    assign hwif_out.User_cpu.req = decoded_reg_strb.User_cpu;
    assign hwif_out.User_cpu.addr = decoded_addr[9:0];
    assign hwif_out.User_cpu.req_is_wr = decoded_req_is_wr;
    assign hwif_out.User_cpu.wr_data = decoded_wr_data;
    assign hwif_out.User_cpu.wr_biten = decoded_wr_biten;
    // External region: Erbium_ESR.Supervisor_cpu
    assign hwif_out.Supervisor_cpu.req = decoded_reg_strb.Supervisor_cpu;
    assign hwif_out.Supervisor_cpu.addr = decoded_addr[9:0];
    assign hwif_out.Supervisor_cpu.req_is_wr = decoded_req_is_wr;
    assign hwif_out.Supervisor_cpu.wr_data = decoded_wr_data;
    assign hwif_out.Supervisor_cpu.wr_biten = decoded_wr_biten;
    // External region: Erbium_ESR.D_hart_esr
    assign hwif_out.D_hart_esr.req = decoded_reg_strb.D_hart_esr;
    assign hwif_out.D_hart_esr.addr = decoded_addr[15:0];
    assign hwif_out.D_hart_esr.req_is_wr = decoded_req_is_wr;
    assign hwif_out.D_hart_esr.wr_data = decoded_wr_data;
    assign hwif_out.D_hart_esr.wr_biten = decoded_wr_biten;
    // External region: Erbium_ESR.D_neigh
    assign hwif_out.D_neigh.req = decoded_reg_strb.D_neigh;
    assign hwif_out.D_neigh.addr = decoded_addr[15:0];
    assign hwif_out.D_neigh.req_is_wr = decoded_req_is_wr;
    assign hwif_out.D_neigh.wr_data = decoded_wr_data;
    assign hwif_out.D_neigh.wr_biten = decoded_wr_biten;
    // External region: Erbium_ESR.D_cpu
    assign hwif_out.D_cpu.req = decoded_reg_strb.D_cpu;
    assign hwif_out.D_cpu.addr = decoded_addr[11:0];
    assign hwif_out.D_cpu.req_is_wr = decoded_req_is_wr;
    assign hwif_out.D_cpu.wr_data = decoded_wr_data;
    assign hwif_out.D_cpu.wr_biten = decoded_wr_biten;
    // External region: Erbium_ESR.Machine_neigh
    assign hwif_out.Machine_neigh.req = decoded_reg_strb.Machine_neigh;
    assign hwif_out.Machine_neigh.addr = decoded_addr[7:0];
    assign hwif_out.Machine_neigh.req_is_wr = decoded_req_is_wr;
    assign hwif_out.Machine_neigh.wr_data = decoded_wr_data;
    assign hwif_out.Machine_neigh.wr_biten = decoded_wr_biten;
    // External region: Erbium_ESR.Machine_cpu
    assign hwif_out.Machine_cpu.req = decoded_reg_strb.Machine_cpu;
    assign hwif_out.Machine_cpu.addr = decoded_addr[9:0];
    assign hwif_out.Machine_cpu.req_is_wr = decoded_req_is_wr;
    assign hwif_out.Machine_cpu.wr_data = decoded_wr_data;
    assign hwif_out.Machine_cpu.wr_biten = decoded_wr_biten;

    //--------------------------------------------------------------------------
    // Write response
    //--------------------------------------------------------------------------
    always_comb begin
        automatic logic wr_ack;
        wr_ack = '0;
        wr_ack |= hwif_in.User_neigh.wr_ack;
        wr_ack |= hwif_in.User_cpu.wr_ack;
        wr_ack |= hwif_in.Supervisor_cpu.wr_ack;
        wr_ack |= hwif_in.D_hart_esr.wr_ack;
        wr_ack |= hwif_in.D_neigh.wr_ack;
        wr_ack |= hwif_in.D_cpu.wr_ack;
        wr_ack |= hwif_in.Machine_neigh.wr_ack;
        wr_ack |= hwif_in.Machine_cpu.wr_ack;
        external_wr_ack = wr_ack;
    end
    assign cpuif_wr_ack = external_wr_ack | (decoded_req & decoded_req_is_wr & ~decoded_req_is_external);
    // Writes are always granted with no error response
    assign cpuif_wr_err = '0;

    //--------------------------------------------------------------------------
    // Readback
    //--------------------------------------------------------------------------
    logic readback_external_rd_ack_c;
    always_comb begin
        automatic logic rd_ack;
        rd_ack = '0;
        rd_ack |= hwif_in.User_neigh.rd_ack;
        rd_ack |= hwif_in.User_cpu.rd_ack;
        rd_ack |= hwif_in.Supervisor_cpu.rd_ack;
        rd_ack |= hwif_in.D_hart_esr.rd_ack;
        rd_ack |= hwif_in.D_neigh.rd_ack;
        rd_ack |= hwif_in.D_cpu.rd_ack;
        rd_ack |= hwif_in.Machine_neigh.rd_ack;
        rd_ack |= hwif_in.Machine_cpu.rd_ack;
        readback_external_rd_ack_c = rd_ack;
    end

    logic readback_external_rd_ack;

    assign readback_external_rd_ack = readback_external_rd_ack_c;

    logic [23:0] rd_mux_addr;
    logic [23:0] pending_rd_addr;
    // Hold read mux address to guarantee it is stable throughout any external accesses
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            pending_rd_addr <= '0;
        end else begin
            if(decoded_req) pending_rd_addr <= decoded_addr;
        end
    end
    assign rd_mux_addr = decoded_req ? decoded_addr : pending_rd_addr;

    logic readback_err;
    logic readback_done;
    logic [31:0] readback_data;
    always_comb begin
        automatic logic [31:0] readback_data_var;
        readback_data_var = '0;
        if((rd_mux_addr >= 24'h100000) && (rd_mux_addr <= 24'h100000 + 24'h47)) begin
            readback_data_var = hwif_in.User_neigh.rd_data;
        end
        if((rd_mux_addr >= 24'h340000) && (rd_mux_addr <= 24'h340000 + 24'h2ff)) begin
            readback_data_var = hwif_in.User_cpu.rd_data;
        end
        if((rd_mux_addr >= 24'h740000) && (rd_mux_addr <= 24'h740000 + 24'h307)) begin
            readback_data_var = hwif_in.Supervisor_cpu.rd_data;
        end
        if((rd_mux_addr >= 24'h800000) && (rd_mux_addr <= 24'h800000 + 24'hffff)) begin
            readback_data_var = hwif_in.D_hart_esr.rd_data;
        end
        if((rd_mux_addr >= 24'h900000) && (rd_mux_addr <= 24'h900000 + 24'hff9f)) begin
            readback_data_var = hwif_in.D_neigh.rd_data;
        end
        if((rd_mux_addr >= 24'hb5f000) && (rd_mux_addr <= 24'hb5f000 + 24'hfd7)) begin
            readback_data_var = hwif_in.D_cpu.rd_data;
        end
        if((rd_mux_addr >= 24'hd00000) && (rd_mux_addr <= 24'hd00000 + 24'h97)) begin
            readback_data_var = hwif_in.Machine_neigh.rd_data;
        end
        if((rd_mux_addr >= 24'hf40000) && (rd_mux_addr <= 24'hf40000 + 24'h317)) begin
            readback_data_var = hwif_in.Machine_cpu.rd_data;
        end
        readback_data = readback_data_var;
        readback_done = decoded_req & ~decoded_req_is_wr & ~decoded_req_is_external;
        readback_err = '0;
    end

    assign external_rd_ack = readback_external_rd_ack;
    assign cpuif_rd_ack = readback_done | readback_external_rd_ack;
    assign cpuif_rd_data = readback_data;
    assign cpuif_rd_err = readback_err;
endmodule
