// Copyright (c) 2026 Ainekko
// SPDX-License-Identifier: Apache-2.0

module cosim_txfma_c5_tb import vpu_defs_pkg::*;
(
  input logic [VPU_DTYPE_SZ-1:0] op_dtype_f5a_h,
  input logic [VPU_FCMD_SZ-1:0] cmd_f5a_h,
  input logic [TXFMA_SIGS_SZ-1:0] sigs_f5a_h,
  input logic [FP_RM_BITS-1:0] rm_f5a_h,
  input logic [TXFMA_LXD_PS_SZ-1:0] elxd_f5a_h,
  input logic [TXFMA_WSPS_ETRZ_SZ-1:0] etrz50_f5a_h,
  input logic ec_zero_f5a_h,
  input logic prod_sign_hi_f5a_h,
  input logic s_res_f5a_h,
  input logic s_res_check_cadd_a3_f5a_h,
  input logic comp_res_sel_f5a_h,
  input logic comp_op_f5a_h,
  input logic minmax_op_f5a_h,
  input logic trans_log_rr_neg_f5a_h,
  input logic ediff1_zap_f5a_h,
  input logic fa_eq_fc_res_check_hi_f5a_h,
  input logic fc_sel_f5a_h,
  input logic stky2g_f5a_h,
  input logic comb_add_a3_f5a_h,
  output logic orig_rc_ps_f5a_h,
  output logic new_rc_ps_f5a_h,
  output logic orig_rc_ph_f5a_h,
  output logic new_rc_ph_f5a_h,
  output logic orig_rc6_ps_f5a_h,
  output logic new_rc6_ps_f5a_h,
  output logic orig_rc6_ph_f5a_h,
  output logic new_rc6_ph_f5a_h,
  output logic orig_rc_int32_f5a_h,
  output logic new_rc_int32_f5a_h,
  output logic orig_rc_3rmxr_f5a_h,
  output logic new_rc_3rmxr_f5a_h,
  output logic orig_rc_rl01_f5a_h,
  output logic new_rc_rl01_f5a_h,
  output logic orig_rc_rmm_f5a_h,
  output logic new_rc_rmm_f5a_h,
  output logic orig_rc_rup_f5a_h,
  output logic new_rc_rup_f5a_h,
  output logic orig_rc_rne_f5a_h,
  output logic new_rc_rne_f5a_h,
  output logic orig_rc_rdn_f5a_h,
  output logic new_rc_rdn_f5a_h,
  output logic orig_rc_res_sign_f5a_l,
  output logic new_rc_res_sign_f5a_l,
  output logic orig_rc_transrnd_f5a_h,
  output logic new_rc_transrnd_f5a_h,
  output logic orig_rc_transrnd_log_fma2_f5a_h,
  output logic new_rc_transrnd_log_fma2_f5a_h,
  output logic orig_nshcen_sel1b_f5a_h,
  output logic new_nshcen_sel1b_f5a_h,
  output logic orig_en_logrrsel1b_f5a_l,
  output logic new_en_logrrsel1b_f5a_l,
  output logic orig_int32_stky2r_f5a_h,
  output logic new_int32_stky2r_f5a_h,
  output logic orig_mmx_sel_immres_f5a_h,
  output logic new_mmx_sel_immres_f5a_h,
  output logic orig_comp_op_true_f5a_h,
  output logic new_comp_op_true_f5a_h,
  output logic orig_trans2_ps_roundup_r_f5a_h,
  output logic new_trans2_ps_roundup_r_f5a_h,
  output logic orig_e_force_to_zero_f5a_h,
  output logic new_e_force_to_zero_f5a_h,
  output logic orig_s_res_out_f5a_h,
  output logic new_s_res_out_f5a_h
);

  txfma_c5_orig u_orig (
    .op_dtype_f5a_h (op_dtype_f5a_h),
    .cmd_f5a_h (cmd_f5a_h),
    .sigs_f5a_h (sigs_f5a_h),
    .rm_f5a_h (rm_f5a_h),
    .elxd_f5a_h (elxd_f5a_h),
    .etrz50_f5a_h (etrz50_f5a_h),
    .ec_zero_f5a_h (ec_zero_f5a_h),
    .prod_sign_hi_f5a_h (prod_sign_hi_f5a_h),
    .s_res_f5a_h (s_res_f5a_h),
    .s_res_check_cadd_a3_f5a_h (s_res_check_cadd_a3_f5a_h),
    .comp_res_sel_f5a_h (comp_res_sel_f5a_h),
    .comp_op_f5a_h (comp_op_f5a_h),
    .minmax_op_f5a_h (minmax_op_f5a_h),
    .trans_log_rr_neg_f5a_h (trans_log_rr_neg_f5a_h),
    .ediff1_zap_f5a_h (ediff1_zap_f5a_h),
    .fa_eq_fc_res_check_hi_f5a_h (fa_eq_fc_res_check_hi_f5a_h),
    .fc_sel_f5a_h (fc_sel_f5a_h),
    .stky2g_f5a_h (stky2g_f5a_h),
    .comb_add_a3_f5a_h (comb_add_a3_f5a_h),
    .rc_ps_f5a_h (orig_rc_ps_f5a_h),
    .rc_ph_f5a_h (orig_rc_ph_f5a_h),
    .rc6_ps_f5a_h (orig_rc6_ps_f5a_h),
    .rc6_ph_f5a_h (orig_rc6_ph_f5a_h),
    .rc_int32_f5a_h (orig_rc_int32_f5a_h),
    .rc_3rmxr_f5a_h (orig_rc_3rmxr_f5a_h),
    .rc_rl01_f5a_h (orig_rc_rl01_f5a_h),
    .rc_rmm_f5a_h (orig_rc_rmm_f5a_h),
    .rc_rup_f5a_h (orig_rc_rup_f5a_h),
    .rc_rne_f5a_h (orig_rc_rne_f5a_h),
    .rc_rdn_f5a_h (orig_rc_rdn_f5a_h),
    .rc_res_sign_f5a_l (orig_rc_res_sign_f5a_l),
    .rc_transrnd_f5a_h (orig_rc_transrnd_f5a_h),
    .rc_transrnd_log_fma2_f5a_h (orig_rc_transrnd_log_fma2_f5a_h),
    .nshcen_sel1b_f5a_h (orig_nshcen_sel1b_f5a_h),
    .en_logrrsel1b_f5a_l (orig_en_logrrsel1b_f5a_l),
    .int32_stky2r_f5a_h (orig_int32_stky2r_f5a_h),
    .mmx_sel_immres_f5a_h (orig_mmx_sel_immres_f5a_h),
    .comp_op_true_f5a_h (orig_comp_op_true_f5a_h),
    .trans2_ps_roundup_r_f5a_h (orig_trans2_ps_roundup_r_f5a_h),
    .e_force_to_zero_f5a_h (orig_e_force_to_zero_f5a_h),
    .s_res_out_f5a_h (orig_s_res_out_f5a_h)
  );

  txfma_c5 u_new (
    .op_dtype_f5a_h (op_dtype_f5a_h),
    .cmd_f5a_h (cmd_f5a_h),
    .sigs_f5a_h (sigs_f5a_h),
    .rm_f5a_h (rm_f5a_h),
    .elxd_f5a_h (elxd_f5a_h),
    .etrz50_f5a_h (etrz50_f5a_h),
    .ec_zero_f5a_h (ec_zero_f5a_h),
    .prod_sign_hi_f5a_h (prod_sign_hi_f5a_h),
    .s_res_f5a_h (s_res_f5a_h),
    .s_res_check_cadd_a3_f5a_h (s_res_check_cadd_a3_f5a_h),
    .comp_res_sel_f5a_h (comp_res_sel_f5a_h),
    .comp_op_f5a_h (comp_op_f5a_h),
    .minmax_op_f5a_h (minmax_op_f5a_h),
    .trans_log_rr_neg_f5a_h (trans_log_rr_neg_f5a_h),
    .ediff1_zap_f5a_h (ediff1_zap_f5a_h),
    .fa_eq_fc_res_check_hi_f5a_h (fa_eq_fc_res_check_hi_f5a_h),
    .fc_sel_f5a_h (fc_sel_f5a_h),
    .stky2g_f5a_h (stky2g_f5a_h),
    .comb_add_a3_f5a_h (comb_add_a3_f5a_h),
    .rc_ps_f5a_h (new_rc_ps_f5a_h),
    .rc_ph_f5a_h (new_rc_ph_f5a_h),
    .rc6_ps_f5a_h (new_rc6_ps_f5a_h),
    .rc6_ph_f5a_h (new_rc6_ph_f5a_h),
    .rc_int32_f5a_h (new_rc_int32_f5a_h),
    .rc_3rmxr_f5a_h (new_rc_3rmxr_f5a_h),
    .rc_rl01_f5a_h (new_rc_rl01_f5a_h),
    .rc_rmm_f5a_h (new_rc_rmm_f5a_h),
    .rc_rup_f5a_h (new_rc_rup_f5a_h),
    .rc_rne_f5a_h (new_rc_rne_f5a_h),
    .rc_rdn_f5a_h (new_rc_rdn_f5a_h),
    .rc_res_sign_f5a_l (new_rc_res_sign_f5a_l),
    .rc_transrnd_f5a_h (new_rc_transrnd_f5a_h),
    .rc_transrnd_log_fma2_f5a_h (new_rc_transrnd_log_fma2_f5a_h),
    .nshcen_sel1b_f5a_h (new_nshcen_sel1b_f5a_h),
    .en_logrrsel1b_f5a_l (new_en_logrrsel1b_f5a_l),
    .int32_stky2r_f5a_h (new_int32_stky2r_f5a_h),
    .mmx_sel_immres_f5a_h (new_mmx_sel_immres_f5a_h),
    .comp_op_true_f5a_h (new_comp_op_true_f5a_h),
    .trans2_ps_roundup_r_f5a_h (new_trans2_ps_roundup_r_f5a_h),
    .e_force_to_zero_f5a_h (new_e_force_to_zero_f5a_h),
    .s_res_out_f5a_h (new_s_res_out_f5a_h)
  );

endmodule : cosim_txfma_c5_tb
