
/* Copyright (c) 2026 Ainekko          */
/* SPDX-License-Identifier: Apache-2.0 */

#include "esr_properties.h"


////////////////////////////////////////////////////////////////////////////////
// Full name depending on the type of ESR
////////////////////////////////////////////////////////////////////////////////
#include <iostream>
using namespace std;
const std::string ESRPropertiesNeigh::get_info(esr_address_t ad){
  std::ostringstream os;
  os<<std::hex<<
    name_ << " " <<"0x"<<ad<<
    " - shire= 0x"<< ESR_GET_SHIRE(ad)<<
    " - neigh= 0x" << ESR_GET_NEIGH(ad) <<
    " - prot= "<< (int) prot_ <<
    " - regNo=0x"<<regNo_;
  return os.str();
}

const std::string ESRPropertiesCache::get_info(esr_address_t ad){
  std::ostringstream os;
  os<<std::hex<<
    name_ << " " <<"0x"<<ad<<
    " - shire= 0x"<< ESR_GET_SHIRE(ad) <<
    " - bank= 0x" << ESR_GET_BANK(ad) <<
    " - prot= "<< (int) prot_ <<
    " - regNo=0x"<<regNo_;
  return os.str();
}

const std::string ESRPropertiesRbox::get_info(esr_address_t ad){
  std::ostringstream os;
  os<<std::hex <<
    name_ << " " <<"0x"<<ad<<
    " - shire= 0x"<< ESR_GET_SHIRE(ad)<<
    " - prot= "<< (int) prot_ <<
    " - regNo=0x"<<regNo_;
  return os.str();
}

const std::string ESRPropertiesShire::get_info(esr_address_t ad){
  std::ostringstream os;
  os<<std::hex <<
    name_ << " " <<"0x"<<ad<<
    " - shire= 0x"<< ESR_GET_SHIRE(ad)<<
    " - prot= "<< (int) prot_ <<
    " - regNo=0x"<<regNo_;
  return os.str();
}


////////////////////////////////////////////////////////////////////////////////
// Full ESR list
////////////////////////////////////////////////////////////////////////////////

#define ESR_NEIGH_ADD_TO_LIST(name)                                                         \
  add ( new ESRPropertiesNeigh                                                              \
        ("ESR_NEIGH_" # name, ESR_NEIGH_ ## name ##_REGNO,                                  \
         ESR_NEIGH_ ## name ##_PROT, ESR_NEIGH_ ## name ##_ACCESS))

#define ESR_CACHE_ADD_TO_LIST(name)                                                         \
  add ( new ESRPropertiesCache                                                              \
        ("ESR_CACHE_" # name, ESR_CACHE_ ## name ##_REGNO,                                  \
         ESR_CACHE_ ## name ##_PROT,      ESR_CACHE_ ## name ##_ACCESS))

#define ESR_RBOX_ADD_TO_LIST(name)  /*note that for rbox, reg names already include _RBOX*/ \
  add ( new ESRPropertiesRbox                                                               \
        ("ESR_" # name, ESR_ ## name ##_REGNO,                                              \
         ESR_ ## name ##_PROT,ESR_ ## name ##_ACCESS) )

#define ESR_SHIRE_ADD_TO_LIST(name)                                                         \
  add ( new ESRPropertiesShire                                                              \
        ("ESR_SHIRE_" # name, ESR_SHIRE_ ## name ##_REGNO,                                  \
         ESR_SHIRE_ ## name ##_PROT, ESR_SHIRE_ ## name ##_ACCESS) )



ESRRegisterList::ESRRegisterList() {
//BEGIN autogenerated ESR list for NEIGH
ESR_NEIGH_ADD_TO_LIST(MINION_BOOT);
ESR_NEIGH_ADD_TO_LIST(MPROT);
ESR_NEIGH_ADD_TO_LIST(IPI_REDIRECT_PC);
ESR_NEIGH_ADD_TO_LIST(HACTRL);
ESR_NEIGH_ADD_TO_LIST(HASTATUS0);
ESR_NEIGH_ADD_TO_LIST(HASTATUS1);
ESR_NEIGH_ADD_TO_LIST(AND_OR_TREEL0);
ESR_NEIGH_ADD_TO_LIST(PMU_CTRL);
ESR_NEIGH_ADD_TO_LIST(NEIGH_CHICKEN);
ESR_NEIGH_ADD_TO_LIST(ICACHE_ERR_LOG_CTL);
ESR_NEIGH_ADD_TO_LIST(ICACHE_ERR_LOG_INFO);
ESR_NEIGH_ADD_TO_LIST(ICACHE_ERR_LOG_ADDRESS);
ESR_NEIGH_ADD_TO_LIST(ICACHE_SBE_DBE_COUNTS);
//END autogenerated ESR list for NEIGH

//BEGIN autogenerated ESR list for CACHE_BANK
ESR_CACHE_ADD_TO_LIST(SC_L3_SHIRE_SWIZZLE_CTL);
ESR_CACHE_ADD_TO_LIST(SC_REQQ_CTL);
ESR_CACHE_ADD_TO_LIST(SC_PIPE_CTL);
ESR_CACHE_ADD_TO_LIST(SC_L2_CACHE_CTL);
ESR_CACHE_ADD_TO_LIST(SC_L3_CACHE_CTL);
ESR_CACHE_ADD_TO_LIST(SC_SCP_CACHE_CTL);
ESR_CACHE_ADD_TO_LIST(SC_IDX_COP_SM_CTL);
ESR_CACHE_ADD_TO_LIST(SC_IDX_COP_SM_PHYSICAL_INDEX);
ESR_CACHE_ADD_TO_LIST(SC_IDX_COP_SM_DATA0);
ESR_CACHE_ADD_TO_LIST(SC_IDX_COP_SM_DATA1);
ESR_CACHE_ADD_TO_LIST(SC_IDX_COP_SM_ECC);
ESR_CACHE_ADD_TO_LIST(SC_ERR_LOG_CTL);
ESR_CACHE_ADD_TO_LIST(SC_ERR_LOG_INFO);
ESR_CACHE_ADD_TO_LIST(SC_ERR_LOG_ADDRESS);
ESR_CACHE_ADD_TO_LIST(SC_SBE_DBE_COUNTS);
ESR_CACHE_ADD_TO_LIST(SC_REQQ_DEBUG_CTL);
ESR_CACHE_ADD_TO_LIST(SC_REQQ_DEBUG0);
ESR_CACHE_ADD_TO_LIST(SC_REQQ_DEBUG1);
ESR_CACHE_ADD_TO_LIST(SC_REQQ_DEBUG2);
ESR_CACHE_ADD_TO_LIST(SC_REQQ_DEBUG3);
ESR_CACHE_ADD_TO_LIST(SC_ECO_CTL);
ESR_CACHE_ADD_TO_LIST(SC_PERFMON_CTL_STATUS);
ESR_CACHE_ADD_TO_LIST(SC_PERFMON_CYC_CNTR);
ESR_CACHE_ADD_TO_LIST(SC_PERFMON_P0_CNTR);
ESR_CACHE_ADD_TO_LIST(SC_PERFMON_P1_CNTR);
ESR_CACHE_ADD_TO_LIST(SC_PERFMON_P0_QUAL);
ESR_CACHE_ADD_TO_LIST(SC_PERFMON_P1_QUAL);
ESR_CACHE_ADD_TO_LIST(SC_IDX_COP_SM_CTL_USER);
ESR_CACHE_ADD_TO_LIST(SC_TRACE_ADDRESS_ENABLE);
ESR_CACHE_ADD_TO_LIST(SC_TRACE_ADDRESS_VALUE);
ESR_CACHE_ADD_TO_LIST(SC_TRACE_CTL);
//END autogenerated ESR list for CACHE_BANK

//BEGIN autogenerated ESR list for RBOX
ESR_RBOX_ADD_TO_LIST(RBOX_CONFIG);
ESR_RBOX_ADD_TO_LIST(RBOX_IN_BUF_PG);
ESR_RBOX_ADD_TO_LIST(RBOX_IN_BUF_CFG);
ESR_RBOX_ADD_TO_LIST(RBOX_OUT_BUF_PG);
ESR_RBOX_ADD_TO_LIST(RBOX_OUT_BUF_CFG);
ESR_RBOX_ADD_TO_LIST(RBOX_STATUS);
ESR_RBOX_ADD_TO_LIST(RBOX_START);
ESR_RBOX_ADD_TO_LIST(RBOX_CONSUME);
//END autogenerated ESR list for RBOX

//BEGIN autogenerated ESR list for SHIRE_OTHER
ESR_SHIRE_ADD_TO_LIST(MINION_FEATURE);
ESR_SHIRE_ADD_TO_LIST(THREAD1_DISABLE);
ESR_SHIRE_ADD_TO_LIST(IPI_REDIRECT_TRIGGER);
ESR_SHIRE_ADD_TO_LIST(IPI_REDIRECT_FILTER);
ESR_SHIRE_ADD_TO_LIST(IPI_TRIGGER);
ESR_SHIRE_ADD_TO_LIST(IPI_TRIGGER_CLEAR);
ESR_SHIRE_ADD_TO_LIST(FCC_CREDINC_0);
ESR_SHIRE_ADD_TO_LIST(FCC_CREDINC_1);
ESR_SHIRE_ADD_TO_LIST(FCC_CREDINC_2);
ESR_SHIRE_ADD_TO_LIST(FCC_CREDINC_3);
ESR_SHIRE_ADD_TO_LIST(FAST_LOCAL_BARRIER0);
ESR_SHIRE_ADD_TO_LIST(FAST_LOCAL_BARRIER1);
ESR_SHIRE_ADD_TO_LIST(FAST_LOCAL_BARRIER2);
ESR_SHIRE_ADD_TO_LIST(FAST_LOCAL_BARRIER3);
ESR_SHIRE_ADD_TO_LIST(FAST_LOCAL_BARRIER4);
ESR_SHIRE_ADD_TO_LIST(FAST_LOCAL_BARRIER5);
ESR_SHIRE_ADD_TO_LIST(FAST_LOCAL_BARRIER6);
ESR_SHIRE_ADD_TO_LIST(FAST_LOCAL_BARRIER7);
ESR_SHIRE_ADD_TO_LIST(FAST_LOCAL_BARRIER8);
ESR_SHIRE_ADD_TO_LIST(FAST_LOCAL_BARRIER9);
ESR_SHIRE_ADD_TO_LIST(FAST_LOCAL_BARRIER10);
ESR_SHIRE_ADD_TO_LIST(FAST_LOCAL_BARRIER11);
ESR_SHIRE_ADD_TO_LIST(FAST_LOCAL_BARRIER12);
ESR_SHIRE_ADD_TO_LIST(FAST_LOCAL_BARRIER13);
ESR_SHIRE_ADD_TO_LIST(FAST_LOCAL_BARRIER14);
ESR_SHIRE_ADD_TO_LIST(FAST_LOCAL_BARRIER15);
ESR_SHIRE_ADD_TO_LIST(FAST_LOCAL_BARRIER16);
ESR_SHIRE_ADD_TO_LIST(FAST_LOCAL_BARRIER17);
ESR_SHIRE_ADD_TO_LIST(FAST_LOCAL_BARRIER18);
ESR_SHIRE_ADD_TO_LIST(FAST_LOCAL_BARRIER19);
ESR_SHIRE_ADD_TO_LIST(FAST_LOCAL_BARRIER20);
ESR_SHIRE_ADD_TO_LIST(FAST_LOCAL_BARRIER21);
ESR_SHIRE_ADD_TO_LIST(FAST_LOCAL_BARRIER22);
ESR_SHIRE_ADD_TO_LIST(FAST_LOCAL_BARRIER23);
ESR_SHIRE_ADD_TO_LIST(FAST_LOCAL_BARRIER24);
ESR_SHIRE_ADD_TO_LIST(FAST_LOCAL_BARRIER25);
ESR_SHIRE_ADD_TO_LIST(FAST_LOCAL_BARRIER26);
ESR_SHIRE_ADD_TO_LIST(FAST_LOCAL_BARRIER27);
ESR_SHIRE_ADD_TO_LIST(FAST_LOCAL_BARRIER28);
ESR_SHIRE_ADD_TO_LIST(FAST_LOCAL_BARRIER29);
ESR_SHIRE_ADD_TO_LIST(FAST_LOCAL_BARRIER30);
ESR_SHIRE_ADD_TO_LIST(FAST_LOCAL_BARRIER31);
ESR_SHIRE_ADD_TO_LIST(MTIME);
ESR_SHIRE_ADD_TO_LIST(MTIMECMP);
ESR_SHIRE_ADD_TO_LIST(TIME_CONFIG);
ESR_SHIRE_ADD_TO_LIST(MTIME_LOCAL_TARGET);
ESR_SHIRE_ADD_TO_LIST(THREAD0_DISABLE);
ESR_SHIRE_ADD_TO_LIST(SHIRE_COOP_MODE);
ESR_SHIRE_ADD_TO_LIST(ICACHE_UPREFETCH);
ESR_SHIRE_ADD_TO_LIST(ICACHE_SPREFETCH);
ESR_SHIRE_ADD_TO_LIST(ICACHE_MPREFETCH);
ESR_SHIRE_ADD_TO_LIST(CLK_GATE_CTRL);
ESR_SHIRE_ADD_TO_LIST(SM_CONFIG);
ESR_SHIRE_ADD_TO_LIST(SM_TRIGGER);
ESR_SHIRE_ADD_TO_LIST(SM_MATCH);
ESR_SHIRE_ADD_TO_LIST(SM_FILTER0);
ESR_SHIRE_ADD_TO_LIST(SM_FILTER1);
ESR_SHIRE_ADD_TO_LIST(SM_FILTER2);
ESR_SHIRE_ADD_TO_LIST(SM_DATA0);
ESR_SHIRE_ADD_TO_LIST(SM_DATA1);
ESR_SHIRE_ADD_TO_LIST(DMCTRL);
//END autogenerated ESR list for SHIRE_OTHER

}
