#!/usr/bin/env python3
# Copyright (c) 2026 Ainekko
# SPDX-License-Identifier: Apache-2.0

import sys
import os

from shutil import copyfile

if "RTLROOT" not in os.environ:
    raise Exception( "RTLROOT not set" )
rtlroot= os.environ['RTLROOT']
sys.path.append(rtlroot + '/shire/scripts')
from EsrFile import EsrFile, EsrRegister
from XsrType import XsrType
from XsrFileIO import printToFile, replaceInFile, mkdir_p
from ParseDefines import ParseDefines

dstDirRTL= rtlroot + '/shire/esr/'
dstDirDEF = rtlroot + '/inc/'
dstDirCPP = rtlroot + '/shire/esr/scripts/'
fileDEF = dstDirDEF + 'esr_defines_auto.vh'
fileTYPE = dstDirDEF + 'esr_types_auto.vh'
fileCPPHeader = dstDirCPP + 'esr_defines.h'
fileCPPProp = dstDirCPP + 'esr_properties.cc'

for f in [fileDEF, fileTYPE, fileCPPHeader, fileCPPProp ]:
    copyfile( f, f + '.old')

# load constants from include files
#ParseDefines.addDefines([rtlroot + "/inc/test.vh", rtlroot + "/inc/test2.vh"])
#ParseDefines.addDefines([rtlroot + "/inc/shire_cache_defines.vh"])


#if "FROM_GDOCS" in os.environ:
#    fromGdocs = os.environ['FROM_GDOCS'] != "0"
#else:
fromGdocs = False


modules=["neigh", "cache_bank", "shire_other", "rbox", "memshire", "ddrc", "spio"]
for mod in modules:
    print ('Generating ' + mod + ' ESR')

    # make copy of old files
    fileRTL = dstDirRTL + 'esr_'+ mod + '_auto.v'
    filePorts = dstDirRTL + 'esr_' + mod + '.v'
    
    copyfile( fileRTL, fileRTL + '.old')
    copyfile( filePorts, filePorts + '.old')

    # generate code
    c = EsrFile(mod = mod, fromGdocs = fromGdocs);

    # for shire_esr_auto.vh
    labelsRTL = ['DECLARATIONS', 'READ_AND_DECODE_COMB_DEFAULT',  'READ_AND_DECODE_COMB_CASES', 
                 'READ_AND_DECODE_SEQ', 'WRITE_COMB_DEFAULT', 'WRITE_CORE_COMB', 
                 'WRITE_SEQ',  'TYPE_CONVERSIONS', 'PORT_ASSIGN']
    code = []

    code.append(c.declarations())
    code.extend(c.readAndDecodeProc([False, True, False]))
    code.append(c.writeCombDefault(True))
    code.append(c.writeCoreComb(True))
    #if mod == 'neigh' or mod == 'shire_other' or mod == 'cache_bank' or mod == 'ddrc' or mod == 'memshire' or mod == 'rbox' :
    #   code.extend(c.readAndDecodeProc([False, True, False]))
    #   code.append(c.writeCombDefault(True))
    #   code.append(c.writeCoreComb(True))
    #else:
    #   code.extend(c.readAndDecodeProc())
    #   code.append(c.writeCombDefault())
    #   code.append(c.writeCoreComb())

    code.append(c.writeSeq())
    code.append(XsrType.allConversions())
    code.append(c.portAssignments())

    for contents, lab in zip(code, labelsRTL):
        replaceInFile( fileRTL, contents, 'BEGIN autogenerated ' + lab, 'END autogenerated ' + lab, False)


    lab = ' autogenerated ESR_AD_DEFINITIONS for ' + mod
    # address widths (commented out, no longer automatic ceil(log2(max_ad)).. but constant in esr_defines.vh
    # code = ('`define %s %d\n' % (EsrRegister.adWidth(''), c.log2MaxAd()))
    # replaceInFile(fileDEF, code, 'BEGIN' + lab, 'END' + lab)

    # enums with addresses
    code = c.addressDefinitions(extraBits = 2) # extraBits = PP bits
    replaceInFile(fileTYPE, code, 'BEGIN' + lab, 'END' + lab)

    # C definitions with addresses
    lab = ' autogenerated ESR address definitions for ' + mod.upper()
    cpp_stamps = {"neigh": "ESR_NEIGH", "cache_bank": "ESR_CACHE", "shire_other": "ESR_SHIRE", "rbox": "ESR", "memshire":"ESR_MEMSHIRE", "ddrc":"ESR_DDRC", "spio": "ESR_SPIO"}
    code = c.cppAddressDefinitions(cpp_stamps[mod])
    replaceInFile(fileCPPHeader, code, 'BEGIN' + lab, 'END' + lab)

    if mod in ["neigh", "cache_bank", "shire_other", "rbox"]:
        cpp_stamps = {"neigh": "ESR_NEIGH", "cache_bank": "ESR_CACHE", "shire_other": "ESR_SHIRE", "rbox": "ESR_RBOX"}
        lab = " autogenerated ESR list for " +  mod.upper()
        code = c.cppList(cpp_stamps[mod])
        replaceInFile(fileCPPProp, code, 'BEGIN' + lab, 'END' + lab)    
    
    # and ports
    replaceInFile( filePorts, c.portDeclarations(), 'BEGIN autogenerated PORTS', 'END autogenerated PORTS')

    # and reset 'conversion used' so that conversions are added to the next ESR slaves
    XsrType.resetConversionUsed()
    
# code for type definitions (outside of main loop, in case there is a struct used in more than one slave)
contents = XsrType.allDefinitions()
replaceInFile( fileTYPE, contents, 'BEGIN autogenerated TYPE_DEFINITIONS', 'END autogenerated TYPE_DEFINITIONS')

