// Copyright (c) 2026 Ainekko
// SPDX-License-Identifier: Apache-2.0

module cosim_txfma_c0_tb import minion_pkg::*; import vpu_defs_pkg::*;
(
  input logic clk_i,
  input logic rst_ni,
  input logic in_valid_exa_h,
  input logic [$bits(minion_pkg::vpu_ctrl_sigs_t)-1:0] sigs_in_exa_h_bits,
  input logic [TXFMA_RM_SZ-1:0] rm_in_exa_h,
  input logic [TRANS_MASK_SIZE-1:0] trans_mask_exa_h,
  input logic trans_taylor_exa_h,
  input logic trans_exp_fma2_exc_exa_h,
  input logic use_prev_sigs_exa_h,
  input logic sa_hi_f0a_h,
  input logic sa_lo_f0a_h,
  input logic sb_hi_f0a_h,
  input logic sb_lo_f0a_h,
  input logic sc_f0a_h,
  input logic ea_hi_zero_f0a_l,
  input logic ea_hi_all1_f0a_h,
  input logic ea_lo_zero_f0a_l,
  input logic ea_lo_all1_f0a_h,
  input logic eb_hi_zero_f0a_l,
  input logic eb_hi_all1_f0a_h,
  input logic eb_lo_zero_f0a_l,
  input logic eb_lo_all1_f0a_h,
  input logic ec_zero_f0a_l,
  input logic ec_all1_f0a_h,
  input logic eb_eql_127_f0a_h,
  input logic eb_eql_126_f0a_h,
  input logic eb_eql_125_f0a_h,
  input logic fcf10_zero_f0a_l,
  input logic fcf11_zero_f0a_l,
  input logic fcps_zero_f0a_h,
  input logic fcph_zero_f0a_l,
  input logic fcnorm_zero_29_8_f0a_h,
  input logic fcnorm16_eq_1_f0a_h,
  input logic fcnorm8_eq_1_f0a_h,
  input logic fcn8_one_30_24_f0a_h,
  input logic fcn10_one_30_22_f0a_h,
  input logic fcn16_one_30_16_f0a_h,
  input logic fcn24_one_30_8_f0a_h,
  input logic faps_zero_f0a_l,
  input logic fbps_zero_f0a_l,
  input logic faph_hi_zero_f0a_l,
  input logic fbph_hi_zero_f0a_l,
  input logic faph_lo_zero_f0a_l,
  input logic fbph_lo_zero_f0a_l,
  input logic faph_lo_b0_f0a_h,
  input logic fbph_lo_b0_f0a_h,
  input logic faps_b0_f0a_h,
  input logic fbps_b0_f0a_h,
  input logic fc_31_f0a_h,
  input logic fcnorm_30_f0a_h,
  input logic faph_hi_b0_f0a_h,
  input logic fbph_hi_b0_f0a_h,
  input logic fcph_b0_f0a_h,
  input logic fcf11_b0_f0a_h,
  input logic fcf10_b0_f0a_h,
  input logic fcps_b0_f0a_h,
  output logic orig_trans_exp_fma2_exc_f0a_h,
  output logic new_trans_exp_fma2_exc_f0a_h,
  output logic orig_opa_valid_rfa_h,
  output logic new_opa_valid_rfa_h,
  output logic orig_opb_valid_rfa_h,
  output logic new_opb_valid_rfa_h,
  output logic orig_opc_valid_rfa_h,
  output logic new_opc_valid_rfa_h,
  output logic orig_ctrl_valid_f0a_h,
  output logic new_ctrl_valid_f0a_h,
  output logic orig_is_trans_rfa_h,
  output logic new_is_trans_rfa_h,
  output logic [5:0] orig_eb_hi_k_exa_h,
  output logic [5:0] new_eb_hi_k_exa_h,
  output logic orig_fa_en_exa_h,
  output logic new_fa_en_exa_h,
  output logic orig_fb_en_exa_h,
  output logic new_fb_en_exa_h,
  output logic orig_fc_en_exa_h,
  output logic new_fc_en_exa_h,
  output logic orig_sa_hi_en_exa_h,
  output logic new_sa_hi_en_exa_h,
  output logic orig_sa_lo_en_exa_h,
  output logic new_sa_lo_en_exa_h,
  output logic orig_sb_hi_en_exa_h,
  output logic new_sb_hi_en_exa_h,
  output logic orig_sb_lo_en_exa_h,
  output logic new_sb_lo_en_exa_h,
  output logic orig_ea_hi_zero_clr_f0a_h,
  output logic new_ea_hi_zero_clr_f0a_h,
  output logic orig_eb_hi_zero_clr_f0a_h,
  output logic new_eb_hi_zero_clr_f0a_h,
  output logic orig_ea_lo_zero_clr_f0a_h,
  output logic new_ea_lo_zero_clr_f0a_h,
  output logic orig_eb_lo_zero_clr_f0a_h,
  output logic new_eb_lo_zero_clr_f0a_h,
  output logic [1:0] orig_sel_eainmux_exa_h,
  output logic [1:0] new_sel_eainmux_exa_h,
  output logic orig_sel_ealo_ph_exa_h,
  output logic new_sel_ealo_ph_exa_h,
  output logic orig_ehi_ea_en_exa_h,
  output logic new_ehi_ea_en_exa_h,
  output logic orig_elo_ea_en_exa_h,
  output logic new_elo_ea_en_exa_h,
  output logic [1:0] orig_sel_ebin_hi_exa_h,
  output logic [1:0] new_sel_ebin_hi_exa_h,
  output logic orig_sel_eblo_ph_exa_h,
  output logic new_sel_eblo_ph_exa_h,
  output logic orig_ehi_eb_en_exa_h,
  output logic new_ehi_eb_en_exa_h,
  output logic orig_elo_eb_en_exa_h,
  output logic new_elo_eb_en_exa_h,
  output logic [1:0] orig_sel_ec5b_exa_h,
  output logic [1:0] new_sel_ec5b_exa_h,
  output logic [1:0] orig_sel_ecin_exa_h,
  output logic [1:0] new_sel_ecin_exa_h,
  output logic orig_ec_en_exa_h,
  output logic new_ec_en_exa_h,
  output logic orig_sel_ec5bdet_exa_h,
  output logic new_sel_ec5bdet_exa_h,
  output logic orig_sc_en_exa_h,
  output logic new_sc_en_exa_h,
  output logic orig_sa1_nr2_frcpfxp_exa_h,
  output logic new_sa1_nr2_frcpfxp_exa_h,
  output logic [1:0] orig_sel_sc_exa_h,
  output logic [1:0] new_sel_sc_exa_h,
  output logic orig_sel_sign_sinp2_exa_h,
  output logic new_sel_sign_sinp2_exa_h,
  output logic orig_sa_zap_exa_l,
  output logic new_sa_zap_exa_l,
  output logic orig_sb_zap_exa_l,
  output logic new_sb_zap_exa_l,
  output logic orig_sel_f10_exa_h,
  output logic new_sel_f10_exa_h,
  output logic orig_sel_f11_exa_h,
  output logic new_sel_f11_exa_h,
  output logic [1:0] orig_sel_opcgfx_exa_h,
  output logic [1:0] new_sel_opcgfx_exa_h,
  output logic orig_fc_dtps_exa_h,
  output logic new_fc_dtps_exa_h,
  output logic orig_neg_fmaop_exa_h,
  output logic new_neg_fmaop_exa_h,
  output logic orig_trans_op2_exa_l,
  output logic new_trans_op2_exa_l,
  output logic [1:0] orig_sel_xopc_exa_h,
  output logic [1:0] new_sel_xopc_exa_h,
  output logic [1:0] orig_sel_opcfmt_exa_h,
  output logic [1:0] new_sel_opcfmt_exa_h,
  output logic orig_sel_snorm_exa_h,
  output logic new_sel_snorm_exa_h,
  output logic orig_sel_g1sk2_exa_h,
  output logic new_sel_g1sk2_exa_h,
  output logic orig_sel_g1sk8_exa_h,
  output logic new_sel_g1sk8_exa_h,
  output logic orig_sel_g1sk16_exa_h,
  output logic new_sel_g1sk16_exa_h,
  output logic orig_sel_g1sk24_exa_h,
  output logic new_sel_g1sk24_exa_h,
  output logic orig_sel_xexpfrac_exa_h,
  output logic new_sel_xexpfrac_exa_h,
  output logic [1:0] orig_sel_transfa_exa_h,
  output logic [1:0] new_sel_transfa_exa_h,
  output logic [1:0] orig_sel_transfb_exa_h,
  output logic [1:0] new_sel_transfb_exa_h,
  output logic [1:0] orig_sel_opafmt_exa_h,
  output logic [1:0] new_sel_opafmt_exa_h,
  output logic [1:0] orig_sel_opbfmt_exa_h,
  output logic [1:0] new_sel_opbfmt_exa_h,
  output logic orig_mul_sign_f0a_h,
  output logic new_mul_sign_f0a_h,
  output logic orig_mul_hp_mode_f0a_h,
  output logic new_mul_hp_mode_f0a_h,
  output logic orig_res_inf_f0a_h,
  output logic new_res_inf_f0a_h,
  output logic orig_res_snan_f0a_h,
  output logic new_res_snan_f0a_h,
  output logic orig_res_qnan_f0a_h,
  output logic new_res_qnan_f0a_h,
  output logic [FP_CLASS_BITS-1:0] orig_classify_f0a_h,
  output logic [FP_CLASS_BITS-1:0] new_classify_f0a_h,
  output logic orig_prod_inf_hi_f0a_h,
  output logic new_prod_inf_hi_f0a_h,
  output logic orig_c_inf_f0a_h,
  output logic new_c_inf_f0a_h,
  output logic orig_a_inf_f0a_h,
  output logic new_a_inf_f0a_h,
  output logic [VPU_FLAGS_SZ-1:0] orig_flags_f0a_h,
  output logic [VPU_FLAGS_SZ-1:0] new_flags_f0a_h,
  output logic orig_a_is_qnan_hi_f0a_h,
  output logic new_a_is_qnan_hi_f0a_h,
  output logic orig_c_is_qnan_f0a_h,
  output logic new_c_is_qnan_f0a_h,
  output logic orig_a_is_snan_hi_f0a_h,
  output logic new_a_is_snan_hi_f0a_h,
  output logic orig_c_is_snan_f0a_h,
  output logic new_c_is_snan_f0a_h,
  output logic orig_res_pos_int_nan_f0a_h,
  output logic new_res_pos_int_nan_f0a_h,
  output logic orig_res_neg_int_nan_f0a_h,
  output logic new_res_neg_int_nan_f0a_h,
  output logic orig_fc_zero30_8_f0a_h,
  output logic new_fc_zero30_8_f0a_h,
  output logic orig_res_uint_nan_f0a_h,
  output logic new_res_uint_nan_f0a_h,
  output logic orig_res_zero_f0a_h,
  output logic new_res_zero_f0a_h,
  output logic orig_res_one_f0a_h,
  output logic new_res_one_f0a_h,
  output logic orig_prod_inf_lo_f0a_h,
  output logic new_prod_inf_lo_f0a_h,
  output logic orig_fa_hi_zero_f0a_h,
  output logic new_fa_hi_zero_f0a_h,
  output logic orig_fb_hi_zero_f0a_h,
  output logic new_fb_hi_zero_f0a_h,
  output logic orig_res_unorm_one_f0a_h,
  output logic new_res_unorm_one_f0a_h,
  output logic orig_res_snorm_one_f0a_h,
  output logic new_res_snorm_one_f0a_h,
  output logic orig_flags_en_f0a_h,
  output logic new_flags_en_f0a_h,
  output logic orig_dtps_f0a_h,
  output logic new_dtps_f0a_h,
  output logic orig_spec_res_en_f0a_h,
  output logic new_spec_res_en_f0a_h,
  output logic orig_use_prev_sigs_f0a_h,
  output logic new_use_prev_sigs_f0a_h,
  output logic [TXFMA_RM_SZ-1:0] orig_rm_f0a_h,
  output logic [TXFMA_RM_SZ-1:0] new_rm_f0a_h,
  output logic [VPU_FCMD_SZ-1:0] orig_cmd_f0a_h,
  output logic [VPU_FCMD_SZ-1:0] new_cmd_f0a_h,
  output logic [TXFMA_SIGS_SZ-1:0] orig_sigs_f0a_h,
  output logic [TXFMA_SIGS_SZ-1:0] new_sigs_f0a_h,
  output logic [VPU_DTYPE_SZ-1:0] orig_op_dtype_f0a_h,
  output logic [VPU_DTYPE_SZ-1:0] new_op_dtype_f0a_h,
  output logic [2:0] orig_sin_res_shf_idx_f0a_h,
  output logic [2:0] new_sin_res_shf_idx_f0a_h,
  output logic orig_flog_mul_prod_zero_f0a_h,
  output logic new_flog_mul_prod_zero_f0a_h,
  output logic orig_ec_zero_clr_f0a_h,
  output logic new_ec_zero_clr_f0a_h,
  output logic orig_use_mul_f0a_h,
  output logic new_use_mul_f0a_h
);

  minion_pkg::vpu_ctrl_sigs_t sigs_in_exa_h;
  assign sigs_in_exa_h = minion_pkg::vpu_ctrl_sigs_t'(sigs_in_exa_h_bits);

  txfma_c0_orig u_orig (
    .clock (clk_i),
    .reset (!rst_ni),
    .in_valid_exa_h (in_valid_exa_h),
    .sigs_in_exa_h (sigs_in_exa_h),
    .rm_in_exa_h (rm_in_exa_h),
    .trans_mask_exa_h (trans_mask_exa_h),
    .trans_taylor_exa_h (trans_taylor_exa_h),
    .trans_exp_fma2_exc_exa_h (trans_exp_fma2_exc_exa_h),
    .use_prev_sigs_exa_h (use_prev_sigs_exa_h),
    .sa_hi_f0a_h (sa_hi_f0a_h),
    .sa_lo_f0a_h (sa_lo_f0a_h),
    .sb_hi_f0a_h (sb_hi_f0a_h),
    .sb_lo_f0a_h (sb_lo_f0a_h),
    .sc_f0a_h (sc_f0a_h),
    .ea_hi_zero_f0a_l (ea_hi_zero_f0a_l),
    .ea_hi_all1_f0a_h (ea_hi_all1_f0a_h),
    .ea_lo_zero_f0a_l (ea_lo_zero_f0a_l),
    .ea_lo_all1_f0a_h (ea_lo_all1_f0a_h),
    .eb_hi_zero_f0a_l (eb_hi_zero_f0a_l),
    .eb_hi_all1_f0a_h (eb_hi_all1_f0a_h),
    .eb_lo_zero_f0a_l (eb_lo_zero_f0a_l),
    .eb_lo_all1_f0a_h (eb_lo_all1_f0a_h),
    .ec_zero_f0a_l (ec_zero_f0a_l),
    .ec_all1_f0a_h (ec_all1_f0a_h),
    .eb_eql_127_f0a_h (eb_eql_127_f0a_h),
    .eb_eql_126_f0a_h (eb_eql_126_f0a_h),
    .eb_eql_125_f0a_h (eb_eql_125_f0a_h),
    .fcf10_zero_f0a_l (fcf10_zero_f0a_l),
    .fcf11_zero_f0a_l (fcf11_zero_f0a_l),
    .fcps_zero_f0a_h (fcps_zero_f0a_h),
    .fcph_zero_f0a_l (fcph_zero_f0a_l),
    .fcnorm_zero_29_8_f0a_h (fcnorm_zero_29_8_f0a_h),
    .fcnorm16_eq_1_f0a_h (fcnorm16_eq_1_f0a_h),
    .fcnorm8_eq_1_f0a_h (fcnorm8_eq_1_f0a_h),
    .fcn8_one_30_24_f0a_h (fcn8_one_30_24_f0a_h),
    .fcn10_one_30_22_f0a_h (fcn10_one_30_22_f0a_h),
    .fcn16_one_30_16_f0a_h (fcn16_one_30_16_f0a_h),
    .fcn24_one_30_8_f0a_h (fcn24_one_30_8_f0a_h),
    .faps_zero_f0a_l (faps_zero_f0a_l),
    .fbps_zero_f0a_l (fbps_zero_f0a_l),
    .faph_hi_zero_f0a_l (faph_hi_zero_f0a_l),
    .fbph_hi_zero_f0a_l (fbph_hi_zero_f0a_l),
    .faph_lo_zero_f0a_l (faph_lo_zero_f0a_l),
    .fbph_lo_zero_f0a_l (fbph_lo_zero_f0a_l),
    .faph_lo_b0_f0a_h (faph_lo_b0_f0a_h),
    .fbph_lo_b0_f0a_h (fbph_lo_b0_f0a_h),
    .faps_b0_f0a_h (faps_b0_f0a_h),
    .fbps_b0_f0a_h (fbps_b0_f0a_h),
    .fc_31_f0a_h (fc_31_f0a_h),
    .fcnorm_30_f0a_h (fcnorm_30_f0a_h),
    .faph_hi_b0_f0a_h (faph_hi_b0_f0a_h),
    .fbph_hi_b0_f0a_h (fbph_hi_b0_f0a_h),
    .fcph_b0_f0a_h (fcph_b0_f0a_h),
    .fcf11_b0_f0a_h (fcf11_b0_f0a_h),
    .fcf10_b0_f0a_h (fcf10_b0_f0a_h),
    .fcps_b0_f0a_h (fcps_b0_f0a_h),
    .trans_exp_fma2_exc_f0a_h (orig_trans_exp_fma2_exc_f0a_h),
    .opa_valid_rfa_h (orig_opa_valid_rfa_h),
    .opb_valid_rfa_h (orig_opb_valid_rfa_h),
    .opc_valid_rfa_h (orig_opc_valid_rfa_h),
    .ctrl_valid_f0a_h (orig_ctrl_valid_f0a_h),
    .is_trans_rfa_h (orig_is_trans_rfa_h),
    .eb_hi_k_exa_h (orig_eb_hi_k_exa_h),
    .fa_en_exa_h (orig_fa_en_exa_h),
    .fb_en_exa_h (orig_fb_en_exa_h),
    .fc_en_exa_h (orig_fc_en_exa_h),
    .sa_hi_en_exa_h (orig_sa_hi_en_exa_h),
    .sa_lo_en_exa_h (orig_sa_lo_en_exa_h),
    .sb_hi_en_exa_h (orig_sb_hi_en_exa_h),
    .sb_lo_en_exa_h (orig_sb_lo_en_exa_h),
    .ea_hi_zero_clr_f0a_h (orig_ea_hi_zero_clr_f0a_h),
    .eb_hi_zero_clr_f0a_h (orig_eb_hi_zero_clr_f0a_h),
    .ea_lo_zero_clr_f0a_h (orig_ea_lo_zero_clr_f0a_h),
    .eb_lo_zero_clr_f0a_h (orig_eb_lo_zero_clr_f0a_h),
    .sel_eainmux_exa_h (orig_sel_eainmux_exa_h),
    .sel_ealo_ph_exa_h (orig_sel_ealo_ph_exa_h),
    .ehi_ea_en_exa_h (orig_ehi_ea_en_exa_h),
    .elo_ea_en_exa_h (orig_elo_ea_en_exa_h),
    .sel_ebin_hi_exa_h (orig_sel_ebin_hi_exa_h),
    .sel_eblo_ph_exa_h (orig_sel_eblo_ph_exa_h),
    .ehi_eb_en_exa_h (orig_ehi_eb_en_exa_h),
    .elo_eb_en_exa_h (orig_elo_eb_en_exa_h),
    .sel_ec5b_exa_h (orig_sel_ec5b_exa_h),
    .sel_ecin_exa_h (orig_sel_ecin_exa_h),
    .ec_en_exa_h (orig_ec_en_exa_h),
    .sel_ec5bdet_exa_h (orig_sel_ec5bdet_exa_h),
    .sc_en_exa_h (orig_sc_en_exa_h),
    .sa1_nr2_frcpfxp_exa_h (orig_sa1_nr2_frcpfxp_exa_h),
    .sel_sc_exa_h (orig_sel_sc_exa_h),
    .sel_sign_sinp2_exa_h (orig_sel_sign_sinp2_exa_h),
    .sa_zap_exa_l (orig_sa_zap_exa_l),
    .sb_zap_exa_l (orig_sb_zap_exa_l),
    .sel_f10_exa_h (orig_sel_f10_exa_h),
    .sel_f11_exa_h (orig_sel_f11_exa_h),
    .sel_opcgfx_exa_h (orig_sel_opcgfx_exa_h),
    .fc_dtps_exa_h (orig_fc_dtps_exa_h),
    .neg_fmaop_exa_h (orig_neg_fmaop_exa_h),
    .trans_op2_exa_l (orig_trans_op2_exa_l),
    .sel_xopc_exa_h (orig_sel_xopc_exa_h),
    .sel_opcfmt_exa_h (orig_sel_opcfmt_exa_h),
    .sel_snorm_exa_h (orig_sel_snorm_exa_h),
    .sel_g1sk2_exa_h (orig_sel_g1sk2_exa_h),
    .sel_g1sk8_exa_h (orig_sel_g1sk8_exa_h),
    .sel_g1sk16_exa_h (orig_sel_g1sk16_exa_h),
    .sel_g1sk24_exa_h (orig_sel_g1sk24_exa_h),
    .sel_xexpfrac_exa_h (orig_sel_xexpfrac_exa_h),
    .sel_transfa_exa_h (orig_sel_transfa_exa_h),
    .sel_transfb_exa_h (orig_sel_transfb_exa_h),
    .sel_opafmt_exa_h (orig_sel_opafmt_exa_h),
    .sel_opbfmt_exa_h (orig_sel_opbfmt_exa_h),
    .mul_sign_f0a_h (orig_mul_sign_f0a_h),
    .mul_hp_mode_f0a_h (orig_mul_hp_mode_f0a_h),
    .res_inf_f0a_h (orig_res_inf_f0a_h),
    .res_snan_f0a_h (orig_res_snan_f0a_h),
    .res_qnan_f0a_h (orig_res_qnan_f0a_h),
    .classify_f0a_h (orig_classify_f0a_h),
    .prod_inf_hi_f0a_h (orig_prod_inf_hi_f0a_h),
    .c_inf_f0a_h (orig_c_inf_f0a_h),
    .a_inf_f0a_h (orig_a_inf_f0a_h),
    .flags_f0a_h (orig_flags_f0a_h),
    .a_is_qnan_hi_f0a_h (orig_a_is_qnan_hi_f0a_h),
    .c_is_qnan_f0a_h (orig_c_is_qnan_f0a_h),
    .a_is_snan_hi_f0a_h (orig_a_is_snan_hi_f0a_h),
    .c_is_snan_f0a_h (orig_c_is_snan_f0a_h),
    .res_pos_int_nan_f0a_h (orig_res_pos_int_nan_f0a_h),
    .res_neg_int_nan_f0a_h (orig_res_neg_int_nan_f0a_h),
    .fc_zero30_8_f0a_h (orig_fc_zero30_8_f0a_h),
    .res_uint_nan_f0a_h (orig_res_uint_nan_f0a_h),
    .res_zero_f0a_h (orig_res_zero_f0a_h),
    .res_one_f0a_h (orig_res_one_f0a_h),
    .prod_inf_lo_f0a_h (orig_prod_inf_lo_f0a_h),
    .fa_hi_zero_f0a_h (orig_fa_hi_zero_f0a_h),
    .fb_hi_zero_f0a_h (orig_fb_hi_zero_f0a_h),
    .res_unorm_one_f0a_h (orig_res_unorm_one_f0a_h),
    .res_snorm_one_f0a_h (orig_res_snorm_one_f0a_h),
    .flags_en_f0a_h (orig_flags_en_f0a_h),
    .dtps_f0a_h (orig_dtps_f0a_h),
    .spec_res_en_f0a_h (orig_spec_res_en_f0a_h),
    .use_prev_sigs_f0a_h (orig_use_prev_sigs_f0a_h),
    .rm_f0a_h (orig_rm_f0a_h),
    .cmd_f0a_h (orig_cmd_f0a_h),
    .sigs_f0a_h (orig_sigs_f0a_h),
    .op_dtype_f0a_h (orig_op_dtype_f0a_h),
    .sin_res_shf_idx_f0a_h (orig_sin_res_shf_idx_f0a_h),
    .flog_mul_prod_zero_f0a_h (orig_flog_mul_prod_zero_f0a_h),
    .ec_zero_clr_f0a_h (orig_ec_zero_clr_f0a_h),
    .use_mul_f0a_h (orig_use_mul_f0a_h)
  );

  txfma_c0 u_new (
    .clock (clk_i),
    .reset (!rst_ni),
    .in_valid_exa_h (in_valid_exa_h),
    .sigs_in_exa_h (sigs_in_exa_h),
    .rm_in_exa_h (rm_in_exa_h),
    .trans_mask_exa_h (trans_mask_exa_h),
    .trans_taylor_exa_h (trans_taylor_exa_h),
    .trans_exp_fma2_exc_exa_h (trans_exp_fma2_exc_exa_h),
    .use_prev_sigs_exa_h (use_prev_sigs_exa_h),
    .sa_hi_f0a_h (sa_hi_f0a_h),
    .sa_lo_f0a_h (sa_lo_f0a_h),
    .sb_hi_f0a_h (sb_hi_f0a_h),
    .sb_lo_f0a_h (sb_lo_f0a_h),
    .sc_f0a_h (sc_f0a_h),
    .ea_hi_zero_f0a_l (ea_hi_zero_f0a_l),
    .ea_hi_all1_f0a_h (ea_hi_all1_f0a_h),
    .ea_lo_zero_f0a_l (ea_lo_zero_f0a_l),
    .ea_lo_all1_f0a_h (ea_lo_all1_f0a_h),
    .eb_hi_zero_f0a_l (eb_hi_zero_f0a_l),
    .eb_hi_all1_f0a_h (eb_hi_all1_f0a_h),
    .eb_lo_zero_f0a_l (eb_lo_zero_f0a_l),
    .eb_lo_all1_f0a_h (eb_lo_all1_f0a_h),
    .ec_zero_f0a_l (ec_zero_f0a_l),
    .ec_all1_f0a_h (ec_all1_f0a_h),
    .eb_eql_127_f0a_h (eb_eql_127_f0a_h),
    .eb_eql_126_f0a_h (eb_eql_126_f0a_h),
    .eb_eql_125_f0a_h (eb_eql_125_f0a_h),
    .fcf10_zero_f0a_l (fcf10_zero_f0a_l),
    .fcf11_zero_f0a_l (fcf11_zero_f0a_l),
    .fcps_zero_f0a_h (fcps_zero_f0a_h),
    .fcph_zero_f0a_l (fcph_zero_f0a_l),
    .fcnorm_zero_29_8_f0a_h (fcnorm_zero_29_8_f0a_h),
    .fcnorm16_eq_1_f0a_h (fcnorm16_eq_1_f0a_h),
    .fcnorm8_eq_1_f0a_h (fcnorm8_eq_1_f0a_h),
    .fcn8_one_30_24_f0a_h (fcn8_one_30_24_f0a_h),
    .fcn10_one_30_22_f0a_h (fcn10_one_30_22_f0a_h),
    .fcn16_one_30_16_f0a_h (fcn16_one_30_16_f0a_h),
    .fcn24_one_30_8_f0a_h (fcn24_one_30_8_f0a_h),
    .faps_zero_f0a_l (faps_zero_f0a_l),
    .fbps_zero_f0a_l (fbps_zero_f0a_l),
    .faph_hi_zero_f0a_l (faph_hi_zero_f0a_l),
    .fbph_hi_zero_f0a_l (fbph_hi_zero_f0a_l),
    .faph_lo_zero_f0a_l (faph_lo_zero_f0a_l),
    .fbph_lo_zero_f0a_l (fbph_lo_zero_f0a_l),
    .faph_lo_b0_f0a_h (faph_lo_b0_f0a_h),
    .fbph_lo_b0_f0a_h (fbph_lo_b0_f0a_h),
    .faps_b0_f0a_h (faps_b0_f0a_h),
    .fbps_b0_f0a_h (fbps_b0_f0a_h),
    .fc_31_f0a_h (fc_31_f0a_h),
    .fcnorm_30_f0a_h (fcnorm_30_f0a_h),
    .faph_hi_b0_f0a_h (faph_hi_b0_f0a_h),
    .fbph_hi_b0_f0a_h (fbph_hi_b0_f0a_h),
    .fcph_b0_f0a_h (fcph_b0_f0a_h),
    .fcf11_b0_f0a_h (fcf11_b0_f0a_h),
    .fcf10_b0_f0a_h (fcf10_b0_f0a_h),
    .fcps_b0_f0a_h (fcps_b0_f0a_h),
    .trans_exp_fma2_exc_f0a_h (new_trans_exp_fma2_exc_f0a_h),
    .opa_valid_rfa_h (new_opa_valid_rfa_h),
    .opb_valid_rfa_h (new_opb_valid_rfa_h),
    .opc_valid_rfa_h (new_opc_valid_rfa_h),
    .ctrl_valid_f0a_h (new_ctrl_valid_f0a_h),
    .is_trans_rfa_h (new_is_trans_rfa_h),
    .eb_hi_k_exa_h (new_eb_hi_k_exa_h),
    .fa_en_exa_h (new_fa_en_exa_h),
    .fb_en_exa_h (new_fb_en_exa_h),
    .fc_en_exa_h (new_fc_en_exa_h),
    .sa_hi_en_exa_h (new_sa_hi_en_exa_h),
    .sa_lo_en_exa_h (new_sa_lo_en_exa_h),
    .sb_hi_en_exa_h (new_sb_hi_en_exa_h),
    .sb_lo_en_exa_h (new_sb_lo_en_exa_h),
    .ea_hi_zero_clr_f0a_h (new_ea_hi_zero_clr_f0a_h),
    .eb_hi_zero_clr_f0a_h (new_eb_hi_zero_clr_f0a_h),
    .ea_lo_zero_clr_f0a_h (new_ea_lo_zero_clr_f0a_h),
    .eb_lo_zero_clr_f0a_h (new_eb_lo_zero_clr_f0a_h),
    .sel_eainmux_exa_h (new_sel_eainmux_exa_h),
    .sel_ealo_ph_exa_h (new_sel_ealo_ph_exa_h),
    .ehi_ea_en_exa_h (new_ehi_ea_en_exa_h),
    .elo_ea_en_exa_h (new_elo_ea_en_exa_h),
    .sel_ebin_hi_exa_h (new_sel_ebin_hi_exa_h),
    .sel_eblo_ph_exa_h (new_sel_eblo_ph_exa_h),
    .ehi_eb_en_exa_h (new_ehi_eb_en_exa_h),
    .elo_eb_en_exa_h (new_elo_eb_en_exa_h),
    .sel_ec5b_exa_h (new_sel_ec5b_exa_h),
    .sel_ecin_exa_h (new_sel_ecin_exa_h),
    .ec_en_exa_h (new_ec_en_exa_h),
    .sel_ec5bdet_exa_h (new_sel_ec5bdet_exa_h),
    .sc_en_exa_h (new_sc_en_exa_h),
    .sa1_nr2_frcpfxp_exa_h (new_sa1_nr2_frcpfxp_exa_h),
    .sel_sc_exa_h (new_sel_sc_exa_h),
    .sel_sign_sinp2_exa_h (new_sel_sign_sinp2_exa_h),
    .sa_zap_exa_l (new_sa_zap_exa_l),
    .sb_zap_exa_l (new_sb_zap_exa_l),
    .sel_f10_exa_h (new_sel_f10_exa_h),
    .sel_f11_exa_h (new_sel_f11_exa_h),
    .sel_opcgfx_exa_h (new_sel_opcgfx_exa_h),
    .fc_dtps_exa_h (new_fc_dtps_exa_h),
    .neg_fmaop_exa_h (new_neg_fmaop_exa_h),
    .trans_op2_exa_l (new_trans_op2_exa_l),
    .sel_xopc_exa_h (new_sel_xopc_exa_h),
    .sel_opcfmt_exa_h (new_sel_opcfmt_exa_h),
    .sel_snorm_exa_h (new_sel_snorm_exa_h),
    .sel_g1sk2_exa_h (new_sel_g1sk2_exa_h),
    .sel_g1sk8_exa_h (new_sel_g1sk8_exa_h),
    .sel_g1sk16_exa_h (new_sel_g1sk16_exa_h),
    .sel_g1sk24_exa_h (new_sel_g1sk24_exa_h),
    .sel_xexpfrac_exa_h (new_sel_xexpfrac_exa_h),
    .sel_transfa_exa_h (new_sel_transfa_exa_h),
    .sel_transfb_exa_h (new_sel_transfb_exa_h),
    .sel_opafmt_exa_h (new_sel_opafmt_exa_h),
    .sel_opbfmt_exa_h (new_sel_opbfmt_exa_h),
    .mul_sign_f0a_h (new_mul_sign_f0a_h),
    .mul_hp_mode_f0a_h (new_mul_hp_mode_f0a_h),
    .res_inf_f0a_h (new_res_inf_f0a_h),
    .res_snan_f0a_h (new_res_snan_f0a_h),
    .res_qnan_f0a_h (new_res_qnan_f0a_h),
    .classify_f0a_h (new_classify_f0a_h),
    .prod_inf_hi_f0a_h (new_prod_inf_hi_f0a_h),
    .c_inf_f0a_h (new_c_inf_f0a_h),
    .a_inf_f0a_h (new_a_inf_f0a_h),
    .flags_f0a_h (new_flags_f0a_h),
    .a_is_qnan_hi_f0a_h (new_a_is_qnan_hi_f0a_h),
    .c_is_qnan_f0a_h (new_c_is_qnan_f0a_h),
    .a_is_snan_hi_f0a_h (new_a_is_snan_hi_f0a_h),
    .c_is_snan_f0a_h (new_c_is_snan_f0a_h),
    .res_pos_int_nan_f0a_h (new_res_pos_int_nan_f0a_h),
    .res_neg_int_nan_f0a_h (new_res_neg_int_nan_f0a_h),
    .fc_zero30_8_f0a_h (new_fc_zero30_8_f0a_h),
    .res_uint_nan_f0a_h (new_res_uint_nan_f0a_h),
    .res_zero_f0a_h (new_res_zero_f0a_h),
    .res_one_f0a_h (new_res_one_f0a_h),
    .prod_inf_lo_f0a_h (new_prod_inf_lo_f0a_h),
    .fa_hi_zero_f0a_h (new_fa_hi_zero_f0a_h),
    .fb_hi_zero_f0a_h (new_fb_hi_zero_f0a_h),
    .res_unorm_one_f0a_h (new_res_unorm_one_f0a_h),
    .res_snorm_one_f0a_h (new_res_snorm_one_f0a_h),
    .flags_en_f0a_h (new_flags_en_f0a_h),
    .dtps_f0a_h (new_dtps_f0a_h),
    .spec_res_en_f0a_h (new_spec_res_en_f0a_h),
    .use_prev_sigs_f0a_h (new_use_prev_sigs_f0a_h),
    .rm_f0a_h (new_rm_f0a_h),
    .cmd_f0a_h (new_cmd_f0a_h),
    .sigs_f0a_h (new_sigs_f0a_h),
    .op_dtype_f0a_h (new_op_dtype_f0a_h),
    .sin_res_shf_idx_f0a_h (new_sin_res_shf_idx_f0a_h),
    .flog_mul_prod_zero_f0a_h (new_flog_mul_prod_zero_f0a_h),
    .ec_zero_clr_f0a_h (new_ec_zero_clr_f0a_h),
    .use_mul_f0a_h (new_use_mul_f0a_h)
  );

endmodule : cosim_txfma_c0_tb
