EXTRA_CFLAGS=-Wl,-section-start=.operands_array=0x0000008000200000
EXTRA_CFLAGS=-Wl,-section-start=.result_array=0x0000008000400000
EXTRA_CFLAGS=-Wl,-section-start=.address_array=0x0000008000800000

include $(MINION_DIAGS)/common/include.mk
