/* Copyright (c) 2026 Ainekko          */
/* SPDX-License-Identifier: Apache-2.0 */

#include "cpu.h"
#include "tb.h"
#include "soc.h"
#include "macros.h"
#include "plic_api.h"
#include "fcc.h"
#include "esr.h"
#include <inttypes.h>
#include "macros.h"
#include "minion.h"
#include "esr_rw.h"
#include "et_test_common.h"

#define ESR_ICACHE_ERR_LOG_CTL     0xF

int main()
{

    volatile uint64_t  shire_id = get_shire_id();
    volatile uint64_t* pAddr;
    long long int addr = 0x8000000000;

    C_TEST_START;

    if (shire_id == 0) {
        int ii;

        wait_for_credit(0);

        /* Configure and enable interrupt on Minion ICache */
        //write_esr(PP_MACHINE, shire_id, REGION_SHIRE_CACHE, ESR_ICACHE_ERR_LOG_CTL, 0x2);

        // Perform the following loop twice.  The first time through, there should be no
        // ECC error ... at the end of the loop, a magic opcode (slti t0, t0, 0x700) is
        // performed ... that will notify the TCL script to insert an I-cache error at the
        // address of the cache line just before the magic opcode ... as a result, the
        // second time through the loop we should see an ECC error.
        pAddr  = (uint64_t*) addr;
        *pAddr = 0xBABEBABEBABEBABE;
        for (ii = 0; ii < 2; ii++) {
            // The following code is essentially a do-nothing piece of code just to use a
            // number of I-cache entries.
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;
            *pAddr = *pAddr + 1;

            // At the end of the loop, trigger the TCL script.
            __asm__ __volatile__ (
               "slti t0, t0, 1792\n"      // magic instruction to trigger double bit error injection
               "nop\n"
               "nop\n"
               "nop\n"
               "nop\n"
               "nop\n"
               :
               :
               : "t0"
            );
        }
    }

    C_TEST_PASS;
}
