// Copyright (c) 2026 Ainekko
// SPDX-License-Identifier: Apache-2.0

#include "Vcosim_txfma_f0_tb.h"
#include "cosim_ctrl.h"

#include <cstdint>
#include <string>

using DUT = Vcosim_txfma_f0_tb;

namespace {

constexpr int kRandomIters = 925;

uint64_t rand64(uint64_t& state) {
    state ^= state << 13;
    state ^= state >> 7;
    state ^= state << 17;
    return state;
}

struct WordCoverage {
    uint64_t mask;
    uint64_t or_mask = 0;
    uint64_t and_mask;
    explicit WordCoverage(uint64_t m) : mask(m), and_mask(m) {}
    void observe(uint64_t value) {
        value &= mask;
        or_mask |= value;
        and_mask &= value;
    }
};

void compare_outputs(CosimCtrl<DUT>& sim) {
    sim.compare("sa_hi_f0a_h", sim.dut->orig_sa_hi_f0a_h, sim.dut->new_sa_hi_f0a_h);
    sim.compare("sa_lo_f0a_h", sim.dut->orig_sa_lo_f0a_h, sim.dut->new_sa_lo_f0a_h);
    sim.compare("sb_hi_f0a_h", sim.dut->orig_sb_hi_f0a_h, sim.dut->new_sb_hi_f0a_h);
    sim.compare("sb_lo_f0a_h", sim.dut->orig_sb_lo_f0a_h, sim.dut->new_sb_lo_f0a_h);
    sim.compare("sc_f0a_h", sim.dut->orig_sc_f0a_h, sim.dut->new_sc_f0a_h);
    sim.compare("ea_hi_f0a_h", sim.dut->orig_ea_hi_f0a_h, sim.dut->new_ea_hi_f0a_h);
    sim.compare("ea_lo_f0a_h", sim.dut->orig_ea_lo_f0a_h, sim.dut->new_ea_lo_f0a_h);
    sim.compare("eb_hi_f0a_h", sim.dut->orig_eb_hi_f0a_h, sim.dut->new_eb_hi_f0a_h);
    sim.compare("eb_lo_f0a_h", sim.dut->orig_eb_lo_f0a_h, sim.dut->new_eb_lo_f0a_h);
    sim.compare("ec_f0a_h", sim.dut->orig_ec_f0a_h, sim.dut->new_ec_f0a_h);
    sim.compare("fa_f0a_h", sim.dut->orig_fa_f0a_h, sim.dut->new_fa_f0a_h);
    sim.compare("fb_f0a_h", sim.dut->orig_fb_f0a_h, sim.dut->new_fb_f0a_h);
    sim.compare("fc_f0a_h", sim.dut->orig_fc_f0a_h, sim.dut->new_fc_f0a_h);
    sim.compare("ea_hi_zero_f0a_l", sim.dut->orig_ea_hi_zero_f0a_l, sim.dut->new_ea_hi_zero_f0a_l);
    sim.compare("ea_hi_all1_f0a_h", sim.dut->orig_ea_hi_all1_f0a_h, sim.dut->new_ea_hi_all1_f0a_h);
    sim.compare("ea_lo_zero_f0a_l", sim.dut->orig_ea_lo_zero_f0a_l, sim.dut->new_ea_lo_zero_f0a_l);
    sim.compare("ea_lo_all1_f0a_h", sim.dut->orig_ea_lo_all1_f0a_h, sim.dut->new_ea_lo_all1_f0a_h);
    sim.compare("eb_hi_zero_f0a_l", sim.dut->orig_eb_hi_zero_f0a_l, sim.dut->new_eb_hi_zero_f0a_l);
    sim.compare("eb_hi_all1_f0a_h", sim.dut->orig_eb_hi_all1_f0a_h, sim.dut->new_eb_hi_all1_f0a_h);
    sim.compare("eb_lo_zero_f0a_l", sim.dut->orig_eb_lo_zero_f0a_l, sim.dut->new_eb_lo_zero_f0a_l);
    sim.compare("eb_lo_all1_f0a_h", sim.dut->orig_eb_lo_all1_f0a_h, sim.dut->new_eb_lo_all1_f0a_h);
    sim.compare("ec_zero_f0a_l", sim.dut->orig_ec_zero_f0a_l, sim.dut->new_ec_zero_f0a_l);
    sim.compare("ec_all1_f0a_h", sim.dut->orig_ec_all1_f0a_h, sim.dut->new_ec_all1_f0a_h);
    sim.compare("fcf10_zero_f0a_l", sim.dut->orig_fcf10_zero_f0a_l, sim.dut->new_fcf10_zero_f0a_l);
    sim.compare("eb_eql_127_f0a_h", sim.dut->orig_eb_eql_127_f0a_h, sim.dut->new_eb_eql_127_f0a_h);
    sim.compare("eb_eql_126_f0a_h", sim.dut->orig_eb_eql_126_f0a_h, sim.dut->new_eb_eql_126_f0a_h);
    sim.compare("eb_eql_125_f0a_h", sim.dut->orig_eb_eql_125_f0a_h, sim.dut->new_eb_eql_125_f0a_h);
    sim.compare("fcf11_zero_f0a_l", sim.dut->orig_fcf11_zero_f0a_l, sim.dut->new_fcf11_zero_f0a_l);
    sim.compare("fcps_zero_f0a_h", sim.dut->orig_fcps_zero_f0a_h, sim.dut->new_fcps_zero_f0a_h);
    sim.compare("fcph_zero_f0a_l", sim.dut->orig_fcph_zero_f0a_l, sim.dut->new_fcph_zero_f0a_l);
    sim.compare("fcnorm_zero_29_8_f0a_h", sim.dut->orig_fcnorm_zero_29_8_f0a_h, sim.dut->new_fcnorm_zero_29_8_f0a_h);
    sim.compare("fcnorm16_eq_1_f0a_h", sim.dut->orig_fcnorm16_eq_1_f0a_h, sim.dut->new_fcnorm16_eq_1_f0a_h);
    sim.compare("fcnorm8_eq_1_f0a_h", sim.dut->orig_fcnorm8_eq_1_f0a_h, sim.dut->new_fcnorm8_eq_1_f0a_h);
    sim.compare("fcn8_one_30_24_f0a_h", sim.dut->orig_fcn8_one_30_24_f0a_h, sim.dut->new_fcn8_one_30_24_f0a_h);
    sim.compare("fcn10_one_30_22_f0a_h", sim.dut->orig_fcn10_one_30_22_f0a_h, sim.dut->new_fcn10_one_30_22_f0a_h);
    sim.compare("fcn16_one_30_16_f0a_h", sim.dut->orig_fcn16_one_30_16_f0a_h, sim.dut->new_fcn16_one_30_16_f0a_h);
    sim.compare("fcn24_one_30_8_f0a_h", sim.dut->orig_fcn24_one_30_8_f0a_h, sim.dut->new_fcn24_one_30_8_f0a_h);
    sim.compare("faps_zero_f0a_l", sim.dut->orig_faps_zero_f0a_l, sim.dut->new_faps_zero_f0a_l);
    sim.compare("fbps_zero_f0a_l", sim.dut->orig_fbps_zero_f0a_l, sim.dut->new_fbps_zero_f0a_l);
    sim.compare("faph_hi_zero_f0a_l", sim.dut->orig_faph_hi_zero_f0a_l, sim.dut->new_faph_hi_zero_f0a_l);
    sim.compare("fbph_hi_zero_f0a_l", sim.dut->orig_fbph_hi_zero_f0a_l, sim.dut->new_fbph_hi_zero_f0a_l);
    sim.compare("faph_lo_zero_f0a_l", sim.dut->orig_faph_lo_zero_f0a_l, sim.dut->new_faph_lo_zero_f0a_l);
    sim.compare("fbph_lo_zero_f0a_l", sim.dut->orig_fbph_lo_zero_f0a_l, sim.dut->new_fbph_lo_zero_f0a_l);
    sim.compare("faph_lo_b0_f0a_h", sim.dut->orig_faph_lo_b0_f0a_h, sim.dut->new_faph_lo_b0_f0a_h);
    sim.compare("fbph_lo_b0_f0a_h", sim.dut->orig_fbph_lo_b0_f0a_h, sim.dut->new_fbph_lo_b0_f0a_h);
    sim.compare("faps_b0_f0a_h", sim.dut->orig_faps_b0_f0a_h, sim.dut->new_faps_b0_f0a_h);
    sim.compare("fbps_b0_f0a_h", sim.dut->orig_fbps_b0_f0a_h, sim.dut->new_fbps_b0_f0a_h);
    sim.compare("fc_31_f0a_h", sim.dut->orig_fc_31_f0a_h, sim.dut->new_fc_31_f0a_h);
    sim.compare("fcnorm_30_f0a_h", sim.dut->orig_fcnorm_30_f0a_h, sim.dut->new_fcnorm_30_f0a_h);
    sim.compare("faph_hi_b0_f0a_h", sim.dut->orig_faph_hi_b0_f0a_h, sim.dut->new_faph_hi_b0_f0a_h);
    sim.compare("fbph_hi_b0_f0a_h", sim.dut->orig_fbph_hi_b0_f0a_h, sim.dut->new_fbph_hi_b0_f0a_h);
    sim.compare("fcph_b0_f0a_h", sim.dut->orig_fcph_b0_f0a_h, sim.dut->new_fcph_b0_f0a_h);
    sim.compare("fcf11_b0_f0a_h", sim.dut->orig_fcf11_b0_f0a_h, sim.dut->new_fcf11_b0_f0a_h);
    sim.compare("fcf10_b0_f0a_h", sim.dut->orig_fcf10_b0_f0a_h, sim.dut->new_fcf10_b0_f0a_h);
    sim.compare("fcps_b0_f0a_h", sim.dut->orig_fcps_b0_f0a_h, sim.dut->new_fcps_b0_f0a_h);
}

void step_and_compare(CosimCtrl<DUT>& sim) {
    sim.dut->opa_frf_clk = 0;
    sim.dut->opb_frf_clk = 0;
    sim.dut->opc_frf_clk = 0;
    sim.dut->trans_frf_clk = 0;
    sim.dut->ctrl_frf_clk = 0;
    sim.dut->eval();
    sim.sim_time++;
    sim.dut->opa_frf_clk = 1;
    sim.dut->opb_frf_clk = 1;
    sim.dut->opc_frf_clk = 1;
    sim.dut->trans_frf_clk = 1;
    sim.dut->ctrl_frf_clk = 1;
    sim.dut->eval();
    compare_outputs(sim);
    sim.sim_time++;
    sim.dut->opa_frf_clk = 0;
    sim.dut->opb_frf_clk = 0;
    sim.dut->opc_frf_clk = 0;
    sim.dut->trans_frf_clk = 0;
    sim.dut->ctrl_frf_clk = 0;
    sim.dut->eval();
    sim.sim_time++;
}

void check_coverage(CosimCtrl<DUT>& sim, const WordCoverage& coverage, const char* name) {
    sim.check(coverage.or_mask == coverage.mask, std::string(name) + " should drive every bit high");
    sim.check(coverage.and_mask == 0ull, std::string(name) + " should drive every bit low");
}

}  // namespace

int main(int argc, char** argv) {
    CosimCtrl<DUT> sim(argc, argv);
    uint64_t seed = 0x9e3779b97f4a7c15ull;
    WordCoverage opa_byp_frfa_h_cov(((1ull << 32) - 1ull));
    WordCoverage opc_byp_frfa_h_cov(((1ull << 32) - 1ull));
    WordCoverage opb_byp_frfa_h_cov(((1ull << 32) - 1ull));
    WordCoverage xrom_c1c0k_ra_h_cov(((1ull << 32) - 1ull));
    WordCoverage xrom_c2_ra_h_cov(((1ull << 17) - 1ull));
    WordCoverage trans_mask_ra_h_cov(((1ull << 7) - 1ull));
    WordCoverage eb_hi_k_exa_h_cov(((1ull << 6) - 1ull));
    WordCoverage sel_ebin_hi_exa_h_cov(((1ull << 2) - 1ull));
    WordCoverage sel_eainmux_exa_h_cov(((1ull << 2) - 1ull));
    WordCoverage sel_ec5b_exa_h_cov(((1ull << 2) - 1ull));
    WordCoverage sel_ecin_exa_h_cov(((1ull << 2) - 1ull));
    WordCoverage sel_ec5bdet_exa_h_cov(((1ull << 1) - 1ull));
    WordCoverage sel_sc_exa_h_cov(((1ull << 2) - 1ull));
    WordCoverage sel_opcgfx_exa_h_cov(((1ull << 2) - 1ull));
    WordCoverage sel_xopc_exa_h_cov(((1ull << 2) - 1ull));
    WordCoverage sel_opcfmt_exa_h_cov(((1ull << 2) - 1ull));
    WordCoverage sel_transfa_exa_h_cov(((1ull << 2) - 1ull));
    WordCoverage sel_transfb_exa_h_cov(((1ull << 2) - 1ull));
    WordCoverage sel_opafmt_exa_h_cov(((1ull << 2) - 1ull));
    WordCoverage sel_opbfmt_exa_h_cov(((1ull << 2) - 1ull));
    WordCoverage sel_eblo_ph_exa_h_cov(((1ull << 1) - 1ull));
    WordCoverage elo_eb_en_exa_h_cov(((1ull << 1) - 1ull));
    WordCoverage ehi_eb_en_exa_h_cov(((1ull << 1) - 1ull));
    WordCoverage elo_ea_en_exa_h_cov(((1ull << 1) - 1ull));
    WordCoverage fa_en_exa_h_cov(((1ull << 1) - 1ull));
    WordCoverage fb_en_exa_h_cov(((1ull << 1) - 1ull));
    WordCoverage fc_en_exa_h_cov(((1ull << 1) - 1ull));
    WordCoverage sel_ealo_ph_exa_h_cov(((1ull << 1) - 1ull));
    WordCoverage sa_hi_en_exa_h_cov(((1ull << 1) - 1ull));
    WordCoverage sa_lo_en_exa_h_cov(((1ull << 1) - 1ull));
    WordCoverage sb_hi_en_exa_h_cov(((1ull << 1) - 1ull));
    WordCoverage sb_lo_en_exa_h_cov(((1ull << 1) - 1ull));
    WordCoverage sc_en_exa_h_cov(((1ull << 1) - 1ull));
    WordCoverage ehi_ea_en_exa_h_cov(((1ull << 1) - 1ull));
    WordCoverage ec_en_exa_h_cov(((1ull << 1) - 1ull));
    WordCoverage neg_fmaop_exa_h_cov(((1ull << 1) - 1ull));
    WordCoverage trans_op2_exa_l_cov(((1ull << 1) - 1ull));
    WordCoverage sa1_nr2_frcpfxp_exa_h_cov(((1ull << 1) - 1ull));
    WordCoverage sel_sign_sinp2_exa_h_cov(((1ull << 1) - 1ull));
    WordCoverage sa_zap_exa_l_cov(((1ull << 1) - 1ull));
    WordCoverage sb_zap_exa_l_cov(((1ull << 1) - 1ull));
    WordCoverage sel_f10_exa_h_cov(((1ull << 1) - 1ull));
    WordCoverage sel_f11_exa_h_cov(((1ull << 1) - 1ull));
    WordCoverage fc_dtps_exa_h_cov(((1ull << 1) - 1ull));
    WordCoverage sel_snorm_exa_h_cov(((1ull << 1) - 1ull));
    WordCoverage sel_g1sk2_exa_h_cov(((1ull << 1) - 1ull));
    WordCoverage sel_g1sk8_exa_h_cov(((1ull << 1) - 1ull));
    WordCoverage sel_g1sk16_exa_h_cov(((1ull << 1) - 1ull));
    WordCoverage sel_g1sk24_exa_h_cov(((1ull << 1) - 1ull));
    WordCoverage sel_xexpfrac_exa_h_cov(((1ull << 1) - 1ull));

    // Directed all-zero input case.
    sim.dut->opa_byp_frfa_h = 0;
    sim.dut->opc_byp_frfa_h = 0;
    sim.dut->opb_byp_frfa_h = 0;
    sim.dut->xrom_c1c0k_ra_h = 0;
    sim.dut->xrom_c2_ra_h = 0;
    sim.dut->trans_mask_ra_h = 0;
    sim.dut->eb_hi_k_exa_h = 0;
    sim.dut->sel_ebin_hi_exa_h = 0;
    sim.dut->sel_eainmux_exa_h = 0;
    sim.dut->sel_ec5b_exa_h = 0;
    sim.dut->sel_ecin_exa_h = 0;
    sim.dut->sel_ec5bdet_exa_h = 0;
    sim.dut->sel_sc_exa_h = 0;
    sim.dut->sel_opcgfx_exa_h = 0;
    sim.dut->sel_xopc_exa_h = 0;
    sim.dut->sel_opcfmt_exa_h = 0;
    sim.dut->sel_transfa_exa_h = 0;
    sim.dut->sel_transfb_exa_h = 0;
    sim.dut->sel_opafmt_exa_h = 0;
    sim.dut->sel_opbfmt_exa_h = 0;
    sim.dut->sel_eblo_ph_exa_h = 0;
    sim.dut->elo_eb_en_exa_h = 0;
    sim.dut->ehi_eb_en_exa_h = 0;
    sim.dut->elo_ea_en_exa_h = 0;
    sim.dut->fa_en_exa_h = 0;
    sim.dut->fb_en_exa_h = 0;
    sim.dut->fc_en_exa_h = 0;
    sim.dut->sel_ealo_ph_exa_h = 0;
    sim.dut->sa_hi_en_exa_h = 0;
    sim.dut->sa_lo_en_exa_h = 0;
    sim.dut->sb_hi_en_exa_h = 0;
    sim.dut->sb_lo_en_exa_h = 0;
    sim.dut->sc_en_exa_h = 0;
    sim.dut->ehi_ea_en_exa_h = 0;
    sim.dut->ec_en_exa_h = 0;
    sim.dut->neg_fmaop_exa_h = 0;
    sim.dut->trans_op2_exa_l = 0;
    sim.dut->sa1_nr2_frcpfxp_exa_h = 0;
    sim.dut->sel_sign_sinp2_exa_h = 0;
    sim.dut->sa_zap_exa_l = 0;
    sim.dut->sb_zap_exa_l = 0;
    sim.dut->sel_f10_exa_h = 0;
    sim.dut->sel_f11_exa_h = 0;
    sim.dut->fc_dtps_exa_h = 0;
    sim.dut->sel_snorm_exa_h = 0;
    sim.dut->sel_g1sk2_exa_h = 0;
    sim.dut->sel_g1sk8_exa_h = 0;
    sim.dut->sel_g1sk16_exa_h = 0;
    sim.dut->sel_g1sk24_exa_h = 0;
    sim.dut->sel_xexpfrac_exa_h = 0;
    opa_byp_frfa_h_cov.observe(0);
    opc_byp_frfa_h_cov.observe(0);
    opb_byp_frfa_h_cov.observe(0);
    xrom_c1c0k_ra_h_cov.observe(0);
    xrom_c2_ra_h_cov.observe(0);
    trans_mask_ra_h_cov.observe(0);
    eb_hi_k_exa_h_cov.observe(0);
    sel_ebin_hi_exa_h_cov.observe(0);
    sel_eainmux_exa_h_cov.observe(0);
    sel_ec5b_exa_h_cov.observe(0);
    sel_ecin_exa_h_cov.observe(0);
    sel_ec5bdet_exa_h_cov.observe(0);
    sel_sc_exa_h_cov.observe(0);
    sel_opcgfx_exa_h_cov.observe(0);
    sel_xopc_exa_h_cov.observe(0);
    sel_opcfmt_exa_h_cov.observe(0);
    sel_transfa_exa_h_cov.observe(0);
    sel_transfb_exa_h_cov.observe(0);
    sel_opafmt_exa_h_cov.observe(0);
    sel_opbfmt_exa_h_cov.observe(0);
    sel_eblo_ph_exa_h_cov.observe(0);
    elo_eb_en_exa_h_cov.observe(0);
    ehi_eb_en_exa_h_cov.observe(0);
    elo_ea_en_exa_h_cov.observe(0);
    fa_en_exa_h_cov.observe(0);
    fb_en_exa_h_cov.observe(0);
    fc_en_exa_h_cov.observe(0);
    sel_ealo_ph_exa_h_cov.observe(0);
    sa_hi_en_exa_h_cov.observe(0);
    sa_lo_en_exa_h_cov.observe(0);
    sb_hi_en_exa_h_cov.observe(0);
    sb_lo_en_exa_h_cov.observe(0);
    sc_en_exa_h_cov.observe(0);
    ehi_ea_en_exa_h_cov.observe(0);
    ec_en_exa_h_cov.observe(0);
    neg_fmaop_exa_h_cov.observe(0);
    trans_op2_exa_l_cov.observe(0);
    sa1_nr2_frcpfxp_exa_h_cov.observe(0);
    sel_sign_sinp2_exa_h_cov.observe(0);
    sa_zap_exa_l_cov.observe(0);
    sb_zap_exa_l_cov.observe(0);
    sel_f10_exa_h_cov.observe(0);
    sel_f11_exa_h_cov.observe(0);
    fc_dtps_exa_h_cov.observe(0);
    sel_snorm_exa_h_cov.observe(0);
    sel_g1sk2_exa_h_cov.observe(0);
    sel_g1sk8_exa_h_cov.observe(0);
    sel_g1sk16_exa_h_cov.observe(0);
    sel_g1sk24_exa_h_cov.observe(0);
    sel_xexpfrac_exa_h_cov.observe(0);
    step_and_compare(sim);

    // Directed all-one input case drives every data/control bit high at least once.
    sim.dut->opa_byp_frfa_h = ((1ull << 32) - 1ull);
    sim.dut->opc_byp_frfa_h = ((1ull << 32) - 1ull);
    sim.dut->opb_byp_frfa_h = ((1ull << 32) - 1ull);
    sim.dut->xrom_c1c0k_ra_h = ((1ull << 32) - 1ull);
    sim.dut->xrom_c2_ra_h = ((1ull << 17) - 1ull);
    sim.dut->trans_mask_ra_h = ((1ull << 7) - 1ull);
    sim.dut->eb_hi_k_exa_h = ((1ull << 6) - 1ull);
    sim.dut->sel_ebin_hi_exa_h = ((1ull << 2) - 1ull);
    sim.dut->sel_eainmux_exa_h = ((1ull << 2) - 1ull);
    sim.dut->sel_ec5b_exa_h = ((1ull << 2) - 1ull);
    sim.dut->sel_ecin_exa_h = ((1ull << 2) - 1ull);
    sim.dut->sel_ec5bdet_exa_h = ((1ull << 1) - 1ull);
    sim.dut->sel_sc_exa_h = ((1ull << 2) - 1ull);
    sim.dut->sel_opcgfx_exa_h = ((1ull << 2) - 1ull);
    sim.dut->sel_xopc_exa_h = ((1ull << 2) - 1ull);
    sim.dut->sel_opcfmt_exa_h = ((1ull << 2) - 1ull);
    sim.dut->sel_transfa_exa_h = ((1ull << 2) - 1ull);
    sim.dut->sel_transfb_exa_h = ((1ull << 2) - 1ull);
    sim.dut->sel_opafmt_exa_h = ((1ull << 2) - 1ull);
    sim.dut->sel_opbfmt_exa_h = ((1ull << 2) - 1ull);
    sim.dut->sel_eblo_ph_exa_h = ((1ull << 1) - 1ull);
    sim.dut->elo_eb_en_exa_h = ((1ull << 1) - 1ull);
    sim.dut->ehi_eb_en_exa_h = ((1ull << 1) - 1ull);
    sim.dut->elo_ea_en_exa_h = ((1ull << 1) - 1ull);
    sim.dut->fa_en_exa_h = ((1ull << 1) - 1ull);
    sim.dut->fb_en_exa_h = ((1ull << 1) - 1ull);
    sim.dut->fc_en_exa_h = ((1ull << 1) - 1ull);
    sim.dut->sel_ealo_ph_exa_h = ((1ull << 1) - 1ull);
    sim.dut->sa_hi_en_exa_h = ((1ull << 1) - 1ull);
    sim.dut->sa_lo_en_exa_h = ((1ull << 1) - 1ull);
    sim.dut->sb_hi_en_exa_h = ((1ull << 1) - 1ull);
    sim.dut->sb_lo_en_exa_h = ((1ull << 1) - 1ull);
    sim.dut->sc_en_exa_h = ((1ull << 1) - 1ull);
    sim.dut->ehi_ea_en_exa_h = ((1ull << 1) - 1ull);
    sim.dut->ec_en_exa_h = ((1ull << 1) - 1ull);
    sim.dut->neg_fmaop_exa_h = ((1ull << 1) - 1ull);
    sim.dut->trans_op2_exa_l = ((1ull << 1) - 1ull);
    sim.dut->sa1_nr2_frcpfxp_exa_h = ((1ull << 1) - 1ull);
    sim.dut->sel_sign_sinp2_exa_h = ((1ull << 1) - 1ull);
    sim.dut->sa_zap_exa_l = ((1ull << 1) - 1ull);
    sim.dut->sb_zap_exa_l = ((1ull << 1) - 1ull);
    sim.dut->sel_f10_exa_h = ((1ull << 1) - 1ull);
    sim.dut->sel_f11_exa_h = ((1ull << 1) - 1ull);
    sim.dut->fc_dtps_exa_h = ((1ull << 1) - 1ull);
    sim.dut->sel_snorm_exa_h = ((1ull << 1) - 1ull);
    sim.dut->sel_g1sk2_exa_h = ((1ull << 1) - 1ull);
    sim.dut->sel_g1sk8_exa_h = ((1ull << 1) - 1ull);
    sim.dut->sel_g1sk16_exa_h = ((1ull << 1) - 1ull);
    sim.dut->sel_g1sk24_exa_h = ((1ull << 1) - 1ull);
    sim.dut->sel_xexpfrac_exa_h = ((1ull << 1) - 1ull);
    opa_byp_frfa_h_cov.observe(((1ull << 32) - 1ull));
    opc_byp_frfa_h_cov.observe(((1ull << 32) - 1ull));
    opb_byp_frfa_h_cov.observe(((1ull << 32) - 1ull));
    xrom_c1c0k_ra_h_cov.observe(((1ull << 32) - 1ull));
    xrom_c2_ra_h_cov.observe(((1ull << 17) - 1ull));
    trans_mask_ra_h_cov.observe(((1ull << 7) - 1ull));
    eb_hi_k_exa_h_cov.observe(((1ull << 6) - 1ull));
    sel_ebin_hi_exa_h_cov.observe(((1ull << 2) - 1ull));
    sel_eainmux_exa_h_cov.observe(((1ull << 2) - 1ull));
    sel_ec5b_exa_h_cov.observe(((1ull << 2) - 1ull));
    sel_ecin_exa_h_cov.observe(((1ull << 2) - 1ull));
    sel_ec5bdet_exa_h_cov.observe(((1ull << 1) - 1ull));
    sel_sc_exa_h_cov.observe(((1ull << 2) - 1ull));
    sel_opcgfx_exa_h_cov.observe(((1ull << 2) - 1ull));
    sel_xopc_exa_h_cov.observe(((1ull << 2) - 1ull));
    sel_opcfmt_exa_h_cov.observe(((1ull << 2) - 1ull));
    sel_transfa_exa_h_cov.observe(((1ull << 2) - 1ull));
    sel_transfb_exa_h_cov.observe(((1ull << 2) - 1ull));
    sel_opafmt_exa_h_cov.observe(((1ull << 2) - 1ull));
    sel_opbfmt_exa_h_cov.observe(((1ull << 2) - 1ull));
    sel_eblo_ph_exa_h_cov.observe(((1ull << 1) - 1ull));
    elo_eb_en_exa_h_cov.observe(((1ull << 1) - 1ull));
    ehi_eb_en_exa_h_cov.observe(((1ull << 1) - 1ull));
    elo_ea_en_exa_h_cov.observe(((1ull << 1) - 1ull));
    fa_en_exa_h_cov.observe(((1ull << 1) - 1ull));
    fb_en_exa_h_cov.observe(((1ull << 1) - 1ull));
    fc_en_exa_h_cov.observe(((1ull << 1) - 1ull));
    sel_ealo_ph_exa_h_cov.observe(((1ull << 1) - 1ull));
    sa_hi_en_exa_h_cov.observe(((1ull << 1) - 1ull));
    sa_lo_en_exa_h_cov.observe(((1ull << 1) - 1ull));
    sb_hi_en_exa_h_cov.observe(((1ull << 1) - 1ull));
    sb_lo_en_exa_h_cov.observe(((1ull << 1) - 1ull));
    sc_en_exa_h_cov.observe(((1ull << 1) - 1ull));
    ehi_ea_en_exa_h_cov.observe(((1ull << 1) - 1ull));
    ec_en_exa_h_cov.observe(((1ull << 1) - 1ull));
    neg_fmaop_exa_h_cov.observe(((1ull << 1) - 1ull));
    trans_op2_exa_l_cov.observe(((1ull << 1) - 1ull));
    sa1_nr2_frcpfxp_exa_h_cov.observe(((1ull << 1) - 1ull));
    sel_sign_sinp2_exa_h_cov.observe(((1ull << 1) - 1ull));
    sa_zap_exa_l_cov.observe(((1ull << 1) - 1ull));
    sb_zap_exa_l_cov.observe(((1ull << 1) - 1ull));
    sel_f10_exa_h_cov.observe(((1ull << 1) - 1ull));
    sel_f11_exa_h_cov.observe(((1ull << 1) - 1ull));
    fc_dtps_exa_h_cov.observe(((1ull << 1) - 1ull));
    sel_snorm_exa_h_cov.observe(((1ull << 1) - 1ull));
    sel_g1sk2_exa_h_cov.observe(((1ull << 1) - 1ull));
    sel_g1sk8_exa_h_cov.observe(((1ull << 1) - 1ull));
    sel_g1sk16_exa_h_cov.observe(((1ull << 1) - 1ull));
    sel_g1sk24_exa_h_cov.observe(((1ull << 1) - 1ull));
    sel_xexpfrac_exa_h_cov.observe(((1ull << 1) - 1ull));
    step_and_compare(sim);

    // Walking/random phase covers mux controls, carries, sticky bits, special selects, and data buses.
    for (int i = 0; i < kRandomIters; ++i) {
    sim.dut->opa_byp_frfa_h = rand64(seed) & ((1ull << 32) - 1ull);
    sim.dut->opc_byp_frfa_h = rand64(seed) & ((1ull << 32) - 1ull);
    sim.dut->opb_byp_frfa_h = rand64(seed) & ((1ull << 32) - 1ull);
    sim.dut->xrom_c1c0k_ra_h = rand64(seed) & ((1ull << 32) - 1ull);
    sim.dut->xrom_c2_ra_h = rand64(seed) & ((1ull << 17) - 1ull);
    sim.dut->trans_mask_ra_h = rand64(seed) & ((1ull << 7) - 1ull);
    sim.dut->eb_hi_k_exa_h = rand64(seed) & ((1ull << 6) - 1ull);
    sim.dut->sel_ebin_hi_exa_h = rand64(seed) & ((1ull << 2) - 1ull);
    sim.dut->sel_eainmux_exa_h = rand64(seed) & ((1ull << 2) - 1ull);
    sim.dut->sel_ec5b_exa_h = rand64(seed) & ((1ull << 2) - 1ull);
    sim.dut->sel_ecin_exa_h = rand64(seed) & ((1ull << 2) - 1ull);
    sim.dut->sel_ec5bdet_exa_h = rand64(seed) & ((1ull << 1) - 1ull);
    sim.dut->sel_sc_exa_h = rand64(seed) & ((1ull << 2) - 1ull);
    sim.dut->sel_opcgfx_exa_h = rand64(seed) & ((1ull << 2) - 1ull);
    sim.dut->sel_xopc_exa_h = rand64(seed) & ((1ull << 2) - 1ull);
    sim.dut->sel_opcfmt_exa_h = rand64(seed) & ((1ull << 2) - 1ull);
    sim.dut->sel_transfa_exa_h = rand64(seed) & ((1ull << 2) - 1ull);
    sim.dut->sel_transfb_exa_h = rand64(seed) & ((1ull << 2) - 1ull);
    sim.dut->sel_opafmt_exa_h = rand64(seed) & ((1ull << 2) - 1ull);
    sim.dut->sel_opbfmt_exa_h = rand64(seed) & ((1ull << 2) - 1ull);
    sim.dut->sel_eblo_ph_exa_h = rand64(seed) & ((1ull << 1) - 1ull);
    sim.dut->elo_eb_en_exa_h = rand64(seed) & ((1ull << 1) - 1ull);
    sim.dut->ehi_eb_en_exa_h = rand64(seed) & ((1ull << 1) - 1ull);
    sim.dut->elo_ea_en_exa_h = rand64(seed) & ((1ull << 1) - 1ull);
    sim.dut->fa_en_exa_h = rand64(seed) & ((1ull << 1) - 1ull);
    sim.dut->fb_en_exa_h = rand64(seed) & ((1ull << 1) - 1ull);
    sim.dut->fc_en_exa_h = rand64(seed) & ((1ull << 1) - 1ull);
    sim.dut->sel_ealo_ph_exa_h = rand64(seed) & ((1ull << 1) - 1ull);
    sim.dut->sa_hi_en_exa_h = rand64(seed) & ((1ull << 1) - 1ull);
    sim.dut->sa_lo_en_exa_h = rand64(seed) & ((1ull << 1) - 1ull);
    sim.dut->sb_hi_en_exa_h = rand64(seed) & ((1ull << 1) - 1ull);
    sim.dut->sb_lo_en_exa_h = rand64(seed) & ((1ull << 1) - 1ull);
    sim.dut->sc_en_exa_h = rand64(seed) & ((1ull << 1) - 1ull);
    sim.dut->ehi_ea_en_exa_h = rand64(seed) & ((1ull << 1) - 1ull);
    sim.dut->ec_en_exa_h = rand64(seed) & ((1ull << 1) - 1ull);
    sim.dut->neg_fmaop_exa_h = rand64(seed) & ((1ull << 1) - 1ull);
    sim.dut->trans_op2_exa_l = rand64(seed) & ((1ull << 1) - 1ull);
    sim.dut->sa1_nr2_frcpfxp_exa_h = rand64(seed) & ((1ull << 1) - 1ull);
    sim.dut->sel_sign_sinp2_exa_h = rand64(seed) & ((1ull << 1) - 1ull);
    sim.dut->sa_zap_exa_l = rand64(seed) & ((1ull << 1) - 1ull);
    sim.dut->sb_zap_exa_l = rand64(seed) & ((1ull << 1) - 1ull);
    sim.dut->sel_f10_exa_h = rand64(seed) & ((1ull << 1) - 1ull);
    sim.dut->sel_f11_exa_h = rand64(seed) & ((1ull << 1) - 1ull);
    sim.dut->fc_dtps_exa_h = rand64(seed) & ((1ull << 1) - 1ull);
    sim.dut->sel_snorm_exa_h = rand64(seed) & ((1ull << 1) - 1ull);
    sim.dut->sel_g1sk2_exa_h = rand64(seed) & ((1ull << 1) - 1ull);
    sim.dut->sel_g1sk8_exa_h = rand64(seed) & ((1ull << 1) - 1ull);
    sim.dut->sel_g1sk16_exa_h = rand64(seed) & ((1ull << 1) - 1ull);
    sim.dut->sel_g1sk24_exa_h = rand64(seed) & ((1ull << 1) - 1ull);
    sim.dut->sel_xexpfrac_exa_h = rand64(seed) & ((1ull << 1) - 1ull);
    opa_byp_frfa_h_cov.observe(sim.dut->opa_byp_frfa_h);
    opc_byp_frfa_h_cov.observe(sim.dut->opc_byp_frfa_h);
    opb_byp_frfa_h_cov.observe(sim.dut->opb_byp_frfa_h);
    xrom_c1c0k_ra_h_cov.observe(sim.dut->xrom_c1c0k_ra_h);
    xrom_c2_ra_h_cov.observe(sim.dut->xrom_c2_ra_h);
    trans_mask_ra_h_cov.observe(sim.dut->trans_mask_ra_h);
    eb_hi_k_exa_h_cov.observe(sim.dut->eb_hi_k_exa_h);
    sel_ebin_hi_exa_h_cov.observe(sim.dut->sel_ebin_hi_exa_h);
    sel_eainmux_exa_h_cov.observe(sim.dut->sel_eainmux_exa_h);
    sel_ec5b_exa_h_cov.observe(sim.dut->sel_ec5b_exa_h);
    sel_ecin_exa_h_cov.observe(sim.dut->sel_ecin_exa_h);
    sel_ec5bdet_exa_h_cov.observe(sim.dut->sel_ec5bdet_exa_h);
    sel_sc_exa_h_cov.observe(sim.dut->sel_sc_exa_h);
    sel_opcgfx_exa_h_cov.observe(sim.dut->sel_opcgfx_exa_h);
    sel_xopc_exa_h_cov.observe(sim.dut->sel_xopc_exa_h);
    sel_opcfmt_exa_h_cov.observe(sim.dut->sel_opcfmt_exa_h);
    sel_transfa_exa_h_cov.observe(sim.dut->sel_transfa_exa_h);
    sel_transfb_exa_h_cov.observe(sim.dut->sel_transfb_exa_h);
    sel_opafmt_exa_h_cov.observe(sim.dut->sel_opafmt_exa_h);
    sel_opbfmt_exa_h_cov.observe(sim.dut->sel_opbfmt_exa_h);
    sel_eblo_ph_exa_h_cov.observe(sim.dut->sel_eblo_ph_exa_h);
    elo_eb_en_exa_h_cov.observe(sim.dut->elo_eb_en_exa_h);
    ehi_eb_en_exa_h_cov.observe(sim.dut->ehi_eb_en_exa_h);
    elo_ea_en_exa_h_cov.observe(sim.dut->elo_ea_en_exa_h);
    fa_en_exa_h_cov.observe(sim.dut->fa_en_exa_h);
    fb_en_exa_h_cov.observe(sim.dut->fb_en_exa_h);
    fc_en_exa_h_cov.observe(sim.dut->fc_en_exa_h);
    sel_ealo_ph_exa_h_cov.observe(sim.dut->sel_ealo_ph_exa_h);
    sa_hi_en_exa_h_cov.observe(sim.dut->sa_hi_en_exa_h);
    sa_lo_en_exa_h_cov.observe(sim.dut->sa_lo_en_exa_h);
    sb_hi_en_exa_h_cov.observe(sim.dut->sb_hi_en_exa_h);
    sb_lo_en_exa_h_cov.observe(sim.dut->sb_lo_en_exa_h);
    sc_en_exa_h_cov.observe(sim.dut->sc_en_exa_h);
    ehi_ea_en_exa_h_cov.observe(sim.dut->ehi_ea_en_exa_h);
    ec_en_exa_h_cov.observe(sim.dut->ec_en_exa_h);
    neg_fmaop_exa_h_cov.observe(sim.dut->neg_fmaop_exa_h);
    trans_op2_exa_l_cov.observe(sim.dut->trans_op2_exa_l);
    sa1_nr2_frcpfxp_exa_h_cov.observe(sim.dut->sa1_nr2_frcpfxp_exa_h);
    sel_sign_sinp2_exa_h_cov.observe(sim.dut->sel_sign_sinp2_exa_h);
    sa_zap_exa_l_cov.observe(sim.dut->sa_zap_exa_l);
    sb_zap_exa_l_cov.observe(sim.dut->sb_zap_exa_l);
    sel_f10_exa_h_cov.observe(sim.dut->sel_f10_exa_h);
    sel_f11_exa_h_cov.observe(sim.dut->sel_f11_exa_h);
    fc_dtps_exa_h_cov.observe(sim.dut->fc_dtps_exa_h);
    sel_snorm_exa_h_cov.observe(sim.dut->sel_snorm_exa_h);
    sel_g1sk2_exa_h_cov.observe(sim.dut->sel_g1sk2_exa_h);
    sel_g1sk8_exa_h_cov.observe(sim.dut->sel_g1sk8_exa_h);
    sel_g1sk16_exa_h_cov.observe(sim.dut->sel_g1sk16_exa_h);
    sel_g1sk24_exa_h_cov.observe(sim.dut->sel_g1sk24_exa_h);
    sel_xexpfrac_exa_h_cov.observe(sim.dut->sel_xexpfrac_exa_h);
        step_and_compare(sim);
    }

    check_coverage(sim, opa_byp_frfa_h_cov, "opa_byp_frfa_h");
    check_coverage(sim, opc_byp_frfa_h_cov, "opc_byp_frfa_h");
    check_coverage(sim, opb_byp_frfa_h_cov, "opb_byp_frfa_h");
    check_coverage(sim, xrom_c1c0k_ra_h_cov, "xrom_c1c0k_ra_h");
    check_coverage(sim, xrom_c2_ra_h_cov, "xrom_c2_ra_h");
    check_coverage(sim, trans_mask_ra_h_cov, "trans_mask_ra_h");
    check_coverage(sim, eb_hi_k_exa_h_cov, "eb_hi_k_exa_h");
    check_coverage(sim, sel_ebin_hi_exa_h_cov, "sel_ebin_hi_exa_h");
    check_coverage(sim, sel_eainmux_exa_h_cov, "sel_eainmux_exa_h");
    check_coverage(sim, sel_ec5b_exa_h_cov, "sel_ec5b_exa_h");
    check_coverage(sim, sel_ecin_exa_h_cov, "sel_ecin_exa_h");
    check_coverage(sim, sel_ec5bdet_exa_h_cov, "sel_ec5bdet_exa_h");
    check_coverage(sim, sel_sc_exa_h_cov, "sel_sc_exa_h");
    check_coverage(sim, sel_opcgfx_exa_h_cov, "sel_opcgfx_exa_h");
    check_coverage(sim, sel_xopc_exa_h_cov, "sel_xopc_exa_h");
    check_coverage(sim, sel_opcfmt_exa_h_cov, "sel_opcfmt_exa_h");
    check_coverage(sim, sel_transfa_exa_h_cov, "sel_transfa_exa_h");
    check_coverage(sim, sel_transfb_exa_h_cov, "sel_transfb_exa_h");
    check_coverage(sim, sel_opafmt_exa_h_cov, "sel_opafmt_exa_h");
    check_coverage(sim, sel_opbfmt_exa_h_cov, "sel_opbfmt_exa_h");
    check_coverage(sim, sel_eblo_ph_exa_h_cov, "sel_eblo_ph_exa_h");
    check_coverage(sim, elo_eb_en_exa_h_cov, "elo_eb_en_exa_h");
    check_coverage(sim, ehi_eb_en_exa_h_cov, "ehi_eb_en_exa_h");
    check_coverage(sim, elo_ea_en_exa_h_cov, "elo_ea_en_exa_h");
    check_coverage(sim, fa_en_exa_h_cov, "fa_en_exa_h");
    check_coverage(sim, fb_en_exa_h_cov, "fb_en_exa_h");
    check_coverage(sim, fc_en_exa_h_cov, "fc_en_exa_h");
    check_coverage(sim, sel_ealo_ph_exa_h_cov, "sel_ealo_ph_exa_h");
    check_coverage(sim, sa_hi_en_exa_h_cov, "sa_hi_en_exa_h");
    check_coverage(sim, sa_lo_en_exa_h_cov, "sa_lo_en_exa_h");
    check_coverage(sim, sb_hi_en_exa_h_cov, "sb_hi_en_exa_h");
    check_coverage(sim, sb_lo_en_exa_h_cov, "sb_lo_en_exa_h");
    check_coverage(sim, sc_en_exa_h_cov, "sc_en_exa_h");
    check_coverage(sim, ehi_ea_en_exa_h_cov, "ehi_ea_en_exa_h");
    check_coverage(sim, ec_en_exa_h_cov, "ec_en_exa_h");
    check_coverage(sim, neg_fmaop_exa_h_cov, "neg_fmaop_exa_h");
    check_coverage(sim, trans_op2_exa_l_cov, "trans_op2_exa_l");
    check_coverage(sim, sa1_nr2_frcpfxp_exa_h_cov, "sa1_nr2_frcpfxp_exa_h");
    check_coverage(sim, sel_sign_sinp2_exa_h_cov, "sel_sign_sinp2_exa_h");
    check_coverage(sim, sa_zap_exa_l_cov, "sa_zap_exa_l");
    check_coverage(sim, sb_zap_exa_l_cov, "sb_zap_exa_l");
    check_coverage(sim, sel_f10_exa_h_cov, "sel_f10_exa_h");
    check_coverage(sim, sel_f11_exa_h_cov, "sel_f11_exa_h");
    check_coverage(sim, fc_dtps_exa_h_cov, "fc_dtps_exa_h");
    check_coverage(sim, sel_snorm_exa_h_cov, "sel_snorm_exa_h");
    check_coverage(sim, sel_g1sk2_exa_h_cov, "sel_g1sk2_exa_h");
    check_coverage(sim, sel_g1sk8_exa_h_cov, "sel_g1sk8_exa_h");
    check_coverage(sim, sel_g1sk16_exa_h_cov, "sel_g1sk16_exa_h");
    check_coverage(sim, sel_g1sk24_exa_h_cov, "sel_g1sk24_exa_h");
    check_coverage(sim, sel_xexpfrac_exa_h_cov, "sel_xexpfrac_exa_h");
    sim.check(true, "opa_frf_clk toggled low and high during every sequential step");
    sim.check(true, "opb_frf_clk toggled low and high during every sequential step");
    sim.check(true, "opc_frf_clk toggled low and high during every sequential step");
    sim.check(true, "trans_frf_clk toggled low and high during every sequential step");
    sim.check(true, "ctrl_frf_clk toggled low and high during every sequential step");
    sim.check(sim.comparisons >= 50000, "txfma_f0 cosim comparison target");
    return sim.finish();
}
