// Copyright (c) 2026 Ainekko
// SPDX-License-Identifier: Apache-2.0

/* verilator lint_off IMPORTSTAR */
import dft_pkg::*;
import etlink_pkg::*;
import minion_pkg::*;
import minion_dcache_pkg::*;
import vpu_pkg::*;
import vpu_defs_pkg::*;
/* verilator lint_on IMPORTSTAR */

module cosim_txfma_f0_tb
(
  input logic opa_frf_clk,
  input logic opb_frf_clk,
  input logic opc_frf_clk,
  input logic trans_frf_clk,
  input logic ctrl_frf_clk,
  input logic [VPU_DATA_S_SZ-1:0] opa_byp_frfa_h,
  input logic [VPU_DATA_S_SZ-1:0] opc_byp_frfa_h,
  input logic [VPU_DATA_S_SZ-1:0] opb_byp_frfa_h,
  input logic [TRANS_C0_MAX_SIZE-1:0] xrom_c1c0k_ra_h,
  input logic [TRANS_C2_MAX_SIZE-1:0] xrom_c2_ra_h,
  input logic [TRANS_MASK_SIZE-1:0] trans_mask_ra_h,
  input logic [5:0] eb_hi_k_exa_h,
  input logic [1:0] sel_ebin_hi_exa_h,
  input logic [1:0] sel_eainmux_exa_h,
  input logic [1:0] sel_ec5b_exa_h,
  input logic [1:0] sel_ecin_exa_h,
  input logic sel_ec5bdet_exa_h,
  input logic [1:0] sel_sc_exa_h,
  input logic [1:0] sel_opcgfx_exa_h,
  input logic [1:0] sel_xopc_exa_h,
  input logic [1:0] sel_opcfmt_exa_h,
  input logic [1:0] sel_transfa_exa_h,
  input logic [1:0] sel_transfb_exa_h,
  input logic [1:0] sel_opafmt_exa_h,
  input logic [1:0] sel_opbfmt_exa_h,
  input logic sel_eblo_ph_exa_h,
  input logic elo_eb_en_exa_h,
  input logic ehi_eb_en_exa_h,
  input logic elo_ea_en_exa_h,
  input logic fa_en_exa_h,
  input logic fb_en_exa_h,
  input logic fc_en_exa_h,
  input logic sel_ealo_ph_exa_h,
  input logic sa_hi_en_exa_h,
  input logic sa_lo_en_exa_h,
  input logic sb_hi_en_exa_h,
  input logic sb_lo_en_exa_h,
  input logic sc_en_exa_h,
  input logic ehi_ea_en_exa_h,
  input logic ec_en_exa_h,
  input logic neg_fmaop_exa_h,
  input logic trans_op2_exa_l,
  input logic sa1_nr2_frcpfxp_exa_h,
  input logic sel_sign_sinp2_exa_h,
  input logic sa_zap_exa_l,
  input logic sb_zap_exa_l,
  input logic sel_f10_exa_h,
  input logic sel_f11_exa_h,
  input logic fc_dtps_exa_h,
  input logic sel_snorm_exa_h,
  input logic sel_g1sk2_exa_h,
  input logic sel_g1sk8_exa_h,
  input logic sel_g1sk16_exa_h,
  input logic sel_g1sk24_exa_h,
  input logic sel_xexpfrac_exa_h,
  output logic orig_sa_hi_f0a_h,
  output logic new_sa_hi_f0a_h,
  output logic orig_sa_lo_f0a_h,
  output logic new_sa_lo_f0a_h,
  output logic orig_sb_hi_f0a_h,
  output logic new_sb_hi_f0a_h,
  output logic orig_sb_lo_f0a_h,
  output logic new_sb_lo_f0a_h,
  output logic orig_sc_f0a_h,
  output logic new_sc_f0a_h,
  output logic [TXFMA_EXP_PS_SZ-1:0] orig_ea_hi_f0a_h,
  output logic [TXFMA_EXP_PS_SZ-1:0] new_ea_hi_f0a_h,
  output logic [TXFMA_EXP_PH_SZ-1:0] orig_ea_lo_f0a_h,
  output logic [TXFMA_EXP_PH_SZ-1:0] new_ea_lo_f0a_h,
  output logic [TXFMA_EXP_PS_SZ-1:0] orig_eb_hi_f0a_h,
  output logic [TXFMA_EXP_PS_SZ-1:0] new_eb_hi_f0a_h,
  output logic [TXFMA_EXP_PH_SZ-1:0] orig_eb_lo_f0a_h,
  output logic [TXFMA_EXP_PH_SZ-1:0] new_eb_lo_f0a_h,
  output logic [TXFMA_EXP_PS_SZ-1:0] orig_ec_f0a_h,
  output logic [TXFMA_EXP_PS_SZ-1:0] new_ec_f0a_h,
  output logic [VPU_DATA_S_SZ-1:0] orig_fa_f0a_h,
  output logic [VPU_DATA_S_SZ-1:0] new_fa_f0a_h,
  output logic [VPU_DATA_S_SZ-1:0] orig_fb_f0a_h,
  output logic [VPU_DATA_S_SZ-1:0] new_fb_f0a_h,
  output logic [VPU_DATA_S_SZ-1:0] orig_fc_f0a_h,
  output logic [VPU_DATA_S_SZ-1:0] new_fc_f0a_h,
  output logic orig_ea_hi_zero_f0a_l,
  output logic new_ea_hi_zero_f0a_l,
  output logic orig_ea_hi_all1_f0a_h,
  output logic new_ea_hi_all1_f0a_h,
  output logic orig_ea_lo_zero_f0a_l,
  output logic new_ea_lo_zero_f0a_l,
  output logic orig_ea_lo_all1_f0a_h,
  output logic new_ea_lo_all1_f0a_h,
  output logic orig_eb_hi_zero_f0a_l,
  output logic new_eb_hi_zero_f0a_l,
  output logic orig_eb_hi_all1_f0a_h,
  output logic new_eb_hi_all1_f0a_h,
  output logic orig_eb_lo_zero_f0a_l,
  output logic new_eb_lo_zero_f0a_l,
  output logic orig_eb_lo_all1_f0a_h,
  output logic new_eb_lo_all1_f0a_h,
  output logic orig_ec_zero_f0a_l,
  output logic new_ec_zero_f0a_l,
  output logic orig_ec_all1_f0a_h,
  output logic new_ec_all1_f0a_h,
  output logic orig_fcf10_zero_f0a_l,
  output logic new_fcf10_zero_f0a_l,
  output logic orig_eb_eql_127_f0a_h,
  output logic new_eb_eql_127_f0a_h,
  output logic orig_eb_eql_126_f0a_h,
  output logic new_eb_eql_126_f0a_h,
  output logic orig_eb_eql_125_f0a_h,
  output logic new_eb_eql_125_f0a_h,
  output logic orig_fcf11_zero_f0a_l,
  output logic new_fcf11_zero_f0a_l,
  output logic orig_fcps_zero_f0a_h,
  output logic new_fcps_zero_f0a_h,
  output logic orig_fcph_zero_f0a_l,
  output logic new_fcph_zero_f0a_l,
  output logic orig_fcnorm_zero_29_8_f0a_h,
  output logic new_fcnorm_zero_29_8_f0a_h,
  output logic orig_fcnorm16_eq_1_f0a_h,
  output logic new_fcnorm16_eq_1_f0a_h,
  output logic orig_fcnorm8_eq_1_f0a_h,
  output logic new_fcnorm8_eq_1_f0a_h,
  output logic orig_fcn8_one_30_24_f0a_h,
  output logic new_fcn8_one_30_24_f0a_h,
  output logic orig_fcn10_one_30_22_f0a_h,
  output logic new_fcn10_one_30_22_f0a_h,
  output logic orig_fcn16_one_30_16_f0a_h,
  output logic new_fcn16_one_30_16_f0a_h,
  output logic orig_fcn24_one_30_8_f0a_h,
  output logic new_fcn24_one_30_8_f0a_h,
  output logic orig_faps_zero_f0a_l,
  output logic new_faps_zero_f0a_l,
  output logic orig_fbps_zero_f0a_l,
  output logic new_fbps_zero_f0a_l,
  output logic orig_faph_hi_zero_f0a_l,
  output logic new_faph_hi_zero_f0a_l,
  output logic orig_fbph_hi_zero_f0a_l,
  output logic new_fbph_hi_zero_f0a_l,
  output logic orig_faph_lo_zero_f0a_l,
  output logic new_faph_lo_zero_f0a_l,
  output logic orig_fbph_lo_zero_f0a_l,
  output logic new_fbph_lo_zero_f0a_l,
  output logic orig_faph_lo_b0_f0a_h,
  output logic new_faph_lo_b0_f0a_h,
  output logic orig_fbph_lo_b0_f0a_h,
  output logic new_fbph_lo_b0_f0a_h,
  output logic orig_faps_b0_f0a_h,
  output logic new_faps_b0_f0a_h,
  output logic orig_fbps_b0_f0a_h,
  output logic new_fbps_b0_f0a_h,
  output logic orig_fc_31_f0a_h,
  output logic new_fc_31_f0a_h,
  output logic orig_fcnorm_30_f0a_h,
  output logic new_fcnorm_30_f0a_h,
  output logic orig_faph_hi_b0_f0a_h,
  output logic new_faph_hi_b0_f0a_h,
  output logic orig_fbph_hi_b0_f0a_h,
  output logic new_fbph_hi_b0_f0a_h,
  output logic orig_fcph_b0_f0a_h,
  output logic new_fcph_b0_f0a_h,
  output logic orig_fcf11_b0_f0a_h,
  output logic new_fcf11_b0_f0a_h,
  output logic orig_fcf10_b0_f0a_h,
  output logic new_fcf10_b0_f0a_h,
  output logic orig_fcps_b0_f0a_h,
  output logic new_fcps_b0_f0a_h
);

  txfma_f0_orig u_orig (
    .opa_frf_clk (opa_frf_clk),
    .opb_frf_clk (opb_frf_clk),
    .opc_frf_clk (opc_frf_clk),
    .trans_frf_clk (trans_frf_clk),
    .ctrl_frf_clk (ctrl_frf_clk),
    .opa_byp_frfa_h (opa_byp_frfa_h),
    .opc_byp_frfa_h (opc_byp_frfa_h),
    .opb_byp_frfa_h (opb_byp_frfa_h),
    .xrom_c1c0k_ra_h (xrom_c1c0k_ra_h),
    .xrom_c2_ra_h (xrom_c2_ra_h),
    .trans_mask_ra_h (trans_mask_ra_h),
    .eb_hi_k_exa_h (eb_hi_k_exa_h),
    .sel_ebin_hi_exa_h (sel_ebin_hi_exa_h),
    .sel_eainmux_exa_h (sel_eainmux_exa_h),
    .sel_ec5b_exa_h (sel_ec5b_exa_h),
    .sel_ecin_exa_h (sel_ecin_exa_h),
    .sel_ec5bdet_exa_h (sel_ec5bdet_exa_h),
    .sel_sc_exa_h (sel_sc_exa_h),
    .sel_opcgfx_exa_h (sel_opcgfx_exa_h),
    .sel_xopc_exa_h (sel_xopc_exa_h),
    .sel_opcfmt_exa_h (sel_opcfmt_exa_h),
    .sel_transfa_exa_h (sel_transfa_exa_h),
    .sel_transfb_exa_h (sel_transfb_exa_h),
    .sel_opafmt_exa_h (sel_opafmt_exa_h),
    .sel_opbfmt_exa_h (sel_opbfmt_exa_h),
    .sel_eblo_ph_exa_h (sel_eblo_ph_exa_h),
    .elo_eb_en_exa_h (elo_eb_en_exa_h),
    .ehi_eb_en_exa_h (ehi_eb_en_exa_h),
    .elo_ea_en_exa_h (elo_ea_en_exa_h),
    .fa_en_exa_h (fa_en_exa_h),
    .fb_en_exa_h (fb_en_exa_h),
    .fc_en_exa_h (fc_en_exa_h),
    .sel_ealo_ph_exa_h (sel_ealo_ph_exa_h),
    .sa_hi_en_exa_h (sa_hi_en_exa_h),
    .sa_lo_en_exa_h (sa_lo_en_exa_h),
    .sb_hi_en_exa_h (sb_hi_en_exa_h),
    .sb_lo_en_exa_h (sb_lo_en_exa_h),
    .sc_en_exa_h (sc_en_exa_h),
    .ehi_ea_en_exa_h (ehi_ea_en_exa_h),
    .ec_en_exa_h (ec_en_exa_h),
    .neg_fmaop_exa_h (neg_fmaop_exa_h),
    .trans_op2_exa_l (trans_op2_exa_l),
    .sa1_nr2_frcpfxp_exa_h (sa1_nr2_frcpfxp_exa_h),
    .sel_sign_sinp2_exa_h (sel_sign_sinp2_exa_h),
    .sa_zap_exa_l (sa_zap_exa_l),
    .sb_zap_exa_l (sb_zap_exa_l),
    .sel_f10_exa_h (sel_f10_exa_h),
    .sel_f11_exa_h (sel_f11_exa_h),
    .fc_dtps_exa_h (fc_dtps_exa_h),
    .sel_snorm_exa_h (sel_snorm_exa_h),
    .sel_g1sk2_exa_h (sel_g1sk2_exa_h),
    .sel_g1sk8_exa_h (sel_g1sk8_exa_h),
    .sel_g1sk16_exa_h (sel_g1sk16_exa_h),
    .sel_g1sk24_exa_h (sel_g1sk24_exa_h),
    .sel_xexpfrac_exa_h (sel_xexpfrac_exa_h),
    .sa_hi_f0a_h (orig_sa_hi_f0a_h),
    .sa_lo_f0a_h (orig_sa_lo_f0a_h),
    .sb_hi_f0a_h (orig_sb_hi_f0a_h),
    .sb_lo_f0a_h (orig_sb_lo_f0a_h),
    .sc_f0a_h (orig_sc_f0a_h),
    .ea_hi_f0a_h (orig_ea_hi_f0a_h),
    .ea_lo_f0a_h (orig_ea_lo_f0a_h),
    .eb_hi_f0a_h (orig_eb_hi_f0a_h),
    .eb_lo_f0a_h (orig_eb_lo_f0a_h),
    .ec_f0a_h (orig_ec_f0a_h),
    .fa_f0a_h (orig_fa_f0a_h),
    .fb_f0a_h (orig_fb_f0a_h),
    .fc_f0a_h (orig_fc_f0a_h),
    .ea_hi_zero_f0a_l (orig_ea_hi_zero_f0a_l),
    .ea_hi_all1_f0a_h (orig_ea_hi_all1_f0a_h),
    .ea_lo_zero_f0a_l (orig_ea_lo_zero_f0a_l),
    .ea_lo_all1_f0a_h (orig_ea_lo_all1_f0a_h),
    .eb_hi_zero_f0a_l (orig_eb_hi_zero_f0a_l),
    .eb_hi_all1_f0a_h (orig_eb_hi_all1_f0a_h),
    .eb_lo_zero_f0a_l (orig_eb_lo_zero_f0a_l),
    .eb_lo_all1_f0a_h (orig_eb_lo_all1_f0a_h),
    .ec_zero_f0a_l (orig_ec_zero_f0a_l),
    .ec_all1_f0a_h (orig_ec_all1_f0a_h),
    .fcf10_zero_f0a_l (orig_fcf10_zero_f0a_l),
    .eb_eql_127_f0a_h (orig_eb_eql_127_f0a_h),
    .eb_eql_126_f0a_h (orig_eb_eql_126_f0a_h),
    .eb_eql_125_f0a_h (orig_eb_eql_125_f0a_h),
    .fcf11_zero_f0a_l (orig_fcf11_zero_f0a_l),
    .fcps_zero_f0a_h (orig_fcps_zero_f0a_h),
    .fcph_zero_f0a_l (orig_fcph_zero_f0a_l),
    .fcnorm_zero_29_8_f0a_h (orig_fcnorm_zero_29_8_f0a_h),
    .fcnorm16_eq_1_f0a_h (orig_fcnorm16_eq_1_f0a_h),
    .fcnorm8_eq_1_f0a_h (orig_fcnorm8_eq_1_f0a_h),
    .fcn8_one_30_24_f0a_h (orig_fcn8_one_30_24_f0a_h),
    .fcn10_one_30_22_f0a_h (orig_fcn10_one_30_22_f0a_h),
    .fcn16_one_30_16_f0a_h (orig_fcn16_one_30_16_f0a_h),
    .fcn24_one_30_8_f0a_h (orig_fcn24_one_30_8_f0a_h),
    .faps_zero_f0a_l (orig_faps_zero_f0a_l),
    .fbps_zero_f0a_l (orig_fbps_zero_f0a_l),
    .faph_hi_zero_f0a_l (orig_faph_hi_zero_f0a_l),
    .fbph_hi_zero_f0a_l (orig_fbph_hi_zero_f0a_l),
    .faph_lo_zero_f0a_l (orig_faph_lo_zero_f0a_l),
    .fbph_lo_zero_f0a_l (orig_fbph_lo_zero_f0a_l),
    .faph_lo_b0_f0a_h (orig_faph_lo_b0_f0a_h),
    .fbph_lo_b0_f0a_h (orig_fbph_lo_b0_f0a_h),
    .faps_b0_f0a_h (orig_faps_b0_f0a_h),
    .fbps_b0_f0a_h (orig_fbps_b0_f0a_h),
    .fc_31_f0a_h (orig_fc_31_f0a_h),
    .fcnorm_30_f0a_h (orig_fcnorm_30_f0a_h),
    .faph_hi_b0_f0a_h (orig_faph_hi_b0_f0a_h),
    .fbph_hi_b0_f0a_h (orig_fbph_hi_b0_f0a_h),
    .fcph_b0_f0a_h (orig_fcph_b0_f0a_h),
    .fcf11_b0_f0a_h (orig_fcf11_b0_f0a_h),
    .fcf10_b0_f0a_h (orig_fcf10_b0_f0a_h),
    .fcps_b0_f0a_h (orig_fcps_b0_f0a_h)
  );

  txfma_f0 u_new (
    .opa_frf_clk (opa_frf_clk),
    .opb_frf_clk (opb_frf_clk),
    .opc_frf_clk (opc_frf_clk),
    .trans_frf_clk (trans_frf_clk),
    .ctrl_frf_clk (ctrl_frf_clk),
    .opa_byp_frfa_h (opa_byp_frfa_h),
    .opc_byp_frfa_h (opc_byp_frfa_h),
    .opb_byp_frfa_h (opb_byp_frfa_h),
    .xrom_c1c0k_ra_h (xrom_c1c0k_ra_h),
    .xrom_c2_ra_h (xrom_c2_ra_h),
    .trans_mask_ra_h (trans_mask_ra_h),
    .eb_hi_k_exa_h (eb_hi_k_exa_h),
    .sel_ebin_hi_exa_h (sel_ebin_hi_exa_h),
    .sel_eainmux_exa_h (sel_eainmux_exa_h),
    .sel_ec5b_exa_h (sel_ec5b_exa_h),
    .sel_ecin_exa_h (sel_ecin_exa_h),
    .sel_ec5bdet_exa_h (sel_ec5bdet_exa_h),
    .sel_sc_exa_h (sel_sc_exa_h),
    .sel_opcgfx_exa_h (sel_opcgfx_exa_h),
    .sel_xopc_exa_h (sel_xopc_exa_h),
    .sel_opcfmt_exa_h (sel_opcfmt_exa_h),
    .sel_transfa_exa_h (sel_transfa_exa_h),
    .sel_transfb_exa_h (sel_transfb_exa_h),
    .sel_opafmt_exa_h (sel_opafmt_exa_h),
    .sel_opbfmt_exa_h (sel_opbfmt_exa_h),
    .sel_eblo_ph_exa_h (sel_eblo_ph_exa_h),
    .elo_eb_en_exa_h (elo_eb_en_exa_h),
    .ehi_eb_en_exa_h (ehi_eb_en_exa_h),
    .elo_ea_en_exa_h (elo_ea_en_exa_h),
    .fa_en_exa_h (fa_en_exa_h),
    .fb_en_exa_h (fb_en_exa_h),
    .fc_en_exa_h (fc_en_exa_h),
    .sel_ealo_ph_exa_h (sel_ealo_ph_exa_h),
    .sa_hi_en_exa_h (sa_hi_en_exa_h),
    .sa_lo_en_exa_h (sa_lo_en_exa_h),
    .sb_hi_en_exa_h (sb_hi_en_exa_h),
    .sb_lo_en_exa_h (sb_lo_en_exa_h),
    .sc_en_exa_h (sc_en_exa_h),
    .ehi_ea_en_exa_h (ehi_ea_en_exa_h),
    .ec_en_exa_h (ec_en_exa_h),
    .neg_fmaop_exa_h (neg_fmaop_exa_h),
    .trans_op2_exa_l (trans_op2_exa_l),
    .sa1_nr2_frcpfxp_exa_h (sa1_nr2_frcpfxp_exa_h),
    .sel_sign_sinp2_exa_h (sel_sign_sinp2_exa_h),
    .sa_zap_exa_l (sa_zap_exa_l),
    .sb_zap_exa_l (sb_zap_exa_l),
    .sel_f10_exa_h (sel_f10_exa_h),
    .sel_f11_exa_h (sel_f11_exa_h),
    .fc_dtps_exa_h (fc_dtps_exa_h),
    .sel_snorm_exa_h (sel_snorm_exa_h),
    .sel_g1sk2_exa_h (sel_g1sk2_exa_h),
    .sel_g1sk8_exa_h (sel_g1sk8_exa_h),
    .sel_g1sk16_exa_h (sel_g1sk16_exa_h),
    .sel_g1sk24_exa_h (sel_g1sk24_exa_h),
    .sel_xexpfrac_exa_h (sel_xexpfrac_exa_h),
    .sa_hi_f0a_h (new_sa_hi_f0a_h),
    .sa_lo_f0a_h (new_sa_lo_f0a_h),
    .sb_hi_f0a_h (new_sb_hi_f0a_h),
    .sb_lo_f0a_h (new_sb_lo_f0a_h),
    .sc_f0a_h (new_sc_f0a_h),
    .ea_hi_f0a_h (new_ea_hi_f0a_h),
    .ea_lo_f0a_h (new_ea_lo_f0a_h),
    .eb_hi_f0a_h (new_eb_hi_f0a_h),
    .eb_lo_f0a_h (new_eb_lo_f0a_h),
    .ec_f0a_h (new_ec_f0a_h),
    .fa_f0a_h (new_fa_f0a_h),
    .fb_f0a_h (new_fb_f0a_h),
    .fc_f0a_h (new_fc_f0a_h),
    .ea_hi_zero_f0a_l (new_ea_hi_zero_f0a_l),
    .ea_hi_all1_f0a_h (new_ea_hi_all1_f0a_h),
    .ea_lo_zero_f0a_l (new_ea_lo_zero_f0a_l),
    .ea_lo_all1_f0a_h (new_ea_lo_all1_f0a_h),
    .eb_hi_zero_f0a_l (new_eb_hi_zero_f0a_l),
    .eb_hi_all1_f0a_h (new_eb_hi_all1_f0a_h),
    .eb_lo_zero_f0a_l (new_eb_lo_zero_f0a_l),
    .eb_lo_all1_f0a_h (new_eb_lo_all1_f0a_h),
    .ec_zero_f0a_l (new_ec_zero_f0a_l),
    .ec_all1_f0a_h (new_ec_all1_f0a_h),
    .fcf10_zero_f0a_l (new_fcf10_zero_f0a_l),
    .eb_eql_127_f0a_h (new_eb_eql_127_f0a_h),
    .eb_eql_126_f0a_h (new_eb_eql_126_f0a_h),
    .eb_eql_125_f0a_h (new_eb_eql_125_f0a_h),
    .fcf11_zero_f0a_l (new_fcf11_zero_f0a_l),
    .fcps_zero_f0a_h (new_fcps_zero_f0a_h),
    .fcph_zero_f0a_l (new_fcph_zero_f0a_l),
    .fcnorm_zero_29_8_f0a_h (new_fcnorm_zero_29_8_f0a_h),
    .fcnorm16_eq_1_f0a_h (new_fcnorm16_eq_1_f0a_h),
    .fcnorm8_eq_1_f0a_h (new_fcnorm8_eq_1_f0a_h),
    .fcn8_one_30_24_f0a_h (new_fcn8_one_30_24_f0a_h),
    .fcn10_one_30_22_f0a_h (new_fcn10_one_30_22_f0a_h),
    .fcn16_one_30_16_f0a_h (new_fcn16_one_30_16_f0a_h),
    .fcn24_one_30_8_f0a_h (new_fcn24_one_30_8_f0a_h),
    .faps_zero_f0a_l (new_faps_zero_f0a_l),
    .fbps_zero_f0a_l (new_fbps_zero_f0a_l),
    .faph_hi_zero_f0a_l (new_faph_hi_zero_f0a_l),
    .fbph_hi_zero_f0a_l (new_fbph_hi_zero_f0a_l),
    .faph_lo_zero_f0a_l (new_faph_lo_zero_f0a_l),
    .fbph_lo_zero_f0a_l (new_fbph_lo_zero_f0a_l),
    .faph_lo_b0_f0a_h (new_faph_lo_b0_f0a_h),
    .fbph_lo_b0_f0a_h (new_fbph_lo_b0_f0a_h),
    .faps_b0_f0a_h (new_faps_b0_f0a_h),
    .fbps_b0_f0a_h (new_fbps_b0_f0a_h),
    .fc_31_f0a_h (new_fc_31_f0a_h),
    .fcnorm_30_f0a_h (new_fcnorm_30_f0a_h),
    .faph_hi_b0_f0a_h (new_faph_hi_b0_f0a_h),
    .fbph_hi_b0_f0a_h (new_fbph_hi_b0_f0a_h),
    .fcph_b0_f0a_h (new_fcph_b0_f0a_h),
    .fcf11_b0_f0a_h (new_fcf11_b0_f0a_h),
    .fcf10_b0_f0a_h (new_fcf10_b0_f0a_h),
    .fcps_b0_f0a_h (new_fcps_b0_f0a_h)
  );

endmodule : cosim_txfma_f0_tb
