// Copyright (c) 2026 Ainekko
// SPDX-License-Identifier: Apache-2.0

module cosim_txfma_c6_tb import vpu_defs_pkg::*;
(
  input logic [VPU_DTYPE_SZ-1:0] op_dtype_f6a_h,
  input logic [VPU_FCMD_SZ-1:0] cmd_f6a_h,
  input logic classify_zero_f6a_h,
  input logic [TXFMA_SIGS_SZ-1:0] sigs_f6a_h,
  input logic [VPU_FLAGS_SZ-1:0] in_flags_f6a_h,
  input logic [TXFMA_RM_SZ-1:0] rm_f6a_h,
  input logic rmode_f6a_h,
  input logic eff_sub1_f6a_h,
  input logic exp_res_zero_f6a_h,
  input logic s_res_f6a_h,
  input logic flags_en_f6a_h,
  input logic ediff1_lt_31_f6a_h,
  input logic rc_ph_f6a_h,
  input logic rc_ps_f6a_h,
  input logic rc_int32_f6a_h,
  input logic ph_stky2l_f6a_h,
  input logic ps_stky2l_f6a_h,
  input logic int32_stky2l_f6a_h,
  input logic fround_stky2l_f6a_h,
  input logic minmax_op_f6a_h,
  input logic comp_op_f6a_h,
  input logic comp_op_true_f6a_h,
  input logic spec_res_en_f6a_h,
  input logic norm_f32_ovf_f6a_h,
  input logic norm_one_out_f6a_h,
  input logic ec_zero_f6a_h,
  input logic res_inf_f6a_h,
  input logic res_neg_inf_f6a_h,
  input logic res_qnan_f6a_h,
  input logic res_snan_f6a_h,
  input logic pot_ovf_ps_f6a_h,
  input logic def_ovf_ps_f6a_h,
  input logic pot_unf_ps_f6a_h,
  input logic def_unf_ps_f6a_h,
  input logic pot_ovf_ph_f6a_h,
  input logic def_ovf_ph_f6a_h,
  input logic pot_unf_ph_f6a_h,
  input logic def_unf_ph_f6a_h,
  input logic cvt_fui_pos_ovf_f6a_h,
  input logic cvt_fi_pos_ovf_f6a_h,
  input logic cvt_fi_neg_ovf_f6a_h,
  input logic cvt_fi_min_neg_f6a_h,
  input logic res_unorm_one_f6a_h,
  input logic res_snorm_one_f6a_h,
  input logic cmp_invalid_f6a_h,
  input logic res_pos_int_nan_f6a_h,
  input logic res_neg_int_nan_f6a_h,
  input logic res_uint_nan_f6a_h,
  input logic res_zero_f6a_h,
  input logic res_one_f6a_h,
  input logic a_inf_f6a_h,
  input logic frac_zero_f6a_h,
  input logic rnd_l_ph_f6a_h,
  input logic rnd_r_ph_f6a_h,
  input logic rnd_l_ps_f6a_h,
  input logic rnd_r_ps_f6a_h,
  input logic int_res_l_bit_f6a_h,
  input logic ph_allone2r_f6a_h,
  input logic ph_allone2l_f6a_h,
  input logic ps_allone2r_f6a_h,
  input logic ps_allone2l_f6a_h,
  output logic orig_sel_gmaxu24_f6a_h,
  output logic new_sel_gmaxu24_f6a_h,
  output logic orig_sel_gmaxu16_f6a_h,
  output logic new_sel_gmaxu16_f6a_h,
  output logic orig_sel_gmaxs16_f6a_h,
  output logic new_sel_gmaxs16_f6a_h,
  output logic orig_sel_gmins16_f6a_h,
  output logic new_sel_gmins16_f6a_h,
  output logic orig_sel_gmaxs8_f6a_h,
  output logic new_sel_gmaxs8_f6a_h,
  output logic orig_sel_gmaxu2_f6a_h,
  output logic new_sel_gmaxu2_f6a_h,
  output logic orig_sel_gmins8_f6a_h,
  output logic new_sel_gmins8_f6a_h,
  output logic orig_sel_gmaxu8_f6a_h,
  output logic new_sel_gmaxu8_f6a_h,
  output logic orig_sel_gfxmax_f6a_h,
  output logic new_sel_gfxmax_f6a_h,
  output logic orig_sel_psexc_sr_f6a_h,
  output logic new_sel_psexc_sr_f6a_h,
  output logic orig_sel_bit31_one_f6a_h,
  output logic new_sel_bit31_one_f6a_h,
  output logic orig_sel_b30to0_ones_f6a_h,
  output logic new_sel_b30to0_ones_f6a_h,
  output logic orig_sel_zerores_f6a_h,
  output logic new_sel_zerores_f6a_h,
  output logic orig_sel_ps_unf_f6a_h,
  output logic new_sel_ps_unf_f6a_h,
  output logic orig_sel_ps_normone_f6a_h,
  output logic new_sel_ps_normone_f6a_h,
  output logic orig_sel_ps_inf_f6a_h,
  output logic new_sel_ps_inf_f6a_h,
  output logic orig_sel_ps_cqn_f6a_h,
  output logic new_sel_ps_cqn_f6a_h,
  output logic orig_sel_ps_large_f6a_h,
  output logic new_sel_ps_large_f6a_h,
  output logic orig_sel_phsp_f6a_h,
  output logic new_sel_phsp_f6a_h,
  output logic orig_sel_phhi_sr_f6a_h,
  output logic new_sel_phhi_sr_f6a_h,
  output logic orig_sel_phhi_large_f6a_h,
  output logic new_sel_phhi_large_f6a_h,
  output logic orig_sel_phhi_unf_f6a_h,
  output logic new_sel_phhi_unf_f6a_h,
  output logic orig_sel_phhi_infres_f6a_h,
  output logic new_sel_phhi_infres_f6a_h,
  output logic orig_sel_f11large_f6a_h,
  output logic new_sel_f11large_f6a_h,
  output logic orig_sel_f10large_f6a_h,
  output logic new_sel_f10large_f6a_h,
  output logic orig_sel_f11inf_f6a_h,
  output logic new_sel_f11inf_f6a_h,
  output logic orig_sel_f10cqnan_f6a_h,
  output logic new_sel_f10cqnan_f6a_h,
  output logic orig_sel_f11sp_f6a_h,
  output logic new_sel_f11sp_f6a_h,
  output logic orig_sel_f10sp_f6a_h,
  output logic new_sel_f10sp_f6a_h,
  output logic orig_ps_rndovf_f6a_h,
  output logic new_ps_rndovf_f6a_h,
  output logic orig_ph_rndovf_f6a_h,
  output logic new_ph_rndovf_f6a_h,
  output logic orig_sel_set_bit0_one_f6a_h,
  output logic new_sel_set_bit0_one_f6a_h,
  output logic orig_effsub1_set_sign1_f6a_h,
  output logic new_effsub1_set_sign1_f6a_h,
  output logic orig_normmask1_f6a_h,
  output logic new_normmask1_f6a_h,
  output logic orig_normmask2_f6a_h,
  output logic new_normmask2_f6a_h,
  output logic orig_sel_classify_out_f6a_h,
  output logic new_sel_classify_out_f6a_h,
  output logic orig_sel_nr1_frcpres_f6a_h,
  output logic new_sel_nr1_frcpres_f6a_h,
  output logic orig_trans_sinp2m_f6a_h,
  output logic new_trans_sinp2m_f6a_h,
  output logic orig_f10f11mux_sel_f6a_h,
  output logic new_f10f11mux_sel_f6a_h,
  output logic orig_rrmux16l_sel_f6a_l,
  output logic new_rrmux16l_sel_f6a_l,
  output logic [1:0] orig_rrmux32_sel_f6a_h,
  output logic [1:0] new_rrmux32_sel_f6a_h,
  output logic [1:0] orig_sel_excreshi_f6a_h,
  output logic [1:0] new_sel_excreshi_f6a_h,
  output logic [1:0] orig_sel_excreslo_f6a_h,
  output logic [1:0] new_sel_excreslo_f6a_h,
  output logic [1:0] orig_sel_fmares_hi_f6a_h,
  output logic [1:0] new_sel_fmares_hi_f6a_h,
  output logic [1:0] orig_sel_fmares_lo_f6a_h,
  output logic [1:0] new_sel_fmares_lo_f6a_h,
  output logic [VPU_FLAGS_SZ-1:0] orig_fma_flags_f6a_h,
  output logic [VPU_FLAGS_SZ-1:0] new_fma_flags_f6a_h
);

  txfma_c6_orig u_orig (
    .op_dtype_f6a_h (op_dtype_f6a_h),
    .cmd_f6a_h (cmd_f6a_h),
    .classify_zero_f6a_h (classify_zero_f6a_h),
    .sigs_f6a_h (sigs_f6a_h),
    .in_flags_f6a_h (in_flags_f6a_h),
    .rm_f6a_h (rm_f6a_h),
    .rmode_f6a_h (rmode_f6a_h),
    .eff_sub1_f6a_h (eff_sub1_f6a_h),
    .exp_res_zero_f6a_h (exp_res_zero_f6a_h),
    .s_res_f6a_h (s_res_f6a_h),
    .flags_en_f6a_h (flags_en_f6a_h),
    .ediff1_lt_31_f6a_h (ediff1_lt_31_f6a_h),
    .rc_ph_f6a_h (rc_ph_f6a_h),
    .rc_ps_f6a_h (rc_ps_f6a_h),
    .rc_int32_f6a_h (rc_int32_f6a_h),
    .ph_stky2l_f6a_h (ph_stky2l_f6a_h),
    .ps_stky2l_f6a_h (ps_stky2l_f6a_h),
    .int32_stky2l_f6a_h (int32_stky2l_f6a_h),
    .fround_stky2l_f6a_h (fround_stky2l_f6a_h),
    .minmax_op_f6a_h (minmax_op_f6a_h),
    .comp_op_f6a_h (comp_op_f6a_h),
    .comp_op_true_f6a_h (comp_op_true_f6a_h),
    .spec_res_en_f6a_h (spec_res_en_f6a_h),
    .norm_f32_ovf_f6a_h (norm_f32_ovf_f6a_h),
    .norm_one_out_f6a_h (norm_one_out_f6a_h),
    .ec_zero_f6a_h (ec_zero_f6a_h),
    .res_inf_f6a_h (res_inf_f6a_h),
    .res_neg_inf_f6a_h (res_neg_inf_f6a_h),
    .res_qnan_f6a_h (res_qnan_f6a_h),
    .res_snan_f6a_h (res_snan_f6a_h),
    .pot_ovf_ps_f6a_h (pot_ovf_ps_f6a_h),
    .def_ovf_ps_f6a_h (def_ovf_ps_f6a_h),
    .pot_unf_ps_f6a_h (pot_unf_ps_f6a_h),
    .def_unf_ps_f6a_h (def_unf_ps_f6a_h),
    .pot_ovf_ph_f6a_h (pot_ovf_ph_f6a_h),
    .def_ovf_ph_f6a_h (def_ovf_ph_f6a_h),
    .pot_unf_ph_f6a_h (pot_unf_ph_f6a_h),
    .def_unf_ph_f6a_h (def_unf_ph_f6a_h),
    .cvt_fui_pos_ovf_f6a_h (cvt_fui_pos_ovf_f6a_h),
    .cvt_fi_pos_ovf_f6a_h (cvt_fi_pos_ovf_f6a_h),
    .cvt_fi_neg_ovf_f6a_h (cvt_fi_neg_ovf_f6a_h),
    .cvt_fi_min_neg_f6a_h (cvt_fi_min_neg_f6a_h),
    .res_unorm_one_f6a_h (res_unorm_one_f6a_h),
    .res_snorm_one_f6a_h (res_snorm_one_f6a_h),
    .cmp_invalid_f6a_h (cmp_invalid_f6a_h),
    .res_pos_int_nan_f6a_h (res_pos_int_nan_f6a_h),
    .res_neg_int_nan_f6a_h (res_neg_int_nan_f6a_h),
    .res_uint_nan_f6a_h (res_uint_nan_f6a_h),
    .res_zero_f6a_h (res_zero_f6a_h),
    .res_one_f6a_h (res_one_f6a_h),
    .a_inf_f6a_h (a_inf_f6a_h),
    .frac_zero_f6a_h (frac_zero_f6a_h),
    .rnd_l_ph_f6a_h (rnd_l_ph_f6a_h),
    .rnd_r_ph_f6a_h (rnd_r_ph_f6a_h),
    .rnd_l_ps_f6a_h (rnd_l_ps_f6a_h),
    .rnd_r_ps_f6a_h (rnd_r_ps_f6a_h),
    .int_res_l_bit_f6a_h (int_res_l_bit_f6a_h),
    .ph_allone2r_f6a_h (ph_allone2r_f6a_h),
    .ph_allone2l_f6a_h (ph_allone2l_f6a_h),
    .ps_allone2r_f6a_h (ps_allone2r_f6a_h),
    .ps_allone2l_f6a_h (ps_allone2l_f6a_h),
    .sel_gmaxu24_f6a_h (orig_sel_gmaxu24_f6a_h),
    .sel_gmaxu16_f6a_h (orig_sel_gmaxu16_f6a_h),
    .sel_gmaxs16_f6a_h (orig_sel_gmaxs16_f6a_h),
    .sel_gmins16_f6a_h (orig_sel_gmins16_f6a_h),
    .sel_gmaxs8_f6a_h (orig_sel_gmaxs8_f6a_h),
    .sel_gmaxu2_f6a_h (orig_sel_gmaxu2_f6a_h),
    .sel_gmins8_f6a_h (orig_sel_gmins8_f6a_h),
    .sel_gmaxu8_f6a_h (orig_sel_gmaxu8_f6a_h),
    .sel_gfxmax_f6a_h (orig_sel_gfxmax_f6a_h),
    .sel_psexc_sr_f6a_h (orig_sel_psexc_sr_f6a_h),
    .sel_bit31_one_f6a_h (orig_sel_bit31_one_f6a_h),
    .sel_b30to0_ones_f6a_h (orig_sel_b30to0_ones_f6a_h),
    .sel_zerores_f6a_h (orig_sel_zerores_f6a_h),
    .sel_ps_unf_f6a_h (orig_sel_ps_unf_f6a_h),
    .sel_ps_normone_f6a_h (orig_sel_ps_normone_f6a_h),
    .sel_ps_inf_f6a_h (orig_sel_ps_inf_f6a_h),
    .sel_ps_cqn_f6a_h (orig_sel_ps_cqn_f6a_h),
    .sel_ps_large_f6a_h (orig_sel_ps_large_f6a_h),
    .sel_phsp_f6a_h (orig_sel_phsp_f6a_h),
    .sel_phhi_sr_f6a_h (orig_sel_phhi_sr_f6a_h),
    .sel_phhi_large_f6a_h (orig_sel_phhi_large_f6a_h),
    .sel_phhi_unf_f6a_h (orig_sel_phhi_unf_f6a_h),
    .sel_phhi_infres_f6a_h (orig_sel_phhi_infres_f6a_h),
    .sel_f11large_f6a_h (orig_sel_f11large_f6a_h),
    .sel_f10large_f6a_h (orig_sel_f10large_f6a_h),
    .sel_f11inf_f6a_h (orig_sel_f11inf_f6a_h),
    .sel_f10cqnan_f6a_h (orig_sel_f10cqnan_f6a_h),
    .sel_f11sp_f6a_h (orig_sel_f11sp_f6a_h),
    .sel_f10sp_f6a_h (orig_sel_f10sp_f6a_h),
    .ps_rndovf_f6a_h (orig_ps_rndovf_f6a_h),
    .ph_rndovf_f6a_h (orig_ph_rndovf_f6a_h),
    .sel_set_bit0_one_f6a_h (orig_sel_set_bit0_one_f6a_h),
    .effsub1_set_sign1_f6a_h (orig_effsub1_set_sign1_f6a_h),
    .normmask1_f6a_h (orig_normmask1_f6a_h),
    .normmask2_f6a_h (orig_normmask2_f6a_h),
    .sel_classify_out_f6a_h (orig_sel_classify_out_f6a_h),
    .sel_nr1_frcpres_f6a_h (orig_sel_nr1_frcpres_f6a_h),
    .trans_sinp2m_f6a_h (orig_trans_sinp2m_f6a_h),
    .f10f11mux_sel_f6a_h (orig_f10f11mux_sel_f6a_h),
    .rrmux16l_sel_f6a_l (orig_rrmux16l_sel_f6a_l),
    .rrmux32_sel_f6a_h (orig_rrmux32_sel_f6a_h),
    .sel_excreshi_f6a_h (orig_sel_excreshi_f6a_h),
    .sel_excreslo_f6a_h (orig_sel_excreslo_f6a_h),
    .sel_fmares_hi_f6a_h (orig_sel_fmares_hi_f6a_h),
    .sel_fmares_lo_f6a_h (orig_sel_fmares_lo_f6a_h),
    .fma_flags_f6a_h (orig_fma_flags_f6a_h)
  );

  txfma_c6 u_new (
    .op_dtype_f6a_h (op_dtype_f6a_h),
    .cmd_f6a_h (cmd_f6a_h),
    .classify_zero_f6a_h (classify_zero_f6a_h),
    .sigs_f6a_h (sigs_f6a_h),
    .in_flags_f6a_h (in_flags_f6a_h),
    .rm_f6a_h (rm_f6a_h),
    .rmode_f6a_h (rmode_f6a_h),
    .eff_sub1_f6a_h (eff_sub1_f6a_h),
    .exp_res_zero_f6a_h (exp_res_zero_f6a_h),
    .s_res_f6a_h (s_res_f6a_h),
    .flags_en_f6a_h (flags_en_f6a_h),
    .ediff1_lt_31_f6a_h (ediff1_lt_31_f6a_h),
    .rc_ph_f6a_h (rc_ph_f6a_h),
    .rc_ps_f6a_h (rc_ps_f6a_h),
    .rc_int32_f6a_h (rc_int32_f6a_h),
    .ph_stky2l_f6a_h (ph_stky2l_f6a_h),
    .ps_stky2l_f6a_h (ps_stky2l_f6a_h),
    .int32_stky2l_f6a_h (int32_stky2l_f6a_h),
    .fround_stky2l_f6a_h (fround_stky2l_f6a_h),
    .minmax_op_f6a_h (minmax_op_f6a_h),
    .comp_op_f6a_h (comp_op_f6a_h),
    .comp_op_true_f6a_h (comp_op_true_f6a_h),
    .spec_res_en_f6a_h (spec_res_en_f6a_h),
    .norm_f32_ovf_f6a_h (norm_f32_ovf_f6a_h),
    .norm_one_out_f6a_h (norm_one_out_f6a_h),
    .ec_zero_f6a_h (ec_zero_f6a_h),
    .res_inf_f6a_h (res_inf_f6a_h),
    .res_neg_inf_f6a_h (res_neg_inf_f6a_h),
    .res_qnan_f6a_h (res_qnan_f6a_h),
    .res_snan_f6a_h (res_snan_f6a_h),
    .pot_ovf_ps_f6a_h (pot_ovf_ps_f6a_h),
    .def_ovf_ps_f6a_h (def_ovf_ps_f6a_h),
    .pot_unf_ps_f6a_h (pot_unf_ps_f6a_h),
    .def_unf_ps_f6a_h (def_unf_ps_f6a_h),
    .pot_ovf_ph_f6a_h (pot_ovf_ph_f6a_h),
    .def_ovf_ph_f6a_h (def_ovf_ph_f6a_h),
    .pot_unf_ph_f6a_h (pot_unf_ph_f6a_h),
    .def_unf_ph_f6a_h (def_unf_ph_f6a_h),
    .cvt_fui_pos_ovf_f6a_h (cvt_fui_pos_ovf_f6a_h),
    .cvt_fi_pos_ovf_f6a_h (cvt_fi_pos_ovf_f6a_h),
    .cvt_fi_neg_ovf_f6a_h (cvt_fi_neg_ovf_f6a_h),
    .cvt_fi_min_neg_f6a_h (cvt_fi_min_neg_f6a_h),
    .res_unorm_one_f6a_h (res_unorm_one_f6a_h),
    .res_snorm_one_f6a_h (res_snorm_one_f6a_h),
    .cmp_invalid_f6a_h (cmp_invalid_f6a_h),
    .res_pos_int_nan_f6a_h (res_pos_int_nan_f6a_h),
    .res_neg_int_nan_f6a_h (res_neg_int_nan_f6a_h),
    .res_uint_nan_f6a_h (res_uint_nan_f6a_h),
    .res_zero_f6a_h (res_zero_f6a_h),
    .res_one_f6a_h (res_one_f6a_h),
    .a_inf_f6a_h (a_inf_f6a_h),
    .frac_zero_f6a_h (frac_zero_f6a_h),
    .rnd_l_ph_f6a_h (rnd_l_ph_f6a_h),
    .rnd_r_ph_f6a_h (rnd_r_ph_f6a_h),
    .rnd_l_ps_f6a_h (rnd_l_ps_f6a_h),
    .rnd_r_ps_f6a_h (rnd_r_ps_f6a_h),
    .int_res_l_bit_f6a_h (int_res_l_bit_f6a_h),
    .ph_allone2r_f6a_h (ph_allone2r_f6a_h),
    .ph_allone2l_f6a_h (ph_allone2l_f6a_h),
    .ps_allone2r_f6a_h (ps_allone2r_f6a_h),
    .ps_allone2l_f6a_h (ps_allone2l_f6a_h),
    .sel_gmaxu24_f6a_h (new_sel_gmaxu24_f6a_h),
    .sel_gmaxu16_f6a_h (new_sel_gmaxu16_f6a_h),
    .sel_gmaxs16_f6a_h (new_sel_gmaxs16_f6a_h),
    .sel_gmins16_f6a_h (new_sel_gmins16_f6a_h),
    .sel_gmaxs8_f6a_h (new_sel_gmaxs8_f6a_h),
    .sel_gmaxu2_f6a_h (new_sel_gmaxu2_f6a_h),
    .sel_gmins8_f6a_h (new_sel_gmins8_f6a_h),
    .sel_gmaxu8_f6a_h (new_sel_gmaxu8_f6a_h),
    .sel_gfxmax_f6a_h (new_sel_gfxmax_f6a_h),
    .sel_psexc_sr_f6a_h (new_sel_psexc_sr_f6a_h),
    .sel_bit31_one_f6a_h (new_sel_bit31_one_f6a_h),
    .sel_b30to0_ones_f6a_h (new_sel_b30to0_ones_f6a_h),
    .sel_zerores_f6a_h (new_sel_zerores_f6a_h),
    .sel_ps_unf_f6a_h (new_sel_ps_unf_f6a_h),
    .sel_ps_normone_f6a_h (new_sel_ps_normone_f6a_h),
    .sel_ps_inf_f6a_h (new_sel_ps_inf_f6a_h),
    .sel_ps_cqn_f6a_h (new_sel_ps_cqn_f6a_h),
    .sel_ps_large_f6a_h (new_sel_ps_large_f6a_h),
    .sel_phsp_f6a_h (new_sel_phsp_f6a_h),
    .sel_phhi_sr_f6a_h (new_sel_phhi_sr_f6a_h),
    .sel_phhi_large_f6a_h (new_sel_phhi_large_f6a_h),
    .sel_phhi_unf_f6a_h (new_sel_phhi_unf_f6a_h),
    .sel_phhi_infres_f6a_h (new_sel_phhi_infres_f6a_h),
    .sel_f11large_f6a_h (new_sel_f11large_f6a_h),
    .sel_f10large_f6a_h (new_sel_f10large_f6a_h),
    .sel_f11inf_f6a_h (new_sel_f11inf_f6a_h),
    .sel_f10cqnan_f6a_h (new_sel_f10cqnan_f6a_h),
    .sel_f11sp_f6a_h (new_sel_f11sp_f6a_h),
    .sel_f10sp_f6a_h (new_sel_f10sp_f6a_h),
    .ps_rndovf_f6a_h (new_ps_rndovf_f6a_h),
    .ph_rndovf_f6a_h (new_ph_rndovf_f6a_h),
    .sel_set_bit0_one_f6a_h (new_sel_set_bit0_one_f6a_h),
    .effsub1_set_sign1_f6a_h (new_effsub1_set_sign1_f6a_h),
    .normmask1_f6a_h (new_normmask1_f6a_h),
    .normmask2_f6a_h (new_normmask2_f6a_h),
    .sel_classify_out_f6a_h (new_sel_classify_out_f6a_h),
    .sel_nr1_frcpres_f6a_h (new_sel_nr1_frcpres_f6a_h),
    .trans_sinp2m_f6a_h (new_trans_sinp2m_f6a_h),
    .f10f11mux_sel_f6a_h (new_f10f11mux_sel_f6a_h),
    .rrmux16l_sel_f6a_l (new_rrmux16l_sel_f6a_l),
    .rrmux32_sel_f6a_h (new_rrmux32_sel_f6a_h),
    .sel_excreshi_f6a_h (new_sel_excreshi_f6a_h),
    .sel_excreslo_f6a_h (new_sel_excreslo_f6a_h),
    .sel_fmares_hi_f6a_h (new_sel_fmares_hi_f6a_h),
    .sel_fmares_lo_f6a_h (new_sel_fmares_lo_f6a_h),
    .fma_flags_f6a_h (new_fma_flags_f6a_h)
  );

endmodule : cosim_txfma_c6_tb
