// Copyright (c) 2026 Ainekko
// SPDX-License-Identifier: Apache-2.0

module cosim_sp_apb_mux_tb (
  /* verilator lint_off UNUSEDSIGNAL */
  input  logic        clk_i,
  input  logic        rst_ni,
  /* verilator lint_on UNUSEDSIGNAL */

  input  logic [15:0] apb_paddr,
  input  logic        apb_penable,
  input  logic        apb_psel,
  input  logic [63:0] apb_pwdata,
  input  logic        apb_pwrite,

  input  logic [63:0] esr_apb_prdata,
  input  logic        esr_apb_pready,
  input  logic        esr_apb_pslverr,
  input  logic [63:0] icache_apb_prdata,
  input  logic        icache_apb_pready,
  input  logic        icache_apb_pslverr,
  input  logic [63:0] minion_apb_prdata,
  input  logic        minion_apb_pready,
  input  logic        minion_apb_pslverr,
  input  logic [63:0] ic_data_apb_prdata,
  input  logic        ic_data_apb_pready,
  input  logic        ic_data_apb_pslverr,

  output logic [63:0] new_apb_prdata,
  output logic        new_apb_pready,
  output logic        new_apb_pslverr,
  output logic [3:0]  new_esr_apb_paddr,
  output logic        new_esr_apb_penable,
  output logic        new_esr_apb_psel,
  output logic [63:0] new_esr_apb_pwdata,
  output logic        new_esr_apb_pwrite,
  output logic [9:0]  new_icache_apb_paddr,
  output logic        new_icache_apb_pwrite,
  output logic        new_icache_apb_psel,
  output logic        new_icache_apb_penable,
  output logic [63:0] new_icache_apb_pwdata,
  output logic [12:0] new_minion_apb_paddr,
  output logic        new_minion_apb_penable,
  output logic        new_minion_apb_psel,
  output logic [63:0] new_minion_apb_pwdata,
  output logic        new_minion_apb_pwrite,
  output logic [12:0] new_ic_data_apb_paddr,
  output logic        new_ic_data_apb_pwrite,
  output logic        new_ic_data_apb_psel,
  output logic        new_ic_data_apb_penable,
  output logic [63:0] new_ic_data_apb_pwdata,

  output logic [63:0] orig_apb_prdata,
  output logic        orig_apb_pready,
  output logic        orig_apb_pslverr,
  output logic [3:0]  orig_esr_apb_paddr,
  output logic        orig_esr_apb_penable,
  output logic        orig_esr_apb_psel,
  output logic [63:0] orig_esr_apb_pwdata,
  output logic        orig_esr_apb_pwrite,
  output logic [9:0]  orig_icache_apb_paddr,
  output logic        orig_icache_apb_pwrite,
  output logic        orig_icache_apb_psel,
  output logic        orig_icache_apb_penable,
  output logic [63:0] orig_icache_apb_pwdata,
  output logic [12:0] orig_minion_apb_paddr,
  output logic        orig_minion_apb_penable,
  output logic        orig_minion_apb_psel,
  output logic [63:0] orig_minion_apb_pwdata,
  output logic        orig_minion_apb_pwrite,
  output logic [12:0] orig_ic_data_apb_paddr,
  output logic        orig_ic_data_apb_pwrite,
  output logic        orig_ic_data_apb_psel,
  output logic        orig_ic_data_apb_penable,
  output logic [63:0] orig_ic_data_apb_pwdata
);

  sp_apb_mux u_new (
    .apb_paddr,
    .apb_penable,
    .apb_prdata          (new_apb_prdata),
    .apb_pready          (new_apb_pready),
    .apb_psel,
    .apb_pslverr         (new_apb_pslverr),
    .apb_pwdata,
    .apb_pwrite,
    .esr_apb_paddr       (new_esr_apb_paddr),
    .esr_apb_penable     (new_esr_apb_penable),
    .esr_apb_prdata,
    .esr_apb_pready,
    .esr_apb_psel        (new_esr_apb_psel),
    .esr_apb_pslverr,
    .esr_apb_pwdata      (new_esr_apb_pwdata),
    .esr_apb_pwrite      (new_esr_apb_pwrite),
    .icache_apb_paddr    (new_icache_apb_paddr),
    .icache_apb_pwrite   (new_icache_apb_pwrite),
    .icache_apb_psel     (new_icache_apb_psel),
    .icache_apb_penable  (new_icache_apb_penable),
    .icache_apb_pwdata   (new_icache_apb_pwdata),
    .icache_apb_pready,
    .icache_apb_prdata,
    .icache_apb_pslverr,
    .minion_apb_paddr    (new_minion_apb_paddr),
    .minion_apb_penable  (new_minion_apb_penable),
    .minion_apb_prdata,
    .minion_apb_pready,
    .minion_apb_psel     (new_minion_apb_psel),
    .minion_apb_pslverr,
    .minion_apb_pwdata   (new_minion_apb_pwdata),
    .minion_apb_pwrite   (new_minion_apb_pwrite),
    .ic_data_apb_paddr   (new_ic_data_apb_paddr),
    .ic_data_apb_pwrite  (new_ic_data_apb_pwrite),
    .ic_data_apb_psel    (new_ic_data_apb_psel),
    .ic_data_apb_penable (new_ic_data_apb_penable),
    .ic_data_apb_pwdata  (new_ic_data_apb_pwdata),
    .ic_data_apb_pready,
    .ic_data_apb_prdata,
    .ic_data_apb_pslverr
  );

  sp_apb_mux_orig u_orig (
    .apb_paddr,
    .apb_penable,
    .apb_prdata          (orig_apb_prdata),
    .apb_pready          (orig_apb_pready),
    .apb_psel,
    .apb_pslverr         (orig_apb_pslverr),
    .apb_pwdata,
    .apb_pwrite,
    .esr_apb_paddr       (orig_esr_apb_paddr),
    .esr_apb_penable     (orig_esr_apb_penable),
    .esr_apb_prdata,
    .esr_apb_pready,
    .esr_apb_psel        (orig_esr_apb_psel),
    .esr_apb_pslverr,
    .esr_apb_pwdata      (orig_esr_apb_pwdata),
    .esr_apb_pwrite      (orig_esr_apb_pwrite),
    .icache_apb_paddr    (orig_icache_apb_paddr),
    .icache_apb_pwrite   (orig_icache_apb_pwrite),
    .icache_apb_psel     (orig_icache_apb_psel),
    .icache_apb_penable  (orig_icache_apb_penable),
    .icache_apb_pwdata   (orig_icache_apb_pwdata),
    .icache_apb_pready,
    .icache_apb_prdata,
    .icache_apb_pslverr,
    .minion_apb_paddr    (orig_minion_apb_paddr),
    .minion_apb_penable  (orig_minion_apb_penable),
    .minion_apb_prdata,
    .minion_apb_pready,
    .minion_apb_psel     (orig_minion_apb_psel),
    .minion_apb_pslverr,
    .minion_apb_pwdata   (orig_minion_apb_pwdata),
    .minion_apb_pwrite   (orig_minion_apb_pwrite),
    .ic_data_apb_paddr   (orig_ic_data_apb_paddr),
    .ic_data_apb_pwrite  (orig_ic_data_apb_pwrite),
    .ic_data_apb_psel    (orig_ic_data_apb_psel),
    .ic_data_apb_penable (orig_ic_data_apb_penable),
    .ic_data_apb_pwdata  (orig_ic_data_apb_pwdata),
    .ic_data_apb_pready,
    .ic_data_apb_prdata,
    .ic_data_apb_pslverr
  );

endmodule

