// Copyright (c) 2026 Ainekko
// SPDX-License-Identifier: Apache-2.0

/* verilator lint_off IMPORTSTAR */
import dft_pkg::*;
import etlink_pkg::*;
import minion_pkg::*;
import minion_dcache_pkg::*;
import vpu_pkg::*;
import vpu_defs_pkg::*;
/* verilator lint_on IMPORTSTAR */

module cosim_txfma_f5_tb
(
  input logic ctrl_f4_clk,
  input logic ctrl_f5_clk,
  input logic [TXFMA_A3:TXFMA_B47] comb_add_f5a_h,
  input logic [TXFMA_A3:TXFMA_B27] int_minmax_res_f5a_h,
  input logic [TXFMA_NORM_SHF_AMNT_SZ-1:0] enc_nsamt_f4a_h,
  input logic neg_norm_f5a_h,
  input logic en_logrrsel1b_f5a_l,
  input logic mmx_sel_immres_f5a_h,
  input logic nshcen_sel1b_f5a_h,
  input logic rc_ps_f5a_h,
  input logic rc_ph_f5a_h,
  input logic rc_int32_f5a_h,
  input logic int32_stky2r_f5a_h,
  input logic stky2g_f5a_h,
  input logic rc_3rmxr_f5a_h,
  input logic rc_rl01_f5a_h,
  input logic rc_rmm_f5a_h,
  input logic rc_rup_f5a_h,
  input logic rc_rne_f5a_h,
  input logic rc_rdn_f5a_h,
  input logic rc_res_sign_f5a_l,
  input logic rc_transrnd_f5a_h,
  input logic rc_transrnd_log_fma2_f5a_h,
  output logic orig_ph_allone2r_f5a_h,
  output logic new_ph_allone2r_f5a_h,
  output logic orig_ph_allone2l_f5a_h,
  output logic new_ph_allone2l_f5a_h,
  output logic orig_ps_allone2r_f5a_h,
  output logic new_ps_allone2r_f5a_h,
  output logic orig_ps_allone2l_f5a_h,
  output logic new_ps_allone2l_f5a_h,
  output logic orig_nshc_f5a_h,
  output logic new_nshc_f5a_h,
  output logic orig_ph_stky2l_f5a_h,
  output logic new_ph_stky2l_f5a_h,
  output logic orig_ps_stky2l_f5a_h,
  output logic new_ps_stky2l_f5a_h,
  output logic orig_int32_stky2l_f5a_h,
  output logic new_int32_stky2l_f5a_h,
  output logic orig_comb_add_a3_f5a_h,
  output logic new_comb_add_a3_f5a_h,
  output logic orig_frac_zero_f6a_h,
  output logic new_frac_zero_f6a_h,
  output logic orig_rnd_l_ph_f6a_h,
  output logic new_rnd_l_ph_f6a_h,
  output logic orig_rnd_r_ph_f6a_h,
  output logic new_rnd_r_ph_f6a_h,
  output logic orig_rnd_l_ps_f6a_h,
  output logic new_rnd_l_ps_f6a_h,
  output logic orig_rnd_r_ps_f6a_h,
  output logic new_rnd_r_ps_f6a_h,
  output logic orig_rnd_l_int_f6a_h,
  output logic new_rnd_l_int_f6a_h,
  output logic orig_rnd_r_int_f6a_h,
  output logic new_rnd_r_int_f6a_h,
  output logic [TXFMA_FTZ_SZ-1:0] orig_ftz_f6a_l,
  output logic [TXFMA_FTZ_SZ-1:0] new_ftz_f6a_l,
  output logic [TXFMA_A0:TXFMA_B31] orig_mergd_frac_res_hi_f6a_h,
  output logic [TXFMA_A0:TXFMA_B31] new_mergd_frac_res_hi_f6a_h
);

  txfma_f5_orig u_orig (
    .ctrl_f4_clk (ctrl_f4_clk),
    .ctrl_f5_clk (ctrl_f5_clk),
    .comb_add_f5a_h (comb_add_f5a_h),
    .int_minmax_res_f5a_h (int_minmax_res_f5a_h),
    .enc_nsamt_f4a_h (enc_nsamt_f4a_h),
    .neg_norm_f5a_h (neg_norm_f5a_h),
    .en_logrrsel1b_f5a_l (en_logrrsel1b_f5a_l),
    .mmx_sel_immres_f5a_h (mmx_sel_immres_f5a_h),
    .nshcen_sel1b_f5a_h (nshcen_sel1b_f5a_h),
    .rc_ps_f5a_h (rc_ps_f5a_h),
    .rc_ph_f5a_h (rc_ph_f5a_h),
    .rc_int32_f5a_h (rc_int32_f5a_h),
    .int32_stky2r_f5a_h (int32_stky2r_f5a_h),
    .stky2g_f5a_h (stky2g_f5a_h),
    .rc_3rmxr_f5a_h (rc_3rmxr_f5a_h),
    .rc_rl01_f5a_h (rc_rl01_f5a_h),
    .rc_rmm_f5a_h (rc_rmm_f5a_h),
    .rc_rup_f5a_h (rc_rup_f5a_h),
    .rc_rne_f5a_h (rc_rne_f5a_h),
    .rc_rdn_f5a_h (rc_rdn_f5a_h),
    .rc_res_sign_f5a_l (rc_res_sign_f5a_l),
    .rc_transrnd_f5a_h (rc_transrnd_f5a_h),
    .rc_transrnd_log_fma2_f5a_h (rc_transrnd_log_fma2_f5a_h),
    .ph_allone2r_f5a_h (orig_ph_allone2r_f5a_h),
    .ph_allone2l_f5a_h (orig_ph_allone2l_f5a_h),
    .ps_allone2r_f5a_h (orig_ps_allone2r_f5a_h),
    .ps_allone2l_f5a_h (orig_ps_allone2l_f5a_h),
    .nshc_f5a_h (orig_nshc_f5a_h),
    .ph_stky2l_f5a_h (orig_ph_stky2l_f5a_h),
    .ps_stky2l_f5a_h (orig_ps_stky2l_f5a_h),
    .int32_stky2l_f5a_h (orig_int32_stky2l_f5a_h),
    .comb_add_a3_f5a_h (orig_comb_add_a3_f5a_h),
    .frac_zero_f6a_h (orig_frac_zero_f6a_h),
    .rnd_l_ph_f6a_h (orig_rnd_l_ph_f6a_h),
    .rnd_r_ph_f6a_h (orig_rnd_r_ph_f6a_h),
    .rnd_l_ps_f6a_h (orig_rnd_l_ps_f6a_h),
    .rnd_r_ps_f6a_h (orig_rnd_r_ps_f6a_h),
    .rnd_l_int_f6a_h (orig_rnd_l_int_f6a_h),
    .rnd_r_int_f6a_h (orig_rnd_r_int_f6a_h),
    .ftz_f6a_l (orig_ftz_f6a_l),
    .mergd_frac_res_hi_f6a_h (orig_mergd_frac_res_hi_f6a_h)
  );

  txfma_f5 u_new (
    .ctrl_f4_clk (ctrl_f4_clk),
    .ctrl_f5_clk (ctrl_f5_clk),
    .comb_add_f5a_h (comb_add_f5a_h),
    .int_minmax_res_f5a_h (int_minmax_res_f5a_h),
    .enc_nsamt_f4a_h (enc_nsamt_f4a_h),
    .neg_norm_f5a_h (neg_norm_f5a_h),
    .en_logrrsel1b_f5a_l (en_logrrsel1b_f5a_l),
    .mmx_sel_immres_f5a_h (mmx_sel_immres_f5a_h),
    .nshcen_sel1b_f5a_h (nshcen_sel1b_f5a_h),
    .rc_ps_f5a_h (rc_ps_f5a_h),
    .rc_ph_f5a_h (rc_ph_f5a_h),
    .rc_int32_f5a_h (rc_int32_f5a_h),
    .int32_stky2r_f5a_h (int32_stky2r_f5a_h),
    .stky2g_f5a_h (stky2g_f5a_h),
    .rc_3rmxr_f5a_h (rc_3rmxr_f5a_h),
    .rc_rl01_f5a_h (rc_rl01_f5a_h),
    .rc_rmm_f5a_h (rc_rmm_f5a_h),
    .rc_rup_f5a_h (rc_rup_f5a_h),
    .rc_rne_f5a_h (rc_rne_f5a_h),
    .rc_rdn_f5a_h (rc_rdn_f5a_h),
    .rc_res_sign_f5a_l (rc_res_sign_f5a_l),
    .rc_transrnd_f5a_h (rc_transrnd_f5a_h),
    .rc_transrnd_log_fma2_f5a_h (rc_transrnd_log_fma2_f5a_h),
    .ph_allone2r_f5a_h (new_ph_allone2r_f5a_h),
    .ph_allone2l_f5a_h (new_ph_allone2l_f5a_h),
    .ps_allone2r_f5a_h (new_ps_allone2r_f5a_h),
    .ps_allone2l_f5a_h (new_ps_allone2l_f5a_h),
    .nshc_f5a_h (new_nshc_f5a_h),
    .ph_stky2l_f5a_h (new_ph_stky2l_f5a_h),
    .ps_stky2l_f5a_h (new_ps_stky2l_f5a_h),
    .int32_stky2l_f5a_h (new_int32_stky2l_f5a_h),
    .comb_add_a3_f5a_h (new_comb_add_a3_f5a_h),
    .frac_zero_f6a_h (new_frac_zero_f6a_h),
    .rnd_l_ph_f6a_h (new_rnd_l_ph_f6a_h),
    .rnd_r_ph_f6a_h (new_rnd_r_ph_f6a_h),
    .rnd_l_ps_f6a_h (new_rnd_l_ps_f6a_h),
    .rnd_r_ps_f6a_h (new_rnd_r_ps_f6a_h),
    .rnd_l_int_f6a_h (new_rnd_l_int_f6a_h),
    .rnd_r_int_f6a_h (new_rnd_r_int_f6a_h),
    .ftz_f6a_l (new_ftz_f6a_l),
    .mergd_frac_res_hi_f6a_h (new_mergd_frac_res_hi_f6a_h)
  );

endmodule : cosim_txfma_f5_tb
