class neigh_cvg_per_minion;

   // Cooperative minion mask
   covergroup neigh_coop_tload_mask_cg with function sample (bit [3:0] neigh_local_coop_min_mask, bit [2:0] neigh_local_coop_neigh_mask);

      option.name = "neigh_coop_tload_mask_cg";
      option.per_instance         = 0;
      type_option.merge_instances = 1;

      cp_neigh_coop_min_mask: coverpoint neigh_local_coop_min_mask {
         bins min_mask_1 = {1};
         bins min_mask_2 = {2};
         bins min_mask_3 = {3};
         bins min_mask_4 = {4};
         bins min_mask_5 = {5};
         bins min_mask_6 = {6};
         bins min_mask_7 = {7};
         bins min_mask_8 = {8};
      }

      cp_neigh_coop_neigh_mask: coverpoint neigh_local_coop_neigh_mask {
         bins neigh_mask_1 = {1};
         bins neigh_mask_2 = {2};
         bins neigh_mask_3 = {3};
         bins neigh_mask_4 = {4};
      }

   endgroup


   // Values of master neighborhood
   covergroup neigh_coop_tload_master_neigh_cg with function sample (int j, logic [`NUM_NEIGH_R] neigh_master_neigh);

      option.name = "neigh_coop_tload_master_neigh_cg";
      option.per_instance         = 0;
      type_option.merge_instances = 1;

      cp_neigh_coop_tload_master_neigh_tenb_req : coverpoint neigh_master_neigh iff (j == 0) {
         bins master_neigh_tenb_req[4] = {[0:3]};
      }

      cp_neigh_coop_tload_master_neigh_scp_req : coverpoint neigh_master_neigh iff (j == 1) {
         bins master_neigh_scp_req[4] = {[0:3]};
      }

   endgroup


   //
   covergroup neigh_min_evict_req_size_cg with function sample (neigh_et_link_minion_evict_req_info_t min_evict_req);

      option.name = "neigh_min_evict_req_size_cg";
      option.per_instance         = 0;
      type_option.merge_instances = 1;

      cp_neigh_min_evict_req_size: coverpoint min_evict_req.size {
         bins et_link_Byte               = {3'b000}; // 8b
         bins et_link_HWord              = {3'b001}; // 16b
         bins et_link_Word               = {3'b010}; // 32b
         bins et_link_DWord              = {3'b011}; // 64b
         bins et_link_QWord              = {3'b100}; // 128b
         bins et_link_HLine              = {3'b101}; // 256b
         bins et_link_Line               = {3'b110}; // 512b
         ignore_bins et_link_IllegalSize = {3'b111}; // Unused
      }

   endgroup


   // Sizes of ET Link miss requests generated by minions
   covergroup neigh_min_miss_req_size_cg with function sample (neigh_et_link_minion_miss_req_info_t min_miss_req);

      option.name = "neigh_min_miss_req_size_cg";
      option.per_instance         = 0;
      type_option.merge_instances = 1;

      cp_neigh_min_miss_req_size: coverpoint min_miss_req.size {
         bins et_link_Byte               = {3'b000}; // 8b
         bins et_link_HWord              = {3'b001}; // 16b
         bins et_link_Word               = {3'b010}; // 32b
         bins et_link_DWord              = {3'b011}; // 64b
         bins et_link_QWord              = {3'b100}; // 128b
         bins et_link_HLine              = {3'b101}; // 256b
         bins et_link_Line               = {3'b110}; // 512b
         ignore_bins et_link_IllegalSize = {3'b111}; // Unused
      }

   endgroup


   // Sizes of ET Link responses sent to minions
   covergroup neigh_min_resp_size_cg with function sample (neigh_et_link_minion_rsp_info_t min_rsp);

      option.name = "neigh_min_resp_size_cg";
      option.per_instance         = 0;
      type_option.merge_instances = 1;

      cp_neigh_min_resp_size: coverpoint min_rsp.size {
         bins et_link_Byte               = {3'b000}; // 8b
         bins et_link_HWord              = {3'b001}; // 16b
         bins et_link_Word               = {3'b010}; // 32b
         bins et_link_DWord              = {3'b011}; // 64b
         bins et_link_QWord              = {3'b100}; // 128b
         bins et_link_HLine              = {3'b101}; // 256b
         bins et_link_Line               = {3'b110}; // 512b
         ignore_bins et_link_IllegalSize = {3'b111}; // Unused
      }

   endgroup


   function new();
      neigh_coop_tload_mask_cg = new();
      neigh_coop_tload_master_neigh_cg = new();
      neigh_min_evict_req_size_cg = new();
      neigh_min_miss_req_size_cg = new();
      neigh_min_resp_size_cg = new();
   endfunction

endclass : neigh_cvg_per_minion;
