EXTRA_SRC+=trap_handler.S
STACK_SIZE_LOG2=16                                                                                                                  
STACK_BASE=0x8004090000
include $(MINION_DIAGS)/common/fullchip/fullchip.defines
include $(MINION_DIAGS)/common/include.mk

#CFLAGS+=-I${IOSHIRE_DIAGS}/sw/inc 
