// Copyright (c) 2026 Ainekko
// SPDX-License-Identifier: Apache-2.0

module txfma_c0_tb import minion_pkg::*; import vpu_defs_pkg::*;
(
  input logic clk_i,
  input logic rst_ni,
  input logic in_valid_exa_h,
  input logic [$bits(minion_pkg::vpu_ctrl_sigs_t)-1:0] sigs_in_exa_h_bits,
  input logic [TXFMA_RM_SZ-1:0] rm_in_exa_h,
  input logic [TRANS_MASK_SIZE-1:0] trans_mask_exa_h,
  input logic trans_taylor_exa_h,
  input logic trans_exp_fma2_exc_exa_h,
  input logic use_prev_sigs_exa_h,
  input logic sa_hi_f0a_h,
  input logic sa_lo_f0a_h,
  input logic sb_hi_f0a_h,
  input logic sb_lo_f0a_h,
  input logic sc_f0a_h,
  input logic ea_hi_zero_f0a_l,
  input logic ea_hi_all1_f0a_h,
  input logic ea_lo_zero_f0a_l,
  input logic ea_lo_all1_f0a_h,
  input logic eb_hi_zero_f0a_l,
  input logic eb_hi_all1_f0a_h,
  input logic eb_lo_zero_f0a_l,
  input logic eb_lo_all1_f0a_h,
  input logic ec_zero_f0a_l,
  input logic ec_all1_f0a_h,
  input logic eb_eql_127_f0a_h,
  input logic eb_eql_126_f0a_h,
  input logic eb_eql_125_f0a_h,
  input logic fcf10_zero_f0a_l,
  input logic fcf11_zero_f0a_l,
  input logic fcps_zero_f0a_h,
  input logic fcph_zero_f0a_l,
  input logic fcnorm_zero_29_8_f0a_h,
  input logic fcnorm16_eq_1_f0a_h,
  input logic fcnorm8_eq_1_f0a_h,
  input logic fcn8_one_30_24_f0a_h,
  input logic fcn10_one_30_22_f0a_h,
  input logic fcn16_one_30_16_f0a_h,
  input logic fcn24_one_30_8_f0a_h,
  input logic faps_zero_f0a_l,
  input logic fbps_zero_f0a_l,
  input logic faph_hi_zero_f0a_l,
  input logic fbph_hi_zero_f0a_l,
  input logic faph_lo_zero_f0a_l,
  input logic fbph_lo_zero_f0a_l,
  input logic faph_lo_b0_f0a_h,
  input logic fbph_lo_b0_f0a_h,
  input logic faps_b0_f0a_h,
  input logic fbps_b0_f0a_h,
  input logic fc_31_f0a_h,
  input logic fcnorm_30_f0a_h,
  input logic faph_hi_b0_f0a_h,
  input logic fbph_hi_b0_f0a_h,
  input logic fcph_b0_f0a_h,
  input logic fcf11_b0_f0a_h,
  input logic fcf10_b0_f0a_h,
  input logic fcps_b0_f0a_h,
  output logic trans_exp_fma2_exc_f0a_h,
  output logic opa_valid_rfa_h,
  output logic opb_valid_rfa_h,
  output logic opc_valid_rfa_h,
  output logic ctrl_valid_f0a_h,
  output logic is_trans_rfa_h,
  output logic [5:0] eb_hi_k_exa_h,
  output logic fa_en_exa_h,
  output logic fb_en_exa_h,
  output logic fc_en_exa_h,
  output logic sa_hi_en_exa_h,
  output logic sa_lo_en_exa_h,
  output logic sb_hi_en_exa_h,
  output logic sb_lo_en_exa_h,
  output logic ea_hi_zero_clr_f0a_h,
  output logic eb_hi_zero_clr_f0a_h,
  output logic ea_lo_zero_clr_f0a_h,
  output logic eb_lo_zero_clr_f0a_h,
  output logic [1:0] sel_eainmux_exa_h,
  output logic sel_ealo_ph_exa_h,
  output logic ehi_ea_en_exa_h,
  output logic elo_ea_en_exa_h,
  output logic [1:0] sel_ebin_hi_exa_h,
  output logic sel_eblo_ph_exa_h,
  output logic ehi_eb_en_exa_h,
  output logic elo_eb_en_exa_h,
  output logic [1:0] sel_ec5b_exa_h,
  output logic [1:0] sel_ecin_exa_h,
  output logic ec_en_exa_h,
  output logic sel_ec5bdet_exa_h,
  output logic sc_en_exa_h,
  output logic sa1_nr2_frcpfxp_exa_h,
  output logic [1:0] sel_sc_exa_h,
  output logic sel_sign_sinp2_exa_h,
  output logic sa_zap_exa_l,
  output logic sb_zap_exa_l,
  output logic sel_f10_exa_h,
  output logic sel_f11_exa_h,
  output logic [1:0] sel_opcgfx_exa_h,
  output logic fc_dtps_exa_h,
  output logic neg_fmaop_exa_h,
  output logic trans_op2_exa_l,
  output logic [1:0] sel_xopc_exa_h,
  output logic [1:0] sel_opcfmt_exa_h,
  output logic sel_snorm_exa_h,
  output logic sel_g1sk2_exa_h,
  output logic sel_g1sk8_exa_h,
  output logic sel_g1sk16_exa_h,
  output logic sel_g1sk24_exa_h,
  output logic sel_xexpfrac_exa_h,
  output logic [1:0] sel_transfa_exa_h,
  output logic [1:0] sel_transfb_exa_h,
  output logic [1:0] sel_opafmt_exa_h,
  output logic [1:0] sel_opbfmt_exa_h,
  output logic mul_sign_f0a_h,
  output logic mul_hp_mode_f0a_h,
  output logic res_inf_f0a_h,
  output logic res_snan_f0a_h,
  output logic res_qnan_f0a_h,
  output logic [FP_CLASS_BITS-1:0] classify_f0a_h,
  output logic prod_inf_hi_f0a_h,
  output logic c_inf_f0a_h,
  output logic a_inf_f0a_h,
  output logic [VPU_FLAGS_SZ-1:0] flags_f0a_h,
  output logic a_is_qnan_hi_f0a_h,
  output logic c_is_qnan_f0a_h,
  output logic a_is_snan_hi_f0a_h,
  output logic c_is_snan_f0a_h,
  output logic res_pos_int_nan_f0a_h,
  output logic res_neg_int_nan_f0a_h,
  output logic fc_zero30_8_f0a_h,
  output logic res_uint_nan_f0a_h,
  output logic res_zero_f0a_h,
  output logic res_one_f0a_h,
  output logic prod_inf_lo_f0a_h,
  output logic fa_hi_zero_f0a_h,
  output logic fb_hi_zero_f0a_h,
  output logic res_unorm_one_f0a_h,
  output logic res_snorm_one_f0a_h,
  output logic flags_en_f0a_h,
  output logic dtps_f0a_h,
  output logic spec_res_en_f0a_h,
  output logic use_prev_sigs_f0a_h,
  output logic [TXFMA_RM_SZ-1:0] rm_f0a_h,
  output logic [VPU_FCMD_SZ-1:0] cmd_f0a_h,
  output logic [TXFMA_SIGS_SZ-1:0] sigs_f0a_h,
  output logic [VPU_DTYPE_SZ-1:0] op_dtype_f0a_h,
  output logic [2:0] sin_res_shf_idx_f0a_h,
  output logic flog_mul_prod_zero_f0a_h,
  output logic ec_zero_clr_f0a_h,
  output logic use_mul_f0a_h,
  output logic [63:0] out_chunk0_o,
  output logic [63:0] out_chunk1_o,
  output logic [63:0] out_chunk2_o
);

  minion_pkg::vpu_ctrl_sigs_t sigs_in_exa_h;
  assign sigs_in_exa_h = minion_pkg::vpu_ctrl_sigs_t'(sigs_in_exa_h_bits);

  txfma_c0 u_dut (
    .clock (clk_i),
    .reset (!rst_ni),
    .in_valid_exa_h (in_valid_exa_h),
    .sigs_in_exa_h (sigs_in_exa_h),
    .rm_in_exa_h (rm_in_exa_h),
    .trans_mask_exa_h (trans_mask_exa_h),
    .trans_taylor_exa_h (trans_taylor_exa_h),
    .trans_exp_fma2_exc_exa_h (trans_exp_fma2_exc_exa_h),
    .use_prev_sigs_exa_h (use_prev_sigs_exa_h),
    .sa_hi_f0a_h (sa_hi_f0a_h),
    .sa_lo_f0a_h (sa_lo_f0a_h),
    .sb_hi_f0a_h (sb_hi_f0a_h),
    .sb_lo_f0a_h (sb_lo_f0a_h),
    .sc_f0a_h (sc_f0a_h),
    .ea_hi_zero_f0a_l (ea_hi_zero_f0a_l),
    .ea_hi_all1_f0a_h (ea_hi_all1_f0a_h),
    .ea_lo_zero_f0a_l (ea_lo_zero_f0a_l),
    .ea_lo_all1_f0a_h (ea_lo_all1_f0a_h),
    .eb_hi_zero_f0a_l (eb_hi_zero_f0a_l),
    .eb_hi_all1_f0a_h (eb_hi_all1_f0a_h),
    .eb_lo_zero_f0a_l (eb_lo_zero_f0a_l),
    .eb_lo_all1_f0a_h (eb_lo_all1_f0a_h),
    .ec_zero_f0a_l (ec_zero_f0a_l),
    .ec_all1_f0a_h (ec_all1_f0a_h),
    .eb_eql_127_f0a_h (eb_eql_127_f0a_h),
    .eb_eql_126_f0a_h (eb_eql_126_f0a_h),
    .eb_eql_125_f0a_h (eb_eql_125_f0a_h),
    .fcf10_zero_f0a_l (fcf10_zero_f0a_l),
    .fcf11_zero_f0a_l (fcf11_zero_f0a_l),
    .fcps_zero_f0a_h (fcps_zero_f0a_h),
    .fcph_zero_f0a_l (fcph_zero_f0a_l),
    .fcnorm_zero_29_8_f0a_h (fcnorm_zero_29_8_f0a_h),
    .fcnorm16_eq_1_f0a_h (fcnorm16_eq_1_f0a_h),
    .fcnorm8_eq_1_f0a_h (fcnorm8_eq_1_f0a_h),
    .fcn8_one_30_24_f0a_h (fcn8_one_30_24_f0a_h),
    .fcn10_one_30_22_f0a_h (fcn10_one_30_22_f0a_h),
    .fcn16_one_30_16_f0a_h (fcn16_one_30_16_f0a_h),
    .fcn24_one_30_8_f0a_h (fcn24_one_30_8_f0a_h),
    .faps_zero_f0a_l (faps_zero_f0a_l),
    .fbps_zero_f0a_l (fbps_zero_f0a_l),
    .faph_hi_zero_f0a_l (faph_hi_zero_f0a_l),
    .fbph_hi_zero_f0a_l (fbph_hi_zero_f0a_l),
    .faph_lo_zero_f0a_l (faph_lo_zero_f0a_l),
    .fbph_lo_zero_f0a_l (fbph_lo_zero_f0a_l),
    .faph_lo_b0_f0a_h (faph_lo_b0_f0a_h),
    .fbph_lo_b0_f0a_h (fbph_lo_b0_f0a_h),
    .faps_b0_f0a_h (faps_b0_f0a_h),
    .fbps_b0_f0a_h (fbps_b0_f0a_h),
    .fc_31_f0a_h (fc_31_f0a_h),
    .fcnorm_30_f0a_h (fcnorm_30_f0a_h),
    .faph_hi_b0_f0a_h (faph_hi_b0_f0a_h),
    .fbph_hi_b0_f0a_h (fbph_hi_b0_f0a_h),
    .fcph_b0_f0a_h (fcph_b0_f0a_h),
    .fcf11_b0_f0a_h (fcf11_b0_f0a_h),
    .fcf10_b0_f0a_h (fcf10_b0_f0a_h),
    .fcps_b0_f0a_h (fcps_b0_f0a_h),
    .trans_exp_fma2_exc_f0a_h (trans_exp_fma2_exc_f0a_h),
    .opa_valid_rfa_h (opa_valid_rfa_h),
    .opb_valid_rfa_h (opb_valid_rfa_h),
    .opc_valid_rfa_h (opc_valid_rfa_h),
    .ctrl_valid_f0a_h (ctrl_valid_f0a_h),
    .is_trans_rfa_h (is_trans_rfa_h),
    .eb_hi_k_exa_h (eb_hi_k_exa_h),
    .fa_en_exa_h (fa_en_exa_h),
    .fb_en_exa_h (fb_en_exa_h),
    .fc_en_exa_h (fc_en_exa_h),
    .sa_hi_en_exa_h (sa_hi_en_exa_h),
    .sa_lo_en_exa_h (sa_lo_en_exa_h),
    .sb_hi_en_exa_h (sb_hi_en_exa_h),
    .sb_lo_en_exa_h (sb_lo_en_exa_h),
    .ea_hi_zero_clr_f0a_h (ea_hi_zero_clr_f0a_h),
    .eb_hi_zero_clr_f0a_h (eb_hi_zero_clr_f0a_h),
    .ea_lo_zero_clr_f0a_h (ea_lo_zero_clr_f0a_h),
    .eb_lo_zero_clr_f0a_h (eb_lo_zero_clr_f0a_h),
    .sel_eainmux_exa_h (sel_eainmux_exa_h),
    .sel_ealo_ph_exa_h (sel_ealo_ph_exa_h),
    .ehi_ea_en_exa_h (ehi_ea_en_exa_h),
    .elo_ea_en_exa_h (elo_ea_en_exa_h),
    .sel_ebin_hi_exa_h (sel_ebin_hi_exa_h),
    .sel_eblo_ph_exa_h (sel_eblo_ph_exa_h),
    .ehi_eb_en_exa_h (ehi_eb_en_exa_h),
    .elo_eb_en_exa_h (elo_eb_en_exa_h),
    .sel_ec5b_exa_h (sel_ec5b_exa_h),
    .sel_ecin_exa_h (sel_ecin_exa_h),
    .ec_en_exa_h (ec_en_exa_h),
    .sel_ec5bdet_exa_h (sel_ec5bdet_exa_h),
    .sc_en_exa_h (sc_en_exa_h),
    .sa1_nr2_frcpfxp_exa_h (sa1_nr2_frcpfxp_exa_h),
    .sel_sc_exa_h (sel_sc_exa_h),
    .sel_sign_sinp2_exa_h (sel_sign_sinp2_exa_h),
    .sa_zap_exa_l (sa_zap_exa_l),
    .sb_zap_exa_l (sb_zap_exa_l),
    .sel_f10_exa_h (sel_f10_exa_h),
    .sel_f11_exa_h (sel_f11_exa_h),
    .sel_opcgfx_exa_h (sel_opcgfx_exa_h),
    .fc_dtps_exa_h (fc_dtps_exa_h),
    .neg_fmaop_exa_h (neg_fmaop_exa_h),
    .trans_op2_exa_l (trans_op2_exa_l),
    .sel_xopc_exa_h (sel_xopc_exa_h),
    .sel_opcfmt_exa_h (sel_opcfmt_exa_h),
    .sel_snorm_exa_h (sel_snorm_exa_h),
    .sel_g1sk2_exa_h (sel_g1sk2_exa_h),
    .sel_g1sk8_exa_h (sel_g1sk8_exa_h),
    .sel_g1sk16_exa_h (sel_g1sk16_exa_h),
    .sel_g1sk24_exa_h (sel_g1sk24_exa_h),
    .sel_xexpfrac_exa_h (sel_xexpfrac_exa_h),
    .sel_transfa_exa_h (sel_transfa_exa_h),
    .sel_transfb_exa_h (sel_transfb_exa_h),
    .sel_opafmt_exa_h (sel_opafmt_exa_h),
    .sel_opbfmt_exa_h (sel_opbfmt_exa_h),
    .mul_sign_f0a_h (mul_sign_f0a_h),
    .mul_hp_mode_f0a_h (mul_hp_mode_f0a_h),
    .res_inf_f0a_h (res_inf_f0a_h),
    .res_snan_f0a_h (res_snan_f0a_h),
    .res_qnan_f0a_h (res_qnan_f0a_h),
    .classify_f0a_h (classify_f0a_h),
    .prod_inf_hi_f0a_h (prod_inf_hi_f0a_h),
    .c_inf_f0a_h (c_inf_f0a_h),
    .a_inf_f0a_h (a_inf_f0a_h),
    .flags_f0a_h (flags_f0a_h),
    .a_is_qnan_hi_f0a_h (a_is_qnan_hi_f0a_h),
    .c_is_qnan_f0a_h (c_is_qnan_f0a_h),
    .a_is_snan_hi_f0a_h (a_is_snan_hi_f0a_h),
    .c_is_snan_f0a_h (c_is_snan_f0a_h),
    .res_pos_int_nan_f0a_h (res_pos_int_nan_f0a_h),
    .res_neg_int_nan_f0a_h (res_neg_int_nan_f0a_h),
    .fc_zero30_8_f0a_h (fc_zero30_8_f0a_h),
    .res_uint_nan_f0a_h (res_uint_nan_f0a_h),
    .res_zero_f0a_h (res_zero_f0a_h),
    .res_one_f0a_h (res_one_f0a_h),
    .prod_inf_lo_f0a_h (prod_inf_lo_f0a_h),
    .fa_hi_zero_f0a_h (fa_hi_zero_f0a_h),
    .fb_hi_zero_f0a_h (fb_hi_zero_f0a_h),
    .res_unorm_one_f0a_h (res_unorm_one_f0a_h),
    .res_snorm_one_f0a_h (res_snorm_one_f0a_h),
    .flags_en_f0a_h (flags_en_f0a_h),
    .dtps_f0a_h (dtps_f0a_h),
    .spec_res_en_f0a_h (spec_res_en_f0a_h),
    .use_prev_sigs_f0a_h (use_prev_sigs_f0a_h),
    .rm_f0a_h (rm_f0a_h),
    .cmd_f0a_h (cmd_f0a_h),
    .sigs_f0a_h (sigs_f0a_h),
    .op_dtype_f0a_h (op_dtype_f0a_h),
    .sin_res_shf_idx_f0a_h (sin_res_shf_idx_f0a_h),
    .flog_mul_prod_zero_f0a_h (flog_mul_prod_zero_f0a_h),
    .ec_zero_clr_f0a_h (ec_zero_clr_f0a_h),
    .use_mul_f0a_h (use_mul_f0a_h)
  );

  logic [152:0] all_outputs;
  assign all_outputs = {
    trans_exp_fma2_exc_f0a_h,
    opa_valid_rfa_h,
    opb_valid_rfa_h,
    opc_valid_rfa_h,
    ctrl_valid_f0a_h,
    is_trans_rfa_h,
    eb_hi_k_exa_h,
    fa_en_exa_h,
    fb_en_exa_h,
    fc_en_exa_h,
    sa_hi_en_exa_h,
    sa_lo_en_exa_h,
    sb_hi_en_exa_h,
    sb_lo_en_exa_h,
    ea_hi_zero_clr_f0a_h,
    eb_hi_zero_clr_f0a_h,
    ea_lo_zero_clr_f0a_h,
    eb_lo_zero_clr_f0a_h,
    sel_eainmux_exa_h,
    sel_ealo_ph_exa_h,
    ehi_ea_en_exa_h,
    elo_ea_en_exa_h,
    sel_ebin_hi_exa_h,
    sel_eblo_ph_exa_h,
    ehi_eb_en_exa_h,
    elo_eb_en_exa_h,
    sel_ec5b_exa_h,
    sel_ecin_exa_h,
    ec_en_exa_h,
    sel_ec5bdet_exa_h,
    sc_en_exa_h,
    sa1_nr2_frcpfxp_exa_h,
    sel_sc_exa_h,
    sel_sign_sinp2_exa_h,
    sa_zap_exa_l,
    sb_zap_exa_l,
    sel_f10_exa_h,
    sel_f11_exa_h,
    sel_opcgfx_exa_h,
    fc_dtps_exa_h,
    neg_fmaop_exa_h,
    trans_op2_exa_l,
    sel_xopc_exa_h,
    sel_opcfmt_exa_h,
    sel_snorm_exa_h,
    sel_g1sk2_exa_h,
    sel_g1sk8_exa_h,
    sel_g1sk16_exa_h,
    sel_g1sk24_exa_h,
    sel_xexpfrac_exa_h,
    sel_transfa_exa_h,
    sel_transfb_exa_h,
    sel_opafmt_exa_h,
    sel_opbfmt_exa_h,
    mul_sign_f0a_h,
    mul_hp_mode_f0a_h,
    res_inf_f0a_h,
    res_snan_f0a_h,
    res_qnan_f0a_h,
    classify_f0a_h,
    prod_inf_hi_f0a_h,
    c_inf_f0a_h,
    a_inf_f0a_h,
    flags_f0a_h,
    a_is_qnan_hi_f0a_h,
    c_is_qnan_f0a_h,
    a_is_snan_hi_f0a_h,
    c_is_snan_f0a_h,
    res_pos_int_nan_f0a_h,
    res_neg_int_nan_f0a_h,
    fc_zero30_8_f0a_h,
    res_uint_nan_f0a_h,
    res_zero_f0a_h,
    res_one_f0a_h,
    prod_inf_lo_f0a_h,
    fa_hi_zero_f0a_h,
    fb_hi_zero_f0a_h,
    res_unorm_one_f0a_h,
    res_snorm_one_f0a_h,
    flags_en_f0a_h,
    dtps_f0a_h,
    spec_res_en_f0a_h,
    use_prev_sigs_f0a_h,
    rm_f0a_h,
    cmd_f0a_h,
    sigs_f0a_h,
    op_dtype_f0a_h,
    sin_res_shf_idx_f0a_h,
    flog_mul_prod_zero_f0a_h,
    ec_zero_clr_f0a_h,
    use_mul_f0a_h
  };

  assign out_chunk0_o = all_outputs[0 +: 64];
  assign out_chunk1_o = all_outputs[64 +: 64];
  assign out_chunk2_o = {{ 39{1'b0} }, all_outputs[152:128]};

endmodule : txfma_c0_tb
