// Copyright (c) 2026 Ainekko
// SPDX-License-Identifier: Apache-2.0

/* verilator lint_off IMPORTSTAR */
import dft_pkg::*;
import etlink_pkg::*;
import minion_pkg::*;
import minion_dcache_pkg::*;
import vpu_pkg::*;
import vpu_defs_pkg::*;
/* verilator lint_on IMPORTSTAR */

module txfma_f0_tb
(
  input logic opa_frf_clk,
  input logic opb_frf_clk,
  input logic opc_frf_clk,
  input logic trans_frf_clk,
  input logic ctrl_frf_clk,
  input logic [VPU_DATA_S_SZ-1:0] opa_byp_frfa_h,
  input logic [VPU_DATA_S_SZ-1:0] opc_byp_frfa_h,
  input logic [VPU_DATA_S_SZ-1:0] opb_byp_frfa_h,
  input logic [TRANS_C0_MAX_SIZE-1:0] xrom_c1c0k_ra_h,
  input logic [TRANS_C2_MAX_SIZE-1:0] xrom_c2_ra_h,
  input logic [TRANS_MASK_SIZE-1:0] trans_mask_ra_h,
  input logic [5:0] eb_hi_k_exa_h,
  input logic [1:0] sel_ebin_hi_exa_h,
  input logic [1:0] sel_eainmux_exa_h,
  input logic [1:0] sel_ec5b_exa_h,
  input logic [1:0] sel_ecin_exa_h,
  input logic sel_ec5bdet_exa_h,
  input logic [1:0] sel_sc_exa_h,
  input logic [1:0] sel_opcgfx_exa_h,
  input logic [1:0] sel_xopc_exa_h,
  input logic [1:0] sel_opcfmt_exa_h,
  input logic [1:0] sel_transfa_exa_h,
  input logic [1:0] sel_transfb_exa_h,
  input logic [1:0] sel_opafmt_exa_h,
  input logic [1:0] sel_opbfmt_exa_h,
  input logic sel_eblo_ph_exa_h,
  input logic elo_eb_en_exa_h,
  input logic ehi_eb_en_exa_h,
  input logic elo_ea_en_exa_h,
  input logic fa_en_exa_h,
  input logic fb_en_exa_h,
  input logic fc_en_exa_h,
  input logic sel_ealo_ph_exa_h,
  input logic sa_hi_en_exa_h,
  input logic sa_lo_en_exa_h,
  input logic sb_hi_en_exa_h,
  input logic sb_lo_en_exa_h,
  input logic sc_en_exa_h,
  input logic ehi_ea_en_exa_h,
  input logic ec_en_exa_h,
  input logic neg_fmaop_exa_h,
  input logic trans_op2_exa_l,
  input logic sa1_nr2_frcpfxp_exa_h,
  input logic sel_sign_sinp2_exa_h,
  input logic sa_zap_exa_l,
  input logic sb_zap_exa_l,
  input logic sel_f10_exa_h,
  input logic sel_f11_exa_h,
  input logic fc_dtps_exa_h,
  input logic sel_snorm_exa_h,
  input logic sel_g1sk2_exa_h,
  input logic sel_g1sk8_exa_h,
  input logic sel_g1sk16_exa_h,
  input logic sel_g1sk24_exa_h,
  input logic sel_xexpfrac_exa_h,
  output logic sa_hi_f0a_h,
  output logic sa_lo_f0a_h,
  output logic sb_hi_f0a_h,
  output logic sb_lo_f0a_h,
  output logic sc_f0a_h,
  output logic [TXFMA_EXP_PS_SZ-1:0] ea_hi_f0a_h,
  output logic [TXFMA_EXP_PH_SZ-1:0] ea_lo_f0a_h,
  output logic [TXFMA_EXP_PS_SZ-1:0] eb_hi_f0a_h,
  output logic [TXFMA_EXP_PH_SZ-1:0] eb_lo_f0a_h,
  output logic [TXFMA_EXP_PS_SZ-1:0] ec_f0a_h,
  output logic [VPU_DATA_S_SZ-1:0] fa_f0a_h,
  output logic [VPU_DATA_S_SZ-1:0] fb_f0a_h,
  output logic [VPU_DATA_S_SZ-1:0] fc_f0a_h,
  output logic ea_hi_zero_f0a_l,
  output logic ea_hi_all1_f0a_h,
  output logic ea_lo_zero_f0a_l,
  output logic ea_lo_all1_f0a_h,
  output logic eb_hi_zero_f0a_l,
  output logic eb_hi_all1_f0a_h,
  output logic eb_lo_zero_f0a_l,
  output logic eb_lo_all1_f0a_h,
  output logic ec_zero_f0a_l,
  output logic ec_all1_f0a_h,
  output logic fcf10_zero_f0a_l,
  output logic eb_eql_127_f0a_h,
  output logic eb_eql_126_f0a_h,
  output logic eb_eql_125_f0a_h,
  output logic fcf11_zero_f0a_l,
  output logic fcps_zero_f0a_h,
  output logic fcph_zero_f0a_l,
  output logic fcnorm_zero_29_8_f0a_h,
  output logic fcnorm16_eq_1_f0a_h,
  output logic fcnorm8_eq_1_f0a_h,
  output logic fcn8_one_30_24_f0a_h,
  output logic fcn10_one_30_22_f0a_h,
  output logic fcn16_one_30_16_f0a_h,
  output logic fcn24_one_30_8_f0a_h,
  output logic faps_zero_f0a_l,
  output logic fbps_zero_f0a_l,
  output logic faph_hi_zero_f0a_l,
  output logic fbph_hi_zero_f0a_l,
  output logic faph_lo_zero_f0a_l,
  output logic fbph_lo_zero_f0a_l,
  output logic faph_lo_b0_f0a_h,
  output logic fbph_lo_b0_f0a_h,
  output logic faps_b0_f0a_h,
  output logic fbps_b0_f0a_h,
  output logic fc_31_f0a_h,
  output logic fcnorm_30_f0a_h,
  output logic faph_hi_b0_f0a_h,
  output logic fbph_hi_b0_f0a_h,
  output logic fcph_b0_f0a_h,
  output logic fcf11_b0_f0a_h,
  output logic fcf10_b0_f0a_h,
  output logic fcps_b0_f0a_h
);

  txfma_f0 u_dut (.*);

endmodule : txfma_f0_tb
