// Copyright (c) 2026 Ainekko
// SPDX-License-Identifier: Apache-2.0

module txfma_c2_tb import vpu_defs_pkg::*;
(
  input logic [VPU_DTYPE_SZ-1:0] op_dtype_f2a_h,
  input logic [VPU_FCMD_SZ-1:0] cmd_f2a_h,
  input logic [TXFMA_SIGS_SZ-1:0] sigs_f2a_h,
  input logic [TXFMA_RM_SZ-1:0] rm_f2a_h,
  input logic [TXFMA_EXP_SEXT_PS_SZ-1:0] ediff1_f2a_h,
  input logic [TXFMA_EXP_SEXT_PS_SZ-1:0] ediff1_abs_f2a_h,
  input logic [TXFMA_EXP_SEXT_PS_SZ-1:0] ediff2_abs_f2a_h,
  input logic [TXFMA_EDIFF_OPD_SEL_SZ-1:0] ediff1_sel_f2a_h,
  input logic [TXFMA_EDIFF_OPD_SEL_SZ-1:0] ediff2_sel_f2a_h,
  input logic [TXFMA_EDIFF_OPD_SEL_SZ-1:0] align1_mux_sel_f2a_h,
  input logic [TXFMA_EDIFF_OPD_SEL_SZ-1:0] align2_mux_sel_f2a_h,
  input logic [TXFMA_EDIFF_OPD_SEL_SZ-1:0] opd3_mux_sel_f2a_h,
  input logic [TXFMA_EXP_PS_SZ-1:0] ec_f2a_h,
  input logic ec_zero_f2a_h,
  input logic eprod_hi_zero_f2a_h,
  input logic fc_b0_f2a_h,
  input logic e_sticky1_f2a_h,
  input logic e_sticky2_f2a_h,
  input logic sc_f2a_h,
  input logic sel_fcmask_f2a_h,
  input logic prod_sign_hi_f2a_h,
  input logic prod_sign_lo_f2a_h,
  input logic fc_zero30_8_f2a_h,
  input logic minmax_op_f2a_h,
  output logic eff_sub1_f2a_h,
  output logic eff_sub2_f2a_h,
  output logic comp_op_f2a_h,
  output logic ediff1_0_f2a_h,
  output logic fa_ge_fc_comp_sign_hi_res_f2a_h,
  output logic fa_eq_fc_comp_sign_hi_res_f2a_h,
  output logic ediff1_lt_31_f2a_h,
  output logic cvt_fui_pos_ovf_f2a_h,
  output logic cvt_fi_pos_ovf_f2a_h,
  output logic cvt_fi_neg_ovf_f2a_h,
  output logic cvt_fi_min_neg_f2a_h,
  output logic fc_sel_f2a_h,
  output logic op3p1c_sel_p_f2a_h,
  output logic op3p1c_sel_r_f2a_h,
  output logic op3g_sel_f2a_h,
  output logic rm_rne_f2a_h,
  output logic rm_rmm_f2a_h,
  output logic frnd_rupnsc_f2a_h,
  output logic frnd_rdnsc_f2a_h,
  output logic frnd_t1_f2a_h,
  output logic frnd_t2_f2a_h,
  output logic al1c_zap_f2a_h,
  output logic op1c_log_mul_clr_f2a_h,
  output logic negop1c_int_logmul_clr_f2a_h,
  output logic psc_op1_clr_f2a_h,
  output logic align2_zap_f2a_h,
  output logic align2c_neg_f2a_h,
  output logic trans_log_rr_neg_f2a_h,
  output logic sin_eff_sub1_f2a_h,
  output logic al2c3_neg_cin_ps_f2a_h,
  output logic al1c3_neg_cin_f2a_h,
  output logic op2_sxtto_g_f2a_h,
  output logic [1:0] op3p3spc_sel_f2a_h,
  output logic [2:0] op3p2c_sel_f2a_h,
  output logic [1:0] ugfxrplc_sel_f2a_h,
  output logic [1:0] sgfxrplc_sel_f2a_h,
  output logic [1:0] icgfxc_sel_f2a_h,
  output logic [1:0] al1znp2c_sel_f2a_h,
  output logic [1:0] al2c_sel_f2a_h,
  output logic [1:0] al1p2c_sel_f2a_h,
  output logic sin_ediff2_f2a_h,
  output logic al1p1c_sel_f2a_h,
  output logic sin_align1_neg_f2a_h,
  output logic sin_align2_neg_f2a_h,
  output logic sin_check_fc_sign_f2a_h,
  output logic int_minmax_mux_sel_fc_f2a_h,
  output logic eff_sign1_f2a_h,
  output logic [63:0] out_chunk0_o
);

  txfma_c2 u_dut (
    .op_dtype_f2a_h (op_dtype_f2a_h),
    .cmd_f2a_h (cmd_f2a_h),
    .sigs_f2a_h (sigs_f2a_h),
    .rm_f2a_h (rm_f2a_h),
    .ediff1_f2a_h (ediff1_f2a_h),
    .ediff1_abs_f2a_h (ediff1_abs_f2a_h),
    .ediff2_abs_f2a_h (ediff2_abs_f2a_h),
    .ediff1_sel_f2a_h (ediff1_sel_f2a_h),
    .ediff2_sel_f2a_h (ediff2_sel_f2a_h),
    .align1_mux_sel_f2a_h (align1_mux_sel_f2a_h),
    .align2_mux_sel_f2a_h (align2_mux_sel_f2a_h),
    .opd3_mux_sel_f2a_h (opd3_mux_sel_f2a_h),
    .ec_f2a_h (ec_f2a_h),
    .ec_zero_f2a_h (ec_zero_f2a_h),
    .eprod_hi_zero_f2a_h (eprod_hi_zero_f2a_h),
    .fc_b0_f2a_h (fc_b0_f2a_h),
    .e_sticky1_f2a_h (e_sticky1_f2a_h),
    .e_sticky2_f2a_h (e_sticky2_f2a_h),
    .sc_f2a_h (sc_f2a_h),
    .sel_fcmask_f2a_h (sel_fcmask_f2a_h),
    .prod_sign_hi_f2a_h (prod_sign_hi_f2a_h),
    .prod_sign_lo_f2a_h (prod_sign_lo_f2a_h),
    .fc_zero30_8_f2a_h (fc_zero30_8_f2a_h),
    .minmax_op_f2a_h (minmax_op_f2a_h),
    .eff_sub1_f2a_h (eff_sub1_f2a_h),
    .eff_sub2_f2a_h (eff_sub2_f2a_h),
    .comp_op_f2a_h (comp_op_f2a_h),
    .ediff1_0_f2a_h (ediff1_0_f2a_h),
    .fa_ge_fc_comp_sign_hi_res_f2a_h (fa_ge_fc_comp_sign_hi_res_f2a_h),
    .fa_eq_fc_comp_sign_hi_res_f2a_h (fa_eq_fc_comp_sign_hi_res_f2a_h),
    .ediff1_lt_31_f2a_h (ediff1_lt_31_f2a_h),
    .cvt_fui_pos_ovf_f2a_h (cvt_fui_pos_ovf_f2a_h),
    .cvt_fi_pos_ovf_f2a_h (cvt_fi_pos_ovf_f2a_h),
    .cvt_fi_neg_ovf_f2a_h (cvt_fi_neg_ovf_f2a_h),
    .cvt_fi_min_neg_f2a_h (cvt_fi_min_neg_f2a_h),
    .fc_sel_f2a_h (fc_sel_f2a_h),
    .op3p1c_sel_p_f2a_h (op3p1c_sel_p_f2a_h),
    .op3p1c_sel_r_f2a_h (op3p1c_sel_r_f2a_h),
    .op3g_sel_f2a_h (op3g_sel_f2a_h),
    .rm_rne_f2a_h (rm_rne_f2a_h),
    .rm_rmm_f2a_h (rm_rmm_f2a_h),
    .frnd_rupnsc_f2a_h (frnd_rupnsc_f2a_h),
    .frnd_rdnsc_f2a_h (frnd_rdnsc_f2a_h),
    .frnd_t1_f2a_h (frnd_t1_f2a_h),
    .frnd_t2_f2a_h (frnd_t2_f2a_h),
    .al1c_zap_f2a_h (al1c_zap_f2a_h),
    .op1c_log_mul_clr_f2a_h (op1c_log_mul_clr_f2a_h),
    .negop1c_int_logmul_clr_f2a_h (negop1c_int_logmul_clr_f2a_h),
    .psc_op1_clr_f2a_h (psc_op1_clr_f2a_h),
    .align2_zap_f2a_h (align2_zap_f2a_h),
    .align2c_neg_f2a_h (align2c_neg_f2a_h),
    .trans_log_rr_neg_f2a_h (trans_log_rr_neg_f2a_h),
    .sin_eff_sub1_f2a_h (sin_eff_sub1_f2a_h),
    .al2c3_neg_cin_ps_f2a_h (al2c3_neg_cin_ps_f2a_h),
    .al1c3_neg_cin_f2a_h (al1c3_neg_cin_f2a_h),
    .op2_sxtto_g_f2a_h (op2_sxtto_g_f2a_h),
    .op3p3spc_sel_f2a_h (op3p3spc_sel_f2a_h),
    .op3p2c_sel_f2a_h (op3p2c_sel_f2a_h),
    .ugfxrplc_sel_f2a_h (ugfxrplc_sel_f2a_h),
    .sgfxrplc_sel_f2a_h (sgfxrplc_sel_f2a_h),
    .icgfxc_sel_f2a_h (icgfxc_sel_f2a_h),
    .al1znp2c_sel_f2a_h (al1znp2c_sel_f2a_h),
    .al2c_sel_f2a_h (al2c_sel_f2a_h),
    .al1p2c_sel_f2a_h (al1p2c_sel_f2a_h),
    .sin_ediff2_f2a_h (sin_ediff2_f2a_h),
    .al1p1c_sel_f2a_h (al1p1c_sel_f2a_h),
    .sin_align1_neg_f2a_h (sin_align1_neg_f2a_h),
    .sin_align2_neg_f2a_h (sin_align2_neg_f2a_h),
    .sin_check_fc_sign_f2a_h (sin_check_fc_sign_f2a_h),
    .int_minmax_mux_sel_fc_f2a_h (int_minmax_mux_sel_fc_f2a_h),
    .eff_sign1_f2a_h (eff_sign1_f2a_h)
  );

  logic [55:0] all_outputs;
  assign all_outputs = {
    eff_sub1_f2a_h,
    eff_sub2_f2a_h,
    comp_op_f2a_h,
    ediff1_0_f2a_h,
    fa_ge_fc_comp_sign_hi_res_f2a_h,
    fa_eq_fc_comp_sign_hi_res_f2a_h,
    ediff1_lt_31_f2a_h,
    cvt_fui_pos_ovf_f2a_h,
    cvt_fi_pos_ovf_f2a_h,
    cvt_fi_neg_ovf_f2a_h,
    cvt_fi_min_neg_f2a_h,
    fc_sel_f2a_h,
    op3p1c_sel_p_f2a_h,
    op3p1c_sel_r_f2a_h,
    op3g_sel_f2a_h,
    rm_rne_f2a_h,
    rm_rmm_f2a_h,
    frnd_rupnsc_f2a_h,
    frnd_rdnsc_f2a_h,
    frnd_t1_f2a_h,
    frnd_t2_f2a_h,
    al1c_zap_f2a_h,
    op1c_log_mul_clr_f2a_h,
    negop1c_int_logmul_clr_f2a_h,
    psc_op1_clr_f2a_h,
    align2_zap_f2a_h,
    align2c_neg_f2a_h,
    trans_log_rr_neg_f2a_h,
    sin_eff_sub1_f2a_h,
    al2c3_neg_cin_ps_f2a_h,
    al1c3_neg_cin_f2a_h,
    op2_sxtto_g_f2a_h,
    op3p3spc_sel_f2a_h,
    op3p2c_sel_f2a_h,
    ugfxrplc_sel_f2a_h,
    sgfxrplc_sel_f2a_h,
    icgfxc_sel_f2a_h,
    al1znp2c_sel_f2a_h,
    al2c_sel_f2a_h,
    al1p2c_sel_f2a_h,
    sin_ediff2_f2a_h,
    al1p1c_sel_f2a_h,
    sin_align1_neg_f2a_h,
    sin_align2_neg_f2a_h,
    sin_check_fc_sign_f2a_h,
    int_minmax_mux_sel_fc_f2a_h,
    eff_sign1_f2a_h
  };

  assign out_chunk0_o = {{ 8{1'b0} }, all_outputs[55:0]};

endmodule : txfma_c2_tb
