// Copyright (c) 2026 Ainekko
// SPDX-License-Identifier: Apache-2.0

module txfmaexp_top_tb
  import minion_pkg::*;
  import vpu_pkg::*;
  import vpu_defs_pkg::*;
(
  input  logic                                clk_i,
  input  logic                                ec_zero_f1a_h_i,
  input  logic                                ec_all1_f1a_h_i,
  input  logic                                ctrl_valid_f1a_h_i,
  input  logic                                ctrl_valid_f2a_h_i,
  input  logic                                ctrl_valid_f3a_h_i,
  input  logic                                ctrl_valid_f4a_h_i,
  input  logic                                ctrl_valid_f5a_h_i,
  input  logic [VPU_DTYPE_SZ-1:0]             op_dtype_f1a_h_i,
  input  logic [VPU_DTYPE_SZ-1:0]             op_dtype_f2a_h_i,
  input  logic [VPU_DTYPE_SZ-1:0]             op_dtype_f5a_h_i,
  input  logic [VPU_DTYPE_SZ-1:0]             op_dtype_f6a_h_i,
  input  logic [TXFMA_SIGS_SZ-1:0]            sigs_f1a_h_i,
  input  logic [TXFMA_SIGS_SZ-1:0]            sigs_f2a_h_i,
  input  logic [TXFMA_SIGS_SZ-1:0]            sigs_f5a_h_i,
  input  logic [TXFMA_SIGS_SZ-1:0]            sigs_f6a_h_i,
  input  logic [VPU_FCMD_SZ-1:0]              cmd_f1a_h_i,
  input  logic [VPU_FCMD_SZ-1:0]              cmd_f2a_h_i,
  input  logic [VPU_FCMD_SZ-1:0]              cmd_f5a_h_i,
  input  logic [VPU_FCMD_SZ-1:0]              cmd_f6a_h_i,
  input  logic [TXFMA_EXP_PS_SZ-1:0]          ea_hi_f1a_h_i,
  input  logic [TXFMA_EXP_PH_SZ-1:0]          ea_lo_f1a_h_i,
  input  logic [TXFMA_EXP_PS_SZ-1:0]          eb_hi_f1a_h_i,
  input  logic [TXFMA_EXP_PH_SZ-1:0]          eb_lo_f1a_h_i,
  input  logic [TXFMA_EXP_PS_SZ-1:0]          ec_f1a_h_i,
  input  logic [3:0]                          etrz_fa_hi_ph_f1a_h_i,
  input  logic [4:0]                          etrz_fa_lo_ps_f1a_h_i,
  input  logic [3:0]                          etrz_fb_hi_ph_f1a_h_i,
  input  logic [4:0]                          etrz_fb_lo_ps_f1a_h_i,
  input  logic [4:0]                          etrz_fc_f1a_h_i,
  input  logic                                sin_ediff2_f2a_h_i,
  input  logic [TXFMA_LXD_PS_SZ-1:0]          elxd_f4a_h_i,
  input  logic [TXFMA_WSPS_ETRZ_SZ-1:0]       etrz50_f4a_h_i,
  input  logic [TXFMA_RM_SZ-1:0]              rm_f5a_h_i,
  input  logic [TXFMA_EXP_PS_SZ-1:0]          ea_hi_f5a_h_i,
  input  logic                                ea_hi_zero_f1a_h_i,
  input  logic                                fc_zero30_8_f1a_h_i,
  input  logic                                eprod_hi_zero_f2a_h_i,
  input  logic                                eprod_lo_zero_f2a_h_i,
  input  logic                                ec_zero_f2a_h_i,
  input  logic                                exp_fma2_exc_f2a_h_i,
  input  logic                                eb_hi_lsb_f4a_h_i,
  input  logic                                use_elxd_f4a_h_i,
  input  logic                                elxd_add_in2_mux_sel_f4a_h_i,
  input  logic                                fb_hi_zero_f4a_h_i,
  input  logic                                comp_op_f5a_h_i,
  input  logic                                comp_op_true_f5a_h_i,
  input  logic                                int_minmax_mux_sel_a_f5a_h_i,
  input  logic                                int_minmax_mux_sel_c_f5a_h_i,
  input  logic                                nshc_f5a_h_i,
  input  logic                                s_res_f5a_h_i,
  input  logic                                e_force_to_zero_f5a_h_i,
  input  logic                                ps_rndovf_f6a_h_i,
  input  logic                                ph_rndovf_f6a_h_i,
  output logic [TXFMA_EXP_PS_SZ-1:0]          ec_f2a_h_o,
  output logic [TXFMA_EXP_PS_SZ-1:0]          ec_f3a_h_o,
  output logic                                e_sticky1_f2a_h_o,
  output logic                                e_sticky2_f2a_h_o,
  output logic                                e_sticky1_f3a_h_o,
  output logic [TXFMA_EDIFF_OPD_SEL_SZ-1:0]   align1_mux_sel_f2a_h_o,
  output logic [TXFMA_EDIFF_OPD_SEL_SZ-1:0]   align2_mux_sel_f2a_h_o,
  output logic [TXFMA_EDIFF_OPD_SEL_SZ-1:0]   opd3_mux_sel_f2a_h_o,
  output logic [TXFMA_EXP_SEXT_PS_SZ-1:0]     ediff1_f2a_h_o,
  output logic [TXFMA_EXP_SEXT_PS_SZ-1:0]     ediff2_f3a_h_o,
  output logic [TXFMA_EDIFF_OPD_SEL_SZ-1:0]   ediff1_sel_f2a_h_o,
  output logic [TXFMA_EDIFF_OPD_SEL_SZ-1:0]   ediff2_sel_f2a_h_o,
  output logic [TXFMA_EXP_SEXT_PS_SZ-1:0]     ediff1_abs_f2a_h_o,
  output logic [TXFMA_EXP_SEXT_PS_SZ-1:0]     ediff2_abs_f2a_h_o,
  output logic [5:0]                          ediff_abs_diff_hi_f2a_h_o,
  output logic [4:0]                          align2_rshamt_c3_f2a_h_o,
  output logic                                ph_comb_stiky_f4a_h_o,
  output logic [6:0]                          exp_res_2f3_f2a_h_o,
  output logic                                stky2g_f5a_h_o,
  output logic [TXFMA_EXP_PS_SZ-1:0]          exp_res_f6a_h_o,
  output logic                                exp_res_zero_f6a_h_o,
  output logic                                rmode_f5a_h_o,
  output logic                                ediff1_zap_f5a_h_o,
  output logic                                def_ovf_ps_f6a_h_o,
  output logic                                pot_ovf_ps_f6a_h_o,
  output logic                                def_unf_ps_f6a_h_o,
  output logic                                pot_unf_ps_f6a_h_o,
  output logic                                def_ovf_ph_f6a_h_o,
  output logic                                pot_ovf_ph_f6a_h_o,
  output logic                                def_unf_ph_f6a_h_o,
  output logic                                pot_unf_ph_f6a_h_o
);

  txfmaexp_top u_dut (
    .clock                   (clk_i),
    .ec_zero_f1a_h           (ec_zero_f1a_h_i),
    .ec_all1_f1a_h           (ec_all1_f1a_h_i),
    .ctrl_valid_f1a_h        (ctrl_valid_f1a_h_i),
    .ctrl_valid_f2a_h        (ctrl_valid_f2a_h_i),
    .ctrl_valid_f3a_h        (ctrl_valid_f3a_h_i),
    .ctrl_valid_f4a_h        (ctrl_valid_f4a_h_i),
    .ctrl_valid_f5a_h        (ctrl_valid_f5a_h_i),
    .op_dtype_f1a_h          (op_dtype_f1a_h_i),
    .op_dtype_f2a_h          (op_dtype_f2a_h_i),
    .op_dtype_f5a_h          (op_dtype_f5a_h_i),
    .op_dtype_f6a_h          (op_dtype_f6a_h_i),
    .sigs_f1a_h              (sigs_f1a_h_i),
    .sigs_f2a_h              (sigs_f2a_h_i),
    .sigs_f5a_h              (sigs_f5a_h_i),
    .sigs_f6a_h              (sigs_f6a_h_i),
    .cmd_f1a_h               (cmd_f1a_h_i),
    .cmd_f2a_h               (cmd_f2a_h_i),
    .cmd_f5a_h               (cmd_f5a_h_i),
    .cmd_f6a_h               (cmd_f6a_h_i),
    .ea_hi_f1a_h             (ea_hi_f1a_h_i),
    .ea_lo_f1a_h             (ea_lo_f1a_h_i),
    .eb_hi_f1a_h             (eb_hi_f1a_h_i),
    .eb_lo_f1a_h             (eb_lo_f1a_h_i),
    .ec_f1a_h                (ec_f1a_h_i),
    .etrz_fa_hi_ph_f1a_h     (etrz_fa_hi_ph_f1a_h_i),
    .etrz_fa_lo_ps_f1a_h     (etrz_fa_lo_ps_f1a_h_i),
    .etrz_fb_hi_ph_f1a_h     (etrz_fb_hi_ph_f1a_h_i),
    .etrz_fb_lo_ps_f1a_h     (etrz_fb_lo_ps_f1a_h_i),
    .etrz_fc_f1a_h           (etrz_fc_f1a_h_i),
    .sin_ediff2_f2a_h        (sin_ediff2_f2a_h_i),
    .elxd_f4a_h              (elxd_f4a_h_i),
    .etrz50_f4a_h            (etrz50_f4a_h_i),
    .rm_f5a_h                (rm_f5a_h_i),
    .ea_hi_f5a_h             (ea_hi_f5a_h_i),
    .ea_hi_zero_f1a_h        (ea_hi_zero_f1a_h_i),
    .fc_zero30_8_f1a_h       (fc_zero30_8_f1a_h_i),
    .eprod_hi_zero_f2a_h     (eprod_hi_zero_f2a_h_i),
    .eprod_lo_zero_f2a_h     (eprod_lo_zero_f2a_h_i),
    .ec_zero_f2a_h           (ec_zero_f2a_h_i),
    .exp_fma2_exc_f2a_h      (exp_fma2_exc_f2a_h_i),
    .eb_hi_lsb_f4a_h         (eb_hi_lsb_f4a_h_i),
    .use_elxd_f4a_h          (use_elxd_f4a_h_i),
    .elxd_add_in2_mux_sel_f4a_h(elxd_add_in2_mux_sel_f4a_h_i),
    .fb_hi_zero_f4a_h        (fb_hi_zero_f4a_h_i),
    .comp_op_f5a_h           (comp_op_f5a_h_i),
    .comp_op_true_f5a_h      (comp_op_true_f5a_h_i),
    .int_minmax_mux_sel_a_f5a_h(int_minmax_mux_sel_a_f5a_h_i),
    .int_minmax_mux_sel_c_f5a_h(int_minmax_mux_sel_c_f5a_h_i),
    .nshc_f5a_h              (nshc_f5a_h_i),
    .s_res_f5a_h             (s_res_f5a_h_i),
    .e_force_to_zero_f5a_h   (e_force_to_zero_f5a_h_i),
    .ps_rndovf_f6a_h         (ps_rndovf_f6a_h_i),
    .ph_rndovf_f6a_h         (ph_rndovf_f6a_h_i),
    .ec_f2a_h                (ec_f2a_h_o),
    .ec_f3a_h                (ec_f3a_h_o),
    .e_sticky1_f2a_h         (e_sticky1_f2a_h_o),
    .e_sticky2_f2a_h         (e_sticky2_f2a_h_o),
    .e_sticky1_f3a_h         (e_sticky1_f3a_h_o),
    .align1_mux_sel_f2a_h    (align1_mux_sel_f2a_h_o),
    .align2_mux_sel_f2a_h    (align2_mux_sel_f2a_h_o),
    .opd3_mux_sel_f2a_h      (opd3_mux_sel_f2a_h_o),
    .ediff1_f2a_h            (ediff1_f2a_h_o),
    .ediff2_f3a_h            (ediff2_f3a_h_o),
    .ediff1_sel_f2a_h        (ediff1_sel_f2a_h_o),
    .ediff2_sel_f2a_h        (ediff2_sel_f2a_h_o),
    .ediff1_abs_f2a_h        (ediff1_abs_f2a_h_o),
    .ediff2_abs_f2a_h        (ediff2_abs_f2a_h_o),
    .ediff_abs_diff_hi_f2a_h (ediff_abs_diff_hi_f2a_h_o),
    .align2_rshamt_c3_f2a_h  (align2_rshamt_c3_f2a_h_o),
    .ph_comb_stiky_f4a_h     (ph_comb_stiky_f4a_h_o),
    .exp_res_2f3_f2a_h       (exp_res_2f3_f2a_h_o),
    .stky2g_f5a_h            (stky2g_f5a_h_o),
    .exp_res_f6a_h           (exp_res_f6a_h_o),
    .exp_res_zero_f6a_h      (exp_res_zero_f6a_h_o),
    .rmode_f5a_h             (rmode_f5a_h_o),
    .ediff1_zap_f5a_h        (ediff1_zap_f5a_h_o),
    .def_ovf_ps_f6a_h        (def_ovf_ps_f6a_h_o),
    .pot_ovf_ps_f6a_h        (pot_ovf_ps_f6a_h_o),
    .def_unf_ps_f6a_h        (def_unf_ps_f6a_h_o),
    .pot_unf_ps_f6a_h        (pot_unf_ps_f6a_h_o),
    .def_ovf_ph_f6a_h        (def_ovf_ph_f6a_h_o),
    .pot_ovf_ph_f6a_h        (pot_ovf_ph_f6a_h_o),
    .def_unf_ph_f6a_h        (def_unf_ph_f6a_h_o),
    .pot_unf_ph_f6a_h        (pot_unf_ph_f6a_h_o)
  );

endmodule
