// Copyright (c) 2026 Ainekko
// SPDX-License-Identifier: Apache-2.0

module txfma_c3_tb import vpu_defs_pkg::*;
(
  input logic [VPU_DTYPE_SZ-1:0] op_dtype_f3a_h,
  input logic [VPU_FCMD_SZ-1:0] cmd_f3a_h,
  input logic [TXFMA_SIGS_SZ-1:0] sigs_f3a_h,
  input logic [TXFMA_EXP_SEXT_PS_SZ-1:0] ediff1_f3a_h,
  input logic [TXFMA_EXP_SEXT_PS_SZ-1:0] ediff2_f3a_h,
  input logic [TXFMA_EXP_PS_SZ-1:0] ec_f3a_h,
  input logic [TXFMA_RM_SZ-1:0] rm_f3a_h,
  input logic eff_sub1_f3a_h,
  input logic eff_sub2_f3a_h,
  input logic eprod_hi_zero_f3a_h,
  input logic eprod_lo_zero_f3a_h,
  input logic prod_inf_hi_f3a_h,
  input logic prod_inf_lo_f3a_h,
  input logic eff_sign1_f3a_h,
  input logic prod_sign_hi_f3a_h,
  input logic prod_sign_lo_f3a_h,
  input logic sc_f3a_h,
  input logic c_inf_f3a_h,
  input logic ec_zero_f3a_h,
  input logic a_is_qnan_hi_f3a_h,
  input logic c_is_qnan_f3a_h,
  input logic a_is_snan_hi_f3a_h,
  input logic c_is_snan_f3a_h,
  input logic e_sticky1_f3a_h,
  input logic fround_rbit_f3a_h,
  input logic prodsum_a2_f3a_h,
  input logic ediff1_0_f3a_h,
  input logic fa_ge_fc_comp_sign_hi_res_f3a_h,
  input logic fa_eq_fc_comp_sign_hi_res_f3a_h,
  input logic int_minmax_mux_sel_fc_f3a_h,
  input logic minmax_op_f3a_h,
  input logic comp_op_f3a_h,
  input logic res_inf_f3a_h,
  input logic res_qnan_f3a_h,
  input logic res_snan_f3a_h,
  input logic spec_res_en_f3a_h,
  input logic flags_en_f3a_h,
  input logic trans_log_rr_neg_f3a_h,
  input logic sin_align1_neg_f3a_h,
  input logic sin_align2_neg_f3a_h,
  input logic sin_eff_sub1_f3a_h,
  input logic sin_check_fc_sign_f3a_h,
  input logic fc_sel_f3a_h,
  input logic [TXFMA_EDIFF_OPD_SEL_SZ-1:0] opd3_mux_sel_f3a_h,
  output logic [1:0] imxc_sel_f3a_h,
  output logic res_snan_out_f3a_h,
  output logic res_qnan_out_f3a_h,
  output logic res_inf_out_f3a_h,
  output logic res_neg_inf_out_f3a_h,
  output logic comp_res_sel_f3a_h,
  output logic fa_eq_fc_res_check_hi_f3a_h,
  output logic eff_sub1_out_f3a_h,
  output logic cmp_invalid_f3a_h,
  output logic fma_subopc3_f3a_h,
  output logic s_res_f3a_h,
  output logic s_res_check_cadd_a3_f3a_h,
  output logic int_minmax_mux_sel_a_f3a_h,
  output logic int_minmax_mux_sel_c_f3a_h,
  output logic fround_stky2l_f3a_h,
  output logic [63:0] out_chunk0_o
);

  txfma_c3 u_dut (
    .op_dtype_f3a_h (op_dtype_f3a_h),
    .cmd_f3a_h (cmd_f3a_h),
    .sigs_f3a_h (sigs_f3a_h),
    .ediff1_f3a_h (ediff1_f3a_h),
    .ediff2_f3a_h (ediff2_f3a_h),
    .ec_f3a_h (ec_f3a_h),
    .rm_f3a_h (rm_f3a_h),
    .eff_sub1_f3a_h (eff_sub1_f3a_h),
    .eff_sub2_f3a_h (eff_sub2_f3a_h),
    .eprod_hi_zero_f3a_h (eprod_hi_zero_f3a_h),
    .eprod_lo_zero_f3a_h (eprod_lo_zero_f3a_h),
    .prod_inf_hi_f3a_h (prod_inf_hi_f3a_h),
    .prod_inf_lo_f3a_h (prod_inf_lo_f3a_h),
    .eff_sign1_f3a_h (eff_sign1_f3a_h),
    .prod_sign_hi_f3a_h (prod_sign_hi_f3a_h),
    .prod_sign_lo_f3a_h (prod_sign_lo_f3a_h),
    .sc_f3a_h (sc_f3a_h),
    .c_inf_f3a_h (c_inf_f3a_h),
    .ec_zero_f3a_h (ec_zero_f3a_h),
    .a_is_qnan_hi_f3a_h (a_is_qnan_hi_f3a_h),
    .c_is_qnan_f3a_h (c_is_qnan_f3a_h),
    .a_is_snan_hi_f3a_h (a_is_snan_hi_f3a_h),
    .c_is_snan_f3a_h (c_is_snan_f3a_h),
    .e_sticky1_f3a_h (e_sticky1_f3a_h),
    .fround_rbit_f3a_h (fround_rbit_f3a_h),
    .prodsum_a2_f3a_h (prodsum_a2_f3a_h),
    .ediff1_0_f3a_h (ediff1_0_f3a_h),
    .fa_ge_fc_comp_sign_hi_res_f3a_h (fa_ge_fc_comp_sign_hi_res_f3a_h),
    .fa_eq_fc_comp_sign_hi_res_f3a_h (fa_eq_fc_comp_sign_hi_res_f3a_h),
    .int_minmax_mux_sel_fc_f3a_h (int_minmax_mux_sel_fc_f3a_h),
    .minmax_op_f3a_h (minmax_op_f3a_h),
    .comp_op_f3a_h (comp_op_f3a_h),
    .res_inf_f3a_h (res_inf_f3a_h),
    .res_qnan_f3a_h (res_qnan_f3a_h),
    .res_snan_f3a_h (res_snan_f3a_h),
    .spec_res_en_f3a_h (spec_res_en_f3a_h),
    .flags_en_f3a_h (flags_en_f3a_h),
    .trans_log_rr_neg_f3a_h (trans_log_rr_neg_f3a_h),
    .sin_align1_neg_f3a_h (sin_align1_neg_f3a_h),
    .sin_align2_neg_f3a_h (sin_align2_neg_f3a_h),
    .sin_eff_sub1_f3a_h (sin_eff_sub1_f3a_h),
    .sin_check_fc_sign_f3a_h (sin_check_fc_sign_f3a_h),
    .fc_sel_f3a_h (fc_sel_f3a_h),
    .opd3_mux_sel_f3a_h (opd3_mux_sel_f3a_h),
    .imxc_sel_f3a_h (imxc_sel_f3a_h),
    .res_snan_out_f3a_h (res_snan_out_f3a_h),
    .res_qnan_out_f3a_h (res_qnan_out_f3a_h),
    .res_inf_out_f3a_h (res_inf_out_f3a_h),
    .res_neg_inf_out_f3a_h (res_neg_inf_out_f3a_h),
    .comp_res_sel_f3a_h (comp_res_sel_f3a_h),
    .fa_eq_fc_res_check_hi_f3a_h (fa_eq_fc_res_check_hi_f3a_h),
    .eff_sub1_out_f3a_h (eff_sub1_out_f3a_h),
    .cmp_invalid_f3a_h (cmp_invalid_f3a_h),
    .fma_subopc3_f3a_h (fma_subopc3_f3a_h),
    .s_res_f3a_h (s_res_f3a_h),
    .s_res_check_cadd_a3_f3a_h (s_res_check_cadd_a3_f3a_h),
    .int_minmax_mux_sel_a_f3a_h (int_minmax_mux_sel_a_f3a_h),
    .int_minmax_mux_sel_c_f3a_h (int_minmax_mux_sel_c_f3a_h),
    .fround_stky2l_f3a_h (fround_stky2l_f3a_h)
  );

  logic [15:0] all_outputs;
  assign all_outputs = {
    imxc_sel_f3a_h,
    res_snan_out_f3a_h,
    res_qnan_out_f3a_h,
    res_inf_out_f3a_h,
    res_neg_inf_out_f3a_h,
    comp_res_sel_f3a_h,
    fa_eq_fc_res_check_hi_f3a_h,
    eff_sub1_out_f3a_h,
    cmp_invalid_f3a_h,
    fma_subopc3_f3a_h,
    s_res_f3a_h,
    s_res_check_cadd_a3_f3a_h,
    int_minmax_mux_sel_a_f3a_h,
    int_minmax_mux_sel_c_f3a_h,
    fround_stky2l_f3a_h
  };

  assign out_chunk0_o = {{ 48{1'b0} }, all_outputs[15:0]};

endmodule : txfma_c3_tb
