EXTRA_SRC=../common/vm_boundary_common.cc ../common/trap_handler.S 

USE_STDLIB=1
EXTRA_LDFLAGS=-T../common/linker_sv48.ld
EXTRA_CFLAGS=-fno-threadsafe-statics
include $(MINION_DIAGS)/common/include.mk
