// Copyright (c) 2026 Ainekko
// SPDX-License-Identifier: Apache-2.0

`include "soc.vh"

module cosim_shire_xll_control_tb (
  input  logic clk_i,
  input  logic rst_ni,
  input  logic        esr_enable_i,
  input  logic        esr_reset_i,
  input  logic        esr_run_i,
  input  logic        esr_write_i,
  input  logic [5:0]  esr_reg_first_i,
  input  logic [3:0]  esr_reg_num_i,
  input  logic [1:0]  esr_pclk_sel_i,
  input  logic [255:0] esr_wdata_i,
  input  logic [15:0] prdata_i,
  input  logic        pready_i,
  output logic        orig_busy_o,
  output logic        new_busy_o,
  output logic        orig_rrdy_o,
  output logic        new_rrdy_o,
  output logic [15:0] orig_rdata_o,
  output logic [15:0] new_rdata_o,
  output logic        orig_pclk_o,
  output logic        new_pclk_o,
  output logic        orig_preset_no,
  output logic        new_preset_no,
  output logic [5:0]  orig_paddr_o,
  output logic [5:0]  new_paddr_o,
  output logic        orig_psel_o,
  output logic        new_psel_o,
  output logic        orig_penable_o,
  output logic        new_penable_o,
  output logic        orig_pwrite_o,
  output logic        new_pwrite_o,
  output logic [15:0] orig_pwdata_o,
  output logic [15:0] new_pwdata_o,
  output logic [1:0]  orig_pstrb_o,
  output logic [1:0]  new_pstrb_o
);

  shire_xll_control_orig u_orig (
    .clock         (clk_i),
    .reset         (!rst_ni),
    .esr_enable    (esr_enable_i),
    .esr_reset     (esr_reset_i),
    .esr_run       (esr_run_i),
    .esr_write     (esr_write_i),
    .esr_reg_first (esr_reg_first_i),
    .esr_reg_num   (esr_reg_num_i),
    .esr_pclk_sel  (esr_pclk_sel_i),
    .esr_wdata     (esr_wdata_i),
    .esr_busy      (orig_busy_o),
    .esr_rrdy      (orig_rrdy_o),
    .esr_rdata     (orig_rdata_o),
    .pclk          (orig_pclk_o),
    .preset_n      (orig_preset_no),
    .paddr         (orig_paddr_o),
    .psel          (orig_psel_o),
    .penable       (orig_penable_o),
    .pwrite        (orig_pwrite_o),
    .pwdata        (orig_pwdata_o),
    .pstrb         (orig_pstrb_o),
    .prdata        (prdata_i),
    .pready        (pready_i)
  );

  shire_xll_control u_new (
    .clk_i           (clk_i),
    .rst_ni          (rst_ni),
    .esr_enable_i    (esr_enable_i),
    .esr_reset_i     (esr_reset_i),
    .esr_run_i       (esr_run_i),
    .esr_write_i     (esr_write_i),
    .esr_reg_first_i (esr_reg_first_i),
    .esr_reg_num_i   (esr_reg_num_i),
    .esr_pclk_sel_i  (esr_pclk_sel_i),
    .esr_wdata_i     (esr_wdata_i),
    .esr_busy_o      (new_busy_o),
    .esr_rrdy_o      (new_rrdy_o),
    .esr_rdata_o     (new_rdata_o),
    .pclk_o          (new_pclk_o),
    .preset_no       (new_preset_no),
    .paddr_o         (new_paddr_o),
    .psel_o          (new_psel_o),
    .penable_o       (new_penable_o),
    .pwrite_o        (new_pwrite_o),
    .pwdata_o        (new_pwdata_o),
    .pstrb_o         (new_pstrb_o),
    .prdata_i        (prdata_i),
    .pready_i        (pready_i)
  );
endmodule
