// Copyright (c) 2026 Ainekko
// SPDX-License-Identifier: Apache-2.0

`include "soc.vh"

//  If you want to add custom statements, add them between the comments
//  CUSTOM XXX BEGIN and CUSTOM XXX END with XXX=PORTS,STATEMENTS,POST_DECODE
//  or SIGNALS
//  Otherwise, if file is updated with new template, they will be lost

module esr_memshire
  # ( 
    //////////////////////////////////////////////////////////////////////    
    // CUSTOM PARAMS BEGIN 
    // CUSTOM PARAMS END
    //////////////////////////////////////////////////////////////////////    
      parameter AD_WIDTH = 4,
      parameter SETS_PER_SUB_BANK = `SC_SETS_PER_SUB_BANK,
      parameter NUM_REQQ_ENTRIES = `SC_REQQ_DEPTH
      )
   (
    //////////////////////////////////////////////////////////////
    // System signals
    //////////////////////////////////////////////////////////////
    input logic                         clock,
    input logic                         reset_c,
    input logic                         reset_w,
    input logic                         reset_d,
    input logic                         test_en,
    
    //////////////////////////////////////////////////////////////////////
    // BEGIN autogenerated PORTS - do not edit manually

    // END autogenerated PORTS - do not edit manually   
    //////////////////////////////////////////////////////////////////////

    //////////////////////////////////////////////////////////////////////    
    // CUSTOM PORTS BEGIN 
    
    output memshire_esr_ctl_t           esr_memshire_ctl,
    input  memshire_esr_status_t        esr_memshire_status,

    // CUSTOM PORTS END
    //////////////////////////////////////////////////////////////////////    
    
    //////////////////////////////////////////////////////////////
    // APB slave interface
    //////////////////////////////////////////////////////////////
    // apb signals from master
    input [AD_WIDTH-1:0]                apb_paddr,
    input                               apb_pwrite, 
    input                               apb_psel, 
    input                               apb_penable,
    input [`ESR_APB_D_WIDTH-1:0]        apb_pwdata,
    
    // apb signals to master
    output logic                        apb_pready,
    output logic [`ESR_APB_D_WIDTH-1:0] apb_prdata,
    output logic                        apb_pslverr
    );
      
   ////////////////////////////////////////////////////////////////////////////////
   // SIGNAL declarations
   ////////////////////////////////////////////////////////////////////////////////
   
   // for APB slave
   logic                                       s0_en;
   logic                                       s0_addr_valid;
   logic [`ESR_APB_D_WIDTH-1:0]                s0_rdata;
   
   logic                                       s1_en;
   logic                                       s1_addr_valid;
   logic [`ESR_APB_D_WIDTH-1:0]                s1_rdata;
   logic [`ESR_APB_D_WIDTH-1:0]                s1_wdata;
   wire  [`ESR_APB_D_WIDTH-1:0]                apb_pwdata_1p = s1_wdata; // to be backward compatible to csr generation, could remove later if csr updates their scripts to use s1_wdata


   // CUSTOM SIGNALS BEGIN 
    
   // MANUAL registers assigned below
   // -----------------------------------------
   logic [`MEMSHIRE_ESR_STATUS_SIZE-1:0] esr_status_atomic_sm_ctl;
   logic [`MEMSHIRE_ESR_STATUS_SIZE-1:0] esr_status_mem_revision_id;
   logic [`MEMSHIRE_ESR_STATUS_SIZE-1:0] esr_status_mem_status;

   // CUSTOM SIGNALS END
   
   ////////////////////////////////////////////////////////////////////////////////
   // include autogenerated code from esr scripts
   ////////////////////////////////////////////////////////////////////////////////
`include "esr_memshire_auto.v"

   ////////////////////////////////////////////////////////////////////////////////
   // APB slave implementation
   ////////////////////////////////////////////////////////////////////////////////

   // s0: setup phase (address decoding + read)
   always_comb begin
      s0_en = apb_psel && ! apb_penable;
      s0_addr_valid = 1'b1;
      s0_rdata = '0;

      // set enables to 0 by default
      esr_read_and_decode_comb_default();
      
      // decode
      `esr_read_and_decode_comb_cases_memshire

      // CUSTOM POST_DECODE BEGIN
      // CUSTOM POST_DECODE END
   end

   // s1: access phase
   always_comb begin
      s1_en = apb_psel && apb_penable;
      
      // by default, keep the same value
      `esr_write_comb_default_memshire

      // update regs on write
      `esr_write_comb_memshire

      // CUSTOM POST_WRITE_COMB BEGIN
      // CUSTOM POST_WRITE_COMB END

   end
   
   `EN_FF(clock, s0_en &&  apb_pwrite, s1_wdata, apb_pwdata)
   `EN_FF(clock, s0_en && !apb_pwrite, s1_rdata, s0_rdata)
   `RST_EN_FF(clock, reset_c, s0_en, s1_addr_valid, s0_addr_valid, 1'b0)
   
   // assign APB slave outputs
   assign apb_prdata = s1_rdata;
   assign apb_pslverr = !s1_addr_valid;
   assign apb_pready = 1'b1;


   //////////////////////////////////////////////////////////////////////
   // CUSTOM STATEMENTS BEGIN 

   // assign reg fields to struct definitions to simplify assignments to single esr_memshire_ctl struct output
   esr_ms_mem_ctl_t               esr_ms_mem_ctl;
   esr_ms_clk_gate_ctl_t          esr_ms_clk_gate_ctl;

   assign esr_ms_mem_ctl            = reg_ms_mem_ctl;
   assign esr_ms_clk_gate_ctl       = reg_ms_clk_gate_ctl;

   // assign to common esr_memshire_ctl
   assign esr_memshire_ctl.esr_ms_mc_en                 = esr_ms_mem_ctl.esr_ms_mc_en;
   assign esr_memshire_ctl.esr_ms_addr_mask             = esr_ms_mem_ctl.esr_ms_addr_mask;
   assign esr_memshire_ctl.esr_ms_addr_debug_mc_bit_sel = esr_ms_mem_ctl.esr_ms_addr_debug_mc_bit_sel;
   assign esr_memshire_ctl.esr_ms_addr_mc_bit_sel       = esr_ms_mem_ctl.esr_ms_addr_mc_bit_sel;
   assign esr_memshire_ctl.esr_ms_addr_remove_bit_sel3  = esr_ms_mem_ctl.esr_ms_addr_remove_bit_sel3;
   assign esr_memshire_ctl.esr_ms_addr_remove_bit_sel2  = esr_ms_mem_ctl.esr_ms_addr_remove_bit_sel2;
   assign esr_memshire_ctl.esr_ms_addr_remove_bit_sel1  = esr_ms_mem_ctl.esr_ms_addr_remove_bit_sel1;
   assign esr_memshire_ctl.esr_ms_addr_remove_bit_sel0  = esr_ms_mem_ctl.esr_ms_addr_remove_bit_sel0;
   assign esr_memshire_ctl.esr_ms_clk_disable_debug     = esr_ms_clk_gate_ctl.debug_clock_disable;

   // manual esr ctl
   assign esr_memshire_ctl.wr_en_ms_atomic_sm_ctl   = reg_ms_atomic_sm_ctl_en;
   assign esr_memshire_ctl.wr_data                  = s1_wdata;

   // manual esr status
   assign esr_status_atomic_sm_ctl         = esr_memshire_status.atomic_sm;
   assign esr_status_mem_revision_id       = esr_memshire_status.mem_revision_id;  
   assign esr_status_mem_status            = esr_memshire_status.mem_status;  


   // Lint
   wire unused_ok = &{
`ifndef ET_ASCENT_LINT
                      1'b0,
`endif
                      reset_w,   // no warm reset ESRs
                      reset_d,   // no debug reset ESRs
                      test_en,
                      &SETS_PER_SUB_BANK,
                      &NUM_REQQ_ENTRIES
                      };


   // CUSTOM STATEMENTS END 
   //////////////////////////////////////////////////////////////////////
endmodule
