// Copyright (c) 2026 Ainekko
// SPDX-License-Identifier: Apache-2.0


//////////////////////////////////////////////////////////////////////
// BEGIN autogenerated DECLARATIONS - do not edit manually   
// Neigh ESR
`ESR_DECLARATION_LATCH(minion_boot, `VA_SIZE)
`ESR_DECLARATION_LATCH_WITH_TYPE(mprot, esr_mprot_t)
`ESR_DECLARATION_WITH_TYPE(ipi_redirect_pc, esr_ipi_pc_t)
`ESR_DECLARATION_WITH_TYPE(hactrl, esr_hactrl_t)
`ESR_DECLARATION_WITH_TYPE(hastatus1, esr_hastatus1_t)
`ESR_DECLARATION_WITH_TYPE(pmu_ctrl, esr_pmu_ctrl_t)
`ESR_DECLARATION_WITH_TYPE(neigh_chicken, esr_neigh_chicken_t)
`ESR_DECLARATION_LATCH_WITH_TYPE(icache_err_log_ctl, esr_icache_err_log_ctl_t)
`ESR_DECLARATION_DEC_ONLY(icache_err_log_info)
`ESR_DECLARATION_DEC_ONLY(icache_sbe_dbe_counts)
`ESR_LATCH_RESET_DECLARATION(reset_c)
`ESR_LATCH_RESET_DECLARATION(reset_d)
`ESR_LATCH_P1_WDATA_DECLARATION

// END autogenerated DECLARATIONS
//////////////////////////////////////////////////////////////////////

function automatic void esr_read_and_decode_comb_default;
   begin
      //////////////////////////////////////////////////////////////////////
      // BEGIN autogenerated READ_AND_DECODE_COMB_DEFAULT - do not edit
      // Neigh ESR
      `ESR_DECODE_DEFAULT(minion_boot)
      `ESR_DECODE_DEFAULT(mprot)
      `ESR_DECODE_DEFAULT(ipi_redirect_pc)
      `ESR_DECODE_DEFAULT(hactrl)
      `ESR_DECODE_DEFAULT(hastatus1)
      `ESR_DECODE_DEFAULT(pmu_ctrl)
      `ESR_DECODE_DEFAULT(neigh_chicken)
      `ESR_DECODE_DEFAULT(icache_err_log_ctl)
      `ESR_DECODE_DEFAULT(icache_err_log_info)
      `ESR_DECODE_DEFAULT(icache_sbe_dbe_counts)
      // END autogenerated READ_AND_DECODE_COMB_DEFAULT - do not edit
      //////////////////////////////////////////////////////////////////////
   end
endfunction //


//function automatic void esr_read_and_decode_comb_cases;
//   begin
`define esr_read_and_decode_comb_cases_neigh \
     if(s0_en) begin \
         case (apb_paddr) \
           ////////////////////////////////////////////////////////////////////// \
           // BEGIN autogenerated READ_AND_DECODE_COMB_CASES - do not edit \
            // Neigh ESR \
            `ESR_DECODE_CASE(esr_neigh_ad_MINION_BOOT, minion_boot, reg_minion_boot) \
            `ESR_DECODE_CASE(esr_neigh_ad_MPROT, mprot, reg_mprot) \
            `ESR_DECODE_CASE(esr_neigh_ad_IPI_REDIRECT_PC, ipi_redirect_pc, reg_ipi_redirect_pc) \
            `ESR_DECODE_CASE(esr_neigh_ad_HACTRL, hactrl, reg_hactrl) \
            `ESR_DECODE_CASE_RO(esr_neigh_ad_HASTATUS0, esr_hastatus0_ip) \
            `ESR_DECODE_CASE(esr_neigh_ad_HASTATUS1, hastatus1, read_hastatus1) \
            `ESR_DECODE_CASE_RO(esr_neigh_ad_AND_OR_TREEL0, esr_and_or_treeL0_ip) \
            `ESR_DECODE_CASE(esr_neigh_ad_PMU_CTRL, pmu_ctrl, reg_pmu_ctrl) \
            `ESR_DECODE_CASE(esr_neigh_ad_NEIGH_CHICKEN, neigh_chicken, reg_neigh_chicken) \
            `ESR_DECODE_CASE(esr_neigh_ad_ICACHE_ERR_LOG_CTL, icache_err_log_ctl, reg_icache_err_log_ctl) \
            `ESR_DECODE_CASE(esr_neigh_ad_ICACHE_ERR_LOG_INFO, icache_err_log_info, reg_icache_err_log_info) \
            `ESR_DECODE_CASE_RO(esr_neigh_ad_ICACHE_ERR_LOG_ADDRESS, reg_icache_err_log_address) \
            `ESR_DECODE_CASE(esr_neigh_ad_ICACHE_SBE_DBE_COUNTS, icache_sbe_dbe_counts, reg_icache_sbe_dbe_counters) \
           // END autogenerated READ_AND_DECODE_COMB_CASES - do not edit \
           ////////////////////////////////////////////////////////////////////// \
           default: \
             s0_addr_valid = 1'b0; \
         endcase // case (apb_paddr) \
      end // if (s0_en) \
//   end
//endfunction 


//////////////////////////////////////////////////////////////////////
// BEGIN autogenerated READ_AND_DECODE_SEQ - do not edit
// Neigh ESR
`ESR_DECODE_SEQ(minion_boot)
`ESR_DECODE_SEQ(mprot)
`ESR_DECODE_SEQ(ipi_redirect_pc)
`ESR_DECODE_SEQ(hactrl)
`ESR_DECODE_SEQ(hastatus1)
`ESR_DECODE_SEQ(pmu_ctrl)
`ESR_DECODE_SEQ(neigh_chicken)
`ESR_DECODE_SEQ(icache_err_log_ctl)
`ESR_DECODE_SEQ(icache_err_log_info)
`ESR_DECODE_SEQ(icache_sbe_dbe_counts)
// END autogenerated READ_AND_DECODE_SEQ
//////////////////////////////////////////////////////////////////////


//function  automatic void esr_write_comb_default;
//   begin
`define esr_write_comb_default_neigh \
      ////////////////////////////////////////////////////////////////////// \
      // BEGIN autogenerated WRITE_COMB_DEFAULT - do not edit \
      // Neigh ESR \
      `ESR_WRITE_LATCH_CLK_EN_ZERO(minion_boot) \
      `ESR_WRITE_LATCH_CLK_EN_ZERO(mprot) \
      `ESR_WRITE_COMB_DEFAULT(ipi_redirect_pc) \
      `ESR_WRITE_COMB_DEFAULT(hactrl) \
      `ESR_WRITE_COMB_DEFAULT(hastatus1) \
      `ESR_WRITE_COMB_DEFAULT(pmu_ctrl) \
      `ESR_WRITE_COMB_DEFAULT(neigh_chicken) \
      `ESR_WRITE_LATCH_CLK_EN_ZERO(icache_err_log_ctl) \
      // END autogenerated WRITE_COMB_DEFAULT - do not edit \
      ////////////////////////////////////////////////////////////////////// \
//   end
//endfunction //


//function automatic void esr_write_comb;
//   begin
`define esr_write_comb_neigh \
      ////////////////////////////////////////////////////////////////////// \
      // BEGIN autogenerated WRITE_CORE_COMB - do not edit \
 \
      // WRITE_COMB for regs that shadow some other reg \
 \
      // WRITE_COMB for the other regs \
      // Neigh ESR \
      `ESR_WRITE_COMB_LATCH(minion_boot, apb_pwdata_1p[`VA_SIZE-1:0]) \
      `ESR_WRITE_COMB_LATCH(mprot, apb_pwdata_1p[$bits(esr_mprot_t)-1:0]) \
      `ESR_WRITE_COMB(ipi_redirect_pc, write_ipi_pc(apb_pwdata[$bits(esr_ipi_pc_t)-1:0])) \
      `ESR_WRITE_COMB(hactrl, write_hactrl(apb_pwdata[$bits(esr_hactrl_t)-1:0])) \
      `ESR_WRITE_COMB(hastatus1, write_hastatus1(apb_pwdata[$bits(esr_hastatus1_t)-1:0])) \
      `ESR_WRITE_COMB(pmu_ctrl, apb_pwdata[$bits(esr_pmu_ctrl_t)-1:0]) \
      `ESR_WRITE_COMB(neigh_chicken, apb_pwdata[$bits(esr_neigh_chicken_t)-1:0]) \
      `ESR_WRITE_COMB_LATCH(icache_err_log_ctl, apb_pwdata_1p[$bits(esr_icache_err_log_ctl_t)-1:0]) \
      // END autogenerated WRITE_CORE_COMB - do not edit \
      ////////////////////////////////////////////////////////////////////// \
//   end
//endfunction //



//////////////////////////////////////////////////////////////////////
// BEGIN autogenerated WRITE_SEQ - do not edit
   // Neigh ESR
`ESR_WRITE_LATCH_RST(clock, minion_boot, minion_boot, minion_boot_next, `ESR_NEIGH_MINION_BOOT_RESET_VAL)
`ESR_WRITE_LATCH_RST(clock, mprot, mprot_pre, mprot_next, `MPROT_RESET_VAL)
`ESR_WRITE_TYPE_WITH_RESERVED(mprot, esr_mprot_t')
`ESR_WRITE_SEQ_RST_ND(clock, ipi_redirect_pc_pre, ipi_redirect_pc_next, '0)
`ESR_WRITE_TYPE_WITH_RESERVED(ipi_redirect_pc, write_ipi_pc_non_reserved)
`ESR_WRITE_SEQ_RST_D(clock, hactrl_pre, hactrl_next, '0)
`ESR_WRITE_TYPE_WITH_RESERVED(hactrl, esr_hactrl_t')
`ESR_WRITE_SEQ_RST_D(clock, hastatus1_pre, hastatus1_next, '0)
`ESR_WRITE_TYPE_WITH_RESERVED(hastatus1, esr_hastatus1_t')
`ESR_WRITE_SEQ_RST(clock, pmu_ctrl_pre, pmu_ctrl_next, '0)
`ESR_WRITE_TYPE_WITH_RESERVED(pmu_ctrl, esr_pmu_ctrl_t')
`ESR_WRITE_SEQ_RST(clock, neigh_chicken_pre, neigh_chicken_next, '0)
`ESR_WRITE_TYPE_WITH_RESERVED(neigh_chicken, esr_neigh_chicken_t')
`ESR_WRITE_LATCH_RST(clock, icache_err_log_ctl, icache_err_log_ctl_pre, icache_err_log_ctl_next, `ESR_ICACHE_ERR_LOG_CTL_RESET_VAL)
`ESR_WRITE_TYPE_WITH_RESERVED(icache_err_log_ctl, esr_icache_err_log_ctl_t')
// END autogenerated WRITE_SEQ
//////////////////////////////////////////////////////////////////////


//////////////////////////////////////////////////////////////////////
// BEGIN autogenerated PORT_ASSIGN - do not edit
   // Neigh ESR
   assign esr_minion_boot_op = reg_minion_boot;
   assign esr_mprot_op = reg_mprot;
   assign esr_ipi_redirect_pc_op = reg_ipi_redirect_pc;
   assign esr_hactrl_op = reg_hactrl;
   assign esr_pmu_ctrl_op = reg_pmu_ctrl;
   assign esr_neigh_chicken_op = reg_neigh_chicken;
   assign esr_icache_err_log_ctl_op = reg_icache_err_log_ctl;
// END autogenerated PORT_ASSIGN - do not edit
//////////////////////////////////////////////////////////////////////

//////////////////////////////////////////////////////////////////////
// BEGIN autogenerated TYPE_CONVERSIONS - do not edit
   //conversion functions for esr_hactrl_t
   function automatic esr_hactrl_t write_hactrl;
   input [$bits(esr_hactrl_t)-1:0] d;
   esr_hactrl_t dd;
   esr_hactrl_t ret;
   begin
      dd = esr_hactrl_t'(d);
      ret.hawindow = dd.hawindow;
      ret.hartmask = dd.hartmask;
      ret.resethalt = 'x; // RO field... needs to be set manually if used
      return ret;
   end
   endfunction

   //conversion functions for esr_hastatus1_t
   function automatic esr_hastatus1_t write_hastatus1;
   input [$bits(esr_hastatus1_t)-1:0] d;
   esr_hastatus1_t dd;
   esr_hastatus1_t ret;
   begin
      dd = esr_hastatus1_t'(d);
      ret.busy = 'x; // RO field... needs to be set manually if used
      ret.exception = dd.exception;
      ret.error = dd.error;
      return ret;
   end
   endfunction

   //conversion functions for esr_ipi_pc_t
   function automatic esr_ipi_pc_t write_ipi_pc;
   input [$bits(esr_ipi_pc_t)-1:0] d;
   esr_ipi_pc_t dd;
   esr_ipi_pc_t ret;
   begin
      dd = esr_ipi_pc_t'(d);
      ret.reserved0 = '0; 
      ret.address_msb = dd.address_msb;
      return ret;
   end
   endfunction

   function automatic esr_ipi_pc_t write_ipi_pc_non_reserved;
   input esr_ipi_pc_t d;
   esr_ipi_pc_t ret;
   begin
      ret.reserved0 = '0; 
      ret.address_msb = d.address_msb;
      return ret;
   end
   endfunction
// END autogenerated TYPE_CONVERSIONS
//////////////////////////////////////////////////////////////////////

