// Copyright (c) 2026 Ainekko
// SPDX-License-Identifier: Apache-2.0

`include "soc.vh"

//  If you want to add custom statements, add them between the comments
//  CUSTOM XXX BEGIN and CUSTOM XXX END with XXX=PORTS,STATEMENTS,POST_DECODE
//  or SIGNALS
//  Otherwise, if file is updated with new template, they will be lost

module esr_shire_other
  # (
    //////////////////////////////////////////////////////////////////////
    // CUSTOM PARAMS BEGIN
      parameter NUM_BANKS = `SC_BANKS,
      parameter NUM_NEIGH = `NUM_NEIGH,
    // CUSTOM PARAMS END
    //////////////////////////////////////////////////////////////////////
      parameter AD_WIDTH = 4,
      parameter SETS_PER_SUB_BANK = `SC_SETS_PER_SUB_BANK,
      parameter NUM_REQQ_ENTRIES = `SC_REQQ_DEPTH
      )
   (
    //////////////////////////////////////////////////////////////
    // System signals
    //////////////////////////////////////////////////////////////
    input logic                         clock,
    input logic                         reset_c,
    input logic                         reset_w,
    input logic                         reset_d,
    input logic                         test_en,

    //////////////////////////////////////////////////////////////////////
    // BEGIN autogenerated PORTS - do not edit manually
   // Shire Other
   output esr_minion_features_t esr_minion_feature_op,
   output logic [15:0] esr_ipi_trigger_op,
   output logic [0:0] esr_shire_coop_mode_op,
   output esr_clk_gate_ctrl_t esr_clk_gate_ctrl_op,
   output esr_sm_config_t esr_sm_config_op,

    // END autogenerated PORTS - do not edit manually
    //////////////////////////////////////////////////////////////////////

    //////////////////////////////////////////////////////////////////////
    // CUSTOM PORTS BEGIN

    output icache_prefetch_conf_t     esr_icache_prefetch_conf,
    output logic                      esr_icache_prefetch_start,
    input  logic                      esr_icache_prefetch_done,
    output logic [`MIN_PER_N-1:0]     esr_thread0_enable,
    output logic [`MIN_PER_N-1:0]     esr_thread1_enable,
    output logic [15:0]               esr_ipi_redirect_trigger_op,
    input  cpu_clint_timer_regs_t     esr_timer_regs_read_ip,
    output cpu_clint_timer_regs_t     esr_timer_regs_write_op,
    output cpu_clint_timer_regs_we_t  esr_timer_regs_we_op,
    input  uc_esr_values_t            uc_esr_values,
    output uc_esr_enable_sigs         uc_esr_enables,
    output esr_ms_dmctrl_t            esr_dmctrl_op,

    // DFT signals
    input  logic dft__reset_byp,     //Reset byp
    input  logic dft__reset,         //DFT mode reset

    //status monitor ports
    input logic [63:0] esr_sm_match,
    input logic [63:0] esr_sm_filter0,
    input logic [63:0] esr_sm_filter1,
    input logic [63:0] esr_sm_filter2,
    input logic [63:0] esr_sm_data0,
    input logic [63:0] esr_sm_data1,

    // CUSTOM PORTS END
    //////////////////////////////////////////////////////////////////////

    //////////////////////////////////////////////////////////////
    // APB slave interface
    //////////////////////////////////////////////////////////////
    // apb signals from master
    input [AD_WIDTH-1:0]                apb_paddr,
    input                               apb_pwrite,
    input                               apb_psel,
    input                               apb_penable,
    input [`ESR_APB_D_WIDTH-1:0]        apb_pwdata,

    // apb signals to master
    output logic                        apb_pready,
    output logic [`ESR_APB_D_WIDTH-1:0] apb_prdata,
    output logic                        apb_pslverr
    );

   ////////////////////////////////////////////////////////////////////////////////
   // SIGNAL declarations
   ////////////////////////////////////////////////////////////////////////////////

   // for APB slave
   logic                                       s0_en;
   logic                                       s0_addr_valid;
   logic [`ESR_APB_D_WIDTH-1:0]                s0_rdata;

   logic                                       s1_en;
   logic                                       s1_addr_valid;
   logic [`ESR_APB_D_WIDTH-1:0]                s1_rdata;
   logic [`ESR_APB_D_WIDTH-1:0]                s1_wdata;
   // CUSTOM SIGNALS BEGIN
    logic                                       features_written;
    logic [`CSR_PRV_LEVELS-1:0]                 icache_prv_prefetch_pending;
    logic [`CSR_PRV_LEVELS-1:0]                 icache_prv_prefetch_pending_next;
    logic [`CSR_PRV_LEVELS-1:0]                 icache_prv_prefetch_serve;
    icache_prefetch_conf_t                      esr_icache_prefetch_conf_next;
    logic                                       esr_icache_prefetch_start_next;
    logic                                       icache_prefetch_idle;
    logic                                       icache_prefetch_idle_next;
    logic                                       esr_icache_prefetch_done_reg;
    logic                                       icache_prefetch_busy;
    logic                                       icache_prefetch_busy_next;

    logic [`BARRIER_REGISTERS-1:0][63:0] fast_local_barrier;

    logic [2*NUM_NEIGH+2*NUM_BANKS-1:0]         shire_err_log_rd_value;
   
    esr_dmctrl_t                                dmctrl_read;

    logic [63:0]                                mtime_read;
    logic [63:0]                                mtimecmp_read;
    esr_time_config_t                           time_config_read;
    logic [`THREADS_PER_N-1:0]                  mtime_local_target_read;

    logic [63:0]                                reg_sm_match;
    logic [63:0]                                reg_sm_filter0;
    logic [63:0]                                reg_sm_filter1;
    logic [63:0]                                reg_sm_filter2;
    logic [63:0]                                reg_sm_data0;
    logic [63:0]                                reg_sm_data1;
   

   // CUSTOM SIGNALS END

   ////////////////////////////////////////////////////////////////////////////////
   // include autogenerated code from esr scripts
   ////////////////////////////////////////////////////////////////////////////////
`include "esr_shire_other_auto.v"

   ////////////////////////////////////////////////////////////////////////////////
   // APB slave implementation
   ////////////////////////////////////////////////////////////////////////////////

   // s0: setup phase (address decoding + read)
   always_comb begin
      s0_en = apb_psel && ! apb_penable;
      s0_addr_valid = 1'b1;
      s0_rdata = '0;

      // set enables to 0 by default
      esr_read_and_decode_comb_default();

      // decode
      `esr_read_and_decode_comb_cases_shire_other

      // CUSTOM POST_DECODE BEGIN
      // disable writing to feature, if it has already been writen once
      reg_minion_feature_en_next &= ~features_written;
      // CUSTOM POST_DECODE END
   end

   // s1: access phase
   always_comb begin
      s1_en = apb_psel && apb_penable;

      // by default, keep the same value
      `esr_write_comb_default_shire_other

      // update regs on write
      `esr_write_comb_shire_other

      // CUSTOM POST_WRITE_COMB BEGIN

        // IPI: a write to ipi_trigger register, sets bits in trigger register
      if ( reg_ipi_trigger_en == 1'b1      ) reg_ipi_trigger_next = (apb_pwdata[15:0] | reg_ipi_trigger)  ;
        // IPI: a write to ipi_trigger_clear register, clears bits in trigger register
      if ( reg_ipi_trigger_clear_en == 1'b1) reg_ipi_trigger_next = (~apb_pwdata[15:0] & reg_ipi_trigger) ;
      // dmctrl: legalize reserved fields
      reg_dmctrl_next.reserved2 = '0;
      reg_dmctrl_next.reserved1 = '0;
      reg_dmctrl_next.reserved0 = '0;
      // Keep reset value if dmactive == 0
      if (reg_dmctrl_en && !reg_dmctrl_next.dmactive) begin
         reg_dmctrl_next = esr_dmctrl_t'(`ESR_DMCTRL_RESET_VAL);
      end
      // // CUSTOM POST_WRITE_COMB END

   end

   `EN_FF(clock, s0_en &&  apb_pwrite, s1_wdata, apb_pwdata)
   `EN_FF(clock, s0_en && !apb_pwrite, s1_rdata, s0_rdata)
   `RST_EN_FF(clock, reset_c, s0_en, s1_addr_valid, s0_addr_valid, 1'b0)

   // assign APB slave outputs
   assign apb_prdata = s1_rdata;
   assign apb_pslverr = !s1_addr_valid;
   assign apb_pready = 1'b1;


   //////////////////////////////////////////////////////////////////////
   // CUSTOM STATEMENTS BEGIN

   // Rbox&Tbox run control
   // assign debug_rc_ss_tbox_rbox[`TBOX_PER_SHIRE-1:0]  = reg_tbox_rbox_dbg_rc.tbox_single_step;
   // assign debug_rc_ss_tbox_rbox[`TBOX_PER_SHIRE]      = reg_tbox_rbox_dbg_rc.rbox_single_step;

    // enabling 1st thread
    assign esr_thread0_enable = ~reg_thread0_disable[`MIN_PER_N-1:0];
    // enabling 2nd thread
    assign esr_thread1_enable = reg_minion_feature.disable_multithreading ? '0 : ~reg_thread1_disable[`MIN_PER_N-1:0];

    // feature can only be written once after reset
    `RST_EN_FF(clock, reset_c, reg_minion_feature_en, features_written, 1'b1, 1'b0)

    // UC signals

    genvar k;
    generate for(k = 0; k < `BARRIER_REGISTERS; ++k) begin: BARRIER
        assign fast_local_barrier[k] = {{(64-$bits(uc_esr_values.barriers[k])){1'b0}}, uc_esr_values.barriers[k]};
    end
    endgenerate

    assign uc_esr_enables.barriers[0]  = reg_fast_local_barrier0_en;
    assign uc_esr_enables.barriers[1]  = reg_fast_local_barrier1_en;
    assign uc_esr_enables.barriers[2]  = reg_fast_local_barrier2_en;
    assign uc_esr_enables.barriers[3]  = reg_fast_local_barrier3_en;
    assign uc_esr_enables.barriers[4]  = reg_fast_local_barrier4_en;
    assign uc_esr_enables.barriers[5]  = reg_fast_local_barrier5_en;
    assign uc_esr_enables.barriers[6]  = reg_fast_local_barrier6_en;
    assign uc_esr_enables.barriers[7]  = reg_fast_local_barrier7_en;
    assign uc_esr_enables.barriers[8]  = reg_fast_local_barrier8_en;
    assign uc_esr_enables.barriers[9]  = reg_fast_local_barrier9_en;
    assign uc_esr_enables.barriers[10] = reg_fast_local_barrier10_en;
    assign uc_esr_enables.barriers[11] = reg_fast_local_barrier11_en;
    assign uc_esr_enables.barriers[12] = reg_fast_local_barrier12_en;
    assign uc_esr_enables.barriers[13] = reg_fast_local_barrier13_en;
    assign uc_esr_enables.barriers[14] = reg_fast_local_barrier14_en;
    assign uc_esr_enables.barriers[15] = reg_fast_local_barrier15_en;
    assign uc_esr_enables.barriers[16] = reg_fast_local_barrier16_en;
    assign uc_esr_enables.barriers[17] = reg_fast_local_barrier17_en;
    assign uc_esr_enables.barriers[18] = reg_fast_local_barrier18_en;
    assign uc_esr_enables.barriers[19] = reg_fast_local_barrier19_en;
    assign uc_esr_enables.barriers[20] = reg_fast_local_barrier20_en;
    assign uc_esr_enables.barriers[21] = reg_fast_local_barrier21_en;
    assign uc_esr_enables.barriers[22] = reg_fast_local_barrier22_en;
    assign uc_esr_enables.barriers[23] = reg_fast_local_barrier23_en;
    assign uc_esr_enables.barriers[24] = reg_fast_local_barrier24_en;
    assign uc_esr_enables.barriers[25] = reg_fast_local_barrier25_en;
    assign uc_esr_enables.barriers[26] = reg_fast_local_barrier26_en;
    assign uc_esr_enables.barriers[27] = reg_fast_local_barrier27_en;
    assign uc_esr_enables.barriers[28] = reg_fast_local_barrier28_en;
    assign uc_esr_enables.barriers[29] = reg_fast_local_barrier29_en;
    assign uc_esr_enables.barriers[30] = reg_fast_local_barrier30_en;
    assign uc_esr_enables.barriers[31] = reg_fast_local_barrier31_en;

    assign uc_esr_enables.fcc[0] = reg_fcc_credinc_0_en;
    assign uc_esr_enables.fcc[1] = reg_fcc_credinc_1_en;
    assign uc_esr_enables.fcc[2] = reg_fcc_credinc_2_en;
    assign uc_esr_enables.fcc[3] = reg_fcc_credinc_3_en;

    ////////////////////////////////////////////////////////////////////////////////
    // Icache prefetch service
    ////////////////////////////////////////////////////////////////////////////////

    //      CLK    RST                                  DOUT                          DIN                               DEF
    `RST_FF(clock, reset_w,                             icache_prv_prefetch_pending,  icache_prv_prefetch_pending_next, '0)
    `EN_FF (clock,          |icache_prv_prefetch_serve, esr_icache_prefetch_conf,     esr_icache_prefetch_conf_next)
    `RST_FF(clock, reset_w,                             esr_icache_prefetch_start,    esr_icache_prefetch_start_next,   '0)
    `RST_FF(clock, reset_w,                             esr_icache_prefetch_done_reg, esr_icache_prefetch_done,         '1)
    `RST_FF(clock, reset_w,                             icache_prefetch_busy,         icache_prefetch_busy_next,        '0)
    `RST_FF(clock, reset_w,                             icache_prefetch_idle,         icache_prefetch_idle_next,        '1)

    // Annotate pending prefetches
    always_comb
    begin
        icache_prv_prefetch_pending_next = icache_prv_prefetch_pending;

        // u-prefetch
        if (reg_icache_uprefetch_en & reg_shire_coop_mode)
            icache_prv_prefetch_pending_next[`CSR_PRV_U] = 1'b1;
        else
            icache_prv_prefetch_pending_next[`CSR_PRV_U] = 1'b0;

        // s-prefetch
        if (reg_icache_sprefetch_en & reg_shire_coop_mode)
            icache_prv_prefetch_pending_next[`CSR_PRV_S] = 1'b1;
        else
            icache_prv_prefetch_pending_next[`CSR_PRV_S] = 1'b0;

        // m-prefetch
        if (reg_icache_mprefetch_en & reg_shire_coop_mode)
            icache_prv_prefetch_pending_next[`CSR_PRV_M] = 1'b1;
        else
            icache_prv_prefetch_pending_next[`CSR_PRV_M] = 1'b0;
    end

    // Serve pending prefetches
    // Prefetches are served on a privilege priority order
    // A specific privilege level prefetch is served only if there are not
    // higher-level prefetches pending or running
    assign icache_prv_prefetch_serve[`CSR_PRV_M] = icache_prv_prefetch_pending[`CSR_PRV_M];
    generate for (genvar p = `CSR_PRV_M-1; p >= signed'(`CSR_PRV_U); p--)
    begin : ICACHE_PREFETCH_SERVE
        assign icache_prv_prefetch_serve[p] = icache_prv_prefetch_pending[p]
                                            & (icache_prefetch_idle || (esr_icache_prefetch_conf.prv <= p[`CSR_PRV_SZ-1:0]));
    end
    endgenerate

    // Generate outputs
    always_comb
    begin
        esr_icache_prefetch_conf_next  = '0;
        esr_icache_prefetch_start_next = 1'b0;

        if (icache_prv_prefetch_serve[`CSR_PRV_M])
        begin
            esr_icache_prefetch_conf_next = '{prv: `CSR_PRV_M,
                                              start_addr: reg_icache_mprefetch.start_addr,
                                              num_lines: reg_icache_mprefetch.num_lines};
            esr_icache_prefetch_start_next = 1'b1;
        end
        else if (icache_prv_prefetch_serve[`CSR_PRV_S])
        begin
            esr_icache_prefetch_conf_next = '{prv: `CSR_PRV_S,
                                              start_addr: reg_icache_sprefetch.start_addr,
                                              num_lines: reg_icache_sprefetch.num_lines};
            esr_icache_prefetch_start_next = 1'b1;
        end
        else if (icache_prv_prefetch_serve[`CSR_PRV_U])
        begin
            esr_icache_prefetch_conf_next = '{prv: `CSR_PRV_U,
                                              start_addr: reg_icache_uprefetch.start_addr,
                                              num_lines: reg_icache_uprefetch.num_lines};
            esr_icache_prefetch_start_next = 1'b1;
        end
    end

    // Generate busy flag
    always_comb
    begin
        icache_prefetch_busy_next = icache_prefetch_busy;

        // Every time a start pulse is sent, reset busy flag
        if (esr_icache_prefetch_start_next)
            icache_prefetch_busy_next = 1'b0;
        // Detect that the start pulse was received when the done signal is cleared
        // and set busy flag
        else if (esr_icache_prefetch_done_reg && !esr_icache_prefetch_done)
            icache_prefetch_busy_next = 1'b1;
        // Detect that operation finished when the done signal is set
        // and clear busy flag
        else if (!esr_icache_prefetch_done_reg && esr_icache_prefetch_done)
            icache_prefetch_busy_next = 1'b0;
    end

    // Generate idle flag
    // Every time a start pulse is sent, idle flag is cleared
    // Detect that busy flag is cleared (and start pulse not sent) to set idle flag
    assign icache_prefetch_idle_next = (icache_prefetch_idle | (icache_prefetch_busy & ~icache_prefetch_busy_next)) & ~esr_icache_prefetch_start_next;

    ////////////////////////////////////////////////////////////////////////////////
    // IPI
    ////////////////////////////////////////////////////////////////////////////////
    //ipi redirect trigger : Write op to redirect_trigger reg generates a pulse int (mask & filter)
    assign esr_ipi_redirect_trigger_op = (reg_ipi_redirect_trigger_en)? reg_ipi_redirect_filter & apb_pwdata[15:0] : '0;

    ////////////////////////////////////////////////////////////////////////////////
    // CLINT
    ////////////////////////////////////////////////////////////////////////////////
    `RST_FF(clock, reset_c, esr_timer_regs_we_op.mtime, reg_mtime_en, '0); // push to sync-in fifo
    `RST_FF(clock, reset_c, esr_timer_regs_we_op.mtimecmp, reg_mtimecmp_en, '0);
    `RST_FF(clock, reset_c, esr_timer_regs_we_op.time_config, reg_time_config_en, '0);
    `RST_FF(clock, reset_c, esr_timer_regs_we_op.mtime_local_target, reg_mtime_local_target_en, '0);

    assign esr_timer_regs_write_op.mtime = reg_mtime; // push data to sync-in fifo
    assign esr_timer_regs_write_op.mtimecmp = reg_mtimecmp;
    assign esr_timer_regs_write_op.time_config = reg_time_config;
    assign esr_timer_regs_write_op.mtime_local_target = reg_mtime_local_target;

    assign mtime_read = esr_timer_regs_read_ip.mtime; // popped data from sync-out fifo
    assign mtimecmp_read = esr_timer_regs_read_ip.mtimecmp;
    assign time_config_read = esr_timer_regs_read_ip.time_config;
    assign mtime_local_target_read = esr_timer_regs_read_ip.mtime_local_target;

    // Lint
    wire unused_ok = &{
      `ifndef ET_ASCENT_LINT
       1'b0,
       `endif
       test_en,
       &SETS_PER_SUB_BANK,
       &NUM_REQQ_ENTRIES
    };

   ////////////////////////////////////////////////////////////////
   // dmctrl
   ////////////////////////////////////////////////////////////////
   logic        reg_dmctrl_en_z1;
   
   `FF(clock, reg_dmctrl_en_z1, reg_dmctrl_en)
   
   always_comb begin
      esr_dmctrl_op.dmactive = reg_dmctrl.dmactive;
      esr_dmctrl_op.ndmreset = reg_dmctrl.ndmreset;
      esr_dmctrl_op.clresethaltreq = reg_dmctrl.clrresethaltreq;
      esr_dmctrl_op.setresethaltreq = reg_dmctrl.setresethaltreq;
      esr_dmctrl_op.hasel = reg_dmctrl.hasel;
      esr_dmctrl_op.ackhavereset = reg_dmctrl.ackhavereset;
      esr_dmctrl_op.hartreset = reg_dmctrl.hartreset;
      esr_dmctrl_op.resumereq = reg_dmctrl.resumereq;
      esr_dmctrl_op.haltreq = reg_dmctrl.haltreq;
      esr_dmctrl_op.write_enable = reg_dmctrl_en_z1;
   end // always_comb

   // W1 fields and reserved should be driven by 0
   always_comb begin
      dmctrl_read = reg_dmctrl;
      dmctrl_read.clrresethaltreq = 1'b0;
      dmctrl_read.setresethaltreq = 1'b0;
      dmctrl_read.ackhavereset = 1'b0;
      dmctrl_read.resumereq = 1'b0;
      dmctrl_read.reserved0 = '0;
      dmctrl_read.reserved1 = '0;
      dmctrl_read.reserved2 = '0;            
   end
   

    ////////////////////////////////////////////////////////////////////////////////
    // Status monitor
    ////////////////////////////////////////////////////////////////////////////////
    // A write to sm_trigger register triggers a simultaneous snapshot captured in all the SM ESRs

    //         CLK    RST      EN                 DOUT            DIN             DEF
    `RST_EN_FF(clock, reset_c, reg_sm_trigger_en, reg_sm_match,   esr_sm_match,   '0)
    `RST_EN_FF(clock, reset_c, reg_sm_trigger_en, reg_sm_filter0, esr_sm_filter0, '0)
    `RST_EN_FF(clock, reset_c, reg_sm_trigger_en, reg_sm_filter1, esr_sm_filter1, '0)
    `RST_EN_FF(clock, reset_c, reg_sm_trigger_en, reg_sm_filter2, esr_sm_filter2, '0)
    `RST_EN_FF(clock, reset_c, reg_sm_trigger_en, reg_sm_data0,   esr_sm_data0,   '0)
    `RST_EN_FF(clock, reset_c, reg_sm_trigger_en, reg_sm_data1,   esr_sm_data1,   '0)

   // CUSTOM STATEMENTS END
   //////////////////////////////////////////////////////////////////////
endmodule
