// Copyright (c) 2026 Ainekko
// SPDX-License-Identifier: Apache-2.0

`include "soc.vh"

//  If you want to add custom statements, add them between the comments
//  CUSTOM XXX BEGIN and CUSTOM XXX END with XXX=PORTS,STATEMENTS,POST_DECODE
//  or SIGNALS
//  Otherwise, if file is updated with new template, they will be lost

module esr_neigh
  # ( 
    //////////////////////////////////////////////////////////////////////    
    // CUSTOM PARAMS BEGIN 
    // CUSTOM PARAMS END
    //////////////////////////////////////////////////////////////////////    
      parameter AD_WIDTH = 4,
      parameter SETS_PER_SUB_BANK = `SC_SETS_PER_SUB_BANK,
      parameter NUM_REQQ_ENTRIES = `SC_REQQ_DEPTH
      )
   (
    //////////////////////////////////////////////////////////////
    // System signals
    //////////////////////////////////////////////////////////////
    input logic                         clock,
    input logic                         reset_c,
    input logic                         reset_w,
    input logic                         reset_d,
    input logic                         test_en,
    
    //////////////////////////////////////////////////////////////////////
    // BEGIN autogenerated PORTS - do not edit manually
   // Neigh ESR
   output logic [`VA_SIZE-1:0] esr_minion_boot_op,
   output esr_mprot_t esr_mprot_op,
   output esr_ipi_pc_t esr_ipi_redirect_pc_op,
   output esr_hactrl_t esr_hactrl_op,
   input esr_hastatus0_t esr_hastatus0_ip,
   input esr_and_or_tree_L0_t esr_and_or_treeL0_ip,
   output esr_pmu_ctrl_t esr_pmu_ctrl_op,
   output esr_neigh_chicken_t esr_neigh_chicken_op,
   output esr_icache_err_log_ctl_t esr_icache_err_log_ctl_op,

    // END autogenerated PORTS - do not edit manually   
    //////////////////////////////////////////////////////////////////////

    //////////////////////////////////////////////////////////////////////    
    // CUSTOM PORTS BEGIN 
    //////////////////////////////////////////////////////////////////////
    input logic                 esr_icache_err_log_sbe_ip,
    input logic                 esr_icache_err_log_dbe_ip,
    input icache_err_log_info_t esr_icache_err_log_info_ip,
    output logic                esr_icache_err_detected_op,
    output logic                esr_icache_err_logged_op,
    output logic                esr_icache_ecc_count_ov_op,

    input  esr_hastatus1_t      esr_hastatus1_min,
    input  esr_ms_dmctrl_t      esr_dmctrl,
    
    // DFT signals
    input  logic                                       dft__reset_byp,     //Reset byp
    input  logic                                       dft__reset,         //DFT mode reset
    //////////////////////////////////////////////////////////////////////
    // CUSTOM PORTS END
    //////////////////////////////////////////////////////////////////////    
    
    //////////////////////////////////////////////////////////////
    // APB slave interface
    //////////////////////////////////////////////////////////////
    // apb signals from master
    input [AD_WIDTH-1:0]                apb_paddr,
    input                               apb_pwrite, 
    input                               apb_psel, 
    input                               apb_penable,
    input [`ESR_APB_D_WIDTH-1:0]        apb_pwdata,
    
    // apb signals to master
    output logic                        apb_pready,
    output logic [`ESR_APB_D_WIDTH-1:0] apb_prdata,
    output logic                        apb_pslverr
    );
      
   ////////////////////////////////////////////////////////////////////////////////
   // SIGNAL declarations
   ////////////////////////////////////////////////////////////////////////////////
   
   // for APB slave
   logic                                       s0_en;
   logic                                       s0_addr_valid;
   logic [`ESR_APB_D_WIDTH-1:0]                s0_rdata;
   
   logic                                       s1_en;
   logic                                       s1_addr_valid;
   logic [`ESR_APB_D_WIDTH-1:0]                s1_rdata;
   logic [`ESR_APB_D_WIDTH-1:0]                s1_wdata;
   // CUSTOM SIGNALS BEGIN 
   // Icache error logging
   esr_icache_err_log_info_t                                     reg_icache_err_log_info;
   esr_icache_err_log_info_t                                     reg_icache_err_log_info_next;
   esr_icache_err_log_info_t                                     icache_err_log_info_wdata;
   logic                                                         icache_err_log_info_clr;
   logic                                                         icache_err_log_info_new_err;
   icache_err_code_t                                             icache_err_log_info_new_err_code;
   logic                                                         icache_err_log_info_wr_en;
   logic                                                         icache_err_log_ecc_count_ov;
   logic [`PA_RANGE_CA]                                          reg_icache_err_log_address;
   logic [`PA_RANGE_CA]                                          reg_icache_err_log_address_next;
   logic                                                         icache_err_detected_next;
   logic                                                         icache_err_logged_next;
   logic [`ESR_ICACHE_DBE_CNT_SIZE+`ESR_ICACHE_SBE_CNT_SIZE-1:0] reg_icache_sbe_dbe_counters;
   logic [`ESR_ICACHE_SBE_CNT_SIZE-1:0]                          reg_icache_sbe_counter;
   logic [`ESR_ICACHE_SBE_CNT_SIZE-1:0]                          reg_icache_sbe_counter_next;
   logic                                                         icache_sbe_counter_ov;
   logic [`ESR_ICACHE_SBE_CNT_SIZE-1:0]                          icache_sbe_counter_wdata;
   logic                                                         icache_sbe_counter_clr;
   logic                                                         icache_sbe_counter_en;
   logic [`ESR_ICACHE_DBE_CNT_SIZE-1:0]                          reg_icache_dbe_counter;
   logic [`ESR_ICACHE_DBE_CNT_SIZE-1:0]                          reg_icache_dbe_counter_next;
   logic                                                         icache_dbe_counter_ov;
   logic [`ESR_ICACHE_DBE_CNT_SIZE-1:0]                          icache_dbe_counter_wdata;
   logic                                                         icache_dbe_counter_clr;
   logic                                                         icache_dbe_counter_en;

   esr_hastatus1_t                                               read_hastatus1;
   logic [`MIN_PER_N*`CORE_NR_THREADS - 1:0]                     hartSel;
   // CUSTOM SIGNALS END
   
   ////////////////////////////////////////////////////////////////////////////////
   // include autogenerated code from esr scripts
   ////////////////////////////////////////////////////////////////////////////////
`include "esr_neigh_auto.v"

   ////////////////////////////////////////////////////////////////////////////////
   // APB slave implementation
   ////////////////////////////////////////////////////////////////////////////////

   // s0: setup phase (address decoding + read)
   always_comb begin
      s0_en = apb_psel && ! apb_penable;
      s0_addr_valid = 1'b1;
      s0_rdata = '0;

      // set enables to 0 by default
      esr_read_and_decode_comb_default();
      
      // decode
      `esr_read_and_decode_comb_cases_neigh

      // CUSTOM POST_DECODE BEGIN
      // CUSTOM POST_DECODE END
   end

   // s1: access phase
   always_comb begin
      s1_en = apb_psel && apb_penable;
      
      // by default, keep the same value
      `esr_write_comb_default_neigh

      // update regs on write
      `esr_write_comb_neigh

      // CUSTOM POST_WRITE_COMB BEGIN
      reg_hastatus1_next.error |= esr_hastatus1_min.error;
      reg_hastatus1_next.exception |= esr_hastatus1_min.exception;
      for(int k = 0; k < `MIN_PER_N*`CORE_NR_THREADS;  ++k)  begin
        hartSel[k] = (esr_dmctrl.hasel && reg_hactrl.hawindow[k]) || reg_hactrl.hartmask[k];
        reg_hactrl_next[`HACTRL_RESETHALT_START+k] = reg_hactrl[`HACTRL_RESETHALT_START+k];
        if (esr_dmctrl.clresethaltreq && esr_dmctrl.write_enable && hartSel[k]) begin
          reg_hactrl_next[`HACTRL_RESETHALT_START+k] = 1'b0;
        end
        else if(esr_dmctrl.setresethaltreq && esr_dmctrl.write_enable && hartSel[k]) begin
          reg_hactrl_next[`HACTRL_RESETHALT_START+k] = 1'b1;
        end
      end
      // CUSTOM POST_WRITE_COMB END

   end

   `EN_FF(clock, s0_en &&  apb_pwrite, s1_wdata, apb_pwdata)
   `EN_FF(clock, s0_en && !apb_pwrite, s1_rdata, s0_rdata)
   `RST_EN_FF(clock, reset_c, s0_en, s1_addr_valid, s0_addr_valid, 1'b0)
   
   // assign APB slave outputs
   assign apb_prdata = s1_rdata;
   assign apb_pslverr = !s1_addr_valid;
   assign apb_pready = 1'b1;


   //////////////////////////////////////////////////////////////////////
   // CUSTOM STATEMENTS BEGIN 
   //////////////////////////////////////////////////////////////////////

   // ICACHE ERROR LOGGING
   // --------------------

   // Implement icache_err_log_info manually
   // --------------------------------------

   //         CLK    RST      EN                         DOUT                        DIN                              DEF
   `RST_EN_FF(clock, reset_w, icache_err_log_info_wr_en, reg_icache_err_log_info,    reg_icache_err_log_info_next,    '0)
   `RST_EN_FF(clock, reset_w, icache_err_log_info_wr_en, reg_icache_err_log_address, reg_icache_err_log_address_next, '0)

   // icache_err_log_info is cleared by writing 1'b1 to valid bit and matching code to error code
   assign icache_err_log_info_wdata = esr_icache_err_log_info_t'(s1_wdata);
   assign icache_err_log_info_clr   = reg_icache_err_log_info_en & icache_err_log_info_wdata.valid & (reg_icache_err_log_info.err_code==icache_err_log_info_wdata.err_code);

   assign icache_err_log_info_new_err      = esr_icache_err_log_sbe_ip | esr_icache_err_log_dbe_ip | icache_err_log_ecc_count_ov;
   assign icache_err_log_info_new_err_code = esr_icache_err_log_dbe_ip   ? icache_err_code_DBE
                                           : icache_err_log_ecc_count_ov ? icache_err_code_ECC_cnt_ov
                                           :                               icache_err_code_SBE;

   // icache_err_log_info is written with a new value when it is cleared
   // or when a new error is notified
   assign icache_err_log_info_wr_en = icache_err_log_info_clr | icache_err_log_info_new_err;

   always_comb
   begin
       reg_icache_err_log_info_next    = reg_icache_err_log_info;
       reg_icache_err_log_address_next = reg_icache_err_log_address;

       // Register is cleared
       if (icache_err_log_info_clr)
       begin
           reg_icache_err_log_info_next.enabled = 1'b0;
           reg_icache_err_log_info_next.multi   = 1'b0;
           reg_icache_err_log_info_next.valid   = 1'b0;
       end
       // New error is notified
       else if (icache_err_log_info_new_err)
       begin
           // New error only overwrites a previous one if that one was not valid or if it was disabled and
           // the new error is enabled
           if (~reg_icache_err_log_info.valid | (~reg_icache_err_log_info.enabled & reg_icache_err_log_ctl.err_interrupt_enable[icache_err_log_info_new_err_code]))
           begin
               reg_icache_err_log_address_next        = esr_icache_err_log_info_ip.address;
               reg_icache_err_log_info_next.dbe_ov    = icache_dbe_counter_ov;
               reg_icache_err_log_info_next.err_bits  = esr_icache_err_log_dbe_ip ? esr_icache_err_log_info_ip.dbe_per_block
                                                                                  : esr_icache_err_log_info_ip.sbe_per_block;
               reg_icache_err_log_info_next.way       = esr_icache_err_log_info_ip.way;
               reg_icache_err_log_info_next.set       = esr_icache_err_log_info_ip.set;
               reg_icache_err_log_info_next.err_code  = icache_err_log_info_new_err_code;
               // Imprecise flag is set if this error is enabled and Level 2 error responses are disabled
               // (otherwise, icache errors are always notified down to core)
               // IGA: imprecise flag removed
               //reg_icache_err_log_info_next.imprecise = reg_icache_err_log_ctl.err_interrupt_enable[icache_err_log_info_new_err_code]
               //                                       & ~reg_icache_err_log_ctl.err_rsp_enable;
           end
           // Enabled flag is set if this error is enabled, and it is not overwritten by a not enabled error
           reg_icache_err_log_info_next.enabled |= reg_icache_err_log_ctl.err_interrupt_enable[icache_err_log_info_new_err_code];
           // Multiple flag is set if there was an enabled error already
           // logged and this error is also enabled
           reg_icache_err_log_info_next.multi   |= reg_icache_err_log_info.valid & reg_icache_err_log_info.enabled
                                                 & reg_icache_err_log_ctl.err_interrupt_enable[icache_err_log_info_new_err_code];
           reg_icache_err_log_info_next.valid   = 1'b1;
       end
   end

   // ECC error counters
   // ------------------

   //         CLK    RST      EN                     DOUT                    DIN                          DEF
   `RST_EN_FF(clock, reset_w, icache_sbe_counter_en, reg_icache_sbe_counter, reg_icache_sbe_counter_next, '0)
   `RST_EN_FF(clock, reset_w, icache_dbe_counter_en, reg_icache_dbe_counter, reg_icache_dbe_counter_next, '0)

   // Counter overflow
   assign icache_sbe_counter_ov       = &reg_icache_sbe_counter;
   assign icache_dbe_counter_ov       = &reg_icache_dbe_counter;
   assign icache_err_log_ecc_count_ov = icache_sbe_counter_ov | icache_dbe_counter_ov;

   // Counters are cleared by writing all ones or matching counter value
   assign icache_sbe_counter_wdata = s1_wdata[0 +: `ESR_ICACHE_SBE_CNT_SIZE];
   assign icache_sbe_counter_clr   = reg_icache_sbe_dbe_counts_en && ((icache_sbe_counter_wdata == '1) || (icache_sbe_counter_wdata == reg_icache_sbe_counter));
   assign icache_dbe_counter_wdata = s1_wdata[`ESR_ICACHE_SBE_CNT_SIZE +: `ESR_ICACHE_DBE_CNT_SIZE];
   assign icache_dbe_counter_clr   = reg_icache_sbe_dbe_counts_en && ((icache_dbe_counter_wdata == '1) || (icache_dbe_counter_wdata == reg_icache_dbe_counter));

   // Counters are written when they are cleared or when a new error is notified (and overflow has not happened yet)
   assign icache_sbe_counter_en = icache_sbe_counter_clr || (esr_icache_err_log_sbe_ip && !icache_sbe_counter_ov);
   assign icache_dbe_counter_en = icache_dbe_counter_clr || (esr_icache_err_log_dbe_ip && !icache_dbe_counter_ov);

   always_comb
   begin
       reg_icache_sbe_counter_next = reg_icache_sbe_counter + 1'b1;
       reg_icache_dbe_counter_next = reg_icache_dbe_counter + 1'b1;

       // Counters are cleared
       if (icache_sbe_counter_clr)
           reg_icache_sbe_counter_next = '0;
       if (icache_dbe_counter_clr)
           reg_icache_dbe_counter_next = '0;
   end

   // Combine both counters to output
   assign reg_icache_sbe_dbe_counters = {reg_icache_dbe_counter,reg_icache_sbe_counter};
   
   // Generate icache_err_detected and icache_err_logged outputs
   // ----------------------------------------------------------

   //      CLK    RST      DOUT                        DIN                       DEF
   `RST_FF(clock, reset_w, esr_icache_err_detected_op, icache_err_detected_next, 1'b0)
   `RST_FF(clock, reset_w, esr_icache_err_logged_op,   icache_err_logged_next,   1'b0)

   assign icache_err_detected_next = 1'b0; // reg_icache_err_log_info.valid & reg_icache_err_log_info.enabled & reg_icache_err_log_info.imprecise; // IGA: imprecise bit removed
   assign icache_err_logged_next   = reg_icache_err_log_info.valid & reg_icache_err_log_info.enabled;

   // Generate icache_ecc_count_ov output to core
   // -------------------------------------------

   // ECC count overflow sent to core only if error is enabled and Level 2 error responses are also enabled
   // IGA: err_rsp_enable flag removed, errors are always notified to the core
   assign esr_icache_ecc_count_ov_op = icache_err_log_ecc_count_ov & reg_icache_err_log_ctl.err_interrupt_enable[icache_err_code_ECC_cnt_ov]; // & reg_icache_err_log_ctl.err_rsp_enable;

   // Lint
   wire unused_ok = &{
     `ifndef ET_ASCENT_LINT
      1'b0,
      `endif
      &SETS_PER_SUB_BANK,
      &NUM_REQQ_ENTRIES
   };
   
   always_comb begin
      read_hastatus1 = reg_hastatus1;
      read_hastatus1.busy = esr_hastatus1_min.busy;
   end

   ////////////////////////////////////////////////////////////////////// 
   // CUSTOM STATEMENTS END 
   //////////////////////////////////////////////////////////////////////
endmodule
