// Copyright (c) 2026 Ainekko
// SPDX-License-Identifier: Apache-2.0


//////////////////////////////////////////////////////////////////////
// BEGIN autogenerated DECLARATIONS - do not edit manually   
// MemShire ESRs
`ESR_DECLARATION_WITH_TYPE(ms_mem_ctl, esr_ms_mem_ctl_t)
`ESR_DECLARATION_DEC_ONLY(ms_atomic_sm_ctl)
`ESR_DECLARATION_WITH_TYPE(ms_clk_gate_ctl, esr_ms_clk_gate_ctl_t)

// END autogenerated DECLARATIONS
//////////////////////////////////////////////////////////////////////

function automatic void esr_read_and_decode_comb_default;
   begin
      //////////////////////////////////////////////////////////////////////
      // BEGIN autogenerated READ_AND_DECODE_COMB_DEFAULT - do not edit
      // MemShire ESRs
      `ESR_DECODE_DEFAULT(ms_mem_ctl)
      `ESR_DECODE_DEFAULT(ms_atomic_sm_ctl)
      `ESR_DECODE_DEFAULT(ms_clk_gate_ctl)
      // END autogenerated READ_AND_DECODE_COMB_DEFAULT - do not edit
      //////////////////////////////////////////////////////////////////////
   end
endfunction //


//function automatic void esr_read_and_decode_comb_cases;
//   begin
`define esr_read_and_decode_comb_cases_memshire \
      if(s0_en) begin \
         case (apb_paddr) \
           ////////////////////////////////////////////////////////////////////// \
           // BEGIN autogenerated READ_AND_DECODE_COMB_CASES - do not edit \
            // MemShire ESRs \
            `ESR_DECODE_CASE(esr_memshire_ad_MS_MEM_CTL, ms_mem_ctl, reg_ms_mem_ctl) \
            `ESR_DECODE_CASE(esr_memshire_ad_MS_ATOMIC_SM_CTL, ms_atomic_sm_ctl, esr_status_atomic_sm_ctl) \
            `ESR_DECODE_CASE_RO(esr_memshire_ad_MS_MEM_REVISION_ID, esr_status_mem_revision_id) \
            `ESR_DECODE_CASE(esr_memshire_ad_MS_CLK_GATE_CTL, ms_clk_gate_ctl, reg_ms_clk_gate_ctl) \
            `ESR_DECODE_CASE_RO(esr_memshire_ad_MS_MEM_STATUS, esr_status_mem_status) \
           // END autogenerated READ_AND_DECODE_COMB_CASES - do not edit \
           ////////////////////////////////////////////////////////////////////// \
           default: \
             s0_addr_valid = 1'b0; \
         endcase // case (apb_paddr) \
      end // if (s0_en) \
//   end
//endfunction 


//////////////////////////////////////////////////////////////////////
// BEGIN autogenerated READ_AND_DECODE_SEQ - do not edit
// MemShire ESRs
`ESR_DECODE_SEQ(ms_mem_ctl)
`ESR_DECODE_SEQ(ms_atomic_sm_ctl)
`ESR_DECODE_SEQ(ms_clk_gate_ctl)
// END autogenerated READ_AND_DECODE_SEQ
//////////////////////////////////////////////////////////////////////


//function  automatic void esr_write_comb_default;
//   begin
`define esr_write_comb_default_memshire \
      ////////////////////////////////////////////////////////////////////// \
      // BEGIN autogenerated WRITE_COMB_DEFAULT - do not edit \
      // MemShire ESRs \
      `ESR_WRITE_COMB_DEFAULT(ms_mem_ctl) \
      `ESR_WRITE_COMB_DEFAULT(ms_clk_gate_ctl) \
      // END autogenerated WRITE_COMB_DEFAULT - do not edit \
      ////////////////////////////////////////////////////////////////////// \
//   end 
//endfunction // 


//function automatic void esr_write_comb;
//   begin
`define esr_write_comb_memshire \
      ////////////////////////////////////////////////////////////////////// \
      // BEGIN autogenerated WRITE_CORE_COMB - do not edit \
 \
      // WRITE_COMB for regs that shadow some other reg \
 \
      // WRITE_COMB for the other regs \
      // MemShire ESRs \
      `ESR_WRITE_COMB(ms_mem_ctl, apb_pwdata[$bits(esr_ms_mem_ctl_t)-1:0]) \
      `ESR_WRITE_COMB(ms_clk_gate_ctl, apb_pwdata[$bits(esr_ms_clk_gate_ctl_t)-1:0]) \
      // END autogenerated WRITE_CORE_COMB - do not edit \
      ////////////////////////////////////////////////////////////////////// \
//   end
//endfunction //



//////////////////////////////////////////////////////////////////////
// BEGIN autogenerated WRITE_SEQ - do not edit
   // MemShire ESRs
`ESR_WRITE_SEQ_RST(clock, ms_mem_ctl_pre, ms_mem_ctl_next, `ESR_MS_MEM_CTL_RESET_VAL)
`ESR_WRITE_TYPE_WITH_RESERVED(ms_mem_ctl, esr_ms_mem_ctl_t')
`ESR_WRITE_SEQ_RST_D(clock, ms_clk_gate_ctl_pre, ms_clk_gate_ctl_next, `ESR_MS_CLK_GATE_CTL_RESET_VAL)
`ESR_WRITE_TYPE_WITH_RESERVED(ms_clk_gate_ctl, esr_ms_clk_gate_ctl_t')
// END autogenerated WRITE_SEQ
//////////////////////////////////////////////////////////////////////


//////////////////////////////////////////////////////////////////////
// BEGIN autogenerated PORT_ASSIGN - do not edit
// END autogenerated PORT_ASSIGN - do not edit
//////////////////////////////////////////////////////////////////////

//////////////////////////////////////////////////////////////////////
// BEGIN autogenerated TYPE_CONVERSIONS - do not edit
// END autogenerated TYPE_CONVERSIONS
//////////////////////////////////////////////////////////////////////

