// Copyright (c) 2026 Ainekko
// SPDX-License-Identifier: Apache-2.0

`include "soc.vh"

//  If you want to add custom statements, add them between the comments
//  CUSTOM XXX BEGIN and CUSTOM XXX END with XXX=PORTS,STATEMENTS,POST_DECODE
//  or SIGNALS
//  Otherwise, if file is updated with new template, they will be lost

module esr_rbox
  # ( 
    //////////////////////////////////////////////////////////////////////    
    // CUSTOM PARAMS BEGIN 
    // CUSTOM PARAMS END
    //////////////////////////////////////////////////////////////////////    
      parameter AD_WIDTH = 4,
      parameter SETS_PER_SUB_BANK = `SC_SETS_PER_SUB_BANK,
      parameter NUM_REQQ_ENTRIES = `SC_REQQ_DEPTH
      )
   (
    //////////////////////////////////////////////////////////////
    // System signals
    //////////////////////////////////////////////////////////////
    input logic                         clock,
    input logic                         reset_c,
    input logic                         reset_w,
    input logic                         reset_d,
    input logic                         test_en,
    
    //////////////////////////////////////////////////////////////////////
    // BEGIN autogenerated PORTS - do not edit manually
   // RBOX ESRs
   output logic [63:0] esr_rbox_config_op,
   output logic [63:0] esr_rbox_in_buf_pg_op,
   output logic [63:0] esr_rbox_in_buf_cfg_op,
   output logic [31:0] esr_rbox_out_buf_pg_op,
   output logic [63:0] esr_rbox_out_buf_cfg_op,
   input logic [31:0] esr_rbox_status_ip,
   output logic [31:0] esr_rbox_start_op,
   output logic [31:0] esr_rbox_consume_op,

    // END autogenerated PORTS - do not edit manually   
    //////////////////////////////////////////////////////////////////////

    //////////////////////////////////////////////////////////////////////    
    // CUSTOM PORTS BEGIN 
    output logic esr_rbox_config_en,
    output logic esr_rbox_in_buf_pg_en,
    output logic esr_rbox_in_buf_cfg_en,
    output logic esr_rbox_out_buf_pg_en,
    output logic esr_rbox_out_buf_cfg_en,
    output logic esr_rbox_start_en,
    output logic esr_rbox_consume_en,
    // CUSTOM PORTS END
    //////////////////////////////////////////////////////////////////////    
    
    //////////////////////////////////////////////////////////////
    // APB slave interface
    //////////////////////////////////////////////////////////////
    // apb signals from master
    input [AD_WIDTH-1:0]                apb_paddr,
    input                               apb_pwrite, 
    input                               apb_psel, 
    input                               apb_penable,
    input [`ESR_APB_D_WIDTH-1:0]        apb_pwdata,
    
    // apb signals to master
    output logic                        apb_pready,
    output logic [`ESR_APB_D_WIDTH-1:0] apb_prdata,
    output logic                        apb_pslverr
    );
      
   ////////////////////////////////////////////////////////////////////////////////
   // SIGNAL declarations
   ////////////////////////////////////////////////////////////////////////////////
   
   // for APB slave
   logic                                       s0_en;
   logic                                       s0_addr_valid;
   logic [`ESR_APB_D_WIDTH-1:0]                s0_rdata;
   
   logic                                       s1_en;
   logic                                       s1_addr_valid;
   logic [`ESR_APB_D_WIDTH-1:0]                s1_rdata;
   logic [`ESR_APB_D_WIDTH-1:0]                s1_wdata;
   // CUSTOM SIGNALS BEGIN 
   // CUSTOM SIGNALS END
   
   ////////////////////////////////////////////////////////////////////////////////
   // include autogenerated code from esr scripts
   ////////////////////////////////////////////////////////////////////////////////
`include "esr_rbox_auto.v"

   ////////////////////////////////////////////////////////////////////////////////
   // APB slave implementation
   ////////////////////////////////////////////////////////////////////////////////

   // s0: setup phase (address decoding + read)
   always_comb begin
      s0_en = apb_psel && ! apb_penable;
      s0_addr_valid = 1'b1;
      s0_rdata = '0;

      // set enables to 0 by default
      esr_read_and_decode_comb_default();
      
      // decode
      `esr_read_and_decode_comb_cases_rbox

      // CUSTOM POST_DECODE BEGIN
      // CUSTOM POST_DECODE END
   end

   // s1: access phase
   always_comb begin
      s1_en = apb_psel && apb_penable;
      
      // by default, keep the same value
      `esr_write_comb_default_rbox

      // update regs on write
      `esr_write_comb_rbox

      // CUSTOM POST_WRITE_COMB BEGIN
      // CUSTOM POST_WRITE_COMB END

   end

   `EN_FF(clock, s0_en &&  apb_pwrite, s1_wdata, apb_pwdata)
   `EN_FF(clock, s0_en && !apb_pwrite, s1_rdata, s0_rdata)
   `RST_EN_FF(clock, reset_c, s0_en, s1_addr_valid, s0_addr_valid, 1'b0)
   
   // assign APB slave outputs
   assign apb_prdata = s1_rdata;
   assign apb_pslverr = !s1_addr_valid;
   assign apb_pready = 1'b1;


   //////////////////////////////////////////////////////////////////////
   // CUSTOM STATEMENTS BEGIN 

   logic esr_rbox_config_en_ff;
   logic esr_rbox_config_en_nxt;
   logic esr_rbox_in_buf_pg_en_ff;
   logic esr_rbox_in_buf_pg_en_nxt;
   logic esr_rbox_in_buf_cfg_en_ff;
   logic esr_rbox_in_buf_cfg_en_nxt;
   logic esr_rbox_out_buf_pg_en_ff;
   logic esr_rbox_out_buf_pg_en_nxt;
   logic esr_rbox_out_buf_cfg_en_ff;
   logic esr_rbox_out_buf_cfg_en_nxt;
   logic esr_rbox_start_en_ff;
   logic esr_rbox_start_en_nxt;
   logic esr_rbox_consume_en_ff;
   logic esr_rbox_consume_en_nxt;

   `RST_FF(clock, reset_w, esr_rbox_config_en_ff,      esr_rbox_config_en_nxt,      1'b0)
   `RST_FF(clock, reset_w, esr_rbox_in_buf_pg_en_ff,   esr_rbox_in_buf_pg_en_nxt,   1'b0)
   `RST_FF(clock, reset_w, esr_rbox_in_buf_cfg_en_ff,  esr_rbox_in_buf_cfg_en_nxt,  1'b0)
   `RST_FF(clock, reset_w, esr_rbox_out_buf_pg_en_ff,  esr_rbox_out_buf_pg_en_nxt,  1'b0)
   `RST_FF(clock, reset_w, esr_rbox_out_buf_cfg_en_ff, esr_rbox_out_buf_cfg_en_nxt, 1'b0)
   `RST_FF(clock, reset_w, esr_rbox_start_en_ff,       esr_rbox_start_en_nxt,       1'b0)
   `RST_FF(clock, reset_w, esr_rbox_consume_en_ff,     esr_rbox_consume_en_nxt,     1'b0)
 
   always_comb
   begin 
      esr_rbox_config_en_nxt      = s1_en && s1_wdata && (apb_paddr == esr_rbox_ad_RBOX_CONFIG)     ;
      esr_rbox_in_buf_pg_en_nxt   = s1_en && s1_wdata && (apb_paddr == esr_rbox_ad_RBOX_IN_BUF_PG)  ;
      esr_rbox_in_buf_cfg_en_nxt  = s1_en && s1_wdata && (apb_paddr == esr_rbox_ad_RBOX_IN_BUF_CFG) ;
      esr_rbox_out_buf_pg_en_nxt  = s1_en && s1_wdata && (apb_paddr == esr_rbox_ad_RBOX_OUT_BUF_PG) ;
      esr_rbox_out_buf_cfg_en_nxt = s1_en && s1_wdata && (apb_paddr == esr_rbox_ad_RBOX_OUT_BUF_CFG);
      esr_rbox_start_en_nxt       = s1_en && s1_wdata && (apb_paddr == esr_rbox_ad_RBOX_START)      ;
      esr_rbox_consume_en_nxt     = s1_en && s1_wdata && (apb_paddr == esr_rbox_ad_RBOX_CONSUME)    ;

      esr_rbox_config_en      = esr_rbox_config_en_ff;
      esr_rbox_in_buf_pg_en   = esr_rbox_in_buf_pg_en_ff;
      esr_rbox_in_buf_cfg_en  = esr_rbox_in_buf_cfg_en_ff;
      esr_rbox_out_buf_pg_en  = esr_rbox_out_buf_pg_en_ff;
      esr_rbox_out_buf_cfg_en = esr_rbox_out_buf_cfg_en_ff;
      esr_rbox_start_en       = esr_rbox_start_en_ff;
      esr_rbox_consume_en     = esr_rbox_consume_en_ff; 
   end

   // Lint
   wire unused_ok = &{
     `ifndef ET_ASCENT_LINT
      1'b0,
      `endif
      reset_d,
      test_en,
      &SETS_PER_SUB_BANK,
      &NUM_REQQ_ENTRIES
   };

   // CUSTOM STATEMENTS END 
   //////////////////////////////////////////////////////////////////////
endmodule
