// Copyright (c) 2026 Ainekko
// SPDX-License-Identifier: Apache-2.0


//////////////////////////////////////////////////////////////////////
// BEGIN autogenerated DECLARATIONS - do not edit manually   
// DDRC ESRs
`ESR_DECLARATION_WITH_TYPE(ddrc_reset_ctl, esr_ddrc_reset_ctl_t)
`ESR_DECLARATION_WITH_TYPE(ddrc_clock_ctl, esr_ddrc_clock_ctl_t)
`ESR_DECLARATION_WITH_TYPE(ddrc_main_ctl, esr_ddrc_main_ctl_t)
`ESR_DECLARATION(ddrc_scrub1, 36)
`ESR_DECLARATION(ddrc_scrub2, 36)
`ESR_DECLARATION_DEC_ONLY(ddrc_mrr_status)
`ESR_DECLARATION(ddrc_int_critical_en, 16)
`ESR_DECLARATION(ddrc_int_normal_en, 16)
`ESR_DECLARATION_DEC_ONLY(ddrc_err_int_log)
`ESR_DECLARATION(ddrc_debug_sigs_mask0, 64)
`ESR_DECLARATION(ddrc_debug_sigs_mask1, 64)
`ESR_DECLARATION(ddrc_scratch, 64)
`ESR_DECLARATION_WITH_TYPE(ddrc_trace_ctl, esr_ddrc_trace_ctl_t)
`ESR_DECLARATION_DEC_ONLY(ddrc_perfmon_ctl_status)
`ESR_DECLARATION_DEC_ONLY(ddrc_perfmon_cyc_cntr)
`ESR_DECLARATION_DEC_ONLY(ddrc_perfmon_p0_cntr)
`ESR_DECLARATION_DEC_ONLY(ddrc_perfmon_p1_cntr)
`ESR_DECLARATION_DEC_ONLY(ddrc_perfmon_p0_qual)
`ESR_DECLARATION_DEC_ONLY(ddrc_perfmon_p1_qual)
`ESR_DECLARATION_DEC_ONLY(ddrc_perfmon_p0_qual2)
`ESR_DECLARATION_DEC_ONLY(ddrc_perfmon_p1_qual2)

// END autogenerated DECLARATIONS
//////////////////////////////////////////////////////////////////////

function automatic void esr_read_and_decode_comb_default;
   begin
      //////////////////////////////////////////////////////////////////////
      // BEGIN autogenerated READ_AND_DECODE_COMB_DEFAULT - do not edit
      // DDRC ESRs
      `ESR_DECODE_DEFAULT(ddrc_reset_ctl)
      `ESR_DECODE_DEFAULT(ddrc_clock_ctl)
      `ESR_DECODE_DEFAULT(ddrc_main_ctl)
      `ESR_DECODE_DEFAULT(ddrc_scrub1)
      `ESR_DECODE_DEFAULT(ddrc_scrub2)
      `ESR_DECODE_DEFAULT(ddrc_mrr_status)
      `ESR_DECODE_DEFAULT(ddrc_int_critical_en)
      `ESR_DECODE_DEFAULT(ddrc_int_normal_en)
      `ESR_DECODE_DEFAULT(ddrc_err_int_log)
      `ESR_DECODE_DEFAULT(ddrc_debug_sigs_mask0)
      `ESR_DECODE_DEFAULT(ddrc_debug_sigs_mask1)
      `ESR_DECODE_DEFAULT(ddrc_scratch)
      `ESR_DECODE_DEFAULT(ddrc_trace_ctl)
      `ESR_DECODE_DEFAULT(ddrc_perfmon_ctl_status)
      `ESR_DECODE_DEFAULT(ddrc_perfmon_cyc_cntr)
      `ESR_DECODE_DEFAULT(ddrc_perfmon_p0_cntr)
      `ESR_DECODE_DEFAULT(ddrc_perfmon_p1_cntr)
      `ESR_DECODE_DEFAULT(ddrc_perfmon_p0_qual)
      `ESR_DECODE_DEFAULT(ddrc_perfmon_p1_qual)
      `ESR_DECODE_DEFAULT(ddrc_perfmon_p0_qual2)
      `ESR_DECODE_DEFAULT(ddrc_perfmon_p1_qual2)
      // END autogenerated READ_AND_DECODE_COMB_DEFAULT - do not edit
      //////////////////////////////////////////////////////////////////////
   end
endfunction //


//function automatic void esr_read_and_decode_comb_cases;
//   begin
`define esr_read_and_decode_comb_cases_ddrc \
      if(s0_en) begin \
         case (apb_paddr) \
           ////////////////////////////////////////////////////////////////////// \
           // BEGIN autogenerated READ_AND_DECODE_COMB_CASES - do not edit \
            // DDRC ESRs \
            `ESR_DECODE_CASE(esr_ddrc_ad_DDRC_RESET_CTL, ddrc_reset_ctl, reg_ddrc_reset_ctl) \
            `ESR_DECODE_CASE(esr_ddrc_ad_DDRC_CLOCK_CTL, ddrc_clock_ctl, esr_status_ddrc_clock_ctl) \
            `ESR_DECODE_CASE(esr_ddrc_ad_DDRC_MAIN_CTL, ddrc_main_ctl, reg_ddrc_main_ctl) \
            `ESR_DECODE_CASE(esr_ddrc_ad_DDRC_SCRUB1, ddrc_scrub1, reg_ddrc_scrub1) \
            `ESR_DECODE_CASE(esr_ddrc_ad_DDRC_SCRUB2, ddrc_scrub2, reg_ddrc_scrub2) \
            `ESR_DECODE_CASE_RO(esr_ddrc_ad_DDRC_U0_MRR_DATA, esr_status_ddrc_u0_mrr_data) \
            `ESR_DECODE_CASE_RO(esr_ddrc_ad_DDRC_U1_MRR_DATA, esr_status_ddrc_u1_mrr_data) \
            `ESR_DECODE_CASE(esr_ddrc_ad_DDRC_MRR_STATUS, ddrc_mrr_status, esr_status_ddrc_mrr_status) \
            `ESR_DECODE_CASE_RO(esr_ddrc_ad_DDRC_INT_STATUS, esr_status_ddrc_int_status) \
            `ESR_DECODE_CASE(esr_ddrc_ad_DDRC_INT_CRITICAL_EN, ddrc_int_critical_en, reg_ddrc_int_critical_en) \
            `ESR_DECODE_CASE(esr_ddrc_ad_DDRC_INT_NORMAL_EN, ddrc_int_normal_en, reg_ddrc_int_normal_en) \
            `ESR_DECODE_CASE(esr_ddrc_ad_DDRC_ERR_INT_LOG, ddrc_err_int_log, esr_status_ddrc_err_int_log) \
            `ESR_DECODE_CASE(esr_ddrc_ad_DDRC_DEBUG_SIGS_MASK0, ddrc_debug_sigs_mask0, reg_ddrc_debug_sigs_mask0) \
            `ESR_DECODE_CASE(esr_ddrc_ad_DDRC_DEBUG_SIGS_MASK1, ddrc_debug_sigs_mask1, reg_ddrc_debug_sigs_mask1) \
            `ESR_DECODE_CASE(esr_ddrc_ad_DDRC_SCRATCH, ddrc_scratch, reg_ddrc_scratch) \
            `ESR_DECODE_CASE(esr_ddrc_ad_DDRC_TRACE_CTL, ddrc_trace_ctl, reg_ddrc_trace_ctl) \
            `ESR_DECODE_CASE(esr_ddrc_ad_DDRC_PERFMON_CTL_STATUS, ddrc_perfmon_ctl_status, esr_status_perfmon_ctl_status) \
            `ESR_DECODE_CASE(esr_ddrc_ad_DDRC_PERFMON_CYC_CNTR, ddrc_perfmon_cyc_cntr, esr_status_perfmon_cyc_cntr) \
            `ESR_DECODE_CASE(esr_ddrc_ad_DDRC_PERFMON_P0_CNTR, ddrc_perfmon_p0_cntr, esr_status_perfmon_p0_cntr) \
            `ESR_DECODE_CASE(esr_ddrc_ad_DDRC_PERFMON_P1_CNTR, ddrc_perfmon_p1_cntr, esr_status_perfmon_p1_cntr) \
            `ESR_DECODE_CASE(esr_ddrc_ad_DDRC_PERFMON_P0_QUAL, ddrc_perfmon_p0_qual, esr_status_perfmon_p0_qual) \
            `ESR_DECODE_CASE(esr_ddrc_ad_DDRC_PERFMON_P1_QUAL, ddrc_perfmon_p1_qual, esr_status_perfmon_p1_qual) \
            `ESR_DECODE_CASE(esr_ddrc_ad_DDRC_PERFMON_P0_QUAL2, ddrc_perfmon_p0_qual2, esr_status_perfmon_p0_qual2) \
            `ESR_DECODE_CASE(esr_ddrc_ad_DDRC_PERFMON_P1_QUAL2, ddrc_perfmon_p1_qual2, esr_status_perfmon_p1_qual2) \
           // END autogenerated READ_AND_DECODE_COMB_CASES - do not edit \
           ////////////////////////////////////////////////////////////////////// \
           default: \
             s0_addr_valid = 1'b0; \
         endcase // case (apb_paddr) \
      end // if (s0_en) \
//   end
//endfunction 


//////////////////////////////////////////////////////////////////////
// BEGIN autogenerated READ_AND_DECODE_SEQ - do not edit
// DDRC ESRs
`ESR_DECODE_SEQ(ddrc_reset_ctl)
`ESR_DECODE_SEQ(ddrc_clock_ctl)
`ESR_DECODE_SEQ(ddrc_main_ctl)
`ESR_DECODE_SEQ(ddrc_scrub1)
`ESR_DECODE_SEQ(ddrc_scrub2)
`ESR_DECODE_SEQ(ddrc_mrr_status)
`ESR_DECODE_SEQ(ddrc_int_critical_en)
`ESR_DECODE_SEQ(ddrc_int_normal_en)
`ESR_DECODE_SEQ(ddrc_err_int_log)
`ESR_DECODE_SEQ(ddrc_debug_sigs_mask0)
`ESR_DECODE_SEQ(ddrc_debug_sigs_mask1)
`ESR_DECODE_SEQ(ddrc_scratch)
`ESR_DECODE_SEQ(ddrc_trace_ctl)
`ESR_DECODE_SEQ(ddrc_perfmon_ctl_status)
`ESR_DECODE_SEQ(ddrc_perfmon_cyc_cntr)
`ESR_DECODE_SEQ(ddrc_perfmon_p0_cntr)
`ESR_DECODE_SEQ(ddrc_perfmon_p1_cntr)
`ESR_DECODE_SEQ(ddrc_perfmon_p0_qual)
`ESR_DECODE_SEQ(ddrc_perfmon_p1_qual)
`ESR_DECODE_SEQ(ddrc_perfmon_p0_qual2)
`ESR_DECODE_SEQ(ddrc_perfmon_p1_qual2)
// END autogenerated READ_AND_DECODE_SEQ
//////////////////////////////////////////////////////////////////////


//function  automatic void esr_write_comb_default;
//   begin
`define esr_write_comb_default_ddrc  \
      ////////////////////////////////////////////////////////////////////// \
      // BEGIN autogenerated WRITE_COMB_DEFAULT - do not edit \
      // DDRC ESRs \
      `ESR_WRITE_COMB_DEFAULT(ddrc_reset_ctl) \
      `ESR_WRITE_COMB_DEFAULT(ddrc_clock_ctl) \
      `ESR_WRITE_COMB_DEFAULT(ddrc_main_ctl) \
      `ESR_WRITE_COMB_DEFAULT(ddrc_scrub1) \
      `ESR_WRITE_COMB_DEFAULT(ddrc_scrub2) \
      `ESR_WRITE_COMB_DEFAULT(ddrc_int_critical_en) \
      `ESR_WRITE_COMB_DEFAULT(ddrc_int_normal_en) \
      `ESR_WRITE_COMB_DEFAULT(ddrc_debug_sigs_mask0) \
      `ESR_WRITE_COMB_DEFAULT(ddrc_debug_sigs_mask1) \
      `ESR_WRITE_COMB_DEFAULT(ddrc_scratch) \
      `ESR_WRITE_COMB_DEFAULT(ddrc_trace_ctl) \
      // END autogenerated WRITE_COMB_DEFAULT - do not edit \
      ////////////////////////////////////////////////////////////////////// \
//   end
//endfunction //


//function automatic void esr_write_comb;
//   begin
`define esr_write_comb_ddrc  \
      ////////////////////////////////////////////////////////////////////// \
      // BEGIN autogenerated WRITE_CORE_COMB - do not edit \
 \
      // WRITE_COMB for regs that shadow some other reg \
 \
      // WRITE_COMB for the other regs \
      // DDRC ESRs \
      `ESR_WRITE_COMB(ddrc_reset_ctl, write_ddrc_reset_ctl(apb_pwdata[$bits(esr_ddrc_reset_ctl_t)-1:0])) \
      `ESR_WRITE_COMB(ddrc_clock_ctl, write_ddrc_clock_ctl(apb_pwdata[$bits(esr_ddrc_clock_ctl_t)-1:0])) \
      `ESR_WRITE_COMB(ddrc_main_ctl, apb_pwdata[$bits(esr_ddrc_main_ctl_t)-1:0]) \
      `ESR_WRITE_COMB(ddrc_scrub1, apb_pwdata[35:0]) \
      `ESR_WRITE_COMB(ddrc_scrub2, apb_pwdata[35:0]) \
      `ESR_WRITE_COMB(ddrc_int_critical_en, apb_pwdata[15:0]) \
      `ESR_WRITE_COMB(ddrc_int_normal_en, apb_pwdata[15:0]) \
      `ESR_WRITE_COMB(ddrc_debug_sigs_mask0, apb_pwdata) \
      `ESR_WRITE_COMB(ddrc_debug_sigs_mask1, apb_pwdata) \
      `ESR_WRITE_COMB(ddrc_scratch, apb_pwdata) \
      `ESR_WRITE_COMB(ddrc_trace_ctl, write_ddrc_trace_ctl(apb_pwdata[$bits(esr_ddrc_trace_ctl_t)-1:0])) \
      // END autogenerated WRITE_CORE_COMB - do not edit \
      ////////////////////////////////////////////////////////////////////// \
//   end
//endfunction //



//////////////////////////////////////////////////////////////////////
// BEGIN autogenerated WRITE_SEQ - do not edit
   // DDRC ESRs
`ESR_WRITE_SEQ_RST_ND(clock, ddrc_reset_ctl_pre, ddrc_reset_ctl_next, `ESR_DDRC_RESET_CTL_RESET_VAL)
`ESR_WRITE_TYPE_WITH_RESERVED(ddrc_reset_ctl, esr_ddrc_reset_ctl_t')
`ESR_WRITE_SEQ_RST_ND(clock, ddrc_clock_ctl_pre, ddrc_clock_ctl_next, `ESR_DDRC_CLOCK_CTL_RESET_VAL)
`ESR_WRITE_TYPE_WITH_RESERVED(ddrc_clock_ctl, esr_ddrc_clock_ctl_t')
`ESR_WRITE_SEQ_RST_ND(clock, ddrc_main_ctl_pre, ddrc_main_ctl_next, `ESR_DDRC_MAIN_CTL_RESET_VAL)
`ESR_WRITE_TYPE_WITH_RESERVED(ddrc_main_ctl, esr_ddrc_main_ctl_t')
`ESR_WRITE_SEQ_RST_ND(clock, ddrc_scrub1, ddrc_scrub1_next, '0)
`ESR_WRITE_SEQ_RST_ND(clock, ddrc_scrub2, ddrc_scrub2_next, '0)
`ESR_WRITE_SEQ_RST(clock, ddrc_int_critical_en, ddrc_int_critical_en_next, `ESR_DDRC_INT_CRITICAL_EN_RESET_VAL)
`ESR_WRITE_SEQ_RST(clock, ddrc_int_normal_en, ddrc_int_normal_en_next, `ESR_DDRC_INT_NORMAL_EN_RESET_VAL)
`ESR_WRITE_SEQ_RST_D(clock, ddrc_debug_sigs_mask0, ddrc_debug_sigs_mask0_next, '0)
`ESR_WRITE_SEQ_RST_D(clock, ddrc_debug_sigs_mask1, ddrc_debug_sigs_mask1_next, '0)
`ESR_WRITE_SEQ_RST(clock, ddrc_scratch, ddrc_scratch_next, '0)
`ESR_WRITE_SEQ_RST_D(clock, ddrc_trace_ctl_pre, ddrc_trace_ctl_next, `ESR_DDRC_TRACE_CTL_RESET_VAL)
`ESR_WRITE_TYPE_WITH_RESERVED(ddrc_trace_ctl, esr_ddrc_trace_ctl_t')
// END autogenerated WRITE_SEQ
//////////////////////////////////////////////////////////////////////


//////////////////////////////////////////////////////////////////////
// BEGIN autogenerated PORT_ASSIGN - do not edit
// END autogenerated PORT_ASSIGN - do not edit
//////////////////////////////////////////////////////////////////////

//////////////////////////////////////////////////////////////////////
// BEGIN autogenerated TYPE_CONVERSIONS - do not edit
   //conversion functions for esr_ddrc_clock_ctl_t
   function automatic esr_ddrc_clock_ctl_t write_ddrc_clock_ctl;
   input [$bits(esr_ddrc_clock_ctl_t)-1:0] d;
   esr_ddrc_clock_ctl_t dd;
   esr_ddrc_clock_ctl_t ret;
   begin
      dd = esr_ddrc_clock_ctl_t'(d);
      ret.esr_ddrc_u0_cactive_ddrc = '0; // RO field
      ret.esr_ddrc_u0_csysack_ddrc = '0; // RO field
      ret.esr_ddrc_u0_csysreq_ddrc = dd.esr_ddrc_u0_csysreq_ddrc;
      ret.esr_ddrc_u1_cactive_ddrc = '0; // RO field
      ret.esr_ddrc_u1_csysack_ddrc = '0; // RO field
      ret.esr_ddrc_u1_csysreq_ddrc = dd.esr_ddrc_u1_csysreq_ddrc;
      ret.esr_ddrc_u0_cactive_lo = '0; // RO field
      ret.esr_ddrc_u0_csysack_lo = '0; // RO field
      ret.esr_ddrc_u0_csysreq_lo = dd.esr_ddrc_u0_csysreq_lo;
      ret.esr_ddrc_u1_cactive_lo = '0; // RO field
      ret.esr_ddrc_u1_csysack_lo = '0; // RO field
      ret.esr_ddrc_u1_csysreq_lo = dd.esr_ddrc_u1_csysreq_lo;
      ret.esr_ddrc_u0_cactive_hi = '0; // RO field
      ret.esr_ddrc_u0_csysack_hi = '0; // RO field
      ret.esr_ddrc_u0_csysreq_hi = dd.esr_ddrc_u0_csysreq_hi;
      ret.esr_ddrc_u1_cactive_hi = '0; // RO field
      ret.esr_ddrc_u1_csysack_hi = '0; // RO field
      ret.esr_ddrc_u1_csysreq_hi = dd.esr_ddrc_u1_csysreq_hi;
      return ret;
   end
   endfunction

   //conversion functions for esr_ddrc_reset_ctl_t
   function automatic esr_ddrc_reset_ctl_t write_ddrc_reset_ctl;
   input [$bits(esr_ddrc_reset_ctl_t)-1:0] d;
   esr_ddrc_reset_ctl_t dd;
   esr_ddrc_reset_ctl_t ret;
   begin
      dd = esr_ddrc_reset_ctl_t'(d);
      ret.esr_ddrc_subsystem_reset = dd.esr_ddrc_subsystem_reset;
      ret.esr_ddrc_apb_reset = dd.esr_ddrc_apb_reset;
      ret.esr_ddrc_pub_reset = dd.esr_ddrc_pub_reset;
      ret.esr_ddrc_power_ok = dd.esr_ddrc_power_ok;
      ret.esr_ddrc_reset_ctl_reserved = '0; // RO field
      ret.esr_ddrc_pll_clk_sel = dd.esr_ddrc_pll_clk_sel;
      return ret;
   end
   endfunction

   //conversion functions for esr_ddrc_trace_ctl_t
   function automatic esr_ddrc_trace_ctl_t write_ddrc_trace_ctl;
   input [$bits(esr_ddrc_trace_ctl_t)-1:0] d;
   esr_ddrc_trace_ctl_t dd;
   esr_ddrc_trace_ctl_t ret;
   begin
      dd = esr_ddrc_trace_ctl_t'(d);
      ret.esr_ddrc_trace_en = dd.esr_ddrc_trace_en;
      ret.esr_ddrc_debug_ctl_reserved = '0; // RO field
      ret.esr_ddrc_perf_op_sigs_mask = dd.esr_ddrc_perf_op_sigs_mask;
      return ret;
   end
   endfunction
// END autogenerated TYPE_CONVERSIONS
//////////////////////////////////////////////////////////////////////

