// Copyright (c) 2026 Ainekko
// SPDX-License-Identifier: Apache-2.0


//////////////////////////////////////////////////////////////////////
// BEGIN autogenerated DECLARATIONS - do not edit manually   
// Shire Cache ESR
`ESR_DECLARATION_WITH_TYPE(sc_l3_shire_swizzle_ctl, esr_sc_l3_shire_swizzle_ctl_t)
`ESR_DECLARATION_WITH_TYPE(sc_reqq_ctl, esr_sc_reqq_ctl_t)
`ESR_DECLARATION_WITH_TYPE(sc_pipe_ctl, esr_sc_pipe_ctl_t)
`ESR_DECLARATION_WITH_TYPE(sc_l2_cache_ctl, esr_sc_pipe_cache_ctl_t)
`ESR_DECLARATION_WITH_TYPE(sc_l3_cache_ctl, esr_sc_pipe_cache_ctl_t)
`ESR_DECLARATION_WITH_TYPE(sc_scp_cache_ctl, esr_sc_pipe_cache_ctl_t)
`ESR_DECLARATION_DEC_ONLY(sc_idx_cop_sm_ctl)
`ESR_DECLARATION_DEC_ONLY(sc_idx_cop_sm_physical_index)
`ESR_DECLARATION_DEC_ONLY(sc_idx_cop_sm_data0)
`ESR_DECLARATION_DEC_ONLY(sc_idx_cop_sm_data1)
`ESR_DECLARATION_DEC_ONLY(sc_idx_cop_sm_ecc)
`ESR_DECLARATION_WITH_TYPE(sc_err_log_ctl, esr_sc_err_log_ctl_t)
`ESR_DECLARATION_DEC_ONLY(sc_err_log_info)
`ESR_DECLARATION_DEC_ONLY(sc_sbe_dbe_counts)
`ESR_DECLARATION_DEC_ONLY(sc_reqq_debug_ctl)
`ESR_DECLARATION(sc_eco_ctl, 8)
`ESR_DECLARATION_DEC_ONLY(sc_perfmon_ctl_status)
`ESR_DECLARATION_DEC_ONLY(sc_perfmon_cyc_cntr)
`ESR_DECLARATION_DEC_ONLY(sc_perfmon_p0_cntr)
`ESR_DECLARATION_DEC_ONLY(sc_perfmon_p1_cntr)
`ESR_DECLARATION_DEC_ONLY(sc_perfmon_p0_qual)
`ESR_DECLARATION_DEC_ONLY(sc_perfmon_p1_qual)
`ESR_DECLARATION_DEC_ONLY(sc_idx_cop_sm_ctl_user)
`ESR_DECLARATION(sc_trace_address_enable, 40)
`ESR_DECLARATION(sc_trace_address_value, 40)
`ESR_DECLARATION_WITH_TYPE(sc_trace_ctl, esr_sc_trace_ctl_t)

// END autogenerated DECLARATIONS
//////////////////////////////////////////////////////////////////////

function automatic void esr_read_and_decode_comb_default;
   begin
      //////////////////////////////////////////////////////////////////////
      // BEGIN autogenerated READ_AND_DECODE_COMB_DEFAULT - do not edit
      // Shire Cache ESR
      `ESR_DECODE_DEFAULT(sc_l3_shire_swizzle_ctl)
      `ESR_DECODE_DEFAULT(sc_reqq_ctl)
      `ESR_DECODE_DEFAULT(sc_pipe_ctl)
      `ESR_DECODE_DEFAULT(sc_l2_cache_ctl)
      `ESR_DECODE_DEFAULT(sc_l3_cache_ctl)
      `ESR_DECODE_DEFAULT(sc_scp_cache_ctl)
      `ESR_DECODE_DEFAULT(sc_idx_cop_sm_ctl)
      `ESR_DECODE_DEFAULT(sc_idx_cop_sm_physical_index)
      `ESR_DECODE_DEFAULT(sc_idx_cop_sm_data0)
      `ESR_DECODE_DEFAULT(sc_idx_cop_sm_data1)
      `ESR_DECODE_DEFAULT(sc_idx_cop_sm_ecc)
      `ESR_DECODE_DEFAULT(sc_err_log_ctl)
      `ESR_DECODE_DEFAULT(sc_err_log_info)
      `ESR_DECODE_DEFAULT(sc_sbe_dbe_counts)
      `ESR_DECODE_DEFAULT(sc_reqq_debug_ctl)
      `ESR_DECODE_DEFAULT(sc_eco_ctl)
      `ESR_DECODE_DEFAULT(sc_perfmon_ctl_status)
      `ESR_DECODE_DEFAULT(sc_perfmon_cyc_cntr)
      `ESR_DECODE_DEFAULT(sc_perfmon_p0_cntr)
      `ESR_DECODE_DEFAULT(sc_perfmon_p1_cntr)
      `ESR_DECODE_DEFAULT(sc_perfmon_p0_qual)
      `ESR_DECODE_DEFAULT(sc_perfmon_p1_qual)
      `ESR_DECODE_DEFAULT(sc_idx_cop_sm_ctl_user)
      `ESR_DECODE_DEFAULT(sc_trace_address_enable)
      `ESR_DECODE_DEFAULT(sc_trace_address_value)
      `ESR_DECODE_DEFAULT(sc_trace_ctl)
      // END autogenerated READ_AND_DECODE_COMB_DEFAULT - do not edit
      //////////////////////////////////////////////////////////////////////
   end
endfunction //


//function automatic void esr_read_and_decode_comb_cases;
//   begin
`define esr_read_and_decode_comb_cases_cache_bank \
      if(s0_en) begin \
         case (apb_paddr) \
           ////////////////////////////////////////////////////////////////////// \
           // BEGIN autogenerated READ_AND_DECODE_COMB_CASES - do not edit \
            // Shire Cache ESR \
            `ESR_DECODE_CASE(esr_cache_bank_ad_SC_L3_SHIRE_SWIZZLE_CTL, sc_l3_shire_swizzle_ctl, reg_sc_l3_shire_swizzle_ctl) \
            `ESR_DECODE_CASE(esr_cache_bank_ad_SC_REQQ_CTL, sc_reqq_ctl, reg_sc_reqq_ctl) \
            `ESR_DECODE_CASE(esr_cache_bank_ad_SC_PIPE_CTL, sc_pipe_ctl, reg_sc_pipe_ctl) \
            `ESR_DECODE_CASE(esr_cache_bank_ad_SC_L2_CACHE_CTL, sc_l2_cache_ctl, reg_sc_l2_cache_ctl) \
            `ESR_DECODE_CASE(esr_cache_bank_ad_SC_L3_CACHE_CTL, sc_l3_cache_ctl, reg_sc_l3_cache_ctl) \
            `ESR_DECODE_CASE(esr_cache_bank_ad_SC_SCP_CACHE_CTL, sc_scp_cache_ctl, reg_sc_scp_cache_ctl) \
            `ESR_DECODE_CASE(esr_cache_bank_ad_SC_IDX_COP_SM_CTL, sc_idx_cop_sm_ctl, esr_status_pipe_idx_cop_sm_ctl) \
            `ESR_DECODE_CASE(esr_cache_bank_ad_SC_IDX_COP_SM_PHYSICAL_INDEX, sc_idx_cop_sm_physical_index, esr_status_pipe_idx_cop_sm_physical_index) \
            `ESR_DECODE_CASE(esr_cache_bank_ad_SC_IDX_COP_SM_DATA0, sc_idx_cop_sm_data0, esr_status_pipe_idx_cop_sm_data0) \
            `ESR_DECODE_CASE(esr_cache_bank_ad_SC_IDX_COP_SM_DATA1, sc_idx_cop_sm_data1, esr_status_pipe_idx_cop_sm_data1) \
            `ESR_DECODE_CASE(esr_cache_bank_ad_SC_IDX_COP_SM_ECC, sc_idx_cop_sm_ecc, esr_status_pipe_idx_cop_sm_ecc) \
            `ESR_DECODE_CASE(esr_cache_bank_ad_SC_ERR_LOG_CTL, sc_err_log_ctl, reg_sc_err_log_ctl) \
            `ESR_DECODE_CASE(esr_cache_bank_ad_SC_ERR_LOG_INFO, sc_err_log_info, esr_status_err_log_info) \
            `ESR_DECODE_CASE_RO(esr_cache_bank_ad_SC_ERR_LOG_ADDRESS, esr_status_err_log_address) \
            `ESR_DECODE_CASE(esr_cache_bank_ad_SC_SBE_DBE_COUNTS, sc_sbe_dbe_counts, esr_status_sbe_dbe_counts) \
            `ESR_DECODE_CASE_RD_CONSTANT(esr_cache_bank_ad_SC_REQQ_DEBUG_CTL, sc_reqq_debug_ctl, '0) \
            `ESR_DECODE_CASE_RO(esr_cache_bank_ad_SC_REQQ_DEBUG0, esr_status_reqq_debug0) \
            `ESR_DECODE_CASE_RO(esr_cache_bank_ad_SC_REQQ_DEBUG1, esr_status_reqq_debug1) \
            `ESR_DECODE_CASE_RO(esr_cache_bank_ad_SC_REQQ_DEBUG2, esr_status_reqq_debug2) \
            `ESR_DECODE_CASE_RO(esr_cache_bank_ad_SC_REQQ_DEBUG3, esr_status_reqq_debug3) \
            `ESR_DECODE_CASE(esr_cache_bank_ad_SC_ECO_CTL, sc_eco_ctl, reg_sc_eco_ctl) \
            `ESR_DECODE_CASE(esr_cache_bank_ad_SC_PERFMON_CTL_STATUS, sc_perfmon_ctl_status, esr_status_perfmon_ctl_status) \
            `ESR_DECODE_CASE(esr_cache_bank_ad_SC_PERFMON_CYC_CNTR, sc_perfmon_cyc_cntr, esr_status_perfmon_cyc_cntr) \
            `ESR_DECODE_CASE(esr_cache_bank_ad_SC_PERFMON_P0_CNTR, sc_perfmon_p0_cntr, esr_status_perfmon_p0_cntr) \
            `ESR_DECODE_CASE(esr_cache_bank_ad_SC_PERFMON_P1_CNTR, sc_perfmon_p1_cntr, esr_status_perfmon_p1_cntr) \
            `ESR_DECODE_CASE(esr_cache_bank_ad_SC_PERFMON_P0_QUAL, sc_perfmon_p0_qual, esr_status_perfmon_p0_qual) \
            `ESR_DECODE_CASE(esr_cache_bank_ad_SC_PERFMON_P1_QUAL, sc_perfmon_p1_qual, esr_status_perfmon_p1_qual) \
            `ESR_DECODE_CASE(esr_cache_bank_ad_SC_IDX_COP_SM_CTL_USER, sc_idx_cop_sm_ctl_user, esr_status_pipe_idx_cop_sm_ctl_user) \
            `ESR_DECODE_CASE(esr_cache_bank_ad_SC_TRACE_ADDRESS_ENABLE, sc_trace_address_enable, reg_sc_trace_address_enable) \
            `ESR_DECODE_CASE(esr_cache_bank_ad_SC_TRACE_ADDRESS_VALUE, sc_trace_address_value, reg_sc_trace_address_value) \
            `ESR_DECODE_CASE(esr_cache_bank_ad_SC_TRACE_CTL, sc_trace_ctl, reg_sc_trace_ctl) \
           // END autogenerated READ_AND_DECODE_COMB_CASES - do not edit \
           ////////////////////////////////////////////////////////////////////// \
           default: \
             s0_addr_valid = 1'b0; \
         endcase // case (apb_paddr) \
      end // if (s0_en) \
//   end
//endfunction 


//////////////////////////////////////////////////////////////////////
// BEGIN autogenerated READ_AND_DECODE_SEQ - do not edit
// Shire Cache ESR
`ESR_DECODE_SEQ(sc_l3_shire_swizzle_ctl)
`ESR_DECODE_SEQ(sc_reqq_ctl)
`ESR_DECODE_SEQ(sc_pipe_ctl)
`ESR_DECODE_SEQ(sc_l2_cache_ctl)
`ESR_DECODE_SEQ(sc_l3_cache_ctl)
`ESR_DECODE_SEQ(sc_scp_cache_ctl)
`ESR_DECODE_SEQ(sc_idx_cop_sm_ctl)
`ESR_DECODE_SEQ(sc_idx_cop_sm_physical_index)
`ESR_DECODE_SEQ(sc_idx_cop_sm_data0)
`ESR_DECODE_SEQ(sc_idx_cop_sm_data1)
`ESR_DECODE_SEQ(sc_idx_cop_sm_ecc)
`ESR_DECODE_SEQ(sc_err_log_ctl)
`ESR_DECODE_SEQ(sc_err_log_info)
`ESR_DECODE_SEQ(sc_sbe_dbe_counts)
`ESR_DECODE_SEQ(sc_reqq_debug_ctl)
`ESR_DECODE_SEQ(sc_eco_ctl)
`ESR_DECODE_SEQ(sc_perfmon_ctl_status)
`ESR_DECODE_SEQ(sc_perfmon_cyc_cntr)
`ESR_DECODE_SEQ(sc_perfmon_p0_cntr)
`ESR_DECODE_SEQ(sc_perfmon_p1_cntr)
`ESR_DECODE_SEQ(sc_perfmon_p0_qual)
`ESR_DECODE_SEQ(sc_perfmon_p1_qual)
`ESR_DECODE_SEQ(sc_idx_cop_sm_ctl_user)
`ESR_DECODE_SEQ(sc_trace_address_enable)
`ESR_DECODE_SEQ(sc_trace_address_value)
`ESR_DECODE_SEQ(sc_trace_ctl)
// END autogenerated READ_AND_DECODE_SEQ
//////////////////////////////////////////////////////////////////////


//function  automatic void esr_write_comb_default;
//   begin
`define esr_write_comb_default_cache_bank \
      ////////////////////////////////////////////////////////////////////// \
      // BEGIN autogenerated WRITE_COMB_DEFAULT - do not edit \
      // Shire Cache ESR \
      `ESR_WRITE_COMB_DEFAULT(sc_l3_shire_swizzle_ctl) \
      `ESR_WRITE_COMB_DEFAULT(sc_reqq_ctl) \
      `ESR_WRITE_COMB_DEFAULT(sc_pipe_ctl) \
      `ESR_WRITE_COMB_DEFAULT(sc_l2_cache_ctl) \
      `ESR_WRITE_COMB_DEFAULT(sc_l3_cache_ctl) \
      `ESR_WRITE_COMB_DEFAULT(sc_scp_cache_ctl) \
      `ESR_WRITE_COMB_DEFAULT(sc_err_log_ctl) \
      `ESR_WRITE_COMB_DEFAULT(sc_eco_ctl) \
      `ESR_WRITE_COMB_DEFAULT(sc_trace_address_enable) \
      `ESR_WRITE_COMB_DEFAULT(sc_trace_address_value) \
      `ESR_WRITE_COMB_DEFAULT(sc_trace_ctl) \
      // END autogenerated WRITE_COMB_DEFAULT - do not edit \
      ////////////////////////////////////////////////////////////////////// \
//   end
//endfunction //


//function automatic void esr_write_comb;
//   begin
`define esr_write_comb_cache_bank \
      ////////////////////////////////////////////////////////////////////// \
      // BEGIN autogenerated WRITE_CORE_COMB - do not edit \
 \
      // WRITE_COMB for regs that shadow some other reg \
 \
      // WRITE_COMB for the other regs \
      // Shire Cache ESR \
      `ESR_WRITE_COMB(sc_l3_shire_swizzle_ctl, apb_pwdata[$bits(esr_sc_l3_shire_swizzle_ctl_t)-1:0]) \
      `ESR_WRITE_COMB(sc_reqq_ctl, apb_pwdata[$bits(esr_sc_reqq_ctl_t)-1:0]) \
      `ESR_WRITE_COMB(sc_pipe_ctl, apb_pwdata[$bits(esr_sc_pipe_ctl_t)-1:0]) \
      `ESR_WRITE_COMB(sc_l2_cache_ctl, write_sc_pipe_cache_ctl(apb_pwdata[$bits(esr_sc_pipe_cache_ctl_t)-1:0])) \
      `ESR_WRITE_COMB(sc_l3_cache_ctl, write_sc_pipe_cache_ctl(apb_pwdata[$bits(esr_sc_pipe_cache_ctl_t)-1:0])) \
      `ESR_WRITE_COMB(sc_scp_cache_ctl, write_sc_pipe_cache_ctl(apb_pwdata[$bits(esr_sc_pipe_cache_ctl_t)-1:0])) \
      `ESR_WRITE_COMB(sc_err_log_ctl, apb_pwdata[$bits(esr_sc_err_log_ctl_t)-1:0]) \
      `ESR_WRITE_COMB(sc_eco_ctl, apb_pwdata[7:0]) \
      `ESR_WRITE_COMB(sc_trace_address_enable, apb_pwdata[39:0]) \
      `ESR_WRITE_COMB(sc_trace_address_value, apb_pwdata[39:0]) \
      `ESR_WRITE_COMB(sc_trace_ctl, apb_pwdata[$bits(esr_sc_trace_ctl_t)-1:0]) \
      // END autogenerated WRITE_CORE_COMB - do not edit \
      //////////////////////////////////////////////////////////////////////
//   end
//endfunction //



//////////////////////////////////////////////////////////////////////
// BEGIN autogenerated WRITE_SEQ - do not edit
   // Shire Cache ESR
`ESR_WRITE_SEQ_RST(clock, sc_l3_shire_swizzle_ctl_pre, sc_l3_shire_swizzle_ctl_next, `ESR_SC_L3_SHIRE_SWIZZLE_CTL_RESET_VAL)
`ESR_WRITE_TYPE_WITH_RESERVED(sc_l3_shire_swizzle_ctl, esr_sc_l3_shire_swizzle_ctl_t')
`ESR_WRITE_SEQ_RST(clock, sc_reqq_ctl_pre, sc_reqq_ctl_next, `ESR_SC_REQQ_CTL_RESET_VAL)
`ESR_WRITE_TYPE_WITH_RESERVED(sc_reqq_ctl, esr_sc_reqq_ctl_t')
`ESR_WRITE_SEQ_RST(clock, sc_pipe_ctl_pre, sc_pipe_ctl_next, `ESR_SC_PIPE_CTL_RESET_VAL)
`ESR_WRITE_TYPE_WITH_RESERVED(sc_pipe_ctl, esr_sc_pipe_ctl_t')
`ESR_WRITE_SEQ_RST(clock, sc_l2_cache_ctl_pre, sc_l2_cache_ctl_next, `ESR_SC_L2_CACHE_CTL_RESET_VAL)
`ESR_WRITE_TYPE_WITH_RESERVED(sc_l2_cache_ctl, esr_sc_pipe_cache_ctl_t')
`ESR_WRITE_SEQ_RST(clock, sc_l3_cache_ctl_pre, sc_l3_cache_ctl_next, `ESR_SC_L3_CACHE_CTL_RESET_VAL)
`ESR_WRITE_TYPE_WITH_RESERVED(sc_l3_cache_ctl, esr_sc_pipe_cache_ctl_t')
`ESR_WRITE_SEQ_RST(clock, sc_scp_cache_ctl_pre, sc_scp_cache_ctl_next, `ESR_SC_SCP_CACHE_CTL_RESET_VAL)
`ESR_WRITE_TYPE_WITH_RESERVED(sc_scp_cache_ctl, esr_sc_pipe_cache_ctl_t')
`ESR_WRITE_SEQ_RST(clock, sc_err_log_ctl_pre, sc_err_log_ctl_next, `ESR_SC_ERR_LOG_CTL_RESET_VAL)
`ESR_WRITE_TYPE_WITH_RESERVED(sc_err_log_ctl, esr_sc_err_log_ctl_t')
`ESR_WRITE_SEQ_RST(clock, sc_eco_ctl, sc_eco_ctl_next, '0)
`ESR_WRITE_SEQ_RST_D(clock, sc_trace_address_enable, sc_trace_address_enable_next, '0)
`ESR_WRITE_SEQ(clock, sc_trace_address_value, sc_trace_address_value_next)
`ESR_WRITE_SEQ_RST_D(clock, sc_trace_ctl_pre, sc_trace_ctl_next, `ESR_SC_TRACE_CTL_RESET_VAL)
`ESR_WRITE_TYPE_WITH_RESERVED(sc_trace_ctl, esr_sc_trace_ctl_t')
// END autogenerated WRITE_SEQ
//////////////////////////////////////////////////////////////////////


//////////////////////////////////////////////////////////////////////
// BEGIN autogenerated PORT_ASSIGN - do not edit
// END autogenerated PORT_ASSIGN - do not edit
//////////////////////////////////////////////////////////////////////

//////////////////////////////////////////////////////////////////////
// BEGIN autogenerated TYPE_CONVERSIONS - do not edit
   //conversion functions for esr_sc_pipe_cache_ctl_t
   function automatic esr_sc_pipe_cache_ctl_t write_sc_pipe_cache_ctl;
   input [$bits(esr_sc_pipe_cache_ctl_t)-1:0] d;
   esr_sc_pipe_cache_ctl_t dd;
   esr_sc_pipe_cache_ctl_t ret;
   begin
      dd = esr_sc_pipe_cache_ctl_t'(d);
      ret.tag_mask = dd.tag_mask;
      ret.tag_mask_rsvd = '0; // RO field
      ret.set_mask = dd.set_mask;
      ret.set_mask_rsvd = '0; // RO field
      ret.set_size = dd.set_size;
      ret.set_size_rsvd = '0; // RO field
      ret.set_base = dd.set_base;
      ret.set_base_rsvd = '0; // RO field
      return ret;
   end
   endfunction
// END autogenerated TYPE_CONVERSIONS
//////////////////////////////////////////////////////////////////////

