#include "et_soc.h"
#include "board_conf.h"
#include "snp_common.h"
#include <assert.h>
#include "et_test_env.h" //autogenerated by Sting. Can be found under 'build' dir

std::set<unum_t> snp_get_active_local_shire_minions_set(CpuResource * cpu_resource) {
   std::set<unum_t> active_local_shire_minions;
   unum_t cpuid = snp_cpu_id(cpu_resource);
   unum_t local_shire = snp_get_shire_id(cpu_resource, cpuid);
   for (unum_t i = 0; i < BOARD_CONF.NUM_LCPUID_TO_PCPUID_MAP; i++) {
      unum_t tmp_shire = snp_get_shire_id(cpu_resource, i);
      if (tmp_shire == local_shire) {
         active_local_shire_minions.insert(i);
      }
   }
   return active_local_shire_minions;
}

unum_t get_idx_from_active_local_shire_minions(CpuResource * cpu_resource) {
   std::set<unum_t> active_local_shire_minions = snp_get_active_local_shire_minions_set(cpu_resource);
   unum_t cpuid = snp_cpu_id(cpu_resource);

   unum_t idx = 0;
   std::set<unum_t>::iterator it = active_local_shire_minions.begin();
   while (it != active_local_shire_minions.end()) {
      if ((*it) == cpuid) break;
      idx++;
      it++;
   }
   assert(it != active_local_shire_minions.end());
   return idx;
}

unum_t snp_get_local_active_harts(CpuResource * cpu_resource) {
   std::set<unum_t> active_local_shire_minions = snp_get_active_local_shire_minions_set(cpu_resource);
   return active_local_shire_minions.size();
}

std::set<unum_t> snp_get_active_shires_set(CpuResource * cpu_resource) {
    std::set<unum_t> active_shires;
    for (unum_t i = 0; i < BOARD_CONF.NUM_LCPUID_TO_PCPUID_MAP; i++) {
        unum_t tmp_shire = snp_get_shire_id(cpu_resource, i);
        active_shires.insert(tmp_shire);
    }
    return active_shires;
}

unum_t snp_get_shireid_from_set_idx(CpuResource * cpu_resource, unum_t lsid) {
    // This variant computes the shire id's and puts them in a std::set
    // This function is called from a snippet using a 'sting for loop'
    // The 'sting for loop' size is the number of active shires aka active_shires.size()
    // So 'lsid' is the index of the std::set
    // And this function returns the physical shire id corresponding to the std::set with idx lsid
    std::set<unum_t> active_shires = snp_get_active_shires_set(cpu_resource);
    std::set<unum_t>::iterator iter = active_shires.begin();
    std::advance(iter, lsid);
    return *iter;
}

unum_t snp_get_num_active_shires(CpuResource * cpu_resource) {
    std::set<unum_t> active_shires = snp_get_active_shires_set(cpu_resource);
    return active_shires.size();
}

std::set<unum_t> snp_get_soc_active_minions_set(CpuResource * cpu_resource) {
   std::set<unum_t> active_minions;
   for (unum_t i = 0; i < BOARD_CONF.NUM_LCPUID_TO_PCPUID_MAP; ++i) {
      unum_t phy_hartid = snp_get_phycpu(cpu_resource, i);
      unum_t phy_minionid = phy_hartid >> 1;
      active_minions.insert(phy_minionid);
   }
   return active_minions;
}

unum_t snp_get_soc_active_minions(CpuResource * cpu_resource) {
   std::set<unum_t> active_minions = snp_get_soc_active_minions_set(cpu_resource);
   return active_minions.size();
}

unum_t snp_get_phycpu_mask(CpuResource * cpu_resource, unum_t logcpu_mask)
{
    unum_t phycpu_mask = 0;
    for (unum_t i = 0; i < BOARD_CONF.NUM_LCPUID_TO_PCPUID_MAP; ++i) {
        phycpu_mask |= ((logcpu_mask >> i) & 1) << BOARD_CONF.LCPUID_TO_PCPUID_MAP[i];
    }
    return phycpu_mask;
}

unum_t snp_get_phycpu(CpuResource * cpu_resource, unum_t hartid)
{
   return (unum_t)BOARD_CONF.LCPUID_TO_PCPUID_MAP[hartid];
}

unum_t snp_get_phycpu_shire(CpuResource * cpu_resource, unum_t lcpuid) {
   // Get the physical CPU id but whithin the shire
   return snp_get_phycpu(cpu_resource, lcpuid) % 64;
}

unum_t snp_get_shire_id(CpuResource * cpu_resource, unum_t hartid)
{
   hartid = snp_get_phycpu(cpu_resource, hartid);
   return hartid >> 6;
}

unum_t snp_get_neigh_id(CpuResource * cpu_resource, unum_t hartid)
{
  hartid = snp_get_phycpu(cpu_resource, hartid);
  return (hartid >> 4) & 3;
}

unum_t snp_get_minion_id(CpuResource * cpu_resource, unum_t hartid)
{
   hartid = snp_get_phycpu(cpu_resource, hartid);
   return (hartid >> 1) & 0x7;
}

unum_t snp_get_global_minion_id(CpuResource * cpu_resource, unum_t hartid)
{
   hartid = snp_get_phycpu(cpu_resource, hartid);
   return (hartid >> 1) & 0xffff;
}

unum_t snp_get_thread_id(CpuResource * cpu_resource, unum_t hartid)
{
   hartid = snp_get_phycpu(cpu_resource, hartid);
   return hartid & 1;
}

unum_t snp_bit_set_in_mask(CpuResource * cpu_resource, unum_t bit, unum_t mask)
{
   return ((mask >> bit) & 1);
}

unum_t snp_setc(CpuResource * cpu_resource, unum_t mask)
{
   unum_t count = 0;
   while (mask) {
      if (mask & 1) count++;
      mask >>= 1;
   }
   return count;
}

unum_t snp_get_first_bit_set(CpuResource * cpu_resource, unum_t mask)
{
   unum_t ii = 0;

   if (mask == 0) return -1;
   while (((mask >> ii) & 1) == 0) ii++;
   return ii;
}

unum_t snp_get_odd_bits(CpuResource * cpu_resource, unum_t mask)
{
   unum_t odd_mask = 0;
   unum_t ii = 0;
   unum_t jj = 0;
   while (mask > 0) {
      if ((ii % 2) == 1) {
         odd_mask = odd_mask | ((mask & 1) << jj);
         jj++;
      }
      mask >>= 1;
      ii++;
   }
   return odd_mask;
}

unum_t snp_get_even_bits(CpuResource * cpu_resource, unum_t mask)
{
   unum_t even_mask = 0;
   unum_t ii = 0;
   unum_t jj = 0;
   while (mask > 0) {
      if ((ii % 2) == 0) {
         even_mask = even_mask | ((mask & 1) << jj);
         jj++;
      }
      mask >>= 1;
      ii++;
   }
   return even_mask;
}


unum_t snp_min(CpuResource * cpu_resource, unum_t a, unum_t b)
{
   return (a < b) ? a : b;
}

unum_t snp_get_hartid_biased(CpuResource * cpu_resource, unum_t nharts) {
   unum_t bias      = snp_urandrange_glbl(cpu_resource, 0, 27);
   unum_t rand_hart = snp_urandrange_glbl(cpu_resource, 0, nharts);
   unum_t rand_op   = snp_urandrange_glbl(cpu_resource, 0, 2);
   return snp_get_hartid_biased_from_rand(cpu_resource, nharts, bias, rand_hart, rand_op);
}

unum_t snp_get_hartid_biased_from_rand(CpuResource * cpu_resource, unum_t nharts, unum_t bias, unum_t rand_hart, unum_t rand_op) {

   if (nharts == 1) return 0;

   int hartid = rand_hart;

   // BIAS == 0: Must return an odd HART ID
   // BIAS == 1: Must return an even HART ID
   unum_t parity = (bias == 0) ? 1 : 0;

   //If rand_hart has a different parity, then we must force the value to the correct parity
   if ((rand_hart%2) != parity) {
      // To force the value to the correct parity, we have to increment or decrement
      // In order to be fair, we are choosing randomly whether we increment or decrement
      if (rand_op == 0) {
         hartid = rand_hart + 1;
         // If we are above the number of available CPUS, we have to decrement by 2
         if (hartid >= nharts) {
            hartid = hartid - 2;
         }
      }
      else {
         hartid = rand_hart - 1;
         // If the hartid is negative, we have to increment by 2
         if (hartid < 0) {
            hartid = hartid + 2;
         }
      }
   }
   assert(hartid >= 0);
   assert(hartid <  nharts);
   return (unum_t) hartid;
}

unum_t snp_gen_harts_mask(CpuResource * cpu_resource, unum_t num_cpus) {

  unum_t i = 0;
  unum_t idhartmask = 0;
  
  for (i = 0; i < num_cpus; i++) {
    idhartmask |= (1<<i);
  }
  
  return idhartmask;
}

// This function returns 1 if 'cpuid' is the minion with lower ID between the
// active minions of the same shire
unum_t snp_is_min_shire(CpuResource * cpu_resource, unum_t cpuid)
{
    unum_t hart_id = snp_get_phycpu(cpu_resource, cpuid);
    unum_t shire_id = snp_get_shire_id(cpu_resource, cpuid);
    unum_t min_id = 2048;
    for (unum_t i = 0; i < BOARD_CONF.NUM_LCPUID_TO_PCPUID_MAP; i++) {
        unum_t tmp_shire = snp_get_shire_id(cpu_resource, i);
        if (shire_id == tmp_shire) {
            unum_t tmp_hart = snp_get_phycpu(cpu_resource, i);
            min_id = (tmp_hart < min_id) ? tmp_hart : min_id;
        }
    }
    if (min_id == hart_id) return 1;
    return 0;
}

unum_t snp_get_minion_mask(CpuResource * cpu_resource, unum_t cpuid)
{
    unum_t hart_id = snp_get_phycpu(cpu_resource, cpuid);
    unum_t minion_id = hart_id >> 1;
    return (1 << minion_id);
}

unum_t snp_get_esr_addr_coop_mode (CpuResource * cpu_resource, unum_t cpuid) {
   unum_t base_addr = 0x80740290;
   unum_t shire_id = snp_get_shire_id(cpu_resource, cpuid);

   unum_t bias = snp_urandrange(cpu_resource, 0, 4);
   shire_id = (bias == 0) ? 0xffffffff : shire_id;

   unum_t ret = snp_set_bits(cpu_resource, base_addr, 29, 22, shire_id);

   return ret;
}

unum_t snp_get_num_harts_local_shire(CpuResource * cpu_resource, unum_t cpuid) {
   unum_t shire_id = snp_get_shire_id(cpu_resource, cpuid);
   unum_t num_harts = 0;
   for (unum_t i = 0; i < BOARD_CONF.NUM_LCPUID_TO_PCPUID_MAP; i++) {
      unum_t tmp_shire = snp_get_shire_id(cpu_resource, i);
      if (shire_id == tmp_shire) {
         num_harts++;
      }
   }
   return num_harts;
}

unum_t snp_get_mprot_base(CpuResource * cpu_resource, unum_t mprot) {
   if (ET_TEST_ENV.SECURE_MEMORY == 1) {
      mprot = mprot | 0x40; // bit[6] Enables SecureMemory
      // OS_REGION: iff ~mprot[3] then RW in M/S-mode and RWX in U-mode
      mprot = snp_set_bits(cpu_resource, mprot, 3, 3, 0);
   }
   else {
      // bit[6] Disable SecureMemory
      mprot = snp_set_bits(cpu_resource, mprot, 6, 6, 0);
   }
   return mprot;
}

unum_t snp_get_rand_mprot(CpuResource * cpu_resource) {
   unum_t mprot = snp_urandrange(cpu_resource, 0, 64);
   return snp_get_mprot_base(cpu_resource, mprot);
}

unum_t snp_get_tensor_rand_mprot(CpuResource * cpu_resource) {
   unum_t mprot = snp_urandrange(cpu_resource, 16, 64);
   return snp_get_mprot_base(cpu_resource, mprot);
}

uint32_t snp_get_unpr_fregs_mask(CpuResource * cpu_resource) {
   // FUTURE: this could be done with constexpr and template
   const unum_t nfregs = 14;
   const unum_t unpr_fregs[nfregs] = {0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 28, 29};
   uint32_t unpr_mask = 0;
   for (int i = 0; i < nfregs; i++) unpr_mask |= (1 << unpr_fregs[i]);
   return unpr_mask;
}
